### ISSUE TITLE
npm listed version and viewed version do not match (5.2.16/5.2.17)

### ISSUE THREAD

**Issue by cengageLucas** [postcss/postcss#1005]
I'm having install issues since yesterday with the following output

npm ERR! No compatible version found: postcss@^5.2.17

I notice that the npm site shows 5.2.17 as the newest version, but npm view only shows up to 2.1.16.

**Comment by michael-ciniawsky** [comment]
@cengageLucas Try 

```bash
sudo rm -rf ./node_modules && sudo npm cache clean && sudo npm i  
```

otherwise it's an npm bug :)

**Comment by cengageLucas** [comment]
Thanks. I got ahead of myself, and I think it's a mirroring issue. Main npm doesn't appear to have this problem, just me. :)
