### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by solodynamo** [postcss/postcss#1013]
Repo should have some contributing guidelines for new people who would like to contribute , I would like to add initial CONTRIBUTING.md which can be modified later.

**Comment by ai** [comment]
Sure. I suggest to focus on most popular contribution types, to be the most useful (and don't copy Contribution doc from other project).

What contribution types is the most popular here? You can see PR.

**Comment by solodynamo** [comment]
Okay will create one after reviewing the PR's flow.

**Comment by abhigyank** [comment]
If this isn't assigned, I would like to work on this.

**Comment by ai** [comment]
Sure. I think it will be good to start from analysis, rather than copy standard contribution docs.

How can new contributors help?

What is the most popular PR?

What could be a main problems with them?

**Comment by abhigyank** [comment]
@ai could I be assigned to this?

**Comment by ai** [comment]
@abhigyank sure. You are on it.

**Comment by hzlmn** [comment]
Any progress on it? I can create `WIP` PR and we can discuss about structure etc...

**Comment by ai** [comment]
@hzlmn no progress. If you want your should start from discussing structure.

**Comment by ai** [comment]
https://github.com/postcss/postcss/blob/master/CONTRIBUTING.md
