### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by LuisKrotz** [postcss/postcss#1019]
This error is occurring on many scripts since the last update from postCSS.
Even with nodejs and npm on the last version.
```
[17:13:53] PostCSS
✖ Processing public/css/app.css
[TypeError: this is not a typed array.]
[17:13:53] Concat
[17:13:53] vendor.min.css
[17:13:53] Done
```

**Comment by h0tc0d3** [comment]
PostCSS don't use typed arrays. What postcss plugins and task manager you use?

**Comment by ai** [comment]
Thanks for report. I think you have some conflict between different tools.

You need to show your build tool config and error stacktrace.

**Comment by LuisKrotz** [comment]
Thanks for the replay, I hope this helps, i'll send more info as soon as I got to the project with this error again.


### package.json
Working
```
{
  "scripts": {
    "build:styles": "./tasks/styles.sh",
    "build:scripts": "./tasks/scripts.sh",
    "build": "npm run build:styles && npm run build:scripts",
    "watch:jslint": "find resources/assets/js -type f | entr jslint /_ --color",
    "watch:scripts": "find resources/assets/js -type f | entr npm run build:scripts",
    "watch:styles": "find resources/assets/sass -type f | entr npm run build:styles",
    "watch": "npm run watch:styles && npm run watch:scripts"
  },
  "devDependencies": {
    "autoprefixer": "*",
    "css-mqpacker": "*",
    "jslint": "^0.10.1",
    "node-sass": "^4.5.2",
    "postcss-cli": "^3.2"
  }
}
```

Not Working
```
{
  "scripts": {
    "build:styles": "./tasks/styles.sh",
    "build:scripts": "./tasks/scripts.sh",
    "build": "npm run build:styles && npm run build:scripts",
    "watch:jslint": "find resources/assets/js -type f | entr jslint /_ --color",
    "watch:scripts": "find resources/assets/js -type f | entr npm run build:scripts",
    "watch:styles": "find resources/assets/sass -type f | entr npm run build:styles",
    "watch": "npm run watch:styles && npm run watch:scripts"
  },
  "devDependencies": {
    "autoprefixer": "*",
    "css-mqpacker": "*",
    "jslint": "^0.10.1",
    "node-sass": "^4.5.2",
    "postcss-cli": "*"
  }
}
```


## ALL WORKING with ^3.2
-------------------------------------------------------------------------
### js.list

```
site:public/vendor/js/{jquery-3.2.1.min.js,materialize.min.js}:public/js/vendor.min.js
site:resources/assets/js/app.js:public/js/app.min.js
```

### postcss.list

```
site:public/css/app.min.css:public/css/app.css
```
### scss.list

```
site:resources/assets/materialize/sass/materialize.scss:public/css/materialize.css
site:resources/assets/sass/app.scss:public/css/app.css
```

### concat.list
```
site:public/vendor/css/{normalize.min.css,materialize.min.css}:public/css/vendor.min.css
```

---------------------------------------------------------------------
### scripts.sh

```
#!/bin/bash

# USAGE
# ./tasks/scripts.sh

FILTER=$(test $# -eq 1 && echo "^$1:" || echo "")

echo "["$(date +%H:%M:%S)"] Concat"

cat tasks/js.list |
grep "$FILTER" |
cut -d: -f2,3 |
while read line
do
    val=($(echo "$line" | tr : "\n"))
    eval cat ${val[0]} > ${val[1]}
done


if test "x$1" = "xsite" || test "x$1" = "x"; then
    echo "["$(date +%H:%M:%S)"] app.min.js"
    cat public/js/app.min.js > public/js/app.js

fi

echo "["$(date +%H:%M:%S)"] Done"
```

### styles.sh

```
#!/bin/bash

FILTER=$(test $# -eq 1 && echo "^$1:" || echo "")

echo "["$(date +%H:%M:%S)"] Sass"

cat tasks/scss.list |
grep "$FILTER" |
cut -d: -f2,3 |
tr : "\n" |
xargs -n2 node-sass

echo "["$(date +%H:%M:%S)"] PostCSS"

cat tasks/postcss.list |
grep "$FILTER" |
cut -d: -f2,3 |
tr : "\n" |
xargs -n2 postcss -u autoprefixer --autoprefixer.browsers " last 2 version" -u css-mqpacker -o

echo "["$(date +%H:%M:%S)"] Concat"

cat tasks/concat.list |
grep "$FILTER" |
cut -d: -f2,3 |
while read line
do
    val=($(echo "$line" | tr : "\n"))
    eval cat ${val[0]} > ${val[1]}
done


if test "x$1" = "xsite" || test "x$1" = "x"; then
    echo "["$(date +%H:%M:%S)"] vendor.min.css"
    cat public/css/vendor.min.css > public/css/vendor.css

fi

echo "["$(date +%H:%M:%S)"] Done"
```

**Comment by LuisKrotz** [comment]
```
I0509 18:59:04.622311 1 sti.go:586] >>> Build tasks
I0509 18:59:04.979568 1 sti.go:586] 
I0509 18:59:04.979595 1 sti.go:586] > @ build:scripts /opt/app-root/src
I0509 18:59:04.979602 1 sti.go:586] > ./tasks/scripts.sh
I0509 18:59:04.979607 1 sti.go:586] 
I0509 18:59:04.993649 1 sti.go:586] [18:59:04] Concat
I0509 18:59:05.040313 1 sti.go:586] [18:59:05] ALL.JS
I0509 18:59:05.040841 1 sti.go:586] [18:59:05] WHERE.VENDOR.JS
I0509 18:59:05.042110 1 sti.go:586] [18:59:05] Done
I0509 18:59:05.476719 1 sti.go:586] 
I0509 18:59:05.477061 1 sti.go:586] > @ build:styles /opt/app-root/src
I0509 18:59:05.477084 1 sti.go:586] > ./tasks/styles.sh
I0509 18:59:05.477090 1 sti.go:586] 
I0509 18:59:05.487401 1 sti.go:586] [18:59:05] Less
I0509 18:59:18.322312 1 sti.go:586] [18:59:18] PostCSS
I0509 18:59:19.934319 1 sti.go:593] ✖ Processing public/assets/css/main.css
I0509 18:59:19.936675 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:22.013189 1 sti.go:593] ✖ Processing public/assets/css/internals.css
I0509 18:59:22.013245 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:23.610931 1 sti.go:593] ✖ Processing public/assets/css/symphony.css
I0509 18:59:23.616205 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:24.645358 1 sti.go:593] ✖ Processing public/assets/css/where.css
I0509 18:59:24.648330 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:25.857180 1 sti.go:593] ✖ Processing public/assets/css/about.css
I0509 18:59:25.860179 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:26.993166 1 sti.go:593] ✖ Processing public/assets/css/hotsites.css
I0509 18:59:26.995514 1 sti.go:593] [TypeError: this is not a typed array.]
I0509 18:59:27.009483 1 sti.go:586] [18:59:27] Done

I0509 18:59:27.021639 1 sti.go:586] >>> DONE
```

Output of the same script but in another project, this project uses less as preprocessor.

**Comment by ai** [comment]
Can you run PostCSS just in console? You have big build system. Try to find smallest command. There you will be able to get stacktrace.

For example, try to start from 

```
xargs -n2 postcss -u autoprefixer --autoprefixer.browsers " last 2 version" -u css-mqpacker -o
```

Run it on files manually.

**Comment by LuisKrotz** [comment]
I find out that the problem only occurs with 
```
npm info using npm@3.5.2
npm info using node@v4.2.6
```

**Comment by ai** [comment]
Without a stacktrace I can't help you.

**Comment by ai** [comment]
You have very complex build system. Try to make it easier and get debug information.

**Comment by portstrom** [comment]
```
toBase64(str) {
    if ( Buffer ) {
        return Buffer.from ?
            Buffer.from(str).toString('base64') :
            new Buffer(str).toString('base64');
    } else {
        return window.btoa(unescape(encodeURIComponent(str)));
    }
}
```
https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L125

This code is calling the function `Buffer.from` with an argument that is a string. In Node 4.2.6 this throws an exception.

```
$ node -v
v4.2.6
$ node
> Buffer.from("")
TypeError: this is not a typed array.
```

The correct way to do it is `new Buffer(str)`:

```
> new Buffer("example").toString("base64")
'ZXhhbXBsZQ=='
```

**Comment by h0tc0d3** [comment]
@portstrom `new Buffer()` marked as deprecated on latest versions of nodejs. I wrote this piece of code and @ai was decided that postcss will not support old version nodejs. People wanted to exclude `new Buffer()` code.

**Comment by ai** [comment]
@h0tc0d3 what Node.js version, BTW? < 4?

**Comment by h0tc0d3** [comment]
@ai I do't remember. Something was discussed in the gitter and some in pull request. @michael-ciniawsky review this code and also @ben-eb in gitter said his opinion.

**Comment by portstrom** [comment]
@h0tc0d3 If you are not going to support Node 4.2.6 because it requires using the `Buffer` constructor, you should update `package.json` to say it's not supported. Currently it says Node 4.0.0 and above are supported.
https://github.com/postcss/postcss/blob/master/package.json#L6

**Comment by ben-eb** [comment]
I thought we were still supporting Node 4 until it goes out of LTS? That's April 2018. 😄

I can't remember what I wrote in Gitter but I don't think I advised that we drop Node 4 support. If anything, it would have been 0.12 that I was recommending to drop seeing as it is end of lifed.

https://github.com/nodejs/LTS

**Comment by ai** [comment]
We still support Node.js 4.

@portstrom strange that our tests didn’t fall in Node.js 4. Do you have any ideas?

**Comment by portstrom** [comment]
It works in Node 4.8.4 but not 4.2.6.

**Comment by ai** [comment]
We support only latest 4.x version 😄

**Comment by portstrom** [comment]
According to `package.json`, you support 4.0.0. This number should be increased.
https://github.com/postcss/postcss/blob/master/package.json#L6

**Comment by ai** [comment]
I added old `new Buffer(str)` support together with `Buffer.from`. So I think now we support both. https://github.com/postcss/postcss/commit/88673ab56a19c426773d68467033d9b2802bfb54

**Comment by portstrom** [comment]
No, you don't support both. https://github.com/postcss/postcss/commit/88673ab56a19c426773d68467033d9b2802bfb54 is the commit that caused this issue. If you revert it, it will solve the issue.

**Comment by ai** [comment]
@portstrom oops :(. Can you explain how it broke? It seems normal for me.

**Comment by portstrom** [comment]
I explained in my first message.
https://github.com/postcss/postcss/issues/1019#issuecomment-312423358

`Buffer.from` can't be used with a string argument in node 4.2.6. It throws an exception.

**Comment by portstrom** [comment]
It seems you already solved it, looking at https://github.com/postcss/postcss/issues/1052
