### ISSUE TITLE
Add PostCSS development docs (architecture, env setup, etc.)

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss#1020]
Hello, as one who recently contributed small patches to `postcss`, I noticed some improvement factors about project docs. 

As a user it's pretty clear how to setup and work with `postcss`, docs are pretty good and extensive. From the other side, if i am new to project i could feel lack of docs about things like project architecture, how to setup dev env, maybe FAQs about env setup (for development), etc. 

My propose is to add this kind of things as a separate `development docs` , that potentially can increase number of new contributors. 

I really like how React and Relay docs organized as a reference for example.

If it make sense to you, I could start writing some parts.

**Comment by ai** [comment]
Totally agree. But this issue is dublicate for  https://github.com/postcss/postcss/issues/1013

**Comment by hzlmn** [comment]
@ai Yes, I saw that issue, but it not fully the same thing it's kind like an addition to that propose of including `contributing.md` to the project, but rather focusing on docs side of `postcss` internals for example. That's why i created separate issue.

**Comment by ai** [comment]
Contributing is a development docs too. Also we need same analysis for both tasks.

We don't need just internal description. First we need to understand what is main PR, what is main questions.
