### ISSUE TITLE
Leading _ in classnames

### ISSUE THREAD

**Issue by Diokuz** [postcss/postcss#1023]
Im struggling with `postcss` because it removes leading underscore character in my classnames. For example (pseudocode):

```css
._x {
  color: red;
}
```

```jsx
import s from './css.css';

<div className={s._x}> // undefined, {s.x} works
```

So, looks like it is works like that for the last three years: https://github.com/postcss/postcss/blob/d06be7280469a79865ef9f6ed8bdb337db8523db/lib/parser.es6#L209-L212

But somehow it breaks only when `css-loader` works. When `postcss-loader` works – it doesnt happen)

Why you forbid leading underscores in classNames?
Or maybe all the magic happens in `node.raws.before` and `css-loader` doesnt handle it properly?

I use `React` `webpack@2`, `postcss@5.2.17` `css-loader@0.28.2`

css-loader issue https://github.com/webpack-contrib/css-loader/issues/541

**Comment by ai** [comment]
That code in parser is only for declaration.

Are you sure, that it is PostCSS, because you show this problem on CSS Modules example, where CSS Modules can do some magic with classnames.

Can you try to check AST by `postcss.parse(css)`?

**Comment by michael-ciniawsky** [comment]
`css-loader` compiles the [style] exports (e.g `camelCase`) it's not a PostCSS issue, reopen in webpack-contrib/css-loader please

**Comment by Diokuz** [comment]
```
postcss.parse('.src⁄x___x {\n  color: red;\n}\n:export {\n  _x: src⁄x___x;\n}\n').nodes[1]
```
↓↓↓
```
Rule {
  raws: { before: '\n', between: ' ', semicolon: true, after: '\n' },
  type: 'rule',
  nodes: 
   [ Declaration {
       raws: [Object],
       type: 'decl',
       parent: [Circular],
       source: [Object],
       prop: 'x',
       value: 'src⁄x___x' } ],
  parent: 
   Root {
     raws: { semicolon: false, after: '\n' },
     type: 'root',
     nodes: [ [Object], [Circular] ],
     source: { input: [Object], start: [Object] } },
  source: 
   { start: { line: 4, column: 1 },
     input: 
      Input {
        css: '.src⁄x___x {\n  color: red;\n}\n:export {\n  _x: src⁄x___x;\n}\n',
        id: '<input css 2>' },
     end: { line: 6, column: 1 } },
  selector: ':export' }
```

So, `props` is `x`

**Comment by Diokuz** [comment]
After that `css-loader` just do that:

```
exports[decl.prop] = decl.value;
```

and I lose `_`

I just trying to understant what happens in postcss) Why `_` lost in `prop`.
I understant that it is rather `css-loader` problem.

**Comment by Diokuz** [comment]
If I print `decl`:
```js
decl Declaration {
  raws: { before: '\n  _', between: ': ' },
  type: 'decl',
...
```

So, should it be like

```js
exports[decl.raws.before.trim() + decl.prop] = decl.value;
```

?

How to get proper classname there?

**Comment by michael-ciniawsky** [comment]
This is already ICSS (`:export`), does `._className { color: red;  }` without any plugins etc also produce this issue ?

**Comment by Diokuz** [comment]
Without `:export` there is no `prop` key.

The question is: why you remove `_` from `prop`, and what to advise `css-loader` maintainers? Theirs code looks logical, and `decl.raws.before.trim() + decl.prop` looks wired.

**Comment by ai** [comment]
@Diokuz you ask about declaration property `_x: black;` it about class name `._x { }`. Because in first comment you show class example, but in AST show example work property.

**Comment by TrySound** [comment]
@ai css-modules plugins first converts all to icss which is looks like this
```css
:export {
  localClass: 'globalClass--hash'
}
```
And then loader extracts all info from this.

**Comment by TrySound** [comment]
We can concat prefixes on extracting only in one place. Nothing wrong with it.

**Comment by Diokuz** [comment]
Well, I use `postcss-loader` first, and it creates `:export` stuff. Then I use `css-loader` only to create js objects, but uses `postcss` for that. Here is config https://github.com/webpack-contrib/css-loader/issues/541

Should `postcss` be able to parse `ICSS`, or maybe that is a problem?

**Comment by TrySound** [comment]
@Diokuz I do ICSS utilities which will be used in all loaders and behave in the same way.
https://github.com/css-modules/icss-utils
So this will be fixed.

**Comment by ai** [comment]
I will close it because it is not related to PostCSS.

PostCSS keeps _ in class. PostCSS removes leading _ from declaration properties, because it is illegal symbol there.

**Comment by michael-ciniawsky** [comment]
> I do ICSS utilities which will be **used in all loaders** and behave in the same way.

What (ノಠ益ಠ)ノ彡┻━┻ ?  🙃 😛 :D

**Comment by TrySound** [comment]
I mean css-loader, css-modules-parser, core loader

**Comment by michael-ciniawsky** [comment]
> Well, I use postcss-loader first, and it creates :export stuff.

@Diokuz That's likely the issue, you can't _really_ use `css-modules` with `postcss-loader` yet [#227](https://github.com/postcss/postcss-loader/issues/227)

@TrySound Yup, I'm already 'stalking' all the cssm repos :D

**Comment by Diokuz** [comment]
> you can't really use css-modules with postcss-loader yet #227

Haha, thats funny) Thanks anyway)

> PostCSS keeps _ in class. PostCSS removes leading _ from declaration properties, because it is illegal symbol there.

@ai does `postcss` supports `ICSS` syntax?

**Comment by ai** [comment]
@Diokuz of course, CSS Modules uses PostCSS to parse CSS, so PostCSS by default support it.

**Comment by Diokuz** [comment]
@ai then I still didn't get it, why it is considered as a normal behaviour to drop leading `_` in classnames inside `:export`?

**Comment by ai** [comment]
Nope. Normal behavior is to drop _ only in property names. If you have different wrong behavior with selectors, show it with PostCSS API example (you shown selector problem only with CSS Modules, with PostCSS you shown properties behavior which is correct).
