### ISSUE TITLE
Better warning on function as syntax

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1024]
https://github.com/AleshaOleg/postcss-sass/issues/8

**Comment by ben-eb** [comment]
These might be good to look into:

* https://github.com/facebook/jest/tree/master/packages/jest-validate
* https://github.com/epoberezkin/ajv

**Comment by hzlmn** [comment]
Hello, is it still relevant, can look on it if so?

**Comment by ai** [comment]
Still relevant. and fix will be easy :)

**Comment by hzlmn** [comment]
Yeah, i was just thinking about some kind of general options validations based on something like `json` schema . Not only for this case. What do you think about it?

**Comment by ai** [comment]
We need good error messages. Not `passed [function] instead of [object]`, but `Seems like you use parser as a syntax. Replace syntax option to parser.`

**Comment by hzlmn** [comment]
Ok, got it.
