### ISSUE TITLE
Module build failed: Error: [object Promise] is not a PostCSS plugin

### ISSUE THREAD

**Issue by martinyeh** [postcss/postcss#1025]
My webpack.config.js is below:
```
module.exports = {
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname,
    publicPath: '/',
    filename: 'bundle.js'
  },
  node: {
    fs: "empty"
},
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: { importLoaders: 1 }
          },
           'postcss-loader'
        ]
      }
    ],
    loaders: [{
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        plugins: ['transform-decorators-legacy' ],
        presets: ['react', 'es2015', 'stage-1']
      }
    },{
      test: /\.css$/,   // *.css but not *.theme.css
      loader: `${STYLE_LOADER}?insertAt=top!${CSS_LOADER}!postcss-loader`,
      exclude: /node_modules/,
    }],
  },
  postcss: function plugins(bundler) {
    return [
      require('postcss-import')({ addDependencyTo: bundler }),
      require('postcss-mixins')(),
      require('postcss-cssnext')({ autoprefixer: AUTOPREFIXER_BROWSERS }),
      require('postcss-nested')(),
      require('postcss-load-config')(),

    ];
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devServer: {
    historyApiFallback: true,
    contentBase: './'
  }
};
```

After I run, npm start, I got this error:
ERROR in ./~/css-loader!./~/postcss-loader!./style/style.css
Module build failed: Error: [object Promise] is not a PostCSS plugin
    at Processor.normalize (D:\workspaces\DetailPage\node_modules\postcss\lib\processor.js:145:15)
    at new Processor (D:\workspaces\DetailPage\node_modules\postcss\lib\processor.js:51:25)
    at postcss (D:\workspaces\DetailPage\node_modules\postcss\lib\postcss.js:73:10)
    at Object.module.exports (D:\workspaces\DetailPage\node_modules\postcss-loader\index.js:42:5)
 @ ./style/style.css 5:14-114

**Comment by michael-ciniawsky** [comment]
Please open issue with `postcss-loader` at `postcss-loader` repo :D. webpack 2 ? postcss-loader v?

**Comment by michael-ciniawsky** [comment]
```
  postcss: function plugins(bundler) {
    return [
      require('postcss-import')({ addDependencyTo: bundler }),
      require('postcss-mixins')(),
      require('postcss-cssnext')({ autoprefixer: AUTOPREFIXER_BROWSERS }),
      require('postcss-nested')(),
-      require('postcss-load-config')(), // postcss-loader already implements this interally, 
       // it's not a plugin (likely where the Error comes from)
    ];
```

**Comment by michael-ciniawsky** [comment]
If you want to use `postcss-load-config` make the follwoing changes

**webpack.config.js**
```
-  postcss: function plugins(bundler) {
-    return [
-      require('postcss-import')({ addDependencyTo: bundler }),
-      require('postcss-mixins')(),
-      require('postcss-cssnext')({ autoprefixer: AUTOPREFIXER_BROWSERS }),
-      require('postcss-nested')(),
-      require('postcss-load-config')(),
-    ];
```

**postcss.config.js** (placed in './' (Root) at best)
```js
const vars =  {
   'color': 'red'
}

const options =  {
   autoprefixer: {...options}
}

module.exports = (ctx) => ({
     plugins: [
      require('postcss-import')()
      require('postcss-mixins')(),
      require('postcss-cssnext')({ 
        variables: vars
        autoprefixer: options.autoprefixer 
      }),
      require('postcss-nested')(),
      require('postcss-load-config')(),
    ]
})
```

Otherwise just remove `postcss-load-config` from `webpack.config.js`

**Comment by martinyeh** [comment]
Thanks, it resolved!

**Comment by zhe-he** [comment]
@michael-ciniawsky 
hello.  When I upgraded from version 1.3.0 to version 2.0.5.
``
--- webpack.config.js
var loaders = [
    {loader: 'css-loader'},
    {
        loader: 'postcss-loader',
        options: {
            config: 'config/postcss.config.js'
        }
    }
];
...
{
                test: /\.(scss|sass)$/,
                exclude:/node_modules/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: loaders.concat({loader: 'sass-loader'})
                })
            },

--- config/postcss.config.js
const autoprefixer = require('autoprefixer')
module.exports = {
    plugins: [
        autoprefixer({ browsers: ['last 9 versions'], cascade: false })
    ]
}
``
---

``ERROR in ./~/_css-loader@0.28.3@css-loader!./~/_postcss-loader@2.0.5@postcss-loader/lib?{"config":"config/postcss.config.js"}!./~/_sass-loader@6.0.5@sass-loader/lib/loader.js!./css/credentials.scss
    Module build failed: Validation Error

    PostCSS Loader Invalid Options

    options.config should be object``


***  ***

**Comment by zhe-he** [comment]
sorry.
I should go to postcss-loader.
