### ISSUE TITLE
There are mistakes in postcss.d.ts 

### ISSUE THREAD

**Issue by hidekatsu-izuno** [postcss/postcss#1027]
Maybe There are mistakes in postcss.d.ts.

1.  A Plugin<T> must not be extend a Transformer<T>. Because the function definition need to be "(opts?: T): Transformer" unlike "(root: Root, result?: Result): void | Function | any".
2. The Plugin<T>'s process function must be pluginOptions in addition to processOptions.

**Comment by ai** [comment]
/cc @jedmao

(But I will have flight to Cuba today, I will not have internet there, so we will fix it only after 2 weeks)

**Comment by ai** [comment]
I think it was fixed
