### ISSUE TITLE
Input Error: Did not receive any STDIN  Ask Question

### ISSUE THREAD

**Issue by dschinkel** [postcss/postcss#1029]
Not sure why this is happening, when I yarn run this I get 

`✖ Input Error: Did not receive any STDIN`

**package.json**

`"css": "postcss -c postcss-options.json"`

**postcss-options.json**

```
{
  "use": ["precss"],
  "input": "./src/css/style.css",
  "output": "./src/css/final.css",
  "local-plugins": true
}
```
I'm going off of http://www.competa.com/blog/handle-postcss-with-plugins-with-npm-scripts

**Comment by TrySound** [comment]
@dschinkel Please move this issue to cli project
https://github.com/postcss/postcss-cli

**Comment by michael-ciniawsky** [comment]
That's the old config syntax `postcss-cli =< v2.0.0` used. See the [Migration Guide](https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2-to-v3) for more info and please clode the issue here. Open a new issue in postcss/postcss-cli if still regressions

**Comment by dschinkel** [comment]
thanks, will do!
