### ISSUE TITLE
API: mock source.input.file

### ISSUE THREAD

**Issue by sandrina-p** [postcss/postcss#1031]
I need to prevent my plugin to run on css files inside `/node_modules`. 
For that I check for the value of `rule.source.input.file`.
 
```js        
root.walkDecls(rule => {
    if (rule.source.input.file && rule.source.input.file.indexOf('/node_modules') > 0) {
       return false;
    }
   
    // ...
}
```

Now I want to do a Jest test with it, but the `input.file` is always `undefined`. 

How do I mock it?

**Comment by ai** [comment]
Check that you pass any `from` option to PostCSS in your tests.

**Comment by sandrina-p** [comment]
Sorry I dont understand what you mean... Can you explain better?

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Thu, Jun 1, 2017 at 17:50, Andrey Sitnik <notifications@github.com> wrote:
Check that you pass any from option to PostCSS in your tests.

**Comment by ai** [comment]
Can you show your tests?

**Comment by sandrina-p** [comment]
Sure, here is the link of the PR with the changeshttps://github.com/sandrina-p/postcss-start-to-end/pull/9/files#diff-168726dbe96b3ce427e7fedce31bb0bcR157



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Thu, Jun 1, 2017 at 18:12, Andrey Sitnik <notifications@github.com> wrote:
Can you show your tests?

**Comment by sandrina-p** [comment]
And this is the file with all the tests https://github.com/sandrina-p/postcss-start-to-end/blob/feature/add-option-ignoreNodeModules/index.test.js [https://github.com/sandrina-p/postcss-start-to-end/blob/feature/add-option-ignoreNodeModules/index.test.js]

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Thu, Jun 1, 2017 at 18:14, sandrin4pereir4@gmail.com <sandrin4pereir4@gmail.com> wrote:
Sure, here is the link of the PR with the changeshttps://github.com/sandrina-p/postcss-start-to-end/pull/9/files#diff-168726dbe96b3ce427e7fedce31bb0bcR157



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.2&source=email_footer_2]
On Thu, Jun 1, 2017 at 18:12, Andrey Sitnik <notifications@github.com> wrote:
Can you show your tests?

**Comment by ai** [comment]
Add this code (replace similar code in the to of test file).

```
postcss([ plugin(opts) ]).process(input, { from: "test/path" })
```

**Comment by sandrina-p** [comment]
Ah awesome! I will try it out and then comment back 😊

**Comment by sandrina-p** [comment]
Hey [it worked](https://github.com/sandrina-p/postcss-start-to-end/pull/9/files#diff-275a6743b2ff7d68e3d76f3462691716R417)!

Thanks 🎉
