### ISSUE TITLE
Selectors and Values parsing

### ISSUE THREAD

**Issue by iddan** [postcss/postcss#1035]
I was wondering: if PostCSS creates an AST of CSS shouldn't it also parse selectors and values? I've seen incredible work towards it in postcss/postcss-selector-parser and TrySound/postcss-value-parser and just wanted to make sure why isn't it part of the main parser.

**Comment by TrySound** [comment]
@iddan In the beginning it was for performance reasons. Now we have a problem like custom syntax. If we will parse all stuff then we won't be able to introduce a lot of syntax sugar which is made postcss so popular and useful.

**Comment by iddan** [comment]
I know this is a problem @babel face as well. But as I see it custom syntax extensions should be registered in the parser level and code modifiers later

**Comment by TrySound** [comment]
It's different parser architecture which can break all existing stuff.

**Comment by iddan** [comment]
Not everything: only custom syntax plugins. I think it can be in a future major release as it is a reasonable breaking change.

**Comment by TrySound** [comment]
Well, the discussion is here FYI.
https://github.com/postcss/postcss/issues/754

**Comment by ai** [comment]
We want this too and will add it to some future version.
