### ISSUE TITLE
Getting UnhandledPromiseRejectionWarning on walk() promise

### ISSUE THREAD

**Issue by gespinha** [postcss/postcss#1036]
Hi,

While building the tests for a plugin with `mocha` and `chai`, I'm getting an "UnhandledPromiseRejectionWarning: Unhandled promise rejection" error after running the following inside a test promise:

```
function process(input, options){
  return postcss().use(plugin(options)).process(input);
}

process(file, options).then(result => {
  result.root.walk(rule => {
    expect(true).to.equal(true);
  });
});
```
I've noticed the problem is related to the `walk()` promise, but can't figure what is missing. Can anyone help me identify the issue?

Thanks!

**Comment by ai** [comment]
`UnhandledPromiseRejectionWarning` just hide other real issue. Change:

```js
process(file, options).then(result => {
  …
})
```

to:

```js
process(file, options).then(result => {
  …
}).catch(err => {
  throw err;
})
```

**Comment by gespinha** [comment]
Thanks! If the expected error is always the actual failed test, then the `catch()` will always be the same, right?

Is there any test lib that allows me not to declare `catch()`?

**Comment by ai** [comment]
Jest and AVA allows to not declare `catch()`, but you must to return Promise from test. Check PostCSS plugin boilerplate: https://github.com/postcss/postcss-plugin-boilerplate/blob/master/index.test.js

**Comment by gespinha** [comment]
Will do! Thank you!
