### ISSUE TITLE
Error when piping over a certain amount of data

### ISSUE THREAD

**Issue by michaelalhilly** [postcss/postcss#1037]
I encountered an error when piping data from node-sass to postcss that seems to be due to a limit of some sort. Here is the npm script I was running:

```
"build:css": "node-sass src/css/main.scss | postcss --u autoprefixer -b 'last 2 versions' > dist/css/main.css",
"postbuild:css": "cleancss --source-map --output dist/css/main.min.css dist/css/main.css"

```
I had to change the process to this to get it working:

```
"build:css": "node-sass src/css/main.scss > dist/css/main.css",
"postbuild:css": "postcss dist/css/main.css --u autoprefixer -b 'last 2 versions' | cleancss --source-map --output dist/css/main.min.css"
```

I've got about 50 SCSS modules that generate main.css, which is a little over 2,800 lines and 66KB. I'm not sure if this issue is related to number of lines, css nesting, file size, piping buffer limits, or something else. The result was postcss was not processing any data beyond a specific point (line 2609 in my case) which generated whatever error occurred on the last line due to the missing data.

The fix works fine and it actually make more sense to generate the file first.

Thought it might be helpful to document this limitation here.

**Comment by TrySound** [comment]
@michaelalhilly I guess it's related to [postcss-cli](https://github.com/postcss/postcss-cli) project

**Comment by ai** [comment]
Yeap, ask postcss-cli.

**Comment by michaelalhilly** [comment]
Agreed. I posted the issue [there](https://github.com/postcss/postcss-cli/issues/140). Thanks for the suggestion.
