### ISSUE TITLE
TypeScript declaration file enhancement.

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss#1038]
Hello, sir.

Currently,` ts` declaration file only includes consumer facing parts of `postcss` API. However it would be nice if it includes *internal* `APIs` as well (eg Parser, Tokenizer).  

If you consider this as an option, I can submit patch with that declarations.

**Comment by ai** [comment]
What is use case for it?

**Comment by hzlmn** [comment]
As for me, I need it, for custom syntax parser that i writing in `TypeScript`, so i thought that it maybe useful for someone as well.

**Comment by ai** [comment]
2-3 use cases not good deal for increasing `node_modules` size for 5M users ;).

Custom typed definitions is better here.
