### ISSUE TITLE
v6    nested css Does not perform

### ISSUE THREAD

**Issue by wanglong167** [postcss/postcss#1039]
.phone { 
    img {
        display: block;
    }
}
results =>

![image](https://user-images.githubusercontent.com/456516/27119084-f7da9714-5110-11e7-8dac-ce802ff1a311.png)

**Comment by michael-ciniawsky** [comment]
CSS Nesting is not supported by default in any browser yet, you need a plugin to handle nested structures e.g [`postcss-nested`](https://github.com/postcss/postcss-nested). Please close the issue here :) it's not related to PostCSS

**Comment by michael-ciniawsky** [comment]
For `postcss >= v6.0.0`, ensure to have `postcss-nested >= v2.0.0` installed
