### ISSUE TITLE
PostCSS Config - ES6 

### ISSUE THREAD

**Issue by bradennapier** [postcss/postcss#1040]
Is there any method for running the postcss config with es6 and import/export?  My reasoning is that I have quite a few things that I want to import so that i can setup configuration maps etc that are shared throughout the app with a single codebase (don't want to switch between es6/5 etc).

**Comment by TrySound** [comment]
@bradennapier Wrong repo. Post this issue in [postcss-cli](https://github.com/postcss/postcss-cli) repo please

**Comment by bradennapier** [comment]
Ok thanks @TrySound
