### ISSUE TITLE
Causes eslint configurations to take a long time

### ISSUE THREAD

**Issue by mikeyGlitz** [postcss/postcss#1041]
Adding `postcss` causes linting in my project to take a long time.
This is my config file:
```js
{
"env": {
"browser": true,
"node": true,
"jest": true
},
"extends": "airbnb"
}
```

Nowhere in my configuration does it require `eslint-config-postcss` or `eslint-config-cssnano`, but when I try to run eslint without them, the linter crashes.

**Comment by ai** [comment]
Add ignoring `node_modules` to your ESLint run

**Comment by mikeyGlitz** [comment]
I have `node_modules/**` in my .eslintignore file

**Comment by ai** [comment]
In this case I recommend to go to ESLint chat channel and ask there.

It is first report about ESLint config problems, so I think you have some problem in ESLint config as result ignores didn't used.

I am not so good in ESLint to help with this.

If somebody will report about this issue too, I could reconsider that it is PostCSS config problem.

**Comment by mikeyGlitz** [comment]
I've noticed that `eslint-config-postcss` and `eslint-config-cssnano` are listed as `devDependencies` of `postcss`. I don't know why my config would care about that.

**Comment by ai** [comment]
devDependencies are not installed from dependencies
