### ISSUE TITLE
Tokenizer: Unicode escapes with trailing whitespaces

### ISSUE THREAD

**Issue by subzey** [postcss/postcss#1042]
I've noticed that postcss doesn't work with [hexadecimal unicode css escapes](https://www.w3.org/TR/css-syntax-3/#escape-diagram).

Declaration `\62 olor: red` is incorrectly parsed into
```js
{"decl": "\\62", "value": "red", /*...*/}
```
Expected is:
```js
{"decl": "\\62 olor", "value": "red", /*...*/}
```
One of the results is the fact [stylelint property-blacklist](https://stylelint.io/user-guide/rules/property-blacklist/) and many other rules can be easily tricked. And it's very unlikely that this issue can be resolved on the stylelint side.

Digging deeper I've found that issue is in tokenizer. The test string is `\0a \09 `. Calling `tokenize({css: '\\0a \\09 '})` yields
```
[ 'word', '\\0', 1, 1, 1, 2 ]
[ 'word', 'a', 1, 3, 1, 3 ]
[ 'space', ' ' ]
[ 'word', '\\0', 1, 5, 1, 6 ]
[ 'word', '9', 1, 7, 1, 7 ]
[ 'space', ' ' ]
```
expected result is all (up to 6) hex numbers and a trailing whitespace are glued to the backslash:
```
[ 'word', '\\0a ', 1, 1, 1, 4 ]
[ 'word', '\\09 ', 1, 5, 1, 8 ]
```

I understand that this change can be breaking: for example, existing plugins could possibly not expect whitespaces or newlines in property names, media queries, etc. So if you decide that it just doesn't worth it and nobody writes code this way, I'll be okay with that.

**Comment by ai** [comment]
Interesting case.

Can you write simple PR to tokenizer?

**Comment by subzey** [comment]
Sure. But it'll take some time for me to find out how the tokenizer works.

**Comment by ai** [comment]
I added test to common parsers tests: https://github.com/postcss/postcss-parser-tests/commit/116e88e12a766993354c66af0aeb8bc8bac4ce8c

**Comment by hzlmn** [comment]
@subzey 
> Sure. But it'll take some time for me to find out how the tokenizer works.

I currently trying to add docs that will help with this (hopefully), could you please look on #1078 
Maybe you have something that as a contributor you would like to see there. Also please take a look on parsing stage overview (draft version), is it understandable ?
