### ISSUE TITLE
Absent end position when parsing at rule

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss#1046]
Hi @ai ,

```js
a { @import "a.css" }
```
When at rule defined inside rule declaration, it parsed without corresponding `end` block.
As you can see from [`this`](https://github.com/postcss/postcss-parser-tests/blob/master/cases/inside.json#L26-L31).

**Comment by ai** [comment]
Yeap, it is bug. Do you want to try fix it?

**Comment by hzlmn** [comment]
Yes, I will look what i can do.

**Comment by hzlmn** [comment]
Hello, I have small question.

For such code sample 
```css
// First case
@import "test"

// Second case
@import "test";
```
How should `end` position be matched for such cases, cuz in `first` case it matched by closing character of params and in `second` case  in match start of `;` as and `end` for `at-rule` ?

As i understand `at-rule ` end position should be end of all params as in `second` case, but seems like right know Parser don't understand sequence ending different then char `;`

**Comment by ai** [comment]
Technically, at-rule *must* have `;`. Last code example is invalid.

**Comment by hzlmn** [comment]
Yes i know, due to spec. But `postcss` parse it cuz it should understand sometimes not standard compatible syntax, am i right? So the question is in such cases should it just match ending by end of `@import` or end of last param?

I ask it cuz when parsing
```
a { @import "./test" "test" }
```
should `end`  position be end of params or end of import keyword

**Comment by ai** [comment]
Ideal solution: yeap, it should be the last non-space token

**Comment by hzlmn** [comment]
Okay, thanks.
