### ISSUE TITLE
Question about Prettier

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss#1048]
While submitting patches I realised that you almost every time clean up code (shame on me).

So maybe it would be nice to integrate `prettier` etc. or just at lease add common style guide (I guess it should be part of #1013 ) for preventing such cases in future?

**Comment by ai** [comment]
`prettier` is not flexible for our code style. But I am OK of improving our ESLint config.

**Comment by ai** [comment]
Anyway it is not a big deal. I can fix code style in small PR.
