### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by i-like-robots** [postcss/postcss#1049]
[I have a Webpack plugin](https://github.com/i-like-robots/extract-css-block-webpack-plugin) that receives one large CSS input and splits into multiple, smaller output files.

E.G.

```scss
/*! start:critical.css */
@import "shared-ui/component/normalize";
@import "shared-ui/component/grid";
@import "shared-ui/component/typography";
/*! end:critical.css */

@import "component/tabs";
@import "component/modal";
@import "layout/list-page";
@import "layout/content-page";

/*! start:comments.css */
@import "component/comments";
@import "component/comment-form";
/*! end:comments.css */
```

Will result in 3 stylesheets:- main.css, critical.css and comments.css.

I am looking into porting this plugin to PostCSS as Webpack and CSS are not currently much fun. I'm hoping this will require only minor changes (I am already manipulating an AST etc.) but I'm unsure if it is currently possible to output multiple files within the PostCSS plugin API. Is this correct, or, how can it be done (preferably without resorting to manually writing the files!)?

Thanks.

**Comment by ai** [comment]
Right now there is no API for multiple input/output.

I thought to add it but didn’t found the good solution.

But you can do it manually:

```js
const full = postcss.parse(css, { from })
const fullProcessed = postcss(prePlugins).process(full).root

const root1 = postcss.root()
const root2 = postcss.root()

fullProcessed.each(node => {
  if (check(node)) {
    root1.append(node)
  } else {
    root2.append(node)
  }
})

const css1 = postcss(postPlugins).process(root1).css
const css2 = postcss(postPlugins).process(root2).css
```

**Comment by i-like-robots** [comment]
Thanks for your fast response
