### ISSUE TITLE
Module build failed: Error: Failed to find 'views/**/*.css'

### ISSUE THREAD

**Issue by kaihendry** [postcss/postcss#1053]
Trying to upgrade to Webpack, but I'm unable to get it working.

Version: webpack 3.3.0

```
static-website$ grep postcss package.json
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-url": "^7.0.0",
```

```
static-website$ cat postcss.config.js
module.exports = (ctx) => {
     return {
            plugins: [
                      require("postcss-import")({ addDependencyTo: ctx.webpack }),
                      require("postcss-url")(),
                      require("postcss-cssnext")({ browsers: [ "last 3 versions" ] }),
                      require("rucksack-css")()
                   ]
          }
}
```

And the relevant section in `webpack.config.js`

```
      { test: /\.css/,
                 use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
      },
```

What am I missing ? Many thanks,

**Comment by michael-ciniawsky** [comment]
```diff
module.exports = (ctx) => {
     return {
            plugins: [
                        // @import => css-loader#importLoaders
-                      require("postcss-import")({ addDependencyTo: ctx.webpack }),
                      require("postcss-url")(),
                      require("postcss-cssnext")({ browsers: [ "last 3 versions" ] }),
                      require("rucksack-css")()
                   ]
          }
}
```

In case you are using `postcss-loader >= v2.0.0` the `ctx` changed and doesn't expose the `webpack` property anymore for perf reasons. Like mentioned you won't need `postcss-import` when using webpack, it is even discouraged to do so, bc it can bloat your CSS sigificantly. For webpack `@import` needs to be converted into `import/require()` requests to ensure deduping imports. This is what `css-loader` does via `importLoaders` so use it instead please. In case you need/want to rely on `postcss-import` nevertheless `postcss-import >= v9.0.0` && `postcss-loader` add `@import` to the webpack watcher as dependencies automatically and the `{ addDependencyTo: ctx.webpack }` isn't needed aswell :)

**Comment by michael-ciniawsky** [comment]
⚠️ Glob patterns are not supported by `postcss-import` or `css-loader#importLoaders`

**Comment by kaihendry** [comment]
Thanks @michael-ciniawsky ... removing that line allows me to move on. I think.
