### ISSUE TITLE
Cannot read property 'postcss' of null

### ISSUE THREAD

**Issue by killerlayup** [postcss/postcss#1055]
Hi, All
when I set vue-loader, like this:

````
{
                    test: /\.vue$/,
                    loader: 'vue-loader',
                    include: [
                        $srcFolder,
                        require('@vdian/hotpot').path
                    ],
                    options: {
                        loaders: {
                            css: [
                                {
                                    loader:'css-loader?minimize'
                                },
                                {
                                    loader: 'postcss-loader',
                                    options:{
                                        plugins: [require('autoprefixer')({
                                            browsers: [
                                                    "Android >= 4",
                                                    "iOS >= 5"
                                                ],
                                            cascade: true
                                        })]
                                    }
                                }
                            ], // will be replaced
                            less: [
                                {
                                    loader:'css-loader?minimize'
                                },
                                {
                                    loader: 'postcss-loader',
                                    options:{
                                        plugins: [require('autoprefixer')({
                                            browsers: [
                                                    "Android >= 4",
                                                    "iOS >= 5"
                                                ],
                                            cascade: true
                                        })]
                                    }
                                },
                                {
                                    loader:'less-loader'
                                }
                            ] // will be replaced
                        }
                    }
                }
````

run webpack, I got 'Cannot read property 'postcss' of null',

But when I just change  plugins to:

`plugins: []`

webpack run OK. 

can anyone help me?

**Comment by killerlayup** [comment]
By the way, I can set postcss-loader successfully like this:

`{
                    test: /\.less$/,
                    use: [
                        {
                            loader:'css-loader?minimize'
                        },
                        {
                            loader: 'postcss-loader',
                            options:{
                                plugins: [require('autoprefixer')({
                                    browsers: [
                                            "Android >= 4",
                                            "iOS >= 5"
                                        ],
                                    cascade: true
                                })]
                            }
                        },
                        {
                            loader:'less-loader'
                        }
                    ] // will be replaced
                }`

**Comment by michael-ciniawsky** [comment]
Please open issues like that in `postcss/postcss-loader` instead :). Try adding an `ident` to your `postcss-loader` config in the first example, the {Function} stringifier is sometimes buggy when used in more complex setup (with `vue-loader` here)

**webpack.config.js**
```js
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss' // <= this line
    plugins: () => [...plugins]
  }
}
```

**Comment by michael-ciniawsky** [comment]
Otherwise open an issue in `vue-loader`
