### ISSUE TITLE
CSS parsing order.

### ISSUE THREAD

**Issue by tom-drake** [postcss/postcss#1056]
Hi, this is a question about the order a CSS file is parsed. It comes from an [issue](https://github.com/TrySound/postcss-inline-svg/issues/40) I've had in postcss plugin. The library uses css.walk() (This is the walk of a Root object). When I output the Root object which is provided to the library from postcss I see the order of the nodes array does not match what I would expect from the CSS file. The CSS defines a few AtRules at the top and then some Decls later reference those. The problem is that if the Decl is parsed before the associated AtRule the library throws an error for that Decl.

Is it expected that the order of the nodes array within Root does not relate to the order in the CSS file? Should the library be walking the AtRules first then the Decls after? Thanks

**Comment by ai** [comment]
It is the bug, the order should be the same.

Could you show CSS, JS code to parse and walk and the result.

The problem is that we test that parsed is byte-to-byte equal to output. And there are no and problems with this test. So I think that maybe you have some plugin, which changes order before parsing and your code.

But maybe it is some rare edge-case bug. So give me code examples :).

**Comment by tom-drake** [comment]
I can refer you to what the library is doing and my understanding of how its working. [Line 35](https://github.com/TrySound/postcss-inline-svg/blob/master/src/index.js) is the part which does the walking of the nodes. It is checking to see if its an AtRule and keeping a list of those AtRules as the loaders for some of the Decls. In the same walk it also checks if its a Decl and looks up the loader from the internal map. But the problem became clear when an error was throw because the associated AtRule had not been seen first even though it was defined first in the CSS.

We are using a fairly standard setup in this project with postcss-loader and a postcss.config.js file defining our plugins (postcss-inline-svg being the one I linked to earlier). There's no JS which interacts with the CSS that we have made as far as I'm aware.

I can give sanitized css and the associated output from just a console.log on the Root element.

style.css
```
@import "a.css";
@import "b.css";

@svg-load icon_1 url(ICON_1.svg) {}
@svg-load icon_2 url(ICON_2.svg) {}

:root {
  --icons: {
    & .icon.icon-1 {
      background: svg-inline(icon_1) 50% no-repeat;
    }

    & .icon.icon-2 {
      background: svg-inline(icon_2) 50% no-repeat;
    }
}

button.btn {
  @apply --icons;
  ...
}
```

Root object:
```
root {
  raws: { semicolon: false, after: '\r\n' },
  type: 'root',
  nodes:
   [ Rule {
       raws: {},
       type: 'rule',
       nodes: [Object],
       source: [Object],
       selector: '.icon-2, ...',
       selector: 'button.btn .icon.icon-2, ...', /* Issue here on the walk of Root */
       parent: [Circular],
       lastEach: 38,
       indexes: {},
       _autoprefixerDisabled: false },
     ...,
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'svg-load',
       parent: [Circular],
       source: [Object],
       params: 'icon_1 url(ICON_1.svg)',
       nodes: [],
       lastEach: 39,
       indexes: {} },
     AtRule {
       raws: [Object],
       type: 'atrule',
       name: 'svg-load',
       parent: [Circular],
       source: [Object],
       params: 'icon_2 url(ICON_2.svg)',
       nodes: [],
       lastEach: 39,
       indexes: {} },
     ...,
     Rule {
       raws: [Object],
       type: 'rule',
       nodes: [Object],
       source: [Object],
       selector: 'button.btn .icon.icon-1, ...',
       parent: [Circular],
       lastEach: 39,
       indexes: {},
       _autoprefixerDisabled: false } ],
  source:
   { input:
      Input {
        css: '...',
        file: '...' },
     start: { line: 1, column: 1 } },
  lastEach: 41,
  indexes: {},
  _autoprefixerDisabled: false } 
```

I'm still not sure what is causing this issue so haven't been able to produce something which is reproducible other than the in my current projects code base. It does occur across other css files in the project as well.

**Comment by ai** [comment]
According to rules selector AST was changed by some plugin. Seems like it was `cssnext`.

**Comment by tom-drake** [comment]
I have updated our postcss.config.js file to use the postcss-inline-svg plugin before our postcss-cssnext plugin and that fixes the problem! Thanks for the help.
