### ISSUE TITLE
Incorrect behavior when building the AST

### ISSUE THREAD

**Issue by iGetPass** [postcss/postcss#1066]
Hi.

`.Compo/* incorrect */nent`
PostCSS the output of this selector:
`.Component`

You can correct this behavior?

**Comment by ai** [comment]
Yeap, it is unexpected behavior.

Quick fix: you can use `rule.raws.selector.value` to get selector before comment stripping.

**Comment by hzlmn** [comment]
@ai Did you have a chance to look on it, if not i can fix it?

**Comment by ai** [comment]
Did had time :(.

@hzlmn it will be awesome if you will send PR.

**Comment by hzlmn** [comment]
Okay, i will try to come with something later today.

**Comment by hzlmn** [comment]
@ai Quick question, should it be parsed as a single rule node with value 
equal to `"Compo/* incorrect*/sent` or it should be three separate nodes corresponding?

**Comment by ai** [comment]
Good question :-/.

In the current API we don’t have nodes in `Rule#selector`. So maybe the best option here will be not trim comment without space at least from one side.

**Comment by hzlmn** [comment]
@ai Seems reasonable, but to be honest I hardly think that there is a case when such selector could be useful :)

**Comment by ai** [comment]
Released in 6.0.17
