### ISSUE TITLE
`background-clip` doesn't work.

### ISSUE THREAD

**Issue by wzup** [postcss/postcss#1068]
background-clip doesn't work.

![background-clip - google chrome 2017-09-09 20 24 59](https://user-images.githubusercontent.com/3880497/30240119-311e08aa-959d-11e7-8c32-aa07bc8d8515.png)

Don't know whose issue this is, autoprefixer's or postcss. I write it here because I found same issue from 2013 #156

**Comment by deflock** [comment]
Why do you think this is somehow related to postcss?
Or provide some more information about your input and expected output
