### ISSUE TITLE
Import postcss in typescript

### ISSUE THREAD

**Issue by khlevnov** [postcss/postcss#1070]
I try to use typescript to write a postcss plugin, but there is a problem with import postcss from node_modules. If I try to import it with following code (default es6 import) in a .ts file
`import { postcss } from 'postcss';`
I will get an error
`TS2307: Cannot find module 'postcss'`
So, I try to add postcss in a types section in tsconfig.json, but nothing happens.

What I am doing wrong?  And how can I resolve this problem and import postcss in typescript?

**Comment by ai** [comment]
@khlevnov you should write `import postcss from 'postcss'` without `{`

**Comment by khlevnov** [comment]
@ai I try to use this variant, but I've got the same error. Full text of error in a block below:

> ERROR in [at-loader] ./index.ts:1:21
>     TS2307: Cannot find module 'postcss'.

**Comment by ai** [comment]
Are you sure that it is not `npm` error? Does same import work in `node`?

**Comment by r3nya** [comment]
@khlevnov can you try `import * as postcss from 'postcss'`?

And you need to declare this module …

E.g.:

- Please create a file with customs definitions:
```
definitions/global.d.ts
```
- Include it in `tsconfig.json`:
```
  "filesGlob": [
    "node_modules/**/*.d.ts",
    "definitions/*.d.ts",
    …
  ],
```
- And final step:
```
declare module 'postcss';
```

Please ping me if you will have any problems. =)

**Comment by khlevnov** [comment]
Thanks, now import is working!

**Comment by r3nya** [comment]
Btw, @jedmao I found that postCSS supports types for TypeScript (https://github.com/postcss/postcss/blob/master/lib/postcss.d.ts) … But it doesn't work I guess.

**Comment by jedmao** [comment]
@r3nya it works for me. See https://github.com/jedmao/postcss-center/blob/9ea9f28f571f7a26a04bbece4c7220b46643039c/src/plugin.ts#L1
