### ISSUE TITLE
Postcss handles postcss.config.js incorrectly when putting it in project folders

### ISSUE THREAD

**Issue by deser** [postcss/postcss#1076]
Let's say I have the following folder structure:
```
- app1
  - file1.js
  - 1.css
  - postcss.conf.js
- app2
  - file2.js
- shared
  - vendor.js
  - vendor.css
```

file1.js requires 1.css
file1.js requires vendor.js which requires vendor.css.
All dependencies are taken via webpack 3.*

The problem is that vendor.css isn't processed by postcss when 1.css is. Seems that postcss just processes files within the folder it lays but not the dependencies webpack got for entry point.

**Comment by ai** [comment]
Yeap. It is so by design.

Same as in Babel.

**Comment by deser** [comment]
@ai, maybe you can advise smth? I need different processing for different entry points in one webpack config.
Thanks

**Comment by ai** [comment]
You can try to use different import. So PostCSS will see file after concat

**Comment by deser** [comment]
You mean do postCSS processing not via config but inside webpack config?

**Comment by ai** [comment]
No. I mean do not use postcss-import. Use some non-PostCSS tool for import files.

**Comment by deser** [comment]
You mean `postcss-loader` ? Sorry for taking your time but maybe you can advise some other non-postCSS tools?

**Comment by ai** [comment]
Nope. Google `webpack import css`. Sorry I am not at laptop right now.

**Comment by deser** [comment]
ok, thanks a lot.
Btw, seems I resolved my problem by using postcss-import
