### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by necolas** [postcss/postcss#108]
Would be useful to have docs focused on detailing the complete API, including methods available to manipulate or traverse the AST, rather than only use-case examples. It's too much work to piece it all together from the existing README.

**Comment by ai** [comment]
Does it good start? https://github.com/postcss/postcss/blob/master/API.md

**Comment by ai** [comment]
API docs are finished https://github.com/postcss/postcss/blob/master/API.md

I put them to file in repository because I love to develop code in airplanes and I think that it is good to have a `API.md` in plugin `node_modules/postcss`.

/cc @MoOx @davidtheclark @lydell

**Comment by lydell** [comment]
Nice! Could use a bit of polish here and there, but I think there will be PRs for that. Great work! :)

**Comment by ai** [comment]
@lydell it is only a half ow work. In this weekend I finish new `README.md`, because many potencial PostCSS use do not understand what it is :)

**Comment by ai** [comment]
First version of new `README.md` is finished too. https://github.com/postcss/postcss/blob/master/README.md
