### ISSUE TITLE
When a rule only includes a mixin and nothing else, sourcemap points to mixin definition, not to rule

### ISSUE THREAD

**Issue by setek** [postcss/postcss#1083]
dependencies:
```
"autoprefixer": "^7.1.5",
"node-sass": "^4.5.3",
"postcss": "^6.0.13",
"postcss-cli": "^4.1.1",
```

Ran:
```
node-sass --source-map true --output-style compressed -o \"assets/css\"
postcss -m -r "assets/css/style.css"
```

SCSS:
```
.ai-sub-title {
  @include ai-value--lg;
}
```

Inspecting `<h2 class="ai-sub-title">` shows the sourcemap pointing to the mixins file, to the correct line number of `@mixin ai-value--lg {}`, instead of to the rule that called the mixin.

Is this expected behaviour, or a bug?

Thanks!

**Comment by ai** [comment]
I tried to fix this bug but didn’t find a way (and since it is not PostCSS issue, but 2 tools compatibility issue I decide that bug is not really critical). If oy know how to fix it, please send PR.
