### ISSUE TITLE
Question - How to use config.json?

### ISSUE THREAD

**Issue by BamiGorengo** [postcss/postcss#1086]
Hello, Sorry for asking things in a issue board, but i cant resist any more. I try now to sience about 8 hours, to make postcss working.

My package.json:
```
{
  "scripts": {
    "postcss": "postcss --config postcss.json"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.6",
    "bootstrap-sass": "^3.3.7",
    "cssnano": "^3.10.0",
    "node-sass": "^4.5.0",
    "postcss": "^6.0.13",
    "postcss-cli": "^4.1.1",
    "postcss-colormin": "^2.2.2",
  }
}
```

My postcss.json:
```
{
  "use": [
    "autoprefixer"
  ],
  "input": "public_html/css/",
  "output": "public_html/css/min/*.css",
  "local-plugins": true,
  "watch": false
}
```

With this i get a Error when i run "npm run postcss":

> Input Error: Did not receive any STDIN

Okay, Looks like that the --config param dont work. so i tryed to input the files direct in the script:

> "postcss": "postcss public_html/css/**/*.css --base --dir public_html/css/min/"

But what ever i try, i cant make that he collect my 4 css files and keep the folder structure:

public_html/css/style.css
public_html/css/folder/xxx.csss
public_html/css/folder/xxx.csss
public_html/css/folder/xxx.csss

I find here: https://github.com/postcss/postcss-cli in the "Options List" the --base option. So i try it with --base --dir because the documentations says: "Use together with --dir for keeping directory structure." but when i use them together i get following errors again:

> Input Error: Must use --dir or --replace with multiple input files

Im verry short to get mad ;)
Please Help me! :D

**Comment by ai** [comment]
Hi. Sorry, I don't use postcss-cli. Try to open issue on their repo.

**Comment by michael-ciniawsky** [comment]
@BamiGorengo https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2-to-v3#config-files
