### ISSUE TITLE
JS API plugins vs postcss.config.js

### ISSUE THREAD

**Issue by beefchimi** [postcss/postcss#1088]
Curious if there is a way to have `postcss` read from the `postcss.config.js` in the project root when using the JS API? Seems like we have to specify plugins as an array instead? Not really sure how CSSnano is to be configured if it goes into the array.

```js
function postProcess(sassResult) {
  // can I remove this array and have `postcss` read from the `config`?
  postcss([autoprefixer, cssnano]).process(sassResult.css, {
    from: srcFullPath,
    to: distFullPath,
    map: true,
  }).then((result) => {
    return fs.writeFile(distFullPath, result.css, Helpers.throwError);
  }).catch((error) => {
    throw new Error(error);
  });
}
```

**Comment by ai** [comment]
Yeap. Use `postcss-load-config` https://github.com/michael-ciniawsky/postcss-load-config
