### ISSUE TITLE
[Feature request] Provide Tokenizer, Comment and Parser as named exports

### ISSUE THREAD

**Issue by wessberg** [postcss/postcss#1094]
Hi,

Thanks for your great contributions to Open Source! <3

Here's a PR for this issue: https://github.com/postcss/postcss/pull/1095

# Problem

Currently you have to import internal modules to implement your own custom parser for PostCSS.
For example:

```javascript
import tokenizer from 'postcss/lib/tokenize';
import Comment from 'postcss/lib/comment';
import Parser from 'postcss/lib/parser';
```

Since PostCSS is set up to accept a custom parser as a configuration option, I would be very happy if you provide these as public importable modules, rather than having consumers need to tap in to the internals of PostCSS to actually implement a custom parser and/or tokenizer.

# Proposed solution

Here's what I would like to do:

```javascript
import {tokenizer, Comment, Parser} from "postcss";

class MyCustomParser extends Parser {
    // ...
}
```

To do that, you could add:
```javascript
export {tokenizer, Comment, Parser}
```

in the bottom of `/lib/postcss.js` right below the default export. The Typescript typings would need to be updated too to reflect this change.

I hope you'll consider this. Thanks!

**Comment by ai** [comment]
Honestly, it is not the best way since more JS will be parsed. Also client-side bundle will be bigger since tree-shaking doesn't work so effective as separated files. Separated files is simplier and more performance way.

But it is not a big problem, so we can do it in next minor release. It could take a week or a month (holidays).

**Comment by wessberg** [comment]
Let me prepare a PR for you, and then you can decide if you want to merge it in :-)
I'll update this issue when its ready.

**Comment by ai** [comment]
Good plan

**Comment by wessberg** [comment]
Submitted PR: https://github.com/postcss/postcss/pull/1095

**Comment by wessberg** [comment]
Closing.
