### ISSUE TITLE
Retrieving the AST after plugins

### ISSUE THREAD

**Issue by matthew-dean** [postcss/postcss#1096]
Question: I couldn't seem to figure this out from the API. When processing styles, how do you get the AST 1) after styles have been parsed, 2) after plugins have transformed all nodes, and 3) before nodes have been stringified?

Is there no public API method for this? That is, is the only way to retrieve the "final" AST before stringification is to insert a PostCSS plugin after the last plugin that can receive the AST?

**Comment by ai** [comment]
To get AST after plugins:

```js
const before = postcss.parse(css, opts)
before //=> AST before plugins
postcss(plugins).process(before, opts).then(result => {
  result.root //=> AST after plugins (after plugins have transformed all nodes and before nodes have been stringified)
  result.css //=> CSS string after plugins
})
```

**Comment by matthew-dean** [comment]
Ah, I see, so it returns both the stringified and the AST form? Interesting, I wouldn't have expected that. Seems like unnecessary work if you're not going to use the string. But thanks!

**Comment by ai** [comment]
Yeap. We thought to have lazy stringifing, but it is very fast operation. You should not take care about it.

Anyway, if you don't need string, you can always make transformation by your own:

```js
const ast = postcss.parse(case, opts)
plugin1(plugin1opts)(ast)
plugin2(plugin2opts)(ast)
ast //=> result

**Comment by dhlolo** [comment]
Location is postcss@8.3.9. Now return values of `plugins(pluginopts)` are an object. So there will be ts error about it.
![image](https://user-images.githubusercontent.com/50065494/176345399-1344895b-853f-4fdf-b61e-d2fd5860bc5e.png)


> Yeap. We thought to have lazy stringifing, but it is very fast operation. You should not take care about it.
> 
> Anyway, if you don't need string, you can always make transformation by your own:
> 
> ```js
> const ast = postcss.parse(case, opts)
> plugin1(plugin1opts)(ast)
> plugin2(plugin2opts)(ast)
> ast //=> result
> ```
