### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by Nirazul** [postcss/postcss#1100]
I know there has been another issue (#1049) before, but I'd be also very interested in splitting up files and returning files to the postcss stream.

Currently, there's no way to split up a file into two and allow following plugins to do their work unaffected from the split. One will always be saved to the filesystem, which is very unfortunate as a solution. Every plugin I've found, that needs this or tries to handle this, does simply save another file directly.

**Comment by ai** [comment]
The problem is `postcss-loader`. So if you want to split the file, you already need some special case.

The best way is to use low level JS API to it.
