### ISSUE TITLE
Node warning Node#before is deprecated

### ISSUE THREAD

**Issue by GrosSacASac** [postcss/postcss#1101]
`postcss css/game.css --use import-postcss cssnano --output built/bundle.css`

```
npm : Node#before is deprecated. Use Node#raws.before
At line:1 char:1
+ npm run buildcss
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Node#before is ...ode#raws.before:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Node#moveTo was deprecated. Use Container#append.
```

A warning that appears. Otherwise it works thanks alot for postcss.

**Comment by GrosSacASac** [comment]
Node version 8, NPM 5.5

    "postcss-cli": "^4.1.1",
    "import-postcss": "^8.0.2",
    "cssnano": "^3.10.0",

**Comment by ai** [comment]
Hi. Run `npm ls` to see all dependencies. In this list you will find what PostCSS plugin use old API. i think it should be `cssnano`. You should open or `+1` issue in `cssnano` repo.
