### ISSUE TITLE
"Unknown word" error when commenting with "//"

### ISSUE THREAD

**Issue by ZeeCoder** [postcss/postcss#1102]
You can reproduce the issue using autoprefixer's live demo:
https://autoprefixer.github.io/

After the closing "}", (with or without newline) add a comment, using "//".

The same error occurs when a comment is entered after the last css rule inside the brackets.

**Comment by ai** [comment]
@ZeeCoder can you show exactly code input?

**Comment by ZeeCoder** [comment]
Yeah, these all cause the same error to appear:


```
// some comment without actual css
```

```
.a-class {
color: inherit;
}
// this will cause an error too
```

```
.ert {} // won't work
```

**Comment by ai** [comment]
@ZeeCoder `//` is not a comment in CSS language. CSS allows only `/**/` comments ;).

Use `postcss-scss` if you want to use `//` comments.

Maybe we should use better error for this cases, but I am not sure.

**Comment by ZeeCoder** [comment]
I was so sure postcss allowed for such comments! it works for the most part too, only on these edge cases it fails.

**Comment by jeddy3** [comment]
> it works for the most part too,

You might be thinking of [next construct comments](https://www.xanthir.com/b4U10).

Incidentally, if you want to disallow this quirky feature of the CSS language, you can do so with the [`no-invalid-double-slash-comment`](https://stylelint.io/user-guide/rules/no-invalid-double-slash-comments/) stylelint rule.

**Comment by ZeeCoder** [comment]
I think I just tried using it and since it worked fine, assumed it was part of postcss.
I probably littered my postcss files with such comments all over the place without realising it could fail to compile.

Wonder if there's a postcss plugin to allow for such comments. 🤔

**Comment by jeddy3** [comment]
> Wonder if there's a postcss plugin to allow for such comments.

As @ai said, you'll need to use [a non-standard syntax parser](https://github.com/postcss/postcss#syntaxes) (like `postcss-scss`) if you want to use a construct that isn't part of the CSS language.

**Comment by ddoddo456** [comment]
thank you I lost a lot of time on this issue. Well done.
