### ISSUE TITLE
Better warning message

### ISSUE THREAD

**Issue by mhkeller** [postcss/postcss#1103]
This message:

https://github.com/postcss/postcss/blob/1416fbca02094063b28922c25accf81758d8aa4f/lib/lazy-result.es6#L193-L196

has a typo—I believe `Witout` should be `Without`—and I don't quite get the meaning of second part where it says `do not find`. It seems like the tense is wrong and maybe should be `could not` or `will not`.

**Comment by ai** [comment]
@mhkeller sure. Can you send a PR, so I will save your name in the project history?

> and I don't quite get the meaning of second part where it says do not find

`opts.from` is using in Browserslist. Browserslist takes CSS file path and start up-directory search for `.browserslistrc` config. If `opts.from` is undefined, Browserslist will not be started and config will not be applied.

**Comment by ai** [comment]
Fixed 43da29a

**Comment by ai** [comment]
Released in 6.0.16
