### ISSUE TITLE
Remove unused styles from a React SPA app!

### ISSUE THREAD

**Issue by amerllica** [postcss/postcss#1108]
Hi, I'm developing a React SPA application, I'm using `Webpack` and `React` for my app, CSS is making by `PostCSS` and I read [this link:#767](https://github.com/postcss/postcss/issues/767).

But `UnCSS` is for created `HTML` and `CSS` file, But my `DOM` is virtual and is not exist in real. So how I can  remove unused styles from my `CSS` file. for example, `class` styles for font shaping that I never will use them. my `Webpack` configuration is :

    const path = require('path');
    const ExtractTextPlugin = require("extract-text-webpack-plugin"),
        CleanWebpackPlugin = require('clean-webpack-plugin');
    
    const DistDir = path.resolve(__dirname, './dist'),
        SrcDir = path.resolve(__dirname, './src');
    
    let q = [],
        cache = {};
    
    function randomNaming(length,limit) {
        let result = '',
            chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_',
            fchars = 'abcdefghjklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_';
    
        do {
            if (q.length >= (52 * Math.pow(64, limit - 1)) && limit >= length) {
                return 'OutOfPossibility';
            } else if (q.length >= (52 * Math.pow(64, limit - 1)) && limit < length) {
                ++limit;
            }
            result = '';
            result += fchars[Math.floor(Math.random() * fchars.length)];
            for (let i = limit - 1; i > 0; --i) {
                result += chars[Math.floor(Math.random() * chars.length)];
            }
        } while (q.includes(result));
        q.push(result);
        return result;
    }
    
    module.exports = {
        resolve: {
            alias: {
                AppRoot: path.resolve(__dirname, './src/app'),
                PcssRoot: path.resolve(__dirname, './src/pcss')
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: ['node_modules'],
                    include: SrcDir,
                    loader: 'babel-loader'
                },
                {
                    test: /\.pcss$/,
                    exclude: /node_modules/,
                    include: SrcDir,
                    use: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            {
                                loader: 'css-loader',
                                options: {
                                    importLoaders: 1,
                                    modules: true,
                                    getLocalIdent: (loaderContext, localIdentName, localName, options) => {
                                        var randName = randomNaming(3,2);
                                        if (localName.match(/^i-/i)) {
                                            randName = `i-${randName}`;
                                        } else if (localName.match(/^i_/i)) {
                                            randName = `i_`;
                                        } else {
                                            randName = `${randName}`;
                                        }
                                        if (typeof cache[localName] == 'undefined') {
                                            cache[localName] = randName;
                                            return cache[localName];
                                        } else {
                                            return cache[localName];
                                        }
                                        }
                                    }
                            },
                            {
                                loader: 'postcss-loader',
                                options: {
                                    ident: 'postcss',
                                    syntax: 'postcss-scss',
                                    plugins: () => ([
                                        require('postcss-partial-import')({
                                            prefix: "_",
                                            extension: ".pcss",
                                            glob: false,
                                            path: ['./src/pcss']
                                        }),
                                        require('postcss-nested-ancestors'),
                                        require('postcss-apply'),
                                        require('postcss-custom-properties'),
                                        require('postcss-nested'),
                                        require('postcss-cssnext')({
                                            features: {
                                                nesting: false
                                            },
                                            warnForDuplicates: false
                                        }),
                                        require('postcss-extend'),
                                        require('css-mqpacker')({
                                            sort: true
                                        }),
                                        require('autoprefixer')({
                                            browsers: [`last 15 versions`]
                                        })
                                    ])
                                }
                            }
                        ]
                    })
                },
                {
                    test: /\.(woff|woff2|eot|ttf|svg)$/,
                    exclude: /node_modules/,
                    loader: 'file-loader',
                    options: {
                        limit: 1024,
                        name: '[hash:base64:3].[ext]',
                        publicPath: '../font/',
                        outputPath: 'asset/font/'
                    }
                }
            ]
        },
        plugins: [
            new ExtractTextPlugin({
                filename: `asset/css/style.css`
            }),
            new CleanWebpackPlugin(`${DistDir}/asset`)
        ],
        entry: {
            "sd": `${SrcDir}/app/index.js`
        },
        externals: {
            config: JSON.stringify(require(SrcDir + '/config/config.prod.json'))
        },
        output: {
            path: DistDir,
            filename: "asset/js/[name].bundle.js"
        },
        devServer: {inline: true},
    };

**Comment by ai** [comment]
Sorry, I didn't hear about any uncss for React 😔.

My suggestion is to split CSS into small components as you split React components. Next put CSS and React code of each component in same dir. So when you will delete React code, you will delete CSS code as well.

**Comment by amerllica** [comment]
@ai, Thanks a lot my dear friend, I like your manner 👍 💯 ❤️ 
My issue not removing react components and then unused CSS, surely I created a sexy plan for `.pcss` files that definitely related to their own react components. so I never leave behind `.pcss` files after deleting react components.

My exactly issue is unused styles that freely rolling on extracted `.css` files that you said has no solution.

Thanks

**Comment by ai** [comment]
@amerllica BTW, maybe you want to write this tool? You could start with a very easy tool which will just collect all static `className="X"` from all `*.jsx` files in some directory.

You know, very popular tools was started from fixing own problems :).

**Comment by amerllica** [comment]
I think to your offer, Absolutely every developer wanna be professional like you, so it's right way to fixing my own problem first and then it became a popular tool. thanks a lot dude 🌹 💟
