### ISSUE TITLE
Inconsistency in declaration parsing when there is no semicolon; 

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#1110]
Hi,

If a declaration value ends with a comment, postcss parses the comment into raw value **except** when that declaration has no semicolon, it's parsed into a separate comment node.

> It's a common practice for CSS minifiers to drop the last declaration semicolon

See example: https://runkit.com/embed/vlzhtauxqd32

This is causing problems to rtlcss users due to directives being dropped when converting minified LTR stylesheets.

Thanks!

**Comment by ai** [comment]
Current behavior was specially asked from other users 😅.

Sorry, there is no best way to do it. Both way have some problem for some users.

Is it possible to make RTLCSS a little smarter and cover both control comment positions (inside and outside of the node)?

**Comment by MohammadYounes** [comment]
This is the main difference between control and value directives.

> Control directives are placed between declarations or statements (rules and at-rules). 

> Value directives are placed any where inside the declaration value.

I don’t think there will be an easy way to work around this in rtlcss 😢

**Comment by ai** [comment]
Why? You can check is declaration is the last one and is it have semicolon.

Sorry, changing it in the core will break public API. But I will have the same check in the core. It doesn't matter, will we put it to core or to RTLCSS (if I understand it correctly).

**Comment by MohammadYounes** [comment]
On second thought, it's also impossible for you to know whether the comment is part of the declaration or not! 

In rtlcss - placing the _Value Directive_ **anywhere** inside the declaration value gives the same result. So, having the comment before the value provides the perfect fix.

Thanks @ai

**Comment by MohammadYounes** [comment]
Not so perfect fix 😢 

Comments placed first goes into `between` rather than `value.raw` #598 - Which I hoped it would be fixed by postcss as the change is dangerous for rtlcss public API too.
