### ISSUE TITLE
Minify multiple input file with postcss

### ISSUE THREAD

**Issue by bobc82** [postcss/postcss#1112]
I installed cssnano following these step: http://cssnano.co/guides/getting-started/

Into the root of my project i ran:

    `npm install cssnano --save-dev`

After i installed postcss-cli:

    `npm install postcss-cli --global`

Finally i created postcss.config.js file following the guide:

```
module.exports = {
       plugins: [
        require('cssnano')({
            preset: 'default',
        }),
      ],
    };
```

I was able to minify only a file. In the roow of my project i executed:

    `postcss src/plugins/bootstrap/css/bootstrap.css > src/compiled.min.css`

But i'm not able to include multiple input file and create a minified.css compiled file (and i don't know if it's possible) as i did in gulp. When i try to run a command of this type:

    `postcss src/plugins/bootstrap/css/bootstrap.css src/plugins/animatecss/css/animate.css > src/compiled.min.css`

There was the following error:

    `Input Error: Must use --dir or --replace with multiple input files`

**Comment by ai** [comment]
You should all postcss-cli authors (sorry, that look has different maintainers, I can make delicious for them).

I think it is good idea. Our tools should be easy to use. Also making contacting in PostCSS is good for new source map (you can copy my thoughts to issue)
