### ISSUE TITLE
Please upgrade source-map to 0.7.2 to get speed improvements

### ISSUE THREAD

**Issue by andreicristianpetcu** [postcss/postcss#1126]
The latest source-map which is v0.7.2 got support for WebAssembly and it is 10 times faster than the old one. More info here:

https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#072
http://fitzgeraldnick.com/2018/02/26/speed-without-wizardry.html
https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/
https://github.com/devtools-html/debugger.html/issues/5598

Please update so you would get 10 times speed improvements for your library in Firefox, 9 times in Safari and 5 times in Chrome.

**Comment by ai** [comment]
Since source-map uses async API we can't update it without major release (with a lot of changes).

Or maybe I understood something wrong?

**Comment by ai** [comment]
I tried to add it in 7.0, but found few big problems.

* The minor problem is that new WASM source-map uses async API. It is not a problem in stringifier. But we need source map reading in `Node#error`. Moving this method to async will break too many plugins.
* The main problem is that WASM is supported (if I understand it correctly) only from Node.js 8. We need to support Node.js 6 until [April 2019](https://github.com/nodejs/Release).
* source map is not the main performance problem in most PostCSS use cases.

In result of this reasons, I decide to wait for a little until `source-map` update (it is painful for me too, I really like to use the latest software 😭). We will wait until:
* Sync API will be added https://github.com/mozilla/source-map/issues/331
* Node 6 support will be added or Node 6 LTS will be ended.
