### ISSUE TITLE
[API Usage Instructions] fs.writeFile without callback is deprecated

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss#1128]
Calling `fs.writeFile` without a callback is deprecated.  Might want to update README.md API usage instructions to use `fs.writeFileSync`.

Something like:

``` js
// Make sure dest directory is created first
//The node mkdirp module is good at this
fs.writeFileSync('dest/result.css', result);
```

**Comment by ai** [comment]
@oleersoy yeap. Good idea. Do you want to send PR?

**Comment by ai** [comment]
I think again and decided that have 2 lines comment in this simple example is too big. Maybe we should change file names to avoid this error?

**Comment by oleersoy** [comment]
We could put it on one line or delete the `mkdirp` suggestion.  WDYT?

**Comment by ai** [comment]
Or to write to `app.out.css` instead of `dest/app.css`
