### ISSUE TITLE
When css is null, an error has occurred.

### ISSUE THREAD

**Issue by chenwenxian** [postcss/postcss#1130]
postcss/lib/lazy-result.js
![image](https://user-images.githubusercontent.com/5305181/37275297-bc58422a-2619-11e8-96d0-7ba6c914ff3d.png)
Modified code:
![image](https://user-images.githubusercontent.com/5305181/37275343-df98b6fc-2619-11e8-8dba-0eb2f9a8e6b4.png)

**Comment by ai** [comment]
@chenwenxian sure, we need a small fix here: https://github.com/postcss/postcss/blob/master/lib/lazy-result.es6#L26

Do you want to send PR to save your name in project history? :)

**Comment by chenwenxian** [comment]
ok, very good!

**Comment by ai** [comment]
Done 1a3467b

**Comment by ai** [comment]
Released in 6.0.20.
