### ISSUE TITLE
Can PostCSS perform processes POST (after) some other functions?

### ISSUE THREAD

**Issue by hannwong** [postcss/postcss#1134]
Maybe I'm reading the word **POST** wrong, but it seems to mean `PostCSS` is meant to run processes (eg. autoprefixer) **after** some other processes.

In the `Processor.process()` command, I don't see anyway to add in a **PRE** function to be executed before every `PostCSS` plugin is run.

I need to know this because I have some **PRE** function that reads from disk. I don't want to read from disk twice; `Processor.process()` seems to only want to read from disk, not from byte stream or something.

**Comment by ai** [comment]
PostCSS is like postmodern. Next level of CSS ;).

Right now PostCSS can run as linter (Stylelint), change sources on sources (like postcss-sorting), preprocess (like PreCSS), polyfill (like poostcss-preset-env or cssnext) and anything else ;).

**Comment by hannwong** [comment]
Sorry to waste your time. I think I really am misunderstanding the PostCSS docs.

`Processor.process(css, opts)` actually does take in raw CSS (string) for `css` argument. In this way, `PostCSS` actually works as a postprocessor (though it can be a preprocessor as well).

In short, `PostCSS` is built flexibly as a pre/post processor.

This truly is the next level of CSS. Thanks!

**Comment by ai** [comment]
It accepts CSS as a string because pure JS doesn’t have file system APIs and we want to run PostCSS in any JS runtime, not only Node.js :).

So we decided that we have PostCSS core and environment tools like `gulp-postcss` or `postcss-cli`. And environment tools will read files in the best way in this environment.
