### ISSUE TITLE
Inconsistent whitespace for `after` with cloned nodes

### ISSUE THREAD

**Issue by mgol** [postcss/postcss#1137]
See http://astexplorer.net/#/gist/b7bd890d25272696356f82506c1094a8/70748e4e86a57be7e2817b73206bba62e6269299

Putting it here for posterity as well:
```js
const postcss = require('postcss');

module.exports postcss.plugin('my-plugin', () => root => {
	root.walkAtRules('media', atRule => {
    	const newRules = atRule.clone();
      	newRules.walkRules(rule => {
            rule.selector = `foo, ${ rule.selector }`;
        });
	    atRule.after(newRules.nodes);
	});
});
```

If you use `after` with cloned nodes to unwrap a media query, the first invocation prepends extra whitespace whereas next invocations don't do that.

In the test case you'll see an extra new line but in my local testing with latest PostCSS on similar examples I got a few spaces extra, not a new line. The basic issue stays the same, though.

**Comment by ai** [comment]
Sorry, the current auto-spacing algorithm is too tricky. I afraid to change it. I will fix an issue in one place and add in few others :D.

My policy right now: “auto-spacing algorithm works as-is”. If you want smarter—set `raws` property manually. Or even use any beautifuler after :D.

Is this issue is critical for your case?

**Comment by mgol** [comment]
It's not critical for me, it just required me to tweak the expected test results so that it anticipates different spacing for the first occurrence. Perhaps I should be passing the output through a formatter as you advised to not worry about it in tests.

**Comment by ai** [comment]
OK, I will close the issue until somebody will bring me a good algorithm for dealing with spaces which will cover all cases :).

But thanks for the report.
