### ISSUE TITLE
Critical dependency for plugins in webpack

### ISSUE THREAD

**Issue by AngeIII** [postcss/postcss#1139]
node_modules/postcss-functions/dist/index.js
Critical dependency: the request of a dependency is an expression
```
plugin = require('postcss').plugin
export default plugin('postcss-functions', (opts = {}) => {
```

for webpack and to run this in browser it needs to be a plain class/object/function.

**Comment by ai** [comment]
@AngeIII Yeap. Should we open a issue in postcss-functions?

**Comment by AngeIII** [comment]
@ai yes, looks like postcss working good in webpack, but postcss-function latest version has "glob" added which produced this critical dependency, after removing this everything is working good.
fork: https://github.com/wpbakery/postcss-functions

**Comment by ai** [comment]
@AngeIII what I can do in postcss core to fix postcss-functions? Maybe we should fix postcss-functions?

**Comment by AngeIII** [comment]
@ai I think there is no need to fix anything in postcss core :+1: , but in postcss-function there are options.glob:
```
functions[name] = require(file);
```
this cannot be bundled in webpack, and I don't see any possibility to fix it without removing :/

**Comment by ai** [comment]
Could you open a issue in https://github.com/andyjansson/postcss-functions

I have not access to that repo to fix error.
