### ISSUE TITLE
how not add sourceMappingURL key

### ISSUE THREAD

**Issue by cccisbug** [postcss/postcss#1144]
thanks  you，

after one css file exec  postcss command, then  append 'sourceMappingURL' data at the end，how can control it not append?

**Comment by cccisbug** [comment]
just add '--no-map'

**Comment by ai** [comment]
Here are JS API options to control source maps: https://github.com/postcss/postcss/blob/master/docs/source-maps.md

If you need so disable source map at all set `map: false`. If you want to generate source map, but disable `sourceMappingURL` set `map: { annotation: false }`.

`--no-map` is [PostCSS CLI](https://github.com/postcss/postcss-cli/) API. Maybe you can define JS API options in `postcssrc.js`, which will be read by PostCSS CLI.
