### ISSUE TITLE
Add LazyResult#finalize

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1146]
To be compatible with current Promise spec

**Comment by igorkamyshev** [comment]
Do you mean `finalize` or `finaly`?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

May I try to implement that?

**Comment by ai** [comment]
`finally` 😅

Sure, please send PR to `amy` branch.

**Comment by igorkamyshev** [comment]
Done #1154

**Comment by igorkamyshev** [comment]
Do I need to do something else to solve this issue?

**Comment by ai** [comment]
Congrats =^_^=

**Comment by igorkamyshev** [comment]
Thanks! 😁
