### ISSUE TITLE
Using PostCss as a standalone processor for CSS strings

### ISSUE THREAD

**Issue by tomgallagher** [postcss/postcss#1150]
I want to use the power of PostCSS outside of a build process, using the JS API on a node.js server to optimize CSS.

I'm struggling a bit with the best options for doing this. At the moment I have this:

```
const postcss = require('postcss');
const safe = require('postcss-safe-parser');
const uncss = require('uncss');
const cssnano = require('cssnano');

const returnUsedCSS = function(html, css) {
    
    return new Promise( (resolve, reject) => {
        const options = {raw: css};
        uncss(html, options, function (error, output) {
            if (error) { debug(error); reject(); }
            resolve(output);
        });
    });
    
};

const generateMinifiedCSS = function(html, originCSS) {
    
    return new Promise( (resolve, reject) => {
        const nanoOpts = {};     
        postcss([]).process(originCSS, { parser: safe, from: 'undefined', to: 'undefined', map: false})
            .then(result => returnUsedCSS(html, result.css) )
            .then(css => cssnano.process(css, nanoOpts) )
            .then(result => { 
                debug(result.css);
                resolve({optimisedCSS: result.css});
            })
            .catch(err => reject(err));
    });
    
};
``` 
Can anyone point me towards some resources for using the PostCSS JS API outside the build process?

**Comment by ai** [comment]
1. You don’t need to wrap `postcss().process` into Promise since `process()` return a Promise. Just do `return postcss().process(…)`
2. You must to set `from` and `to`. Where did you read `originCSS`? Just put the path to `originCSS` file to `to` and `from`.
3. You must pass `uncss` and `cssnano` as plugins. When you call PostCSS with zero plugins `postcss([])` it doesn’t do anything. Do `postcss([cssnano, uncss.postcssPlugin]).process()`

**Comment by ai** [comment]
As result, the final code:

```js
const postcss = require('postcss');
const safe = require('postcss-safe-parser');
const uncss = require('uncss');
const cssnano = require('cssnano');

const generateMinifiedCSS = function(html, originCSS) {
    const nanoOpts = {};     
    return postcss([uncss.postcssPlugin, cssnano(nanoOpts)]).process(originCSS, { parser: safe, from: 'path/to/file.css', to: 'path/to/file.css', map: false })
};
```

**Comment by tomgallagher** [comment]
Thanks very much for the help and the re-code.

I am reading css from memory, it is never part of the file system and I do not write it to a file. I just send it as an object elsewhere. Does it matter if the file exists, if I have set map to false? Or should I read and write with a blank file that I create?

I had a long search last night and the JS API has very few, if any, articles or guides associated with it when postcss is used outside the build process. There is the good API documentation but getting started is a bit of a challenge.

Thanks again.

**Comment by ai** [comment]
Hm. If you don't need source map and you use safe parser (so there will be no way messages) you can miss `from` and `to`.

**Comment by ai** [comment]
Will this website useful for you?
http://api.postcss.org

**Comment by tomgallagher** [comment]
Yes, I have been looking at that, but with all detailed API guides you need a basic level of competence before they actually start to make sense.

> you use safe parser (so there will be no way messages) 

What's a way message?

**Comment by ai** [comment]
Way message = error message

**Comment by ai** [comment]
If you have a idea how to improve docs, feel free to send pull request.

It is always better to wire docs by person, who try to learn a tool. Since you see what is problem parts. Maintainers are always bad in writing docs done they know anything.
