### ISSUE TITLE
Accessing `from` option from a plugin

### ISSUE THREAD

**Issue by just-boris** [postcss/postcss#1155]
I am currently upgrading my postcss plugin to the new version.  The plugin was using the current file name from the `from` option to do some logic.

Since PostCSS v6.x the API has changed, so `processOpts` and `pluginOpts`.  So, now I have to pass `from` option twice:

```js
const from = '/path/to/my/file.css'
await importsResolver.process(cssSource, { from }, { from });
```

Is this indented behavior or a missing feature?

**Comment by ai** [comment]
```js
postcss.plugin('name', () => {
  return (root, result) => {
    result.opts //=> options
  }
})
```

**Comment by just-boris** [comment]
That works, thank you!
