### ISSUE TITLE
Improve Readme Introduction

### ISSUE THREAD

**Issue by kschiffer** [postcss/postcss#1156]
This project is really great but I think you could help newcomers a big deal by changing the readme introduction a little bit. I think it is right now a little to complicated to be easily understood. I am thinking about something like this after the first sentence:
> Put simply, `postcss` transforms CSS into an "abstract syntax tree" (AST) which provides an extensive API to analyze its rules iteratively. This API can then be used by [plugins](https://github.com/postcss/postcss#plugins) to do any arbitrary operation on these rules, like eg. linting or automatic vendor prefixes.

Not sure if this is 100% accurate but I think you get the point. Something like this would have helped me greatly to understand what postcss does at first glance.

**Comment by ai** [comment]
Good idea. Let’s add it as the 3rd paragraph before links block. Do you want to send a PR?

**Comment by kschiffer** [comment]
Done.
