### ISSUE TITLE
Path issue on Linux servers

### ISSUE THREAD

**Issue by bschatz12** [postcss/postcss#1159]
Latest release has broken all our builds. Example: 
npm ERR! fetch failed https://nexusrepo.ace.aaaclubnet.com/repository/npm-group/postcss/-/postcss-6.0.23.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
We think it is maybe due to the - in the path: ...postcss/-/postcss-6.0.23.tgz

**Comment by ai** [comment]
It is just an npm issue with the cache.

It happens sometimes with any npm package. PostCSS is just very popular package this is why you can see `postcss` in this type of error more often.

Sorry, I have no idea how to fix this issue with npm. You may have an error in cache, mirror or some other infrastructure around npm.
