### ISSUE TITLE
NexusIQ has quarantined this version

### ISSUE THREAD

**Issue by bschatz12** [postcss/postcss#1160]
NexusIQ has quarantined this version of postcss (v.6.0.23). This breaks our builds. We can probably override the quarantine. But you should inquire from Sonatype why the quarantine.

**Comment by ai** [comment]
Never worked with NexusIQ before.

Can you tell me more about it and why it could quarantine PostCSS version?

Maybe you can ask their support?

**Comment by ai** [comment]
@bschatz12 ping

**Comment by Martodox** [comment]
@ai It is not an isolated issue.
I run into an error `Error: Cannot find module 'postcss'` with Nexus proxy, so that could be the reason why @bschatz12's setup has quarantined that version.

Any idea why that error occurs on 6.0.23 and not on 6.0.22 ?

**Comment by ai** [comment]
Have no idea. 6.0.23 was very small release with docs and regexp fixes. https://github.com/postcss/postcss/commit/5f7c79d48a70f6cae16a1a4c727e61648f8a9916

Nothing was changed in npm infrastructure. This is why I think it is a proxy error.

**Comment by ai** [comment]
Sorry, I never use Nexus proxy and have no idea how to works.

If you will some changes, feel free to open an issue.
