### ISSUE TITLE
Suggestion: throw error if plugin does not support PostCSS version

### ISSUE THREAD

**Issue by OliverJAsh** [postcss/postcss#1165]
I recently ran into an issue whereby my CSS output was very messed up:

- only nesting one level deep compiled (https://github.com/jonathantneal/postcss-nesting/issues/37#issuecomment-401784444)
- nested selectors in compiled output had wrong order (https://github.com/jonathantneal/postcss-nesting/issues/37#issuecomment-401786769)

I *believe* the culprit ended up being the fact I was using postcss-nesting 2.3.0 within postcss 6, and postcss-nesting 2.3.0 does not have support for postcss 6. I fixed the issue by upgrading to postcss-nesting 3.0.0, which is the first version that does have support for postcss 6.

I wanted to suggest that we make PostCSS throw an error early if you try to use a plugin which does not yet support this version of PostCSS, instead of the current behaviour which is to fail silently.

This would have save me several hours of debugging, and it's highly likely other users will run into similar issues when trying to upgrade their libraries.

This took me awhile to debug and I'm keen to improve the experience for the next user who hits a similar problem.

What do you think? :-)

Related https://github.com/postcss/postcss/issues/163 https://github.com/jonathantneal/postcss-nesting/issues/57

**Comment by jonathantneal** [comment]
@OliverJAsh, I want to add that I’m truly sorry that you had to lose so many hours looking into this issue, and I appreciate you taking the time to write up these issues.

While it’s easy for me to excuse the issue you reported, and which was reported by others by responding with “Your plugin was over a year out of date. Bye!”, I don’t think that’s entirely fair of me, because neither my README.md or any other text document in the library’s repository defined my level of support.

This is something I want to improve in all of the open source projects I maintain. If you would be honest, did you check the project’s documentation before filing an issue? It’s okay to say I didn’t, because I’m only interested in helping protect future users from losing similar time. I want my libraries to be trusted as being very high quality.

Related: https://twitter.com/jon_neal/status/1013767405183684609

**Comment by OliverJAsh** [comment]
@jonathantneal That's very kind of you. I want to be clear that I'm not blaming anyone—this is difficult to get right. It's great to hear that you care about this and want to get it right.

I realise the version of postcss-nesting which we were using was far behind the latest version. However, on our small team, we can only invest in upgrades when we have good reasons for doing so, especially considering we have so many modules in our project.

Recently, we wanted to upgrade to webpack v4, which required a new major version of postcss-loader, which required a new major version of postcss. We did all of that, but then noticed our CSS output was off. If there was a version mismatch somewhere, I expected an error, but there was none. 

For awhile it wasn't clear what part of oust PostCSS setup was to blame, as users were experiencing all sorts of issues.

When I eventually pinpointed the issue to nesting, I did check the documentation for the version of postcss-nesting I was using, but it made no mention of what PostCSS version it supported. In the end, I ended up inferring this information from the changelog, which mentioned PostCSS 6 support being added in postcss-nesting 3.0.0.

Perhaps it would have helped if postcss-nesting documented what the support was with regards to PostCSS versions. However I think the real issue here is that this all failed silently. This should have failed quickly and loudly, so it was clear where and when an upgrade was necessary.

It's tempting just to say "fix this by upgrading everything to the latest version", but in my experience, upgrades just swap old bugs with new bugs. Furthermore, in many cases, a year of no upgrades can mean we're behind on several major versions, meaning a full upgrade could require a lot of work. We want to find the shortest path to achieving our goal, whatever that may be, so we would much prefer to deal in terms of small, transparent fixes.

**Comment by ai** [comment]
Right now:

1. We try to run any plugin
2. If plugin throwed a error, we check plugin PostCSS version. If it was different version, we print a warning before the error.

So we already check it. Maybe you want to make this UI better?

**Comment by ai** [comment]
Yeap, I understand that in your case this check will be useful. But it will be terrible in other cases:

1. Most of PostCSS major releases didn't break a compatibility. Like PostCSS 7 will just remove Node.js 4 support.
2. Blocking plugins with different PostCSS version will make PostCSS major release a terrible experience. For few first month most of plugins will not support it and you will not be able to update anything.

Maybe you have a idea of solution for all cases?

**Comment by OliverJAsh** [comment]
I don't have any suggestions I'm afraid, but I would prefer too much information (potentially false positives) than no information at all (i.e. silent failures).

**Comment by ai** [comment]
For the whole history of PostCSS, it is the first time when plugin started to work different instead of t he throwing a error.

I will think about warning for any old plugins if we will have this case again.
