### ISSUE TITLE
Update docs: clone no longer removes raws

### ISSUE THREAD

**Issue by straker** [postcss/postcss#1169]
The docs for `clone` say that the cloned node will have clean code style properties. From what I could find, I think as of version 6 that is no longer the case.

Also, is there a recommended way to remove the code style properties for cloned nodes and all child nodes?

**Comment by ai** [comment]
Oops. Do you want to send PR?

Use `Node#cleanRaws`

**Comment by straker** [comment]
Awesome. I can send a pr later today. Thanks

**Comment by straker** [comment]
Closed via #1170
