### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by hudochenkov** [postcss/postcss#1171]
PostCSS 7.0 [introduced](https://github.com/postcss/postcss/commit/4208a1828242cb4316f68b03c654b98bc58d2663) new warnings:

> You did not set any plugins, parser, or stringifier. Right now PostCSS do nothing. Pick plugins for your case on https://www.postcss.parts/ and usem them in postcss.config.js.

Unfortunately, it backfired big time in [stylelint](https://github.com/stylelint/stylelint). When we run tests, [we receive](https://travis-ci.org/stylelint/stylelint/jobs/405145270) this warning 15 707 times. Probably, because we use default parser without plugins in many places. We just need an AST in these places, so defaults are good for us.

Would you reconsider adding this warning, please?

**Comment by ai** [comment]
There is also another option to replace `postcss().process(css).root` to more correct `postcss.parse(css)` in your tests ;).

Can you check the tests, maybe it is only a few places (which are reused in 15 707 places).

If you call it many times, you can write a small regexp to replace it in all tests.

(But I know your pain, I fix many places in PostCSS tests too to hide this warning, I just think that it is a good reason to make tests code more correct.)

**Comment by ai** [comment]
Sure. Will wait for your review. Maybe warning check is wrong.

**Comment by hudochenkov** [comment]
I dig a little bit. And the first thing I found is [`getPostcssResult()`](https://github.com/stylelint/stylelint/blob/0d0a7a1383fc9463905875bc00aeb871d59d2c96/lib/getPostcssResult.js#L106) which is used all the time (each stylelint run). Basically it's `postcss().process()` without any plugins. Every rule and many internal things rely on `result` from it. We can't replace it with `postcss.parse`, because it returns very different thing.

If I understand correctly the only way to get rid of this warning without changing PostCSS is to rewrite half of stylelint, which is crazy :)

**Comment by ai** [comment]
Can you just fix `getPostcssResult()`. If it calls `postcss()` only there it will solve the problem everywhere else.

**Comment by hudochenkov** [comment]
I'm afraid not, because we need `LazyResult`, every rule, and plugin expects it. Is there another way to get `LazyResult` but `postcss().process()`?

**Comment by ai** [comment]
Do you need just `Result` or `LazyResult` specific? PostCSS plugins receive `Result`.

**Comment by hudochenkov** [comment]
I guess it's `LazyResult`, because when I replaced `postcss().process()` with `postcss.parse().toResult()` 301 test out of 13652 broke. And we still had 153 warnings from tests for our small functions.

I didn't notice any pattern in fails, except many `Unknown word (CssSyntaxError)` when we expected reported violation from stylelint rule.

**Comment by ai** [comment]
Not sure, that creating a `LazyResult` is the best way here, but here another way:

```
const LazyResult = require('postcss/lib/lazy-result')

const processor = postcss()
const result = new LazyResult(processor, 'a{}', { from })
```

**Comment by hudochenkov** [comment]
Thank you! Now tests all green, and we need only change tests, which use PostCSS directly.

Is this solution a “right” way? Feels like creating `LazyResult` manually is a hack, and `postcss().process()` is more correct.

**Comment by ai** [comment]
There both way are hacky 😣. `LazyResult` was created to very different purpose.

**Comment by hudochenkov** [comment]
While I was working on stylelint tests I found a limitation of `.parse`. Looks like it's impossible to use non-default syntax. 

The [following](https://github.com/stylelint/stylelint/blob/0d0a7a1383fc9463905875bc00aeb871d59d2c96/lib/utils/__tests__/isStandardSyntaxDeclaration.test.js#L225-L231) code:

```js
postcss()
    .process(css, { syntax: scss, from: undefined })
    .then(result => {
      return result.root.walkDecls(cb);
    });
```

Doesn't apply custom syntax, when converted to:

```js
postcss.parse(css, { syntax: scss}).walkDecls(cb);
```

**Comment by ai** [comment]
Just replace `postcss.parse` to other syntax parse function.

**Comment by hudochenkov** [comment]
Thank you for your help and time!

**Comment by danielo515** [comment]
I am using postcss through webpack. Is there a way I can silence the warnings? I just don't care in certain scenarios

**Comment by ai** [comment]
> Is there a way I can silence the warnings? I just don't care in certain scenarios

Look sources for the secret parameter (I do not want to promote it since this warning is important for performance)

**Comment by danielo515** [comment]
Maybe a link to the file I should look at 😄?

**Comment by shawn-p-m** [comment]
> Maybe a link to the file I should look at 😄?

Any update on this? lol
