### ISSUE TITLE
Monorepo for plugins

### ISSUE THREAD

**Issue by halfzebra** [postcss/postcss#1173]
Thanks for PostCSS!

With emerging necessity for plugin presets, plugins have to stay in sync with PostCSS.

I totally understand that such an idea requires an enormous amount of involvement from maintainers and contributors, but perhaps it could be a good step towards the future of PostCSS?

For example, to upgrade posts-preset-env maintainers would need to get almost 29 plugins upgraded, 10 of them are hosted under [PostCSS org](https://github.com/csstools/postcss-preset-env/network/dependencies).

Here's an issue for the reference: https://github.com/csstools/postcss-preset-env/issues/58

Babel did this long time ago and it's proven to be a decent way of doing it:
https://github.com/babel/babel/tree/master/packages

**Update**
Please feel free to close this issue if you find it irrelevant.

**Update**
Added more numbers for the reference.

**Comment by ai** [comment]
Hi. It is not possible, since most of plugins are controlled by different people.

**Comment by ai** [comment]
The same. They are not official. They just made by people who speak often together.
