### ISSUE TITLE
Add `postcss-mixins` into plugins list

### ISSUE THREAD

**Issue by AlexWayfer** [postcss/postcss#1174]
https://github.com/postcss/postcss-mixins

**Comment by AlexWayfer** [comment]
@ai but it's not:

![](https://i.imgur.com/xTplOsj.jpg)

**Comment by AlexWayfer** [comment]
Oh, I see [plugins list page](https://github.com/postcss/postcss/blob/master/docs/plugins.md) now. But I don't understand why there is [separate minimal list in the README](https://github.com/postcss/postcss/blob/master/README.md#plugins).

**Comment by ai** [comment]
This short list is highlighted plugins that we recommend

**Comment by ai** [comment]
Because we recommend PreCSS which include postcss-mixins

**Comment by AlexWayfer** [comment]
> Because we recommend PreCSS which include postcss-mixins

OK, thanks. Sorry, I'm newbie with PostCSS.
