### ISSUE TITLE
Differentiate variable from declaration?

### ISSUE THREAD

**Issue by Siilwyn** [postcss/postcss#1175]
Wondering if it would be a good idea to differentiate between a `Declaration` and a variable in CSS.
E.g.: `--bg-color: blue;` would return the `Variable` instead of `Declaration`.

So instead of having to check the declaration property for `--` it would be provided by the parser.

Context:
- https://github.com/AleshaOleg/postcss-sass/issues/54
- https://github.com/Siilwyn/css-declaration-sorter/pull/51/

**Comment by ai** [comment]
It will be breaking change. But I am OK, if you will find a way without breaking changes.

**Comment by hzlmn** [comment]
One possible backward compatible solution is to add extra property to declaration for variables like with !important.

**Comment by ai** [comment]
Done f3df413

https://postcss.org/api/#declaration-variable
