### ISSUE TITLE
AtRule members are not presented in api doc

### ISSUE THREAD

**Issue by boccob** [postcss/postcss#1177]
For some reason `name`, `params` and `raws` properties are not displayed in `AtRule` documentation (http://api.postcss.org/AtRule.html) though they are presented in JSDoc.

**Comment by ai** [comment]
Do you have ideas why?

**Comment by boccob** [comment]
It's somehow connected with constructor of `AtRule`. I removed it and then missed properties appear in doc.

**Comment by ai** [comment]
I have no idea too 😣

**Comment by ai** [comment]
I am closing this issue. In 8.0 we plan to move to TypeDoc to fix problems like this.
