### ISSUE TITLE
No PostCSS Config

### ISSUE THREAD

**Issue by Yongest** [postcss/postcss#1190]
Error: No PostCSS Config found in: D:\张\frontend\frontend\build
    at D:\张\frontend\frontend\build\node_modules\postcss-load-config\src\index.js:55:15

node version:4.4.3.

**Comment by ai** [comment]
Hi. Do you have `postcss.config.js` in your project? If not, create it according `postcss-load-config` docs.

**Comment by Yongest** [comment]
i created postcss.config.js.
but now，can't prefixed   attribution ,like 'dispaly:flex;flex:1';how to do.     i use gulp and postcss.config.js: 

module.exports = {
    plugins: [
        require('autoprefixer')
    ]
}

**Comment by ai** [comment]
All modern browsers don’t need a prefix for Flexbox https://caniuse.com/#feat=flexbox
