### ISSUE TITLE
Get rid of "You did not set any plugins, parser..." warning

### ISSUE THREAD

**Issue by pribilinskiy** [postcss/postcss#1202]
We have a very simple configuration that simply checks whether it's a production environment and adds autoprefixer in that case, otherwise just returns an empty object, i.e.

```js
module.exports = {
	plugins: {},
};
```

But now we have a bunch of repetitive warnings when building in dev mode (multiconfig):
```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. 
Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

How to get rid of these?

**Comment by ai** [comment]
Change logic to not call PostCSS for non-production cases.

This warning is really helpful for you. 90% of Autoprefixer runtime is compiling CSS by PostCSS. By passing empty plugins you anyway spend this 90% in PostCSS. So your optimization just didn't work. Now PostCSS warms you about it.
