### ISSUE TITLE
Parsing selectors with comment

### ISSUE THREAD

**Issue by sswebcoder** [postcss/postcss#1204]
```javascript test.js
let LazyResult = require('./dist/lazy-result')
let Processor = require('./dist/processor')

let processor = new Processor.default()

let result = new LazyResult.default(processor, '.newbackbtn,/* .searchall, */.calNav {}', { })

console.log(result.result.root.nodes[0].selectors)
```
```bash
node test.js 
[ '.newbackbtn', '/* .searchall', '*/.calNav' ]
```

I think what comment should be excluded from selectors. It's right?
I'm trying to debug this, can somebody explain me this block https://github.com/postcss/postcss/blob/master/lib/parser.es6#L370

Thanks!

**Comment by hzlmn** [comment]
See https://github.com/postcss/postcss/pull/1109

**Comment by sswebcoder** [comment]
> See #1109. If you add space before and after comment it should be excluded.

But what I should do in case without spaces?

**Comment by sswebcoder** [comment]
I think what 

> Let's keep comments only inside identificator (letters and digits). Not between difficult like different tokens.

is meant what comment should be excluded if it located not in selector token. Right?

**Comment by hzlmn** [comment]
> is meant what comment should be excluded if it located not in selector token. Right?

In current api we can not know is comment part of single selector or multiple like in this case so decided to have at least one space from some side. See [Andrey's comment](https://github.com/postcss/postcss/issues/1066#issuecomment-335617884).

Going back to your question i am wondered why do you need such selector? Is it generated css?

**Comment by sswebcoder** [comment]
> Going back to your question i am wondered why do you need such selector? Is it generated css?

I'm trying to debug this https://github.com/stylelint/stylelint/issues/3729

**Comment by ai** [comment]
Use any library to parse selectors. Like https://github.com/postcss/postcss-selector-parser

Core’s `Rule#selectors` is very simple tool.
