### ISSUE TITLE
Default to an empty config if no config is found instead of throwing No PostCSS Config found

### ISSUE THREAD

**Issue by light24bulbs** [postcss/postcss#1205]
This module creates some weird issues when symlinking and other complex scenarios when it doesn't find a config that can be resolved by just putting an empty config.  Why does it not simply default to an empty config instead of throwing and requiring me to shim it?

**Comment by ai** [comment]
This is a core library. It doesn’t load `postcss.config.js`.

I think you should check this project and open issue there https://github.com/michael-ciniawsky/postcss-load-config

**Comment by ai** [comment]
> Why does it not simply default to an empty config instead of throwing and requiring me to shim it?

It is a big philosophical question of IT. If we will hide error and load empty config a lot of users will send us question “why PostCSS ignore my config”. I think that sometimes it is easier to tell about the error explicitly.

But, I am not the creator of config loader. Maybe he had different thoughts.
