### ISSUE TITLE
Sources key is badly overridden in the .sourcemap file when it should build upon a previous sourcemap.

### ISSUE THREAD

**Issue by rob-bar** [postcss/postcss#1211]
Hi,

I am trying to build upon a sass generated css file.
Every time I use postcss it just removes the information in the sources key from the sourcemap file and puts in the from file.

I have tried setting it up with the postcss-cli first and thought it was a problem in their repo, then I bypassed it by creating my own script in this example, but the problem persists.

It does nothing special, just some autoprefixing.
I have also read this: https://github.com/postcss/postcss/blob/master/docs/source-maps.md
But postcss does not really respect the previous sources from node-sass compilation.

postcss.config.js
```js
const yargs = require('yargs').argv;
const fs = require('fs');
const postcss = require('postcss');
const plugins = [require('autoprefixer')];

if (yargs.minify) {
  plugins = [require('postcss-csso')({ restructure: false })];
}

fs.readFile('./public/stylesheets/style.css', (err, css) => {
  postcss(plugins)
    .process(css, { from: './public/stylesheets/style.css', to: './public/stylesheets/style.css' , map: { inline: false }})
    .then(result => {
      fs.writeFile('./public/stylesheets/style.css', result.css, () => true);
      console.log(result.map);
      if ( result.map ) {
        fs.writeFile('./public/stylesheets/maps/style.css.map', result.map, () => true);
      }
    });
});

```

my package.json:
```
    "autoprefixer": "^9.3.1",
    "node-sass": "^4.11.0",
    "node-sass-glob-importer": "^5.2.0",
    "postcss": "^7.0.7",
    "postcss-csso": "^3.0.0"

scripts

    "compile:sass": "npx node-sass --include-path ./node_modules/react-image-gallery/styles/scss --include-path ./node_modules/singularitygs/stylesheets --include-path ./node_modules/breakpoint-sass/stylesheets --source-map ./public/stylesheets/maps --importer node_modules/node-sass-glob-importer/dist/cli.js ./frontend/sass -o ./public/stylesheets",
    "compile:postcss": "node postcss.config.js",
    "compile": "npm-run-all compile:sass compile:postcss",

```
its funny because an older project it works fine( same package.json but based upon postcss-cli), 
it respects the old sources key.

This must be broken by a minor upgrade.
Many thanks for the help!

Possible issue could be:
- same file, input is same as output.
- I never inline the sourcemap file.

**Comment by rob-bar** [comment]
As I inspect the sourcemap file beter, there is also a sourcesContent key available in the sourcemap
with the whole css in it, is this wanted?

**Comment by ai** [comment]
Feel free to send PR (cross-tool source map support is not number 1 priority for me right now, but I will be happy to answer a questions about PR and will merge and release it ASAP)

**Comment by rob-bar** [comment]
I see 2 solutions to this PR:
- Fix the bug and do care about previous sourcemapping like it was.
- Maybe also provide a way that post css does not touch the sourcemapping link in the bottom of the file at all? Is this even possible now? I think it gets stripped out either way.

**Comment by rob-bar** [comment]
if you just for example: change some values of properties...
the sourcemap will stay the same and you don't really want to update it I think.
Anyhow, the override problem is more important than the addition, since the doc says that this works but it doesn't.

**Comment by ai** [comment]
> if you just for example: change some values of properties...

I think it is better to update source map in this case. It is very fast.

**Comment by delicatesther** [comment]
I want to one-up this issue. Me and my colleagues have been struggling with source maps for a while now. 

We all compile sass to css, then use postcss to include autoprefixer and merge media queries etc, but it inevitably means source map issues. 

Personally I use postcss-cli, and either the default embedded map overwrites my perfectly fine nodesass source map and breaks it, the --map option removes my former source map and provides a faulty one, or the --no-map removes everything. 

My only option right now is to use --no-map and add the source to an external nodesass source map back in manually, which is, you know, insane.

**Comment by rob-bar** [comment]
Thanks Esther for the one up, this still needs a fix.
I have made a work around in the project by just doing the autoprefixing, in a later step.
Like that I have my source maps only in chrome when I am working and when I compile for test or prod environments I do the autoprefixing.

**Comment by ai** [comment]
If somebody have a solution, you can send PR

**Comment by papandreou** [comment]
I had [a test break in assetgraph with similar symptoms](https://travis-ci.org/assetgraph/assetgraph/jobs/479083491#L655-L679) when I upgraded from 7.0.9 to 7.0.10.

I bisected it down to [this commit](https://github.com/postcss/postcss/commit/0ccf7620433ab0b06eb4c5402748be10507e5278), but didn't really understand what that tried to accomplish. Then I got lazy and pinned postcss to 7.0.9, assuming it would be sorted out quickly :angel:

**Comment by ai** [comment]
@papandreou when you use multiple tools, you never could trust in source map. You need to error-less code in both tools (be sure that both Less and PostCSS generates correct source maps). It is always better to use PostCSS pure solutions if you want 100% correct source maps.

That commit resolved the issue. We can’t revert it or we will be jumping between issues (and it could be even Less issues as it happens much time before).

I really recommend you to use one parser for the whole stack. It will increase the performance (because parsing is the longest part) and stability.

(Or, of course, I am always for PR if you found the exact reason and know how to fix it without hurting anyone)

**Comment by papandreou** [comment]
@ai, thanks for taking a look. I think you're right, now that I look at the test case with https://sokra.github.io/source-map-visualization/ it looks like those source maps are severely busted. I remade the test case now with the latest version of the `less` compiler, and now it all works as expected, also with postcss 7.0.10+. Sorry for the noise, must have been due to bugs in `less` back in 2016 when the test was made.
