### ISSUE TITLE
Use TypeDoc instead of JSDoc

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#1221]
In response to @ai's comment [here](https://github.com/postcss/postcss/pull/1217#issuecomment-451640314), I suggest we use [JSDoc annotations to provide type information in JavaScript files](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript) w/o a TypeScript build step.

### Related
- https://github.com/postcss/postcss/issues/452

**Comment by ai** [comment]
Good idea

**Comment by jedmao** [comment]
@aoberoi you might like this idea too.

**Comment by aoberoi** [comment]
@jedmao interesting idea indeed! Could doing this work possibly help in the problem of having to synchronize the type definitions outside the source code? Specifically, do you know if there’s a way to run `tsc` to output declaration files (`.d.ts`) from comments in that style?

**Comment by aoberoi** [comment]
It seems the types that can be specified using JSDoc comments are still less expressive than TypeScript (most of the advanced types are missing, such as generics, mapped types, intersections, etc). However, if we’re not going to author the source code in TypeScript, this would still be a good compromise towards making PostCSS more usable for TypeScript users. 

I recently heard this advice: “if you aren’t going to write the code in TS, then no types is better than wrong types”. This leads me to believe that if we go down this route, we should remove the `.d.ts` file from this repo so that there’s only one source of truth (the JSDoc comments). Something to consider, since that’s quite a large trade off.

IMHO if we’re going to have an unsynchronized declaration file, it shouldn’t be in this repo, but rather in DefinatelyTyped, so that it’s opt-in and wrong declarations don’t get in the way of productivity.

**Comment by jedmao** [comment]
1. Yes, this would kind of solve the whack-a-mole situation we're in.
1. From what I understand, you would run `tsc --noEmit` on the js code to see if it passes the TS compiler.
1. I don't know if you can generate the `.d.ts` file from it, but I don't think you need to either, because it would just get the types directly from the JS source.
1. I'm not sure how less expressive the types are in JSDoc comments. Are you 100% sure they don't accept generics? Because I love generics! I understand the need for a compromise though.
1. I'm also wondering if we might want to add `// @ts-check` at the top of each file for additional type safety checks or if that's even needed.
1. Moving the `.d.ts` file to DefinitelyTyped might confuse some peeps though. Having two options is always confusing and I'm not even sure which one would override the other or if it would do some kind of declaration merging? Never done this before.

**Comment by jedmao** [comment]
This issue, should it be implemented, would also allow us to use [tsickle](https://github.com/angular/tsickle) to further optimize the bundle size.

As a side note, here is the history of PostCSS with respect to compilation steps.

## History of PostCSS
1. [Sep 7, 2013 - Initial commit in CoffeeScript](https://github.com/postcss/postcss/commit/2d96cea96e3a96f616c28f897358086a69caa506#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R15).
1. [July 23, 2014 - Converted into ES5 via Traceur](https://github.com/postcss/postcss/releases/tag/2.0.0).
1. [July 27, 2014 - via es6-transpiler](https://github.com/postcss/postcss/releases/tag/2.1.0).
1. [November 12, 2014 - via 6to5 (now Babel)](https://github.com/postcss/postcss/releases/tag/3.0.0).
1. [August 19, 2015 - Babel](https://github.com/postcss/postcss/releases/tag/5.0.0).
1. [January 17, 2019 (today) - Still using Babel](https://github.com/postcss/postcss/blob/adc1ed0338f61b4b815ffdf86c60c2f81ce26d6b/package.json#L36).

_Credit goes to @DrewML for pretty much everything above._

**Comment by DrewML** [comment]
> It seems the types that can be specified using JSDoc comments are still less expressive than TypeScript (most of the advanced types are missing, such as generics, mapped types, intersections, etc)

This is not accurate. I've yet to find a type I could not model with JSDoc. Per the constructs you mentioned:

## Generics + Mapped Types
```js
/**
 * @typedef {{ readonly [P in keyof T]: T[P] }} ReadonlyExample
 * @template T
 */
```
**VSCode showing TypeScript Language Service type**
![image](https://user-images.githubusercontent.com/5233399/51348865-5dda8100-1a69-11e9-8d4a-0adc486267d9.png)

## Union Types
```js
/**
 * @typedef {{ readonly [P in keyof T]: T[P] }} ReadonlyExample
 * @template T
 */

/**
 * @typedef {Object} Foo
 * @property {string} foo
 */

/**
 * @typedef {Object} Bar
 * @property {string} bar
 */

/**
* @typedef {Foo & Bar} FooBar
*/

/** @type {FooBar} */
const FooBarValue = {
    foo: 'foo',
    bar: 'bar',
    bizz: 'test' // bizz properly gets flagged as not being a member of Foo & Bar
};
```
**VSCode showing TypeScript Language Service type**
![image](https://user-images.githubusercontent.com/5233399/51349041-e527f480-1a69-11e9-9da5-d6f7b24a2170.png)

**Comment by DrewML** [comment]
> I recently heard this advice: “if you aren’t going to write the code in TS, then no types is better than wrong types”. This leads me to believe that if we go down this route, we should remove the .d.ts file from this repo so that there’s only one source of truth (the JSDoc comments). Something to consider, since that’s quite a large trade off.

Also note that, using JSDoc you can have the `tsc` command generate the `d.ts` file for you automatically. So code runs in node without compilation, but 1 command to generate type defs.

**Comment by ai** [comment]
I think I will move from JSDoc to TypeDoc in 8.0

**Comment by ai** [comment]
Done eeee4ab
