### ISSUE TITLE
Sourcemaps contain invalid mappings (even without any plugins)

### ISSUE THREAD

**Issue by mischnic** [postcss/postcss#1222]
PostCSS seems to generate or emit sourcemaps with mappings to non-existent positions. [In this visualisation](http://sokra.github.io/source-map-visualization/#base64,CmJvZHkgewoJYmFja2dyb3VuZC1jb2xvcjogcmVkOwp9Cgo=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUNBO0NBQ0Msc0JBQXNCO0NBQ3RCIiwiZmlsZSI6Im91dC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyJcbmJvZHkge1xuXHRiYWNrZ3JvdW5kLWNvbG9yOiByZWQ7XG59XG5cbiJdfQ==,CmJvZHkgewoJYmFja2dyb3VuZC1jb2xvcjogcmVkOwp9Cgo=), you can see that there is a mapping from/to line 3 col 23. But that line has only 23 columns (which are 0-indexed). 
This could be a off-by-one error or caused by incorrect usage of the source-map library.

I have some issues with sourcemaps in https://github.com/parcel-bundler/parcel, because when concatenating multiple css files, the last position from one CSS asset would then actually point to a different CSS asset. Chrome seems to handle them fine, but testing is becomes harder.

Input file:
```css

body {
	background-color: red;
}

```

Generated map:
```json
{"version":3,"sources":["src/style.css"],"names":[],"mappings":";AACA;CACC,sBAAsB;CACtB","file":"out.css","sourcesContent":["\nbody {\n\tbackground-color: red;\n}\n\n"]}
```

Code:
```js
const fs = require("fs").promises;
const postcss = require("postcss");

(async () => {
	const inputFile = "src/style.css";
	const contents = await fs.readFile(inputFile);

	const root = postcss.parse(contents, { from: inputFile });

	const result = root.toResult({
		to: "out.css",
		map: { inline: false, annotation: false, sourcesContent: true }
	});

	let { css, map } = result;
	console.log(map.toJSON());
	map = map.toString();

	await fs.writeFile("out.css", css);
	await fs.writeFile("out.css.map", map);
})();
```

**Comment by ai** [comment]
Hi. Thanks for the good report.

Unfortunately, I will be able to fix it only next week (sorry, other open source projects is in the line). If you want you can try to send PR to fix it quicker:

1. Here is a code which inserts mappings for the end of the rules https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L230-L247
2. If `Rule#source.end` is wrong, here is a code which calculates a position https://github.com/postcss/postcss/blob/master/lib/parser.es6#L321
3. Feel free to ask any question, I will try to answer ASAP

P. S. I started to use Parcel recently and was extremely satisfied with its DX. Thanks for your work in that projects.
