### ISSUE TITLE
Javascript API Example is missing 'utf8' from fs.readFile()

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss#1227]
It needs this:

`fs.readFile('css/app.css','utf8',`

Without the `utf8` the css looks like binary ...

**Comment by ai** [comment]
PostCSS will work with binary output as well. So there is no reason to change it in this example.

Even all non-latin Unicode symbols will be kept without this encoding option.

I think done should be clear and we can keep it without encoding details.

**Comment by oleersoy** [comment]
Ah - Very cool!
