### ISSUE TITLE
Regression in 7.0.12

### ISSUE THREAD

**Issue by hudochenkov** [postcss/postcss#1229]
Some stylelint tests are failing with 7.0.12. https://travis-ci.org/stylelint/stylelint/jobs/479975682

E. g.

```css
a { color/*comment*/:/*comment*/pink; }
a { color/*comment*/ : /*comment*/pink; }
a { color/*comment*/:/*comment*/pink; }
```

[Also](https://travis-ci.org/stylelint/stylelint/jobs/479975682#L781-L796):

```css
a { // color: pink; }
```

I'm not sure what parser we're using standard or safe-parser.

**Comment by ai** [comment]
Fixed 9c59b02

**Comment by ai** [comment]
Released in 7.0.13

**Comment by hudochenkov** [comment]
Amazing! Thank you for a quick fix! It fixed most of the problems.

Unfortunately, tests for [no-invalid-double-slash-comments](https://github.com/stylelint/stylelint/tree/master/lib/rules/no-invalid-double-slash-comments) rule are still [broken](https://travis-ci.org/stylelint/stylelint/jobs/480017257#L695-L711):

```css
a { // color: pink; }
```

**Comment by ai** [comment]
I am not sure that it is valid CSS

**Comment by hudochenkov** [comment]
It's not a valid CSS, but browser won't fail on parsing CSS with such comments. So people, who get used to such comments in other syntaxes produce invalid code, which stylelint trying to avoid.

https://stackoverflow.com/questions/12298890/is-it-bad-practice-to-comment-out-single-lines-of-css-with/20192639#20192639
https://www.xanthir.com/b4U10

**Comment by hudochenkov** [comment]
Maybe it's ok... The goal of that rule is to help a user to have no invalid code. With the latest change to PostCSS, the goal is still achieved. A user will be warned about invalid code. Warning message would be not user-friendly, though.

> Unknown word (CssSyntaxError)

Instead of:

> Unexpected double-slash CSS comment (no-invalid-double-slash-comments)

**Comment by ai** [comment]
> Let us know if it is, and we'll update the test in this rule too.

I think it should be syntax error on this input.

So let's update the test.

Sorry for broking tests. At least, I think everyone agree that invalid syntax is not a public API 😅.

This syntax error was added by real user because if really unpredictable behavior in his case.

**Comment by jeddy3** [comment]
> Sorry for broking tests

No worries! 

> So let's update the test.

I've updated the `value-list-comma-space-after` test and the CI is now green in the [PR](https://github.com/stylelint/stylelint/pull/3892).

@ai Thanks, as always, for your quick responses :)

**Comment by hudochenkov** [comment]
Thank you, @ai! It's always a pleasure to collaborate with you! :)
