### ISSUE TITLE
rule like 'stylus' -> colon, semicolon

### ISSUE THREAD

**Issue by mrG0bliN** [postcss/postcss#1238]
![image](https://user-images.githubusercontent.com/11839238/51628704-c5f00200-1f56-11e9-8886-2c35454470a9.png)
After I switch to postcss, can I use harmony when writing code like in stylus ??
Ignore the colon and semicolon!

**Comment by ai** [comment]
PostCSS doesn’t support Stylus. If you want compact syntax use [SugarSS](https://github.com/postcss/sugarss) (but you need to write colon).

**Comment by mrG0bliN** [comment]
@ai я в курсе что он не поддерживает, меня интересует возможность писать в похожем стиле, это же очевидно из картинки :(((

**Comment by ai** [comment]
Нет, такой возможности нет (возможность писать практически равна поддержки синтаксиса).

Если хочешь, можешь попробовать создать какой-то свой синтаксис и форкнуть SugarSS.

**Comment by mrG0bliN** [comment]
это парсер дописывать на js или свое что то экспортировать?

**Comment by ai** [comment]
> это парсер дописывать на js

На JS проще всего

**Comment by mrG0bliN** [comment]
окай, спасибо
