### ISSUE TITLE
Sometime the tag "scssOriginIndicator" remains in the css files after the parsing

### ISSUE THREAD

**Issue by vittalas** [postcss/postcss#1240]
postcss version: 7.0.14

Sometimes after the parsing there are some traces left behind in my css files like below; any clue why this key gets added and who adds it. If i have to debug this where do i begin with.

.title {
         font-size: 20px;
         margin-bottom: 5px;
         font-weight: 500;
+        scssOriginIndicator: "/Users/myplugins/src/sass/rrcon-ui.scss#2469";
     }
 
     .heading {
         font-weight: 500;
+        scssOriginIndicator: "/Users/myplugins/src/sass/rrcon-ui.scss#2475";
     }

**Comment by ai** [comment]
PostCSS doesn’t insert it. I think (because of the property name) it was created by Sass.

**Comment by vittalas** [comment]
This is way i have been trying to generate the ast's for the css files using the scss parser  (https://github.com/postcss/postcss-scss ) 
file.ast = postcss().process(fs.readFileSync(file.source, "utf8"), {parser: postcssScss}); 
Did you mean to say this package the scss parser does that ?

**Comment by ai** [comment]
Yeap. `postcss-scss` contains Sass compiler inside.
