### ISSUE TITLE
Expected a pseudo-class or pseudo-element

### ISSUE THREAD

**Issue by vssaini** [postcss/postcss#1246]
Hi,

This is my first time raising an issue.

I am studying [Git a Web Developer](https://www.udemy.com/git-a-web-developer-job-mastering-the-modern-workflow/) and added post css library. Now, facing error as follow - 

`Error in plugin "gulp-postcss"
Message:
    Expected a pseudo-class or pseudo-element.
Details:
    fileName: /Users/Vikram/Documents/DevLab/travel-site/app/assets/styles/styles.css

Stack:
Error: Expected a pseudo-class or pseudo-element.
    at Root._error (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:182:24)
    at Root.error (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/selectors/root.js:43:25)
    at Parser.error (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:666:25)
    at Parser.expected (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:994:25)
    at Parser.pseudo (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:799:25)
    at Parser.parse (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:955:22)
    at Parser.loop (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:923:18)
    at new Parser (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/parser.js:174:14)
    at Processor._root (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.processSync (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at parse (/Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-nested/index.js:9:9)
    at /Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-nested/index.js:39:18
    at Array.forEach (<anonymous>)
    at /Users/Vikram/Documents/DevLab/travel-site/node_modules/postcss-nested/index.js:38:21
    at Array.forEach (<anonymous>)`

The stack clearly mentions the error to be found in **postcss-nested/index.js**. I tried reinstalling the postcss but it doesn't help.

Due to this error, any styles further added are not working.

**Comment by ai** [comment]
Hi. Show you PostCSS plugin list (you may find it in your Gulpfile or in postcss.config.js) and input CSS.

**Comment by vssaini** [comment]
Hi @ai 

I found PostCSS plugin list in **package.json** as follow. There is no _postcss.config.js_ file.

{
  "name": "travel-site",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "^3.3.1",
    "normalize.css": "^8.0.1",
    "waypoints": "^4.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.3.3",
    "@babel/preset-env": "^7.3.1",
    "autoprefixer": "^9.4.7",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "browser-sync": "^2.26.3",
    "del": "^3.0.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "gulp": "^4.0.0",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-svg-sprite": "^1.5.0",
    "gulp-watch": "^5.0.1",
    "postcss": "^7.0.14",
    "postcss-hexrgba": "^1.0.1",
    "postcss-import": "^12.0.1",
    "postcss-mixins": "^6.2.1",
    "postcss-nested": "^4.1.1",
    "postcss-simple-vars": "^5.0.1",
    "webpack": "^4.29.4",
    "webpack-cli": "^3.2.3"
  }
}

and **input CSS** as follow - 

/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */

/* Document
   ========================================================================== */

/**
 * 1. Correct the line height in all browsers.
 * 2. Prevent adjustments of font size after orientation changes in iOS.
 */

html {
  line-height: 1.15; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
}

/* Sections
   ========================================================================== */

/**
 * Remove the margin in all browsers.
 */

body {
  margin: 0;
}

/**
 * Render the `main` element consistently in IE.
 */

main {
  display: block;
}

/**
 * Correct the font size and margin on `h1` elements within `section` and
 * `article` contexts in Chrome, Firefox, and Safari.
 */

h1 {
  font-size: 2em;
  margin: 0.67em 0;
}

/* Grouping content
   ========================================================================== */

/**
 * 1. Add the correct box sizing in Firefox.
 * 2. Show the overflow in Edge and IE.
 */

hr {
  box-sizing: content-box; /* 1 */
  height: 0; /* 1 */
  overflow: visible; /* 2 */
}

/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

pre {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}

/* Text-level semantics
   ========================================================================== */

/**
 * Remove the gray background on active links in IE 10.
 */

a {
  background-color: transparent;
}

/**
 * 1. Remove the bottom border in Chrome 57-
 * 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
 */

abbr[title] {
  border-bottom: none; /* 1 */
  text-decoration: underline; /* 2 */
  -webkit-text-decoration: underline dotted;
          text-decoration: underline dotted; /* 2 */
}

/**
 * Add the correct font weight in Chrome, Edge, and Safari.
 */

b,
strong {
  font-weight: bolder;
}

/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

code,
kbd,
samp {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}

/**
 * Add the correct font size in all browsers.
 */

small {
  font-size: 80%;
}

/**
 * Prevent `sub` and `sup` elements from affecting the line height in
 * all browsers.
 */

sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}

sub {
  bottom: -0.25em;
}

sup {
  top: -0.5em;
}

/* Embedded content
   ========================================================================== */

/**
 * Remove the border on images inside links in IE 10.
 */

img {
  border-style: none;
}

/* Forms
   ========================================================================== */

/**
 * 1. Change the font styles in all browsers.
 * 2. Remove the margin in Firefox and Safari.
 */

button,
input,
optgroup,
select,
textarea {
  font-family: inherit; /* 1 */
  font-size: 100%; /* 1 */
  line-height: 1.15; /* 1 */
  margin: 0; /* 2 */
}

/**
 * Show the overflow in IE.
 * 1. Show the overflow in Edge.
 */

button,
input { /* 1 */
  overflow: visible;
}

/**
 * Remove the inheritance of text transform in Edge, Firefox, and IE.
 * 1. Remove the inheritance of text transform in Firefox.
 */

button,
select { /* 1 */
  text-transform: none;
}

/**
 * Correct the inability to style clickable types in iOS and Safari.
 */

button,
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}

/**
 * Remove the inner border and padding in Firefox.
 */

button::-moz-focus-inner,
[type="button"]::-moz-focus-inner,
[type="reset"]::-moz-focus-inner,
[type="submit"]::-moz-focus-inner {
  border-style: none;
  padding: 0;
}

/**
 * Restore the focus styles unset by the previous rule.
 */

button:-moz-focusring,
[type="button"]:-moz-focusring,
[type="reset"]:-moz-focusring,
[type="submit"]:-moz-focusring {
  outline: 1px dotted ButtonText;
}

/**
 * Correct the padding in Firefox.
 */

fieldset {
  padding: 0.35em 0.75em 0.625em;
}

/**
 * 1. Correct the text wrapping in Edge and IE.
 * 2. Correct the color inheritance from `fieldset` elements in IE.
 * 3. Remove the padding so developers are not caught out when they zero out
 *    `fieldset` elements in all browsers.
 */

legend {
  box-sizing: border-box; /* 1 */
  color: inherit; /* 2 */
  display: table; /* 1 */
  max-width: 100%; /* 1 */
  padding: 0; /* 3 */
  white-space: normal; /* 1 */
}

/**
 * Add the correct vertical alignment in Chrome, Firefox, and Opera.
 */

progress {
  vertical-align: baseline;
}

/**
 * Remove the default vertical scrollbar in IE 10+.
 */

textarea {
  overflow: auto;
}

/**
 * 1. Add the correct box sizing in IE 10.
 * 2. Remove the padding in IE 10.
 */

[type="checkbox"],
[type="radio"] {
  box-sizing: border-box; /* 1 */
  padding: 0; /* 2 */
}

/**
 * Correct the cursor style of increment and decrement buttons in Chrome.
 */

[type="number"]::-webkit-inner-spin-button,
[type="number"]::-webkit-outer-spin-button {
  height: auto;
}

/**
 * 1. Correct the odd appearance in Chrome and Safari.
 * 2. Correct the outline style in Safari.
 */

[type="search"] {
  -webkit-appearance: textfield; /* 1 */
  outline-offset: -2px; /* 2 */
}

/**
 * Remove the inner padding in Chrome and Safari on macOS.
 */

[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}

/**
 * 1. Correct the inability to style clickable types in iOS and Safari.
 * 2. Change font properties to `inherit` in Safari.
 */

::-webkit-file-upload-button {
  -webkit-appearance: button; /* 1 */
  font: inherit; /* 2 */
}

/* Interactive
   ========================================================================== */

/*
 * Add the correct display in Edge, IE 10+, and Firefox.
 */

details {
  display: block;
}

/*
 * Add the correct display in all browsers.
 */

summary {
  display: list-item;
}

/* Misc
   ========================================================================== */

/**
 * Add the correct display in IE 10+.
 */

template {
  display: none;
}

/**
 * Add the correct display in IE 10.
 */

[hidden] {
  display: none;
}

body{
	font-family: 'Roboto', sans-serif;
	color: #333;
}

img{
	max-width: 100%;
	height: auto;
}

* {
	box-sizing: border-box;
}

a{
	color: #d59541;
}

.large-hero{
	border-bottom: 10px solid #2f5572;
	position:relative;

}

.large-hero__image{
		display: block;
	}

.large-hero__text-content{
	position: absolute;
	top: 50%;
	-webkit-transform: translateY(-50%);
	        transform: translateY(-50%);
	left: 0;
	width: 100%;
	text-align: center
   }

.large-hero__title{
	font-weight: 300;
	color: #2f5572;
	font-size: 2.4rem;
	margin:0;
   }

@media(min-width: 530px){

.large-hero__title{
		font-size: 4.8rem
   }
	}

.large-hero__subtitle{
	font-weight: 300;
	color: #2f5572;
	font-size: 1.5rem ;
	margin:0;
   }

@media(min-width: 530px){

.large-hero__subtitle{
		font-size:2.9rem
   }
	}

.large-hero__description{
   	font-weight:100;
   	color: #FFF;
   	font-size: 1.1rem;
   	text-shadow: 2px 2px 0 rgba(0,0,0,.1);
   	max-width: 30rem;
   	margin-left:auto;
   	margin-right:auto;
   }

@media(min-width: 530px){

.large-hero__description{
   		font-size: 1.875rem
   }
	}

.btn{
  	background-color: #2f5572;
  	color: #FFF;
  	text-decoration: none;
  	padding: .75rem 1.2rem;
  	display: inline-block;
  }

.btn--orange{
  		background-color: #d59541;
  	}

.btn--large{
  		padding: 1.1rem 1.9rem;
  	}

@media(min-width: 530px){

.btn--large{
        font-size: 1.25rem
  	}
	}

.wrapper{
	overflow:hidden;
	padding-left: 18px;
	padding-right: 18px;
	max-width: 1236px;
	margin-left: auto;
	margin-right: auto;
}

.wrapper--medium{
		max-width: 976px;
	}

.wrapper--no-padding-until-medium{
		padding-left: 0;
		padding-right: 0;
	}

@media(min-width: 800px){

.wrapper--no-padding-until-medium{
			padding-left: 18px;
	        padding-right: 18px
	}
	}

.wrapper--no-padding-until-large{
		padding-left: 0;
		padding-right: 0;
	}

@media(min-width: 1010px){

.wrapper--no-padding-until-large{
			padding-left: 18px;
	        padding-right: 18px
	}
	}

.wrapper .wrapper{
		padding-left: 0;
		padding-right: 0;
	}

.wrapper--b-margin{
		margin-bottom: 1rem;
	}

@media(min-width: 530px){

.wrapper--b-margin{
			margin-bottom: 3.875rem
	}
	}

.page-section{
	padding: 1.2rem 0;

  
}

@media(min-width: 800px){

.page-section{
		padding: 4.5rem 0

  
}
	}

.page-section--no-b-padding-until-medium{
    padding-bottom: 0;
  }

@media(min-width: 800px){

.page-section--no-b-padding-until-medium{
      padding-bottom: 4.5rem
  }
	}

.page-section--no-b-padding-until-large{
    padding-bottom: 0;
  }

@media(min-width: 1010px){

.page-section--no-b-padding-until-large{
      padding-bottom: 4.5rem
  }
	}

.page-section--blue{
	background-color: #2f5572;
	color: #FFF;
  }

.page-section--testimonials{
  	background-color: #e0e6ef;  	
  }

@media(min-width: 1010px){

.page-section--testimonials{
  		background: url('/assets/images/testimonials-bg.jpg') top center no-repeat;
  	    background-size: cover  	
  }
	}

.headline{
	font-size: 1.9rem;
	font-weight: 300;
	color: #2f5572;
}

@media(min-width: 530px){

.headline{
		font-size: 2.875rem
}
	}

.headline--centered{
		text-align: center;
	}

.headline--orange{
		color: #d59541;
	}

.headline--small{
		font-size: 1.2rem;
	}

@media(min-width: 530px){

.headline--small{
			font-size: 1.875rem
	}
	}

.headline--narrow{
		max-width: 500px;
		margin-left: auto;
		margin-right: auto;
	}

.headline--light{
		font-weight: 100;
	}

.headline--b-margin-small{
		margin-bottom: .5em;
	}

.headline--b-margin-large{
		margin-bottom: 1.6em;
	}

.headline--no-t-margin{
		margin-top: 0;
	}

.row::after{
		content: "";
		clear: both;
		display: table;
	}

.row--t-padding{
    	padding-top:80px;
    }

.row--gutters{
		margin-right: -65px;
	}

.row--gutters-large{
		margin-right: -100px;
	}

.row--gutters-small{
		margin-right: -45px;
	}

.row--gutters > div{
		padding-right: 65px;
	}

.row--gutters-large > div{
		padding-right: 100px;
	}

.row--gutters-small > div{
		padding-right: 45px;
	}

.row__b-margin-until-medium{
		margin-bottom: 1rem;
	}

@media(min-width: 800px){

	.row__b-margin-until-medium{
		margin-bottom: 0;  
	}

	.row__medium-4{
		float:left;
		width:33.33%;
	}

	.row__medium-4--larger{
		width:37%;
	}

	.row__medium-6{
		float: left;
		width: 50%;
	}

	.row__medium-8{
		float:left;
		width: 66.66%;

	}

	.row__medium-8--smaller{
		width:63%;
	}
	}

@media(min-width: 1010px){

	.row__b-margin-until-large{
		margin-bottom: 0;  
	}

	.row__large-4{
		float:left;
		width:33.33%;
	}

	.row__large-4--larger{
		width:37%;
	}

	.row__large-6{
		float: left;
		width: 50%;
	}

	.row__large-8{
		float:left;
		width: 66.66%;

	}

	.row__large-8--smaller{
		width:63%;
	}
	}

/* Begin Equal Height Rules */

@media(min-width: 800px){

.row--equal-height-at-medium{
			display: flex
	}
	}

.row--equal-height-at-medium > div{
			float: none;
			display: flex;
		}

@media(min-width: 1010px){

.row--equal-height-at-large{
			display: flex
	}
	}

.row--equal-height-at-large > div{
			float: none;
			display: flex;
		}

.generic-content-container p{
		font-weight: 300;
		line-height: 1.65;
		margin: 0 0 1.8rem 0;
	}

@media(min-width: 530px){

.generic-content-container p{
			font-size: 1.125rem
	}
	}

.generic-content-container p a {
		font-weight: 700;
	}

.section-title{
	font-size: 2.55rem;
	font-weight: 300;
	text-align: center;
}

@media(min-width: 530px){

.section-title{
		font-size: 3.75rem
}
	}

.section-title strong{
		font-weight: 500;
	}

.section-title__icon{
		display: block;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: .6rem;
	}

@media(min-width: 530px){

.section-title__icon{
			position: relative;
			top:8px;
			margin-right: .5rem;
			margin-left:0;
			margin-bottom: 0;
			display: inline-block
	}
	}

.section-title--blue{
		color:#2f5572;
	}

.feature-item{
	position: relative;	
	padding-bottom: 2.5rem;
}

@media(min-width: 530px){

.feature-item{
		padding-left: 94px
}
	}

.feature-item__icon{
		display: block;
		margin: 0 auto;
	}

@media(min-width: 530px){

.feature-item__icon{
			position: absolute;
		    left:0
	}
	}

.feature-item__title{
		font-size: 1.6rem;
		font-weight: 300;
		margin-top: .7em;
		margin-bottom:.8rem;
		text-align: center;
	}

@media(min-width: 530px){

.feature-item__title{
			text-align: left;
			margin-top: 1em;
			font-size: 1.875rem
	}
	}

.testimonial{
	background-color: rgba(255,255,255,.8);
	padding: 0 18px 1px 18px;
	margin-bottom: 98px;

}

@media(min-width: 1010px){

.testimonial{
		padding: 0 1.8125rem 1px 1.8125rem;
		margin-bottom: 0

}
	}

.testimonial--last{
		margin-bottom: 0;
	}

.testimonial__photo{
		border-radius: 80px;
		overflow: hidden;
		width: 160px;
		height: 160px;
		margin: 0 auto -80px auto;
		position: relative;
		top:-80px;
		border: 6px solid rgba(255,255,255,.8);
	}

.testimonial__title{
		color: #2f5572;
		text-align: center;
		font-size: 1.5rem;
		font-weight: 500;
		margin: 0
	}

.testimonial__subtitle{
		color:#d59541;
		text-align: center;
		font-weight: 400;
		font-size: 0.9375rem;
		margin:.25rem 0 1rem 0;
	}

/* Do not edit modules/_sprite directly as it is auto-generated by Gulp. Instead edit gulp/templates/sprite */

.icon{
	background-image: url('/assets/images/sprites/sprite-d675eadb.svg');
}

.icon--clear-view-escapes{
 	width: 142.4px;
 	height: 59.53px;
 	background-position: 0 0 ;
 }

.icon--comment{
 	width: 64px;
 	height: 64px;
 	background-position: 99.70443349753694% 0 ;
 }

.icon--facebook{
 	width: 21.23px;
 	height: 42.01px;
 	background-position: 26.040607071652357% 45.795830448496034% ;
 }

.icon--fire{
 	width: 56px;
 	height: 64px;
 	background-position: 0 99.56481481481481% ;
 }

.icon--globe{
 	width: 64px;
 	height: 64px;
 	background-position: 27.586206896551722% 99.56481481481481% ;
 }

.icon--instagram{
 	width: 42.01px;
 	height: 42.01px;
 	background-position: 63.2917018534157% 49.234556504346486% ;
 }

.icon--mail{
 	width: 64px;
 	height: 48px;
 	background-position: 0 48.00806451612903% ;
 }

.icon--rain{
 	width: 64px;
 	height: 64px;
 	background-position: 99.70443349753694% 59.25925925925926% ;
 }

.icon--star{
 	width: 64px;
 	height: 64px;
 	background-position: 59.11330049261084% 99.56481481481481% ;
 }

.icon--twitter{
 	width: 51.78px;
 	height: 42.06px;
 	background-position: 94.04330452560171% 98.50700323226104% ;
 }

.icon--wifi{
 	width: 60px;
 	height: 64px;
 	background-position: 68.79227053140097% 0 ;
 }

.icon--youtube{
 	width: 34.75px;
 	height: 42px;
 	background-position: 36.69752421959096% 45.792307692307695% ;
 }

.site-footer{
	background-color: #2f5572;
	color: #FFF;
	padding: .5rem 0;
	text-align: center;
}

.site-footer__text{
		display: block;
		margin-bottom: 1rem;
		font-weight: 200;
	}

@media(min-width: 800px){

.site-footer__text{
			display: inline;
			margin-bottom: 0;
			margin-right: 1.4rem
	}
	}

.site-header{
	padding: 10px 0;
	position: absolute;
	width: 100%;
	z-index: 2;
	background-color: rgba(47,85,114, .3);
}

.site-header__btn-container{
		float:right;
	}

.site-header__logo{
		top:0;
		position: absolute;
		background-color: #2f5572;
		padding: 25px 36px;
	}

.primary-nav--pull-right{
		float: right;
	}

.primary-nav ul {
		margin: 0;
		padding: 0;
	}

.primary-nav ul::after{
		content: "";
		clear: both;
		display: table;
	}

.primary-nav li {
		list-style: none;
		float: left;
		padding-right: 20px;
	}

.primary-nav a {
		text-decoration: none;
		color: #FFF;
		font-weight: 300;
		display: block;
		padding: 12px 0;
	}

**Comment by ai** [comment]
Can you upload your project somewhere, so I will be able to look at the code?

**Comment by vssaini** [comment]
Hi,

I think you can take a look over from the repository at [Travel Site](https://github.com/vssaini/travel-site).

**Comment by ai** [comment]
I fixed `postcss-nested`, not it prints much better error on syntax errors like this.

1. Update `postcss-nested` in your `package.json`: `"postcss-nested": "^4.1.2"`.
2. Install the update by `npm install` command.
3. Run your Gulp again. PostCSS will print better error (you have missed `;`)

**Comment by hirenkeraliya** [comment]
I have also got this error and I am trying to solve this for the last 3 days.

And, Today I got the solution.

```
.revenue-cards{
   @apply p-3 lg: p-4 rounded-xl h-auto;
}
```

In my CSS there is a simple space between `lg:` and `p-4`. I have changed it to `lg:p-4` and it's working fine.

And this would be done by the vs code.

**Comment by salmaniz82** [comment]
Hi there, this is first time I using purge css I followed the official instruction but this is not working for me. Getting the same error as mentioned in this ticket. 

![image](https://user-images.githubusercontent.com/21281162/213288810-55ba4e20-484b-49d8-b25e-e6661a70d983.png)

![image](https://user-images.githubusercontent.com/21281162/213288876-46f9f3bf-5e88-4ec4-989f-0864074ace57.png)

![image](https://user-images.githubusercontent.com/21281162/213288931-ba777a28-d713-4234-b9dd-d9e42b3f476f.png)

I am sharing all screenshots, please check and let me know. 

Thanks.

**Comment by stephenharveycodes** [comment]
Hey there, join quite late here but I am having a similar issue when trying to run build. Here is the error I am getting.

Creating an optimized production build...
Failed to compile.

static/css/main.bdf57c4d.css from Css Minimizer plugin
Error: Expected a pseudo-class or pseudo-element.

You can find a direct link to the repo here: https://github.com/stephenharveycodes/gpt3_steve

Thank you @ai
