### ISSUE TITLE
How do we exclude multiple Locations?

### ISSUE THREAD

**Issue by blachawk** [postcss/postcss#1248]
I would like to exclude the following 2 locations, but what is the correct way to do it with this plugin? The following throws an error due to me not using correct syntax.

```
  excludeAssets: [/mystyles.css.*/,/playground/bundle.*.js/]
```

Thanks

**Comment by ai** [comment]
Hi. PostCSS doesn't have `excludeAssets`. Are you asking about some PostCSS plugin?
