### ISSUE TITLE
postss-bem version is too low

### ISSUE THREAD

**Issue by holidaypenguin** [postcss/postcss#1249]
# 中文
在 [language-extensions](https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions) 中的`postcss-bem` 版本过低，建议用[postcss-bem-fix](https://github.com/supermonkeyz/postcss-bem-fix)替换他的位置

# English
The version of `postcss-bem` in [language-extensions](https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions)  is too low. It is recommended to replace his location with [postcss-bem-fix](https://github.com/supermonkeyz/postcss-bem-fix).

**Comment by ai** [comment]
@holidaypenguin sure. Do you want to send PR?

**Comment by holidaypenguin** [comment]
Can I do it?

**Comment by ai** [comment]
@holidaypenguin yeap! Press the Edit button for this file on GitHub and send a pull request. Let's save your name in the project history.
