### ISSUE TITLE
CSS errors are displayed as TypeError: _this.setMessage is not a function

### ISSUE THREAD

**Issue by leiyangyou** [postcss/postcss#1252]
in node version 11.9.0, all CSS errors were outputted as TypeError: _this.setMessage is not a function

was able to get the correct behaviour by changing

```
  function CssSyntaxError(message, line, column, source, file, plugin) {
    var _this;

    _this = _Error.call(this, message) || this;
```
to

```
  function CssSyntaxError(message, line, column, source, file, plugin) {
    var _this;
    _Error.call(this, message);
    _this =  this;
```

this probably cause by a babel bug [https://github.com/babel/babel/issues/4485](https://github.com/babel/babel/issues/4485)

**Comment by ai** [comment]
I will try to update Babel, recompile and release new version today

**Comment by ai** [comment]
Updating Babel didn’t change compiled code :(. Do you have any idea how to fix it?

**Comment by ai** [comment]
How I can reproduce `TypeError: _this.setMessage is not a function`? I tried to run it on the latest Node.js 11.12 and everything works correctly.

**Comment by leiyangyou** [comment]
Looks like it's not a postcss error, but something induced by another plugin, favicons-webpack-plugin.

https://github.com/leiyangyou/postcss-error-reproduction

**Comment by ai** [comment]
> Looks like it's not a postcss error, but something induced by another plugin, favicons-webpack-plugin.

=^_^= Cool, so it is not issue for me
