### ISSUE TITLE
postcss-safe-parser parser bug

### ISSUE THREAD

**Issue by lolipop99** [postcss/postcss#1253]
use Syntaxes `postcss-safe-parser` cannot fix this bug。
```javascript
# bad css
@import 'a.css'
a: {
 color: red
}

# expect output
@import 'a.css';
a: {
 color: red
}
```

because postcss parse `@import "a.css"  a: { color: red }` will export the node arule.params `"\"/a.css\"\n.a"`

**Comment by ai** [comment]
Sorry, the idea of `postcss-safe-parser` is NOT fixing the syntax errors. It garantees that it will parser anything without an error. But the result could be incorrect.

**Comment by ai** [comment]
In this case, it is not obvious how to parse this example. Maybe you have a long at-rule parameters and decided to split it to several lines?

**Comment by ai** [comment]
I think the best case for you will be creating a custom PostCSS plugin, which will find cases like this and fix it according your case.

**Comment by lolipop99** [comment]
> I think the best case for you will be creating a custom PostCSS plugin, which will find cases like this and fix it according your case.

@ai ok. ths for your reply
