### ISSUE TITLE
postcss directory CssSyntaxError：unclosed string image

### ISSUE THREAD

**Issue by burkgames** [postcss/postcss#1254]
When I do a conversion to a folder，i got this error......

Because there is a picture below the folder, how can i avoid it?

thx very much~

![image](https://user-images.githubusercontent.com/4887816/55561888-82b7c980-5725-11e9-888b-405a2f581f13.png)

**Comment by burkgames** [comment]
When I do a conversion to a folder，i got this error......

Because there is a picture below the folder, how can i avoid it?

thx very much~

![image](https://user-images.githubusercontent.com/4887816/55561473-ca8a2100-5724-11e9-9075-a25b45561d1b.png)

**Comment by ai** [comment]
Seems like `node-sass` sends PNG images to `postcss`, which broke input.

Try to change a way how you convert CSS. Maybe `gulp-postcss` is a good idea.

I am closing it since it is not PostCSS core issue.
