### ISSUE TITLE
Removing rules or rules' declarations is causing unwanted line breaks

### ISSUE THREAD

**Issue by ianthedev** [postcss/postcss#1256]
Style sheet:

```HTML
<style>
h1 { font-size: 20px; }

h2 { font-size: 20px; }

h3 { font-size: 20px; }
</style>
```

JavaScript:

```JavaScript
var root = postcss.parse(document.querySelector('style').innerHTML);

root.each(function (rule)
{
    // Create a new rule and insert it before the old rule.
    var newRule = postcss.rule({ selector: rule.selector + '.new' });
    newRule.append(postcss.decl({ prop: 'color', value: '#000' }));
    newRule.append(postcss.decl({ prop: 'font-weight', value: '400' }));
    rule.before(newRule);

    // Remove the old rule.
    rule.remove();
});

console.log(root.toString());
```

The expected result is:
```
h1.new { color: #000; font-weight: 400; }

h2.new { color: #000; font-weight: 400; }

h3.new { color: #000; font-weight: 400; }
```

But the actual result is containing unwanted line breaks:

```
h1.new {

    color: #000;

    font-weight: 400
}

h2.new {

    color: #000;

    font-weight: 400
}

h3.new {

    color: #000;

    font-weight: 400
}
```

During my testings, I also found that removing old rules' declarations instead of removing old rules is causing the same unwanted line breaks, too. In other words, in JavaScript, changing `rule.remove()` to `rule.walkDecls(function (decl) { decl.remove() })` is causing the same unwanted line breaks, too.

**Comment by ai** [comment]
Just copy `Declaration#raws` from existed declaration inside rule to keep origin code style. Or you can set `Declaration#raws` to any specific value.

The error happens because you remove all origin declarations. As a result, PostCSS doesn’t have any declaration example to copy code style. It looks at how you write rules and copy a double new line from it.

The code style system is already too complicated (and I do not know how to make it simpler). This is why I recommend two options:

1. Care about whitespaces in your plugin by setting `Node#raws`.
2. Use `stylelint  --fix` or any other plugins to control whitespaces after your plugin.

**Comment by ianthedev** [comment]
@ai 

Do you mean setting the `.raws` object for each new rule and the `.rawCache` object for the root, such as the following updated code?

```JavaScript
var root = postcss.parse(document.querySelector('style').innerHTML);

root.each(function (rule)
{
	// Create a new rule and insert it before the old rule.
	var newRule = postcss.rule({ selector: rule.selector + '.new' });
	newRule.raws = { after: " ", before: "\n", between: " ", semicolon: true };
	newRule.append(postcss.decl({ prop: 'color', value: '#000' }));
	newRule.append(postcss.decl({ prop: 'font-weight', value: '400' }));
	rule.before(newRule);

	// Remove the old rule.
	rule.remove();
});

root.rawCache = { beforeDecl: " ", beforeRule: "", colon: ": ", indent: "" };

console.log(root.toString().trim());
```

I tested it and it does help me get the ideal code format in the result. But I'm not sure if that's what you mean exactly and if that can cause unwanted side effects. Could you please advise?

**Comment by ai** [comment]
> Do you mean setting the .rawCache object for the root, such as the following example?

Yeap, `rawCache` is a good option in your case.

However, `rawCache` doesn’t affect whitespaces in nodes, that you do not create in your plugin. So it doesn’t feet all cases. If it works for you, keep it.

**Comment by ianthedev** [comment]
> Yeap, `rawCache` is a good option in your case.
> 
> However, `rawCache` doesn’t affect whitespaces in nodes, that you do not create in your plugin. So it doesn’t feet all cases. If it works for you, keep it.

I see. Thank you very much!
