### ISSUE TITLE
Migrate from JSDoc to Documentation.js

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1264]
- [x] Create HTML generator
- [ ] Fix fonts
- [x] Trim Globals from menu (do not forget that types are still in HTML)
- [x] Improve `generateDocs()` readability

/cc @isolovev

**Comment by ai** [comment]
@isolovev fonts still doesn’t work

**Comment by isolovev** [comment]
I removed Asap font and added system-ui font

**Comment by ai** [comment]
In your latest PR page use serif font, which doesn’t fit the style (we need sans serif).

Also, it does not look like the real fix. Why origin font was not loaded?

**Comment by isolovev** [comment]
[Proof](https://github.com/ur300/documentation-theme-light/pull/10/files#diff-087a8fead74c133dc919c9503a9b54f4R2)
I added sans-serif family font.

**Comment by ai** [comment]
https://i.imgur.com/bpNtTzK.png

Table and link to JS file have serif font

**Comment by isolovev** [comment]
Will you try clean cache?

**Comment by ai** [comment]
The same result with the disabled cache. DevTools shows that you forget to clean `Asap` font definition from `.documentation` rule.

**Comment by isolovev** [comment]
Resolve ur300/documentation-theme-light#10
