### ISSUE TITLE
Finding info on ...

### ISSUE THREAD

**Issue by blaasvaer** [postcss/postcss#1266]
How do I find info on getting equal heights on grid elements with this tool?

I seem to have to read ALL documentation to figure out whether this is supported at all or not.

How can the documentation be optimized to get a better overview of the capabilities of the tools? The 'few' examples doesn't really cut it ... unless of course, that's all the tool does …

**Comment by ai** [comment]
1. PostCSS is a framework to make CSS tools. It doesn’t do anything with Grid.
2. PostCSS ecosystem has [Autoprefixer](https://github.com/postcss/autoprefixer), which can generate `-ms-` prefix for Grid to use it in IE. Hoverewer, it doesn’t have any helpers or anything in addition to Grid spec.

Are you asking about Grid layout spec in general? Or you have some issue with Autoprefixer?

**Comment by blaasvaer** [comment]
Harh, sorry, I was meant to post this on the lost grid tool ... talking about 'overview' ; )

**Comment by ai** [comment]
Here is help about Grid syntax: https://css-tricks.com/snippets/css/complete-guide-grid/

According this guide, you should use:

```css
.container {
  align-items: stretch;
}
```

**Comment by ai** [comment]
Here is Lost Grid repo: https://github.com/peterramsing/lost

You can ask a question there.

But I recommend you to use the standard CSS Grid Layout instead of any grid framework.

**Comment by blaasvaer** [comment]
Yeah, thanks, that's what I was supposed to do …
