### ISSUE TITLE
Should split out shorthand properties in CSS.

### ISSUE THREAD

**Issue by adjenks** [postcss/postcss#1268]
Some properties have a lot of trouble being handled in shorthand form with functions inside of them. For example: ["calc() does not work when used in the flex property"](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/850091/)
(I realise that link is broken but it exists in the bug list and can be found if you search for it: https://www.bing.com/search?q=calc%28%29+does+not+work+when+used+in+the+flex+property)

And example is that this doesn't work:
```
flex: calc(1) 1 150px;
```

but this does:
```
flex-grow: calc(1);
flex-shrink: 1;
flex-basis: auto;
```

So splitting them out for compatibility with Edge and other struggling browsers should be useful.

**Comment by adjenks** [comment]
I noticed a similar, non-bug related ticket, was previously closed for a similar request: https://github.com/postcss/postcss/issues/23

I think this would help with the "Use tomorrow’s CSS today!" claim on the home page.

**Comment by ai** [comment]
The idea behind PostCSS parser, that it doesn’t know semantic of CSS properties. For PostCSS is just key-value storage.

We are using this idea to keep parser simple and avoid releases on any new CSS property.

However, it is an important task. We just think that it will be better to do it in an additional layout on top of PostCSS parser.

**Comment by adjenks** [comment]
@ai I asked this question elsewhere and it was suggested to go here. Is there some other library/package/tool that you could recommend that would be better suited for this type of CSS manipulation?

**Comment by ai** [comment]
https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md#tools

Seems like nobody created this module yet
