### ISSUE TITLE
PostCSS on a CSS-in-JS contained project

### ISSUE THREAD

**Issue by amerllica** [postcss/postcss#1269]
I used PosCSS in several Reactjs projects. Now I wanna Use [Aphrodite](https://github.com/Khan/aphrodite) library for implementing CSS-in-JS (JSS) on my project, But I'm worried about  Cross-Browser CSS, in the PostCSS configuration I set the config to support browsers and then in the output CSS I saw many new CSS properties that PostCSS was generated for me.

Now how it can happen on JSS? how I can use PostCSS benefits on a JSS project?

**Comment by ai** [comment]
We recommend using zero runtime CSS-in-JS solutions like [astroturf](https://github.com/4Catalyzer/astroturf) or [linaria](https://github.com/callstack/linaria).

Compare to Aphrodite, zero time solutions have much better performance (no runtime on the client side, everything was made by Babel plugin during deploy) and support of many CSS tools including PostCSS.

**Comment by amerllica** [comment]
Dear @ai (Andrey), I love you 💋 You're my man. thanks for your response.
