### ISSUE TITLE
Cannot find module 'postcss'

### ISSUE THREAD

**Issue by SilverLeaves** [postcss/postcss#1270]
If i don't use `tsc`， it works well.
but my other files is .ts，so I get the error.
![图片](https://user-images.githubusercontent.com/31165554/57755074-8a09c400-7722-11e9-896a-ac9925f1a2c1.png)

**Comment by ai** [comment]
@SilverLeaves how it is related with PostCSS? (Sorry, I do not use TS and can’t help you with advice)

**Comment by SilverLeaves** [comment]
@ai I update the img, please have a look.

**Comment by ai** [comment]
@jedmao can you help here?

**Comment by SilverLeaves** [comment]
https://github.com/microsoft/TypeScript/issues/31405
