### ISSUE TITLE
🔍 Improving search on docs with Algolia's DocSearch

### ISSUE THREAD

**Issue by Shipow** [postcss/postcss#1271]
Hello PostCSS team,<br><br>I've noticed that your documentation could take advantage of our <a href='https://community.algolia.com/docsearch/'>DocSearch</a> initiative.<br><br>So, we went on <b>trying to improve the search and came up with this:</b><br>💖<a href='https://docsearch-postcss.netlify.com/'>Try out the search here</a> 💖 (we've added docsearch.js to a mirror of the documentation).<br><br>Algolia's DocSearch is crawling the website every 24h, extracting content from every page. Then this content is made searchable by Algolia's API and exposed to the user with a searchbox and its custom dropdown.<br><br>You might have already used DocSearch on some popular docs like <a href='https://getbootstrap.com/docs/4.1/getting-started/introduction/'>Bootstrap</a>, <a href='https://vuejs.org/v2/guide/'>Vue</a>, <a href='https://api.jquery.com/'>jQuery</a>, <a href='https://reactjs.org/docs/getting-started.html'>React</a>, <a href='https://jestjs.io/docs/en/api'>Jest</a>, <a href='https://docs.gitlab.com/'>Gitlab</a>, <a href='https://docs.brew.sh/'>Brew</a>, <a href='https://devcenter.heroku.com/'>Heroku</a>, <a href='https://support.invisionapp.com/'>Invision</a>, <a href='https://stripe.com/docs'>Stripe</a>, <a href='https://www.algolia.com/doc/'>Algolia</a>, ...<br>So far, we are maintaining our crawler for 1500+ docs.<br><br><img src='https://res.cloudinary.com/hilnmyskv/image/upload/v1558102381/docsearch-dropdown.png' alt='docsearch autocomplete preview'><br><br><ul><li><a href='https://community.algolia.com/docsearch/'>DocSearch</a> is fast, it handles typos and highlighting.</li><li>Search results jump directly to the matching part of the page.</li><li>Whenever your markup changes you can <a href='https://github.com/algolia/docsearch-configs/blob/master/configs/postcss_api.json'>customize the configuration</a> on DocSearch repository.</li><li>You'll also have access to a dashboard of the most queries terms, as well as those that yields no results. We found it to be a very good way of knowing how to improve our documentation.</li><li>DocSearch is and will remain <b>FREE</b> (provided by <a href='https://www.algolia.com/'>Algolia</a>).</li></ul><br><b>Would that be something you'd be interested in?</b><br><br><br>Ping @shipow or @s-pace 🚀<br>

**Comment by ai** [comment]
Hi. Interesting tool (also I was in Algolia office, you have a great team).

I am not sure about PostCSS (we use static generated Documentation.js template). But I am try to implement DocSearch for my new [Logux](https://github.com/logux/logux) first (docs there are more critical) and then will think about PostCSS.

**Comment by Shipow** [comment]
Hi Ai,
Thanks for the kind words!

The setup of DocSearch is done on our side so all you have to do really is to add the js snippet to the website, but.. yeah it needs a website :p

Let us know when you are ready for Logux by sending a [request on our form](https://community.algolia.com/docsearch/).

Keep it up with good stuff!

**Comment by ai** [comment]
How I can integrate this search in new API website? https://github.com/postcss/postcss/tree/ose

**Comment by Shipow** [comment]
Hey Andrey, I believe the most straightforward way is to [submit a request on our website](https://community.algolia.com/docsearch/#join-docsearch-program) so you'll receive the snippet and credentials from our system. Once you get this we can help you integrate it on a PR.

**Comment by ai** [comment]
Right now I do not want to use custom Documentation.js theme just because of the search. But I very like the whole project. You search definitely will be helpful for other projects.

**Comment by Shipow** [comment]
Actually let see with documentation.js team if DocSearch could be added as an options. We are already providing a default setup with some other generators like docusaurus, pkgdown, vuepress, ...
