### ISSUE TITLE
Could not load existing sourcemap of "node_modules/postcss/lib/map-generator.js".

### ISSUE THREAD

**Issue by nikowonde** [postcss/postcss#1272]
Hey, I tried adding postcss/postcssJs to my code and during build it gives me this error.

![error1](https://user-images.githubusercontent.com/45310446/58014067-aa5dc800-7b00-11e9-81eb-56cf9b63cb19.jpg)

I've implemented postcss-js this way and I use parcel-bundler to build my project.

```
const postcssJs = require("postcss-js");
const autoprefixer = require("autoprefixer");
const prefixer = postcssJs.sync([autoprefixer]);

        const style = prefixer({
            gridArea: X
        });

Y.style.gridArea = style

```

Am I doing something wrong or is it actually broken in some way?

**Comment by ai** [comment]
Install `postcss`, it could help.

I will try to look the source of the problem this week

**Comment by ai** [comment]
If it will not help, remove `node_modules` and install dependencies again.

**Comment by nikowonde** [comment]
> 
> 
> Install `postcss`, it could help.
> 
> I will try to look the source of the problem this week



> 
> 
> If it will not help, remove `node_modules` and install dependencies again.

Hey, thanks for quick reply. I believe parcel-bundler comes with postcss. But I still added it as dependency and I also tried deleting and installing all dependencies again with no luck.

**Comment by ai** [comment]
Seems like error came from `mozilla.SourceMapGenerator`. Can you put `console.log` and check what is inside `this.outputFile()`?

**Comment by nikowonde** [comment]
So I mentioned in the first post that error comes up during build, but I could've included also that it causes build to fail so I can't run it while having postcss(-js) activated.

**Comment by ai** [comment]
What is in `content` variable? Can you put `console.log` in sources?

**Comment by painty** [comment]
@nikowonde Maybe it's the packing tool's problem (Parcel? I guess.).  See [Parcel with source maps enabled cannot import LiveScript](https://github.com/parcel-bundler/parcel/issues/2408)

**Comment by kekexunxun** [comment]
@nikowonde I use "this.css += `${eol}/# sourceMappingURL=${content}/`;" solved this question

**Comment by ai** [comment]
@kekexunxun can I ask you to send PR to save you in project history?

**Comment by kekexunxun** [comment]
@ai just as @nikowonde said, use template-literal to replace '+', but then it won't work in IE
![image](https://user-images.githubusercontent.com/44473551/60424216-6e02a900-9c22-11e9-8853-42d986dd9854.png)

**Comment by ai** [comment]
You can replace template string with `a.toString() +`. Who want to send PR?

**Comment by kekexunxun** [comment]
@ai I think the question is caused by \'/*\'. Take a look at this error, `/*# sourceMappingURL=` has omitted just beacuse
`191 |     var eol = '\n';
  192 |     if (this.css.indexOf('\r\n') !== -1) eol = '\r\n';
> 193 |     this.css += eol + ' + content + ' */';
      |                                        ^
  194 |     // this.css += `${eol}/# sourceMappingURL=${content}/`;
  195 |   };`
So I tried to remove this `*` and it worked.
And look the template string, it also removed `*`.
But it confused me when I used `"sanitize-html": "^1.20.1"` then it came up with this question, without it everything is fine.
So I'm not sure that what causes this problem.

**Comment by ai** [comment]
Seems like it is Parcel issue https://github.com/parcel-bundler/parcel/pull/2427
