### ISSUE TITLE
Warning "Previous source map found, but options.sourceMap isn't set"

### ISSUE THREAD

**Issue by SupinePandora43** [postcss/postcss#1276]
i fixed messages in script "**react-app-rewired start --scripts-version react-scripts-ts**"
adding to "css-rule","css-modules-rule","stylus-rule","stylus-modules-rule"
to all loaders option "**sourceMap:true**",
but i get warning in script "**react-app-rewired build --scripts-version react-scripts-ts**"
// "**devtool:"source-map**" doesn't help!

### log ###
yarn run v1.15.2
$ react-app-rewired build --scripts-version react-scripts-ts
Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@3.4.5 and E:\electron-app\tsconfig.prod.json
Compiled with warnings.

./src/stylus/index.styl
(Emitted value instead of an instance of Error)

 ⚠️  PostCSS Loader

Previous source map found, but options.sourceMap isn't set.
In this case the loader will discard the source map entirely for performance reasons.
See https://github.com/postcss/postcss-loader#sourcemap for more information.

./src/stylus/App.styl
(Emitted value instead of an instance of Error)

 ⚠️  PostCSS Loader

Previous source map found, but options.sourceMap isn't set.
In this case the loader will discard the source map entirely for performance reasons.
See https://github.com/postcss/postcss-loader#sourcemap for more information.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  136.05 KB  build\static\js\main.1a2b2f7a.js
  269 B      build\static\css\main.cd0ea0bd.css

The project was built assuming it is hosted at /electron-app/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
To publish it at https://supinepandora43.github.io/electron-app, run:

  yarn run deploy

Find out more about deployment here:

  http://bit.ly/2vY88Kr

Done in 100.19s.

**Comment by ai** [comment]
Sorry, it is a configuration problem. I can’t help here.

Try to open an issue at your boilerplate or what do you use to create a configuration.

**Comment by SupinePandora43** [comment]
i use https://github.com/marcopeg/react-app-rewire-stylus-modules. and i can't open issue because its a fork!
so... in which situations this message showed up?! @ai

**Comment by ai** [comment]
> in which situations this message showed up?!

I have no idea. This message came from `postcss-loader`. I am not a maintainer of this module for a year and this message was added after I gave a project to another person.

You can look at `postcss-loader` sources and put `console.log` there to debug the reasons of this message.

**Comment by SupinePandora43** [comment]
@ai i will try this, but i dont know how to debug npm scripts! yes i can put console.log but i think it will be not very effective

**Comment by ai** [comment]
> i can put console.log but i think it will be not very effective

This is a way which I am using for a years 😅 It’s work.

**Comment by SupinePandora43** [comment]
only hardcore!

**Comment by SupinePandora43** [comment]
i see'd difference between webpack.config.dev.js and webpack.config.prod.js (in react-scripts-ts), and now i know why rule.use.foreach cause error in production build!
### steps to fix PostCSS warnings ###
1 - build script needs env var `GENERATE_SOURCEMAP=false`
2 - add it to config-overrides.js:
`if (process.env!=="production") {
		const findIndexAndRules = (rulesSource, ruleMatcher) => {
			let result = undefined;
			const rules = Array.isArray(rulesSource) ? rulesSource : ruleChildren(rulesSource);
			rules.some((rule, index) => result = ruleMatcher(rule) ? { index, rules } : findIndexAndRules(ruleChildren(rule), ruleMatcher));
			return result;
		}
		const findRule = (rulesSource, ruleMatcher) => {
			const { index, rules } = findIndexAndRules(rulesSource, ruleMatcher);
			return rules[index];
		}
		function enableSourceMap(loader1) {
			if (loader1 instanceof String) {
				loader1 = { loader: loader1 };
			}
			loader1.options = Object.assign({ sourceMap: true }, loader1.options);
		}
		const cssRule = findRule(config.module.rules, (rule) => rule.test && String(rule.exclude) === String(/\.module\.css$/));
		const stylRule = findRule(config.module.rules, (rule) => rule.test && String(rule.exclude) === String(/\.module\.styl$/));
		const cssModulesRule = findRule(config.module.rules, (rule) => !rule.exclude && rule.test && String(rule.test) === String(/\.css$/));
		const stylModulesRule = findRule(config.module.rules, (rule) => !rule.exclude && rule.test && String(rule.test) === String(/\.module\.styl$/));
		[cssRule.use, stylRule.use, cssModulesRule.use, stylModulesRule.use].forEach((use) => {
			use.forEach((loader) => {
				enableSourceMap(loader);
			});
		})
	}`

// yes i'm using react-app-rewired(1.6.2 because react-scripts-ts don't updated webpack config) !

**Comment by SupinePandora43** [comment]
now issue really closed!

**Comment by SupinePandora43** [comment]
code here: https://github.com/SupinePandora43/electron-app
