### ISSUE TITLE
Questions about variables resolution

### ISSUE THREAD

**Issue by jesusreal** [postcss/postcss#1280]
This is a question, not an issue, but I really want to know why it behaves like that and I think it could be useful as reference for other people.

#### CSS input
```
:root {
  --color-root-1: red;
  --color-root-2: white;
}

.fd-shellbar {
  --color-block-bg: blue;
  --color-block-2: var(--color-root-2);
  color: var(--color-root-1);
  background-color: var(--color-block-bg);
  color: var(--color-block-2);
}
```

#### CSS output
```
:root {
  --color-root-1: red;
  --color-root-2: white;
}

.fd-shellbar {
  --color-block-bg: blue;
  --color-block-2: var(--color-root-2);
  color: red;
  color: var(--color-root-1);
  background-color: var(--color-block-bg);
  color: var(--color-block-2);
}
```

These are my questions:

1. Being _--color-root-2_ defined only once and only in _:root_, and being _--color-block-2_ defined only once and only being used in the block where it is defined, why not output this?
```
  color: white;
  color: var(--color-block-2);
```
2. Being _--color-block-bg_ defined only once and only being used in the block where it is defined, why not output this?
```
  background-color: blue;
  background-color: var(--color-block-bg);
```

Is the reason for not doing these transformations that they are very time consuming?

Instead of polluting the description I created a repo with the codebase I have used to perform my tests: https://github.com/jesusreal/postcss-playground.

**Comment by ai** [comment]
This is a good question for postcss-custom-properties plugin. This repo is for core parser and I do not know answer for your question, sorry.

**Comment by jesusreal** [comment]
For future reference, [here](https://github.com/postcss/postcss-custom-properties/issues/185) the issue in the [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties/) repo.
