### ISSUE TITLE
SASS Source-Map Error

### ISSUE THREAD

**Issue by Melluish** [postcss/postcss#1281]
When running PostCSS with the autoprefixer plugin on a CSS file that was compiled from SASS using the "sass" npm package, I get the following error:

```
> testsitecom@1.0.0 css-prefix /var/www/testsitecom
> postcss httpdocs/css/main.css --use autoprefixer -b 'last 2 versions' -r

Error: Unsupported source map encoding charset=utf-8
```

Here's the start of the source-map line it struggles with:

`/*# sourceMappingURL=data:application/json;charset=utf-8...`

Here's the "scripts" block of my package.json:

```
"css-compile": "sass --embed-source-map httpdocs/scss/main.scss:httpdocs/css/main.css",
"css-prefix": "postcss httpdocs/css/main.css --use autoprefixer -b 'last 2 versions' -r",
"css-minify": "postcss httpdocs/css/main.css --use cssnano -o httpdocs/css/main.min.css",
"css": "npm-run-all css-compile css-prefix css-minify"
```

**Comment by ai** [comment]
I am right now in Atakama dessert. Can you try to change `lib/input.js` or `lib/map-generator.js` in `ose` branch?

**Comment by Melluish** [comment]
So it seems they're inlining it as URL-encoded JSON rather than Base64 encoded. in `lib/previous-map.es6` in the `decodeInline` function line 82:

`let uri = 'data:application/json,'`

I can't test this at the moment so this is super sketchy, but if you add another var underneath that:

`let charsetUri = new RegExp('^data:application/json[,;](charset=utf-8,)?(?!base64)');`

And then before the first IF block add this:

```
let charsetUrlMatch = text.match(charsetUri);
if (charsetUriMatch !== 'null') {
      return decodeURIComponent(text.substr(charsetUriMatch[0].length));
}
```

**Comment by Melluish** [comment]
Apart from the few typos (now edited) I just tried those changes here and it worked fine. I did a test with another SASS compiler that outputs them inlined as base64 and that still worked.

**Comment by Melluish** [comment]
I'm a bit of a n00b anyway so don't worry too much :) You enjoy your holiday man!

**Comment by ai** [comment]
I believe in you 👍 Test is a good start.

**Comment by Melluish** [comment]
Cheers mate!

Cleaned it up a bit on my lunch break. Here's my version of the "decodeInline" function. Please be aware that I'm not really familiar with source maps, but from what I can see the embedded type come in two flavours: The actual map JSON is either Base64 encoded, or URL encoded. If this observation is incorrect then please ignore me :)

```
_proto.decodeInline = function decodeInline(text) {
    let re = /data:application\/json[,;](charset=utf-?8[,;])?(base64,)?/;
    let matches = text.match(re);
    let mapJSON = text.substr(matches[0].length);

    if (typeof matches[matches.length - 1] === 'undefined') {
      return decodeURIComponent(mapJSON);
    }
    return fromBase64(mapJSON);

    var encoding = text.match(/data:application\/json;([^,]+),/)[1];
    throw new Error('Unsupported source map encoding ' + encoding);
  };
```

Again I tested it here with an inline map produces from both the "sass" package (URL encoded, with charset) and the "node-sass" package (Base64 encoded, no charset) and it still worked for both.

**Comment by ai** [comment]
@Melluish great! Can you send PR?

1. Press Fork button in PostCSS repo.
2. Clone your fork.
3. `git checkout ose`
4. Add test to `test/previous-map.test.js`
5. Fix `lib/previous-map.js`
6. `git checkout -b json-map`
7. `git commit -m "Add application/json source map support"`
8. `git push origin json-map`
9. Send PR from your fork page on GitHub

**Comment by Melluish** [comment]
I think that went okay. My first time 🤦‍♂

**Comment by ai** [comment]
@Melluish you did it great. Do you have a Twitter account to mention your in release tweets?

**Comment by Melluish** [comment]
I don't I'm afraid, but no worries. Thanks for being patient with me. Have a great weekend.

**Comment by notlee** [comment]
hey @ai,  I ran into the same issue using inline source maps from dart-sass. I see [@Melluish's contribution was merged](https://github.com/Melluish/postcss/commit/e6418acb8b3d899c41cf9a58d31faf691dd912a3) into the `ose` branch last year. I was wondering what this branch is and if it will be released? Thanks for your work on postcss 😄

**Comment by ai** [comment]
@notlee we are now collecting funds to buy a working time and release `ose` (we need this time to write good migration docs, rewrite plugins, made few extra refactorings).

If your company uses PostCSS you can talk to your manager about funding us.
https://opencollective.com/postcss/

Or you can help us with a retweet
https://twitter.com/PostCSS/status/1227280750506057728
