### ISSUE TITLE
Directives to ignore specific tags

### ISSUE THREAD

**Issue by gterras** [postcss/postcss#1287]
Hi, 

Is there a way to prevent PostCSS to parse some parts of a file ? 

Having some PHP tags in the CSS throws a `Unknown word` error.  

PostHTML has a `directives` option like so : 
`directives: [{ name: '?php', start: '<', end: '>' } ]`. 

Does a similar feature exists in PostCSS ?

**Comment by ai** [comment]
Nope. You need to write custom parser (it is extremely hard to make plugable parser fast).

We have a docs about writing custom parses in PostCSS docs. Or you can write to surrender@evilmartians.com for commerical support and we will write custom parser for you.

**Comment by gterras** [comment]
All right mate thanks for answering :+1:
