### ISSUE TITLE
Tokenizing fails when font property line height value is set from custom property

### ISSUE THREAD

**Issue by lauriii** [postcss/postcss#1298]
Tokenizer fails to tokenize font property correctly if line-height is using a custom property. Example of CSS that is not tokenized correctly:

```
html { font: 1em/var(--line-height); }
```

Tokenizer seems to think that `1em/var` is a function.

I created a failing test for this here: https://github.com/lauriii/postcss/commit/87085589fa6ed303f0f2052f424214a54a804b72

This trickles down to https://github.com/shellscape/postcss-values-parser. I also created a failing test for that https://github.com/lauriii/postcss-values-parser/commit/d0bbbbcae47afee98f2d367e3fd0e525d0480cfe.

This finally trickles down to https://github.com/postcss/postcss-custom-properties. I did also create a failing test for that: https://github.com/lauriii/postcss-custom-properties/commit/6de537ec9c25c87f3f5b41be0dd0f353a9f83e28.

**Comment by ai** [comment]
Is it an issue for `postcss-values-parser`? I think they should use their own tokenizer.

**Comment by lauriii** [comment]
This indeed causes problems with `postcss-values-parser` but given that they use the PostCSS tokenizer, it seemed like it couldn't be fixed in that package. I opened an issue in that package, but I still think this might have to be fixed here.

> I think they should use their own tokenizer.
I don't know the history of that package but it seems like they just did a major refactoring from using their own tokenizer into using PostCSS tokenizer.

**Comment by ai** [comment]
Can you open an issue there? We will not able to fix tokenizer for every case. For instance, for postcss-safe-parser I copy pasted tokenizer.

**Comment by lauriii** [comment]
Thank you @ai for your prompt replies! 🙏 I'll try to work with the maintainer of that package to resolve this. ✌️

**Comment by shellscape** [comment]
postcss-values-parser _leverages_ the PostCSS base parser. There's a marked difference between using and leveraging. We inherit from and modify the behavior of the base parser. It's actually quite an efficient and reliable method and makes maintenance 1000x easier. These kind of edge cases are expected.

**Comment by ai** [comment]
> It's actually quite an efficient and reliable method and makes maintenance 1000x easier.

I am supporting the tokenizer in `potscss-scss`. It is not 1000x worse (check out special [patch comments in SCSS tokenizer](https://github.com/postcss/postcss-scss/blob/master/lib/scss-tokenize.es6#L58-L90)).

If you can’t send non-breaking changes PR, I can accept it.

**Comment by shellscape** [comment]
@ai no worries, I don't believe the issue is in PostCSS's tokenizer 😄 

The tokenizer in postcss-values-parser was always very difficult for me to maintain before I started leveraging PostCSS tokenizer - but please let me specify by saying that it was only difficult for me personally. I would never say that it would be 1000x worse for anyone else 👍
