### ISSUE TITLE
how to use in clojurescript?

### ISSUE THREAD

**Issue by qdhaiqiang** [postcss/postcss#1300]
I am using reagent+hiccup+shadow-cljs in my web project, I also want to use this plugins.

There are a lot of  introductions in blog, included Parcel、webpack、Gulp and so on，then how can i use in clojurescript project？

**Comment by ai** [comment]
Sorry, I have no idea, to be honest, because I never used Clojure.

Feel free to send PR to docs if you find a way.

**Comment by qdhaiqiang** [comment]
OK, I will.
Think you.
