### ISSUE TITLE
source maps access within plugin

### ISSUE THREAD

**Issue by SassNinja** [postcss/postcss#1312]
I've created a postcss plugin that extracts css and emits it as separate files

Right now I'm struggling with adding source maps to those files.
My idea is to simply take over the original map and inject it.

example gulp task

```javascript
function sass() {
  return gulp.src('src/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(postcss())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('dist'));
}
```

my plugin

```javascript
module.exports = postcss.plugin('my-plugin', opts => {
  return (root, result) => {
    // need access to source map here
  };
});
```

Unfortunately I'm only able to access the map after all postcss plugins are appplied meaning after the `sourcemaps.write()` pipe.

Is there any chance to achieve this?

**Comment by ai** [comment]
The official API for the source map is [`Node#source`](http://api.postcss.org/Node.html#source).

```js
// rule1 will be mapped to location of rule2
let rule1 = postcss.rule({ selector: 'a', source: rule2.source })
```

```js
let input4 = rule4.source.input // a.css

// Map rule3 to a.css:1:1…a.css:3:10
let rule3 = postcss.rule({
  selector: 'b',
  source: {
    input,
    start: { line: 1, column: 1 },
    end: { line: 3, column: 10 }
  }
})
```

Does this API is enough for you or you want something more tricky?

**Comment by SassNinja** [comment]
Hi @ai

does API provide any access to the input's source map?

As explained I'm emitting files myself, meaning the original postcss pipe doesn't know those so I need to add the map myself (a clone of the original one would be sufficient)

I've noticed I can access the source map when I change the order of my pipes into this (sourcemaps write BEFORE the postcss)

```
function sass() {
  return gulp.src('src/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(sourcemaps.write())
	.pipe(postcss())
    .pipe(gulp.dest('dist'));
}
```

then I can find the map in `root.source.input.map` tough this only works with inline source maps and is probably not intended to be used like this

if I stay with the regular order I cannot find any source map (always undefined)

is there any way to do this?

**Comment by ai** [comment]
As I know `sourcemaps.init()` deal with merging source maps on its own, so it doesn’t send map from previous step to next step

**Comment by SassNinja** [comment]
> As I know sourcemaps.init() deal with merging source maps on its own

but postcss is keeping this map alive so I assume it must have access to it (after the init pipe) or am I missing anything?

to come back to my initial question: do you know any way I can access the actual map within my postcss plugin or is does the problem not belong to postcss?

**Comment by ai** [comment]
PostCSS can update previous source map but in Gulp, Gulp updates it. This is why it doesn't need to send previous map to PostCSS.

Technically, tools doesn't not update source maps. They generate new source map and merge it with previous one. As result you have two steps (generating and merging) and Gulp can takes second task on it own.

**Comment by ai** [comment]
Happy New Year, BTW 🎅

**Comment by SassNinja** [comment]
> This is why it doesn't need to send previous map to PostCSS.

You mean gulp-postcss doesn't send the map to postcss?
If so I should probably submit my feature request there.

Happy New Year, too!
(though we still have to wait 2 hours in Germany until 2019 ends 😉)

**Comment by ai** [comment]
> You mean gulp-postcss doesn't send the map to postcss?

This is how I understand the problem

**Comment by SassNinja** [comment]
alright, seems I'm getting closer:

I've setup a webpack example and am able to access the map without problems.
Therefore I'll create an issue in the gulp-postcss repo

However in the course of this I've ended up with a new problem.
As mentioned above I've got now access to the [PreviousMap](https://api.postcss.org/PreviousMap.html) via `root.source.input.map` but it's not an annotation although I'm defined inline-source-map in the webpack config:

```javascript
devtool: 'inline-source-map',
module: {
    rules: [
        {
            test: /\.scss$/,
            use: [
                MiniCssExtractPlugin.loader,
                {
                    loader: 'css-loader',
                    options: {
                        sourceMap: true
                    }
                },
                {
                    loader: 'postcss-loader',
                    options: {
                        sourceMap: true
                    }
                },
                {
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true
                    }
                }
            ]
        }
    ]
},
```

instead the only thing that is map like is `root.source.input.map.text`

```
"{"version":3,"sourceRoot":"/Users/kfalkowski/Development/github/postcss-extract-media-query/examples/webpack","sources":["src/example.scss","src/_foo.scss","src/_bar.scss"],"sourcesContent":["@import 'foo';\n@import 'bar';\n.test { z-index: 1; }\n@media screen and (min-width: 1200px) {\n  .test { z-index: 2; }\n}",".foo { color: red; }\n@media screen and (min-width: 1024px) {\n  .foo { color: green; }\n}",".bar { font-size: 1rem; }\n@media screen and (min-width: 1024px) {\n  .bar { font-size: 2rem; }\n}"],"names":[],"mappings":"ACAA,AAAA,IAAI,AAAC,CAAE,KAAK,CAAE,GAAG,CAAI,AACrB,MAAM,CAAC,MAAM,MAAM,SAAS,EAAE,MAAM,EAClC,AAAA,IAAI,AAAC,CAAE,KAAK,CAAE,KAAK,CAAI,CCFzB,AAAA,IAAI,AAAC,CAAE,SAAS,CAAE,IAAI,CAAI,AAC1B,MAAM,CAAC,MAAM,MAAM,SAAS,EAAE,MAAM,EAClC,AAAA,IAAI,AAAC,CAAE,SAAS,CAAE,IAAI,CAAI,CFA5B,AAAA,KAAK,AAAC,CAAE,OAAO,CAAE,CAAC,CAAI,AACtB,MAAM,CAAC,MAAM,MAAM,SAAS,EAAE,MAAM,EAClC,AAAA,KAAK,AAAC,CAAE,OAAO,CAAE,CAAC,CAAI"}"
```

is there some built-in method to convert that PreviousMap into an annotation?

**Comment by SassNinja** [comment]
I've found [convert-source-map](https://www.npmjs.com/package/convert-source-map) that might do the job though the annotation is not 100% identical to the one in the file emitted by webpack and I'd prefer to not differentiate between inline & external source map myself but simply use what's about to get added to the original file

**Comment by ai** [comment]
Should we close this issue, since it is now about tricky cases with source maps, rather than a bug in PostCSS?

We can continue talking in closed issue. I just want to clean up my todo list :).

**Comment by ai** [comment]
> though the annotation is not 100% identical

Unfortunatelly, there is many way for you can cook your source map

**Comment by SassNinja** [comment]
> Should we close this issue, since it is now about tricky cases with source maps, rather than a bug in PostCSS?

sure, talking about converting source maps is not the initial purpose of this issue

seems I have to post issues first for all bundlers/runners that don't provide access to PreviousMap
