### ISSUE TITLE
NodeBase.toString()'s types don't include a parameter

### ISSUE THREAD

**Issue by nex3** [postcss/postcss#1313]
According to [the API docs](http://api.postcss.org/Node.html#toString), the `Node.toString()` function takes a parameter of type `stringifier | syntax`. However, this isn't reflected in the TypeScript interface:

https://github.com/postcss/postcss/blob/4d8a9859c6dbbbdfa159bd04939f6184ebedfe67/lib/postcss.d.ts#L603-L606

**Comment by ai** [comment]
Can I ask you to send PR? I am not TS user and mostly rely on PR to fix TS definitions.

**Comment by ai** [comment]
Released at 7.0.26.
