### ISSUE TITLE
Getting font resolution errors when introducing postcss

### ISSUE THREAD

**Issue by simkessy** [postcss/postcss#1314]
main.scss

    @import 'vendors'

vendors.scss

    @import 'bootstrap/dist/css/bootstrap.min.css';
    @import 'react-bootstrap-table/dist/react-bootstrap-table.min.css';
    @import 'react-bootstrap-typeahead/css/Typeahead.css';

Error: 

    ERROR in ./src/scss/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/scss/main.scss)
    Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.eot' in '/Users/user/code/pinboard/services/zdqa/client/src/scss'
     @ ./src/scss/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/scss/main.scss) 4:36-88

postcss.config.js

    module.exports = {
        // parser: 'sugarss',
        plugins: {
          'postcss-import': {},
          'postcss-preset-env': {},
          'cssnano': {}
        }
      };

webpack: 

      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } }
        ]
      },
      {
        // Compile scss into css files
        test: /\.scss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: process.env.NODE_ENV === 'development'
            }
          },
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'fonts/'
            }
          }
        ]
      }

**Comment by ai** [comment]
This error doesn’t come from the PostCSS core. `Can't resolve` comes from webpack, when it can’t find the file. Often it means that there is a problem with webpack config.

If you need help with front-end DevOps you can buy our support at [OpenCollective](https://opencollective.com/postcss/).
