### ISSUE TITLE
How can I parse an input css file to an array of property-value tuples

### ISSUE THREAD

**Issue by open-source-explorer** [postcss/postcss#1319]
I'm looking forward to parse an input `css` file to a format as [here](https://github.com/styled-components/css-to-react-native#api).

**Comment by open-source-explorer** [comment]
@ai any suggestions would be highly appreciated :clap:

**Comment by ai** [comment]
You can parse CSS into PostCSS AST (tree of objects, like DOM) and then convert this AST to any format.

For instance:

```js
function toArray (node) {
  if (node.type === 'decl') {
    return [node.prop, node.value]
  } else if (node.type === 'rule') {
    return [node.selector, node.nodes.map(toArray)]
  } else if (node.type === 'atrule') {
    return [`@${ node.name } ${ node.params }`, node.nodes.map(toArray)]
  }
}

let root = postcss.parse(css, { from })
return root.nodes.map(toArray)
```

You can check API at [AST Explorer REPL](https://astexplorer.net/) or check [postcss-js](https://github.com/postcss/postcss-js/).

If you need help with writing this tool and working from a big company, our [OpenCollective tiers](https://opencollective.com/postcss/) have support hours.

**Comment by open-source-explorer** [comment]
> If you need help with writing this tool and working from a big company, our OpenCollective tiers have support hours.

I didn't get this, can you elaborate?

**Comment by ai** [comment]
@open-source-explorer you can buy a time of me or other developer and I will write the parser

**Comment by open-source-explorer** [comment]
Gotcha :+1:
