### ISSUE TITLE
SourceMap Annotation string with file name

### ISSUE THREAD

**Issue by Pikachews** [postcss/postcss#1324]
I want to link the generated sourcemaps to localhost so that I can serve and use them locally, even on my production site (as described [here](https://itnext.io/using-sourcemaps-on-production-without-revealing-the-source-code-%EF%B8%8F-d41e78e20c89)).
However, according to the following snippet:
https://github.com/postcss/postcss/blob/ee267d5f6406e9a9ca88be4191ffb6c8b648dc15/lib/map-generator.es6#L127-L143
there doesn't seem to be a way to specify a public path, and specifying 'annotation' as a string just sets the sourcemap url to that string, without the file name appended to it.

I'm using OptimizeCssAssetsPlugin to apply this change.

I assume appending the file name to the end would be a breaking change, so if that's not possible, would it be viable to make 'annotation' accept a method with a file name as the argument so that the sourcemap url can be customized further?

**Comment by ai** [comment]
Why `opts.map.annotation = 'https://localhost/path/to/source-map.map'` is not a solution here?

**Comment by Pikachews** [comment]
If I have chunked css files, that does not give each file their respective chunk sourcemap; all of them would link to `https://localhost/path/to/source-map.map`

**Comment by ai** [comment]
In PostCSS core API you can set different `opts.map.annotation` for each file.

Do you not see the way to set different URL to different file in `OptimizeCssAssetsPlugin`?

**Comment by Pikachews** [comment]
Hm.

As far as I am aware, the way to set the plugin to generate the sourcemap is this:
```js
      new OptimizeCssAssetsPlugin({
        cssProcessorOptions: {
          map: {
            annotation: true,
          },
        },
      }),
```

This generates the source and sourcemap file, with the source linking to the sourcemap file as such:
```js
/*# sourceMappingURL=main.6a577f29.css.map */
```

However, if I want the sourcemaps to link to localhost as this guide (https://itnext.io/using-sourcemaps-on-production-without-revealing-the-source-code-%EF%B8%8F-d41e78e20c89) directs, I would supposedly need to set the `annotation` property as a string.

```js
          map: {
            annotation: 'https://localhost:8443/',
          },
```
but this generates the following `sourceMappingURL`:
```js
/*# sourceMappingURL=https://localhost:8443/ */
```
which does not have the file name or path appended.

As far as I can tell, the `annotation` property does not take a function that passes the path to the sourcemap file to customize the `sourceMappingURL` with so that I can append it.

**Comment by ai** [comment]
@Pikachews we can add functions support to `opts.map.annotation` at PostCSS 8.0.

Do you want to send PR?

**Comment by ai** [comment]
Done 1cba3fb

We will release it in 8.0.

---

If you want to speed up 8.0 release, you can talk to your company’s manager about supporting PostCSS

https://opencollective.com/postcss/
