### ISSUE TITLE
Run PostCSS synchronously?

### ISSUE THREAD

**Issue by ahmadalfy** [postcss/postcss#1328]
I am writing my own node script for development. I am facing a problem where PostCSS processes the files asynchronously and the server starts before the compilation is complete.

I know it should return a [LazyResult](https://api.postcss.org/LazyResult.html), is there a way to not do that? This is my code:

```javascript
const processCSS = () => {
	const CSSFile = fs.readFileSync(path.resolve(__dirname, '../src/styles/main.css'));
	postcss(postcssConfig.plugins)
		.process(CSSFile, { from: 'src/styles/main.css', to: '.tmp/styles/main.css' })
		.then(result => {
			fs.writeFileSync('.tmp/styles/main.css', result.css, () => true);
			logInfo('CSS', 'steelblue', 'Processed successfully');
			if ( result.map ) {
				fs.writeFileSync('.tmp/styles/main.css', result.map, () => true);
			}
		})
		.catch(err => {
		});
}

processCSS();
```

I tried switching to `async/await` without success. I've seen this [old issue](https://github.com/postcss/postcss/issues/595) and I still have no clue what should be done.

**Comment by ai** [comment]
You need something like this:

```js
processCSS().then(() => {
  startServer()
})
```

**Comment by ahmadalfy** [comment]
I found the problem,

Those plugins I use don't offer sync mode:

```
		// require('postcss-import'),
		// require('postcss-easy-import'),
		// require('postcss-preset-env'),
		// require('cssnano'),
```

Thank you, that sounds like a reasonable solution

**Comment by sergeysova** [comment]
I want to build a babel plugin to process css at build-time. But now, each babel plugin must be sync, and this [never changes](https://github.com/babel/babel/discussions/11768#discussioncomment-102505).

Can you help me process CSS with postcss?

**Comment by ai** [comment]
@sergeysova if you do not want to use async plugins, you can call PostCSS sync API:

```js
let result = postcss(plugins).process(css, opts)
result.css
result.map
result.messages
```

**Comment by sergeysova** [comment]
@ai Thank you! It is works for me
