### ISSUE TITLE
Support `postcss.config.cjs`

### ISSUE THREAD

**Issue by johnmuhl** [postcss/postcss#1329]
When I add `"type": "module"` to `package.json` I get:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/me/src/postcss.config.js
require() of ES modules is not supported.
require() of /home/me/src/postcss.config.js from /home/me/src/node_modules/import-fresh/index.js is an ES module file as it is a .js file whose nearest
parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/me/src/package.json.

```

If I follow the advice to change the extension to `cjs` I get:

```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

My `postcss.config.{cjs,js}` looks like:

```js
module.exports = {
  plugins: [require("tailwindcss"), require("autoprefixer")]
};
```

Removing `"type": "module"` and using the `js` extension everything works.

Sorry I couldn't tell if the issue should be here or `postcss-cli`.

**Comment by ai** [comment]
Good idea, but you need to open an issue at https://github.com/michael-ciniawsky/postcss-load-config

**Comment by kkdima** [comment]
@johnmuhl hi. Did you managed to fix this issue? I encountered exactly the same type of problem but with different package. Would be very helpful if you shed some light on this. Thank you!

**Comment by ai** [comment]
`.cjs` support was added in the latest release. Update your dependencies.
