### ISSUE TITLE
How do I know the order of plug-in execution

### ISSUE THREAD

**Issue by fukai007** [postcss/postcss#1335]
I want to know the execution of the plug-in, because the configuration is a JavaScript object. I don't know which one executes first and which one executes later in nuxt.config.js
```
export default {
  build: {
    postcss: {
      // 添加插件名称作为键，参数作为值
      // 使用npm或yarn安装它们
      plugins: {
        // 通过传递 false 来禁用插件
        'postcss-url': false,
        'postcss-nested': {},
        'postcss-responsive-type': {},
        'postcss-hexrgba': {}
      },
      preset: {
        // 更改postcss-preset-env 设置
        autoprefixer: {
          grid: true
        }
      }
    }
  }
}
```

**Comment by ai** [comment]
The order of plugins is the same as you described them in `plugins`.

I do not know about `preset` option, since it is not standard PostCSS config and you should ask the Nuxt team.

Is it an answer for your question?

**Comment by fukai007** [comment]
You mean postcss-url -- >postcss-nested -- >postcss-responsive -- type -- >postcss-hexrgba

**Comment by fukai007** [comment]
How do you develop a postcss plug-in locally?

**Comment by ai** [comment]
> You mean postcss-url -- >postcss-nested -- >postcss-responsive -- type -- >postcss-hexrgba

Yeap

> How do you develop a postcss plug-in locally?

Here is our project template for plugins with dev tools

https://github.com/postcss/postcss-plugin-boilerplate

**Comment by fukai007** [comment]
Thank you for your guidance

**Comment by ai** [comment]
If your company uses PostCSS you can talk with your manager about helping us with funding

https://opencollective.com/postcss/

**Comment by fukai007** [comment]
ok i will pay
