### ISSUE TITLE
brackets being stripped from nested calc

### ISSUE THREAD

**Issue by vdecree** [postcss/postcss#1337]
Hi there,

I am noticing that my nested calc lines are being compromised by postcss. For instance, my input looks like:

```--step--2: calc(((var(--fluid-min-size--2) * 1rem) + (var(--fluid-max-size--2) - var(--fluid-min-size--2)) * var(--fluid-bp))); ```

is output as:

```--step-0: calc(var(--fluid-min-size-0)*1rem + (var(--fluid-max-size-0) - var(--fluid-min-size-0))*var(--fluid-bp));```

I can't seem to find any issues that point to a solution to this. Any help would be appreciated.

**Comment by ai** [comment]
What plugins do you use?

It is very likely that brackets were removed in the plugin, rather than in parser.

**Comment by vdecree** [comment]
> 
> 
> What plugins do you use?
> 
> It is very likely that brackets were removed in the plugin, rather than in parser.

I am using postcss import & cssnano.

**Comment by ai** [comment]
Yeap, you need to open issue in cssnano, since I am not a maintainer and can’t fix it.

**Comment by Semigradsky** [comment]
@vdecree it looks like issue in `postcss-calc`. Try to disable `calc` optimization in cssnano.
