### ISSUE TITLE
Does not work with .sass indented syntax

### ISSUE THREAD

**Issue by yuri-karadzhov** [postcss/postcss#1340]
Sass indented syntax is not being transformed.
```sass
// Main.sass
#app
  height: 100%

html, body
  height: 100%
  font-size: 14px
```
```js
const postcss = require('postcss');
const syntaxSASS = require('postcss-sass');
const sass = require('postcss-node-sass');

const options = { syntax: syntaxSASS };
const plugins = [sass({ indentedSyntax: true })];

const { css, map } = await postcss(plugins)
    .process(content, options);
```
```css
/* Main.css */
#app
    height: 100%

html, body
    height: 100%
    font-size: 14px
```

**Comment by ai** [comment]
1. `syntax` mean that you want Sass for input *and output*. If you want to compile Sass syntax to CSS, you need to set `parser` option.
2. Do not use PostCSS to compile Sass. Just use Sass (PostCSS plugins will not give 100% compatibility) or move to [SugarSS](https://github.com/postcss/sugarss)

**Comment by yuri-karadzhov** [comment]
Yeah, that is the problem with `postcss-node-sass` plugin, already post them an issue. Thanks for assistance, I will switch to sass.
