### ISSUE TITLE
Use PostCSS as peer dependencies in plugins

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1343]
It will reduce `node_modules` size

**Comment by jonathantneal** [comment]
@ai, is there a write-up about this that I can look over? I’d like to understand the problem better, and then understand how this addresses that problem. And please let me know how I can help. If I understand the problem and the solution, I can help implement the solution at the plugin level.

**Comment by ai** [comment]
Benefits:

1. Few developers complained that dependencies deduplication doesn’t work in their cases and they have many different `postcss` in `node_modules`. Unfortunately, I forget where I discussed it. Was it `postcss-preset-env` issue?
2. We have a problem when plugin based on PostCSS 6 is running in PostCSS 7 runner. Because of `postcss.decl()` calls, it will put old nodes into the new AST. It will be nice to pass `postcss` as the third argument to the plugin `(root, result, postcss) => { }`, so plugins will always use the latest AST.
3. It will be nice to use Yarn `peerDependencies` warnings to force plugins to update their API on the new `postcss` major release.
4. It will be nice to use `peerDependencies`, because everyone use it. But, of course, it was never a strong argument for me.

Problems:

1. The plugin developer will be forced to update PostCSS even if they don’t have any API changes.
2. Should we force runners like `postcss-loader` to have PostCSS in `peerDependencies` too?

**Comment by ai** [comment]
Done. Now we pass `{ ...postcss, result: Result }` as a second argument to visitors callback af70155

`postcss.plugin` was deprecated https://github.com/postcss/postcss/commit/299476d55088ead9af1c1bc37e7911a358d5812c

I created a separated issue to prohibit `dependencies: { postcss }` in Plugin Guidelines https://github.com/postcss/postcss/issues/1387
