### ISSUE TITLE
Why does postcss source code have an es6 extension?

### ISSUE THREAD

**Issue by mudgen** [postcss/postcss#1344]
Why does postcss source code have an .es6 extension?

**Comment by ai** [comment]
Because in the old system we cal Babel to compile `.es6` file to `.js` and keep the path the same (we do not have `src/` and `dist` folders).

But in the next 8.0 release, we removed Babel and using `.js` extension https://github.com/postcss/postcss/tree/ose

**Comment by mudgen** [comment]
Okay, great. Thanks!
