### ISSUE TITLE
Export all public classes from root

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1345]
https://twitter.com/nex3/status/1248716921865826304

**Comment by ai** [comment]
@nex3 done https://github.com/postcss/postcss/commit/15d569c0ed545239498c4970f3187ab9a9e0fabb

Together with ESM support https://github.com/postcss/postcss/commit/52ede2d237c4cb8cec39f04aea6148d1965eff42

**Comment by nex3** [comment]
Awesome, thanks @ai!
