### ISSUE TITLE
Process fails because of html tag in comment

### ISSUE THREAD

**Issue by jsbrain** [postcss/postcss#1362]
Hi, Cosmin and I noticed that HTML tags in comments get picked up by PostCSS and cause the process to fail, at least in some circumstances as seen in this issue: https://github.com/maizzle/framework/issues/195

You someone please clarify if this is the expected behavior? :)

**Comment by ai** [comment]
You have a tricky mix of PostCSS and PostHTML in that case.

I tested the CSS parser on pure PostCSS pipeline on [autoprefixer.github.io](https://autoprefixer.github.io/) and everything works well.

So I think PostHTML broke CSS before sending it to PostCSS.

Feel free to open another issue if you will find a problem in PostCSS itself.

If you need help with debugging the environment, you can use [our commercial support](https://opencollective.com/postcss/) at OpenCollective.

**Comment by jsbrain** [comment]
Thank you for your quick answer. That helps!

**Comment by cossssmin** [comment]
It was indeed an issue with the CSS string I was providing to PostCSS - for anyone curious, I've fixed it in https://github.com/posthtml/posthtml-safe-class-names/commit/3d7deb980be70c200f8bf2180f17a8207fad1dd6. Thanks, Andrey!
