### ISSUE TITLE
Remove postcss.vendor

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1372]
According to [GitHub search](https://github.com/search?q=%22postcss.vendor%22&type=Code) only `postcss-sorting` is using `postcss.vendor` API.

I think we should remove it in PostCSS 8, because:

1. People mostly do not use it.
2. It increases bundle size.
3. It is very simple, people can just copy-paste it to their own sources.
4. Browsers are removing vendor prefixes

/cc @hudochenkov

**Comment by ai** [comment]
Done 777c55b

**Comment by hudochenkov** [comment]
Thanks for mentioning! I'll make sure to replace it.
