### ISSUE TITLE
Automatic conversion of number to string in declaration values

### ISSUE THREAD

**Issue by K3TH3R** [postcss/postcss#1373]
@ai asked me to open up an issue after he helped me to understand that an error I was encountering was being caused by setting a declaration value with a number instead of a string:
```js
const paddingTop = postcss.decl({ prop: 'top', value: 0 })
```
This would in turn throw the following error: `TypeError: decl.value.indexOf is not a function`

I believe the idea we discussed would be to automatically cast number values to strings to improve DX in a case like this rather than throwing an error.

**Comment by ai** [comment]
Fixed 57c81be
