### ISSUE TITLE
postcss-nested & autoprefixer plugins causing build to break

### ISSUE THREAD

**Issue by saaduw** [postcss/postcss#1391]
I'm working on an Electron application using Svelte and Tailwind. I'm using Parcel instead of Rollup which is the default for Svelte projects.
Up until recently I was able to use the `postcss-nested` & `autoprefixer` plugins inside the `posts.config.js` file but I can't anymore.

This is what my `postcss.config.js` file looks like right now:
```
const purgecss = require('@fullhuman/postcss-purgecss');

const production = process.env.NODE_ENV === 'production'

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('postcss-nested'),
    require('autoprefixer'),
    ...(production ? [purgecss] : [])
  ]
};
```

removing `postcss-nested` and `autoprefixer` plugins allows the build to work.

**Comment by ai** [comment]
What exactly error do you have?

**Comment by saaduw** [comment]
The Svelte Preprocessor throws the following error the moment I try to include `autoprefixer` or `postcss-nested`
```
[svelte-preprocess] PostCSS configuration was not passed. If you expect to load it from a file, make sure to install "postcss-load-config" and try again ʕ•ᴥ•ʔ
```

**Comment by ai** [comment]
Seems like Svelte is trying to load PostCSS config, but got an error. Try to run `node` in terminal to get Node’s interactive console and run there these two commands:

```js
require('postcss-nested')
require('autoprefixer')
```

Maybe it will throw an error, which will explain to you what happened.

**Comment by saaduw** [comment]
Thanks for the help.
Looks like `autoprefixer` doesn't play well with Node 13.5.

**Comment by saaduw** [comment]
Issue solved by upgrading to the latest version of Node (v14.8)
