### ISSUE TITLE
Declarations should support whitespace as a valid value

### ISSUE THREAD

**Issue by adamwathan** [postcss/postcss#1404]
Something I've run into this week while trying to solve some interesting problems using CSS custom properties is learning that this is valid CSS:

```
--my-custom-property: ;
```

From [here](https://www.w3.org/TR/css-variables-1/#syntax):
 
> Note: While <declaration-value> must represent at least one token, that one token may be whitespace. This implies that --foo: ; is valid, and the corresponding var(--foo) call would have a single space as its substitution value, but --foo:; is invalid.

PostCSS parses this but importantly sets the `value` of the declaration to `''`, when it should be `' '`.

This distinction is important because of situations like this:

```css
.multiple-shadows {
  --shadow-1: ;
  --shadow-2: ;
  box-shadow: var(--shadow-1) var(--shadow-2);
}
.shadow-1 {
  --shadow-1: 0 0 0 1px rgba(0, 0, 0, 0.05);
}
.shadow-2 {
  --shadow-2: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
}
```

Applying all three classes to an element (`multiple-shadows shadow-1 shadow-2`) should result in this computed box shadow (not too weird):

```
box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.05) 0 1px 2px 0 rgba(0, 0, 0, 0.05);
```

What _is_ interesting is that applying only 2 classes (say `multiple-shadows shadow-1`) should result in this computed box shadow:

```
box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.05);
```

This is _only_ possible because of `--shadow-2: ;` being valid CSS for assigning a single whitespace character to the value of `--shadow-2`.

When `--shadow-2` has _no_ value (rather than whitespace), the box shadow simply computes to `none` because `--shadow-2` resolves to the "guaranteed invalid value" rather an whitespace, which is always a valid value.

This is the source of a minification issue that occurs in cssnano where the `discardEmptyRules` optimization removes declarations like this:

```
--shadow-1: ;
```

...which are actually _not_ empty, and not safe to remove because they do impact how the browser actually renders the styles. This could be worked around in cssnano but I believe the ultimate cause of the issue is how we parse declarations in PostCSS, and based on what I know currently I think this is the right place to solve it.

Very weird corner case situation for sure, curious to hear any thoughts on it 👍

**Comment by ai** [comment]
Short-term solution:

```js
root.walkDecls(decl => {
  if (decl.value === '' && decl.raws?.value?.raw === ' ') {
    decl.value = ' '
    delete decl.raws.value
  }
})
```

Will it fix cssnano?

**Comment by adamwathan** [comment]
Almost, the problem is `raws.value` is not set in this case. This is what you get:

```
raws: { before: '\n  ', between: ': ' },
```

If I remove the second half of your conditional (not correct fix but enough to validate general idea) it does work 👍🏻

**Comment by ai** [comment]
But since CSS requires at least one token, it will be better to parse it as `{ value: ' ', raws: { between: ':' } }`?

**Comment by adamwathan** [comment]
We should probably be careful with this situation too:

```
--my-custom-property: !important;
```

Currently `decl.value` is `!important` but I bet it should be ` !important` (with a space).

**Comment by adamwathan** [comment]
> But since CSS requires at least one token, it will be better to parse it as { value: ' ', raws: { between: ':' } }?

I'm not totally sure, I think yes? But only if there are no other values. Like `--foo: bar` should probably still just be `'bar'`, not `' bar'`?

**Comment by adamwathan** [comment]
The overall idea of the workaround definitely works if you have the opportunity to throw that plugin into the chain, but unfortunately doesn't work in situations where you don't have access to PostCSS of course. The motivating example for this in my case is Next.js — it uses cssnano in a final separate stage to optimize all of your CSS but does so after stringifying the initial PostCSS output and reparsing in a separate production-only stage, so no opportunity to rewrite the decl values there.

Not that that is helpful or changes anything of course 😅  Appreciate the quick response.

**Comment by ai** [comment]
Yeap, I like the idea of using `' '` as a value because the value can’t be `''`. It requires at least a single token. I will add it and release it in 8.0 since it could be breaking change.

The 8.0 release should be on this or next week.

**Comment by evilebottnawi** [comment]
We have the same problem in `prettier` :smile:

**Comment by ai** [comment]
@evilebottnawi will `{ value: ' ', raws: { between: ':' } }` solve the problem in Prettier as well?

**Comment by evilebottnawi** [comment]
Yep

**Comment by ai** [comment]
Fixed 8366bda

Will be released in 8.0

**Comment by adamwathan** [comment]
Awesome, thank you!

Will this solution work correctly for this sort of stuff too (which should parse to the same)?

```css
--foo: /**/;
```

**Comment by ai** [comment]
Nope :(. Wait a second. I will improve the solution.

**Comment by ai** [comment]
I also added `--empty3: !important;` to test case. It should be parsed to `{ value: ' ', between: ':', important: true }`. Am I right?

**Comment by evilebottnawi** [comment]
@ai

```css
:root {
  --empty3: !important;
}
```

is valid syntax

Also:
```css
:root {
  --empty3:/*test*/ !important;
}
```

```css
:root {
  --empty3: /*test*/!important;
}
```

Valid too

https://tomhodgins.com/demo/cssom/

**Comment by ai** [comment]
Next attempt:

* Code ddc2951
* Tests https://github.com/postcss/postcss-parser-tests/commit/fd34d4b3a2d9ef79b6f731cf4d36bb03f33e51e5
