### ISSUE TITLE
Invalid PostCSS Plugin found error with very basic setup

### ISSUE THREAD

**Issue by Mehdi-Hp** [postcss/postcss#1408]
I'm trying to upgrade my plugin for postCSS 8. But this confusing error:  
`TypeError: Invalid PostCSS Plugin found at: plugins[0]`. 

##### postcss.config.js

```js
module.exports = {
    map: true,
    plugins: {
        './postcss/test.js': {}
    }
};
```

##### postcss/test.js

```js
module.exports = (opts = {}) => {
    return {
        postcssPlugin: 'PLUGIN_NAME'
    }
};
module.exports.postcss = true;
```
##### package.json
...
"postcss": "^8.0.1",
...

**Comment by Mehdi-Hp** [comment]
Alright. There seems to be some known problem.
![image](https://user-images.githubusercontent.com/8641684/93320462-5b27c480-f826-11ea-9f80-ceda68ae9d9c.png)

**Comment by frederikhors** [comment]
And for `postcss-load-plugins` migration guide?

**Comment by ai** [comment]
I am closing this issue since we have a special issue for better error message https://github.com/postcss/postcss/issues/1410
