### ISSUE TITLE
v7.0.33 is marked as "latest" instead of v8.0.3

### ISSUE THREAD

**Issue by noahbrenner** [postcss/postcss#1409]
I know you just published `7.0.33` less than 10 minutes ago, but just in case you didn't catch the misplaced tag, I thought I'd let you know.

`$ npm outdated` shows:

```
Package  Current   Wanted   Latest
postcss    8.0.3    8.0.3   7.0.33
```

And the [GitHub release](https://github.com/postcss/postcss/releases/tag/7.0.33) is marked `Latest release`

Unless I'm misunderstanding your intentions, I'd expect v8.0.3 to still be marked as latest, at least in the npm registry.

**Comment by ai** [comment]
I released `8.0.4`. It should solve the problem of `npm outdated` wrong sorting.
