### ISSUE TITLE
TypeError: Invalid PostCSS Plugin found at: plugins[1]

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1410]
We need a better error message for PostCSS 8 plugins in `postcss-load-config`.

- [x] Get access from @michael-ciniawsky
- [x] Fix PostCSS 8 support
- [x] Release major release

**Comment by heath-freenome** [comment]
I agree, this error isn't helpful.  I am not sure which one of my plugins is failing when I upgrade to Postcss 8... so I'm not doing it yet.

**Comment by michael-ciniawsky** [comment]
< Get access from @michael-ciniawsky

@ai You should have access now (npm & github)

I can't transfer the repo because of missing rights to do so... Maybe you can otherwise please send me a mail
