### ISSUE TITLE
TypeError: Class constructor Parser cannot be invoked without 'new'

### ISSUE THREAD

**Issue by davidboschwitz** [postcss/postcss#1412]
See description and comments in https://github.com/facebook/create-react-app/issues/9655

This appears to be an issue in postcss

(also callout to https://github.com/postcss/postcss-scss/issues/111)

**Comment by ai** [comment]
What versions of PostCSS and `postcss-scss` do you have in `npm ls`?

Do you have the full stack trace?

**Comment by maxabrams** [comment]
From the Issue @davidboschwitz linked above: "It might be a problem of postcss@7.0.33 and if I changes yarn.lock (postcss@7.0.33 to postcss@7.0.32), build runs successfully."

**Comment by ai** [comment]
@maxabrams I saw the comment, but I need an output of `npm ls | grep postcss`

**Comment by ai** [comment]
The fix was released in PostCSS 7.0.34
