### ISSUE TITLE
TypeError: node.getIterator is not a function

### ISSUE THREAD

**Issue by LP1994** [postcss/postcss#1414]
node: 14.11.0;
npm: 6.14.8;
operating system: Windows 10;
postcss: 8.0.5;
postcss-less: 3.1.4;

Error description:
ERROR in ./src/styles/less/basic/Basic.less
    Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
    TypeError: node.getIterator is not a function
        at LazyResult.visitTick (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss\lib\lazy-result.js:470:33)
        at LazyResult.runAsync (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss\lib\lazy-result.js:357:30)
        at async Object.loader (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss-loader\dist\index.js:94:14)
     @ ./src/tplEJS/pages/AuditLogIndex.ejs (./node_modules/html-webpack-plugin/lib/loader.js!./src/tplEJS/pages/AuditLogIndex.ejs) 83:10-42

step:
When I use the following configuration, an error will be reported: TypeError: node.getIterator is not a function.
{
    test: /\.less$/i,
    use: [
        {
            loader: 'file-loader',
            options: {
                name: '[name]_[sha512:contenthash:hex:6].css',
                outputPath: './styles/',
                emitFile: true,
                esModule: false,
            }
        },
        {
            loader: 'extract-loader',
        },
        {
            loader: 'css-loader',
            options: {
                url: true,
                import: true,
                importLoaders: 2,
                esModule: false,
            },
        },
       
        // If you comment out the "postcss-loader" below, you won't get an error(TypeError: node.getIterator is not a function).
        {
            loader: 'postcss-loader',
            options: {
                execute: false,
                sourceMap: false,
                postcssOptions: {
                    syntax: require( 'postcss-syntax' )( {
                        css: require( 'postcss-safe-parser' ),
                        sass: require( 'postcss-sass' ),
                        scss: require( 'postcss-scss' ),
                        less: require( 'postcss-less' ),
                    } ),
                },
            },
        },

        {
            loader: 'less-loader',
            options: {
                lessOptions: {
                    math: 'strict-legacy',
                    strictUnits: true,
                    noIeCompat: true,
                },
            },
        },
    ],
    sideEffects: true,
}

explain:
When processing ".less" files, if "postcss-loader" is not used, no error will be reported and it can be successfully compiled. If "postcss-loader" is used, an error will be reported. Moreover, the above configuration will not report an error in postcss 7. X, but it will be reported if it is updated to postcss 8. X.

**Comment by LP1994** [comment]
I live in the East eight international time zone, so if you have any questions, you may not be able to reply in time. Please forgive me for the inconvenience.

**Comment by ai** [comment]
Seems like `postcss-less` do not support PostCSS 8. Downgrade other PostCSS modules.

I will create an issue in `postcss-less` tomorrow.

**Comment by LP1994** [comment]
Thank you for your timely reply!!! At first, I thought that it might be the "postcss less" problem. However, the code reported "postcss", so I came here to submit the error. Now I will go to "postcss less" to submit this error.

**Comment by ai** [comment]
Here is a correct issue https://github.com/shellscape/postcss-less/issues/150

**Comment by Juraj-Masiar** [comment]
Hello,
I'm having the same issue, but I'm not using less:
```js
        {
          test: /\.css$/,
          use: [
            MiniCssExtractPlugin.loader,
            "css-loader",
            "postcss-loader",    // if I comment out this line, it will work again
          ]
        },
```
This is the full stack trace:
```js
ERROR in ./node_modules/@fortawesome/fontawesome-free/css/all.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\css-loader\node_modules\postcss\lib\lazy-result.js:528:33)
    at LazyResult.runAsync (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\css-loader\node_modules\postcss\lib\lazy-result.js:408:30)
    at LazyResult.async (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\css-loader\node_modules\postcss\lib\lazy-result.js:221:30)
    at LazyResult.then (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\css-loader\node_modules\postcss\lib\lazy-result.js:206:17)
    at processResult (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\webpack\lib\NormalModule.js:703:19)
    at C:\Users\Juraj\git\addons\PrivateNotes\node_modules\webpack\lib\NormalModule.js:809:5
    at C:\Users\Juraj\git\addons\PrivateNotes\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\Juraj\git\addons\PrivateNotes\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\Users\Juraj\git\addons\PrivateNotes\node_modules\css-loader\dist\index.js:155:5)
 @ ./src/plugins/vuetify.ts 6:0-51
 @ ./src/editor/editor.ts 19:8-77
```
And my libraries:
```
"autoprefixer": "^9.8.6",
"mini-css-extract-plugin": "^2.1.0",
"postcss": "^8.3.6",
"postcss-comment": "^2.0.0",
"postcss-load-config": "^3.1.0",
"postcss-loader": "^6.1.1",
"postcss-plugin": "^1.0.0",
```
I'm trying to migrate to Webpack 5 and this is the last problem I'm facing.
I've tried to downgrade PostCSS from 8 to 7 but then I get a different error from one of the libraries that says:
```
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8
```

**Comment by latel** [comment]
> postcss-comment

any ideas how to track which library is causing this issue?
