### ISSUE TITLE
Wrong engines in package json?

### ISSUE THREAD

**Issue by fivethreeo** [postcss/postcss#1415]
I get 

```
error postcss@8.0.4: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.14.0"
```

On node 13.14.0

**Comment by ai** [comment]
Why it is Wrong?

Node.js 13.14 has no security ues anymore.

**Comment by fivethreeo** [comment]
I may be uninfomed here. But does this work on 13.x. My CI tests go from 10.x to 14.x. If 13.x is not considered stable at all I can understanding exclude it completely

**Comment by ai** [comment]
Yeap. I recommend removing Node.js 13 from CI
