### ISSUE TITLE
Issue with handling of options 

### ISSUE THREAD

**Issue by fivethreeo** [postcss/postcss#1416]
Issue with postcss-loader. If I use postcss-loader and dont have a postcss.config.js, postcss report missing options but all options work correctly. 

You have mentioned adding a option to fix this. But the issue is those options can only be supplied in the config file, including the option to prevent this(chicken/egg). So if we use it programmatically it causes errors.

**Comment by ai** [comment]
Check that you used the latest `postcss-loader` release. If yes, create an issue there. Maybe they didn’t release the fix.

**Comment by fivethreeo** [comment]
I use the latest. I may be wrong but it seems to me that postcss tries to read the config before the options. My analysis might be wrong, but with latest postcss-loader, all plugins work but I get warnings. So it seems to me that postcss always looks for config files and if that is not found ignores the options given programmatically. But the errormessage comes from here.

**Comment by ai** [comment]
`postcss-loader` reads config. `postcss` core does not work with file system (accepts CSS as string).

**Comment by fivethreeo** [comment]
Oh, I mat be barking up the wrong tree then ;)
