### ISSUE TITLE
Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by inwardmovement** [postcss/postcss#1421]
[CI fails](https://github.com/algosphere/algo-website/actions?query=workflow%3Aci-cd-main) overnight, fixed by replacing `npm i -g postcss-cli autoprefixer` by `npm i -g postcss-cli autoprefixer@9`.

But it breaks again today, what fix could work please?

**Comment by ai** [comment]
With `autoprefixer` 10 you need to add `postcss` to `package.json`:

```
npm i postcss
```

---

We highly do not recommend to install any npm dependencies globally. Remove `-g` and call PostCSS by `npx postcss`.

**Comment by inwardmovement** [comment]
I have to install it globally as per [Hugo docs](https://gohugo.io/hugo-pipes/postcss/). What version of autoprefixer should I force so it works like before?

**Comment by ai** [comment]
@inwardmovement just install `npm i -g postcss` globally, in this case.

I send PR to update Hugo docs https://github.com/gohugoio/hugo/pull/7723
