### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by oscarotero** [postcss/postcss#1430]
I've tried to install postcss in Deno using JSPM (https://dev.jspm.io/postcss) that converts the node code to standard javascript modules and seems that the `nanoid` dependency is failing, because I get this error:

```
error: Uncaught TypeError: Import 'https://dev.jspm.io/npm:nanoid@3.1.12/non-secure/index.dew.js' failed: 500 Internal Server Error
Imported from "https://dev.jspm.io/npm:nanoid@3/non-secure?dew:1"
```

This only happens with postcss 8, version 7.x can be installed correctly.

Due the source code of postcss is typescript, I guess it shouldn't require much effort to have a Deno version. Or, at least, fix these errors generated by jspm converter.

FYI, there's an attempt to port postcss to deno here: https://github.com/denolib/deno-postcss

**Comment by ai** [comment]
> I've tried to install postcss in Deno

I like Deno and would like to add Deno support to PostCSS.

> Due the source code of postcss is typescript

Nope. PostCSS was written on pure JS (ES6+ with CommonJS modules). For TS we have only `.d.ts` files.

> This only happens with postcss 8, version 7.x can be installed correctly.

In PostCSS 8 we added `nanoid` dependency. `nanoid` has good ES modules support.

> FYI, there's an attempt to port postcss to deno here: https://github.com/denolib/deno-postcss

The fork is the last option. Very soon it will stop maintaince. We need to find another way.

> Or, at least, fix these errors generated by jspm converter.

What error do we have on JSPM? I see only 500 HTTP error without details, why JSPM wasn’t able to compile Nano ID.

**Comment by oscarotero** [comment]
Hi. It's great you want to add Deno support!

> The fork is the last option. Very soon it will stop maintaince. We need to find another way.

Completely agree. There should be a way to create a code that can be exported for both platforms. Some libraries like [lodash](https://github.com/lodash/lodash) or [date-fns](https://github.com/date-fns/date-fns) are doing that.

> What error do we have on JSPM? I see only 500 HTTP error without details, why JSPM wasn’t able to compile Nano ID.

No idea. Seems an error in the v3 version: https://dev.jspm.io/npm:nanoid@3.1.12/non-secure/index.dew.js 
If you try v2, it seems to work fine: https://dev.jspm.io/npm:nanoid@2.0.0/non-secure/index.dew.js

The problem is in this file: https://github.com/ai/nanoid/blob/master/non-secure/index.js, but I don't see anything strange.
Comparing [the v2 version](https://github.com/ai/nanoid/blob/2.0.0/non-secure/index.js) with [the latest v3](https://github.com/ai/nanoid/blob/3.1.12/non-secure/index.js), the only thing may be the way that the module is exported.

**Comment by ai** [comment]
In Nano ID we added ES support. We are using `dual-publish`, which rename CJS files `index.js` → `index.cjs` and compile CJS to ESM `index.js` (`module.exports = { method }` → `export { method }`).

Can it be a source of the problem?

**Comment by oscarotero** [comment]
Yes, maybe. There're some guidelines about universal module semantics here: https://jspm.org/#universal-module-semantics.

Anyway, the automatic conversion with JSPM is not a complete solution right now because things like filesystem functions (read and write local files) are not supported. Deno is working on a node compatibility layer here: https://github.com/denoland/deno/tree/master/std/node but it's incomplete for now, and JSPM is waiting for this https://github.com/jspm/project/issues/50

So, the problem is not only about module format but also those native functions that are different in both platforms.

To illustrate this with an example:
I'm working on a SSG in Deno, and it have a plugin to convert css code (you can see here: https://github.com/oscarotero/lume/blob/master/plugins/css.js). The idea is that the plugin get the css code, inlines the `@import` and apply all css optimizations with `postcssPresetEnv`.
But `postcss-import` plugin can no be used because reading local files is something that JSPM cannot convert from node to deno. So I had to port [stylecow to Deno](https://github.com/stylecow/stylecow-core) as a temporary solution (I have no plans to continue developing stylecow, but created the branch `deno` for that). So I use stylecow to run the `@import` stuff and them use postcss for the rest of optimizations.

Maybe, as a first step we can create a `deno` branch, with the postcss code converted to ES Modules and use deno dependencies when it's possible. Then, in the future, find out a way to merge both branches.

**Comment by ai** [comment]
What do we need from the library to have native Deno support? Seems like JSPN is not a perfect solution.

Will ESM migration be enouph? I afraid that some dependencies will not work.

**Comment by oscarotero** [comment]
To have native Deno support, we need to do two things:
- Migrate to ES modules
- Fix the dependencies
  - npm modules are easy to replace. For example, instead
    ```
    const path = require("path");
    ```
    must be changed for:
    ```
    import path from "https://deno.land/std/node/path.ts"
    ```
  - Other dependencies can be loaded from jspm.io
  - Optionally, `colorette` could be replaced by the standard deno module https://deno.land/std/fmt/colors.ts

The way to do this change can vary. [denoify](https://github.com/garronej/denoify) seems a good solution (I didn't try it), but it seems like only works with typescript, not vanilla javascript.

**Comment by ai** [comment]
@oscarotero what a standard was for Deno packages to publish library?

**Comment by oscarotero** [comment]
@ai I'm not sure to understand your question.

Deno has a hosting service to publish packages: https://deno.land/x
Basically, it only requires a public github repository and you have to add a webhook so after every new tag, the new version will be reflected in the deno repository.

A good practice is having a `mod.ts` (or `mod.js`) that works like the "main" module of the package, but it's not required, because you can import directly any file of the package as a module. For example, I could import postcss main module `import postcss from "https://deno.land/x/postcss/mod.ts"` or any submodule `import Parser from "https://deno.land/x/postcss/lib/parser.ts"`.

There's no a "publish", "install" or anything like that, as we have in node/npm. The deno.land/x repository only caches the files as they are in the git repository, it's more like a pretty-url service. All dependencies are imported directly using its own url. In fact, it's not required to have the package in deno.land/x, you can import any package directly from github, jspm.io or any other domain.

Eta, for example has a "deno_dist" directory (https://github.com/eta-dev/eta) that is the same directory registered in deno.land/x (https://deno.land/x/eta@v1.11.0) (you can specify a subdirectory instead submit the complete repository).

I don't know if I have resolved your doubts, let me know if you have more questions.

**Comment by ai** [comment]
I want to avoid keeping build files in GitHub repository. Can I run a script on every release and publish build files for Deno somewhere to have `https://deno.land/x/postcss/mod.ts`?

**Comment by ai** [comment]
We can use GitHub Actions to rebuild `postcss/postcss-deno` on new release in `postcss/postcss`.

Do you want to be a maintainer for this Deno port (sorry, after PostCSS 8.1 I promised to [Logux](https://logux.io/) team switching to that project)? You can create `postcss-deno` with build script in your personal account and then I will move it to `postcss` org and give you access.

**Comment by oscarotero** [comment]
I'm not sure to have enough time but I'll try and let you know when I get something good enough.

**Comment by oscarotero** [comment]
Ok, I'm working on this: https://github.com/oscarotero/postcss-deno

I'll need to make some changes in the postcss code too, to ease the transformation. They are changes related with the code style, for example in this file: https://github.com/postcss/postcss/blob/master/lib/symbols.js I would change it for something like this:

```js
module.exports.isClean = Symbol('isClean');
```
If it's ok with you, I'll create a PR with these changes.

**Comment by ai** [comment]
> If it's ok with you, I'll create a PR with these changes.

Sure!

**Comment by oscarotero** [comment]
Ok, I think I have a first version of postcss that works fine in Deno.

Basically, I've created a script that clones the repo and transform the folders "lib" and test" to be deno compatible (https://github.com/oscarotero/postcss-deno/blob/master/run.sh)

It can also runs the tests, but I had to skip some test files because I didn't find a way to make them compatibles with Deno. The list of ignored files are here: https://github.com/oscarotero/postcss-deno/blob/master/to_deno.js#L31 I can add again these files when I find out a way to make them work in Deno.  

My idea is that every new tag of postcss, should update the sh script here: https://github.com/oscarotero/postcss-deno/blob/master/run.sh#L7 to clone that specific tag. For example, on releasing the version `8.1.2`, this line should change to `git clone --depth 1 --branch 8.1.2 https://github.com/postcss/postcss.git`. Then generate the all files, run the tests and if everything is fine, release the same tag in the deno repository.

What do you thing? How do you like to continue?

**Comment by ai** [comment]
1. Test skipping is OK.
2. I like the idea of pushing PostCSS versions to separated branches. Is it a standard practice in Deno community?
3. What if we will keep the `master` branch only for build scripts and `x.x.x` branches will contain only code without build script?
4. We can remove tests after passing them to keep branch smaller.

**Comment by oscarotero** [comment]
To know how the Deno modules registry works, you can try to create the postcss module here: https://deno.land/x (press the "Add a module" button below the module searcher).

Basically, it works by adding a webhook to the github repository. This webhook is triggered on creating a new tag. This means that any new tag in the repository is converted to a new version in the Deno modules registry. The problem with this is that there's not a build phase, every time you create a new tag, the whole repository (or you can configure to show only a subdirectory) will be visible in the Deno registry. I don't know if there's a standard good practice in Deno, I found different strategies and it depends on whether the package is for Deno/Browser only, or it must work also in node.

In Postcss, there's a tag for every new version released (even if it's not required to publish to npm). 

- A solution is creating a subfolder to place the Deno version files, but this is discarded because we don't want to add build files in the repository.
- Other solution could be creating a new branch, as you said. But this branch should create its own tags. For example, in addition to the new 8.1.2 tag (pointing to master), there should be a 8.1.2-deno tag (pointing to the files in the deno branch). I think this solution is not very elegant and it's confusing because the're many different tags for the same version. Take a look, for example to [lodash repository](https://deno.land/x/lodash@4.17.19) in Deno. They have 4 different variants of every version (npm, es, amd...), some of them don't even work in Deno. Other example: I have [a package](https://github.com/oscarotero/keep-a-changelog) that works in Deno and Node that have two branches (master and deno). When I added Deno support, I decided to create tags only for Deno versions but not for node released. That works (for now) but it's not the ideal solution, imho.
- And the other solution is by using a different repository, as we have now, so it can release its own tags, that should match with the tags of the main repository but with different files.

**Comment by ai** [comment]
@oscarotero I sent you an invite to `postcss` org to transfer `postcss-deno` repository.

1. Is it enouph for you to create a module on `deno.land/x`?
2. Can you add me to `postcss` module on`deno.land/x` to improve bus factor (if they have this feature)?

> And the other solution is by using a different repository, as we have now, so it can release its own tags, that should match with the tags of the main repository but with different files.

Yeap, separated reposiroty with:

1. Build scripts in `master`
2. PostCSS converted files in tags
3. GitHub Actions to build new version on new release in `postcss/postcss`

is a perfect solution for my taste

**Comment by oscarotero** [comment]
Ok, I just transfered the repository to this org (https://github.com/postcss/postcss-deno)
And also did a few changes: 

- Moved all converted files to the subdirectory "deno"
- In addition to the code, I added also the readme, license and changelog
- And the main module (`mod.js`) is located in the root of that folder. So users can import postcss with:
```js
import postcss from "https://deno.land/x/postcss/mod.js"
```

I've also tried to publish it to deno.land but I cannot do it because after transfer the repository to postcss organization, I not longer have access to the settings of the repo. So I'm copypasting a screenshot from deno.land with the instructions:

<img width="740" alt="imaxe" src="https://user-images.githubusercontent.com/377873/95902444-219a9880-0d95-11eb-90c9-15ed3cd415a6.png">

As you can see, the registry is done with webhooks. There's no "admin" or "manage" section in deno.land so no bus factor here. The only thing that we have to do is add this webhook to the repo and that's all. In fact, if in a future we want to merge postcss and postcss-deno in the same repo, we only have to create a webhook in that repo, because the url of the webhook includes all info: `https://api.deno.land/webhook/gh/postcss?subdir=deno%2F` (the package is `postcss` and the subdirectory `deno/`).

Can you register this package? or if you give me access to edit the repository settings, I can do it.

**Comment by ai** [comment]
I gave you an `admin` role in the repository.

Can you also send PR to PostCSS docs with Deno instructions?

**Comment by ai** [comment]
Sorry for the delay. Right now I am spending all open source time on [another project](https://github.com/logux/state).

**Comment by lucacasonato** [comment]
@ai @oscarotero Very cool that you are working on Deno support! I have been using PostCSS for a long time, and it is awesome. Thanks :-)

I work the deno.land/x registry, so if you need any help with publishing (or anything else Deno related), let me know.

Reading through the issue, I think I have a solution for your publishing challenge: deno.land/x has a hidden feature that lets you selectively choose which tags to publish (instead of unconditionally publishing all tags). That way you can have `x.x.x` tags, and `deno/x.x.x` tags, and the registry webhook would only pick up and publish the `deno/` prefixed tags. This is achieved through a `version_prefix` query parameter on the webhook URL. For example `https://api.deno.land/webhook/gh/postcss?version_prefix=deno%2F` would only publish a tag starting with `deno/`. E.g the tag `deno/1.0.0`, would then be available at `https://deno.land/x/postcss@1.0.0`. A tag named `1.0.0` would not be published because it does not start with `deno/`. (It is possible to use the `version_prefix` and `subdir` options at the same time.

With this setup you can set up a GitHub Action that triggers when you create a new tag for NPM (like `1.0.0`). It could then run the required build steps, and then push a `deno/1.0.0` tag. This tag would then be picked up by the webhook and published to the registry.

An alternative approach could also be to not use deno.land/x at all. You could also serve the files from your own web server (e.g. `https://postcss.org/1.0.0/mod.js`), or use a different public registry like https://nest.land (which has a CLI more like npm).

**Comment by oscarotero** [comment]
Hey, @lucacasonato, That's awesome, I didn't know the `version_prefix` parameter. This allows to have all in a single repository, publishing the deno version in a different branch and creating tags available only for deno.

Thanks for your help, I think it's a better publishing way.

BTW, I'd love that Deno had better documentation about how to publish publishing modules and even different use cases and best practices about how to maintain a project for Deno and Node :)

@ai I'll send a PR to postcss implementing this flow, and if it's accepted, we can remove postcss-deno repository.

**Comment by ai** [comment]
I do not like the idea of bloating `postcss/postcss` repo with `deno/*` branches, but could change my mind if there will be good reasons for it.

**Comment by oscarotero** [comment]
Hi @ai, I was about to create a PR with this.
The idea is having just one branch: `deno`. You can see my fork here: https://github.com/oscarotero/postcss

In `master` there's a gh-action executed everytime a new tag is created. https://github.com/oscarotero/postcss/blob/master/.github/workflows/deno.yml

This action updates the `deno` branch with the latest version of the code from master and create the same tag starting with `deno/`. Here you can see two tags: `8.1.3` and `deno/8.1.3` https://github.com/oscarotero/postcss/releases

What do you think?

**Comment by ai** [comment]
I afraid that it will bloat git repository size. Separated repository looks like a better option for now: I do not see any disadvantages (but maybe I am missing something), but it will not increase `postcss/postcss` size.

**Comment by oscarotero** [comment]
ok, understood. I will do so

**Comment by oscarotero** [comment]
Ok, PR created.

I've tagged manually the current version [in postcss-deno](https://github.com/postcss/postcss-deno/releases), so we have an initial Deno version available: https://deno.land/x/postcss@8.1.2

After merging the PR, the new versions should be created and tagged automatically.

**Comment by ai** [comment]
@oscarotero Thanks for great work. It was a big project.
