### ISSUE TITLE
Migration from `postcss.plugin` for complete CSS transformation

### ISSUE THREAD

**Issue by matzeeable** [postcss/postcss#1431]
Hi!

Just upgraded PostCSS and one of my local plugins did not work anymore. It is very simply, it takes the PostCSS' css and pipes it to [`clean-css`](https://github.com/jakubpawlowicz/clean-css).

```ts
import postcss from "postcss";
import CleanCss from "clean-css";

module.exports = process.plugin("clean-css", (options = {}) => {
    const cleaner = new CleanCss(options);
    return (css, res) =>
        new Promise((resolve, reject) =>
            cleaner.minify(css.toString(), (error, result) => {
                if (error) {
                    return reject(new Error(error));
                }

                for (const w of result.warnings) {
                    res.warn(w);
                }

                res.root = postcss.parse(result.styles);
                resolve();
            })
        );
});
```

I read the following references but did not find out, how to migrate the above code to the new API:

- https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md
- https://evilmartians.com/chronicles/postcss-8-plugin-migration

Regards,
Matthew :-)

**Comment by Semigradsky** [comment]
Any ideas why do it as PostCSS plugin if it doesn't use PostCSS AST?

**Comment by matzeeable** [comment]
Hi @Semigradsky !

Thanks for your fast reply. I never thought about that... I can now use `clean-css` directly within my `webpack` config: https://github.com/webpack-contrib/css-minimizer-webpack-plugin#using-custom-minifier-clean-css

Regards,
Matthew :-)
