### ISSUE TITLE
Get Started Guide for writing a plugin

### ISSUE THREAD

**Issue by TheJaredWilcurt** [postcss/postcss#1437]
There should be an easy getting started guide for writing a plugin.

It took like like 20 clicks to find a link, and eventually it just took me to a GitHub folder, instead of an actual site and I had to click on the hosted markdown file.

* https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md

This then gave me a link to an AST playground, which I used as my basis to start trying to understand PostCSS and it's confusing API. Then when I try to run it locally (which I only found after googling around other unrelated parts of the docs), I get a deprecation warning which takes me to a blog post migration guide?

* https://evilmartians.com/chronicles/postcss-8-plugin-migration

Which is well written, it's just.... I don't have anything to migrate, I don't want to learn two APIs just so I can understand how to use the new one. Where is the "Hi, you've never used PostCSS before, so we aren't going to make any assumptions, and instead just gently walk you through the most common aspects of writing a plugin" guide?

I just need a reliable CSS parser for my library. I don't think it should be this hard.

**Note:** Along the way, I did find a plugin boilerplate, but it had Husky and a bunch of other junk in it that is way too opinionated to be a general recommendation.

**Comment by ai** [comment]
What docs changes do you suggest?

> Along the way, I did find a plugin boilerplate, but it had Husky and a bunch of other junk in it that is way too opinionated to be a general recommendation.

What things can be replaced expect `clean-publish`?

**Comment by TheJaredWilcurt** [comment]
I just want the simplest "Hello World" example.
How do I run it locally. How do I get it setup. The AST playground of reversing property names was good. It's just with an outdated API, and hard to find.

For that boilerplate, everything after the peerDependency should be removed. I'm a big fan of **[linting](https://github.com/tjw-lint)** and **[testing](https://twitter.com/TheJaredWilcurt/status/1311514118466293761)**, but those should be decisions I make, not the boilerplate. And Husky (and it's very annoying derivative Yorkie) breaks all git hooks on Windows and collides with Git GUIs on all platforms. I'd rather just use GitHub Actions and require checks pass before merging. I don't care when the linting/tests are fixed (before every commit, or just in the very last commit), as long as it happens before being merged to `master` (or I guess `main` now). The use of git hooks enforces one persons workflow on everyone. Nothing is stopping you from running `npm run lint` or `npm t` by hand before committing if you want to make that part of *your* work flow (which is what I do anyway).

So I saw that 2/3rds of the `package.json` in the boilerplate was overly opinionated, and projected to the rest of the boilerplate from there. So I left it in search of an easier "Hello World". I don't think this would be an uncommon assessment/reaction.

**Comment by ai** [comment]
> For that boilerplate, everything after the peerDependency in package.json should be removed

If you have your favorite tool, you can still replace Jest. But removing tests and linters will force many developers to ignore tests at all.

> And Husky (and it's very annoying derivative Yorkie) breaks all git hooks on Windows

I agree with git hooks. Please send PR with removing `husky` and `lint-staged`.

> I just want the simplest "Hello World" example.

There are 3 very different users groups:

1. Plugin authors
2. Parser users
3. End-user users of PostCSS-based tools

I am not sure that simple example can cover all 3 groups.

**Comment by TheJaredWilcurt** [comment]
Then I think stating those 3 groups at the top of the docs and directing them to documentation for them would be the best case.

**Comment by ai** [comment]
Good idea. Do you want to send PR?

**Comment by TheJaredWilcurt** [comment]
Currently I'm still evaluating CSS parse libraries. If I end up using PostCSS, I will create PRs.

**Comment by TheJaredWilcurt** [comment]
I ended up going with `rework/css`. Its documentation also needed some help but it was much more straight forward and easier to get started with. So I did a PR there to improve the docs.

I'll leave this open for anyone that wants to improve the onboarding process of postcss.

**Comment by ai** [comment]
Open source is not a place full of workers. I prefer to keep issues closed if they are not about bugs and other code-related things.

Otherwise, I will lost myself in many issues.
