### ISSUE TITLE
result.warn is not a function

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss#1438]
Code to reproduce
```js
module.exports = (options) => {
  return {
    postcssPlugin: "postcss-modules-values",
    OnceExit(root, postcss) {
      root.walkAtRules(/value/i, (atRule) => {
        atRule.warn("warning ");
      }
    }
  }
}
```

**Comment by ai** [comment]
`Node#warn()` accepts `postcss.result` as first argument (but double check API, I am not 100% sure).

**Comment by evilebottnawi** [comment]
Oh, yes, my mistake, don't found it in migration guide, but it works in `postcss@7`, so I think it is bug
