### ISSUE TITLE
PostCSS does not recognize given plugins

### ISSUE THREAD

**Issue by Groschenroman** [postcss/postcss#1440]
I'm running an application with
```json
// package.json
…
// dependencies
…
  "angular/core": "~10.1.3",
…
// dev-dependencies
  "postcss-import": "^12.0.1",
  "postcss-loader": "^3.0.0",
  "postcss-scss": "^3.0.2",
…
```
and I keep getting this
>You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
error despite having plugins configured.

My `webpack.config.js` looks like this
```javascript
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loader: 'postcss-loader',
        options: {
          postcssOptions: {
            ident: 'postcss',
            syntax: 'postcss-scss',
            plugins: [
              require('postcss-import'),
              require('tailwindcss'),
              require('autoprefixer'),
            ],
          },
        },
      },
    ],
  },
};
```

And finally that's my main stylesheet file:
```scss
@tailwind 'base';
@tailwind 'components';
/* Custom components go here */
@tailwind 'utilities';
/* Custom utilites go here */
@import 'styles/resets', 'styles/variables', 'styles/animations';
```

I read about similar incidents of others but in most of those cases there were really no plugins. Other than here.
Or am I missing something?

**Comment by ai** [comment]
Sorry, after PostCSS 8 release I am burned-out and can’t help a lot in debugging. Here is what I would test:

1. Move plugins to the PostCSS config file.
2. Maybe this warning comes not from `postcss-loader`, but from another tool, which use PostCSS inside?
