### ISSUE TITLE
PostCSS Plugin postcss export value

### ISSUE THREAD

**Issue by Siilwyn** [postcss/postcss#1441]
Looking into migrating code to use ECMAScript Modules instead of CommonJS, I see [in the second step](https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md#step-2-create-a-project) PostCSS expects this to be exported: `module.exports.postcss = true`.

Wondering what the ECMAScript equivalent would be and if it would work with PostCSS at this moment.

**Comment by ai** [comment]
```js
export default const plugin = () => { … }
plugin.postcss = true
```
