### ISSUE TITLE
TypeError when using postcss-clean plugin after upgrade

### ISSUE THREAD

**Issue by reddevil7nine** [postcss/postcss#1444]
After upgrading from `postcss@7.0.35` and using the `postcss-clean@1.1.0` plugin, the following error occurs during build:

```
ERROR in ./src/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (C:\postcss-clean-error\node_modules\postcss\lib\lazy-result.js:461:33)
    at LazyResult.runAsync (C:\postcss-clean-error\node_modules\postcss\lib\lazy-result.js:345:30)
    at LazyResult.async (C:\postcss-clean-error\node_modules\postcss\lib\lazy-result.js:178:30)
    at LazyResult.then (C:\postcss-clean-error\node_modules\postcss\lib\lazy-result.js:163:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at processResult (C:\postcss-clean-error\node_modules\webpack\lib\NormalModule.js:576:19)
    at C:\postcss-clean-error\node_modules\webpack\lib\NormalModule.js:669:5
    at C:\postcss-clean-error\node_modules\loader-runner\lib\LoaderRunner.js:397:11
    at C:\postcss-clean-error\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\postcss-clean-error\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\postcss-clean-error\node_modules\css-loader\dist\index.js:155:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Removing `postcss-clean` or downgrading `postcss` allows the build to complete. Sample project attached.
[postcss-clean-error.zip](https://github.com/postcss/postcss/files/5403562/postcss-clean-error.zip)

**Comment by ai** [comment]
1. You should start by opening an issue in `postcss-clean` about migration to PostCSS 8. PostCSS 8 mostly supports all PostCSS 7 plugins, but `postcss-clean` uses old API. Ask them to keep the origin `Root`.
2. There is no reason to use `postcss-clean`. This plugin convert CSS tree to CSS string, send it to `cleancss` and parse again. It will be better to use `cleancss-loader` or something like this since you have no benefits of using `cleancss` inside PostCSS.

**Comment by reddevil7nine** [comment]
Thank you

**Comment by RiZKiT** [comment]
There is the related issue https://github.com/leodido/postcss-clean/issues/40 and a potential fix PR https://github.com/leodido/postcss-clean/pull/41.

Beside that, alternatives that work with PostCSS using the AST, but have no formatting options like postcss-clean plugin, are:
- https://github.com/lahmatiy/postcss-csso (a plugin which uses csso and has very few dependencies)
- https://github.com/cssnano/cssnano (work with PostCSS out of the box, has more features but has more dependencies)

**Comment by studentIvan** [comment]
Just quick code copy-paste for the next searchers:

```js
const CleanCss = require('clean-css');

const clean = (opts = {}) => {
  const cleancss = new CleanCss(opts);

  return {
    postcssPlugin: 'clean',
    Once(css, { result }) {
      return new Promise((resolve, reject) => {
        cleancss.minify(css.toString(), (err, min) => {
          if (err) {
            return reject(new Error(err.join('\n')));
          }

          for (const w of min.warnings) {
            result.warn(w);
          }

          result.root = postcss.parse(min.styles);
          resolve();
        });
      });
    },
  };
};
```
