### ISSUE TITLE
Postcss migration codemods

### ISSUE THREAD

**Issue by coderaiser** [postcss/postcss#1445]
[New API](https://evilmartians.com/chronicles/postcss-8-plugin-migration) for `postcss plugins` looks very good, the only think I don't really like is the need to fix all the things by hand. So I want to suggest using codemods to automate migration of already written plugins and for this purpose I started to work on [@putout/plugin-postcss](https://github.com/coderaiser/putout/tree/master/packages/plugin-postcss).

Any suggestions and help highly appreciated :).

**Comment by ai** [comment]
Looks good. I will promote it in Twitter.

**Comment by ai** [comment]
Tweet schedules on Thursday
