### ISSUE TITLE
Clarify peerDependency rules for custom parsers

### ISSUE THREAD

**Issue by stof** [postcss/postcss#1447]
As of Postcss 8, the official recommendation for plugin authors is to make `postcss` a peer dependency rather than a dependency, to guarantee that a single postcss version is used.
currently, this rule is not applied for custom parsers. https://github.com/postcss/postcss-scss and https://github.com/postcss/postcss-safe-parser are both using postcss as a regular dependency, which then leads third-party parsers to do the same (see https://github.com/shellscape/postcss-less/pull/151#discussion_r509150747 for instance).
AFAIU, the reasons for using a peer dependency in plugin also apply to custom parsers, and so they should probably also migrate to a peer dependency. But this would need some clarification from the postcss maintainers.

**Comment by shellscape** [comment]
Please don't attempt to mandate how other projects should use tools. That's overstepping your bounds.

**Comment by stof** [comment]
I'm asking here what should the best practices for package extending postcss with custom parsers, just like postcss 8 explicitly defines such a rule for postcss plugins, which are another way to extend postcss.
What I'm asking here is whether the rule defined by postcss maintainers for plugins and runners should also be applied to parsers or no. My own understanding is that it would make sense, but I'm indeed not the one making the decision here.

And to me, postcss maintainers are perfectly in their right to mandate some rules for packages *extending* postcss (I'm not talking about packages *using* postcss). Thus they already do that in the [release notes of Postcss 8](https://github.com/postcss/postcss/releases/tag/8.0.0):

> PostCSS development guidelines were also changed:
> * Now it is prohibited to create own AST on top of PostCSS AST classes since it could lead to painful bugs due to the usage private APIs.
> *  Plugins and runners must have postcss in peerDependencies.

**Comment by ai** [comment]
> As of Postcss 8, the official recommendation for plugin authors is to make postcss a peer dependency rather than a dependency, to guarantee that a single postcss version is used.

Parsers are much more dependent on PostCSS versions than plugins.

I think for now let’s use `dependencies`.

> postcss maintainers are perfectly in their right to mandate some rules for packages extending postcss

Yeap. You need to copy-paste AST classes and can’t extends them in your tool.

We had painful bugs because class extentions was broken in PostCSS patch release.
