### ISSUE TITLE
`Node.source.end.offset` not correct.

### ISSUE THREAD

**Issue by fisker** [postcss/postcss#1450]
```js
require('postcss').parse('a{}').nodes[0].source
// -> { offset: 2, line: 1, column: 3 }
```

Shouldn't `offset` be `3`?

**Comment by ai** [comment]
Offset i counting from `0`, column from `1`

**Comment by ai** [comment]
I improved docs 7ca198f

**Comment by fisker** [comment]
No, this is not what I mean.

The input is `'a{}'`, so, `{start: 0, end: 2}`, `'a{}'.slice(0, 2) === 'a{'`, in JS parsers `a()` always has range `[0, 3]`, is this difference by design?

**Comment by fisker** [comment]
I have to `+ 1` [here](https://github.com/prettier/prettier/pull/9502/files#diff-4acbe93a3ebc8c1bd8c6fdd6b8b15bc80eea2e26f0dd671ff042de2a599c313dR42)

**Comment by ai** [comment]
> is this difference by design?

Yeap. `end` points to the last symbol (`0: a, 1: {, 2: }`)

**Comment by fisker** [comment]
Okay, thank you!
