### ISSUE TITLE
Updating postcss and nodeJS version: "collateral damages" ?

### ISSUE THREAD

**Issue by webmasterpf** [postcss/postcss#1451]
Hello

I wonder if I need to update my nodejs version (actually 8) to a supported one (v15 according nodejs website and postcss 8) because could this do collateral damages about others nodes modules ?

Waiting about before doing this update.

Thanks

**Comment by ai** [comment]
Yeap, Node.js 8 do not have support anymore (from Node.js developers). You can't run PostCSS 8 on Node.js 8.

I do not recommend to update to 15 since odd versions are experimental.

Use LTS releases: 14.x.

**Comment by webmasterpf** [comment]
ok I go to update postcss only so.

**Comment by webmasterpf** [comment]
found a how to: https://evilmartians.com/chronicles/postcss-8-plugin-migration  :)
