### ISSUE TITLE
Property 'finally' does not exist on type 'Promise<Result>'  when I use postcss with ts

### ISSUE THREAD

**Issue by munan2** [postcss/postcss#1452]
![image](https://user-images.githubusercontent.com/26422582/97387545-2ae94080-1911-11eb-97d9-161174e063b8.png)

**Comment by ai** [comment]
I do not have an issue on my machine.

What Node.js version do you use? Do you have `@types/node` in your `dependencies`?

**Comment by Semigradsky** [comment]
`Promise.prototype.finally` was added in ES2018
@munan2 be sure that you have `ES2018.Promise` or `ES2018` or `ESNext` in `lib` property in your `tsconfig.json` file. See https://www.typescriptlang.org/tsconfig#lib

**Comment by ai** [comment]
@Semigradsky can we do something for this users? For instance: `finally: 'finally' in Promise<Result> ? Promise<Result>['finally'] : ((result: Result) => void)`

**Comment by Semigradsky** [comment]
`Promise.prototype.finally` is available in `node@10`. Not sure if we need to do anything.

Only if you plan to support old browsers - https://caniuse.com/promise-finally.

**Comment by Semigradsky** [comment]
I don't think it is necessary.

**Comment by munan2** [comment]
> `Promise.prototype.finally` was added in ES2018
> @munan2 be sure that you have `ES2018.Promise` or `ES2018` or `ESNext` in `lib` property in your `tsconfig.json` file. See https://www.typescriptlang.org/tsconfig#lib
I have add  "lib": ["es2015", "es2016", "dom", "es2018.promise"]。It's OK
