### ISSUE TITLE
Version bump from 8.0.9 to 8.1.0 causes infinite loop with `next()`

### ISSUE THREAD

**Issue by dcwither** [postcss/postcss#1453]
## Summary

I've written a [postcss plugin](https://github.com/dcwither/scss-codemods/blob/master/src/plugins/remove-dash-ampersand.js) that works well in 8.0.9, but runs into an infinite loop on 8.1.0 (as well as 8.1.4). I'm currently unable to find the cause (or whether I'm using anything that's not explicitly in the postcss api that would warrant this issue).

## Failing code

The lines of the plugin that are causing an infinite loop are:
```js
while (
  // Should go after initial comments and existing variable declarations
  shouldGoAfter(decl, beforeNode) 
) {
  beforeNode = beforeNode.next();
}
```
and the minimal failing test case I can produce is the following:
```scss
.toggle-checkbox {
  $height: 15px;
  $width: 50px;

  &-slider {
    &:hover {
      height: $height;
      width: $width;
    }
  }
}
```

## Additional Context:
- I'm using `poscss-scss` as the parser (version 3.0.2 when running with `postcss` 8.1.0+) 
- Currently testing on node 10.18.1

## What I've looked at so far

The crux of the bug appears to be that `decl.next() === decl` is true. This appears to be after `$height` has moved up to `root`, but this didn't seem to happen before 8.1.0.

I've looked through the release diff https://github.com/postcss/postcss/compare/8.0.9...8.1.0 and haven't seen anything that might cause something similar to this, but did notice a subtle difference in behavior with [`markDirty`](https://github.com/postcss/postcss/compare/8.0.9...8.1.0#diff-6c2a7b9329ef569eb21f3a5b424aac9fa4a6642a1e71cba1a2aff04877d1d08eR278).

## Next steps

I'll do some more work a little later on getting a simpler plugin to reproduce the infinite loop, and for now I'll set an exact dependency on 8.0.9.

I'm curious if there's either a known or expected scenario where a node's `next()` would become itself, resulting in this loop. Also not sure if this is more closely related to `postcss-scss` instead.

**Comment by ai** [comment]
Can you try to replace [here](https://github.com/postcss/postcss/blob/master/lib/node.js#L244):

```diff
      get (node, prop) {
        if (prop === 'proxyOf') {
          return node
-       } else if (prop === 'root') {
-         return () => node.root().toProxy()
+      } else if (prop === 'root' || prop === 'next' || prop === 'prev') {
+         return () => node[prop]().toProxy()
```

**Comment by dcwither** [comment]
Here's an example of the minimal failing case that's similar to the original that I created. There's probably an easier case to be made from it: https://repl.it/@dcwither/postcss-loop-example#index.js

**Comment by ai** [comment]
It happens, because in `8.1` we fixed an issue and now `Root` is calling on any node’s changes.

https://twitter.com/PostCSS/status/1310217954953490435

You have a problem in `child.prop.startsWith('$')` where you do not check that you already applied changes.

There are a few options to fix the plugin:
1. Move to correct `Declaration` and `Rule` listeners and check that node was already processed.
2. Use `Once` instead of `Root`.

**Comment by dcwither** [comment]
Thanks for looking into this, and for the update! Your suggested use of `Once` definitely works, though I'm not 100% following why it's failing, specifically with
> `Root` is calling on any node’s changes

I didn't see multiple calls to `Root` when adding some logging. I should probably clarify that for my simplified case, it doesn't apply changes multiple times. What the example is demonstrating is that the result is a `Declaration` with `decl.next() === decl`. 

I'll do some more digging to try and better understand the suggestion as well as the PostCSS visitor pattern.
