### ISSUE TITLE
Add API for capturing plugin execution times 

### ISSUE THREAD

**Issue by lukemelia** [postcss/postcss#1454]
postcss is very fast, but plugin performance can understandably vary considerably, and it can be difficult to identify what plugins are slowing down postcss' processing. I am opening this issue to propose that postcss itself should allow an option to capture plugin execution times and report them back as part of the Result object.

I recently undertook such an investigation into unknown postcss slowness (7-second build times) and tried to use [postcss-devtools](https://github.com/postcss/postcss-devtools) to help. It does not work out of the box with postcss v7, and the approach (the devtools plugin wraps every other plugin) is awkward and doesn't necessarily play nicely with other plugins. By hacking local source code, I was able to get the execution times I needed to diagnose the problem (a key piece was [cssstats](https://github.com/cssstats/postcss-cssstats) performing a max-level gzip on every build!), but I think postcss would benefit considerably by making it easy to get visibility into plugin times.

Capturing the timings may even be inexpensive enough to have it be on by default, so that other tools can proactively warn users about slow plugin execution.

**Comment by ai** [comment]
What API do you suggest?

**Comment by lukemelia** [comment]
I don't know the internals of postcss very well, so I may be missing context, but a public API like this seems like it would work:

```js
let processor = postcss([autoprefixer(), someOtherPlugin()]);
processor.captureExecutionTimes(); // if it is too costly to enable by default 
let result = await processor.process(css);
console.log(result.executionTimes); // => { autoprefixer: [0, 100005002], someOtherPlugin: [1, 420001011] }
```

The plugin names would be retrieved from the plugins, or generated in the case that a plugin is a simple callback, and timings would be tuples of `[numSeconds, numRemainingNanoseconds]` as is returned by [Process.hrtime](https://stackoverflow.com/questions/18031839/how-to-use-process-hrtime-to-get-execution-time-of-async-function/18031945)

**Comment by ai** [comment]
I prefer high-level API which can be used not only for execution time capturing.

For instance, some API to wrap plugins.

**Comment by lukemelia** [comment]
What is another example use case that this high-level API would support?

**Comment by ai** [comment]
> What is another example use case that this high-level API would support?

Tracking before/after changes.

My main reason is that I do not want to have time tracking code in the core.

**Comment by lukemelia** [comment]
>My main reason is that I do not want to have time tracking code in the core.

OK, in that case, it sounds like you're rejecting the intent of this issue (and that's fine) but suggesting that there might be another API that would let us accomplish this time tracking in userland. Is that right?

I don't know what that would look like, especially given it would need to support all supported plugin types including the new v8 API. Perhaps it would be a class that knows how to wrap all these supported plugin types and instrument them with before/after callbacks. Then a user could write:

```js
let timers = {};
let times = {};
let plugins = [autoprefixer(), someOtherPlugin()].map((pluginInstance) => {
  times[pluginInstance] = 0;
  return new InstrumentedPlugin(pluginInstance, new {
     before() {
       timers[pluginInstance] = process.hrtime.bigInt();
     },
     after() {
       let executionTime = process.hrtime.bigInt(timers[pluginInstance]);
       times[pluginInstance] = times[pluginInstance] + executionTime; 
     }
  });
let processor = postcss(plugins);
let result = await processor.process(css);
console.log(times); // => { autoprefixer: 100005002, someOtherPlugin: 1420001011 }
```

I'm not sure whether "before"/"after" makes sense or whether they are too broad, and also what arguments, if any, they should be called with.

**Comment by ai** [comment]
> OK, in that case, it sounds like you're rejecting the intent of this issue (and that's fine) but suggesting that there might be another API that would let us accomplish this time tracking in userland. Is that right?

Yeap. I suggest adding a high-level API to do multiple things including time tracking.

> Perhaps it would be a class that knows how to wrap all these supported plugin types and instrument them with before/after callbacks

We will need an API to pass the current `root`, `result`, plugin’s name, and event (`Root`, `Rule`, etc).

**Comment by lukemelia** [comment]
Sounds good. Would it be helpful if I close this issue and open a new one for this plugin callbacks API?

**Comment by ai** [comment]
Sure
