### ISSUE TITLE
Microsoft Edge 44 - Expected identifier, string or number” in vendor.js (line 86753)

### ISSUE THREAD

**Issue by onovo1** [postcss/postcss#1458]
Hi, 
Could you please remove the last comma (',') from line 86753 of the vendor.js file. Microsoft Edge 44 browner gives an error and the page does not loaded:
 
```
constructor(props) {
    this.data = props.data;
    this.element = props.element;
    this.margin = {
      left: 16,
      right: 24,
      top: 16,
      bottom: 32,
      ...props.margin, <------- remove that comma
    };

```

Thanks,

Oscar

**Comment by ai** [comment]
It is not a PostCSS code

**Comment by onovo1** [comment]
OK, true. Now, I checked the git code.
How come the file is inside the lib folder of my postcss node_modules? 
Is it fetching that file from somewhere else?

**Comment by ai** [comment]
Seems like it is a React component. Maybe it came from some UI library.

**Comment by onovo1** [comment]
OK, that makes sense. I am using Angular. I will check the other components then. 
Thanks!

**Comment by zachariahtimothy** [comment]
@onovo1 did you ever find a resolution? I am also getting this in Edge 44 only, works in all other modern browsers.

**Comment by maubut** [comment]
Did you manage to do anything with this error? I have the same problem in Edge for my VueJS application

**Comment by onovo1** [comment]
No, I didn't find a resolution to the problem. I think it would be better if they remove that comma from the constructor.
