### ISSUE TITLE
Deno vs PostCSS 8.1.7

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1460]
Recent [ES imports TS fix](https://github.com/postcss/postcss/pull/1459) [killed](https://github.com/postcss/postcss/actions/runs/356156497) Deno build.

@oscarotero we need your help

![4777548-tec60feb1942](https://user-images.githubusercontent.com/19343/98700183-ea90b600-2345-11eb-9fdb-18de096fdcdb.jpg)

**Comment by oscarotero** [comment]
😄 mmm, weird. Let me investigate...

**Comment by oscarotero** [comment]
After spending some hours researching, I found that this error only happens in deno 1.5.1 and upper (in deno 1.5.0 works fine). And seems like this only happens only while running the tests, but the library seems to work fine.

A workaround may be disabling the tests in the github action or, at least, force to install Deno 1.5.0 (it can be configured here: https://github.com/postcss/postcss/blob/master/.github/workflows/deno.yml#L16)

I'm going to create an issue in Deno repository.

**Comment by oscarotero** [comment]
Bug reported here: https://github.com/denoland/deno/issues/8355

**Comment by oscarotero** [comment]
Ok, I've updated the deno conversion to remove the changes introduced in 8.1.7, like `CssSyntaxError.default = CssSyntaxError;`

There's an open issue (https://github.com/denoland/deno/issues/8355) to fix this problem in Deno, but meanwhile I've removed here:
https://github.com/postcss/postcss-deno/blob/master/to_deno.js#L29

So, once this https://github.com/postcss/postcss/pull/1474 is merged, I think Deno conversion should work again.

**Comment by ai** [comment]
Thanks!
