### ISSUE TITLE
emacs support for postcss syntax

### ISSUE THREAD

**Issue by nour-dev** [postcss/postcss#1469]
emacs mode for postcss syntax ? any maybe linter ?

**Comment by ai** [comment]
Didn’t heart about it.

As a temporary solution, you can use Sass syntax.

I am closing this issue since it is an issue for the Emacs community.

**Comment by nour-dev** [comment]
> Didn’t heart about it.
> 
> As a temporary solution, you can use Sass syntax.
> 
> I am closing this issue since it is an issue for the Emacs community.

ok, thank you
