### ISSUE TITLE
README: Unclear option `-c` in `postcss --use autoprefixer -c options.json -o main.css css/*.css`

### ISSUE THREAD

**Issue by Hocdoc** [postcss/postcss#1475]
A minor documentation issue from a beginner:

The README contains this example line for using `postcss-cli`:

`postcss --use autoprefixer -c options.json -o main.css css/*.css`

For me, it is unclear what's the effect of the option `-c`. I can also find no documentation about this flag in the `postcss-cli` repository or in the CLI help message. Does this option really exist?

**Comment by ai** [comment]
Thanks. Fixed b4479d0
