### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./node_modules/colorette/index.js

### ISSUE THREAD

**Issue by anark** [postcss/postcss#1478]
I am running into a strange issue that started when updating tailwind/postcss packages that use colorette and running webpack via react-cypress-unit-test testing library.

The error I am getting is
```
Webpack Compilation Error
./app/javascript/components/Input/Input.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./node_modules/colorette/index.js
require() of ES modules is not supported.
require() of ./node_modules/colorette/index.js from ./node_modules/postcss/lib/css-syntax-error.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./node_modules/colorette/package.json.
```

If I explicitly install colorette 1.2.0 instead of 1.2.1 everything seems to work fine.

**Comment by ai** [comment]
What Node.js version do you use?

If it is Node.js 13 you need to update it since it has many problems and does not have any security updates anymore.

**Comment by anark** [comment]
I had this issue when using node 14.15.1.  Also tried with 12.16.3 and 15.3.0 and had the same error.

**Comment by ai** [comment]
What webpack and Babel versions do you use?

**Comment by anark** [comment]
webpack 4.44.2 and babel 7.12.9

The weird thing is it seems to work fine when running webpack normally.  I run into issues when webpack is run via cypress-react-unit-test.

**Comment by ai** [comment]
Sorry, you need to ask webpack or cypress team to help.

Both webpack and Node.js supports `require()` ESM-dependencies. Something is broken in the build process.

The error is very similar to Node.js 13 error message (this version had a problem with ESM). Maybe cypress use it somewhere inside?

**Comment by anark** [comment]
Thanks!
