### ISSUE TITLE
source maps not reflected when removing comments.

### ISSUE THREAD

**Issue by shirotech** [postcss/postcss#1479]
```js
const pluginTest = () => ({
  postcssPlugin: 'postcss-test,
  Comment(comment) {
    comment.remove();
  },
});

pluginTest.postcss = true;
```

When adding this to the plugins array, it removes the comments fine, but the line numbers in the source maps are off by a few lines, assuming that removing the comment did not re-calculate the line numbers. Am I missing something?

**Comment by ai** [comment]
@shirotech can you create a small CSS file, process it by PostCSS, upload files and source map to [source-map-visualization](https://sokra.github.io/source-map-visualization/) and post a link?

**Comment by shirotech** [comment]
All good, I was applying it before plugins, moving it to the end works.
