### ISSUE TITLE
Error: Cannot find module 'E:\Courses\projects\e-commerce-frontend\node_modules\postcss-safe-parser\node_modules\postcss\lib\tokenize'

### ISSUE THREAD

**Issue by YousifAbozid** [postcss/postcss#1483]
Hey guys,
There is a warning in my console when I'm running my react app with npm start, it said

(node:6800) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\Courses\projects\e-commerce-frontend\node_modules\postcss-safe-parser\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
I searched for solution for this warning and found this issue #1455 , I did what you recommended just like this in package.json

```json
"exports": {
    ".": {
      "require": "./lib/postcss.js",
      "import": "./lib/postcss.mjs",
      "types": "./lib/postcss.d.ts"
    },
    "./*": "./*",
    "./": "./"
  },
```

I thought that everything is good but I get that error 

Error: Cannot find module 'E:\Courses\projects\e-commerce-frontend\node_modules\postcss-safe-parser\node_modules\postcss\lib\tokenize'

and my app didn't work, so your solution doesn't fix the problem, what should I do?

npm version is => 7.0.14
node version => v15.3.0
also I'm using Windows 10 Pro VERSION: 1709 and OS BUILD :16299.1087

**Comment by ai** [comment]
Do you have error:

```
Error: Cannot find module 'E:\Courses\projects\e-commerce-frontend\node_modules\postcss-safe-parser\node_modules\postcss\lib\tokenize'
```

after you added `"./*": "./*"`?

**Comment by YousifAbozid** [comment]
yeah, that's why I opened this issue ,
also it can't find module code: 'MODULE_NOT_FOUND'
there is a problem I guess in this file tokenize
`'E:\Courses\projects\e-commerce-frontend\node_modules\postcss-safe-parser\node_modules\postcss\lib\tokenize'`

**Comment by ai** [comment]
Can you remove `"./*": "./*"` and keep using the origin PostCSS (and ignoring the warning)?

**Comment by YousifAbozid** [comment]
I guess this is what should I do for now to keep working on my app, but I just wanna let you know about this error, that's it.
Thanks for your time and you can close this issue now :)
