### ISSUE TITLE
memory issue with 8.2?

### ISSUE THREAD

**Issue by jnardone** [postcss/postcss#1489]
Our build, which uses Webpack 5 and postcss-loader, started throwing out of memory issues in our CI system with the switch from postcss 8.1.4 -> 8.2.0.

    "postcss": "8.1.4", (works)  "8.2.0" causes OOM on a box with 6GB of RAM
    "postcss-import": "^13.0.0",
    "postcss-loader": "^4.1.0",
    "postcss-preset-env": "^6.7.0",
    "postcss-url": "^10.1.1",
    "webpack": "^5.10.0",

I'm not sure what's useful to track here.  We pass `--max-old-space-size=8192` into the webpack process.  Our CSS build step is

```
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              import: false
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: false,
              postcssOptions: {
                config: require.resolve('../postcss.config.js'),
              },
            }
          }
        ]
      }
    ]
  },
```

The postcss.config.js is

```
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
  plugins: {
    'postcss-preset-env': postcssPresetEnv({ browsers: '> 1%', stage: 3 }),
    'postcss-url': {},
    autoprefixer: {},
  },
};

```

Any thoughts on how I can debug/troubleshoot?

**Comment by ai** [comment]
Can you try few latest PostCSS 8.1.x versions (get numbers from ChangeLog).

Let's detect the exact version of regression.

**Comment by jnardone** [comment]
It breaks from 8.1.14 to 8.2.0.

**Comment by ai** [comment]
Can you try 8.2.1?

**Comment by jnardone** [comment]
I'm going to close this.  We have a lot of moving parts right now.  I got failures on 8.2.1, but then also 8.1.14 sometimes.  we're also relatively new on webpack 5 so ... hard to narrow down.  We bumped the resource size on our CI builds to a larger class and will monitor for additional memory issues.  But I can't say postcss is the problem here at this point.  Sorry.
