### ISSUE TITLE
TypeError: this[node.type] is not a function at TemplateStringifier.stringify

### ISSUE THREAD

**Issue by julienben** [postcss/postcss#1490]
Hey there,

I'm using `stylelint` on a project with `@emotion/react` for CSS.

On a specific code pattern, `stylelint` throws this error:

![image](https://user-images.githubusercontent.com/8948127/102195178-e87ec180-3ec6-11eb-8c4c-851b6ac3dd53.png)

(Note: It happens both inside the IDE and the terminal.)

I'm posting here because the issue happens in `postcss`'s TemplateStringifier class but I'll be happy to hear if you believe there's a more adequate place to be reporting this.

This is the code which triggers this error:

```js
const myCss = css`
  ${checkSomething &&
  css`
    color: hotpink;
  `}
`;
```

Strangely, if I add a selector after this, the error no longer happens:

```js
const myCss = css`
  ${checkSomething &&
  css`
    color: hotpink;
  `}

  > div {
    color: blue;
  }
`;
```
Thank you in advance for any help!

**Comment by ai** [comment]
Can you debug the code and found that was `node.type` before the error?

**Comment by julienben** [comment]
Sure! I logged the `node.type` for the code which triggers the error and ended up getting 3 errors: `root`, `literal` and `root` again. See below.

![image](https://user-images.githubusercontent.com/8948127/102376695-8e682400-3fcc-11eb-8a3f-164b528c9f02.png)

Happy to help debug this further if you'd like!

**Comment by ai** [comment]
I improved error message 205e910

Sorry, it is an error inside Stylelint. They should not send non-standard AST to PostCSS.

**Comment by julienben** [comment]
Ok thanks Andrey. I'll report it there.
