### ISSUE TITLE
Deno test fails

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1496]
@oscarotero publish script was not able to convert PostCSS 8.2.2 release

https://github.com/postcss/postcss/runs/1623421462?check_suite_focus=true

**Comment by oscarotero** [comment]
Fixed in https://github.com/postcss/postcss-deno/commit/0d69d8021f413da342fb6cf2ca8e52c5ca0a751e and tagged (manually) the new version for Deno

**Comment by ai** [comment]
Thanks =^_^=
