### ISSUE TITLE
PostCSS fails to parse files that start with a Unicode Byte Order Mark with "CssSyntaxError: Unclosed block"

### ISSUE THREAD

**Issue by IceCreamYou** [postcss/postcss#1500]
I am using [dart-sass](https://github.com/sass/dart-sass) to compile my SCSS. For some [inexplicable reason](https://github.com/sass/dart-sass/issues/472) it prepends a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8), `U+FEFF`, to the start of its CSS output, which is allowed in UTF-8 and UTF-16. I tried to use [doiuse](https://github.com/anandthakker/doiuse) to parse this CSS and was very confused for awhile after getting this error:

```
CssSyntaxError: .../test.css:1:1: Unclosed block
    at Input.error (.../doiuse/node_modules/postcss/lib/input.js:104:16)
    at Parser.unclosedBlock (.../doiuse/node_modules/postcss/lib/parser.js:527:22)
    at ... {
  reason: 'Unclosed block',
  file: '.../test.css',
  line: 1,
  column: 1,
  input: {
    line: 1,
    column: 1,
    source: '@keyframes wipe{100%{background-position:-300% 0}',
    url: 'file:///.../test.css',
    file: '.../test.css'
  }
}
```

After removing the BOM, PostCSS correctly processes the file.

Now that I know what's going on, it is not a big deal, but it took awhile to figure out what was happening. Even if PostCSS just emitted a more descriptive error if the BOM is present, that would be helpful.

**Comment by ai** [comment]
We have a special code for BOM https://github.com/postcss/postcss/blob/main/lib/input.js#L25

Can you debug why it doesn’t work on your CSS?

**Comment by IceCreamYou** [comment]
I tried to poke around for awhile tonight but did not figure out why this is happening. Here is a repro:

```bash
$ echo $(perl -C -e 'print chr 0xfeff') '@keyframes wipe{100%{background-position:-300% 0}}' > postcss-test-1
$ doiuse --browsers "> 20%" ./postcss-test-1
CssSyntaxError: .../postcss-test:1:1: Unclosed block
	at ...<snip>
$ echo '@keyframes wipe{100%{background-position:-300% 0}}' > postcss-test-2
$ doiuse --browsers "> 20%" ./postcss-test-2 # success
$ git diff --word-diff=color --word-diff-regex=. ./postcss-test-1 ./postcss-test-2 
diff --git a/./postcss-test-1 b/./postcss-test-2
index bba8eae..b0d555b 100644
--- a/./postcss-test-1
+++ b/./postcss-test-2
@@ -1 +1 @@
<U+FEFF> @keyframes wipe{100%{background-position:-300% 0}}
```

and here is how `doiuse` is using postcss: https://github.com/anandthakker/doiuse/blob/master/stream.js#L25-L60

**Comment by ai** [comment]
Can you try to parse input with `postcss` without `doiuse`? `require('postcss').parse(css)`

**Comment by IceCreamYou** [comment]
This successfully prints a `Root` object:

```bash
node -e "console.log(require('/usr/local/lib/node_modules/doiuse/node_modules/postcss').parse(require('fs').readFileSync('./postcss-test-1', 'utf8')))"
```

**Comment by ai** [comment]
Send like we have a `doiuse` issue. Can you open an issue there?

**Comment by IceCreamYou** [comment]
Based on the stack trace I think it's more likely that there is an issue with postcss with non-default options passed to it, but it could certainly be possible that `doiuse` is doing something that doubles up on the BOM or something like that. If I have reason to try again at some point I'll open a ticket there. Thanks for your attention.

**Comment by ai** [comment]
Feel free to open another issue if you will be able to reproduce the issue with standard PostCSS
