### ISSUE TITLE
Enable plugins based on NODE_ENV

### ISSUE THREAD

**Issue by mischnic** [postcss/postcss#1506]
Using this pattern to only run purgecss in production 
```
const purgecss = require("@fullhuman/postcss-purgecss")({
	content: ["./index.html"],
});

module.exports = {
	plugins: [...(process.env.NODE_ENV === "production" ? [purgecss] : [])],
};
```

fails in development because `PostCSS config must have plugins`. Is there a (better) way to achieve this?

**Comment by mischnic** [comment]
Sorry, PostCSS isn't throwing that error....

**Comment by ai** [comment]
You need to run PostCSS only in production. Running PostCSS without plugins is just wasting CPU.
