### ISSUE TITLE
How to access project's browserslist within plugin

### ISSUE THREAD

**Issue by gdvsbp** [postcss/postcss#1511]
First, I apologize in advance if this is glaringly obvious, but I've looked through docs and other plugins (autoprefixer, mainly), and didn't find the answer I was looking for. Maybe that means the way I'm going about this isn't an option, but I figured it would be smarter to stop spinning my wheels and ask the community.

I'm writing a small custom plugin for a project I'm working on that adds some IE fallbacks for specific CSS declarations. **I'd _like_ to only run this plugin if the project's browserslist settings include the versions of IE I need to support.**

I know I can get these values by targeting the project's .browserslistrc, but that seems rather tightly-coupled to me. My expectation is that something would be exposed to the plugin with those browserslist values already available, since this is a PostCSS plugin.

Am I missing something obvious? Am I barking up the wrong tree?

If the answer is to just import browserslist and target package.json/.browserslistrc/whatever in a series of fallbacks, then so be it, but I'd like to avoid it if possible.

**Comment by ai** [comment]
You need to use Browserslist JS API:

https://github.com/browserslist/browserslist#js-api

**Comment by gdvsbp** [comment]
I found what I needed literally minutes after writing this and was just coming back to say how ashamed I was and close it. @ai thanks for closing the obvious thing for me.

**Comment by ai** [comment]
Obvious questions is not a problem.

Bad plugin design is a bad thing. And you are good because of using Browserslist 👍
