### ISSUE TITLE
Provide an ability to specify custom ID of the CSS source

### ISSUE THREAD

**Issue by hivokas** [postcss/postcss#1512]
Thanks for such a great tool!

As per docs:

```
Input#from
The CSS source identifier. Contains Input#file if the user set the from option, or Input#id if they did not.

const root = postcss.parse(css, { from: 'a.css' })
root.source.input.from //=> "/home/ai/a.css"

const root = postcss.parse(css)
root.source.input.from //=> "<input css 1>"
```

It would be great if it's possible to do something like that:

```
const root = postcss.parse(css, { id: 'foo' })
root.source.input.from //=> "<input css foo>"
```

Or maybe this feature is already available and I'm missing something?

_Context: https://github.com/tailwindlabs/tailwindcss/issues/3349_

**Comment by hivokas** [comment]
Looks like it's not possible to provide a custom ID:

https://github.com/postcss/postcss/blob/af8311a9c4c940c3e159f81bb205786677687e15/lib/input.js#L47-L49

**Comment by hivokas** [comment]
I want `root.source.input.from` to be the same for each build.

The only way I see it to pass `{ from: 'a.css' }` for the `opts` argument.

```
const root = postcss.parse(css, { from: 'a.css' })
root.source.input.from //=> "/home/ai/a.css"
```

However, I'm not sure whether it's okay to pass `'a.css'` if this file does not exist. Is there a reason I shouldn't do that?

**Comment by ai** [comment]
Why you can put a correct file name?

**Comment by hivokas** [comment]
> Why you can put a correct file name?

Do you mean **can't**?

That's because CSS is generated on the fly:

https://github.com/tailwindlabs/tailwindcss/blob/3fa7a22b00d357ed31102ca587b6436ecf7c5996/src/lib/substituteClassApplyAtRules.js#L352-L354

**Comment by ai** [comment]
In this case you can use JS file name: `from: __filename`

The idea of `from` option to help users to find the source of this file

**Comment by hivokas** [comment]
> In this case you can use JS file name: `from: __filename`
> 
> The idea of `from` option to help users to find the source of this file

It makes a lot of sense! Thanks a lot!
