### ISSUE TITLE
Unable to use built-in Bootstrap mixins and variables

### ISSUE THREAD

**Issue by strandofgenius** [postcss/postcss#1514]
Hello, I'm using a webpack 5 config with Bootstrap 4 and trying to figure out how to utilize the built-in mixins and variables and can't seem to figure out what I'm missing. I keep getting an error.

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
@include media-breakdown-up(md) {}
```

Here is what my loaders look like. I've installed `postcss-scss` but I can't tell if this is what I need to use. Any help would be great.

```
  {
      loader: 'css-loader',
      options: {
          sourceMap: false,
          url: false,
          import: false,
      },
  },
  {
      loader: 'postcss-loader',
      options: {
          sourceMap: false,
          postcssOptions: {
              path: path.resolve(__dirname),
              parser: require('postcss-scss'),
              plugins: [
                  ...postCssPlugins,
              ],
          }
      }
  },
  {
      // compiles Sass to CSS
      loader: 'sass-loader'
  }
```

**Comment by strandofgenius** [comment]
I figured out the mixin, I had a typo and it should be `@include media-breakpoint-up(md) {}`.

**Comment by strandofgenius** [comment]
I'm going to reopen because I'm still having trouble with overriding Bootstrap variables. I can't tell if this is something to do with postcss or something else since I can override some variables but not all available options from the bootstrap variables file.

```
## app.scss

@import "custom-variables";

@import "node_modules/bootstrap/scss/functions";
@import "node_modules/bootstrap/scss/variables";
@import "node_modules/bootstrap/scss/mixins";
... other bootstrap
... other custom sass files
```

**Comment by ai** [comment]
Sorry. I burned-out (because of the lack of community feedback during PostCSS 8 development) and do not accept the environmental issues.

If you know, what do you need to cheng in PostCSS, open the direct issue.
