### ISSUE TITLE
Deprecation warning in node v15.4.0

### ISSUE THREAD

**Issue by barak007** [postcss/postcss#1517]
Hello, I started to get this DeprecationWarning in node v15.4.0

(node:19956) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at [MY_PROJECT]\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by ai** [comment]
Update Node.js 15.x. This warning is from the bug, which was fixed in the latest 15.x version.

**Comment by barak007** [comment]
10x good to know
