### ISSUE TITLE
[Question] Is it possible to pass an async function to walkDecls?

### ISSUE THREAD

**Issue by npearson72** [postcss/postcss#1518]
I'm trying to modify the value of a background declaration, but for some reason when I pass an async function it doesn't set.

### This does not work

```
  const myFunction = () => new Promise(resolve => setTimeout(resolve('hello'), 3000));

  root.walkDecls(async dec => {
    if (dec.prop.match(/background/) && dec.value.match(/url/)) {
      dec.value = await myFunction();
    }
  });
```

### This does

```
  const myFunction = () => 'hello'

  root.walkDecls(dec => {
    if (dec.prop.match(/background/) && dec.value.match(/url/)) {
      dec.value = myFunction();
    }
  });
```

Is this by design? Is there a trick to this?

**Comment by ai** [comment]
Nope. `walkDecls` doesn't support async iterator.

You need to use PostCSS 8 syntax and register `Declaration` callback. You will have async support there.

https://github.com/postcss/postcss/blob/main/docs/writing-a-plugin.md

**Comment by npearson72** [comment]
Worked like a charm. Thanks!
