### ISSUE TITLE
Uncaught <css input>:20200:1: Unclosed block

### ISSUE THREAD

**Issue by deepwell** [postcss/postcss#153]
Re-post from https://github.com/reworkcss/css/issues/56 as requested (I think?)

PostCSS throws an error after parsing 20,200 lines of nested css.

```
/Users/etc/etc/node_modules/postcss/lib/input.js:46
    throw new CssSyntaxError(this, message, line, column);
          ^
<css input>:16917:1: Unclosed block
```

Maybe this is the expected behaviour. The css library discards those nested lines (if it's less than call stack limit), and postcss throw an error if closing brackets are missed.

**Comment by ai** [comment]
@arjay23 can I ask you to open a new issue?
