### ISSUE TITLE
What am I doing wrong with the -w option?

### ISSUE THREAD

**Issue by sabelapaulo** [postcss/postcss#1531]
I'm trying to have postcss watch my php files for changes, but for some reason it's not working. I must be doing something wrong. I'm using Tailwind with the php files. My package.json is:

```
{
  "name": "granularrubix",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "postcss -w styles.css -o style.css",
    "build": "NODE_ENV=production postcss styles.css -o style.css"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^10.2.4",
    "postcss": "^8.2.6",
    "postcss-cli": "^8.3.1",
    "tailwindcss": "^2.0.3"
  },
  "dependencies": {}
}
```

`npm run build` works great and is purging the file correctly! But `npm run start` does not update itself when I make changes to the php files. I thought this would be the point of the `-w` option? What am I doing wrong?

**Comment by ai** [comment]
You need to open an issue in `postcss/postcss-cli`

But seems like `-w` watches only for CSS files
