### ISSUE TITLE
[MIGRATE] TS to GoLang

### ISSUE THREAD

**Issue by danny007in** [postcss/postcss#1539]
because of performance
example https://github.com/evanw/esbuild

**Comment by Semigradsky** [comment]
@danny007in do you want to do this?

**Comment by danny007in** [comment]
If any GoLang expert 😃

**Comment by ai** [comment]
We will need completely a different API and UX for Go. SO it will be a completely different project.

The main problem that you will need to backport main PostCSS plugins like Autoprefixer or Stylelint.
