### ISSUE TITLE
Types for CSS modules

### ISSUE THREAD

**Issue by TeoTN** [postcss/postcss#1540]
It's not clear to me how should I define TypeScript types for CSS modules with postcss v8 ?
For the context, I'm using Gatsby v3 and an example import would be:
```
import { Header } from './header.module.css';
```

However, the old style `index.d.ts` I had won't be suitable anymore since default exports were replaced with tree-shakeable variables:
```
declare module '*.module.css' {
  const value: { [className: string]: string };
  export default value;
}
```

That pretty much now ends up in this error:
```
 Module '"*.module.css"' has no exported member 'Header'. Did you mean to use 'import Header from "*.module.css"' instead?
```
I'm not sure how this can be handled?

**Comment by ai** [comment]
Sorry. This repo is only about PostCSS core.

You need to ask about some specific PostCSS plugins (like CSS Modules) in plugin repo.

But I can recommend you a [nyancss](https://github.com/nyancss/nyancss) syntax sugar around CSS Modules. It could have a solution for TS.

**Comment by TeoTN** [comment]
Ah, I've somehow thought it's monorepo. Thanks, I'll ask around there
