### ISSUE TITLE
Can't have class named `default`

### ISSUE THREAD

**Issue by TeoTN** [postcss/postcss#1541]
Postcss v8 now fails if a class is named `default` because it gets transpiled to `const default = ...` and in that position `default` is seen as keyword. 
Presumably this can be extended to other JavaScript keywords like `new`, `this` or `function` that are valid CSS identifiers. (I'd imagine class `new` isn't particularly peculiar and someone may want to use it)

**Comment by ai** [comment]
What class? Can you show an example of how to reproduce the error?

**Comment by TeoTN** [comment]
`pill.module.css`
```
.default {
  transition: opacity 0.3s;
}
```

`Pill.tsx`
```
import * as classes from './pill.module.css';
```

Error:
```
ModuleParseError: Module parse failed: Unexpected keyword 'default' (17:13)
File was processed with these loaders:
 * ./node_modules/gatsby/node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export const angular = "pill-module--angular--3YNfe";
| export const rxjs = "pill-module--rxjs--XJsug";
> export const default = "pill-module--default--3GdzR";
| export default ___CSS_LOADER_EXPORT___;
```

**Comment by ai** [comment]
Sorry. It is again, the CSS Modules issue. I can only recommend avoiding `default` classes.
