### ISSUE TITLE
PostCSS plugin postcss-pxtorem requires PostCSS 8.

### ISSUE THREAD

**Issue by Wykyoyo** [postcss/postcss#1544]
How do you resolve one of the above error reporting cases

**Comment by caichuanwang** [comment]
‘PostCSS plugin postcss-pxtorem requires PostCSS 8.‘，how to resolve this question

**Comment by Wykyoyo** [comment]
> ‘PostCSS plugin postcss-pxtorem requires PostCSS 8.‘，how to resolve this question

npm install postcss-pxtorem@5.1.1 -D

**Comment by mehimanshupatil** [comment]
If you are using CRA avoid postcss 8 as mentioned [here](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users) for which you have to downgrade postcss-pxtorem to v5.1.1

**Comment by LIJUN-XU** [comment]
why this problem occurs?
