### ISSUE TITLE
Fails to parse CSS some variables edge cases

### ISSUE THREAD

**Issue by Andarist** [postcss/postcss#1545]
I'm sorry for bringing this up 🙈 I don't actually need this but it's a parsing bug that I've encountered while checking how this should behave.

Please note that I've not rechecked the correctness of this with [the spec text](https://www.w3.org/TR/css-variables-1/#syntax) (it's a little bit over my head for the moment) but `web-platform-tests` makes assertions on [some very weird cases](https://github.com/web-platform-tests/wpt/blob/f850adcd8f3464f79b5252d284860ac53c81ceb0/css/css-variables/test_variable_legal_values.html#L64&L86).

I've checked how this behaves in Chrome though so I believe that this with the combination of similar web platform tests is a solid ground for creating this issue.

```js
const inChrome = rule => {
  var s = document.createElement('style')
  document.head.append(s)
  s.sheet.insertRule(rule)
  return s.sheet.cssRules[0].cssText
}
```

**Actual**

> Uncaught CssSyntaxError: <css input>:1:1: Unclosed block

**Expected**

```js
inChrome('h1{--example: {}') // "h1 { --example: {}; }"
inChrome('body{--example:{} body{background:red;}') // "body { --example:{} body{background:red;}; }"
```

**Comment by ai** [comment]
Am I right that you are asking to fix CSS Custom Properties parsing for the edge cases of the `Expected` section?

Yeap, we can do it. But since we do not have a real use case, I can only accept PR.

**Comment by Andarist** [comment]
Yep, those expected cases should work - and the ones from web platform tests should also be checked.

I totally understand that you don't plan to fix this yourself. I've just raised this for awareness.

**Comment by haneenmahd** [comment]
I think this is where it is going wrong, the seperation part
> https://github.com/postcss/postcss/blob/2da5501f709862c19e7103b81ba8fb224a5793ff/lib/rule.js#L17-L21

OR

it may occur at parsing the emptyRules
> https://github.com/postcss/postcss/blob/2da5501f709862c19e7103b81ba8fb224a5793ff/lib/parser.js#L84-L90
