### ISSUE TITLE
Parsing issue in less variables

### ISSUE THREAD

**Issue by ssivanatarajan** [postcss/postcss#1548]
LESS

```
    @border-top:none !important;

```
while parsing the above code, getting property as "@borde-top:none" instead of "@border-top" . if there is no space between ":" and property, value getting incorrect results.

Seems the issue was due to the regexp(RE_AT_END) used in tokenize.js, this regexp is not contains ":" to split the property & value.

raised this issue in below dependants  

stylelint-  https://github.com/stylelint/stylelint/issues/5210
postcss-less -https://github.com/shellscape/postcss-less/issues/155

**Comment by Semigradsky** [comment]
Looks like `postcss-less` should use own tokenizer.

**Comment by ai** [comment]
You need a separated parser for Less. PostCSS core was not created to parse Less.
