### ISSUE TITLE
Ignore lines with blade logic in Laravel templates

### ISSUE THREAD

**Issue by szepeviktor** [postcss/postcss#1551]
Hello! Very nice to have PostCSS :)

```css
        @page {
            size: A4 {{ $orientation }};
        }
        div {
            font-size: {{ $orientation === 'landscape' ? '50px' : '40px' }};
        }
```

How to write a loader/parser/code to automatically ignore lines with blade logic?
Lines containing `{{ something }}`
They trigger various rules and cause syntax errors.

Please help me.

**Comment by ai** [comment]
It is hard. You will need to write custom parser:

https://github.com/postcss/postcss/blob/main/docs/syntax.md

**Comment by szepeviktor** [comment]
Thank you.

Hard means *possible*.
