### ISSUE TITLE
Postcss in Parcel-bundler does not work; No CSS modules used

### ISSUE THREAD

**Issue by Isabella-C** [postcss/postcss#1554]
I am using Parcel-bundler@1.12.3, installed with npm.

My CSS is generic pure CSS with no modules or SASS or anything used. 

The "parcel index.html" works perfectly. 

However, when run "parcel build index.html --no-content-hash --out-dir public --no-cache --no-source-maps --public-url ./", parcel began to automatically install postcss and all the dependencies. Then throw this error. 

I have tried to disable all my original CSS and use a dummy CSS for my index.html, the issue still persist.

test.css

`   body {
        background-image: linear-gradient(90deg, #303133, #303133);
        font-family: 'Open Sans', sans-serif;
        font-weight: 200;
        min-height: 100vh;
        margin: 0;
        color: #d3d3d3;
    }
`

Error

> > C:\Users\...\frontend\styles\test.css:undefined:undefined: plugin is not a function 
   > at LazyResult.run (C:\Users\...\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:288:14) 
   at LazyResult.asyncTick (C:\Users\...\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:212:26) 
   at C:\...\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:254:14 at new Promise (<anonymous>) 
   at LazyResult.async (C:\Users\...\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:250:23) 
   at LazyResult.then (C:\Users\...\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:131:17)

![image](https://user-images.githubusercontent.com/11308553/114791024-1585a700-9dc9-11eb-9ff5-47e21f08ba57.png)

**Comment by ai** [comment]
You need to move to Parcel 2 beta.

This error often came from using PostCSS 8 plugins in PostCSS 7. But only Parcel 2 supports PostCSS 8.
