### ISSUE TITLE
Get a relative path broken file

### ISSUE THREAD

**Issue by semiromid** [postcss/postcss#1556]
Hello @ai !

https://postcss.org/api/#csssyntaxerror-file

> CssSyntaxError#file
> Absolute path to the broken file.
> error.input.file.

Is it possible to get a relative path?

**Comment by ai** [comment]
You can use [`relative()`](https://nodejs.org/api/path.html#path_path_relative_from_to) from Node.js API.

Do you need to show shorter path to user? Use `path.relative(process.cwd(), error.file)`
