### ISSUE TITLE
package.json fix to resolve nodejs 16 deprecation message DEP0148

### ISSUE THREAD

**Issue by guypes** [postcss/postcss#1558]
Just update nodejs to version 16.0.0,
serving angular 11.2.10 app,
have this message:

**(node:19852) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\ProgettoTest\wui-work\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".**

fixed modifying line 59 of your package.json:

```
  "exports": {
    ".": {
      "require": "./lib/postcss.js",
      "import": "./lib/postcss.mjs",
      "types": "./lib/postcss.d.ts"
    },
    "./*": "./*"  <=== line 59
  },
```

was:

`    "./": "./"`

Hope it help others...

**Comment by guypes** [comment]
Correction, in the source of package.json on github, the line, where reside the problem, is 14 (not 59 as in my copy on node_modules).

**Comment by ai** [comment]
This fix will break Node.js 14 support.

**Comment by guypes** [comment]
I have downgraded to nodejs (Node: 14.16.1) and the fix work there too.

**Comment by ai** [comment]
@guypes here is a way to test it:

1. Create a new npm project and install your fixed PostCSS by `yarn add postcss@../path/to/postcss`
2. Create ES-project (with `type: "module"` in `package.json`) and install fixed PostCSS there.
3. Add a script which will run PostCSS: `console.log(postcss([]).process('a{}').css)`
4. Run both projects on the latest Node.js 10, 12, 14, 16.

**Comment by KhizerRehan** [comment]
@ai 
node -v -> v16.17.1
```
⠋ Generating browser application bundles...(node:47623) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ....ui/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
⠸ Generating browser application bundles (phase: building)...^C
mac@Macs-MacBook-Pro-2 ui % node -v

mac@Macs-MacBook-Pro-2 ui % node -v
v16.17.1
mac@Macs-MacBook-Pro-2 ui % npm -v
8.15.0
mac@Macs-MacBook-Pro-2 ui % 
```

**Comment by ai** [comment]
@KhizerRehan what is `postcss` version?

**Comment by KhizerRehan** [comment]
@ai "version": "8.2.4" but i don't have any dependency in my lock file it something get installed from when npm install command is run to install packages

**Comment by ai** [comment]
@KhizerRehan you need to learn how to make `deep dependencies updates in npm`.

There are many ways depending on your environment.

I personally prefer to switch to `pnpm`, because it has `pnpm update -r postcss`.

**Comment by KhizerRehan** [comment]
@ai I added a new `devDependencies` with     "postcss": "^8.4.21", version hence it overrides  `8.2.4` default deep dependencies and guess what it worked 🎉 for me. Is it a something to concern due to extra dependency added or is it good to go?

**Comment by ai** [comment]
This method doesn’t always work. In `npm` you could have a difference versions of the library in some cases.
