### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by semiromid** [postcss/postcss#1559]
Hi @ai !

I found an error in the documentation

https://postcss.org/api/#csssyntaxerror

> CssSyntaxError#source
> Source code of the broken file.
> 
> error.source       //=> 'a { b {} }'
> error.input.column //=> 'a b { }'

I think it will be right this way:

> CssSyntaxError#source
> Source code of the broken file.
> 
> error.source       //=> 'a { b {} }'
> error.input.source //=> 'a b { }'

**Comment by ai** [comment]
Yeap. Can you send PR?

**Comment by semiromid** [comment]
@ai 

Yes, of course, but I don't know where located the site data is.

**Comment by ai** [comment]
`lib/css-syntax-error.d.ts`

**Comment by semiromid** [comment]
I did.
https://github.com/postcss/postcss/pull/1560
