### ISSUE TITLE
How to process with Deno? #Question #Help

### ISSUE THREAD

**Issue by ldexterldesign** [postcss/postcss#1565]
Hi!

Thanks for software

Would someone be kind enough to elaborate on the Deno example?

Should postcss handle the file read/write (i.e. `.process({from|to})` option arguments) or does one need to involve the likes of `Deno.readTextFile | Deno.writeTextFile` to do this?

Hope to hear back

Cheers

PS happy to PR the read me later if that's appropriate..?

**Comment by ai** [comment]
This is PostCSS core library. It just process one CSS string to another CSS string. It doesn't read files, you need load CSS string by your own.

**Comment by ai** [comment]
@oscarotero can give a full example

**Comment by ldexterldesign** [comment]
FYI https://mastodon.social/@ldexterldesign/106115616665624601

**Comment by oscarotero** [comment]
@ldexterldesign PostCSS process CSS code but it doesn't read/write files. A basic example using postcss_import plugin:

```js
import postcss from 'https://deno.land/x/postcss@8.2.12/mod.js';
import postcssImportPlugin from 'https://deno.land/x/postcss_import@0.1.2/mod.js';

const runner = postcss([ postcssImportPlugin() ]);

const from = "styles.css";
const to = "styles.output.css";
const code = await Deno.readTextFile(from);

const result = await runner.process(code, { from, to });

await Deno.writeTextFile(to, result.css);
```

As a real implementation, the postcss plugin of Lume static site generator can help: https://github.com/lumeland/lume/blob/master/plugins/postcss.js#L28

**Comment by ldexterldesign** [comment]
Hi @oscarotero,

Thanks for reply

Oh my f#ck, I knew I should have reviewed that module, I saw it in the select menu 🙄

<img width="1904" alt="Screenshot 2021-04-24 at 00 38 30" src="https://user-images.githubusercontent.com/1715809/115939251-75e5aa00-a495-11eb-9282-6fba6e530c76.png">

Thanks

**Comment by ldexterldesign** [comment]
@oscarotero oh, and thanks for the Lume tip - my next task is setting up a Deno HTTP server - which I was dreading TBH - so I may use your SSG

**Comment by ldexterldesign** [comment]
👋 https://github.com/denosaurs/denon#watcher
