### ISSUE TITLE
DeprecationWarning" of Folder Mapping in Node 16.0.0

### ISSUE THREAD

**Issue by UsamaAshraf82** [postcss/postcss#1568]
(node:2643) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /tmp/build_1f1b1baa/node_modules/postcss-safe-parser/node_modules/postcss/package.json.

**Comment by ai** [comment]
Update to latest PostCSS. We fixed it in the latest version.

You will need `yarn update`/`npm update` to update nested dependenies.
