### ISSUE TITLE
Regular Expression Denial of Service even after i installed version 8.2.15

### ISSUE THREAD

**Issue by k4l3b-plo** [postcss/postcss#1578]
npm still says 79 vulnerabilities required manual review and could not be updated and i don't know what to do, need help

**Comment by ai** [comment]
Remove not update all dependencies which require PostCSS 7

**Comment by k4l3b-plo** [comment]
> Remove not update all dependencies which require PostCSS 7

how do i remove them manually or is their an automatic way?

**Comment by ai** [comment]
Sorry, I can't help you with npm today. Have too many tasks.

**Comment by k4l3b-plo** [comment]
> Sorry, I can't help you with npm today. Have too many tasks.

okay, no worries, thanks tho

**Comment by mohkoma** [comment]
This is how I solved it , First I added the next line to scripts inside `package.json `
```
"scripts": {
     "preinstall": "npx npm-force-resolutions"
}
```
then add this to also to bottom of `package.json `
Note: use the version installed in my case I have `8.3.0`

```
"resolutions": {
        "postcss": "8.3.0"
}
```

Finally run `npm install`
This could be a nice temporary solution until we get the patch
