### ISSUE TITLE
Unknown error from PostCSS plugin (Not an issue)

### ISSUE THREAD

**Issue by robbiecren07** [postcss/postcss#1579]
I'm getting an error:
`Unknown error from PostCSS plugin. Your current PostCSS version is 8.1.14, but postcss-functions uses 6.0.23. Perhaps this is the source of the error below.`

I just upgraded one of my devDependencies; laravel-mix, and once once I ran yarn start, postcss automatically upgrade to 8.1. Does this mean I need to upgrade all of my postcss plugins that i'm calling in my postcss.config.js file? I'm using about 25 different ones. Or does it have to do with the way I wrote my postcss.config.js file.

**Comment by ai** [comment]
You may need to update only old PostCSS plugins to use PostCSS 7 or PostCSS 8.
