### ISSUE TITLE
Website - Change API doc page title depending on anchor in the url

### ISSUE THREAD

**Issue by JesusTheHun** [postcss/postcss#1581]
### Problem
As someone who is currently learning postcss, I open several browser tab of the doc, pointing to different sections. Sadly, all those tabs have the same name, making it difficult to identify each tab.

I would love to be able to identify each tab I have open in the documentation

### Solution
As a solution, I think it would be nice and easy to have the title of the page change depending on the anchor in the url

**Comment by ai** [comment]
I personally think that it will be too complicated and unstable.

But you can send PR.

I am closing this issue, because I do not think we should keep this task in Todo.

**Comment by JesusTheHun** [comment]
What do you use for your website ?

**Comment by ai** [comment]
https://github.com/postcss/postcss.org

It is my own script to compile TypeDocs to HTML and Parcel to generate assets.
