### ISSUE TITLE
Module build failed when using mini-css-extract-plugin with postcss-loader for less

### ISSUE THREAD

**Issue by KID-joker** [postcss/postcss#1588]
# Bug report
Module build failed when using mini-css-extract-plugin with postcss-loader for less. If I remove postcss-loader from the loaders list, then it builds correctly. Problem with mini-css-extract-plugin or postcss-loader ?

**What is the current behavior?**
> ERROR in ./src/views/app.vue?vue&type=style&index=0&lang=less& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??clonedRuleSet-7[0].rules[0].use[1]!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-7[0].rules[0].use[2]!./node_modules/less-loader/dist/cjs.js??clonedRuleSet-7[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/views/app.vue?vue&type=style&index=0&lang=less&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (E:\demo\node_modules\postcss\lib\lazy-result.js:522:33)
    at LazyResult.runAsync (E:\demo\node_modules\postcss\lib\lazy-result.js:402:30)
    at async Object.loader (E:\demo\node_modules\postcss-loader\dist\index.js:87:14)
    at processResult (E:\demo\node_modules\webpack\lib\NormalModule.js:700:19)
    at E:\demo\node_modules\webpack\lib\NormalModule.js:806:5
    at E:\demo\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at E:\demo\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (E:\demo\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (E:\demo\node_modules\postcss-loader\dist\index.js:96:7)
 @ ./src/views/app.vue?vue&type=style&index=0&lang=less& 1:0-482 1:0-482
 @ ./src/views/app.vue 4:0-64
 @ ./src/main.js 7:0-32 28:13-20

**If the current behavior is a bug, please provide the steps to reproduce.**

```
exports.cssLoaders = function (options) {
    options = options || {}

    const cssLoader = {
        loader: 'css-loader',
        options: {
            sourceMap: options.sourceMap
        }
    }

    const postcssLoader = {
        loader: 'postcss-loader',
        options: {
            sourceMap: options.sourceMap
        }
    }

    // generate loader string to be used with extract text plugin
    function generateLoaders (loader, loaderOptions) {
        const loaders = []

        // Extract CSS when that option is specified
        // (which is the case during production build)
        if (options.extract) {
            loaders.push(MiniCssExtractPlugin.loader)
        } else {
            loaders.push('vue-style-loader')
        }

        loaders.push(cssLoader)

        if (options.usePostCSS) {
            loaders.push(postcssLoader)
        }

        if (loader) {
            loaders.push({
                loader: loader + '-loader',
                options: Object.assign({}, loaderOptions, {
                    sourceMap: options.sourceMap
                })
            })
        }

        return loaders
    }
    return {
        css: generateLoaders(),
        postcss: generateLoaders(),
        less: generateLoaders('less'),
        sass: generateLoaders('sass', {
            indentedSyntax: true
        }),
        scss: generateLoaders('sass'),
        stylus: generateLoaders('stylus'),
        styl: generateLoaders('stylus')
    }
}
```

**Other relevant information:**
- webpack 5.37.1
- mini-css-extract-plugin 1.6.0
- postcss-loader 5.3.0
- less 4.1.1

**Comment by ai** [comment]
Try to install `postcss` to your project:

```sh
npm install postcss
```

It will update PostCSS to version 8 and fix this version incompatibility issue.

**Comment by KID-joker** [comment]
> Try to install `postcss` to your project:
> 
> ```shell
> npm install postcss
> ```
> 
> It will update PostCSS to version 8 and fix this version incompatibility issue.

It doesnt work. I have installed postcss. It still reports error `node.getIterator is not a function`

**Comment by ai** [comment]
1. What PostCSS plugins do you use?
2. Check `npm ls` output to find all PostCSS 7 dependencies

**Comment by KID-joker** [comment]
> 1. What PostCSS plugins do you use?
> 2. Check `npm ls` output to find all PostCSS 7 dependencies

1.
- "postcss": "^8.3.0",
- "postcss-import": "^14.0.2",
- "postcss-loader": "^5.3.0",
- "postcss-px2rem-exclude": "0.0.6",
- "postcss-url": "^10.1.3",

2.
```
| `-- postcss-value-parser@4.1.0
| +-- postcss@8.3.0 deduped
| +-- postcss-modules-extract-imports@3.0.0
| +-- postcss-modules-local-by-default@4.0.0
| | +-- postcss-selector-parser@6.0.6
| | `-- postcss-value-parser@4.1.0 deduped
| +-- postcss-modules-scope@3.0.0
| | `-- postcss-selector-parser@6.0.6 deduped
| +-- postcss-modules-values@4.0.0
| +-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-calc@8.0.0
| | | | +-- postcss-selector-parser@6.0.6 deduped
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-colormin@5.1.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-convert-values@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-discard-comments@5.0.1
| | | +-- postcss-discard-duplicates@5.0.1
| | | +-- postcss-discard-empty@5.0.1
| | | +-- postcss-discard-overridden@5.0.1
| | | +-- postcss-merge-longhand@5.0.2
| | | | +-- postcss-value-parser@4.1.0 deduped
| | | |   `-- postcss-selector-parser@6.0.6 deduped
| | | +-- postcss-merge-rules@5.0.1
| | | | +-- postcss-selector-parser@6.0.6 deduped
| | | +-- postcss-minify-font-values@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-minify-gradients@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-minify-params@5.0.1
| | | | +-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-minify-selectors@5.1.0
| | | | `-- postcss-selector-parser@6.0.6 deduped
| | | +-- postcss-normalize-charset@5.0.1
| | | +-- postcss-normalize-display-values@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-positions@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-repeat-style@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-string@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-timing-functions@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-unicode@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-url@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-normalize-whitespace@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-ordered-values@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-reduce-initial@5.0.1
| | | +-- postcss-reduce-transforms@5.0.1
| | | | `-- postcss-value-parser@4.1.0 deduped
| | | +-- postcss-svgo@5.0.1
| | | | +-- postcss-value-parser@4.1.0 deduped
| | | `-- postcss-unique-selectors@5.0.1
| | |   +-- postcss-selector-parser@6.0.6 deduped
| `-- postcss@8.3.0 deduped
+-- postcss@8.3.0
+-- postcss-import@14.0.2
| +-- postcss-value-parser@4.1.0 deduped
+-- postcss-loader@5.3.0
+-- postcss-px2rem-exclude@0.0.6
| +-- postcss@5.2.18
+-- postcss-url@10.1.3
| | +-- postcss@7.0.35
| | +-- postcss-selector-parser@6.0.6 deduped
```

**Comment by ai** [comment]
1. Can you disable all plugins and check the error?
2. Do you use any PostCSS parsers like `postcss-scss`?

**Comment by KID-joker** [comment]
ok. I found the plugin `postcss-px2rem-exclude` that caused the error.
Thanks for your answer
