### ISSUE TITLE
"margin-inline-start" and "padding-inline-start" are lost after compilation

### ISSUE THREAD

**Issue by y805939188** [postcss/postcss#1591]
HI, seniors, I want to consult a question.
In my case, I used the following style：
<img width="346" alt="截屏2021-06-01 下午9 45 58" src="https://user-images.githubusercontent.com/28889103/120333913-c23cc900-c322-11eb-8625-de59b2795e07.png">
I used the  "margin-inline-start" and the style "padding-inline-start".
It works fine in less, but after "postcss" compilation, these two styles will be lost:
<img width="608" alt="截屏2021-06-01 下午9 48 04" src="https://user-images.githubusercontent.com/28889103/120334226-0def7280-c323-11eb-8c60-c9dd2544db8f.png">
My postcss configuration is as follows:
<img width="603" alt="截屏2021-06-01 下午9 48 57" src="https://user-images.githubusercontent.com/28889103/120334391-2c556e00-c323-11eb-9803-01d4cb75cc26.png">
postcss version is 8.2.14:
![image](https://user-images.githubusercontent.com/28889103/120334520-45f6b580-c323-11eb-8fb6-aef5c3b951a3.png)

Is there some configuration required to compile normally?
Thanks.

**Comment by ai** [comment]
PostCSS doesn't delete it since it just parse CSS.

I think postcss-preset-env transpile these properties. Check out their docs and remove polyfill for Logical Properties if you do not need them.

**Comment by y805939188** [comment]
> .

Thank you.
