### ISSUE TITLE
Outputing multi-level folder

### ISSUE THREAD

**Issue by Ryan-da-ghost** [postcss/postcss#1594]
Here is my gulp file: 
```js
var gulp = require("gulp");
var postcss = require("gulp-postcss");
var autoprefixer = require("autoprefixer");
var cssnano = require("cssnano");
var precss = require("precss");
var gulp = require("gulp");
var browserSync = require("browser-sync").create();

gulp.task("css", function () {
  var plugins = [autoprefixer, cssnano, precss];
  return gulp
    .src("./assets/styles/*")
    .pipe(postcss(plugins))
    .pipe(gulp.dest("./assets/output/"));
});
```
My css folder 
--- styles
 ---- base
 ---- layouts
 ---- abstarcts
-- style.css
postcss only outputs the style.css file can someone help mee?  i tried a lot of stuff but nothing is working

**Comment by Ryan-da-ghost** [comment]
i changed it to     .src("./assets/styles/*/*.css") now it works but the style.css doesnt compile anymore!

**Comment by ai** [comment]
You need an opening issue in `gulp-postcss`
