### ISSUE TITLE
The warning about not setting a parser or plugins has false positives when using the syntax option

### ISSUE THREAD

**Issue by stof** [postcss/postcss#1597]
When setting the syntax through the `syntax` option instead of setting the `parser` option, the warning about doing nothing is displayed by postcss. But I have a custom parser thanks to the syntax I set.

**Comment by ai** [comment]
Thanks for the report. I will try to fix it today.

**Comment by ai** [comment]
Fixed 81bf67f

**Comment by ai** [comment]
Released in 8.3.1

**Comment by ai** [comment]
@stof wait a second. Why do you need to use PostCSS without plugins and with the same syntax for parser and stringifier?

```js
postcss([]).process(source, { syntax: scss })
```

In this case, input will be equal to output.

**Comment by stof** [comment]
@ai I have a case where I generate some scss based on some other scss. As part of this, I inline all imported files into my main AST (before running other plugins removing lots of things from the AST). So here, I parse the input to get the AST and insert it to replace the `@import` node in the other tree. I don't stringify it directly.
