### ISSUE TITLE
Where is...

### ISSUE THREAD

**Issue by begrafx** [postcss/postcss#1598]
OK, this is probably a complete bonehead question, but I've searched Google and can't seem to find the answer. Here's the TLDR; version:

Operating System: MacOS Mojave

If I `npm install -g postcss`, where is the PACKAGE.JSON file showing that install?

**Comment by ai** [comment]
`npm` download archive from npm registry. This archive contains `package.json`. This archive I upload this archive during the publish. I use `clean-publish` tool to compress `package.json` from this repo before putting it to uploading archive.

**Comment by begrafx** [comment]
OK, here's the situation: 

I'm working on a project, I start it off and I get a message

`postcss-discard: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration`

OK, Fine. So I go to that link, one of the first things it says is

`The first step is very simple. Just remove PostCSS version 7 from your dependencies and add PostCSS version 8 to devDependencies.` So I type `postcss --version` and it comes back with the PostCSS logo, with v6.1.3 in the circle. So I follow the article's instructions, and `npm uninstall postcss
npm install postcss --save-dev`. I `postcss --version` to confirm the update has taken place, and it still says v6.1.3. I look at the PACKAGE.JSON in my project folder, and it says, `"postcss": "^8.3.0",` So I'm thinking OK, the Version 6 must be a global install, that is overriding the local install. So I type `npm update -g` it does its thing, comes back saying it changed x number of packages and so on and so forth. I type `postcss --version` again, and it still says version 6.1.3. If I type `which postcss` regardless of whether it's in the project folder or the root, it comes back saying `/usr/local/bin/postcss`. So I'm trying to figure out WHERE this `/usr/local/bin/postcss` install comes from, so that I can update it, or whatever.

**Comment by ai** [comment]
> postcss --version

It shows the version of `postcss-cli`, the CLI wrapper around PostCSS.

It has a different version system.

Use `npm ls | grep postcss` to get versions of PostCSS in your system (and `npm ls` to see who loads old PostCSS).

**Comment by begrafx** [comment]
From my project folder:

`$ npm ls | grep postcss
├── postcss-assets@6.0.0
├── postcss-import@14.0.2
├── postcss-loader@5.3.0
├── postcss-preset-env@6.7.0
├── postcss@8.3.0
`

**Comment by begrafx** [comment]
$ npm ls | grep postcss
├── postcss-assets@6.0.0
├── postcss-import@14.0.2
├── postcss-loader@5.3.0
├── postcss-preset-env@6.7.0
├── postcss@8.3.0

**Comment by ai** [comment]
This means, that everyone is using PostCSS 8. You can go to the nest step

**Comment by begrafx** [comment]
OK. Thank you.
