### ISSUE TITLE
Need help plugin that uses Once. The return values don't show up in the file

### ISSUE THREAD

**Issue by navanshu** [postcss/postcss#1601]
I am making a plugin that works using "Once". I have developed plugins before I want to process the complete css file as a string and perform some replacement over it. 
```javascript
module.exports = (opts) => {
    return {
        postcssPlugin: 'postcss-xyz',
        Once: plugin
    };
};
```
I need to do it only once after all plugin have completed. I have succeded in my work of replacing things but I cannot get it to output the transformed css even though I am wrapping it in 
```javascipt 
postcss.parse(x).nodes;
```
I have used AtRules where you can just return the same but this is not working.

**Comment by ai** [comment]
Do you need PostCSS if you work with CSS like a string? It is better to be a separated tool like Sass, which you run before PostCSS (in your case you will run it after PostCSS).

> I have used AtRules where you can just return the same but this is not working.

Show me what code do you have before, input, expected output and actual output.

**Comment by navanshu** [comment]
I know that but that would have been very easy to do, anyways I soled it using the declaration, but it definetly got a bit more complexd that way.

**Comment by ai** [comment]
If you are writing small in-house plugin, you can use `OnceExit`, but work with AST, not string.

**Comment by navanshu** [comment]
I am almost done with it and will publish it by tomorrow.
I used the Declaration property and its performace has a 100ms advantage.

**Comment by ai** [comment]
It will be even faster when you will have multiple plugins
