### ISSUE TITLE
CSS parser error for values containing double braces

### ISSUE THREAD

**Issue by bhavinkamani** [postcss/postcss#161]
Postcss errors out when it sees css property values containing double braces. For example
```
require('postcss')(function (css) { }).process(".fullscreen a { transition: {{input_transition}} }").css
```
throws `CssSyntaxError: <css input>:1:31: Unknown word`.

Is this because it is illegal CSS? I am required to use double braces for data-binding while using [polymerjs](https://www.polymer-project.org/).

Any workaround will be appreciated.

**Comment by ai** [comment]
Yeap, it is because this CSS is totally illegal :)

**Comment by bhavinkamani** [comment]
Oh..  Is there a way to bypass parsing for certain section of css using annotations (like /* autoprefixer: off /*)?

**Comment by ai** [comment]
Nope, because we need to parse content to find this section :).

What task you want to serve. Maybe there is other solution.

**Comment by bhavinkamani** [comment]
I need this for using data-binding in polymerjs. Alternative is to bind them manually using javascript which become little ugly. It a front-end templating syntax for data-binding. For example - http://jsbin.com/pelon/1/edit?html,output

**Comment by ai** [comment]
You can add special format to CSS like: `[[var]]` and then replace `[[]]` to `{{}}` after PostCSS.

**Comment by ai** [comment]
BTW, when PostCSS will have custom parsers #140 we can add special parser, which will be able to parse `{{`.

But I can’t add `{{` to common parser, because there is some CSS draft, wich uses `{{` as part of new syntax. So we will have conflict.

**Comment by bhavinkamani** [comment]
Hmmm.... yep that's a decent workaround. Thanks a ton.

**Comment by bhavinkamani** [comment]
Hmmm.. Thats a great short term workaround and long term solution. Thanks a ton.
