### ISSUE TITLE
When using "CRLF" line breaks, the "each" function in less cannot be parsed

### ISSUE THREAD

**Issue by ydiguo** [postcss/postcss#1614]
When I use less's "each" function (with "CRLF" line breaks), stylelint reports an error: "Unknown word (CssSyntaxError)stylelint(CssSyntaxError)".

![image](https://user-images.githubusercontent.com/55911510/125656118-6946b8fb-1b3b-409b-9bf0-bf2d02be4764.png)

By looking at the source code of stylelint, postcss-less, and postcss, I found some problems in the lib/tokenize.js file of the postcss package, when using RE_BAD_BRACKET(/.[\\/("'\n]/) to parse the code, only The "LF(\n)" line breaks is parsed, but the "CRLF(\r\n)" line breaks is not parsed.

![image](https://user-images.githubusercontent.com/55911510/125658536-2f3745ef-e23d-4005-a870-83f6b81f7691.png)

Therefore, when I use "CRLF" line breaks under Windows system, postcss parses "each(" into "each brackets", and then this parsing result is received by postcss-less, but postcss-less does not recognize "each brackets", so the error "Unknown word (CssSyntaxError)stylelint(CssSyntaxError)" was reported, and the error was passed to stylelint.

Therefore, in the RegExp of RE_BAD_BRACKET(/.[\\/("'\n]/), should the parsing of the "CRLF" line break be added, such as /.[\\/("'\r\n]/ ?

**Comment by ai** [comment]
Can you find a pure CSS case for this bug?

LESS parser is a separated project and should not use PostCSS core parser, but we will fix this bug for CSS. However, we need an input example for tests.

**Comment by ydiguo** [comment]
So sorry, I don't have a pure css case, because there is no similar function in css. 

But I found that the LESS parser is extend from the PostCSS core parser. So should this problem be fixed by PostCSS or by LESS parser(PostCSS-LESS) ?

![image](https://user-images.githubusercontent.com/55911510/125970354-51b88858-742b-48a2-baeb-6d6f2ad6970d.png)

**Comment by ai** [comment]
Extending parsers is prohibit from PostCSS 8. You need to open an issue in `postcss-less`.
