### ISSUE TITLE
Question: CC0-1.0 PostCSS plugins and patents

### ISSUE THREAD

**Issue by mvniekerk** [postcss/postcss#1619]
Question relates to the use of PostCSS in a commercial context.

Context: There are lots of plugins done by Johnathan Neal (@jonathantneal, hi!) , but these plugins are CC0-1.0 licensed.
In section 4.a of the license states "No trademark or patent rights held by Affirmer are waived, abandoned, surrendered, licensed or otherwise affected by this document."

Question 1: Is PostCSS thus patent encumbered by the use of any CC0-1.0 library?
Question 2: PostCSS can be seen as a "compiler" in that it transmutes CSS source code. Is this seen as a business process, which can be patentable?
Question 3: And the use of this business process, the produced artefact (the "compiled" CSS) is shipping that CSS liable for any patent royalties?
Question 4: Are there any projects that removed the CC0-1.0 libraries from PluginCSS which I can follow?

**Comment by ai** [comment]
Hi. I am not a lawyer to make law advice.

Personally, I think this question is far away from open source practice and the context of CSS processing (most of plugins are trivial and had nothing to make patent if we are using patent system respectfully). There are much more dangerous things (like open source maintainer burn out, which create much more problems to the business).

If you are creating a very specific product with unique law requirements just pay to Jonathan to licence you his code on specific license that you want.

**Comment by jonathantneal** [comment]
Hi, @mvniekerk! I’m [asking the community](https://twitter.com/jon_neal/status/1418550215662055431) how I can update my licenses to ensure there are no issues. Feel free to redirect this issue to one of those plugins. This repository is for PostCSS itself, which is MIT, and maintained by @ai.

**Comment by ai** [comment]
(It is still not a legal advice) I do not see any patent agreement in MIT license as well. As I know only GPL/LGPL talk about patents. So I personally do not see a big difference between MIT and CC-0 in terms of patent risks.

**Comment by mvniekerk** [comment]
I have reached out to @jonathantneal on my work e-mail to hear from him wrt this issue.
I'm raising this issue pertinently here also because:
a) These are plugins used by PostCSS so the patent license issue is non-obvious in that it is buried as a dependency.
b) Although it is not standard open source practice, it does not negate the issue that using PostCSS can make you liable for patent fees.

And yes, burnout is an issue. Making unshippable code or opening yourself up for litigation later can be dangerous.

**Comment by mvniekerk** [comment]
Thank you @jonathantneal, I appreciate the comment
