### ISSUE TITLE
postcss failed with TypeError: Invalid PostCSS Plugin found at: plugins[0]

### ISSUE THREAD

**Issue by SathyanaryanaNaidu** [postcss/postcss#1630]
Could you please help me , what is wrong here. ?? 

Next Js : 11

```
"dependencies": {
    "fastify": "^3.18.0",
    "lost": "^8.3.1",
    "next": "^11.0.1",
    "next-pwa": "^5.3.1",
    "postcss": "^8.3.6",
    "postcss-import": "^14.0.2",
    "postcss-mixins": "^8.1.0",
    "postcss-nested": "^5.0.6",
    "postcss-simple-vars": "^6.0.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-jsx": "^4.0.0",
    "styled-jsx-plugin-postcss": "^4.0.1"
  },
```

**.bablerc**

`{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}`

**postcss.config.js** 
```
const breakpointMixins = require("./configs/styles/mixins/breakpointMixing");
const placeholderMixins = require("./configs/styles/mixins/placeHolderMixin");

module.exports = {
  plugins: [
    "lost",
    "postcss-nested",
    "postcss-simple-vars",
    [
      "postcss-import",
      {
        path: ".",
      },
    ],
    [
      "postcss-mixins",
      {
        mixins: { ...breakpointMixins, ...placeholderMixins },
      },
    ],
  ],
};
```

**breakpointMixing.js** 
```
const breakpointMixins = { smallerMobile() {
    return {
      [`@media (min-width: 0px) and (max-width:370px)`]: {
        "@mixin-content": {},
      },
    };
  }
}
module.exports = breakpointMixins;

```

**placeHolderMixin.js** 
```
`const placeholderMixins = {
  placeholder() {
    return {
      "&::placeholder": {
        "@mixin-content": {},
      }
    };
  },
};

module.exports = placeholderMixins;`
```

**Comment by ai** [comment]
1. Can you remove `lost` and try to run PostCSS without it (just to find what plugin is broken)?
2. How do you run PostCSS? Can you try to run it by `postcss-cli` to test that it is not a Next.js issue?

**Comment by SathyanaryanaNaidu** [comment]
@ai   Yea i tried both, still same error 
 ` "postcss:watch": "postcss containers/LayoutContainer/LayoutContainer.style.js --dir dist --watch"`

**LayoutContainer.style.js**
```
import css from "styled-jsx/css";

const backgroundColor = "#eee";

const layOutStyle = css`
  $color: red;
  .hello {
    background-color: ${backgroundColor};
    padding: 100px;
    text-align: center;
    transition: 100ms ease-in background;
    &:hover {
      color: $color;
    }
    @media only screen and (max-width: 480px) {
      font-size: 20px;
    }
  }
`;

export default layOutStyle;
```

**Comment by ai** [comment]
Can you change CSS file to pure CSS (not CSS-in-JS)?

**Comment by SathyanaryanaNaidu** [comment]
@ai  If i use this config in package.json it works fine ,  but i can add mixins here 
```
   "postcss": {
    "plugins": {
      "lost": {},
      "postcss-nested": {},
      "postcss-import" : {
        "path" : "."
      },
      "postcss-simple-vars" : {},
    }
  }
```

mixins to be used : 

```
[
      "postcss-mixins",
      {
        mixins: { ...breakpointMixins, ...placeholderMixins },
      },
    ],
```

**Comment by SathyanaryanaNaidu** [comment]
> Can you change CSS file to pure CSS (not CSS-in-JS)?

The issue is only with the configuration i guess, somewhere i am doing wrong.  CSS in JS will work fine, if use the config in package.json 

any way to add "postcss-mixins" in package.json config

**Comment by ai** [comment]
Can you try to replace: `[plugin, config]` to `plugin: config`?

```js
  "postcss-mixins": {
        mixins: { ...breakpointMixins, ...placeholderMixins }
  }
```

**Comment by SathyanaryanaNaidu** [comment]
> Can you try to replace: `[plugin, config]` to `plugin: config`?
> 
> ```js
>   "postcss-mixins": {
>         mixins: { ...breakpointMixins, ...placeholderMixins }
>   }
> ```

Nice !!!!!!!!  it works
