### ISSUE TITLE
Moderate: Regular Expression Denial of Service

### ISSUE THREAD

**Issue by Darla-Young** [postcss/postcss#1638]
Package: postcss
Patched in: >=7.0.36 <8.0.0 || >=8.2.10
Dependency of: parcel-bundler [dev]
Path: parcel-bundler > htmlnano > purgecss > postcss
More info: https://npmjs.com/advisories/1693

**Comment by ai** [comment]
This issue was fixed in 7.x and 8.x. You need to update dependencies by `npm update` or `yarn update`.
