### ISSUE TITLE
Filtering by Rule selector via Plugin API does not work as expected

### ISSUE THREAD

**Issue by deankeinan** [postcss/postcss#1641]
Hi all! Disclaimer up front that I'm not well acquainted with the project, and barely CSS literate so I may be missing something painfully obvious.

Per the documentation on writing a PostCSS plugin, it's stated that the fastest method of finding/accessing a Node (assuming you know what you are looking for) is like so:

```
    AtRule: {
      media: atRule => {
        // The fastest
      }
   }

```

Is there a reason why the same method is not supported for a Rule entry?

A very basic example: 
```js
const samplePlugin = () => {
    return {
        postcssPlugin: 'sample-plugin',
        Rule: {
            button: rule => {
                // does not work
            },
            "*": rule => {
                // works
            }
        },
        AtRule: {
            charset: atRule => {
                // works
            },
            '*': atRule => {
                 // works
            }
        }
    };
}; 
```
My gut tells me there's something fundamental about CSS I'm ignorant of that explains why this is missing. 

In any case, I just wanted to call some attention to it. It slowed me down for a hot minute trying to sort out what I was doing wrong.

### A Fix?

Toying around locally, I found that by adding another condition to

https://github.com/postcss/postcss/blob/6610edacd4165c3a25959bd7bbeb93ac90457cda/lib/lazy-result.js#L48-L55

like so:
```
  else if (node.type ==='rule') {
    key = node.selector.toLowerCase()
  }
```
gets me the desired result.

**Comment by ai** [comment]
The main reason of hot having fast selector in `Rule` because selector could be combined.

Maybe later, when we have selector parser, we will be able to add fast check for selector’s components.
