### ISSUE TITLE
regex throws Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by AlexisFinn** [postcss/postcss#1646]
Hello.
We recently did a `npm update` on our project to find that suddenly Webpack had stopped working. After investigating the culprit is this commit https://github.com/postcss/postcss/commit/54cbf3c4847eb0fb1501b9d2337465439e849734 in postcss.

It changes the regex and this creates an error with big files.

**Comment by AlexisFinn** [comment]
RangeError: Maximum call stack size exceeded

**Comment by AlexisFinn** [comment]
![2021-10-15-091939_1196x363_scrot](https://user-images.githubusercontent.com/7420883/137709990-8d68ab22-5f1e-4de2-84f1-608b37078a16.png)
here's a screenshot of the stack-trace we got in the actual project.

**Comment by AlexisFinn** [comment]
on Linux

**Comment by yetingli** [comment]
@ai LGTM

**Comment by ai** [comment]
The fix was released in 8.3.10.
