### ISSUE TITLE
White space normalization in v4.0.0

### ISSUE THREAD

**Issue by hail2u** [postcss/postcss#165]
I'm updating dependencies in [CSS MQPacker][1]. However white space normalization in v4.0.0 looks very different to v3.x.x. Sometimes v4.0.0 removes [`after`][2], sometimes removes [`between`][3]. Both expected results updated for passing test with v4.0.0.

I want to know what PostCSS v4.0.0 will and will not do to white spaces when moving nodes.

[1]: https://github.com/hail2u/node-css-mqpacker/tree/postcss-v4
[2]: https://github.com/hail2u/node-css-mqpacker/blob/postcss-v4/test/expected/multiple-queries.css#L8
[3]: https://github.com/hail2u/node-css-mqpacker/blob/postcss-v4/test/expected/other-at-rule.css#L14

**Comment by ai** [comment]
Remove:

1. When you `clone()` node, PostCSS will remove all style properties (`after`, `before`, `between`).
2. When you move node to other CSS root (by `moveTo()`), it will also remove all style properties.
3. When you move node to same CSS root, it will remove only `before` and `after`.

Set new:

1. When you insert node before some node, PostCSS will copy `before` from existed node to new one.
2. When you try to stringify some node and it has no `between`, PostCSS willl try to find node with same type and copy `between` from this other node.
3. When you try to stringify some node and it has no `before` or `after`, [PostCSS will try](https://github.com/postcss/postcss/blob/master/lib/node.js#L321) to find what is indent that you use in your CSS by other nodes, which has `before`. Then PostCSS will calc current node depth and will calc `before`.
4. If PostCSS can’t find other nodes to copy `before`, etc it will use [default style properties](https://github.com/postcss/postcss/blob/master/lib/node.js#L405).

**Comment by hail2u** [comment]
Thanks! I'll try to let PostCSS sets new white spaces.
