### ISSUE TITLE
Do not parse CSS on missed plugins or parser/stringifier option

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1651]
Right now we are showing warning:

> You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.

https://github.com/postcss/postcss/blob/main/lib/processor.js#L19

But many people complain that they can fix it since PostCSS is used wrongly somewhere inside build pipeline.

We can avoid warning if PostCSS will not parse CSS in this case. We can add something like `NoWorkResult`, where `NoWorkResult#css` key will be equal to input. On `NoWorkResult#root` read we still need to parse CSS. And we need to find the best way to deal with `NoWorkResult#map`.

**Comment by bogdan0083** [comment]
@ai I've been working on the issue for some time and have a few questions:

1. What happens with our `Result` if we're not parsing CSS? For example:
```js
let noWorkResult = new NoWork(processor, 'a {}', {})

// this is obvious, we just pass unprocessed css string to result.css
expect(noWorkResult.css).toBe('a {}')

// accessed root, result is parsed
expect(result.root.nodes).toHaveLength(1)

// Let's process our result
let result = await new NoWork(processor, 'a {}', {})

// this is obvious, we just pass unprocessed css string to result.css
expect(result.css).toBe('a {}')

// what about this? Is this correct? I guess not
expect(result.root.nodes).toHaveLength(0)
```

In my `NoWork` implementation I pass empty `Root` to `NoWork#result` if CSS is not parsed, but I guess it might cause confusion for users. Maybe we should parse css not only `NoWork#root` is accessed but also when `Result#root` is accessed? Or just leave it empty?

2. My solution with maps is to actually parse CSS if `NoWork#map` is accessed. The same with `opts.map` - if it's defined then we must parse css. What do you have any thoughts on this? Maybe I miss some edge cases on working with source maps?

Thank you! ❤️

**Comment by ai** [comment]
1. The first 3 examples is a correct behavior. What is `let result = await new NoWork(processor, 'a {}', {})`? We are using `NoWork` only if PostCSS has no plugins. So there is no sense of “processing”.
2. Why do we need to parse CSS to generate source map? We didn’t change anything in CSS. For instance, we can hardcore some simple map describing no changes.

**Comment by bogdan0083** [comment]
> The first 3 examples is a correct behavior. What is let result = await new NoWork(processor, 'a {}', {})? We are using NoWork only if PostCSS has no plugins. So there is no sense of “processing”.

This one is clear now, thanks.

> Why do we need to parse CSS to generate source map? We didn’t change anything in CSS. For instance, we can hardcore some simple map describing no changes.

Are you talking about creating empty map or create an actual source map? If we want to create an actual source map we need still to parse AST because it adds mappings on nodes, so I don't think this is a viable option (still figuring out how source map generator works, sorry 😄).

**Comment by ai** [comment]
> If we want to create an actual source map we need still to parse AST because it adds mappings on nodes

If there are no changes between input and output, you can add only a single map mapping from the whole file to the whole file.

You do not need to create mapping per each CSS part if there are no changes.

**Comment by bogdan0083** [comment]
> > If we want to create an actual source map we need still to parse AST because it adds mappings on nodes
> 
> If there are no changes between input and output, you can add only a single map mapping from the whole file to the whole file.
> 
> You do not need to create mapping per each CSS part if there are no changes.

Got it, thanks.
