### ISSUE TITLE
Processor type is not exported from type definitions

### ISSUE THREAD

**Issue by jfirebaugh** [postcss/postcss#1666]
The return type of the default export of postcss is `Processor`:

https://github.com/postcss/postcss/blob/77c2e73ab3a840caf1743eee08ab08355ce8eb0a/lib/postcss.d.ts#L362-L363

But this type is not exported by the typings, making it inconvenient to define functions which return or receive parameters of this type. I have to declare my own `type PostcssProcessor = ReturnType<typeof postcss>`.

Please add an export of this type to postcss.d.ts. Thanks!

**Comment by ai** [comment]
Sure. Send PR with exporting both `Processor` class in `index.js` and `Processor` class type in `index.d.ts`.

**Comment by ai** [comment]
Fixed 6318030a

Will be released in 8.3.
