### ISSUE TITLE
`parser` option is typed differently to `syntax['parse']`, `root` is always a `Root` but can be a `Document`

### ISSUE THREAD

**Issue by 43081j** [postcss/postcss#1667]
Here we define the `parser` option as being a `Syntax` or a `Parser<Root>` (since `Root` is the default type parameter):

https://github.com/postcss/postcss/blob/6318030a62ceb1667cdd3fb9e49e8e12a910c003/lib/postcss.d.ts#L329

Here we define the `parse` of a `Syntax` as being a `Parser<Root | Document>`:

https://github.com/postcss/postcss/blob/6318030a62ceb1667cdd3fb9e49e8e12a910c003/lib/postcss.d.ts#L249

Maybe these should be aligned?

Similarly, we define the `root` of a `Result` as being a `Root`:

https://github.com/postcss/postcss/blob/6318030a62ceb1667cdd3fb9e49e8e12a910c003/lib/result.d.ts#L97

This isn't true anymore, though. It is possible a custom syntax can emit a `Document` as the root.

**Comment by ai** [comment]
Yeap. You are right. Let’s replace default type parameter for `Parser` and fix other cases.

Please, send PR to save your name in the project history.
