### ISSUE TITLE
Expose `Stringifier` class to make extending the default implementation easier

### ISSUE THREAD

**Issue by 43081j** [postcss/postcss#1673]
I'm writing a syntax for parsing CSS in JS (though tightly scoped to [lit](https://lit.dev)).

Since i'll be mostly stringifying regular CSS, ideally I want to use the default stringifier but override what happens with some things:

```ts
class LitStringifier extends Stringifier {
  comment(node: Comment): void {
    // currently i use comments as placeholders for some original source we stripped
    // so here i would build the original text if its a "special" comment
  }

  root(node: Root): void {
    // handle the codeBefore
    super.root(node);
    // handle the codeAfter
  }
}
```

`Stringifier` currently has no typescript definitions and no `default` export (i.e. your usual `Foo.default = Foo` workaround).

could we expose this? im happy to add the types and the default export if there's no reason not to.

this way i can new up my custom stringifier just like your internal stringifier function does, and rely on the default implementation for the rest.

**Comment by ai** [comment]
Yeap, please send PR. We can try to release it in next 8.4.
