### ISSUE TITLE
CSS Sprites plugin

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#168]
Compass:

```scss
@import "my-icons/*.png";
@include all-my-icons-sprites;
```

**Comment by MoOx** [comment]
I not sure why you are recreating lot of sass stuff with postcss. It's a weird approch.
Even if postcss can parse not really valid CSS, it should not be used for that (IMO).

Importing non css resource is invalid.

CSS Sprites are hack that looks outdated (to me) + hard to maintain (especially with hdpi & non hdpi screens).

datauri seems a easier approach (and some plugin are already doing that).

**Comment by ai** [comment]
I think too that datauri is better.

But If somebody want to create this plugin, why not?

**Comment by yisibl** [comment]
In China also needs to be compatible with IE6.

**Comment by MoOx** [comment]
Ouch. Mhtml don't work on IE6 ? :/

**Comment by yisibl** [comment]
Sometimes, we will also use iconfont.

**Comment by jedmao** [comment]
@MoOx and @ai here are some valid reasons NOT to use data URIs. See http://www.mobify.com/blog/css-sprites-vs-data-uris-which-is-faster-on-mobile/

**Comment by ai** [comment]
@jedmao @yisibl [postcss-sprites](https://github.com/2createStudio/postcss-sprites) :D

**Comment by ai** [comment]
@jedmao yeap, inline images need more CPU to decode base64, but sprites need more memory, because browser uses RAM for all image even if only small part is showed. So it is RAM/CPU trade-off and there is no matter for perfomance.

**Comment by yisibl** [comment]
@ai :+1:
