### ISSUE TITLE
Can a `Rule` have dynamic raws?

### ISSUE THREAD

**Issue by 43081j** [postcss/postcss#1691]
A rule is defined with:

```ts
  raws?: RuleRaws;
```

which is defined here:

https://github.com/postcss/postcss/blob/81292d1bb7e353edf9508e81f5b7ee8420591633/lib/rule.d.ts#L3-L37

this doesn't extend `Record<string, any>` like `Root` raws do. the same applies to things like comments.

should non-root types have extensible raws? or is there a reason we shouldn't be populating them?

my use case is im trying to fix up indentation in `Rule#selector` when stringifying, so i'd like to store the original selector (incl. original indentation) in the raws.

in my case, i noticed i could set `raws.selector` to `{raw, value}` but wasn't sure if that'd conflict with postcss' own internal state

**Comment by ai** [comment]
Yeap, all `Node#raws` can be extendable and keep any other values.

Can you send PR to fix it in `Rule` too?
