### ISSUE TITLE
"./": "./" package.json any update on this issue

### ISSUE THREAD

**Issue by akshayF12** [postcss/postcss#1698]
"exports": {
    ".": {
      "require": "./lib/postcss.js",
      "import": "./lib/postcss.mjs",
      "types": "./lib/postcss.d.ts"
    },
    "./": "./"
  },

**Comment by ai** [comment]
`"./": "./"` doesn’t work in modern Node.js.

Check issues, you will find reports.

**Comment by ai** [comment]
For instance https://github.com/postcss/postcss/issues/1519
