### ISSUE TITLE
dynamic classes with tailwindcss and eleventy

### ISSUE THREAD

**Issue by opheliagame** [postcss/postcss#1699]
I am using eleventy.js with tailwindcss and postcss. In my setup, postcss does not seem to recognise dynamic classes like
`md:pl-{{(loop.length-loop.index+1)*2}}`

And so I never get them in the final css file. Is there any way around this?

command: `postcss src/assets/css/tailwind.css > tmp/assets/css/style.css`

**Comment by ai** [comment]
PostCSS is a framework for CSS transformations. By default, it does nothing.

By default, PostCSS ha no support for `md:pl-{{(loop.length-loop.index+1)*2}}`.

I didn’t find this feature in Tailwind CSS too https://tailwindcss.com/docs/using-with-preprocessors

Maybe you need a special PostCSS plugin to do it?

Can you show your config and the full example of CSS?

Where does `loop` came from in CSS?

**Comment by opheliagame** [comment]
thanks @ai for responding :) i have very limited knowledge of postcss and so i will look into the plugins and see if i can find something. 

my postcss config looks like so 
```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}
```
I am using postcss for tailwindcss along with eleventyjs, and so the `loop` comes from a `nunjuncks` for loop 
```html
<a href="{{ title | url }}">
  {% set title = title.split('') %}
    <div class="text-lg md:text-xl uppercase flex flex-row justify-between md:justify-end">
      {% for letter in title %}
        <p class="md:pl-{{(loop.length-loop.index+1)*2}}">
          <span> {{ letter }} </span>
        </p>
      {% endfor %}
    </div>
  </a>
```

**Comment by ai** [comment]
If you use `loop` in HTML template, you need to debug HTML template system.

PostCSS works only for CSS and is not related with this problem.

What is current HTML output goes to the browsers?

**Comment by opheliagame** [comment]
the class does show up in the final html, and so i figured that tailwind is not able to understand that this class is present and so it is not able to include it in the final css file build. since i am processing tailwind using postcss i wondered if it could be related

**Comment by ai** [comment]
If there is no class in HTML, it means that both Tailwaind and PostCSS is not related.

Try to find some chat or discord server for Eleventy. The problem should be in HTML template.

**Comment by opheliagame** [comment]
the class does show up in html tho
```html
<div class="text-lg md:text-xl uppercase flex flex-row justify-between md:justify-end">
      <p class="md:pl-10"><span>p</span></p>
      <p class="md:pl-8"><span>o</span></p>
      <p class="md:pl-6"><span>e</span></p>
      <p class="md:pl-4"><span>m</span></p>
      <p class="md:pl-2"><span>s</span></p>
</div>
```

**Comment by ai** [comment]
In this case try to check these classes in CSS file and then look for Tailwaind docs to a way to generate them (maybe you need to pass some option to Tailwaind plugin).
