### ISSUE TITLE
Test vulnerability in dependency [nanoid]

### ISSUE THREAD

**Issue by PZiaugra** [postcss/postcss#1702]
Hi,
We have in our CI stack a tool that is responsible for scanning dependencies and identifying vulnerabilities and we got the following result:

```
Issues with no direct upgrade or patch:
  ✗ Information Exposure [Medium Severity][https://snyk.io/vuln/SNYK-JS-NANOID-2332193] in nanoid@3.1.30
    introduced by postcss@8.4.5 > nanoid@3.1.30 and 2 other path(s)
  This issue was fixed in versions: 3.1.31
```

I would like to know if we will have a new version of postcss that already contains the nanoid update with this fix.

Thank you very much for your attention.

**Comment by ai** [comment]
https://github.com/postcss/postcss/blob/main/package.json#L72

PostCSS uses `"^3.1.30"` version requirement for `nanoid`. `^` fits for 3.1.31 and for 3.2.

We do not need new version. Just update nested dependencies by `npm update`.
