### ISSUE TITLE
PostCSS comment removal doesn't preserve syntax

### ISSUE THREAD

**Issue by nex3** [postcss/postcss#1703]
The following code:

```js
console.log(postcss.parse("a {b: c/**/d}").nodes[0].nodes[0].value);
```

prints `cd`. This is substantially different than the original value: where the original value is tokenized as a sequence of two identifiers, `c` and `d`, the new value is tokenized as a single identifier `cd`. PostCSS should instead convert this comment into a space, or not remove it at all.

**Comment by ai** [comment]
We can’t disable comment removing before next major release (which will not be soon).

What side effects will we have on replacing any `[^\s,]COMMENT[^\s,]` to space?

What other symbols before/after comment we should look to avoid adding a space?

**Comment by nex3** [comment]
It's probably a good idea to *always* replace a comment with a space if it's not already surrounded by whitespace. In addition to affecting tokenization, there are a number of places in various CSS specs where CSS requires or forbids tokens to be adjacent, and it'll be hard to enumerate all of them and keep that enumeration up-to-date as new CSS specs release. And without knowing all of those cases, it'll always be possible that this transformation changes the semantics of the CSS.

**Comment by ai** [comment]
I will put it on hold a day or two to think about and collect opinions.

Don’t worry, we will add some fix.

**Comment by ai** [comment]
@nex3 right now for selectors we have [a different way](https://github.com/postcss/postcss/blob/main/lib/parser.js#L414-L423) to solve this problem: we do not remove comments if they change meaning of selector (`a/**/b`).

What do you think if we will use the same logic for declaration and at-rule params instead of replacing comment to space?

**Comment by ai** [comment]
Here is a first attempt to solve the problem: 

https://github.com/postcss/postcss/commit/dc4187de575f476398fe9b5b5ede6ccc0e4c4f27
https://github.com/postcss/postcss-parser-tests/commit/657dce203667e6be1effcbfa776b5efc709660af

**Comment by nex3** [comment]
> What do you think if we will use the same logic for declaration and at-rule params instead of replacing comment to space?

That would also work, since the value parser can then parse the comments.

**Comment by ai** [comment]
Release 8.4.6.
