### ISSUE TITLE
random strings in the postcss file causing styles to break after

### ISSUE THREAD

**Issue by ohabash** [postcss/postcss#1707]
**Tailwind**
"@tailwindcss/aspect-ratio": "^0.4.0",
"@tailwindcss/forms": "^0.4.0",
"@tailwindcss/line-clamp": "^0.3.1",
"@tailwindcss/typography": "^0.5.1",

**PostCss**
"postcss": "^7.4.5",
"postcss-import": "^14.0.2",
"postcss-preset-env": "^6.7.0",
"postcss-url": "^10.1.1",

**Node**
v14.16.0

### The Issue
When build happens; all the scss is minified with **postcss**. In the minified file the style are all working until you get to `@import 'tailwindcss/utilities';` then all styles are broken (not readable in any browser). 

When i prettified the postcss styles i could see some extra code that is causing the problem.
![Screen Shot 2022-01-28 at 1 08 50 PM](https://user-images.githubusercontent.com/15847500/151606818-6c1f1152-d665-49a5-8007-6963db50c2ce.png)

_this is not css so why is it in the postcss file?_
```
.\[k\:string\] {
	k: string
}

.\[https\:\/\/en\.wikipedia\.org\/wiki\/Uname\#Examples\] {
	https:
```

Does anyone know where this is coming from? It looks like a TS interface or json of some sort

**Comment by ai** [comment]
PostCSS is just a parser. All transformation are made by plugins. This is why I am closing this issue, since I can’t fix it in PostCSS core.

I never saw something like this. Honestly, hard to say where it came from. But I recommend starting from Tailwind config.

**Comment by ohabash** [comment]
It was a tailwind thing. Thanks 

https://github.com/tailwindlabs/tailwindcss/issues/7251#issuecomment-1024706872
