### ISSUE TITLE
Sourcemap not available when rule contains only @apply

### ISSUE THREAD

**Issue by Xeevis** [postcss/postcss#1709]
When working with TailwindCSS JIT, rules containing only `@apply` are left out of sourcemaps. Adding any regular css rule or even a simple comment will generate sourcemaps correctly.

```html
<div class="with-sourcemap"></div>
<div class="with-another-sourcemap"></div>
<div class="no-sourcemap-here"></div>
```

```pcss
.with-sourcemap {
  background-color: red;
  @apply h-4 w-4 bg-green-500;
}

.with-another-sourcemap {
  /* sourcemap will work here too */
  @apply h-4 w-4 bg-red-500;
}

.no-sourcemap-here {
  @apply h-4 w-4 bg-black;
}
```

![image](https://user-images.githubusercontent.com/5835044/151717106-64a76fe6-8f28-4052-95e3-2ade4f71c1d4.png)
![image](https://user-images.githubusercontent.com/5835044/151717114-b88e7e6d-0597-4624-9758-0ec267fc7752.png)
![image](https://user-images.githubusercontent.com/5835044/151717126-b132a0be-c401-43df-9543-24995b6efb9f.png)

Related https://github.com/tailwindlabs/tailwindcss/issues/5043

**Comment by ai** [comment]
Very likely that it is an [`postcss-apply`](https://github.com/pascalduez/postcss-apply) issue.

But can you make a smallest example and pass it to [source map visualizer](https://sokra.github.io/source-map-visualization/)? I will try to look.

**Comment by Xeevis** [comment]
Hi, I don't think that particular plugin is used anywhere, it's probably anywhere between postcss, postcss-import and tailwindcss. It won't let me visualize, throws `Source '<no source>' missing`. I've created minimal repo instead https://github.com/Xeevis/postcss-issue-1709, thanks for looking into this.

**Comment by ai** [comment]
Sorry, I can help in environment investigation.

Please come if you will know what you need to change in sources.

For now, try to ask Tailwind team (you need to find a plugin who apply `@apply` changes). PostCSS have a rich API for source map. Very likely that somebody is using it wrong or forget something.
