### ISSUE TITLE
insertBefore/insertAfter should be copyBefore/copyAfter

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#171]
According to the behavior of insertBefore & After, this methods should get another name that reflect the internal behavior.
Currently this methods get some nodes, clone them & insert the clones. This looks like a copy to me.
For example in the DOM, this method, detach nodes from their parent & reattach to the new parent.
So maybe we should offer the 2 methods: insert & copy.
What do you think about that ?

Related to https://github.com/postcss/postcss-import/issues/16#issuecomment-71166687

**Comment by ai** [comment]
Hm. But if you already `clone` ode or create new one, this method will not clone node again.

**Comment by MoOx** [comment]
I get your point, but according to what postcss does during the cloning process (cleaning all whitespace stuff), I am avoiding using cloning for postcss-import, to keep code as close the the original one.
So without considering the real need here, the issue is simple enough in our brain to fix it the right way: insert should 1) remove from current parent 2) insert as in the requested place.
Current behavior is more a copy (that affect some properties) than an simple insert.

**Comment by ai** [comment]
`moveBefore` and `moveAfter` do not clone nodes. It is better for your case.

**Comment by MoOx** [comment]
Nope. [move use insert](https://github.com/postcss/postcss/blob/1bcbfb9e202582af5305405c8bcbc0ba64cec51c/lib/node.js#L163-L166), insert use normalize, normalize use clone.

**Comment by ai** [comment]
Normalize uses clone, becuase I insert some node with other parent is like a mistake. May users make it, so I add a check.

What is semantic sense to insert node into two parents?

**Comment by MoOx** [comment]
Insert should detach from current parent + insert, and it should be able to do so, since every node as a parent property. Right?

**Comment by ai** [comment]
Not every. You can call `node.clone()` or built node manually by `insertBefore({ prop: 'color', value: 'black' })`.

**Comment by MoOx** [comment]
Obviously, an item with no parent will not need to be detached.

**Comment by ai** [comment]
Hm. Yeap, I agree that we can merge `moveBefore` and `insertBefore`. User must `clone` node obviously. But it will not be soon, because many plugins doesn't even migrate to 4.0.

**Comment by ai** [comment]
Lets plan it after docs and async plugins. Maybe we will need to broke API for PostCSS version verification.

**Comment by MoOx** [comment]
yep.
We can provide insertBefore & create copyBefore that does what insert does right now.

**Comment by MoOx** [comment]
It seems it's also affecting \n between rules & ; when there is one node.
It's annoying when you do some test for plugins :(

**Comment by ai** [comment]
I open a more clear issue to have cleaner TODO https://github.com/postcss/postcss/issues/187
