### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mzabuawala** [postcss/postcss#1711]
`
───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Exposure of Sensitive Information to an Unauthorized Actor   │
│               │ in nanoid                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ nanoid                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.1.31                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ postcss                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ postcss > nanoid                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1006897                     │
└───────────────┴──────────────────────────────────────────────────────────────┘

`

**Comment by ai** [comment]
Update nested dependencies. You need something like `npm update` depending on your package manager and environment.
