### ISSUE TITLE
Order of plugins not enforced

### ISSUE THREAD

**Issue by snakemastr** [postcss/postcss#1720]
I'm not sure if this is the correct place to ask but I have created a custom PostCSS plugin to generate a set of declarations with some parameters. I use the AtRule method to walk over atRules, which should be faster according to Docs, than traversing the root in Once().

This is part of my code (some parts omitted for readability):
```
# buttons.css
.button {
  @generate [primary, --c-pri], [secondary, --c-sec], [accent, --c-acc]  {
    &--primary {
      @apply bg-primary border-primary text-primary-content;
      &:focus-visible {
        box-shadow: 0 0 0 2px hsl(var(--c-bas)), 0 0 0 4px hsl(var(--c-pri));
      }
    }
  }
}

#expected output 
    .button--primary {
      @apply bg-primary border-primary text-primary-content;
      &:focus-visible {
        box-shadow: 0 0 0 2px hsl(var(--c-bas)), 0 0 0 4px hsl(var(--c-pri));
      }
    }
    .button--secondary {
      @apply bg-secondary border-secondary text-secondary-content;
      &:focus-visible {
        box-shadow: 0 0 0 2px hsl(var(--c-bas)), 0 0 0 4px hsl(var(--c-sec));
      }
    }
    .button--accent {
      @apply bg-accent border-accent text-accent-content;
      &:focus-visible {
        box-shadow: 0 0 0 2px hsl(var(--c-bas)), 0 0 0 4px hsl(var(--c-acc));
      }
    }
```

```
# postcss/generate.js
return {
    postcssPlugin: 'generate',
    AtRule: {     
      generate: (atRule, {Rule}) => {
        let params = atRule.params;
        // params is analyzed and converted to the expected format

        params.forEach((set, index) => {
          atRule.walkRules((rule) => {
                // very simplified but each rule is duplicated here and values are replaced
                let newRule = duplicateRule(rule, Rule);
                // newly created rule is appended to the parent of the atRule
                atRule.parent.append(newRule);
            })
        })
        atRule.remove();
      }
    },
```
```
# postcss.config.js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('plugins/postcss/generate'), // local plugin
    require('tailwindcss/nesting')
    require('tailwindcss')('./tailwind.config.js'),
  ]
}
```

If I run this through a standalone postcss-cli tool, the generate rules are working as expected and I get button--primary, button--secondary etc. If I run this through a Vite + Vue application, the plugin seems to be called after TailwindCSS(/nesting) and my result has &--primary and &--secondary and I get Tailwind nesting errors. How is the postcss with postcss-loader different from the command-line tool?

Should I move the code to Once() or is there another way to ensure the execution order of plugins is enforced?

The reason for the runtime application is so I can hot reload while developing and only rebuild when I am satisfied with the result as that takes a lot longer.

**Comment by ai** [comment]
The whole concept of new event system (like `AtRule`) is to stop thinking about plugin order. All plugins will work in the same moment.

Unfortunately, we are in the migration period where have old-style plugins (use `Once` to work with AST) and new-style plugins (use proper `AtRule`, etc).

The best way is to ask Tailwind to move to proper AST events, but it could take a while.

I am closing the issue, since it should be in Discussions.

**Comment by ai** [comment]
The dirty solution which you can use right now:

1. In `Once` check `result.processor.plugins` for Tailwind.
2. If Tailwind is in user system, use `Once` otherwise use `AtRule`

**Comment by snakemastr** [comment]
Thank you for replying so fast. 
I think I understand the difference now. At least now I know why I haven't found a decent advanced example that uses the new Event system. 

Also thanks for providing a workaround,, much appreciated!
