### ISSUE TITLE
postcss-black-white plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#173]
Like [postcss-color-gray](https://github.com/postcss/postcss-color-gray), but also makes `white(alpha)` and `black(alpha)` aliases.

**Comment by shinnn** [comment]
I'm really opposed to overwrite `white()` and `black()`. These function names are already reserved. 

http://dev.w3.org/csswg/css-color/#hsl-hwb-adjusters

>  w(), white(), b(), or black()

Doesn't [postcss-color-gray](https://github.com/postcss/postcss-color-gray) meet your requirements?

**Comment by ai** [comment]
Nope, what is a point of `gray` if we need always `gray(255, a)` or `gray(0, a)`? ;)

Does I understand correct, that `w(), white(), b(), or black()` can be only inside `color(` function? I can check where I found `white()` and `black()`.

**Comment by shinnn** [comment]
IMO it confuses the users though we can check the positions of `white()` and `black()`...

But if you think it's worth creating the plugin, go ahead.

**Comment by ai** [comment]
I can create plugin not in organization, because it is opinionable. But thanks for name conflict. I didn’t know about `black()` and `white()` commands in `color()` function.

**Comment by MoOx** [comment]
You can also use
- postcss-color-function: color(#000 a(50%))
- postcss-hex-alpha: `#0008` or `#fff8`, black or white with alpha to 50%. Less chars.

Btw: http://ianstormtaylor.com/design-tip-never-use-black/ and I think the same applies to white (not recommanded to use #fff). That said, alpha should affect that.

**Comment by ai** [comment]
Hm, maybe `#hexa` is nice solution.

But it is difficult to write alpha in hex. I think @yisibl mentioned some spec or idea to combine hex color and decimal alpha like `#000.5`.

**Comment by yisibl** [comment]
Yes, I will develop this plugin.

**Comment by MoOx** [comment]
Any link to the spec ?

**Comment by yisibl** [comment]
There is no standard, but we can send e-mail to `www-style`

**Comment by MoOx** [comment]
I don't think they will will make a spec with mixed base 16 and base 10 number. This is so confusing.

**Comment by yisibl** [comment]
Never mind, not all plugins demand is to think logically. Designers need to write.

**Comment by ai** [comment]
@yisibl can you remind me a syntax of your idea?

**Comment by MoOx** [comment]
...
We should totally not encourage  non standard stuff for designers. They already have difficulties by working in modern complex web apps & workflows.

**Comment by ai** [comment]
@MoOx we should use power modularity. I really  think that is very important to have different ideas. There is no development without real world competition.

We can think some theory, while develop a specs, but real world will be different. PostCSS gives us power to test some ideas before implement it in browsers.

If many people will prefer decimal alpha (designers really didn’t know hex), we can show it to W3C and they will add some decimal syntax to specs. Because specs are for developers, not a developers for specs :).

**Comment by yisibl** [comment]
Sorry, my English is bad, @ai has already said my idea.

**Comment by yisibl** [comment]
In fact, we will learn the colors in the Photoshop, and then paste it into the CSS file. `#rgb.alpha` can facilitate the rapid adjustment.

**Comment by ai** [comment]
@yisibl 百花齐放，百家争鸣 :-D

**Comment by yisibl** [comment]
@ai :heart: Too great!

**Comment by avanes** [comment]
Hello from brainwashing ;)
https://github.com/avanes/postcss-color-alpha

**Comment by ai** [comment]
@avanes awesome!
