### ISSUE TITLE
Using @use with aliases

### ISSUE THREAD

**Issue by bryanjtc** [postcss/postcss#1733]
Is there any plugin to resolve @use with aliases on rollup?

**Comment by ai** [comment]
Sorry, I have no idea about the context.

Can you show some examples?

**Comment by ai** [comment]
Another question: why do you need Rollup for library?

**Comment by bryanjtc** [comment]
My team and I are building a component library and we choose rollup instead of webpack to bundle it.

**Comment by bryanjtc** [comment]
Here is an example:
In a scss module file I have this
```scss
@use '@typography' as *;
@use '@spacing' as *;
@use '@colors' as *;
```
In my rollup config I use this plugin to define the aliases
```js
alias({
        entries: [
          { find: '@atoms', replacement: path.resolve(__dirname, './src/components/atoms') },
          { find: '@molecules', replacement: path.resolve(__dirname, './src/components/molecules') },
          { find: '@organisms', replacement: path.resolve(__dirname, './src/components/organisms') },
          { find: '@colors', replacement: path.resolve(__dirname, './src/colors.module.scss') },
          { find: '@spacing', replacement: path.resolve(__dirname, './src/spacing.module.scss') },
          { find: '@typography', replacement: path.resolve(__dirname, './src/typography.module.scss') },
        ],
      }),
```

**Comment by ai** [comment]
You need to use PostCSS only after Sass compile step.

Seems like you need a help with configuring your environment, and it is not an issue. I can’t help with environment, this is why I am closing this issue.
