### ISSUE TITLE
Improving the type definitions

### ISSUE THREAD

**Issue by binyamin** [postcss/postcss#1734]
### Summary
I have some suggestions for this project's type definitions. I'm willing to open a PR, assuming these changes are okay.

### Details
1. There's a typo in [`lib/processor.d.ts`](https://github.com/postcss/postcss/blob/main/lib/processor.d.ts#L75). "Processes" should be "Processor".
    ```diff
     /**
      * ...
    - * @return {Processes} Current processor to make methods chain.
    + * @return {Processor} Current processor to make methods chain.
      */
     use(plugin: AcceptedPlugin): this
    ```
2. I don't see a point in adding a return type (`@return {Processor}`) in the JSDoc comments. The method already has a return type, because this is typescript.
3. Unrelated, but should the examples in the comments use an `@example` directive? It's made for that purpose.

**Comment by ai** [comment]
> I don't see a point in adding a return type (@return {Processor}) in the JSDoc comments

Yes, it was a mistake. It seems like an artifact from refactoring.

Fixed 34f6fee3

**Comment by ai** [comment]
> Unrelated, but should the examples in the comments use an @example directive?

I didn’t find any UX benefits in IDE.

Do you know any reasons to use `@example`?

**Comment by binyamin** [comment]
Um, not really. I suppose it might be for documentation generators. Thank you.
