### ISSUE TITLE
Traversing though `.parent` and then mutating `.nodes` causes `append` to fail

### ISSUE THREAD

**Issue by thecrypticace** [postcss/postcss#1738]
If you use postcss-nested to un-nest CSS, later traverse the tree, and mutate the parent's children it can cause calls to `append` to fail for any _original_ reference to the parent. If you go through `parent` to append children the call works fine.Additionally, if you mutate the children with the original reference the call to append will succeed.

I looked into this some and it appears that `append` calls `normalize` on the nodes passed to the children. This results in calls to `parent.removeChild(…)` which tries to find the node, fails silently, and uses the `-1` index to remove the child. This the removal of the parent from the node to throw an error because `this.proxyOf.nodes[child]` is undefined.

I'm guessing this is because the proxies postcss is using aren't being cleaned up properly when the parent's children are reassigned (at least I think that's what's happening) but I'm not sure. I wanted to PR the fix for this but I'm not entirely sure where to start on this one. Any help would be super appreciated, thanks!

Here's a short reproduction using `postcss-nested`:

```js
let root = postcss.parse(`
  @media (min-width: 640px) {
    .page {
      width: auto;
    }
  }
  .page {
    @media (min-width: 640px) {
      width: auto;
    }
  }
`)

let result = await postcss([
  postcssNested,
  
  // This is meant to emulate collapsing the declarations into one
  {
    postcssPlugin: 'some-plugin',
    OnceExit(root) {
      let firstRule = root.nodes[0]
      let secondRule = root.nodes[1]

      let node = firstRule.nodes[0].parent
      node.nodes = node.nodes
      firstRule.append(secondRule.nodes)
      secondRule.remove()
    },
  },
]).process(root, { from: 'whatever' })
```

And here's a reproduction using just postcss with more explanation and other scenarios that appear to work fine. Note that one of the classes was changed to simplify the `Rule` visitor:

```js
let root = postcss.parse(`
  @media (min-width: 640px) {
    .page {
      width: auto;
    }
  }
  .nested {
    @media (min-width: 640px) {
      width: auto;
    }
  }
`)

let result = await postcss([
  {
    postcssPlugin: 'some-plugin',
    
    // Make some changes to the tree
    // This appears to be required
    // This emulates having used postcss-nested to mutate the tree
    Rule (rule) {
      // This is obviously not the same as the postcss-nested version
      // but this simpler visitor still reproduces the bug
      if (rule.selector === '.nested' && rule.nodes.length === 1) {
        rule.after(rule.nodes[0])
      }
    },

    // This is meant to emulate collapsing the declarations into one
    OnceExit(root) {
      let firstRule = root.nodes[0]
      let secondRule = root.nodes[1]
      let node

      // If we:
      // 1. Traverse the tree
      // 2. Traverse back up the parent
      // 3. Mutate that parent's children (even by setting it to itself)
      // 4. Later append nodes to the parent using an original reference (not from traversal)
      // 5. The call to append will throw an error

      // This fails:
      node = firstRule.nodes[0].parent
      node.nodes = node.nodes
      firstRule.append(secondRule.nodes)

      // This works #1:
      // node = firstRule.nodes[0].parent
      // node.nodes = node.nodes
      // firstRule.nodes[0].parent.append(secondRule.nodes)

      // This works #2:
      // node = firstRule.nodes[0].parent
      // node.nodes = node.nodes
      // firstRule.append(secondRule.nodes)

      // This works #3:
      // node = firstRule
      // node.nodes = node.nodes
      // firstRule.append(secondRule.nodes)
      
      secondRule.remove()
    },
  },
]).process(root, { from: 'whatever' })
```

**Comment by ai** [comment]
Thanks for reproduction case.

I will investigate it on weekend or later.

Sorry, I am preparing the talk to meetup and can’t investigate early. But if you will send PR I will try to release it earlier.

**Comment by thecrypticace** [comment]
I tracked this down to `.parent` being set to a proxy during normalization rather than the node itself. This eventually causes a lookup to fail because node.nodes[…] ends up containing proxies as a result of this. I'll be opening a PR soon-ish.
