### ISSUE TITLE
Postcss-each with Tailwind and Next.js

### ISSUE THREAD

**Issue by eliza3291** [postcss/postcss#1742]
### Describe the Bug

I have a Next.js app, with Tailwindcss, Postcss and postcss-each plugin. While trying to upgrade the packages because of some vulnerabilities I found out that the configuration I had before in my `postcss.config.js` start failing because the plugins order changed in Postcss 8.

Old configuration:
```javascript
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}'],
  plugins: {
    'postcss-each': {},
     tailwindcss: {},
    'postcss-preset-env': {},
    autoprefixer: {},
  },
}
```

and I found this [solution](https://github.com/tailwindlabs/tailwindcss/discussions/7362#discussioncomment-2132610) so I need to use the [beforeEach](https://github.com/madyankin/postcss-each#beforeeach) configuration available in `postcss-each´ plugin in order to call Tailwindcss plugin before each iteration.

[Next.js documentation](https://nextjs.org/docs/advanced-features/customizing-postcss-config) explicitly says:

> Do not use require() to import the PostCSS Plugins. Plugins must be provided as strings.

But when I try to import Tailwindcss in the postcss.config.js as a string without require() like this:

```javascript
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}'],
  plugins: {
    'postcss-each': {
      plugins: {
        beforeEach: ['tailwindcss']
      }
    },
    'postcss-preset-env': {},
    autoprefixer: {},
  },
}
```

and trying to run the app then I got `Error: tailwindcss is not a PostCSS plugin`

### Expected Behavior

Tailwindcss plugin is found when called inside beforeEach without `require()` as defined in the Next.js documentation.

### To Reproduce

[Github Repository](https://github.com/eliza3291/nextjs-postcss-tailwind)

In the [Getting Started](https://github.com/eliza3291/nextjs-postcss-tailwind#getting-started) section of the readme file you can find the steps to reproduce the issue.

**Comment by ai** [comment]
Sorry, you need to ask `postcss-each` author.

The only thing I can help is to suggest replacing `beforeEach: ['tailwindcss']` to `beforeEach: [require('tailwindcss')]`
