### ISSUE TITLE
Bundling/concatenation of css files is not allowed?

### ISSUE THREAD

**Issue by skitsanos** [postcss/postcss#1743]
`postcss src/styles/*.css -o dist/lib.css` still firing the error `Input Error: Must use --dir or --replace with multiple input files`

PostCSS does not allow bundling into a single file? 

Unfortunately couldn't find anything about it in the documentation...

**Comment by ai** [comment]
Seems like.

I am not sure, since this is a limit of `postcss-cli` (who has another developer) https://github.com/postcss/postcss-cli

This is repo for the core parser
