### ISSUE TITLE
Favorite plugins list contains unmaintained packages

### ISSUE THREAD

**Issue by fabercancio** [postcss/postcss#1748]
The [favorite plugins list](https://github.com/postcss/postcss#plugins) contain two packages that are unmaintained and the projects have been archived on Github by the owners:

* postcss-assets: https://github.com/borodean/postcss-assets
* postcss-rtl: https://github.com/vkalinichev/postcss-rtl

### Alternatives

These alternatives are contained already [on the plugin list](https://github.com/postcss/postcss/blob/main/docs/plugins.md).

An alternative for `postcss-assets` is [postcss-url](https://www.npmjs.com/package/postcss-url), it is not exactly the same functionality, but multiple features of `postcss-assets` can be achieved with it.

An alternative for `postcss-rtl` is [postcss-rtlcss](https://github.com/elchininet/postcss-rtlcss). It has the same features as `postcss-rtl` and more and it solves most of the bugs present on the first.

**Comment by ai** [comment]
Yes, let’s replace them. Do you want to send PR to save your name in the project’s history?

**Comment by fabercancio** [comment]
Thanks. Let me prepare it :)

**Comment by fabercancio** [comment]
Ready: https://github.com/postcss/postcss/pull/1749
