### ISSUE TITLE
postcss-default-unit plugin

### ISSUE THREAD

**Issue by ai** [postcss/postcss#175]
Fork [rework-default-unit](https://github.com/fgnass/rework-default-unit) plugin and make it better (add `@media` support).

**Comment by MoOx** [comment]
😱

**Comment by ai** [comment]
Yeap, it is part of non-specs plugins :D.

But really, we need to write too many letters for `px`.

**Comment by yisibl** [comment]
I think this plugin has little significance, but also easy to cause confusion, destroyed the original semantic.

**Comment by ai** [comment]
What if we willhave whitelist of properties?

**Comment by lydell** [comment]
> But really, we can save 2 letters is most of properties.

Sounds completely useless to me.

**Comment by ai** [comment]
Done https://github.com/antyakushev/postcss-default-unit
