### ISSUE TITLE
I am having a warning on gatsby develop : [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'mini-css-extract-plugin

### ISSUE THREAD

**Issue by unilimpio** [postcss/postcss#1751]
Hi and good day to all of you, 
I am having an issue on a totally working gatsby v4+tailwindcss website, currently continuously deploying with no problems on  netlify .  I was trying to do a routine npm outdate - npm update  when this strange warning started to appear, it does not break the develop process, and the webpage loads but seems to loadsignificantly slower on all pages and sharp image jobs.
:

<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'mini-css-extract-plugin C:\Users\mfilb\uniweb4-update-bug-fix\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!C:\Users\mfilb\uniweb4-update-bug-fix\node_modules\gatsby-plugin-postcss\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!C:\Users\mfilb\uniweb4-update-bug-fix\src\styles\global.css|0|Compilation/modules|C:\Users\mfilb\uniweb4-update-bug-fix\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[9].oneOf[1].use[1]!C:\Users\mfilb\uniweb4-update-bug-fix\node_modules\gatsby-plugin-postcss\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[9].oneOf[1].use[2]!C:\Users\mfilb\uniweb4-update-bug-fix\src\styles\global.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 3 items } -> webpack/lib/ModuleWarning -> Warning

i'm kind of new to node.js and react world, so i am not sure what config you mean. I am currently developping a website using gatsby v4 +tailwindcss + a bit of styled components for the navbar, this is my setup:

  npmPackages:
    gatsby: ^4.14.1 => 4.14.1
    gatsby-plugin-breadcrumb: ^12.3.1 => 12.3.1
    gatsby-plugin-image: ^2.14.1 => 2.14.1
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-netlify: ^4.4.0 => 4.4.0
    gatsby-plugin-postcss: ^5.14.0 => 5.14.0
    gatsby-plugin-purgecss: ^6.1.2 => 6.1.2
    gatsby-plugin-react-helmet: ^5.14.0 => 5.14.0
    gatsby-plugin-sharp: ^4.14.1 => 4.14.1
    gatsby-plugin-sitemap: ^5.14.0 => 5.14.0
    gatsby-plugin-styled-components: ^5.14.0 => 5.14.0
    gatsby-source-filesystem: ^4.14.0 => 4.14.0
    gatsby-transformer-remark: ^5.14.0 => 5.14.0
    gatsby-transformer-sharp: ^4.14.0 => 4.14.0
  npmGlobalPackages:
    gatsby-cli: 4.14.0

and this is my gatsby-config bit for the concerned part:

    `gatsby-plugin-postcss`,
    {
      resolve: `gatsby-plugin-purgecss`,
      options: {
        printRejected: true, // Print removed selectors and processed file names
        // develop: true, // Enable while using `gatsby develop`
        tailwind: true, // Enable tailwindcss support
        // ignore: ['/ignored.css', 'prismjs/', 'docsearch.js/'], // Ignore files/folders
        // purgeOnly : ['components/', '/main.css', 'bootstrap/'], // Purge only these files/folders
        purgeCSSOptions: {
          // https://purgecss.com/configuration.html#options
          safelist: [
            'breadcrumb',
            'breadcrumb__list',
            'breadcrumb__list__item',
            'breadcrumb__link',
            'breadcrumb__separator',
            'ol',
          ], // Don't remove this selector
        },
       }
     },

I have done some research and my own testing and the problem seems to arrise when i updated autoprefixer from 10.4.4to 10.4.7, and i because of CD i will not push this tho repository and merge on main until i get this warning sorted out. 
 any ideas on why this warning is displaying during develop?
Thank you for any tips or insight
MFC

**Comment by ai** [comment]
Sorry, this warning is not from PostCSS and I need to send you to webpack community for advice
