### ISSUE TITLE
PostCSS legacy code

### ISSUE THREAD

**Issue by vikaskaliramna** [postcss/postcss#1752]
Why PostCSS is full of legacy code, I was exploring it's source code and found many work arounds.

What is reason for that and will it be improved in future?

**Comment by ai** [comment]
Can you show a few examples?

**Comment by ai** [comment]
> A good example is Container module, where AtRule, Rule and parse are not imported but just declared as variable.

This is for a reason. CommonJS do not allow circular dependencies. So we define variables and fulfill them later.

> List module is also a good example, the source code is messy

But we can think about removing them in next major release (which will not be soon, since PostCSS 8 migration was no ended).

>  type string was assigned to type boolean.

Where? Let’s fix it.

> And the postcss.js module is also filled with many issues.

Can you show examples?

**Comment by vikaskaliramna** [comment]
> This is for a reason. CommonJS do not allow circular dependencies. So we define variables and fulfill them later.

Really? I haven't used cjs much so I don't know about that.

> type string was assigned to type boolean.

This problem is with a variable
https://github.com/postcss/postcss/blob/e0c4e8fcfe02c958d431e870281b95cc24d258a0/lib/list.js#L10


This line would always return false(Error from TypeScript) I am pretty sure it won't cause any problem but why keep bad code.

https://github.com/postcss/postcss/blob/e0c4e8fcfe02c958d431e870281b95cc24d258a0/lib/list.js#L19


And here it is assigned, either you keep it string or boolean. It won't break anything, but we I am sure you don't want `runtime funtime`.
https://github.com/postcss/postcss/blob/e0c4e8fcfe02c958d431e870281b95cc24d258a0/lib/list.js#L23



I think assigning something to a function using this `postcss.` is a work around, I never use it to prevent Js doing some magic behind the scenes.
https://github.com/postcss/postcss/blob/e0c4e8fcfe02c958d431e870281b95cc24d258a0/lib/postcss.js#L29


In my TypeScript version of PostCSS, I removed many of these `.default = `, I don't know what's their use.

https://github.com/postcss/postcss/blob/e0c4e8fcfe02c958d431e870281b95cc24d258a0/lib/list.js#L56

**Comment by ai** [comment]
> let quote = false 

I rewrote this part a little to make it more readable and avoid type changes 80f02d9b

> I think assigning something to a function using this postcss. is a work around, I never use it to prevent Js doing some magic behind the scenes.

We are doing it because of CJS. In CJS you do not have separation between `default` and named exports. Named exports are just keys in default export.

So we need `postcss.parse =` if we want to support APIs like:

```js
// User A
const postcss = require('postcss')

// User B
const { parse } = require('postcss') //=> const parser = require('postcss').parse
```

> In my TypeScript version of PostCSS, I removed many of these .default = , I don't know what's their use.

CommonJS compatibility (technically compatibility with CJS→ESM compatibility layers).

**Comment by vikaskaliramna** [comment]
So all the legacy code is because of Common Js right? Common Js is legacy itself btw.

It means many things can't be changed, right?

**Comment by ai** [comment]
> Common Js is legacy itself btw.

Not yet. ESM migration has many problems. It is still impossible to migrate many projects.

> It means many things can't be changed, right?

Yeap. We can drop CJS support for so popular projects like PostCSS (and with so complex ecosystem) only in a few years.
