### ISSUE TITLE
[vite:css-post] <css input>:45595:21: Unknown word

### ISSUE THREAD

**Issue by r-wells** [postcss/postcss#1753]
Hello all. Currently getting this error when trying to run our build in one of our repos.

```
[vite:css-post] <css input>:45595:21: Unknown word
```

This is a brand new issue, and seems to be subject to a specific PR but I haven't found what would be causing it. The current working theory is we are using the latest version of tailwind, but not the latest version of `postcss`.

Post css version: `8.4.12`
Tailwind version: `^3.0.23`

We also recently introduced `"@tailwindcss/forms": "^0.4.0",` but removing that package doesn't seem to fix it.

Any ideas what's happening here? It's possible this PR introduces a `tailwind` class that wasn't previously in the repo, but so far haven't seen anything we're not already using.

Also, this PR introduced `"joi": "^17.6.0",` to the repo. I can't see how that's the problem, but you never know.

**Comment by r-wells** [comment]
Update - upgrading `postcss` doesn't solve the issue either.

**Comment by ai** [comment]
Sorry, we can’t help with environment issues. Very likely that you stack just sending broken CSS.

If you will find that valid CSS is not parsed by CSS, please open an issue with input CSS.
