### ISSUE TITLE
Make TypeScript type for `postcss.config.js`

### ISSUE THREAD

**Issue by PythonCoderAS** [postcss/postcss#1755]
I want to be able to validate the config I export using TypeScript, but there is no Config type that I can use. Eslint for example has a type I can assign to a config object, but I cannot find one for this project. It would be nice if one could be added.

**Comment by ai** [comment]
`.ts` config should be supported https://github.com/postcss/postcss-load-config/blob/main/src/index.js#L87

Maybe you are using the tool with own PostCSS config loader? You need to open issue there in this case.

**Comment by PythonCoderAS** [comment]
> `.ts` config should be supported https://github.com/postcss/postcss-load-config/blob/main/src/index.js#L87
> 
> Maybe you are using the tool with own PostCSS config loader? You need to open issue there in this case.

No, that's not the issue I meant. What I meant was making an `Interface` for the PostCSS configuration file export. For example:

```ts
export interface PluginInit {
postcssPlugin: string;
options: {[key: string]: any};
...
}

export interface Config {
plugins: (() => PluginInit)[];
...
}
```

**Comment by ai** [comment]
There is this interface https://github.com/postcss/postcss-load-config/blob/main/src/index.d.ts#L52-L60

Does it fit your task?

We can improve docs in `postcss-load-config` with an example for TS (but I would ask you to send PR since English is not my native language).

**Comment by PythonCoderAS** [comment]
This is exactly what I'm looking for, thank you! I just assumed it would be in `postcss` directly.
