### ISSUE TITLE
Plugin Boilerplate

### ISSUE THREAD

**Issue by ai** [postcss/postcss#176]
We need some `postcss-plugin-boilerplate` repo with good start point for plugin developer.

@MoOx @yisibl @lydell what you hate in my style? :D https://github.com/postcss/postcss-size

**Comment by yisibl** [comment]
I like the 2 space indentation, you don't hit me.

We can add

* .editorconfig https://github.com/postcss/postcss-custom-selectors/blob/master/.editorconfig
* .travis.yml
* Other

**Comment by MoOx** [comment]
I think there is enough plugin that might be used as a boilerplate.
You can check postcss-import for example that even have appveyor integration.

**Comment by ai** [comment]
@MoOx I think it is very kindly to have a one enter point for newbies. But I agree that this task is low priority because we really has many good examples of plugins.

**Comment by ai** [comment]
First version is finished https://github.com/postcss/postcss-plugin-boilerplate

Note about `./start` script. It ask author name, email, plugin name, etc and then fill all files ^_^.

Please send me PR for your favorite config files and tools :).

**Comment by ai** [comment]
Maybe I shoould use Yeoman to fill files? But right now `./start` is easy and simplier for developers.

**Comment by MoOx** [comment]
gulp is already too big for such a simpler process, don't use a tank please :D

**Comment by ai** [comment]
You mean is will be better to run `mocha` and `jshint` as CLI tools?

**Comment by ai** [comment]
Yeap, maybe. Can you create a issue in thet repo. I will move it to CLI tools later.
