### ISSUE TITLE
normalize.css:undefined:undefined: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by SturmB** [postcss/postcss#1760]
I've started a new project in PhpStorm using the HTML5 Boilerplate template. Shortly thereafter, I am attempting to install TailwindCSS with PostCSS and Autoprefixer.

The boilerplate comes with Parcel, so I followed TailwindCSS's instructions for installing with Parcel, and the result of running `pnpm run dev`, which is a `package.json` script that runs `parcel index.html --open`, is this unintelligible (to me) mess:

![phpstorm64_tyOz0xz5cc](https://user-images.githubusercontent.com/6216224/178152531-d55f09c8-38c0-47ec-b246-ddbb1f6bf578.png)

I don't have any PostCSS plugins to my knowledge and have not touched the `normalize.css` file at all. What's going on and how can I fix it?

**Comment by ai** [comment]
Sorry, I can’t help with configuring your project.

Very likely that you are using old PostCSS (maybe because of outdated dependencies in boilerplate).

You should create an issue in Boilerplate or just change it.

**Comment by SturmB** [comment]
Thank you, ai, for not even bothering to read the first few words of the very first sentence of my post: "I've started a new project…" and just closing the issue out-of-hand. I mean, I know that PostCSS is a super-busy project and you are likely pressured to close as many tickets as quickly as possible, but come on.

The jist of my first sentence was to convey that _everything is current_ in this project. There is no "old PostCSS." The project was literally created _today_. Here's the `package.json` to help prove it:

```json
{
  "name": "iel-prize-wheel",
  "description": "Simple prize wheel app for IEL",
  "version": "0.0.1",
  "author": "Chris McGee",
  "bugs": {
    "url": "https://github.com/SturmB/iel-prize-wheel/issues"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.7",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "parcel-bundler": "^1.12.5",
    "postcss": "^8.4.14",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.1.5"
  },
  "directories": {
    "doc": "doc"
  },
  "homepage": "https://github.com/SturmB/iel-prize-wheel#readme",
  "keywords": [
    "iel",
    "prize",
    "tier",
    "wheel",
    "winwheel"
  ],
  "license": "ISC",
  "main": "index.html",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SturmB/iel-prize-wheel.git"
  },
  "scripts": {
    "build": "parcel build index.html",
    "dev": "parcel index.html --open",
    "start": "npm run build && npm run dev",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
```

As you can (hopefully) see, all the dependencies' version numbers are 100% up to date as of today.

**Comment by ai** [comment]
You are using Parcel 1, which uses PostCSS 7. But you are using PostCSS 8 in your `package.json`. It starts to have conflict.

The current Parcel is 2.x and has PostCSS 8 support.

The problem was not in PostCSS but in mixing old Boilerplate with new tools like TailwindCSS.

**Comment by SturmB** [comment]
Thank you, ai.
