### ISSUE TITLE
plugin template  boilerplate page not found 

### ISSUE THREAD

**Issue by Mdkawsarislam2002** [postcss/postcss#1761]
#### now, how can I get a boilerplate plugin template?

![image](https://user-images.githubusercontent.com/87494463/178970480-aef14a05-d42b-408a-97a6-1a1e88d2b872.png)

## result: 
![image](https://user-images.githubusercontent.com/87494463/178970628-656e4d56-beab-47f5-8510-8653a6a75555.png)

**Comment by ai** [comment]
Here is a link https://github.com/postcss/postcss-plugin-boilerplate

**Comment by Mdkawsarislam2002** [comment]
Thanks
