### ISSUE TITLE
Parsing error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by PhantomRex123** [postcss/postcss#1764]
```
Parsing error: Cannot find module 'next/babel'
Require stack:
- REMOVED/next/dist/compiled/babel/bundle.js
- REMOVED/next/dist/compiled/babel/eslint-parser.js
- REMOVED/node_modules/eslint-config-next/parser.js
- REMOVED/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
```

I'm using postcss with nextjs.

My postcss configs:

```
module.exports = {
  plugins: [
    'tailwindcss',
    'postcss-preset-env',
  ],
}
```

**Comment by ai** [comment]
Why do you think it is connected with PistCSS?

**Comment by PhantomRex123** [comment]
> Why do you think it is connected with PistCSS?

Oh so it isn't? 

Well sorry then, it seems to be a nextjs issue, sinc eon svelte it works perfectly.

Thanks for having/supporting some awesome opensource projects!

Regards,
Ryan

**Comment by ai** [comment]
Sorry, very likely that it is an issue with Babel config in your project (which cause a conflict with ESLint).

It is out of my area of expertise to help you here.
