### ISSUE TITLE
Strict Parser should throw error or Safe Parser should reject the declaration, if CSS variables are not accompanied by proper unicode character

### ISSUE THREAD

**Issue by phoenisx** [postcss/postcss#1765]
## Issue

Parser successfully returns for CSS custom properties accompanied by improper Unicode character.

## Current Behaviour

```js
await postcss().process(":root { -- : #333; }");

// Returns
{
  ...
   nodes: [
    Declaration {
      raws: [Object],
      type: 'decl',
      parent: [Circular *1],
      source: [Object],
      prop: '--', // This should be ignored
      value: '#333',
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    }
  ],
  ...
}
```

## Expected Behaviour

The parser for the above content should throw an error (or ignore it if used with safe-parser).

### References:

<div align="center">
<a href="https://drafts.csswg.org/css-syntax/#ident-token-diagram" target="_blank">
<img width="66%" alt="image" src="https://user-images.githubusercontent.com/11786283/183624927-8be38d7e-eb28-4b46-ae82-7ba854467bb8.png">
</a>

<img width="32%" alt="image" src="https://user-images.githubusercontent.com/11786283/183625700-7ead79ad-4194-43d1-923b-5ce8e40866ea.png">

**Comment by ai** [comment]
Can I ask you to send PR? I agree that we could improve it, but I personally does not see a use case and prefer focusing on another task. But I will help you.

**Comment by phoenisx** [comment]
Sure @ai
Let me take a look. I would be able to work on it next weekend.

<br>

> P.S: Forgot to mention: _Thanks for building such a great tool_ 🙇🏽
