### ISSUE TITLE
Regression in 8.4.15 for Stylelint in Yarn Workspaces

### ISSUE THREAD

**Issue by johnnybenson** [postcss/postcss#1766]
Hey bear with me for a second, I realize this bug report is entangled not only with [stylelint](https://github.com/stylelint/stylelint), but also [@stylelint/postcss-css-in-js](https://github.com/stylelint/postcss-css-in-js).

I am filing the issue with PostCSS because that was the only dependency change. Upgrading and downgrading PostCSS resolves the problem.

Upgrading PostCSS past `8.4.14` breaks the plugin resolution. The change set is small, hoping someone more familiar with this tool chain has an "a-ha" moment.

This project uses Yarn 1.x (`1.22.19`) workspace, the dev dependency is declared in the workspace.

https://github.com/postcss/postcss/compare/8.4.14...8.4.15

Downgrading PostCSS resolves the issue.

Here's the output:

```sh
$ stylelint --config ./stylelint.config.js './src/**/*.tsx'
Error: Cannot resolve custom syntax module "@stylelint/postcss-css-in-js". Check that module "@stylelint/postcss-css-in-js" is available and spelled correctly.

Caused by: Error: Cannot find module '@stylelint/postcss-css-in-js'
Require stack:
- /project/node_modules/stylelint/lib/getPostcssResult.js
- /project/node_modules/stylelint/lib/createStylelint.js
- /project/node_modules/stylelint/lib/resolveConfig.js
- /project/node_modules/stylelint/lib/printConfig.js
- /project/node_modules/stylelint/lib/cli.js
- /project/node_modules/stylelint/bin/stylelint.js
    at getCustomSyntax (/project/node_modules/stylelint/lib/getPostcssResult.js:105:11)
    at getPostcssResult (/project/node_modules/stylelint/lib/getPostcssResult.js:41:5)
    at lintSource (/project/node_modules/stylelint/lib/lintSource.js:79:20)
    at async /project/node_modules/stylelint/lib/standalone.js:228:27
    at async Promise.all (index 6)
    at async standalone (/project/node_modules/stylelint/lib/standalone.js:267:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

FWIW, the Stylelint config references the plugin like this:

```js
module.exports = {
    extends: [
        'stylelint-config-recommended',
        'stylelint-config-styled-components',
    ],
    overrides: [
        {
            files: ['**/*.tsx'],
            customSyntax: '@stylelint/postcss-css-in-js',
            rules: {
                'function-no-unknown': null,
            },
        },
    ],
};
```

Going to downgrade for now, and any insights are much appreciated! Thanks for making PostCSS 😎

**Comment by ai** [comment]
Let’s discuss here https://github.com/stylelint/stylelint/issues/6252
