### ISSUE TITLE
TypeError: Cannot read property 'stringify' of undefined (8.3.0 -> 8.4.16)

### ISSUE THREAD

**Issue by Lonli-Lokli** [postcss/postcss#1767]
I faced an issue with upgrading my Nx codebase (React+StyledComponents) to the latrst version. The change I noticed is that version goes up 8.3.0 -> 8.4.16
I do not have working small reproduction, if you think you will need it can you explain what sample will satisfy your needs (complexity)

My assumption here is that now this module cannot handle empty files or files without styled components
```
 $) stylelint "**/*.{ts,tsx}"

TypeError: Cannot read property 'stringify' of undefined
    at Function.stringify (D:\sources\rmboa\node_modules\postcss-syntax\stringify.js:8:38)
    at MapGenerator.generate (D:\sources\rmboa\node_modules\stylelint\node_modules\postcss\lib\map-generator.js:323:12)
    at LazyResult.stringify (D:\sources\rmboa\node_modules\stylelint\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.runAsync (D:\sources\rmboa\node_modules\stylelint\node_modules\postcss\lib\lazy-result.js:443:17)
    at LazyResult.async (D:\sources\rmboa\node_modules\stylelint\node_modules\postcss\lib\lazy-result.js:221:30)
    at LazyResult.then (D:\sources\rmboa\node_modules\stylelint\node_modules\postcss\lib\lazy-result.js:206:17)
```

**Comment by ai** [comment]
Sorry, you need to open this issue in Stylelint.

If you will know what to change in PostCSS core open a new issue.

**Comment by AndreyYevtukhov** [comment]
@Lonli-Lokli 

did you open that issue in https://github.com/stylelint/stylelint? 
or maybe found a solution? :)

**Comment by Lonli-Lokli** [comment]
Unfortunately not for both cases. I think it's related to latest changes in postcss to lazy load, but everyone needs a clean simple reproduction without external libraries

**Comment by omjokine** [comment]
I have this same issue. Unfortunately I don't have very simple piece of code to reproduce this issue, but got the same stack trace as OP had.

This happened when updated postcss from `8.4.14` to 8.4.16`. So I can reproduce it simply running `npm update postcss` and then running stylelint. So I guess it is regression in postcss, not in stylelint.

**Comment by tomof** [comment]
I faced the same problem. Fortunately, the repository is publicly available, so I will post the URL of the pull request by the Renovate bot that caused the problem. I hope this helps. 

- https://github.com/kufu/smarthr-design-system/pull/239
- Update postcss from `8.4.14` to `8.4.16`.
  - https://github.com/kufu/smarthr-design-system/pull/239/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR17820
- Error log
  - https://github.com/kufu/smarthr-design-system/runs/7832428358?check_suite_focus=true

**Comment by Lonli-Lokli** [comment]
@ai Can you please reiterate this issue? Do you still think it should be fixed in stylelint?

**Comment by AndreyYevtukhov** [comment]
we have solved it by adding 

```
"overrides": {
    "postcss": "^8.4.16"
  }
```

in `package.json`

**Comment by Lonli-Lokli** [comment]
Unfortunately that's only workaround and also requires Node16

**Comment by ai** [comment]
> Can you please reiterate this issue?

I will re-open this issue only if we will have explicit understandard what do we need to change in the core.

Before it, better to discuss it in Stylelint issue.

**Comment by Lonli-Lokli** [comment]
@ai Here is my findings.
`postcss-syntax` expecting to have document (aka root) to be Document
https://github.com/gucong3000/postcss-syntax/blob/master/stringify.js#L5-L7

Which does not happen with new version https://github.com/postcss/postcss/blob/main/lib/container.js#L427-L430
While was happening with the old one https://github.com/postcss/postcss/blob/8.4.14/lib/container.js#L421-L423

As a result stringifier goes into the https://github.com/gucong3000/postcss-syntax/blob/master/stringify.js#L8
`source` property does not exists and we are facing an issue.

**Comment by ai** [comment]
Seems like `postcss-syntax` is hack the AST.

We can’t just remove `node.type === 'root'` because it is fixed another bug.

Here are my suggestions:

1. Fix Stylelint and set `.source.syntax.stringify` to some custom analog of `docStringify`
2. Find a way to detect `Document` from `postcss-syntax` and avoid conversation. But I afraid it will break AST normalization fix.
