### ISSUE TITLE
[v8.4.19] Cannot read properties of undefined (reading 'stringify')

### ISSUE THREAD

**Issue by fmacherey** [postcss/postcss#1791]
After updating from 8.4.18 to 8.4.19 I get the following error when using stylelint.

I am using linaria inside nextjs.

```
[stylelint] TypeError: Cannot read properties of undefined (reading 'stringify')
[stylelint]     at Function.stringify ([...]application/node_modules/postcss-syntax/stringify.js:8:38)
[stylelint]     at MapGenerator.generate ([...]application/node_modules/stylelint/node_modules/postcss/lib/map-generator.js:328:12)
[stylelint]     at LazyResult.stringify ([...]application/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:277:20)
[stylelint]     at LazyResult.runAsync ([...]application/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:443:17)
[stylelint]     at LazyResult.async ([...]application/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:221:30)
[stylelint]     at LazyResult.then ([...]application/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:206:17)
error Command failed with exit code 1.
```

**Comment by ai** [comment]
cc @romainmenke

**Comment by romainmenke** [comment]
Second line in that stacktrace seems to correspond with : https://github.com/gucong3000/postcss-syntax/blob/master/stringify.js#L8

**Comment by fmacherey** [comment]
It looks like there is a general problem. Even if I lint one small component, it still crashes. 

```
export const GreeterWrapper = styled.div`
    position: absolute;
    top: 0;
    left: 50%;
    transform: translateX(-50%);
    width: 300px;
    height: 150px;

    span {
        position: absolute;
        bottom: 10px;
        left: 50%;
        transform: translateX(-50%);
        font-size: 28px;
        font-weight: bold;
        color: blue;
    }
`;
```

**Comment by romainmenke** [comment]
Thank you!

Do you have any extra info you can share on how to setup a project that would similar to yours?

First going to try and reproduce the bug on my end so that I can see what is going on in detail.

**Comment by fmacherey** [comment]
I have a NextJS App with Linaria for styling

Note: I am using not the current v4 versions, due to a babel error. I am using this versions:
```
        "@linaria/babel-preset": "3.0.0-beta.23",
        "@linaria/core": "3.0.0-beta.22",
        "@linaria/react": "3.0.0-beta.22",
        "@linaria/shaker": "3.0.0-beta.23",
        "@linaria/stylelint": "3.0.0-beta.22",
        "@linaria/webpack-loader": "3.0.0-beta.23",
```

This is my .babelrc
```
{
    "presets": [
        "next/babel",
        "@babel/preset-react",
        "@linaria"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime"
    ]
}
```

and my .stylelintrc
```
{
    "extends": [
        "stylelint-config-recommended",
        "@stylelint/postcss-css-in-js",
        "@linaria/stylelint"
    ],
    "overrides": [
        {
            "files": [
                "**/*.tsx",
                "**/*.jsx",
                "**/*.ts",
                "**/*.js"

            ],
            "customSyntax": "@stylelint/postcss-css-in-js"
        }
    ],
    "rules": {
        "function-no-unknown": null,
        "no-empty-source": null
    }
}

```

**Comment by romainmenke** [comment]
Hehe, yeah I have no idea what most of those things are or how to glue them together as a project :D

what I did:
- `npx create-next-app@latest`
- copy/paste those extra dependencies
- create the `.babelrc` file
- create the `.stylelintrc` file

A complete minimal reproduction would be ideal.

**Comment by romainmenke** [comment]
What I can see :

- `postcss-syntax` is using `Node.source` as a storage object : https://github.com/gucong3000/postcss-syntax/blob/master/parser.js
- `postcss-syntax` seems to store information about the syntax on the `Root` node.
- something is resetting the stored information
- `postcss-syntax` doesn't have sufficient `null` checking for `Node.source` : https://github.com/gucong3000/postcss-syntax/blob/master/stringify.js#L8
- `postcss` has code that deletes `Node.source` : https://github.com/postcss/postcss/blob/main/lib/container.js#L13

What I want to find out :
- are there are other plugins that might be altering `Node.source` or only `postcss` itself.
- why/how is the information in `Node.source` being removed.

**Comment by fmacherey** [comment]
No only linaria is working with postcss in our project.

**Comment by romainmenke** [comment]
> What I want to find out :
>
> - are there are other plugins that might be altering Node.source or only postcss itself.
> - why/how is the information in Node.source being removed.

This is something I can only answer with a reproduction.
`postcss-syntax` for example is the first package in the stacktrace and it is definitely making substantial changes to PostCSS internals.

I have tried to write some tests for the scenario's that can cause PostCSS to remove `Node.source` but I don't spot any difference here between 8.4.18 and 8.4.19

I think a minimal reproduction is our best chance of finding out what is going on here :)

**Comment by ai** [comment]
During PostCSS update, are you changing only `postcss` version in the lock file?

Do you have any other changes?

**Comment by fmacherey** [comment]
I only updated the postcss dependency, here is my lockfile. I can look, if i get a wokring example I can provide you :) 

```
diff --git a/application/yarn.lock b/application/yarn.lock
index 4ecb71c1..df62c4ee 100644
--- a/application/yarn.lock
+++ b/application/yarn.lock
@@ -8606,6 +8606,15 @@ postcss@^8.4.18:
     picocolors "^1.0.0"
     source-map-js "^1.0.2"

+postcss@^8.4.19:
+  version "8.4.19"
+  resolved "https://registry.yarnpkg.com/postcss/-/postcss-8.4.19.tgz#61178e2add236b17351897c8bcc0b4c8ecab56fc"
+  integrity sha512-h+pbPsyhlYj6N2ozBmHhHrs9DzGmbaarbLvWipMRO7RLS+v4onj26MPFXA5OBYFxyqYhUJK456SwDcY9H2/zsA==
+  dependencies:
+    nanoid "^3.3.4"
+    picocolors "^1.0.0"
+    source-map-js "^1.0.2"
+
 prelude-ls@^1.2.1:
   version "1.2.1"
   resolved "https://registry.yarnpkg.com/prelude-ls/-/prelude-ls-1.2.1.tgz#debc6489d7a6e6b0e7611888cec880337d316396"
```

**Comment by romainmenke** [comment]
Good catch!

Always happy to help out 🙇
