### ISSUE TITLE
Last semicolon in file is not parsed

### ISSUE THREAD

**Issue by mvorisek** [postcss/postcss#1806]
LESS file:
```
@variable: {
  field: something;
};
```

is currently parsed wrongly and the `raws` property contains:
```
raws: { semicolon: false, after: ';\n' },
```

but I would expect:
```
raws: { semicolon: true, after: '\n' },
```

Observations:
- the problem seems to be in `lib/parser.js` file
- the semicolon is not consumed only for the last LESS variable in file
- file like `@variable: something;` (ie. variable without curly brackets) has the semicolon consumed correctly

**Comment by ai** [comment]
You need to open issue at PostCSS Less parser.

This repo is for standard CSS parser. It is illegal syntax for it.

**Comment by mvorisek** [comment]
Sorry for opening an issue here, I belive the problem is in prettier directly - see https://github.com/prettier/prettier/pull/14007.
