### ISSUE TITLE
New plugin API

### ISSUE THREAD

**Issue by ai** [postcss/postcss#181]
We need new plugin API to fix #163 and to store plugin name for #177

I suggesting:

```js
var postcss = require('postcss');

module.exports = postcss.plugin('postcss-my-plugin', function (opts) {
    // Work with options
    return function (css, postcss) {
        // Work with CSS AST
        // postcss will be PostCSS instance with other plugins
    };
});
```

Of course, old one function style will be supported too. But it ill be only for custom plugins. Plugin Guideline will required only this format.

**Comment by lydell** [comment]
It might be confusing to have two different `postcss` variables around.

**Comment by ai** [comment]
@lydell yeap. How about this: `function (css, processor) {`

**Comment by MoOx** [comment]
@ai +1 for this simple change already mentioned in #177

**Comment by ai** [comment]
@MoOx I think I misunderstood you in #177. Can you write a code example of your suggestion, like I did abowe?

**Comment by MoOx** [comment]
This seems enough.

```
module.exports = function (opts) {
    // opts are options for plugin
    return function (css, postcss) {
        // css => ast
        // postcss => instance with other plugins
    }
})
```

Just add `postcss` as a second argument. No need to changes things again. I don't see any benefit on a register method.

**Comment by ai** [comment]
`postcss.plugin` will add wrap with PostCSS AST version check

**Comment by ai** [comment]
@MoOx also, where we will get plugin name for `result.messages`?

**Comment by MoOx** [comment]
The message format might expect an `origin` key.
Multiples plugins can hace hte same origin (ex: a linter that use a plugin for each rule should have message from the same origin).

**Comment by ai** [comment]
Should we ask all plugins developers to have `postcss-plugin` in `package.json` keyworks?

**Comment by hail2u** [comment]
`-` seems extraneous to me.

**Comment by ai** [comment]
@hail2u I agree :). Can we use spaces inside keywords? `"postcss plugin"`?

**Comment by hail2u** [comment]
@ai Spaces can be used on keywords, but `postcssplugin` (like [`gulpplugin`](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) or [`gruntplugin`](http://gruntjs.com/plugins)) looks good to me.

**Comment by ai** [comment]
@hail2u thanks. Yes, let’s `postcssplugin` if Gulp and Grunt uses this format.

Also thanks for link to Gulp plugin guidelines, it will useful when I will write PostCSS Guidelines.

**Comment by ai** [comment]
OK, I added `postcssplugin` to boilerplate https://github.com/postcss/postcss-plugin-boilerplate/commit/8d31112e6addcaeb5733d9dd23fb1ee1ef174d2f

**Comment by ai** [comment]
Done 7342320
