### ISSUE TITLE
Rename postcss.atRule to postcss.atrule

### ISSUE THREAD

**Issue by ai** [postcss/postcss#183]

**Comment by hail2u** [comment]
If you rename `postcss.atRule` to `postcss.atrule`, you should rename `eachAtRule` container method to `eachAtrule` also.

**Comment by MoOx** [comment]
What the point of this ?

**Comment by ai** [comment]
`type` property uses `atrule` form. Also mixed case is difficult to enter.

**Comment by magsout** [comment]
IMHO atRule is perfect => camelCase..

**Comment by ai** [comment]
@ben-eb @jonathantneal what are you think here? Right now we have some inconsistence and I think it will be good to clean it.

**Comment by davidtheclark** [comment]
I do make the `node.type === 'atRule'` typo frequently. But I do not think that mixed case is difficult to enter, or that that should be important. Instead, I think a function named `eachAtrule` would be too strange — looks like a mistake. So if you want to make it all consistent (which I'm in favor of) my vote would be for camelCasing the `type` `atrule` instead of lowercasing `atRule`.

**Comment by ben-eb** [comment]
:+1: to @davidtheclark's suggestion.

**Comment by ai** [comment]
Ouh, OK, let’s close it, I hate `type === "atRule"` :D.

**Comment by lydell** [comment]
Wasn't the conclusion to change `node.type` from `'atrule'` to `'atRule'`, or am I confused?

**Comment by ai** [comment]
@lydell nope :). I suggest change `postcss.atRule` to `postcss.atrule` :).

**Comment by lydell** [comment]
I know that was the original idea of this issue, but wasn't the conclusion here in the end that we should change node.type from 'atrule' to 'atRule'?

**Comment by ai** [comment]
I think `atRule` is more hard to input. Also changing `node.type` behaviour is too hard. We can’t print a warning for old API.

**Comment by ben-eb** [comment]
You could always do a case-insensitive check on `node.type`. That would be a good compromise.

**Comment by ai** [comment]
Problem is not in PostCSS code, but in plugins code.

**Comment by ben-eb** [comment]
If the check is case-insensitive, it means that plugin authors don't need to do anything to update and those who want to use `atRule` can do so.

**Comment by ai** [comment]
I mean, that right now we have many code with `node.type ==="atrule"` in plugins. So this check already case sensitive.
