### ISSUE TITLE
Help with the postcss error, please.

### ISSUE THREAD

**Issue by NnicanBuak** [postcss/postcss#1831]
<sub>Nuxt: 3.3.1-3.4.1
tailwindcss: ~3.3.0
autoprefixer: ^10.4.14
postcss: ^8.4.21
@nuxt/postcss8: ^1.1.3
postcss-custom-properties: ^13.1.4
postcss-nesting: ^11.2.1
</sub>
https://stackoverflow.com/questions/76010260
![](https://i.stack.imgur.com/L9r1M.png)

**Thank you in advance for your help!**

**Comment by ai** [comment]
Sorry. Seems like it is environment problem, not an issue in PostCSS.
