### ISSUE TITLE
TypeError: Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rodriguezmarting** [postcss/postcss#1833]
Updating to latest postcss version using Broccoli is throwing a type error, tried with different approaches but none worked:

Using `"broccoli-postcss": "6.1.0"` which uses `"postcss": "8.1.4"`
Same error using `"broccoli-postcss-single": "5.0.2"` which also uses `"postcss":  "8.1.4"`

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/51244476/232585385-9c2d5d7d-d19e-41a2-860e-6b6eb4debe81.png">

My brocfile:

```
...
const postcss = require("broccoli-postcss");
...

export default ({env}) => {

  ...

  const cssPlugins = {
    plugins: [
      {
        module: postcssMixins
      },
      {
        module: postcssMomentumScrolling
      },
      {
        module: postcssPresetEnv,
        options: {
          stage: 0, 
          preserve: false,
        }
      },
    ]
  };

  ...


  postcss("css", {plugins: cssPlugins})

  ...
```

After adding the `new` keyword it throws the following error:

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/51244476/232589910-93e2ddba-fdff-4e41-82bb-3c7b448b181a.png">

**Comment by rodriguezmarting** [comment]
Thanks for your input.
Just to confirm, is it just about bumping up the version of postcss in broccoli-postcss or nothing related to postcss at all?

**Comment by ai** [comment]
It is hard to say. We need to debug their code.
