### ISSUE TITLE
 Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by Mohit8561** [postcss/postcss#1834]
I am trying to upgrade the Postcss version from 7 -> 8 and I have css-loader version 5.2.0, during the build time I am getting this particular error mentioned below

./node_modules/rc-input-number/assets/index.css
Error: Package subpath './lib/vendor' is not defined by "exports" in /app/node_modules/postcss/package.json

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/app/node_modules/next/dist/build/index.js:192:15)
make: *** [Makefile:71: check] Error 1

Please anyone can suggest what could be the root cause for this error?

**Comment by ai** [comment]
`vendor()`  helper was removed in PostCSS 8. You need to remove this import.

1. Be sure that you update all PostCSS plugins too (like Autoprefixer).
2. Search for `lib/vendor` in your code and in `node_modules`.
