### ISSUE TITLE
Parser types are confusing

### ISSUE THREAD

**Issue by marekdedic** [postcss/postcss#1839]
Hi,
I am trying to create my own simplified version of `postcss-safe-parser` (one that would work with `postcss-scss`) with TypeScript. However, I have a hard time understanding the types around `Parser` and `parse`.

If I understand it correctly, the `Parser` class is not exported from `postcss`, while the `parse` function is exported and has a TS type of `Parser` - is that correct? Because that is really confusing.

So, is there any way to extend the `Parser` class? because I cannot `import { Parser } from "postcss/lib/parser"`, it tells me there is no declaration and I can't create one because there already is a `Parser` type that isn't actually the type of the `Parser` class...

Thanks

**Comment by ai** [comment]
Yes, `Parser` is semi-private class. I am using it in `postcss-safe-parser` only because two projects share the same maintainer.

Why do you need another `postcss-safe-parser` version?

**Comment by marekdedic** [comment]
> Why do you need another `postcss-safe-parser` version?

I am trying to add style parsing using SCSS to svelte-eslint-parser (see sveltejs/svelte-eslint-parser#340). Because svelte styles can be in multiple languages (e.g. SCSS), the parser needs to be able to parse multiple languages. At the same time, I don't want it to crash on invalid input, preferably listing parse errors as part of the output.

AFAICT, one could do this with something akin to

```ts
class SafeCSSParser extends CSSParser {
  createTokenizer() {
    this.tokenizer = tokenizer(this.input, { ignoreErrors: true })
  }
}

class SafeSCSSParser extends SCSSParser {
  createTokenizer() {
    this.tokenizer = tokenizer(this.input, { ignoreErrors: true })
  }
}

const parser = shouldUseSCSS ? new SafeSCSSParser() : new SafeCSSParser();
parser.parse(); 
```

So that's why I'd need access to the `Parser` class :) But maybe there is a better way to do this whole thing (like, exposing the `ignoreErrors` option on the `parse` function of `postcss` and `postcss-scss`?)

Thanks!

**Comment by ai** [comment]
I am not sure that `ignoreErrors` will not hit the performance.

For you, it will be just to copy-patse tokenizer and parser code and add patches (like we did in `postcss-scss`).

**Comment by marekdedic** [comment]
> I am not sure that `ignoreErrors` will not hit the performance.

Thanks, that's a good heads up :)

> For you, it will be just to copy-patse tokenizer and parser code and add patches (like we did in `postcss-scss`).

Do I understand you correctly in saying that I should basically copy-paste a non-trivial part of `postcss`, `postcss-scss` and potentially any other parsers just to change one line? Because that would make the maintenance of such code an order of magnitude more complicated...

**Comment by ai** [comment]
> to change one line?

This exactly what we did for `postcss-scss`. Performance requires sacrifices 😅

**Comment by marekdedic** [comment]
Thanks, closing this as answered :)
