### ISSUE TITLE
postcss seems not to handle * hack

### ISSUE THREAD

**Issue by kud** [postcss/postcss#184]
I've got this code (yes a bit old)

```
.container:before {
    display: table;
    content: "";
    zoom: 1;
    *display: inline; }
```

but postcss compiles it as:

```
.container:before {
    display: table;
    content: "";
    zoom: 1;
    display: inline
}
```

which breaks all my design. Any idea?

**Comment by ai** [comment]
PostCSS can parse `*`. Try PostCSS with only Autoprefixer in [interactive demo](http://simevidas.jsbin.com/gufoko/quiet).

Can you post all of CSS? Because I think some plugin remove your code styles (maybe it is a postcss-mixin).

**Comment by MoOx** [comment]
@kud is using cssnext

But...

![screen shot 2015-02-10 at 19 01 13](https://cloud.githubusercontent.com/assets/157534/6133032/498d6c46-b157-11e4-8175-79033b38b134.png)

Not sure what is the fuck here :)

**Comment by ai** [comment]
@MoOx `clone` and `moveTo` removes the code style. And `*` is just a code style in PostCSS.

I can leave old `before` on cloning if it contains non-space symbols. It will break a indentation when we change depth in mixin, but it is a rare case.

**Comment by MoOx** [comment]
> clone and moveTo removes the code style

This is responsible for a lot of trouble recently with postcss-import :(
Maybe I should just stop using postcss api in postcss-import in favor of raw manipulation...

Why don't you just create a `copy()` method with an optional argument to remove code style ?
It's not a clone if you copy + alter something.

**Comment by ai** [comment]
@MoOx you can move nodes by your own functions. It is totally OK with PostCSS ideology. Methods a just a helpers.

I think quick steps make situation only worse. Tell me, what is a problem with cleaning code style variables in `postcss-import`. Maybe we need to fix code style detector or other parts of PostCSS.

**Comment by MoOx** [comment]
> Tell me, what is a problem with cleaning code style variables in postcss-import

This bug

+

The difficulties I encounter when upgrading to postcss 4 https://github.com/postcss/postcss-import/issues/16#issuecomment-71166687

If that just "helpers", make them simple & stupid. clone should clone, not clone + modify. This is more like a opinionated copy.

**Comment by ai** [comment]
@MoOx you didn’t speak about a bugs in that issue in `postcss-import`, only ask a question about behaviour.

Current API try to hide difficults with code style process. For example, if you move node from root to at-rule, we need to increase indent. We can change API in 5.0, but what new API you suggest?

We can clean code style in insert methods and have a option to leave it without changes. But I didn’t think that this method is simplier.

**Comment by MoOx** [comment]
@kud fyi, postcss-import 5.0.2 ship a workaround to avoid this bug.
Please uninstall cssnext, reinstall and confirm me it's ok :)

**Comment by kud** [comment]
Thank you very much, I will try. ;)

**Comment by ai** [comment]
Merges into #199

**Comment by kapouer** [comment]
Just for other people stung by that star hack problem: i had to replace .append() to .push() call, as a workaround.

**Comment by ai** [comment]
@kapouer `push()` is for parser only. You can broke a AST if you will use `push()` in wrong way.

What do you want to do? Maybe I can suggest you better way?

**Comment by kapouer** [comment]
I'm parsing several files, concatenating them (append to root) and applying various stuff to them, see https://github.com/kapouer/raja-minify/blob/master/index.js#L133
