### ISSUE TITLE
How do I make 2 different configuration ??

### ISSUE THREAD

**Issue by alcapitan** [postcss/postcss#1842]
I'm currently very frustrated by this error, especially as there's no explanation on the Internet and PostCSS doesn't indicate any error even in verbose mode.

Here is my NPM commands : 
```
postcss atui/kernel/src/*.css --config .pre-postcssrc.json --replace --no-map
postcss atui/kernel/src/*.css -d atui/kernel/dist/ -m
```

This is my `.pre-postcssrc.json` config file : 
```json
{
    "plugins": {
        "cssnano": {
            "preset": ["default", { "normalizeWhitespace": false, "discardComments": false }]
        }
    }
}

```

And my `.postcssrc.json` config file : 
```json
{
    "plugins": {
        "cssnano": {
            "preset": ["default", { "discardComments" : { "removeAllButFirst": true } } ]
        },
        "postcss-import": {},
        "postcss-preset-env": {
            "stage": 2
        },
        "autoprefixer": {}
    }
}
```

I expect my first command with `--config .pre-postcssrc.json` to execute the `.pre-postcssrc.json` file, but it executes the `.postcssrc.json` file.

After a lot of testing, I think PostCSS ignores the `--config` option. However, the `--config` option appears in `npx postcss --help` as well as in the [PostCSS-cli's README](https://github.com/postcss/postcss-cli/blob/master/README.md#usage).

I'm using these versions :
- PostCSS : 8.4.24
- PostCSS-cli : 10.1.0

I want this way of operation. So please tell me how to fix that error.

**Comment by ai** [comment]
Sorry, you need open this issue on `postcss-cli` package. I am developing the core, and CLI tool is on another developer.
