### ISSUE TITLE
Parse property with several tokens

### ISSUE THREAD

**Issue by ai** [postcss/postcss#185]
We need to parse `$(var)-prop: value`

**Comment by lydell** [comment]
Does that really belong to the core parser? Isn’t this a custom parser thing?

**Comment by ai** [comment]
Right now `postcss-simple-vars` plugin required in. Maybe in future other plugins will required it too.

I didn’t think that plugin should depends on parser. They just work with AST.

Anyway it is not so difficult to make it in standard parser. So  I didn’t see disadvantages is standard parser with parse it.

**Comment by lydell** [comment]
Alright. The only concern I had was “If we start here, where do we stop? When is syntax parsing requests from plugins too much?”. But whatever. :)

**Comment by ai** [comment]
Fixed by @mahtd in PostCSS 5.0.5
