### ISSUE TITLE
[regression][8.4.25] clone() return base node type instead of the origin node type

### ISSUE THREAD

**Issue by idoros** [postcss/postcss#1854]
This breaking change was introduced in [`Improved documentation & types`](https://github.com/postcss/postcss/pull/1849) PR.

I believe this is a mistake, and one would expect to have a `root` type node when cloning a `root` node (or any other node type that didn't explicitly override the clone method).

**Comment by ai** [comment]
I will try to fix it tonight

**Comment by vikaskaliramna07** [comment]
As I explained there, `this` refers to the reference of that already existing node.
For proper type support, it should be written like this `node.clone() as Root` 

You can check this, not exactly postcss implementation but explains why `this` is not allowed as return type when a new reference(for duplicated node) is returned.

```ts
class NodeA {
  // typescript does not allow this
  public clone(): this {
    return new NodeA();
  }
}

// but this is allowed
class NodeB {
  public clone(): NodeB {
    return new NodeB();
  }
}
```



<details><summary><b>Output</b></summary>

```ts
"use strict";
class NodeA {
    // typescript does not allow this
    clone() {
        return new NodeA();
    }
}
// but this is allowed
class NodeB {
    clone() {
        return new NodeB();
    }
}

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/MYGwhgzhAEByD2ATApgQWgbwFDWgej2gBcBPAB2QmACcBLMo6ReS6AO3kbBBHgHdiAC1oQc0MgFcARiFrBooeG2QAKAJQAuISMxjc1ZEQnU27ZAIQpU6gNxiAvlkdYC0KRMZFhMHd159kRCxQSBhLZAAhXVxJGTkFXmV1LXCo7Fx9Q2NTZQskSNsHJyA)

**Comment by ai** [comment]
> As I explained there, this refers to the reference of that already existing node.

Can you show the TS example where it will create an issue?

**Comment by vikaskaliramna07** [comment]
If you click on the provided link, it does show you the error but you could override it using
`return new NodeA() as this;`, which is not the correct way.

It might or might not create an issue for a plugin developer but it surely is the correct way of writing the types, just like using `Record<K, V>` instead of `object` type.

**Comment by ai** [comment]
I found a better way (not old, not new) b5a3b35a

**Comment by ai** [comment]
The fix was released in 8.4.26

**Comment by vikaskaliramna07** [comment]
wait, you didn't have this before?
I have a local fork of postcss, where each class handles cloning, implementing the `defaults` passed to constructor own their own.
Which does follow this method, I would love to share it but it's not complete and I removed lots of old features from it.

Written in pure typescript(using Deno) and expected to be released before August 31 :)

**Comment by ai** [comment]
> I have a local fork of postcss, where each class handles cloning, implementing the defaults passed to constructor own their own.

Yes, but they have `this` in return (you fixed it only in `Node#clone`, `Rule#clone` still return `this`)

**Comment by vikaskaliramna07** [comment]
Yeah I initially focused on few files, which included Node, Comment and Declaration only.
I am going to open an issue where I will suggest some changes that I think would improve the postcss project,
found those issues while working on a re-write in pure typescript, includes fix for circular dependency(that comes at a cost of removing 2 - 3 methods)

**Comment by idoros** [comment]
Apologies for the delayed response.

To be honest, I acknowledge that you are technically correct in stating that returning `this` cannot tell what the actual type is going to be and might refer to the extending type. However, the structure of postcss in JavaScript precisely follows this approach. It creates a fresh copy by invoking `new this.constructor` and then blindly duplicates properties from the original to the clone. 

consequently when hard coding the base return type, any extending node type must override the method to return the extended type.

Regardless, I am open to any solution that avoids the need to cast the type after cloning. I will test the new version on Sunday and report any issues.

And if you make the TypeScript version of the project available, I would be interested in exploring it.

**Comment by vikaskaliramna07** [comment]
Well you are correct, postcss is designed that way and could not be fixed without breaking stuff.

I want to release my typescript version asap but I still need to re-write few APIs from scratch,
also have to introduce some new ones.

It is going to be difficult to migrate because the final result is going to be a lot different than postcss.
Also, the Parser is still not properly written in TypeScript. Will take time :)
