### ISSUE TITLE
for loop support

### ISSUE THREAD

**Issue by vikaskaliramna07** [postcss/postcss#1857]
The Container has a `getIterator` method, which works fine but I have a better suggestion.

```ts
// TypeScript version, works in JavaScript after types are removed.
// I would prefer this one, but would love to hear feedback.
*[Symbol.iterator](): Generator<Node> {
    const duplicateList: Node[] = [...(this.nodes ?? [])];

    if (duplicateList.length > 0) {
      yield duplicateList.shift() as Node;
    }
  }
```

Information about runtime support has been provided [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#browser_compatibility), looks good to me.

This method would add support for directly using a node in a loop, for example:
```ts
for (const node of root) {
  console.log(node.type);
}
```

The `getIterator` method could be deprecated in favour of this or could exist but depend on `Symbol.iterator`

This issue does not define the behavior for the method, the generating of the return value could vary, my version just duplicates the reference of the original nodes(which does have little affect on performance but not as slow as actual cloning a node, duplicating any references is very common).

**Comment by ai** [comment]
`getIterator()` has nothing to do with `for-of`. It is a internal method for PostCSS’ tricky loops. In PostCSS you can remove/add nodes during the loop without unexpected results.

We can add `Symbol.iterator` support, but we need to be sure:

1. It works on every Node.js version ≥ 10 (I will need proofs)
2. We will be able to port a thicky `this.indexes` logic to `Symbol.iterator`

**Comment by vikaskaliramna07** [comment]
1. Yes it works with Node 0.12.0 (Released 2015-02-06) according to MDN website.
[check here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#browser_compatibility)

2. Yes, it removes that this.indexes logic at a cost of duplicating reference, don't know how to perform benchmarks so you have to do that :)

You would not need any other complex logic if you implement the method of `Symbol.iterator` where it duplicates reference..

You could keep iterating over the elements present in `nodes` property, you could set it to undefined and would still work.
But it might cause trouble while traversing using the `walk` method if you append new node or remove existing node which is expected I guess because you can not handle indexes for a whole tree of nodes, depends and needs to be checked.

How this works is, it duplicates the reference in a new array, and when you loop over it, you are actually looping over the original nodes but using the reference that exist in different memory location instead of the ones present in `nodes` property, so doing anything with the `nodes` property would not cause trouble in this function in `forEach` or `for of` loop.

**Comment by ai** [comment]
> How this works is, it duplicates the reference in a new array

It will not work with adding new elements in the middle of the circle.

Also we will need an API to walk through nested children (since it is the most popular API).

**Comment by vikaskaliramna07** [comment]
> It will not work with adding new elements in the middle of the circle.
What do you mean? Like adding new elements to an array or you mean the duplicating of reference(which is not actual duplicating of nodes)

It's not going to affect the walk API, it might not allow appending new elements without causing trouble in loop.
I guess I need to write an dummy implementation and show you.

**Comment by ai** [comment]
> I guess I need to write an dummy implementation and show you.

Yes, let's start from code

**Comment by vikaskaliramna07** [comment]
hey, you can find the implementation [here](https://github.com/vikaskaliramna07/postcss/tree/experimental-forEach)

In this version, you can append before or after nodes or remove nodes without having tricky index logic.
I just copied tests from `each` because I wanted to test if that works fine or not.

This method iterates on the child node that were present before the loop started, any modification within the loop would not affect it and will continue to loop over the original `nodes` property instead of the modified one.

**Comment by ai** [comment]
> hey, you can find the implementation [here](https://github.com/vikaskaliramna07/postcss/tree/experimental-forEach)

I need PR to see the changes (even if tests doesn’t pass)

**Comment by vikaskaliramna07** [comment]
sure
