### ISSUE TITLE
postcss drops  trailing semicolon from a second-to-last non-container AtRule when removing their next sibling 

### ISSUE THREAD

**Issue by Goodwine** [postcss/postcss#1861]
Example input:
```css
@charset "UTF-8";
:root { foo: bar }
```
With a postcss plugin remove the `:root` node:
```js
root.nodes[1].remove();
```
postcss will output the following at-rule without trailing semicolon:
```css
@charset "UTF-8"
```
The semicolon shouldn't have been removed.

**Comment by Goodwine** [comment]
More details: https://runkit.com/goodwine/64b1b53e9dc05400081ff04e

**Comment by Goodwine** [comment]
It is not invalid, but the behavior is not consistent in the following scenarios:

---

Given the input:
```css
@charset "UTF-8";
```
postcss will not drop the semicolon even though the at-rule is the last node.

---

Given the input:
```css
.foo {
  a: b;
  c: d;
}
```
And running a postcss plugin that does:
```js
root.nodes[0].nodes[1].remove() // removes declaration "c: d"
```
results in:
```css
.foo {
  a: b;
}
```
Where the semicolon for the remaining declaration was preserved. I find it a bit odd that the semicolon goes away for the last at-rule in a container, but not for the last declaration in a container 🤔

**Comment by ai** [comment]
I don’t see this issue as critical. It is almost impossible to have a simple code and have consistent for all cases. The core autoformatting is just “good enough” by design. If you want consistent result, you need to use some formatter or manually work with `Node#raws`.

If somebody wants to spend your time on it, I will help and release PR.

**Comment by ai** [comment]
The reason of the current behavior, is that `:root { foo: bar }` don’t have `;` and PostCSS thinks that you are using code style without last `;` (there is no way to detect what code style you are using, so PostCSS is going to the default one).

In your second use case you have another case where we can be sure that user wants `;` in the end. This is why PostCSS keep it.

Honestly, even as a human person, I have no idea by first example do we need `;` or not here. It really depends on use case, which PostCSS doesn’t know.

**Comment by Goodwine** [comment]
I see what you mean. I realize now that a container node has the option to set `semicolon = true` so the last child has that. So.. in the case I mentioned originally I can do `root.semicolon=true`. That works well enough for me, thanks for the explanation :)
