### ISSUE TITLE
PostCSS `>=8.4.25` makes `nuxt build` extremely slow

### ISSUE THREAD

**Issue by quentint** [postcss/postcss#1864]
I recently updated PostCSS and noticed building my Nuxt 3 app took more than 3 times longer. After investigating I pinpointed this issue to versions above `8.4.24` (I can confirm `8.4.24` is decent, while `>=8.4.25` is slow).

It is related to `autoprefixer`, because removing it from `nuxt.config.ts` (`postcss.plugins.autoprefixer`) reverts to a decent build time.

I tried and looked what might have changed between these tags, but many things happened: https://github.com/postcss/postcss/compare/8.4.24...8.4.25

Did anyone also experience this?  
Can I share more details to help investigate?

**Comment by ai** [comment]
@romainmenke could it be realted to https://github.com/postcss/postcss/commit/492f4741042750aa9ffcc06a52ebcaa47ea3b6ab ?

**Comment by romainmenke** [comment]
> Can I share more details to help investigate?

@quentint I don't use `nuxt` and I don't know anything about it.
So it would be helpful if you could create a GitHub repository with a minimal project.

This should have some CSS and it should have the latest versions of the postcss plugins that make it slow.

Then I will be able to start this project locally and investigate what is slow.

**Comment by quentint** [comment]
> @quentint Did you only update `postcss` or did you update multiple things?
> 
> Is it fast if you update all your dependencies and keep PostCSS pinned at `8.4.24` ?

Yes, I took some time to make sure the slow build comes only from this update and version 😉 

> @quentint I don't use `nuxt` and I don't know anything about it. So it would be helpful if you could create a GitHub repository with a minimal project.
> 
> This should have some CSS and it should have the latest versions of postcss and the postcss plugins that make it slow.
> 
> Then I will be able to start this project locally and investigate what is slow.

Sure, I'll prepare that for you.

**Comment by quentint** [comment]
Unfortunately did not have time yet, will try on Friday! 🤞

**Comment by quentint** [comment]
I took some time to investigate this issue and I'm sorry to announce that even though I can reproduce it constantly in my complete setup (the one that made me create this issue), I didn't find a way to do it with a minimal configuration.

I also updated PostCSS to the latest version on my current project state (with many new commits since opening this issue) and everything is back to normal.

I can only suppose this had to do with other modules and/or my Tailwind configuration (did some major cleanup here) but unfortunately I won't be able to help you track this any further.

I guess that's both bad and good news 😉 

Anyways, thanks for such a powerful and useful tool 🎉

**Comment by romainmenke** [comment]
@quentint There is one thing you could check, if you can still recreate this in your setup.

If I recall correctly PostCSS has a mechanic to repair the AST if multiple versions of PostCSS are used and are conflicting.

Updating only PostCSS might introduce such a conflict.
I can imagine that this mechanic slows down processing because it is a lot of work to rebuild AST nodes especially if there are multiple visits and large source files.

In this scenario it would not be this new PostCSS version that would be slow but instead it would be that you have more than one.

`npm why postcss` might give you some insights.

**Comment by quentint** [comment]
Here is `npm why postcss`, before and after updating: https://jsoneditoronline.org/#left=cloud.5fecda09d1c44e359845c3dd4f2efc01&right=cloud.ba221511c77f4fb0be698cd641835c79

Does that confirm your theory?

**Comment by romainmenke** [comment]
No idea, I can't read what is on that page.

**Comment by quentint** [comment]
Oh 🙂 That's the JSON version of `npm why` (`npm why postcss --json`).  
There's the "before updating" on the left, and the "after" on the right!

**Comment by romainmenke** [comment]
I mean that I have no idea how to read that out of context of your project and draw a definitive conclusion from it :)

At a glance it seems that the after json has two version :
- `8.4.27`
- `8.4.24`

**Comment by quentint** [comment]
Same here 🙂
