### ISSUE TITLE
`Root.source` is missing `end` value

### ISSUE THREAD

**Issue by romainmenke** [postcss/postcss#1870]
https://github.com/postcss/postcss/blob/7d51976a7eb031ac2b31670eefcf2981bcff25ec/lib/parser.js#L34

This normally isn't an issue but when creating new nodes and adopting `source` it can lead to broken source maps.

My case :

- run PostCSS on a separate file
- rewrite parts of the AST
- new nodes are given the `source` property from the `Root` node

The end result is a broken source map that contains `<no source>`

Relevant code in the map generator: https://github.com/postcss/postcss/blob/main/lib/map-generator.js#L167-L181

**Comment by ai** [comment]
Do you have any idea how we can improve it?

We can add `end` to `Root`

**Comment by romainmenke** [comment]
Yes, adding `end` to `Root` should resolve all issues :)

----

Is it possible that it was omitted for performance?
I can imagine that scanning ahead at this point has a non-zero cost.

If the performance cost is too high I can also submit patches in affected packages.
Very few will have this bug.

**Comment by ai** [comment]
The fix was released in 8.4.28.
