### ISSUE TITLE
Extremely slow performance on Windows?

### ISSUE THREAD

**Issue by zilti** [postcss/postcss#1877]
We have a project here using postcss for tailwind. It runs very fast (as expected) on Linux and macOS, but we noticed that it's very slow on Windows in our case - Sometimes what takes a second or less on Linux takes 30s or even over a minute on Windows.

Is this a known thing? Are there "hacks"/"workarounds" to get better performance on Windows?

**Comment by ai** [comment]
Hi, again.

No, there are no hacks or workarounds because nobody reported bad performance on Windows before.

I don’t use Windows and can’t help. But my general advice is to avoid using Windows, because in Node.js community most projects even don’t test on Windows.
