### ISSUE TITLE
PostCSS ignoring dvh and svh

### ISSUE THREAD

**Issue by FiggyHunter** [postcss/postcss#1878]
I have a rather complex project where I am using vite and astro, and the older versions of mobile browsers have a bug with setting the height of elements to 100dvh or 100svh. 

What I have found fixes this problem is setting the height to 100% (in my case this works because the element is absolutely positioned in regards to the device viewport) and then specifying the height to a modern unit, so an older browser will only set the element to 100% height, and then look at the unknown unit and ignore that rule. While a modern browser will apply CSS Specificity and set it to the appropriate height.

It would be nice if you guys added some kind of logic to PostCSS that it can recognize these new css rules, and adjust the build code accordingly.

**Comment by ai** [comment]
Sorry. This issue tracker is for bugs inside the core and feature suggestion for API.

The best way is just to write plugin by your own.
