### ISSUE TITLE
Remove replaceWith or replace

### ISSUE THREAD

**Issue by ai** [postcss/postcss#188]
Ouh. We already had `Node#replace(otherNode)` when I add `Node#replaceWith(otherNode)`.

Definitely, new docs project is very important to PostCSS because it helps to find this mistakes.

**Comment by ai** [comment]
I think we should keep `replaceWith` to have API closer to jQuery.

**Comment by jonathantneal** [comment]
`replaceWith` is also the name of [the DOM4 method](https://dom.spec.whatwg.org/#childnode).

**Comment by ai** [comment]
Done by @ben-eb
