### ISSUE TITLE
Insert before shortcut

### ISSUE THREAD

**Issue by ai** [postcss/postcss#189]
Now we have a long API to insert node before some node:

``` js
one.parent.insertBefore(one, two);
```

We need something like:

``` js
one.before(two);
```

@MoOx @lydell what method name we should use?

**Comment by lydell** [comment]
+1 for .before just like [DOM spec](https://dom.spec.whatwg.org/#interface-childnode).

**Comment by ai** [comment]
@lydell nice.I forgot about DOM API as example.

Maybe we should join  to only one `node.remove()` as in DOM API #191

**Comment by MoOx** [comment]
I don't like a .before() since you already have a .before property.
We should stick with verbose and clear method names. Is one inserted before two or the opposite ?
No fucking idea :/

```
two.insertBefore(one)
```

This make more sense to me but I'm not a pro to design api.

**Comment by ai** [comment]
@MoOx I think you a right, I can find any user case to have a insert method in parent container, not in child node.

**Comment by ai** [comment]
@MoOx maybe we should rename `before`, `after` and `between`.

1. Names are little bit confused.
2. They are like a internal API. Most of plugin developer should not think about code style properties. So we should use short names for popular method (like `before(node)`) and long for unpopular (maybe `codeStyle.before`).

**Comment by jedmao** [comment]
:+1: for the more verbose method names like `insertBefore`. I think all method names should be verbs. `before`, `after` and `between` all go against this convention. Prefixing them all with `insert` adds clarity.

**Comment by ai** [comment]
I close it since we have no good name idea

**Comment by ai** [comment]
I decided to use DOM names. They are not verbs, but we can’t use `insertBefore` since it is used for different purpose.

**Comment by ai** [comment]
Done 1e232d1
