### ISSUE TITLE
warning while building my Next js application due to which not able to deploy on Vercel.

### ISSUE THREAD

**Issue by Ghufran496** [postcss/postcss#1896]
(node:10708) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at H:\DeployedFYP\fyp\node_modules\next\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by ai** [comment]
Update PostCSS and Node.js version
