### ISSUE TITLE
Get `Unexpected token 'export'` even the project type is already set to `module`

### ISSUE THREAD

**Issue by stackpan** [postcss/postcss#1899]
I have a problem today that causes my application failed to start
This is the error message:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /var/www/html): [Error] Loading PostCSS Plugin failed: Unexpected token 'export'

(@/var/www/html/postcss.config.js)
Error: Loading PostCSS Plugin failed: Unexpected token 'export'

(@/var/www/html/postcss.config.js)
    at load (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36333:11)
    at file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36358:16
    at Array.map (<anonymous>)
    at plugins (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36357:8)
    at processResult (file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36427:14)
    at file:///var/www/html/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36551:14]

Node.js v20.9.0
```

This happened when I run the project.

I already set my project `type` to `module` in my `package.json` like other solution i found in internet but still can't run.
```json
{
  "type": "module",
}
```

Additional information:
- NodeJS version: 20.9.0
- NPM version: 10.2.4
- PostCSS version: 8.4.31

**Comment by ai** [comment]
Seems like you run PostCSS on JS file (but PostCSS of course can process only CSS files).

Seems like something is broken in your Vite config and Vite send JS files to PostCSS.

You need to ask Vite community, we can’t fix it in PostCSS parser (since it is CSS-only parser).
