### ISSUE TITLE
Getting vulnerability in Postcss.

### ISSUE THREAD

**Issue by Devapraveen90** [postcss/postcss#1900]
Hi,
Currently I am fixing vulnerabilities in my project. While fixing vulnerabilities I am getting issue in Postcss it says moderate issue.
Could you please update this package, And please let me know. I am sharing the screen shot.

<img width="949" alt="image" src="https://github.com/postcss/postcss/assets/125740940/9adf009e-8b3d-4e26-83db-4dfc37970f73">

Thanks & Regards,
Praveen Kumar D.

**Comment by ai** [comment]
The package is already updated https://github.com/postcss/postcss/releases/tag/8.4.31 (on September 29)

It is you who need to update the `postcss` version in your lock file 
 (this is why you are getting this message, because you are using old version without a fix).
