### ISSUE TITLE
A research for generating PR checklists in Pull Request Template

### ISSUE THREAD

**Issue by chenkun1029** [postcss/postcss#1901]
Dear maintainers:
Our team is currently developing a tool for automatically generating PR checklists in Pull Request Template. The tool generates a set of PR rules based on the contribution guidelines in your project, which external contributors may be expected to adhere to. Below are the results of our generation:

**Test**: Use npm test.
**Documentation**:  Spelling check is passing
**Style**: Your changes match TypeScript styling rules.

Also, we suggest you add some checklist notes about **Branch**, **Title**, **Description**, **commit message**, **contributing** and **CLA** which are also important for submitting PRs according to our analysis.

We hope you and your team can provide feedback on our generated output.
Best regards.

**Comment by ai** [comment]
No, thanks.

I also think that it is spam since PostCSS PR history is obviously not about many PRs and checklists.
