### ISSUE TITLE
question/feature request(lint): “not modify” mode for linters

### ISSUE THREAD

**Issue by Kristinita** [postcss/postcss#1904]
### 1. Summary

I haven’t found what I need to do to prevent PostCSS linter plugins make changes to my source maps and EditorConfig settings, when I use linters as PostCSS plugins.

If it really isn’t possible to run PostCSS without modifying the files, I don’t understand why this was done, and why not give users the ability to normally run PostCSS plugins-linters like all other linters I know of.

### 2. MCVE

You can see this MCVE on the “[**SashaAppVeyorDebugging**](https://github.com/Kristinita/SashaAppVeyorDebugging/tree/KiraPostCSSLint)” branch of my GitHub demo repository and in the [**AppVeyor build**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/48721364) for it.

#### 2.1. Example CSS file

+ `KiraExampleCSS.css` with an already existing source map:

```css
h1:has(+ p) {
  margin-bottom: 0;
}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxlQUFjLEVBQWQiLCJmaWxlIjoiS2lyYUV4YW1wbGVDU1MuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiaDE6aGFzKCsgcClcblx0bWFyZ2luLWJvdHRvbSAwXG4iXX0= */

```

#### 2.2. Steps to reproduce

+ [**`appveyor.yml`**](https://github.com/Kristinita/SashaAppVeyorDebugging/blob/KiraPostCSSLint/appveyor.yml#L11):

```yaml
build_script:
- postcss KiraExampleCSS.css -u doiuse -o KiraPostCSS.css

test_script:
- more KiraExampleCSS.css
- more KiraPostCSS.css
- editorconfig-checker
```

#### 3.1. Desired behavior

Leave the `KiraPostCSS.css` file exactly the same as `KiraExampleCSS.css`, since doiuse is a linter and shouldn’t modify files. Solely the message:

```js
1       !!  :has() CSS relational pseudo-class not supported by: Firefox (115,119,120), Opera Mini (all), Firefox for Android (119), UC Browser for Android (15.5), QQ Browser (13.1), KaiOS Browser (2.5,3.0-3.1) (css-has) [doiuse]
```

#### 3.2. Current behavior

I get the same problems when I use [**grunt-postcss**](https://www.npmjs.com/package/@lodder/grunt-postcss).

##### 3.2.1. Problem 1 — source maps

PostCSS makes a modification to the source map that I don’t need:

+ [**`KiraExampleCSS.css` source map**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/48721364#L49):

```text
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxlQUFjLEVBQWQiLCJmaWxlIjoiS2lyYUV4YW1wbGVDU1MuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiaDE6aGFzKCsgcClcblx0bWFyZ2luLWJvdHRvbSAwXG4iXX0= */
```

+ [**Let’s decode it**](https://emn178.github.io/online-tools/base64_decode.html?input=eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxlQUFjLEVBQWQiLCJmaWxlIjoiS2lyYUV4YW1wbGVDU1MuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiaDE6aGFzKCsgcClcblx0bWFyZ2luLWJvdHRvbSAwXG4iXX0%3D):

```json
{
	"version": 3,
	"sources": ["../../stylus/components/KiraExampleCSS.styl"],
	"names": [],
	"mappings": "AAAA;EACC,eAAc,EAAd",
	"file": "KiraExampleCSS.css",
	"sourcesContent": ["h1:has(+ p)\n\tmargin-bottom 0\n"]
}

```

+ [**`KiraPostCSS.css` source map**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/48721364#L55):

```text
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiLCJLaXJhRXhhbXBsZUNTUy5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxnQkFBYztBQ0NmIiwiZmlsZSI6IktpcmFQb3N0Q1NTLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImgxOmhhcygrIHApXG5cdG1hcmdpbi1ib3R0b20gMFxuIiwiaDE6aGFzKCsgcCkge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuLyojIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKemIzVnlZMlZ6SWpwYklpNHVMeTR1TDNOMGVXeDFjeTlqYjIxd2IyNWxiblJ6TDB0cGNtRkZlR0Z0Y0d4bFExTlRMbk4wZVd3aVhTd2libUZ0WlhNaU9sdGRMQ0p0WVhCd2FXNW5jeUk2SWtGQlFVRTdSVUZEUXl4bFFVRmpMRVZCUVdRaUxDSm1hV3hsSWpvaVMybHlZVVY0WVcxd2JHVkRVMU11WTNOeklpd2ljMjkxY21ObGMwTnZiblJsYm5RaU9sc2lhREU2YUdGektDc2djQ2xjYmx4MGJXRnlaMmx1TFdKdmRIUnZiU0F3WEc0aVhYMD0gKi9cbiJdfQ== */
```

+ [**Let’s decode it**](https://emn178.github.io/online-tools/base64_decode.html?input=eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiLCJLaXJhRXhhbXBsZUNTUy5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxnQkFBYztBQ0NmIiwiZmlsZSI6IktpcmFQb3N0Q1NTLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImgxOmhhcygrIHApXG5cdG1hcmdpbi1ib3R0b20gMFxuIiwiaDE6aGFzKCsgcCkge1xuICBtYXJnaW4tYm90dG9tOiAwO1xufVxuLyojIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKemIzVnlZMlZ6SWpwYklpNHVMeTR1TDNOMGVXeDFjeTlqYjIxd2IyNWxiblJ6TDB0cGNtRkZlR0Z0Y0d4bFExTlRMbk4wZVd3aVhTd2libUZ0WlhNaU9sdGRMQ0p0WVhCd2FXNW5jeUk2SWtGQlFVRTdSVUZEUXl4bFFVRmpMRVZCUVdRaUxDSm1hV3hsSWpvaVMybHlZVVY0WVcxd2JHVkRVMU11WTNOeklpd2ljMjkxY21ObGMwTnZiblJsYm5RaU9sc2lhREU2YUdGektDc2djQ2xjYmx4MGJXRnlaMmx1TFdKdmRIUnZiU0F3WEc0aVhYMD0gKi9cbiJdfQ%3D%3D):

```json
{
	"version": 3,
	"sources": ["../../stylus/components/KiraExampleCSS.styl", "KiraExampleCSS.css"],
	"names": [],
	"mappings": "AAAA;EACC,gBAAc;ACCf",
	"file": "KiraPostCSS.css",
	"sourcesContent": ["h1:has(+ p)\n\tmargin-bottom 0\n", "h1:has(+ p) {\n  margin-bottom: 0;\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3N0eWx1cy9jb21wb25lbnRzL0tpcmFFeGFtcGxlQ1NTLnN0eWwiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDQyxlQUFjLEVBQWQiLCJmaWxlIjoiS2lyYUV4YW1wbGVDU1MuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiaDE6aGFzKCsgcClcblx0bWFyZ2luLWJvdHRvbSAwXG4iXX0= */\n"]
}

```

[**`--no-map` option**](https://github.com/postcss/postcss-cli#usage) option deletes the already existing source map rather than leaving it as it was before PostCSS was launched.

##### 3.2.2. Problem 2 — EditorConfig settings

[**editorconfig-checker**](https://editorconfig-checker.github.io/) — this is a linter that checks that project files match the user settings in the file [**`.editorconfig`**](https://editorconfig.org).

[**Result of running editorconfig-checker**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/builds/48721364#L56) for files `KiraExampleCSS.css` и `KiraPostCSS.css`

```js
editorconfig-checker
KiraPostCSS.css:
	Wrong line endings or no final newline
	2: Wrong indentation type(spaces instead of tabs)
KiraExampleCSS.css:
	2: Wrong indentation type(spaces instead of tabs)
3 errors found
```

`Wrong line endings or no final newline` — PostCSS removed the final newline from the file, which is required according to the `.editorconfig` rule.

#### 4.1. Linters don’t modify files

I have never seen a linter before that would forcefully modify files, and this couldn’t be changed in any way. Since [**PostCSS includes linter plugins**](https://github.com/postcss/postcss#linters), I think it would be nice for it to have a standard linters’ behavior — not modify files.

#### 4.2. Linters in the process of website development

During the first stage of my website development, I run tools that create and modify my project files. Linters, including [**doiuse**](https://github.com/anandthakker/doiuse#as-a-postcss-plugin) and [**stylelint**](https://stylelint.io/user-guide/postcss-plugin), which I run as PostCSS plugins, I run in the second stage, after all the files have been created and modified. I think this is the right approach, since any tools run after the linters (including those that fix PostCSS changes) can make mistakes that doiuse and stylelint may detect.

### 5. “not_modify” option

Given the above, I think it might be nice to have the PostCSS option `not_modify` (or `linter_mode`) with boolean `false` value by default. If `true`, PostCSS will not modify files.

### 6. Not helped

I couldn’t find on Google, [**PostCSS documentation**](https://postcss.org/) and this issue tracker what I can do to prevent PostCSS from modifying my files.

Thanks.

**Comment by ai** [comment]
I do not think you should use `grunt-postcss` or `postcss-cli` for linting. Those tools are to modify files.

You should use linter’s CLI (like `stylelint` has) or use PostCSS JS API and do no save changes to the file:

```js
postcss(plugins).process(css, { from }).then(result => {
  result.warnings //=> errors from linter
})
```
