### ISSUE TITLE
Vulnerability in Postcss despite update

### ISSUE THREAD

**Issue by tuhamworld** [postcss/postcss#1906]
Hello,

I am getting an issue regarding vulnerabilities in Postcss despite using the latest version of Postcss which is 8.4.32. Could you please look into it?

![postcss package](https://github.com/postcss/postcss/assets/52820977/2b7424ad-6cdd-4770-8c68-5812df176730)
![postcss error](https://github.com/postcss/postcss/assets/52820977/7fd55554-c3d1-4c64-b83b-be94992db1a6)

Thank you

**Comment by ai** [comment]
Yes, we know about that issue and we fixed it in 8.4.32. Please update to latest version.

Don’t worry, it is not very critical issue. Only a few companies will face it. If you compile your CSS during the website build and do not compile CSS from unknown users, you are not affected.

If you have PostCSS 7 in your system, you need to move to PostCSS 8. PostCSS 7 is very old and is not supported anymore.

Do you have any specific question?

**Comment by tuhamworld** [comment]
Thank you for the prompt response. 

Since it's not a critical issue, I am going to ignore the warning then, and also look at the options of PostCSS 8.

I have no further question again.
