### ISSUE TITLE
"Unexpected }" error when using comments in interpolation strings

### ISSUE THREAD

**Issue by rgehan** [postcss/postcss#1907]
Hi!

It seems `postcss` isn't able to correctly parse interpolation strings that contain comments (although that is perfectly valid TS/JS).

Here is a repo test case:
```ts
test('it does not fail with comments inside string interpolation', () => {
  not.throws(() => {
    parse('let Component = styled.div`color: ${textColor /* very good color */}`;')
  })
});
```

**Comment by ai** [comment]
It is not part of standard CSS syntax and PostCSS should not support it.

You can find on our website a guide of how to write custom syntax parser if you want to work with this syntax.

**Comment by rgehan** [comment]
Oh right, I misunderstood how `postcss-styled-syntax` is using `postcss`.

Sorry for the noise!
