### ISSUE TITLE
Is it correct that a `NoWorkResult` is returned when a sourcemap is requested?

### ISSUE THREAD

**Issue by romainmenke** [postcss/postcss#1911]
I don't know enough about sourcemaps to know what is correct here.

A `NoWorkResult` doesn't do any parsing, so it can not generate detailed sourcemaps.
Everything will be a single blob.

By contrast a `LazyResult` will have sourcemaps that have distinct parts for rules, at rules, declarations, ...

Is it a real world problem that `NoWorkResult` doesn't generate detailed sourcemaps that match `LazyResult`?

No parts were altered so just indicating that the entire blob matches the source seems fine.
But again, I don't know enough about sourcemaps to know what is correct.

**Comment by ai** [comment]
Yes, we have a special very fast 1-to-1 source map generation algorithm

https://github.com/postcss/postcss/blob/main/lib/no-work-result.js#L31C48-L40

> Is it a real world problem that NoWorkResult doesn't generate detailed sourcemaps that match LazyResult?

Why do you need small tokens in generated source map?

**Comment by romainmenke** [comment]
I don't know anything about sourcemaps, so I don't know if smaller tokens are useful.

If smaller tokens are **not** useful then:
- a `NoWorkResult` can have a sourcemap that is just one big blob
- a `NoWorkResult` sourcemap doesn't have to match the `LazyResult` sourcemap

**Comment by ai** [comment]
> I don't know anything about sourcemaps, so I don't know if smaller tokens are useful.

Sourcemap is a tool to map each symbol of source to each symbol of result. The chunks number is not important for this task in this case.

Anyway we can say that `0:8` in `out.css` is `0:8` in `in.css`.

`source-map-js` should handle this processing inside. You can process file by `NoWorkResult` (with a new file name) and open HTML page wioth this file in Chrome. DevTools should give you origin file with right line.

**Comment by romainmenke** [comment]
Check!

🙇
