### ISSUE TITLE
AtRule#nodes can be undefined

### ISSUE THREAD

**Issue by tim-we** [postcss/postcss#1920]
Parsing something like
```css
@layer a, b, c;
```
with `postcss` will result in an `AtRule` object without a `nodes` property. The TS type and the docs suggest that its always present (type `postcss.ChildNode[]`). So my question is, should it be
1. always populated, in this case with an empty array
2. the types (and docs) are inaccurate?

In any case I'm happy to provide PR to fix this, just let me know what it should be.

https://postcss.org/api/#atrule-nodes

**Comment by ai** [comment]
Let's update types. Please send PR

**Comment by ai** [comment]
Thanks. Released in 8.4.34.
