### ISSUE TITLE
[plugin:vite:css] [postcss] Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by Ssionn** [postcss/postcss#1925]
Having this issue with postcss. Anyone know how to fix this? 🤔 

<img width="983" alt="image" src="https://github.com/postcss/postcss/assets/90753599/ce0114b8-d502-414f-929c-9d5044a144b7">

**Comment by ai** [comment]
Dublicate of https://github.com/postcss/postcss/issues/1914
