### ISSUE TITLE
Insert methods should return new node

### ISSUE THREAD

**Issue by ai** [postcss/postcss#193]
It is important to use shortcuts API:

``` js
var rule = root.append({ selector: 'a' });
rule.append({ prop: 'color', value: 'black' })
```

**Comment by MoOx** [comment]
What if you append more than one node (I think we can, right)?
This will make the return of the function not really predictable.
Or it should always return a node list ? Or append should only accept one node ? (or we should get appendNode and appendNodes method ?

**Comment by ai** [comment]
Hm. Good questions. Maybe we should allow to send only `node`, not a array. What is a user case to send a array?

**Comment by MoOx** [comment]
Don't know, just askin question. `append` is just not verbose enough for me. Not clear enough.
I don't like jQuery like API that allows ton of different behavior from a single method :/

**Comment by MoOx** [comment]
If `.append()` only accept a node, so forget what I said on this thread :)

**Comment by ai** [comment]
@MoOx +1 about jQuery methods :).

I added `append(array)` behaviour for CSS concat tools:

```js
root1.append(root2.nodes)
```

But it is a rare case, instead of

```js
var rule = atrule.append({ selector: 'a' });
rule.append({ prop: 'color', value: 'black' });
```

So we can just remove array support from insert methods,

**Comment by MoOx** [comment]
Why not. And with es6 arrow func, will be short to replace appended array :)
