### ISSUE TITLE
PostCSS issues and Next.js

### ISSUE THREAD

**Issue by MrOxMasTer** [postcss/postcss#1931]
Problems starting with next.js@14.1.2-canary.4. 

./src/app/globals.css
Error evaluating Node.js code
Error: Failed to load external module C:\Users\Asus\Desktop\petProjects\shopco/./postcss.config.js: Error [ERRUNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [C:\Users\Asus\Desktop\petProjects\shopco.next\chunks[output]__next_transform_ad1f0f.js:1318:15] 
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js.loader.mjs:3:13) [C:\Users\Asus\Desktop\petProjects\shopco.next\chunks_0b8f1c._.js:11:13]

![image](https://github.com/postcss/postcss/assets/59291123/c3c851b3-12b6-403b-a1ce-46b8f0a406e8)
![image](https://github.com/postcss/postcss/assets/59291123/fb40ef7d-5c93-4351-ba97-13344016f340)

**Comment by MrOxMasTer** [comment]
Another bonus with "type": "module" I can't build a project. Even on version 14.1.2-canary.3.

src\app\layout.tsx
An error occurred in `next/font`.

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\postcss.config.js from C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js not supported.
Instead change the require of postcss.config.js in C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require-hook.js:65:28)
    at findConfig (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js:58:20)
    at async getPostCssPlugins (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\config\blocks\css\plugins.js:89:18)
    at async C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules\.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\config\blocks\css\index.js:124:36

![image](https://github.com/postcss/postcss/assets/59291123/e2cb267d-cab3-4ab8-9a54-1f25de5a207b)

**Comment by ai** [comment]
Show your PostCSS config

**Comment by MrOxMasTer** [comment]
ts config
![image](https://github.com/postcss/postcss/assets/59291123/c8e8ce05-7d0b-4d36-b3bb-6156ba6bf11e)ts config.

postCSS config
![image](https://github.com/postcss/postcss/assets/59291123/16cfb3fe-34d6-4deb-bac7-9739ec54e8d1)

**Comment by MrOxMasTer** [comment]
I also can't switch the post CSS config to the ts version. The project just stops seeing it, even though I explicitly specify the file in input ts.config, but I did something wrong here or did not understand
![image](https://github.com/postcss/postcss/assets/59291123/4993196b-704b-416e-ac8b-b8d52ba9f95f)

**Comment by ai** [comment]
Sorry, everything looks OK from PostCSS side and the error shows that it is an environment issue rather than PostCSS.

Ask in Next.js community.

**Comment by ayadi020** [comment]
node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:3733) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
