### ISSUE TITLE
the plugin is activated, but does not work (tailwindcss)

### ISSUE THREAD

**Issue by MrOxMasTer** [postcss/postcss#1943]
The plugin runs, but gives an error when compiling that the tailwindcss syntax (or rather my syntax)

I just added a new syntax that I am comfortable with and I added the plugin before tailwindcss, but it still fails on my syntax.

```js
// postcss.config.cjs
module.exports = {
  plugins: {
    // 'postcss-flexbugs-fixes': {},
    'postcss-tailwindcss-multiple-classes': {
      activate: 'Yes, he was activated',
    },
    'tailwindcss/nesting': {},
    tailwindcss: {},
    // 'postcss-preset-env': {
    //   autoprefixer: {
    //     flexbox: 'no-2009',
    //   },
    //   stage: 3,
    //   features: {
    //     'custom-properties': false,
    //     'nesting-rules': false
    //   },
    // },
    autoprefixer: {},
    // ...(process.env.NODE_ENV === 'production' ? { cssnano: {} } : {}),
  },
};
```

Despite the fact that the plugin works perfectly in the AST explorer display
![image](https://github.com/postcss/postcss/assets/59291123/8cb60e1d-5d65-47df-b813-2779e4cba854)
![image](https://github.com/postcss/postcss/assets/59291123/b94ea5be-e5ea-498c-b26c-f47dda38c1ae)

![image](https://github.com/postcss/postcss/assets/59291123/df29f49b-c0f2-4bc2-9555-8cbc3f9d26ac)

Error:
![image](https://github.com/postcss/postcss/assets/59291123/364f2fab-c9d8-4054-a655-ecd228040a29)
![image](https://github.com/postcss/postcss/assets/59291123/cad1af74-7f96-4771-b6b9-5298edaeecc1)

```css
  body {
    @apply mm:(bg-sunglow text-greenHaze);

    font-family: var(--font-satoshi);
  }
```

**Comment by ai** [comment]
Sorry, it is Tailwind issue, you need to report it there.

**Comment by adamwathan** [comment]
I think the issue here is that because of the visitor API, the plugins run in an unexpected order. If the OP’s plugin ran before Tailwind (as appears in the config) there would be no issue, but Tailwind is running first even though it doesn’t look like it.

**Comment by ai** [comment]
In this case you can try to replace `AtRule(atrule) {}` to:

```js
Once(root) {
 root.walkAtRules(atrule => {
   …
 })
}
```

**Comment by MrOxMasTer** [comment]
> I think the issue here is that because of the visitor API, the plugins run in an unexpected order. If the OP’s plugin ran before Tailwind (as appears in the config) there would be no issue, but Tailwind is running first even though it doesn’t look like it.

And how, for example, does "tailwind/nesting" start? It is specifically asked to be set earlier in the postcss configuration

**Comment by MrOxMasTer** [comment]
> In this case you can try to replace `AtRule(atrule) {}` to:
> 
> ```js
> Once(root) {
>  root.walkAtRules(atrule => {
>    …
>  })
> }
> ```

It really worked!
```js
module.exports = (opts = {}) => {

  console.log(`\n: ${opts.activate}\n`);

  return {
    postcssPlugin: 'postcss-tailwindcss-multiple-classes',
    Once(root) {
      root.walkAtRules(atrule => {
        if(atrule.name === 'apply') {
          atrule.params = findPseudo(atrule.params);
        }
      })
    },
    // AtRule: {
    //   		apply: (atrule) => {
    //         atrule.params = findPseudo(atrule.params);
    //       }
    // },
  };
};
```

**Comment by MrOxMasTer** [comment]
@ai so it turns out not to be a tailwindcss problem and I can close them?

**Comment by ai** [comment]
You can close the issue there.

It is another issue of Tailwind of using event API (without this API is will have conflicts with other event based plugins).
