### ISSUE TITLE
RFE: add ability to suppress "original.line and original.column are not numbers" message

### ISSUE THREAD

**Issue by kaiyoma** [postcss/postcss#1948]
The underlying issue has been discussed extensively here:

https://github.com/postcss/postcss/issues/1914
https://github.com/swagger-api/swagger-ui/issues/9946

Now when we start our Vite dev server, we see this annoying message:

```
  VITE v5.3.4  ready in 2762 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
```

We can't do anything here to address this - the problem is with the source map distributed by swagger-ui-react. It's unclear when (or if ever) they will fix this, so we're stuck with a confusing and vague warning that we can't do anything about. We don't find this warning helpful, so can we have a way to disable it?

Edit: also seeing this warning during Vite builds and Storybook builds.

**Comment by ai** [comment]
Disable source map (ask Vite how to do it). It will disable the warning.

**Comment by ai** [comment]
I am closing this because we already decided that we would not disable warnings, because the issue with swagger source maps is real.

It is unfair to ask us spend free time solving other project issue.

**Comment by kaiyoma** [comment]
> Disable source map (ask Vite how to do it). It will disable the warning.

Is there a way to disable only CSS source maps? We need to keep JS source maps enabled. I don't see any way to do this, in either the Vite options or the postcss options.

**Comment by ai** [comment]
You need to ask Vite community. I can help only with low-level PostCSS core API.

**Comment by kaiyoma** [comment]
> You need to ask Vite community. I can help only with low-level PostCSS core API.

Vite already supports passing a postcss config: https://vitejs.dev/config/shared-options.html#css-postcss

However, when I look through the postcss config docs (https://postcss.org/api/#sourcemapoptions), I don't see an obvious option for disabling source maps. Will setting one of these boolean options to `false` do the trick?

**Comment by ai** [comment]
`map: false` is exactly API to disable source map

**Comment by kaiyoma** [comment]
> `map: false` is exactly API to disable source map

@ai This doesn't work. If I set this option in my Vite config, I still see the same message on the console:

```
  VITE v5.3.4  ready in 2074 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
```

**Comment by ai** [comment]
Ask Vite community (I think they just override `postcssOps.map`)
