### ISSUE TITLE
Does markDirtyUp go in the wrong direction?

### ISSUE THREAD

**Issue by nex3** [postcss/postcss#1949]
The name `markDirtyUp` suggests that the function would mark nodes as dirty upwards in the tree, which is to say towards the root. However, the actual implementation marks nodes dirty *downwards*, towards the leaves:

https://github.com/postcss/postcss/blob/e0efb168c8a65b42ba10b787857cfa306ba9d48c/lib/container.js#L18-L25

Although this function isn't documented, I'm guessing its purpose is to track when a tree has been modified, in which case it would make sense to try to mark the whole tree as dirty when any part has been touched. And in fact, it looks like the only place that `node[isClean]` is actually read is on the root:

https://github.com/postcss/postcss/blob/e0efb168c8a65b42ba10b787857cfa306ba9d48c/lib/lazy-result.js#L270-L271

Is this a bug? Moreover, is it actually useful to mark any nodes _other than_ the root as dirty?

**Comment by ai** [comment]
> The name markDirtyUp suggests that the function would mark nodes as dirty upwards in the tree, which is to say towards the root

Fixed 53968d7a

> Is this a bug?

No. The function are you taking about is a different one: [`Node#markDirty()`](https://github.com/postcss/postcss/blob/main/lib/node.js#L156-L164)

`markDirtyUp` is using only in a single place
https://github.com/postcss/postcss/blob/main/lib/container.js#L216

We use `markDirtyUp` to mark dirty a subtree which you insert to other tree.

**Comment by ai** [comment]
If some plugin added a few nodes to AST, other plugin needs to process them

**Comment by nex3** [comment]
But how does this actually cause a plugin to process them, when the only node whose dirty state is actually checked in `lazy-result.js` is the root?

**Comment by ai** [comment]
We mark root as dirty by calling `node.markDirty()` in method which adds these nodes

https://github.com/postcss/postcss/blob/main/lib/container.js#L34
