### ISSUE TITLE
 PostCSS Plugins Site Offline [postcss.parts](https://www.postcss.parts/)

### ISSUE THREAD

**Issue by thierryc** [postcss/postcss#1954]
# Issue: PostCSS Plugins Site Offline

## Description:

The website for PostCSS plugins, [postcss.parts](https://www.postcss.parts/), appears to be offline and now displays a site parking page. 

## Steps to Reproduce:

- Visit the website: https://www.postcss.parts/
- Observe that the site displays a parking page instead of the intended content. (screenshot is attached)

## Related Information:

- PostCSS GitHub Repository for more information about the project.
- mxstbr/postcss.parts GitHub Repository for insights into the site’s development and potential updates or issues.

## Suggestions:

Investigate the status of postcss.parts and its hosting situation.
- Provide updates or alternative resources if the site is permanently offline.

## Suggestions:

- Investigate the status of [postcss.parts](https://www.postcss.parts/) and its hosting situation.
- Consider hosting the site under a subdomain of [postcss.org](https://postcss.org/) (e.g., plugins.postcss.org) to ensure its availability and integration with the main PostCSS website.
- Provide updates or alternative resources if the site is permanently offline.

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/6e481da6-eaa3-4df0-aec9-5e20ef995be0">

**Comment by ai** [comment]
It was not mine website. I will update links in docs, but do not want to take responsibility of other website because I already support to many projects

**Comment by ai** [comment]
Website and docs were updated
