### ISSUE TITLE
Source Input File

### ISSUE THREAD

**Issue by Harry5012** [postcss/postcss#1963]
_**###**_ Discussed in https://github.com/orgs/postcss/discussions/1933

<div type='discussions-op-text'>

<sup>Originally posted by **Ownedunkn** March 23, 2024</sup>
How do I get the source input file?
```
postcss [input.css] [OPTIONS] [-o|--output output.css] [--watch|-w]
```

In this case, how can I get the 

> **`input.css`</div>``**

**Comment by ai** [comment]
Hi. This repo is for PostCSS core. You need to open an issue in https://github.com/postcss/postcss-cli

**Comment by ai** [comment]
Very likely that you need to pass it to `--map` but I use Vite.

Also PostCSS can find input source map automatically if it has the same name with `.map` postfix.
