### ISSUE TITLE
Plugins interaction/order

### ISSUE THREAD

**Issue by Harry5012** [postcss/postcss#1964]
### Discussed in https://github.com/orgs/postcss/discussions/1929

<div type='discussions-op-text'>

<sup>Originally posted by **pciarach** March  1, 2024</sup>
Hi, we recently upgraded our PostCSS and plugins to version 8. The order of plugins in the configuration remained unchanged. However, we’ve noticed that some of them are executing in an unexpected sequence. Specifically, the affected plugins are `postcss-mixins` and `postcss-simple-vars`.

To pass multiple values as a single parameter, we define a variable and then pass it to a mixin (simplified example):

```
@define-mixin myMixin $properties, $timing {
  transition-property: $properties;
  transition-duration: $timing;
}

.selector {
  $props: background-color, border-color, color;
  @mixin myMixin $props, 400ms;
}
```

Previously, the mixin would be expanded first, and then the variable values would be substituted (which is the same order as in the configuration). However, now we observe that variables are substituted before resolving the mixin. As a result, the mixin interprets them as separate parameters, leading to unexpected CSS output:

```
.selector {
  transition-property: background-color;
  transition-duration: border-color;
}
```

It’s hard for me to tell whether this behavior is a bug in one of the plugins/PostCSS itself or maybe I'm missing something after the upgrade and there is a way to control this behavior and ensure that variables are not substituted too early. Alternatively, is there another approach to achieve our desired outcome?</div>

**Comment by ai** [comment]
In PostCSS 8 there is no order anymore since all plugins works “in parallel”.

The problem is happening when you mix PostCSS 7 and PostCSS 8 plugins. In this case PostCSS 8 plugins runs before PostCSS 8.

Maybe we have a bug in `postcss-mixins` (but it should work). Double-check that you updated plugins to the latest version and if yes, please open a issue in `postcss-mixins` repo.
