### ISSUE TITLE
build error after upgrading to 8.4.47 (ES Modules vs CommonJS)

### ISSUE THREAD

**Issue by szamanr** [postcss/postcss#1972]
in my next.js app deployed to vercel, i use postcss v8.4.34 with tailwindcss v3.4.13, i also use nanoid v5.0.7. everything works fine on this version, but when i try to upgrade postcss to the latest version (v8.4.47), i get a build error:

```
> Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/nanoid/non-secure/index.js from /vercel/path0/node_modules/postcss/lib/input.js not supported.
Instead change the require of index.js in /vercel/path0/node_modules/postcss/lib/input.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (/vercel/path0/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/vercel/path0/node_modules/postcss/lib/input.js:3:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

my app isn't using CommonJS and my package.json has `"type": "module",`, not sure if that' relevant.

**Comment by ai** [comment]
In PostCSS we use NanoID 3.x which is CommonJS.

Seems like something is broken in your build system which force PostCSS to use NanoID 5.x.

**Comment by szamanr** [comment]
thanks, are there plans to switch to the latest nanoid in a future postcss version?

i should mention i use bun, perhaps that's causing the issue, together with the fact that i include nanoid directly. i will check if people run into similar issues using bun.

**Comment by szamanr** [comment]
PS. did anything related to how nanoid is used changed in between the 2 versions i mentioned? because it's strange that it only started failing after a patch upgrade.

**Comment by ai** [comment]
> thanks, are there plans to switch to the latest nanoid in a future postcss version?

No. The latest version of Nano ID uses only ESM which is not compatible with CJS.

We will move to NanoID 5 only in next major release when we will move to ESM too.
