### ISSUE TITLE
Add parsing support for `$schema`

### ISSUE THREAD

**Issue by khinshankhan** [postcss/postcss#1973]
When I add the key value pair `"$schema": "https://json.schemastore.org/postcssrc.json"` to my `postcss.config.json` I get the warning

```
Warning: Your PostCSS configuration defines a field which is not supported (`$schema`). Please remove this configuration value.
```

The schema lets various editors leverage lsp to an extent to ensure the format is done properly (view `JSON schemas and settings` in https://code.visualstudio.com/docs/languages/json).

This isn't a priority since we can configure it as an editor setting matching filename.

Apologies in advance if the issue wasn't named properly :upside_down_face:

**Comment by ai** [comment]
Seems like this warning is going from Next.js or webpack, you need to create issue there.

In `postcss-load-config` we do not validate every key of config (just ignoring unknown).

**Comment by khinshankhan** [comment]
I'm using nextjs so that's fair. Thanks!
