### ISSUE TITLE
v5.2.18 has been removed from npm

### ISSUE THREAD

**Issue by ajberry** [postcss/postcss#1977]
Hi All, 

Got a strange issue yesterday where my Vue.js project no longer builds. It seems that we use the svg-baker package which has a dependency on v 5.2.18 of postcss, but this is no longer available in the upstream? 

Can someone clarify what has happened to this version? I can see 5.2.17 is available, but 5.2.18 isnt?

**Comment by ai** [comment]
Hm, strange.

We have 5.2.18 in [`ChangeLog.md`](https://github.com/postcss/postcss/blob/main/CHANGELOG.md), but not in [GitHub Releases](https://github.com/postcss/postcss/releases?page=17) and [npm releases](https://www.npmjs.com/package/postcss?activeTab=versions).

Honestly, it was 2017 (7 years ago), I do not remember what happened.

But recently we defiantly do not remove anything. Maybe it was npm?

Anyway, we do not support 5.x, and I am not planning to investigate or fix it.

**Comment by ajberry** [comment]
I appreciate it's not worth fixing, I was just trying to work out how/why this has happened. Thanks for the reply
