### ISSUE TITLE
Does node.removeSelf() can affect .before on the next sibling ?

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#198]
Is this an know possible side effect ?

I remove a node, and the node right after got its "before" value removed.

**Comment by ai** [comment]
Yeap, when you remove first child from Root https://github.com/postcss/postcss/blob/master/lib/root.js#L21

**Comment by ai** [comment]
BTW, I answers faster in gitte

**Comment by MoOx** [comment]
I understand you might want to do that, but with an argument or something... I just loose some hours of debug to find this.

I am really sad to see that postcss api is doing to much magic things by default. Manipulating an AST is supposed to be low level api, not magic crazy stuff that can affect an entire ast.

**Comment by MoOx** [comment]
Too much magic 💥

**Comment by ai** [comment]
My idea of code style magic is that code style should be hidden for plugin developer. What you try to debug? Why you even think about `before`, because by PostCSS ideology you should not know about this property? :)

**Comment by MoOx** [comment]
I do need to handle that since I am doing postcss-import. And if I don't use .before, I get non logic result.
move*, removeSelf, insertBefore all make unexpected results... (And this bug #184).

So I stopping using the api and go low level by manipulating array items. And it makes me sad. But right now, no other choice to avoid some weird behaviors.

**Comment by MoOx** [comment]
I am a a plugin developer, and I need to control output, so before after and shit :)

**Comment by ai** [comment]
Hm. [postcss-nested](https://github.com/postcss/postcss-nested/blob/master/index.js) works without manipulations with `before`.

**Comment by ai** [comment]
Maybe you have a idea right now, what code style API you want? What do you do with `before` right now?

**Comment by MoOx** [comment]
I am replacing a `@import` by the content of the file. It simple, in theory.
So I have to concat the 2 before property to respect whitespace and new lines:

a.css
```css
a{}
```

b.css
```css




b{}
```


```css
@import "a.css";


@import "b.css";
```

should give

```css
a{}





b{}
```

Also some are replaced (local import), some are moved to the top, and when I move a node, I detach it and reattach into the new location. Using removeSelf() affect before of the next sibling and that's totally unexpected.
I can't use move, insert or any method supposed to be an helper because they end up by cloning stuff, and so loosing original code style, and even hacks #184 (so weird to consider that as code style, it's just not...). So I must play with array and manually update before prop.

**Comment by MoOx** [comment]
Btw, it's also very hard to use manipulate array with each* methods because they execute callback while they are looping. So it's hard to play with mutable everywhere.

I think instead, you should collect * type (atrule, decl etc) in a new array, then loop on this one instead. 

So you don't have to maintain some indexes and original ast can be modified without breaking the current loop. Codebase will be reduced with this approch.

So hard for me to make a simple postcss-import codebase with current api behavior, and without it's not fun at all either cause I really can't use any of the api or I start to get "unsynced" behaviors :(

**Comment by ai** [comment]
Hm. You suggest to clone children array and they iterate it without worry about children changes.

But we willhave unexpected behaviour in this case too:

```js
rule.each(function (decl) {
    // Expecting only one iteration
    rule.removeAll();
});
```

Can you show a example what a problem with `each*` you have right now?

**Comment by MoOx** [comment]
Who is doing that ?

Anyway if I start a loop, I don't want it to be dynamic. I start a loop on a given state, not on a dynamic state that can affect my loop itself.

Right now, using simply eachAtRule and detaching some node, change the loop itself and I loose some iteration on some "non iterated on" items.
So I end up with this to avoid unexpected dynamic side effects

```js
  var imports = []
  styles.eachAtRule("import", function checkAtRule(atRule) {imports.push(atRule)})
  
  // here i know "imports" will not change
  imports.forEach(function(atRule) {
    // ...
  })
```

**Comment by ai** [comment]
For example, `forEach` behaviour is much closer to the current `for*`. I think that most native behaviour is like:

```js
for ( var current = parent.first; current; current = current.next() )
```

Can you show me a example when you loose some iteration?

**Comment by MoOx** [comment]
Check this commit https://github.com/postcss/postcss-import/commit/e985ca694a51ce88747b4e724de3bdcbc495c857

Then here, https://github.com/postcss/postcss-import/blob/master/index.js#L81-L82 just use a simple loop instead of 2. Then check what append when you run test (you will understand pretty easily).
