### ISSUE TITLE
Code style properties refactoring

### ISSUE THREAD

**Issue by ai** [postcss/postcss#199]
1. Rename properties to `codeStyle.before`, etc.
2. Do not clean code style properties on clone.
3. Change code style in insert methods with control  option.
4. Do not remove hacks in insert methods.

/cc @MoOx

**Comment by MoOx** [comment]
It not just code style. You should call that `.whitespace.*` or something. Or leave it as is cause it can contain hack like * or _ am i right ?

**Comment by MoOx** [comment]
Also you should offer the ability to normalize but not by default. If someone want to do a 'normalize' he can do `root.normalize()` right ?

**Comment by ai** [comment]
Hm. Special method for fill spaces is a nice idea.

**Comment by MoOx** [comment]
I mean that calling that codeStyle sound not a good idea at all. New lines and indentation are not just "style". In a way, it can be an important part of a node, depending on user pref and plugins objectives.

**Comment by ai** [comment]
Hm. But this properties contains not only whitespaces too :-). Maybe .symbols?

**Comment by MoOx** [comment]
Why do you want to move this ? What the purpose of this change ?

**Comment by ai** [comment]
1. To free `before` and `after` names for insert methods.
2. Current names is little confused. Even `whitespaces.before` is much clear.

**Comment by ben-eb** [comment]
1. Not a fan of calling this `codeStyle`. Perhaps we need clearer definitions on what ends up in these properties - you can't just change `decl.before` to `decl.spaces.before` because it might contain special characters.
2. Would really appreciate an interim solution to `clone`. I think the current behaviour is unintuitive; you don't expect a clone of `h1{color:blue}` to be `h1 { color: blue }`. I propose `clone({}, true)` as an interim API, although I don't much like it I prefer it to `clone({}, {keepCodeStyle: true})`. I need this to be able to compared a CSS transformation's length to a clone's length and I cannot do so if `String(node)` is not exactly the same for both nodes.

**Comment by ai** [comment]
What do you think about `raw` name for code style data?

* `decl.raw.before`
* `decl.raw.between` (not only whitespaces here)
* also we can put raw-values (before we was cleaned them from comments) `node.raw.value`

**Comment by davidtheclark** [comment]
How about "punctuation"? That's what its contents always are, right? --- spaces, newlines, commas, colons?

**Comment by ben-eb** [comment]
It also can contain asterisks, underscores etc, to accommodate for old IE hacks. Raw seems fine to me.

**Comment by MoOx** [comment]
> Raw seems fine to me.
+1

**Comment by ai** [comment]
OK. I will add `.raw` in 4.2 with deprreacted messages in old getters/setters.

**Comment by ai** [comment]
OK. I will add `.raw` in 4.2 with deprreacted messages in old getters/setters.

**Comment by ben-eb** [comment]
@ai We should also look at moving other values from `prop` into `before`. For instance, `!` ends up in `prop` (like `!color: red`).

**Comment by ai** [comment]
@ben-eb most of symbols already moved to `before`. If I miss someone, it is a bug, so we can release a fix in 4.1.14.

**Comment by ai** [comment]
Code style properties was moved to `Node#raw` in 4.2 branch https://github.com/postcss/postcss/commit/54cb6f4415f8055dfff8975709cf408cfb46397b

There are a aliases for old properties with depreacted warnings.

**Comment by MoOx** [comment]
Are the warnings going to be printed just once this time ? :)

**Comment by ai** [comment]
@MoOx of course :-)

**Comment by faergeek** [comment]
Would be cool to have option for default styles overriding and may be even possibility to enforce it.
I think it shouldn't be too hard, but then PostCSS alone could be used as a beautifier.
If it doesn't break PostCSS' philosophy, of course.

**Comment by ai** [comment]
Refactoring finished and will be released in 6.0
