### ISSUE TITLE
"pnpm install" failing with ERR_PNPM_FETCH_304 on AWS CodeBuild, works fine locally

### ISSUE THREAD

**Issue by SanskarDahiya** [postcss/postcss#1993]
I’m facing an issue where `pnpm install` keeps failing on AWS CodeBuild with errors like:

<pre>
[Container] 2024/12/17 14:35:11.133098 Running command pnpm install --no-frozen-lockfile --no-cache --loglevel verbose
Scope: all 9 workspace projects
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +2797
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2797, reused 0, downloaded 34, added 30
Progress: resolved 2797, reused 0, downloaded 142, added 144
Progress: resolved 2797, reused 0, downloaded 210, added 216
Progress: resolved 2797, reused 0, downloaded 319, added 325
·WARN· GET https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz error (ERR_PNPM_FETCH_304). Will retry in 10 seconds. 2 retries left.
Progress: resolved 2797, reused 0, downloaded 452, added 459
Progress: resolved 2797, reused 0, downloaded 544, added 557
Progress: resolved 2797, reused 0, downloaded 637, added 651
Progress: resolved 2797, reused 0, downloaded 700, added 722
Progress: resolved 2797, reused 0, downloaded 803, added 825
Progress: resolved 2797, reused 0, downloaded 929, added 950
Progress: resolved 2797, reused 0, downloaded 1073, added 1094
Progress: resolved 2797, reused 0, downloaded 1143, added 1176
Progress: resolved 2797, reused 0, downloaded 1219, added 1249
Progress: resolved 2797, reused 0, downloaded 1344, added 1388
·WARN· GET https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz error (ERR_PNPM_FETCH_304). Will retry in 1 minute. 1 retries left.
Progress: resolved 2797, reused 0, downloaded 1486, added 1533
·WARN· GET https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz error (ERR_PNPM_FETCH_304). Will retry in 10 seconds. 2 retries left.
·WARN· GET https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz error (ERR_PNPM_FETCH_304). Will retry in 10 seconds. 2 retries left.
·WARN· GET https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz error (ERR_PNPM_FETCH_304). Will retry in 10 seconds. 2 retries left.
Progress: resolved 2797, reused 0, downloaded 1695, added 1736
Progress: resolved 2797, reused 0, downloaded 1913, added 1966
Progress: resolved 2797, reused 0, downloaded 2146, added 2200
Progress: resolved 2797, reused 0, downloaded 2255, added 2309
Progress: resolved 2797, reused 0, downloaded 2295, added 2346
Progress: resolved 2797, reused 0, downloaded 2349, added 2404
Progress: resolved 2797, reused 0, downloaded 2394, added 2449
Progress: resolved 2797, reused 0, downloaded 2463, added 2517
Progress: resolved 2797, reused 0, downloaded 2488, added 2537
·WARN· GET https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz error (ERR_PNPM_FETCH_304). Will retry in 1 minute. 1 retries left.
Progress: resolved 2797, reused 0, downloaded 2528, added 2585
·WARN· GET https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz error (ERR_PNPM_FETCH_304). Will retry in 1 minute. 1 retries left.
·WARN· GET https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz error (ERR_PNPM_FETCH_304). Will retry in 1 minute. 1 retries left.
Progress: resolved 2797, reused 0, downloaded 2634, added 2691
Progress: resolved 2797, reused 0, downloaded 2711, added 2762
Progress: resolved 2797, reused 0, downloaded 2730, added 2791
Progress: resolved 2797, reused 0, downloaded 2731, added 2792
Progress: resolved 2797, reused 0, downloaded 2732, added 2793
·ERR_PNPM_FETCH_304· GET https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz: Not Modified - 304

[Container] 2024/12/17 14:36:26.503731 Command did not exit successfully pnpm install --no-frozen-lockfile --no-cache --loglevel verbose exit status 1
[Container] 2024/12/17 14:36:26.508142 Phase complete: BUILD State: FAILED
[Container] 2024/12/17 14:36:26.508156 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pnpm install --no-frozen-lockfile --no-cache --loglevel verbose. Reason: exit status 1
</pre>
**Error:** GET https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz error (ERR_PNPM_FETCH_304)
Locally, the command pnpm install runs without issues. 

I’ve tried multiple debugging steps locally and on CodeBuild like:

1. Cleared PNPM cache
2. Removed node_modules and lockfile
3. Tried forcing installation
4. Disabled caching
5. Despite all of this, the issue only occurs on AWS CodeBuild.

**Environment:**
**Locally**: pnpm install works fine
**AWS CodeBuild**: Fails consistently
**Node.js Version**: v18.15.0
**PNPM Version**: v8.13.1, Also tried with 9.15.0
**AWS CodeBuild Environment**: aws/codebuild/standard:7.0-23.04.13 (Linux container)

**Expected Behavior:**
`pnpm install` should work successfully on AWS CodeBuild, as it does locally.

**Actual Behavior:**
It fails during the installation process, throwing **ERR_PNPM_FETCH_304** repeatedly, despite retries.

**Question:**
What could be causing `pnpm install` to fail only on AWS CodeBuild, and how can I resolve this issue?

**Comment by ai** [comment]
It is a problem with your environment, not with postcss
