### ISSUE TITLE
Plugin categories

### ISSUE THREAD

**Issue by ai** [postcss/postcss#208]
We has many plugins right now. And we need helps developers to select right plugins.

I think we should group plugins by categories in README.md list.

@davidtheclark @MoOx @yisibl @lydell @hail2u @anandthakker what categories we need?

**Comment by davidtheclark** [comment]
Here are some categories I can imagine using. I'm just throwing out anything I can think of --- just to get the ball rolling --- and I'm not listing all the plugins as examples, just enough to get the idea across:

Transformation (all the plugins that take transform input css)
Transpilation (all the cssnext stuff, autoprefixer -- most)
Language extension (for non-transpilation stuff like mixins and extends)
Optimization (single-charset, data-packer, mqpacker, minifiers, import, bye-bye)
Shortcuts (easings, webp, size)
Special cases (dumb name -- rtlcss, epub)
Analysis (linters, list-selectors, css3modernizr --- not many, so no further subcategories needed yet)
What do you think? Ideas anyone?

**Comment by MoOx** [comment]
Transformation & transpilation are the same things http://en.wikipedia.org/wiki/Source-to-source_compiler
You should use have instead a _plugins_ and a _tools_ sections under transformation.
cssnext & autoprefixer are tools for end user, ready to use, simple api.
plugins on the other side, need a more (relative) complicated usage.

**Comment by ai** [comment]
@MoOx unfortunately, Tool/Plugin separation doesn't work right now. It based not on the plugin function, but on plugin branding.

Also, if user came to PostCSS docs it doesn't care for end-user API like `autoprefixer.process`. User comes to plugin section to select a plugins with nice functions.

**Comment by davidtheclark** [comment]
If a transpiler "takes the source code of a programming language as its input and outputs the source code into another programming language", isn't that a subset of "transformation", since you could "transform" syntax within a single language? Well, it's a pedantic distinction, and maybe there is some better word or phrase for what I meant by "transpilation". Or we could just not have the "transformation" super-category.

I agree that the plugin/tool distinction doesn't quite work, especially when things that can be used as standalone "tools", like cssnext, Autoprefixer, and list-selectors, might also be usable as "plugins" in the same way as other non-standalone "plugins".

**Comment by ai** [comment]
Maybe we should add special CSS4 transpiliers section? And other special section for Autoprefixer, CSS Grace and postcss-epub (But I have no idea how to names it).

**Comment by ai** [comment]
`webp` should be in Optimization section too.

**Comment by ai** [comment]
For other cases I like @davidtheclark categories. @MoOx maybe you want to add some sections?

**Comment by MoOx** [comment]
- Transformation (read + write)
    - Fallbacks (cssnext, autoprefixer, and plugins for not implemented w3c  transformations...)
    - Language extension (for non-transpilation stuff like mixins and extends)
    - Optimization (single-charset, data-packer, mqpacker, minifiers, import, bye-bye)
    - Shortcuts (easings, webp, size)
    - Special cases (dumb name -- rtlcss, epub)
- Analysis (read only)

**Comment by ai** [comment]
I think we should have flat structure here, because anyway nobody will see difference between `h3` and `h4` in README. So:

* W3C Draft Transpilers (cssnext plugins)
* Fallbacks (css grace, autoprefixer, epub)
* Language extension (for non-transpilation stuff like mixins and extends)
* Optimization (single-charset, data-packer, mqpacker, minifiers, import, bye-bye)
* Shortcuts (easings, webp, size)
* Other (rtlcss)
* Analysis (read only)

**Comment by MoOx** [comment]
Using the words "w3c draft" is kind of outdated already. For example Firefox already have custom properties... cssnext is like Autoprefixer for some css features and use (like Autoprefixer) a `browsers` option to enable/disable features if no need to transpile).
In a way, It's all about fallbacks. I just see cssnext has an autoprefixer on steroid :)

**Comment by ai** [comment]
I want to mark plugins by W3C draft by special category, because many people love them more :). In other case epub is like a Autoprefixer and cssnext and cssgrace is very different in my case. So “W3C draft” is mean that there is spec and plugin doesn’t is realize this spec and have all benefits from spec-plugins. Maybe we can rename spec-plugins category?

Also right now “Transpilers”/“Fallback” is too long. Some split will be useful. Maybe we can split it in other way?

**Comment by ai** [comment]
Maybe “W3C Spec Transpiliers”?

**Comment by MoOx** [comment]
Autoprefixer and cssnext have the exact same goal, so they should belong in the same category, even if cssnext include Autoprefixer :)

What about "W3C CSS 4+ transpilers"

**Comment by ai** [comment]
“W3C CSS 4+ transpilers” is better.


Do you remember, that cssnext intself is in other “Plugin Packs” section? “W3C CSS 4+ transpilers” will include only cssnext’s subplugins.

**Comment by MoOx** [comment]
lgtm

**Comment by ai** [comment]
Nice. I will make it today ot tomorrow.

**Comment by davidtheclark** [comment]
I think the W3C CSS4+ Transpilers section will be very long, yes, but that is because those plugins all do the same essential function --- it makes sense to have them in one category together. If we really wanted to split that out, though, maybe they could be split according to which W3C spec they relate to, e.g. Custom Properties, Media Queries, Colors, Extensions?

**Comment by MoOx** [comment]
I think we should KISS for now.

**Comment by ai** [comment]
@davidtheclark I think “W3C CSS4+ Transpilers” is enough right now :).

**Comment by davidtheclark** [comment]
Sounds good to me.

**Comment by iamvdo** [comment]
You should really stop using CSS4. There is no such thing as CSS4.
http://www.xanthir.com/b4Ko0

There's just many modules, each at a different level. Level 4 for stuff that already exists in level 3, Level 1 or 2 instead. For example, CSS Custom Properties is in Level 1.

In addition, many of these plugins does not work as the spec defines them. It is just inspired by W3C draft, not real implementation.

**Comment by ai** [comment]
“Future CSS Transpilers”?

@iamvdo maybe yyou can suggest some better category name?

**Comment by iamvdo** [comment]
Sounds better for me. 
I never liked the word transpiler, but don't ask me why ;)

**Comment by lydell** [comment]
I agree that “future” is better than “CSS4”. Much more … _future_-proof :)

**Comment by MoOx** [comment]
I know there is not css 4. I just found that's an easy way to communicate the idea of "future proof CSS based on new specs" in 4 letters.

Anyway, "Future CSS syntax" lgtm.

**Comment by davidtheclark** [comment]
@MoOx when you say "igtm" do you mean "It's greek to me." (i.e. I don't understand it, it's nonsensical) or "It's GOOD to me."? I'm not familiar with the abbreviation :)

**Comment by MoOx** [comment]
Lgtm: looks good to me :)

**Comment by ai** [comment]
Done https://github.com/postcss/postcss#plugins

**Comment by MoOx** [comment]
maybe postcss-* plugins should be on top of the other, the current state look weird (even if i understand it strictly alpha sorted)

**Comment by ai** [comment]
@MoOx you suggest to make a exclusion for `postcss-` plugins?

**Comment by MoOx** [comment]
exception*, yes. Place before postcss-* plugin (to encourage postcss-* usage) and then the others.

**Comment by ai** [comment]
Does it fair? Or you suggest it to promoto good-named plugins?

**Comment by MoOx** [comment]
We should encourage postcss-* prefix. By placing postcss-* first, we encourage postcss-* usage & people are most likely to create plugins prefixed too.

It's weird to read non prefixed, then prefixed, then non prefixed again. But maybe it's just me :)

**Comment by ai** [comment]
@MoOx done

**Comment by MoOx** [comment]
Looks better :D

**Comment by lydell** [comment]
Great!
