### ISSUE TITLE
Node 12.0 randome CSS Syntax errors

### ISSUE THREAD

**Issue by albertorestifo** [postcss/postcss#213]
Using Autoprefixer, through `gulp-autoprefixer`, sometimes a CSS Syntax Error is generated, but the CSS in question is without errors.

Until now, I got two errors:
 - Unclosed quote
 - `@import` must end with `;`

In both scenario, just re-running the gulp task solved the issue.

Unable to replicate with costance

**Comment by albertorestifo** [comment]
Forgot to mention system informations:

Node 0.12, OSX 10.10.2

With Node 0.10 it was working fine

**Comment by ai** [comment]
There is no new error reports and Travis CI doesn’t throw any syntax errors. I think this issue goes from some environment issues.
