### ISSUE TITLE
Globbing import and data-structure loop example?

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss#218]
I'm testing postCSS at present (via Gulp) and much of what I see, I like. :+1: 

My JS/node abilities are 'novice' so my apologies if some of my questions seem infantile!

However, there are a couple of things I am wondering about. Could anyone shed some light?

# Globbing
Firstly, globbing. Is there currently a facility to 'glob' import files with postCSS:

[in styles.css]
`@import components/**/*.css`

I tend to have lots of partial files (using Sass currently); it's one of the best things Sass brings to the table for me. I'd like the ability to process/combine lots of individual 'partial' CSS files into one without listing out each one in an @import statement (which https://github.com/postcss/postcss-import already allows). Only Ruby Sass has this at present and it's very convenient.

# Data structures and looping
Is there any inherent capability to define and loop through a data structure? I'm talking about this kind of thing: http://benfrain.com/looping-data-map-libsass-3-02/. If there is nothing specific plugin wise, could anyone explain how this could be achieved using a JS object and JS loop in the 'source' CSS? (@MoOx has detailed this partially already here: https://github.com/cssnext/cssnext/issues/60) Or perhaps philosophically how this might be approached with postCSS? 

Thanks very much for any insight you can offer.

**Comment by MoOx** [comment]
for the glob thing, an issue is already open https://github.com/postcss/postcss-import/issues/8

**Comment by ai** [comment]
Main problems of Sass was that you mix programming language and styles. It is like a PHP templates, when you mix HTML and PHP. We avoid this mix in PostCSS and this is a source of out benefits. So there will be no data structures in PostCSS or we will have all problems of Sass.

I have some ideas about looping but I have no dicition about plugin API. So your user case will be ver important for me.

For what user cases you need looping?

**Comment by benfrain** [comment]
@ai in fairness looping it is not an everyday occurence. However, when needed it has been most welcome: As an example, I was given over 150 product categories (as a JSON file), each with its own background-color, border-top color and border-bottom color. I needed to create a class for each with the relevant values. That was easy to solve with Sass and I have concern about how I would solve the same problem if I migrated to postCSS (I documented that one fully here: http://benfrain.com/using-lists-with-maps-in-sass-3-3/).

That is not something I would want to do by hand! 

One thought off the top of my head would be some 'parse-as-js' delimiter so that a block of JS could be written inside delimited characters in the CSS and this would be parsed as JS and written back into the processed CSS at that point (obviously I have no idea how to implement that but it would provide a lot of author freedom ;)) If the delimited section was itself within CSS comments it would retain the integrity of the file remaining parseable CSS.

**Comment by ai** [comment]
@benfrain products JSON is a good example of PostCSS power. You should not keep this code in CSS. Just create custom PostCSS plugin, that will get products JSON and will add CSS for them.

Code will be like this:

```js
var postcss = require('postcss');

var products = require('data/products.json');

module.exports = function (css) {
    for ( name in products ) {
        var rule = postcss.rule({ selector: '.product.is-' + name });
        rule.append({ prop: 'background', value: 'url(' + name + '.png)' });
        css.append(rule);
    }
};
```

**Comment by ai** [comment]
Maybe [postcss-mixins](https://github.com/postcss/postcss-mixins) will be useful for you. It contains object API like:

```js
module.exports = {
    'product.is-one': {
        'background: 'url(one.png)'
    }
}
```

**Comment by benfrain** [comment]
@ai - yep that example is very useful and would certainly solve the problem for me. :+1: 

I don't actually need to at this point but I am curious, would there be a way of defining which point in the CSS those rules would be appended?

**Comment by ai** [comment]
I think about something like

```css
@loop $i 1 12 {
    &:nth-child($i) {
        transition-delay: calc($i * 100ms)
    }
}
```

to make [animations like this](https://amplifr.com/en/). But it will not be like Sass loops, because it is only shortcut, not a real programm loop.
