### ISSUE TITLE
Beginner question on custom plugin definition/usage

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss#219]
I'm trying to port (and document) how to convert a large Sass codebase to PostCSS. Off the back of this thread: https://github.com/postcss/postcss/issues/218 it seems I have a viable way of working with existing data structures. However, as a JS/node novice I'm struggling with some basic issues with getting a custom plugin to pass the results back (sorry, wrong terminology I know) into the processed CSS.

I'm trying to make use of the `dataloop` function defined in my Gulpfile below. I get no error messages but I am not getting any rules appended to the output CSS either.

I'm reading through the API docs: https://github.com/postcss/postcss/blob/master/API.md but I readily admit some of it is beyond my humble mind :)

I have the following gulp file:

````js
var postcss = require('gulp-postcss');
var simplevars = require('postcss-simple-vars');
var autoprefixer = require('autoprefixer-core');
var mqpacker = require('css-mqpacker');
var csswring = require('csswring');
var nestedcss = require('postcss-nested');

var categories = require('./data/cat-colors.js');

var dataloop = module.exports = function (css) {
	for ( var category in categories ) {
		var borderTop = categories[category][0];
		var borderBottom = categories[category][1];
		var rule = postcss.rule({ selector: '.cat-' + category });
		rule.append({ prop: 'border-top', value: '1px solid ' + borderTop });
		css.append(rule);
	}
};

gulp.task('css', function () {
	var processors = [
		autoprefixer({browsers: ['last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4']}),
		simplevars,
		nestedcss,
		dataloop
	];
	return gulp.src('./preCSS/*.css')
		.pipe(postcss(processors))
		// .pipe(postcss(processors).on('error', gutil.log))
		.pipe(gulp.dest('./dest'));
});
````

And here is the `data/cat-colors.js` file:

````js
var colourList = {
    "1"  : ["#000000", "#000011"], 
    "2"  : ["#000011", "#000022"], 
    "3"  : ["#000022", "#000033"], 
    "4"  : ["#000033", "#000044"], 
    "7"  : ["#000044", "#000055"], 
    "8"  : ["#000055", "#000066"], 
    "9"  : ["#000066", "#000077"], 
    "10" : ["#000077", "#000088"],
};
````

My expected output at the end of the other rules would be:

```css
.cat-1 {
    border-top: 1px solid #000000;
}
.cat-2 {
   border-top: 1px solid #000011;
}
etc
```

Could someone explain what I'm doing wrong here to get these rules written into the output CSS?

**Comment by ai** [comment]
First issue:

```js
var dataloop = module.exports = function (css) {
```

There is no need to `module.exports =`, here. Because it makrs what file will return on `require('file')`

**Comment by ai** [comment]
Eveything else looks fine. What is your real output right now?

**Comment by ai** [comment]
I found a problem. 

```js
var postcss = require('gulp-postcss');
```

Here you put `gulp-postcss` into `postcss` variable, not a `postcss` library itself. So `postcss.rule` doesn’t work.

**Comment by benfrain** [comment]
OK, here is what I have now but same problem (no extra rules appended and no error message). As I'm trying to set this up inside Gulp I'm not sure if I am confusing matters (I have both gulp-postcss and postcss under different vars which I'm sure isn't the right way to do this:

```js
var postcss = require('gulp-postcss');
var simplevars = require('postcss-simple-vars');
var autoprefixer = require('autoprefixer-core');
var mqpacker = require('css-mqpacker');
var csswring = require('csswring');
var nestedcss = require('postcss-nested');
var corepostcss = require('postcss');
var categories = require('./data/cat-colors.js');

var dataloop = function(css) {
	for ( var category in categories ) {
		var borderTop = categories[category][0];
		var borderBottom = categories[category][1];
		var rule = corepostcss.rule({ selector: '.cat-' + category });
		rule.append({ prop: 'border-top', value: '1px solid ' + borderTop });
		css.append(rule);
	}
};

gulp.task('css', function () {
	var processors = [
		autoprefixer({browsers: ['last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4']}),
		simplevars,
		nestedcss,
		dataloop
	];
	return gulp.src('./preCSS/*.css')
		.pipe(postcss(processors))
		// .pipe(postcss(processors).on('error', gutil.log))
		.pipe(gulp.dest('./dest'));
});
```

Appreciate any further pointers :)

**Comment by ai** [comment]
Try to debug `dataloop` function inside.

```js
var dataloop = function(css) {
    for ( var category in categories ) {
        var borderTop = categories[category][0];
        var borderBottom = categories[category][1];
        var rule = corepostcss.rule({ selector: '.cat-' + category });
        rule.append({ prop: 'border-top', value: '1px solid ' + borderTop });
        console.log(rule);
        css.append(rule);
    }
};
```

**Comment by benfrain** [comment]
Just for anyone hitting this at a later date, it was (as suspected) a basic beginner JS issue. Here was the working loop:

```js
var dataloop = function(css) {
	for ( var category in categories.colorList ) {
		var colorSet = categories.colorList[category];
		var borderTop = colorSet[0];
		var borderBottom = colorSet[1];
		var rule = corepostcss.rule({ selector: '.cat-' + category });
		rule.append({ prop: 'border-top', value: '1px solid ' + borderTop});
		rule.append({ prop: 'border-bottom', value: '1px solid ' + borderBottom + ";"});
		css.append(rule);
	}
};
```

**Comment by MoOx** [comment]
If you got a simple loop, you can still create vanilla css & ask postcss to parse it. Code would be more readable imo.

**Comment by benfrain** [comment]
@MoOx - could you expand on that a little? Apologies for all the beginner questions; I'm still getting to grips with the possibilities postCSS offers!

**Comment by MoOx** [comment]
Something like this

```js
  var catss = []
  Object.keys(categories.colorList).forEach(function(c) {
    catss.push(".cat-" + c + "{border-top:1px solid " + categories.colorListc][0] + ";border-bottom: 1px solid " + categories.colorList[c][1] + ";}")
  })
  css.append(postcss.parse(catss.join("\n")))
```

I've to admit es5 is still shitty with string, but with es6 the code above can be cleaner:

```js
  var colors = categories.colorList
  css.append(postcss.parse(Object.keys(colors).map((c) => `
  .cat-${c} {
    border-top: 1px solid ${colors[c][0]};
    border-bottom: 1px solid ${colors[c][1]};
  }`).join("\n")))
```

**Comment by MoOx** [comment]
Btw, maybe .append() already accept plain string, so you can do `css.append("some{css:yeah}")`. 
I can't find anything in the API doc about that. So if not, that would be nice allow that. Don't you think @ai ?

**Comment by ai** [comment]
@MoOx nice idea! :) #223
