### ISSUE TITLE
Dealing with previous sourcemaps

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss#222]
Just a quick question about a problem I encountered. Here is a structure:

```
_ assets
    |_ dist
        |_ main.css
        |_ main.css.map
    |_ sources
        |_ scss
            |_ main.scss
            |_ _partials.scss
```

When node-sass parses `main.scss`, it creates `main.css` and `main.css.map`. In sourcemaps file, `sources` are relative, like for example: `../sources/scss/main.scss`, but there is not `sourceRoot`.
When postcss tries to use previous sourcemaps, it rewrites `../sources/scss/main.scss` to `../sources/sources/scss/main.scss` and it fails.

In `map.generator.js:115`, `this.map.applySourceMap(map, from, this.relative(root))`:

- `from` is equal to `../sources/scss/main.scss`
- `this.relative(root)` is equal to `../sources/scss` while it should be equal to `../scss` to make it work.

Any idea where the problem is?

**Comment by ai** [comment]
What `from` and `to` options you set to PostCSS, when you process `assets/dist/main.css`?

**Comment by iamvdo** [comment]
I don't process `assets/dist/main.css`, only `assets/sources/scss/main.scss`. `node-sass` compiles and writes sourcemaps in CSS as string, then gives it to PostCSS who creates output file. So:

- `from` is `/assets/sources/scss/main.scss`
- `to` is `/assets/dist/main.css`

**Comment by ai** [comment]
Why you set `from` to `/assets/sources/scss/main.scss`? You run PostCSS after node-sass, so your input file is `/assets/dist/main.css`?

**Comment by iamvdo** [comment]
No. I don't create files between node-sass and postcss.

I process `assets/sources/scss/main.scss` using node-sass. This return CSS as string and I process it using `postcss.parse(string_css_from_sass, opts)`.

In `opts`, `from` is `assets/sources/scss/main.scss`. I also tried to set `from` to `assets/dist/main.css`, but don't work either.

PostCSS seems to remove all `sources` files from generated sourcemaps, as there is only one `from` file. In fact, there are multiple `from` files. Is it possible ?

**Comment by iamvdo** [comment]
Plus, I don't have the same result if sourcemaps is embedded or used in `prev`.

**Comment by ai** [comment]
When you run `node-sass` you set `/assets/sources/scss/main.scs` to input and output `/assets/dist/main.css`. Sass generates source map fomr `dist/main.css`. So, when you run PostCSS with `from: scss/main.scss`, PostCSS can load previous source map generated for `dist/main.css`.

**Comment by mturnwall** [comment]
I'm having the same issue. I have a single scss file that imports other scss files. The sourcemap from node-sass properly lists all the scss files in the sources array of the sourcemap. Once the css is run through Postcss the sources array now only points to the single scss file that imports everything.

This is my main scss file.

```scss
@import 'easing';

@import '../../node_modules/susy/sass/susy',
        '../../node_modules/css-wipe/index'; // css reset

@import 'config';

@import 'typography',
        'buttons',
        'forms';

@import 'global';
```

Here are my scripts for node-sass and postcss

```javascript
function compileSass() {
    return sass.renderSync({
        file: `./src/sass/${sassFilename}.scss`,
        outFile: `${cssDir}/master.css`,
        outputStyle: 'expanded',
        sourceMap: true,
    });
}

function processCss(css) {
    const processor = postcss([autoprefixer]);
    processor.process(css.css, {
            from: `./src/sass/${sassFilename}.scss`,
            to: `${cssDir}/master.css`,
            map: {
                inline: false,
            },
        })
// mode code here to write files to disk
```

Here is what Postcss outputs for the sourcemap

```json
{"version":3,"sources":["../../src/sass/master.scss"]...
```

How do I get Postcss to still reference all the correct scss files that are imported by the main scss file?

**Comment by mturnwall** [comment]
I think I found a solution using the `prev` key. When I first used `prev` I would get an error telling me that that it was an unsupported format.

```javascript
    processor.process(css.css, {
            from: `./src/sass/${sassFilename}.scss`,
            to: `${cssDir}/master.css`,
            map: {
                prev: css.map,
                inline: false,
            },
        })
```

`css.map` is a properly formatted sourcemap from node-sass. The Postcss [documentation](http://api.postcss.org/global.html#processOptions) says that `prev` accepts an object.

If I convert the map to a string then `prev` works just fine.

```javascript
    processor.process(css.css, {
            from: `./src/sass/${sassFilename}.scss`,
            to: `${cssDir}/master.css`,
            map: {
                prev: css.map.toString(),
                inline: false,
            },
        })
```
