### ISSUE TITLE
String in insert methods

### ISSUE THREAD

**Issue by ai** [postcss/postcss#223]
@MoOx suggested nice idea to use CSS string in insert metthods:

```js
css.append('a { color: black }');
rule.insertAfter(decl, 'color: black');
```

**Comment by ai** [comment]
Done f047e43

**Comment by ai** [comment]
@MoOx @lydell should we remove old object shorcut:

```js
rule.append({ prop: 'color', value: 'black' });
```

Because string shorcut is better.

**Comment by MoOx** [comment]
No need to remove that method imo. Faster and people might already use it.

**Comment by davidtheclark** [comment]
Following up on this --- Is it yet possible to pass an *object*, e.g.

```js
{
  color: 'black',
  background: 'pink',
  padding: '4em',
  'border-radius': '100%'
}
```

Looks like maybe not, but I wanted to check if you were interested before opening an issue. (Maybe it would require a new method so these declarations don't get confused with options?)

**Comment by ai** [comment]
@davidtheclark this shorcut object can be used only to insert declarations, but we can create many node types.

**Comment by ai** [comment]
@davidtheclark but we can use shortcut from postcss-mixins to create rules and at-rules:

```js
css.append({
    '@media screen': {
        'a': {
            color: 'black'
        }
    }
})
```

But does we need it with CSS string shortcut?

@MoOx I think to remove object shorcut only for 5.0 release, so we a free to change API.

**Comment by MoOx** [comment]
I know you can deliver this and remove current api in a major release. Supporting a string is nice but since there is a parsing step, it seems legit to keep the object in order to avoid this step when its possible. Strings are convenient but its not the best & faster interface. Supporting both seems not a big deal.
And this can avoid all plugins dev to change their code like right now...

**Comment by davidtheclark** [comment]
I also think that if people were to compose CSS in JS, they would be much better off creating objects than concatenating strings that included punctuation, you know?

**Comment by MoOx** [comment]
+1

**Comment by ai** [comment]
@MoOx Yeap, parsing is not a fast operation. Let’s keep old object syntax.

@davidtheclark unfortunately even postcss-nested object shortcut syntax is not good for use. I forgot that there is not way to create bodyless at-rule there.
