### ISSUE TITLE
Read previous sourcemaps

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss#233]
After many many tests, I think I've found a bug when using previous sourcemaps:

If structure is like this:
```
_ app
    |_ dist
        |_ css
            |_ main.css
            |_ main.css.map
    |_ src
        |_ files
            |_ main.styl
            |_ import.styl
        |_ modules
            |_ module.styl
```

Preprocessor (here Stylus) generates 3 sources files, in `sources`: `[ '../../src/files/import.styl', '../../src/files/main.styl', '../../src/modules/module.styl' ]`. PostCSS reads it and outputs good sourcemaps (the same thing). It's OK because there are equal nested folders.

If structure is: 
```
_ app
    |_ dist
        |_ main.css
        |_ main.css.map
    |_ src
        |_ files
            |_ main.styl
            |_ import.styl
        |_ modules
            |_ module.styl
```

Then, PostCSS outputs in `sources`: `[ '../src/src/files/import.styl', '../src/files/main.styl', '../src/src/modules/module.styl', '../src/src/files/main.styl' ]`.
It duplicates `src/` on paths, and so a new file (the same) is added.

**Comment by ai** [comment]
What `from` and `to` options you set in last broken example?

**Comment by iamvdo** [comment]
First case:
- `from` is `app/src/files/main.styl`
- `to` is `app/dist/css/main.css`

Second case:
- `from` is `app/src/files/main.styl`
- `to` is `app/dist/main.css`

So, basically, where the files are.

**Comment by ai** [comment]
Again. You set wrong `from` and `to`. Stylus generates source map for `main.css`, not for `main.styl`.

**Comment by ai** [comment]
Think like this. Stylus step:

* from `app/src/files/main.styl`
* to `app/dist/main.css`

If you will open Stylus source map, you will see `main.css` in `file` property. PostCSS’s `from` option **must** be equal with previous source map `file` content.

**Comment by iamvdo** [comment]
I set `from` option as you say. 
But, in order to make it work, I also need to switch `to` from `app/dist/main.css` to `main.css`, or not use it. In both cases, PostCSS adds `main.css` as a new source. Is it intended ?

**Comment by ai** [comment]
if you read `main.css` and write `main.css`  back you shoult set `from: app/dist/main.css` and `to: app/dist/main.css`.

**Comment by iamvdo** [comment]
This creates the same output.

**Comment by ai** [comment]
OK. With fixed options we can go deeper :). What is `sources` after Stylus and after PostCSS?

**Comment by iamvdo** [comment]
After Stylus:
```
[ '../src/files/import.styl',
     '../src/modules/module.styl',
     '../src/files/main.styl' ]
```
After PostCSS:
```
[ '../src/files/import.styl',
     'main.css',
     '../src/modules/module.styl',
     '../src/files/main.styl' ]
```

**Comment by ai** [comment]
So, what is wrong?

**Comment by iamvdo** [comment]
I'm just asking about the `main.css` entry ? I don't even know if it's intended or not ?

**Comment by ai** [comment]
In most cases it iw generates because previous map doesn’t map all symbols of source. For example, Sass doesn’t map `}` symbol. So most of output sources symbols is mapped to some origin source. But some rare symbols are mapped only by PostCSS.

This symbols doesn’t display in DevTools and problem of previous mapping.

**Comment by ai** [comment]
But if you want to know exactly for your case:

1. Open [source map vizualizer](http://sokra.github.io/source-map-visualization/).
2. Press “Custom”.
3. Set all necessary files.

And you will source all mappings of source map.

**Comment by iamvdo** [comment]
OK, I better understand now. Thanks for help. :+1: 
(maybe I will have more questions later ;) )

**Comment by ai** [comment]
Feel free to ask them :)
