### ISSUE TITLE
Resetting `rule.semicolon` and `rule.after` sometimes breaks source map

### ISSUE THREAD

**Issue by hail2u** [postcss/postcss#234]
I dig into a bug reported on hail2u/node-csswring#50. The problem occurred when `rule.semicolon` and `rule.after` reset. However, it seems PostCSS bug.

The testing CSS is same as issue above, but the following test code that only resets `rule.semicolon` and `rule.after` can reproduce this bug:

```javascript
var fs = require('fs');
var importer = require('postcss-import');
var postcss = require('postcss');

var css = fs.readFileSync('a.css', 'utf8');
var result = postcss().use(importer()).use(function (css) {
  css.eachRule(function (rule) {
    rule.before = '';
    rule.between = '';
    rule.semicolon = false;
    rule.after = '';
  });
}).process(css, {
  from: 'a.css',
  map: {
    inline: false
  },
  to: 'to.css'
});

fs.writeFileSync('to.css', result.css);
fs.writeFileSync('to.css.map', result.map);
```

This bug is raised only when concatenate CSS files with plugins like `postcss-import` (I'm not sure).

**Comment by ai** [comment]
Can you give me some small and simple `a.css` that reproduce this issue?

**Comment by hail2u** [comment]
`a.css`:

```css
@import 'b.css';

.a {
  color: red;
}
```

`b.css`:

```css
.b {
  color: blue;
}
```

`test.html`:

```html
<link href="to.css" rel="stylesheet">
<div class="a">a</div>
<div class="b">b</div>
```

Inspecting with Chrome 40:

![cap-20150302-080702](https://cloud.githubusercontent.com/assets/68940/6433464/2e161740-c0b3-11e4-80ce-0ca1d36fceeb.png)

`.a` wrongly linked to `b.css:2`.

--------

Sorry, this issue appears not only when resetting `rule.semicolon` and `rule.after` but also `rule.before` and `rule.between`. I fixed test code above. However, there are other conditions for reproducing this issue.

**Comment by ai** [comment]
Link to source map visualization to reproduce error: [to.css](http://sokra.github.io/source-map-visualization/#base64,LmJ7CiAgY29sb3I6IGJsdWV9LmF7CiAgY29sb3I6IHJlZH0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnpiM1Z5WTJWeklqcGJJbUl1WTNOeklpd2lZUzVqYzNNaVhTd2libUZ0WlhNaU9sdGRMQ0p0WVhCd2FXNW5jeUk2SWtGQlFVRTdSVUZEUlN4WlEwTkdMRUZFUkdNc1EwRkRZanRGUTBORExGZEJRVmNzUTBGRFdpSXNJbVpwYkdVaU9pSjBieTVqYzNNaUxDSnpiM1Z5WTJWelEyOXVkR1Z1ZENJNld5SXVZaUI3WEc0Z0lHTnZiRzl5T2lCaWJIVmxPMXh1ZlZ4dUlpd2lRR2x0Y0c5eWRDQW5ZaTVqYzNNbk8xeHVYRzR1WVNCN1hHNGdJR052Ykc5eU9pQnlaV1E3WEc1OVhHNGlYWDA9ICov,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImIuY3NzIiwiYS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxZQ0NGLEFERGMsQ0FDYjtFQ0NDLFdBQVcsQ0FDWiIsImZpbGUiOiJ0by5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYiB7XG4gIGNvbG9yOiBibHVlO1xufVxuIiwiQGltcG9ydCAnYi5jc3MnO1xuXG4uYSB7XG4gIGNvbG9yOiByZWQ7XG59XG4iXX0=,LmIgewogIGNvbG9yOiBibHVlOwp9Cg==,QGltcG9ydCAnYi5jc3MnOwoKLmEgewogIGNvbG9yOiByZWQ7Cn0K)

**Comment by ai** [comment]
Seems like PostCSS adds wrong column number in source map mappings.

**Comment by ai** [comment]
Hm. I think, I fix this issue: 899c655

**Comment by ai** [comment]
Test from @hail2u looks correct in source map visualization and in Chrome DevTools. I hope I didn’t broke some other cases :D.

**Comment by ai** [comment]
@hail2u I received a mail from GitHub. You updated you message? Did fix works for you right now?

**Comment by hail2u** [comment]
With v4.1 branch (899c655), the problem seems to be fixed! Thanks!

![cap-20150329-143120](https://cloud.githubusercontent.com/assets/68940/6884217/52117662-d620-11e4-8991-add01b51649a.png)
