### ISSUE TITLE
API to parse selectors

### ISSUE THREAD

**Issue by ai** [postcss/postcss#235]
Maybe we should have some special API to parse selector? Like `Rule#parseSelector`?

Of course, it will be only on demand. And we should use some other tool. So it  will like shorcut to use some best library.

**Comment by ai** [comment]
First question: for what plugin cases we need selector parser.

**Comment by TrySound** [comment]
I use it for layout modification with custom tagNames => .classNames, for adding class prefixes.

**Comment by TrySound** [comment]
For functions [reduce-function-call](https://github.com/MoOx/reduce-function-call)
Or low level [balanced-match](https://github.com/juliangruber/balanced-match)

**Comment by TrySound** [comment]
I use such API in my project

```js

function Parser(selector) {};

Parser.prototype.build = function () {};

Parser.prototype.eachRule =  function (cb) {};
// Callback could return selector that will be added to selector chain
```

Full code [here](https://gist.github.com/TrySound/b21efe262f4dc64c15d3)

**Comment by davidtheclark** [comment]
I think it will be useful for any analytics plugins. `list-selectors` uses it (extract simple selectors). `postcss-bem-linter` and other linters could use it (check if selectors are acceptable). 

Glad you opened this: I was just checking the repo to open the exact same issue :)

**Comment by davidtheclark** [comment]
I have only been able to find this existing library: https://github.com/mdevils/node-css-selector-parser Maybe others know of more?

**Comment by TrySound** [comment]
@davidtheclark my wrapper above use it

**Comment by ben-eb** [comment]
@ai My plugin, https://github.com/ben-eb/postcss-minify-selectors would benefit from a built in selector parser.

**Comment by devinus** [comment]
This would be hugely beneficial for me as well.

**Comment by davidtheclark** [comment]
@ai Have you thought further about this?

And @TrySound have you been happy with `node-css-selector-parser`? I noticed that you have filed a couple of issues that have not gotten responses ...

I was thinking about this in the context of selector rules for stylelint (https://github.com/stylelint/stylelint/issues/1). These rules will definitely require some degree of selector parsing; and of course it would better to do this in a way that is shared among PostCSS authors.

**Comment by TrySound** [comment]
@davidtheclark I made own wrapper on this. And it was helpful. I didn't notice big problems, caz I used it small time.

**Comment by ai** [comment]
@davidtheclark right now @ben-eb is working on new selector parser

**Comment by davidtheclark** [comment]
@ben-eb If you'd like any help just point me at the repo :)

**Comment by sokra** [comment]
I've written a module for selector parsing: https://github.com/css-modules/css-selector-tokenizer

**Comment by ai** [comment]
@sokra cute. Maybe we need to add it to `API.md`.

@ben-eb what is current status of PostCSS internal selector parser?

**Comment by ben-eb** [comment]
@ai

Selector string:

```
h1, h2, [href*=test i], a:after
```

Will produce this AST:

```
{ type: 'root',
  selectors:
   [ { type: 'selectors',
       rules:
        [ { type: 'tag',
            rules: [],
            spaces: { before: '', after: '' },
            value: 'h1',
            combinator: '',
            parent: [Circular] } ],
       spaces: { before: '', after: '' },
       parent: [Circular] },
     { type: 'selectors',
       rules:
        [ { type: 'tag',
            rules: [],
            spaces: { before: '', after: '' },
            value: 'h2',
            combinator: '',
            parent: [Circular] } ],
       spaces: { before: ' ', after: '' },
       parent: [Circular] },
     { type: 'selectors',
       rules:
        [ { type: 'attribute',
            rules: [],
            spaces: { before: '', after: '' },
            value: 'test',
            combinator: '',
            insensitive: true,
            attribute: 'href',
            operator: '*=',
            raw: { insensitive: ' i' },
            parent: [Circular] } ],
       spaces: { before: ' ', after: '' },
       parent: [Circular] },
     { type: 'selectors',
       rules:
        [ { type: 'tag',
            rules: [],
            spaces: { before: '', after: '' },
            value: 'a',
            combinator: '',
            parent: [Circular] },
          { type: 'pseudo',
            rules: [],
            spaces: { before: '', after: '' },
            value: ':after',
            combinator: '',
            parameters:
             { type: 'parentheses',
               selectors: [],
               spaces: { before: '', after: '' } },
            parent: [Circular] } ],
       spaces: { before: ' ', after: '' },
       parent: [Circular] } ],
  spaces: { before: '', after: '' } }
```

https://github.com/postcss/postcss-selector-parser

**Comment by ai** [comment]
Yeap, @ben-eb finish a first preview of PostCSS parser. Please take a look, we need your feedback: https://github.com/postcss/postcss-selector-parser

First versions will be as separated library to break a API. When we will finalize it, we will integrate it into PostCSS.

**Comment by ai** [comment]
@sokra PostCSS selector parse will use a tokenize/parse steps, so it will be easy to change and faster. But right now it has some complicated places.

Hor did you solve a nested selectors like? `:not(.a, :b, :c:hover)`?

**Comment by sokra** [comment]
> @sokra PostCSS selector parse will use a tokenize/parse steps, so it will be easy to change and faster. But right now it has some complicated places.

My parser only has 200 lines :smile: (300 if you count all dependencies too)
So it propably easy to change...
 
> Hor did you solve a nested selectors like? :not(.a, :b, :c:hover)?

See README for an example: https://github.com/css-modules/css-selector-tokenizer#css-modules-css-selector-tokenizer

``` js
       { type: "nested-pseudo-class", name: "not", nodes: [
          {
            type: "selector",
            nodes: [
              { type: "pseudo-class", name: "visited" }
            ]
          }
        ] }
```

Internally it holds a stack. So you could nest `:not` inside `:not`: i. e. `a:has(div:not(.active), h2)`,

**Comment by ai** [comment]
@doors lines of code don't show complexity and maintainability. Less code with more internal connections is more complicated, that more code, but with less connections. MVC pattern is a good example :-).

Awesome, that you solve it. Maybe we should take that idea too. I hope our parser will not be like a GNU Hurd kernel with better architecture, but always in alpha :-D.
