### ISSUE TITLE
sourceRoot option

### ISSUE THREAD

**Issue by ai** [postcss/postcss#240]
We need to add `sourceRoot` option to map generator.

For example, right now gulp-postcss change root of `sources` [manually](https://github.com/w0rm/gulp-postcss/blob/master/index.js#L57). Option will be very helpful in this case.

/cc @w0rm

**Comment by ai** [comment]
@w0rm do we really need it?

**Comment by w0rm** [comment]
@ai this is not really critical, I don't mind keeping it as it is now.

**Comment by ai** [comment]
i think we can live without this feature. Anyway PR will be welcome.

**Comment by evilebottnawi** [comment]
@ai We need this feature.
I write plugin for rebase url on sourcemap sources. i get error
```bash
Error in plugin 'css-rebase-urls'
Message:
    "themes/insteria/font-awesome/less/path.less" is not in the SourceMap.
```
Real path "src/themes/insteria/font-awesome/less/path.less"
I use code
```
console.log(decl.source.input.origin(
    decl.source.start.line,
    decl.source.start.column
));
```
Before less compile and concat css. Some files in less format, some in css format.
Base directory sources and build directory is difference.

**Comment by evilebottnawi** [comment]
in fast way i use this code
```javascript
decl.source.input.map.consumer().sourceRoot = '/my/path/to/source';
// Some logics...
decl.source.input.map.consumer().sourceRoot = null;
```
but it is bad code :(. Maybe someone you know can help

**Comment by difosfor** [comment]
Hmm ran into this with our build tool (https://github.com/exmg/nbob) as well. Patching it for now like the gulp-postcss plugin does (as mentioned above), but would enjoy an option for this as well.

**Comment by ai** [comment]
Welcome for PR :D

**Comment by evilebottnawi** [comment]
@ai need feature, because using `gulp-postcss` with options `to`, need for `postcss-import` break sourcemaps :( I will try to  investigate the issue, but do not know postcss code as need to resolve this problem.

**Comment by TrySound** [comment]
@evilebottnawi Doesn't need at all. Where did you find that?

**Comment by evilebottnawi** [comment]
@TrySound find what? Problem? (https://github.com/postcss/gulp-postcss/issues/64)

**Comment by TrySound** [comment]
@evilebottnawi Using with postcss-import

**Comment by evilebottnawi** [comment]
@TrySound sorry, `postcss-import` need this options for resolve path to assets, source and destination directory may be different and resolve not working without `to` options.

**Comment by TrySound** [comment]
@evilebottnawi postcss-import do not need this option. It handle only `from` postcss option.

**Comment by evilebottnawi** [comment]
@TrySound https://github.com/geut/postcss-copy/blob/master/src/index.js#L292 get options from `to`

**Comment by TrySound** [comment]
@evilebottnawi `postcss-copy` is not `postcss-import`.

**Comment by evilebottnawi** [comment]
@TrySound i know, about this issue https://github.com/postcss/gulp-postcss/issues/64#issuecomment-165990365, if i set option `to`, my sourcemap wrong, if i not set option `to`, resolve `postcss-copy` and `postcss-url` not resolve right my path to files (fonts, images).

**Comment by TrySound** [comment]
@evilebottnawi I see, but your mention to `postcss-import` doesn't make sense.

**Comment by evilebottnawi** [comment]
@TrySound I made a mistake and then correct it, be sure to focus on this rather than on solving the problem?

**Comment by TrySound** [comment]
That what I wanted to see.:)

**Comment by evilebottnawi** [comment]
@TrySound maybe help or just offtop?

**Comment by TrySound** [comment]
I response for `postcss-import` and was confused with your mention.

**Comment by Saturate** [comment]
To fix https://github.com/sindresorhus/gulp-autoprefixer/issues/55 we need this.

I did a pull-request **(https://github.com/sindresorhus/gulp-autoprefixer/pull/61)** but as seen in the comments from the owner, it should be fixed here, as other plugin authors will benefit as well, from this change.

**Comment by ai** [comment]
@Saturate can you make a PR here?

**Comment by Saturate** [comment]
@ai I'll have a look at it later.

**Comment by ai** [comment]
@Saturate it is last version for 5.1 release :)

**Comment by tarikihm** [comment]
While this is being looked at, should an extensions array option be added as well? See: https://github.com/postcss/postcss-import/pull/52 and https://github.com/outpunk/postcss-modules/issues/13

Haven't looked in depth at the proposed solutions yet, but perhaps a simple and elegant solution would be to handle file resolving in PostCSS rather than passing down additional parameters to the plugins, so perhaps PostCSS could pass down a resolving function in the API's opts object? that function would return an absolute file path or an error if the file was not found.

**Comment by ai** [comment]
@tarikihm `sourceRoot` it is a thing only for source map. It is not relevant for looking paths from this issues.

**Comment by tarikihm** [comment]
Got it, sorry I skimmed through a bit too quickly, still, is there a way to avoid having to pass file resolving options to each plugin? Would it make sense that it gets handled/supervised by PostCSS?

**Comment by ai** [comment]
@tarikihm open a new issue for it.

**Comment by CREEATION** [comment]
@ai @tarikihm is gone, FYI. :disappointed_relieved:

**Comment by ai** [comment]
OK. I will close this issue again if nobody want to implement it.

**Comment by aleclarson** [comment]
Here's a workaround:

```js
const res = await postcss().process(code, opts);
res.map._sourceRoot = '/path/to/root';

assert(res.map.toJSON().sourceRoot == res.map._sourceRoot);
```

The `sourceRoot` option seems like it should exist for the sake of completeness.
