### ISSUE TITLE
Rename error.generated

### ISSUE THREAD

**Issue by ai** [postcss/postcss#241]
CssSyntaxError ses input source map to find origin source of error. For example, in Sass file. But PostCSS input position is saved to `generated`.

I think this property name is confused, We shouuld change it.

**Comment by ai** [comment]
I plan to use `origin`.

**Comment by ben-eb** [comment]
What about changing this to `before`? As in, an error that occurred *before* PostCSS?

**Comment by ai** [comment]
What about `error.input`, because it was a *input* to PostCSS.

**Comment by ai** [comment]
Also `error.input` is related with PostCSS’ `Input` class for same thing.

**Comment by ben-eb** [comment]
I like `input`. :smile:

**Comment by ai** [comment]
Done c054295d04997080e6bda36d401fe0f682eda3fc
