### ISSUE TITLE
Use supports-color to detect colors

### ISSUE THREAD

**Issue by ai** [postcss/postcss#254]
[support-color](https://github.com/sindresorhus/supports-color/blob/master/index.js)

**Comment by ben-eb** [comment]
@ai This is for CssSyntaxError, right? What do you think of bundling [chalk](https://github.com/chalk/chalk) to clean this up a bit?

**Comment by ai** [comment]
Yeap, only for `CssSyntaxError`.

I think chalk is too big for us, so just `support-color` was enough.

**Comment by ai** [comment]
There is a insteresting question for future PostCSS releases. I want to make some small subset of PostCSS to use in browser. For example for React Style lovers. For example, build without source-map support could be 2 times smaller.

Maybe in PostCSS 5.0 we should split project to `postcss-ast`, `postcss-core` and `postcss`.

**Comment by ai** [comment]
`postcss-ast` is needed for Custom Syntaxes.

**Comment by ai** [comment]
But it is not a final plan, just a thoughts why we should start to think about PostCSS build size.

**Comment by ai** [comment]
There are three problem in `support-color`:

1. It uses `process`, which do not exists in browser.
2. It runs test right on `import`.
3. Arguments tests in unnecessary in this PostCSS case.

So I decide to copy tests right now 06feb5f

@sindresorhus maybe you can suggest better way?

**Comment by sindresorhus** [comment]
You've mentioned some things you think are problems, but you don't say why. So why?

1. Doesn't matter. Browserify will shim it.
2. I don't see why that matters. ?
3. Why?

**Comment by ai** [comment]
Hm. I forgot, that Browserify shims node's objects.

**Comment by ai** [comment]
@sindresorhus moved to `supports-color` 31c6b2e

Maybe we should add `typeof process === 'undefined'` check? PostCSS can be built not by Browserify or runned in non-node env.

**Comment by ben-eb** [comment]
@ai It might be good to do some automated browser testing of PostCSS to find out these problems and work around them if necessary. :smile:

**Comment by ai** [comment]
@ben-eb nice idea. Karma?

**Comment by ben-eb** [comment]
@ai I was thinking tape with run-browser. That way you can write a test in node, browserify it dynamically and test it headlessly. I have such a test setup for another module:

https://github.com/ben-eb/widow/blob/master/test.browser.js
https://github.com/ben-eb/widow/blob/master/package.json#L29-L31

**Comment by ai** [comment]
@ben-eb PR? :)

**Comment by sindresorhus** [comment]
I've added browser support to `supports-color`. I will now check for the `process` global in case it's used without browserify. If browserify is used it will exclude all the code and just return false. https://github.com/chalk/supports-color/commit/983dd4eb0bca835fe53cb0f25c0cf14957191128

**Comment by ben-eb** [comment]
@sindresorhus Awesome. :+1:

**Comment by ai** [comment]
Thanks :)
