### ISSUE TITLE
Runner Guidelines discussion

### ISSUE THREAD

**Issue by ai** [postcss/postcss#261]
I add first guidelines for PostCSS ecosystem. [Runner Guidelines](https://github.com/postcss/postcss/blob/v4.1/Runner%20Guidelines.md).

I will be mondatory, when we will release 4.1, so community feedback is very important.

@nDmitry @w0rm @pirxpilot what do you think about this rules? It will be mondatory for your plugins.

@sindresorhus this rules will be recommended for your `gulp-autoprefixer` too. So what do you think?

/cc @MoOx @MohammadYounes @yisibl

**Comment by sindresorhus** [comment]
Lgtm. I'll update `gulp-autoprefixer` when it's finalized.

**Comment by ai** [comment]
@jeffjewiss this rules will be mondatory for broccoli-postcss too :). What do you think about them?

**Comment by w0rm** [comment]
I'm happy to follow these rules in gulp-postcss, ping me once it's finalized!

**Comment by pirxpilot** [comment]
Seems OK. Two things:

- As far as I can tell async API is not documented in [API.md](https://github.com/postcss/postcss/blob/master/API.md) - we can't tell people *use async API* and *use only documented API* and then not document async API
- Lose the whole scary **mandatory** thing. It's not needed, and it's not enforceable. You can't stop people from writing stuff even if you don't agree with it (and it's a good thing); Instead, let's say something like:

    *in order for you runner to be listed in official postcss `Readme` it has to follow these guidelines*

**Comment by jeffjewiss** [comment]
@ai thanks for including me in this, it was a nice surprise to see you noticed I published the module.

I think the runner guidelines are a great start and I'm happy to follow them. I'm a little unclear on how 1.1 would work. I think this may be because I'm still familiarizing myself with postcss, but I'm not sure how that would work in the context of a Broccoli plugin.

**Comment by ai** [comment]
@pirxpilot you should check out [`API.md` from `v4.1` branch](https://github.com/postcss/postcss/blob/v4.1/API.md)

**Comment by ai** [comment]
@jeffjewiss 1.1 is mostly for `postcss-cli` :)

**Comment by ai** [comment]
@jeffjewiss but I made 1.1 cleaner aec41e9

**Comment by jeffjewiss** [comment]
@ai thanks for clarifying and sorry for the extra messages. :)

**Comment by MohammadYounes** [comment]
Looks Great :+1: 

For **2.1** I would recommend separation between postcss and the plugin options.

```
processor(pluginOptions).process(css, postcssOptions);
```

Also a unified name for the exposed  processing method  

```
processor.postcss(css)
```

**Comment by lydell** [comment]
Pinging @iamvdo about postcss-brunch.

**Comment by ai** [comment]
@iamvdo sorry, I forget about Brunch builder :). What do yo think about this rules?

**Comment by ai** [comment]
@MohammadYounes yes, I will add Rules to boilerplate when everyone will agree it.

**Comment by iamvdo** [comment]
Great rules.
I'm not actively maintaining `postcss-brunch`, and it's a bit of obsolete right now. It was my first "test" before creating `pleeease`. If you want to update, I can add contributors.

BTW, when developing pleeease's "runner", like `pleeease-cli` or `gulp-pleeease`, I needed to separate `postcss.parse` and `postcss.process` methods. Maybe you can also document this ?

**Comment by ai** [comment]
@iamvdo what do yo mean about `postcss.parse` and `postcss.process`?

**Comment by iamvdo** [comment]
Well, as I remember, for example:
- to get full and correct sourcemaps support (from preprocess step)
- to get data from multiple files (custom properties defined in one file and use in another)

I first parse files individually with `postcss.parse(file, sourcemaps)`, and then process concat AST at the end.

**Comment by ai** [comment]
Thanks for feedback. Some small ideas I will remember for future.

Let’s wait for 4.1. I plan to release it on next week.

**Comment by geddski** [comment]
Does it really need to be mandatory?

**Comment by ai** [comment]
@geddski yes, because most of rules that was mentions in Guidelines are very important. For example, if runner will miss `from` option, it will generates broken source map.

With this guidelines PostCSS runners will work better and users will think about PostCSS as quality product.

Maybe you disagree with some rule or think that some rule should not be mandatory in some case? We can change rules before 4.1 release.
