### ISSUE TITLE
converting linked css to inline css

### ISSUE THREAD

**Issue by gedw99** [postcss/postcss#265]
Can someone advice me about approach to do this with postcss.
 
Postcss looks very useful for many things in this area.

**Comment by MoOx** [comment]
Are you looking for this https://github.com/postcss/postcss-import ?

**Comment by davidtheclark** [comment]
Sounds to me @gedw99 like you're looking for a way to process *HTML* (converting it's `<link>`s to inline styles) — so I think that's outside of the scope of PostCSS. PostCSS would be used to process the CSS before some HTML-processing tool inlines it.

**Comment by gedw99** [comment]
Ok thats exactly what I needed to know @davidtheclark . will look for a Java or nodejs package that does the inlining.

**Comment by ben-eb** [comment]
I don't see why this couldn't use PostCSS to parse the CSS. If you have a look at https://www.npmjs.com/package/juice they are using a CSS parser; but of course we know that PostCSS's parser is the fastest available. @gedw99 I would have a look at juice and https://www.npmjs.com/package/inline-css - of course there's no real need to reinvent the wheel. :smile:

**Comment by ai** [comment]
@gedw99 it is not really PostCSS task. I think will bbe more flexible to split your task to 2 subtasks:

1. processing CSS by PostCSS in `.css` files
2. inline processed `.css` to `.html` by some tool from @ben-eb message above.
