### ISSUE TITLE
Please show depreciations notice once per run

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#272]
This is kind of annoying when you get a small update to see so many fucking warnings. This scares user.
I am sure I will get plenty of requests to ask me to "UPDATE ASAP ALL THE PLUGINS".
You should just output this kind of notice once per instance.
Maybe in red or something. But not so many times... 

![screen shot 2015-04-02 at 08 10 39](https://cloud.githubusercontent.com/assets/157534/6958715/f85f9020-d90f-11e4-85f3-a4d5c1aba06a.png)

**Comment by ai** [comment]
Maybe it is a too complicated logic for small deprected message, which is used (as I understand) only in one plugin? :)

I have no problems with warning per instance check, but I think it will be faster to fix plugin, rather that fix PostCSS.

**Comment by MoOx** [comment]
That's not the first time I saw a depreciation notice a hundreds of time. This already happened in the past.
You can just add a boolean flag to know if a notice has already been outputed or not. Like 2 lines of code

Instead of 

```
if (condition) {
  console.log("Depreciation notice!")
}
```

you can do 

```
var noticeHasBeenOutputed = false

if (condition && !noticeHasBeenOutputed) {
  console.log("Depreciation notice!")
  noticeHasBeenOutputed = true
}
```

Not a big deal imo. And that would prevent me from opening an issue (keep in mind that most people will just don't say anything but won't be happy too)

**Comment by MoOx** [comment]
Btw, if I update that right now, people will all need to update postcss. So I need to do a major release for my plugin in order to respect semver.

**Comment by ai** [comment]
I will add boolean flag next time :).
