### ISSUE TITLE
Make README shorter

### ISSUE THREAD

**Issue by ai** [postcss/postcss#277]
How we has too difficult and too long README.md.

**Comment by MoOx** [comment]
Or add a TOC like I did for cssnext ;)
Lot's of things in the README are cool. Especially when you are offline with just your node_modules/* :D

**Comment by ai** [comment]
TOC is a hack, not a solution. One sentence has more power, that 3 sentenses. Also current text is difficult to understand for non-native users.

**Comment by MoOx** [comment]
TOC are not a hack. If get TOC in every book that exist. When you have a lot of content, TOC are just an easy starting point to quickly search for information.
I understand the fact that you can reduce the text, but do not compare shorter text to the purpose of a TOC :)

**Comment by gazay** [comment]
I'm +1 for TOC, as it will helps users to get to `Usage` section more quickly

**Comment by ai** [comment]
We can add TOC as fast fix. But problem will be still exist with TOC.

@MoOx you are right, TOC is nice for API and other book-like big texts. But good promotion text should be short and works without TOC.

**Comment by ai** [comment]
I added TOC. @MoOx thanks for nice TOC example :).

**Comment by ben-eb** [comment]
It might be nice to extract some of the sections into separate files; for example, you could have other files to list recipes for working with PostCSS, another for plugins, etc. As we develop more plugins it might be a nice idea to get a plugin registry, such as http://gulpjs.com/plugins/

**Comment by davidtheclark** [comment]
I think you might have to pick more specifically what you want the readme to communicate. Right now there is a lot of promotional content. If you decide you want to, say, leave that to articles & blog posts and take it out of the README, that would cut down substantially on length. Similarly, as @ben-eb said, if you decide that the README doesn't have to list the plugins, but a separate page could do that, you'd cut it down further.

In its current form, I don't think it's *inefficient*: it's just communicating a whole lot of information. So, yeah, you might just want to pick which information to put elsewhere.

**Comment by ai** [comment]
Yeap, I think we had a 2 steps here:

1. Make current information shorter.
2. Move some extra info to PostCSS site.

But I can start site development only in next month. After Autoprefixer 5.2 and Plugins Guidelines.

**Comment by ai** [comment]
We with @ben-eb rewrote README.md and made it much shorter and cleaner.

@davidtheclark sorry, we remove your well-written text. It is sacrifice on the altar of brevity for all of us :).

**Comment by davidtheclark** [comment]
Ha :) So it goes.
