### ISSUE TITLE
Allow PostCSS to consume a module that only consumes other processors?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#280]
This is being discussed today in the Gitter chat but could use writing up.

Currently, I am working on a modular minifier, which should essentially only wrap existing PostCSS modules. When using PostCSS before `4.1` I could do simply:

```js
function Wrap (options) {
    this.options = options || {};
}

Wrap.prototype.createPipeline = function () {
    return postcss([
        discardComments(this.options.comments),
        colormin(),
        // ... etc
    ]));
};

Wrap.prototype.optimise = function (css) {
    return this.createPipeline().process(css);
};

module.exports = function (css, options) {
    var wrap = new Wrap(options);
    return wrap.optimise(css).css;
};

module.exports.postcss = function (css, options) {
    var wrap = new Wrap(options);
    return wrap.optimise(css);
};
```

But, ideally in `4.1` I should be able to emit a pipeline of processors to act as a whole module. So that I could, as a consumer of PostCSS modules, do:

```js
var postcss = require('postcss');

postcss([ require('autoprefixer'), require('wrap') ]).then(function (result) {
    console.log(result.css);
});
```

In actual fact, from this code, PostCSS sees a pipeline like this:

```js
[ require('autoprefixer'), require('postcss-discard-comments'), require('postcss-colormin') ]
```

This is not just beneficial for me; I think @MoOx and @iamvdo would see benefit for pleeease and cssnext from such a feature. Would appreciate any feedback on the best way to approach this.

**Comment by lydell** [comment]
What abouing make `require('wrap')` return an array and use the ES6 spread operator: `postcss([require('autoprefixer'), ...require('wrap')])`?

**Comment by MoOx** [comment]
cssnext can already be consumed as a postcss plugin.

**Comment by ben-eb** [comment]
@MoOx Thanks, I've had a dig around in the source code and it looks like I might just be able to chain `postcss().use(plugin1).use(plugin2)`. :+1:

**Comment by w0rm** [comment]
I think we should allow passing an object processor in the processors array.

I had to switch gulp-postcss back to using `postcss().use` because of [this issue](https://github.com/w0rm/gulp-postcss/issues/26) with cssnext.

**Comment by ai** [comment]
I think I fix it here 57a8d4fa771fbca9f4976f586b455545f87f21f4

**Comment by ben-eb** [comment]
Please advise on how I accommodate these changes. I need to be able to keep my original API https://github.com/ben-eb/cssnano#scripting as well as this `postcss([ require('cssnano') ])` sugar syntax, which I cannot get to work. I don't want to already release a breaking API change to support this.

**Comment by tunnckoCore** [comment]
@ben-eb I cant got for what is the whole issue, really.. lol

**Comment by tunnckoCore** [comment]
works as of `v4.1.8`

```js

var postcss = require('postcss');
var cssnano = require('cssnano');

var input = 'div {\n  font-weight: 900;;;;\n  color: red;;}';

var res1 = cssnano(input);
var res2 = postcss().use(cssnano()).process(input).css;
var res3 = postcss([cssnano()]).process(input).css;

console.log(res1);
//=> div{font-weight:900;color:red}

console.log(res2);
//=> div{font-weight:900;color:red}

console.log(res3);
//=> div{font-weight:900;color:red}
```
