### ISSUE TITLE
Is there a minify option for stringify?

### ISSUE THREAD

**Issue by devinus** [postcss/postcss#284]
rework's CSS parser has a `minify` option that returns the CSS minified. I was wondering if postcss has the same?

**Comment by ai** [comment]
PostCSS saves source whitespaces and by default doesn’t change them:

```js
postcss().process('a{color:black}') //=> 'a{color:black}'
postcss().process('a { color: black; }') //=> 'a { color: black; }'
```

If you want to minify CSS, you should use some CSS minifier. For example, PostCSS based [csswring](https://github.com/hail2u/node-csswring) by @hail2u.

@ben-eb now developing a new modular CSS minifier, you can use some his minify CSS plugins to compress CSS better.

**Comment by ben-eb** [comment]
Agreed, PostCSS itself should not be responsible for this.
