### ISSUE TITLE
Add warn() method on node directly

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#289]
Is there any reason you didn't offer a warn() method on node like for error() ?

**Comment by ai** [comment]
Because nodes doesn't now current Result instance.

**Comment by ai** [comment]
We can add `Node#setContext` and set `Result` to `node.context.result` to use it in `node.warn`. But does it is a good way?

Especially in current love on pure function and FP.

Or maybe we can use this API:

```
node.warn(result, 'text');
```

@ben-eb @jonathantneal What guys do you think?

**Comment by ben-eb** [comment]
Would it be possible to autofill that `result` parameter? So an API like this:

```js
node.warn('text', result);
```

Where `result` is optional?

**Comment by ai** [comment]
@ben-eb If `result` is option, so what `node.warn` will do without it?

**Comment by ben-eb** [comment]
PostCSS can infer the result object as the 'current' result.

**Comment by ai** [comment]
But how we can set current result to every node in good way.

**Comment by ben-eb** [comment]
The result is passed in the second parameter of the plugin. So we must know the current result, right?

**Comment by ai** [comment]
Yeap, plugin knows current result. But nodes do not know.

We can save result to every node, but what if plugin will create new node manually, it can loose result link from new node.

**Comment by ben-eb** [comment]
I just thought that it might be nice to have a single parameter with an inferred `result`. I know that plugins can return a new `result` instance but in the majority of cases the `result` will be the same as what was passed in.

But it's not a big deal if this isn't possible with new nodes.

**Comment by ben-eb** [comment]
Fixed in https://github.com/postcss/postcss/commit/0b2d1fbf6b5fb090a98c843ddf14fbea0fc2d1bc.
