### ISSUE TITLE
postcss 4.1 breaks postcss-import

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#290]
I don't know why yet, but I guess the async changes are breaking postcss-import interface.
Several tests are broken.
You should have released this release as major...

**Comment by ai** [comment]
@MoOx if you use sync API, behaviour should be totally same. So we didn’t broke API for major release.

**Comment by ai** [comment]
Can you run tests on sync/async API to detect source of problem?

**Comment by MoOx** [comment]
This release was indeed containing a breaking change: https://github.com/postcss/postcss-import/commit/9fefc4fe92eea46287d7d9d2837353a046313089

Even if minor (undocumented) breaking changes, it's still a breaking change.

Please next time, in doubt, use a major bump.

**Comment by MoOx** [comment]
If you don't call a property to generate lazyresult, you don't have the previous behavior: this looks like a breaking change to me :p

**Comment by ai** [comment]
What changes in PostCSS broke a PostCSS API?

**Comment by ai** [comment]
PostCSS 4.1 passes all PostCSS 4.0 tests. Maybe we broke something, but it is a bug, not a major API changes.

**Comment by lydell** [comment]
I think @ai has been pretty clear that only **documented** stuff is part of the public API, right? And semver only applies to the public API.

What could be improved is perhaps to always start everything non-public with an underscore, so people don't use non-public stuff "by mistake" thinking it is part of the public API.

**Comment by ai** [comment]
@lydell BTW I was a fan of underscore methods, but there are a lot of underscore haters :(.

Right now Guidelines tell that only methods from `API.md` are public. But I am thinking about make privte methods more clear. We can add it to 5.0 if everyone agree.

**Comment by ai** [comment]
@MoOx sorry, I am on conference right now and can’t look in source of postcss-import problem. It was because of changes in some private API?

**Comment by MoOx** [comment]
Checkout my commit guys https://github.com/postcss/postcss-import/commit/9fefc4fe92eea46287d7d9d2837353a046313089

I didn't use anything private. I were just using .process() without calling a property on the result, so no lazyresult were generated (so it seems nothing was actually happening - all the fixed tests were not ending before my fix with update to 4.1).

In a way, looks like a minor breaking change to me. That said I agree it's an edge case because nobody (except maybe for test) should use .process() without actually using the result (sync or async).

**Comment by MoOx** [comment]
My problem is fixed, but I was not sure when I opened the issue.

**Comment by ben-eb** [comment]
@ai I don't have a problem with prefixing private properties with an underscore, it is consistent with other JS modules.

**Comment by MoOx** [comment]
Reminder: I. didn't. use. any. private. things.

**Comment by lydell** [comment]
@MoOx sorry, I misunderstood you before.

**Comment by ai** [comment]
@MoOx can you explain what was broken with postcss-import and 4.1? I agree that it is a problem, but I didn’t understand the source of problem, because I didn’t change API.

**Comment by MoOx** [comment]
Before 4.1 that the snippet below were logging an exception

```js
try {
  require("postcss")()
    .use(function(css) {
     	throw new Error("Oups") 
    })
    .process("a{}")
    // throw exception "oups" without the need of generating a lazyresult by calling .css or similar
}
catch(e) {
  console.log("Hey ho", e)
}
```

With 4.1 we need to generate the lazyresult (by calling .css for example) in order to get the exception throw. I conclude that in a way you have changed how things works under the hood that change the user interface in a way you didn't expected.

**Comment by ai** [comment]
Hm. Yeap. In 4.0 `Result` was lazy too (changed root will stringified only on calling `.css`), but plugins was executed immediately.

**Comment by MoOx** [comment]
Note that I just update cssnext to 4.1 and get one test broken when I pass empty string https://github.com/cssnext/cssnext/blob/12ae1f320fd23f8590d880cad7f18d1bde889146/test/api.js#L19.
I got undefined returned when calling .process("").css :/

**Comment by MoOx** [comment]
Well wait a minute, maybe I said some shit :D
