### ISSUE TITLE
I'm sure there's a better way to do this

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss#293]
New to PostCSS. I think it's a cool project and would love to get better at it but I'm not the best JS developer.

I'm trying to port my [grid system](https://github.com/corysimmons/lost/) to PostCSS. Here's what I have so far:

```javascript
var postcss = require('postcss'),
    autoprefixer = require('autoprefixer'),
    fs = require('fs');


var lost = postcss.plugin('postcss-lost', function() {
  return function (css, processor) {
    css.eachDecl('column', function (decl) {
      decl.before = 'float: left; margin-right: 20px;'; // this is wrong but works
      decl.prop = 'width';
      decl.value = 'calc(100% - 20px)';
    });
  };
});

var processor = postcss([autoprefixer, lost]);

processor.process(fs.readFileSync('app.css'), {
  from: 'app.css',
  to: 'app.out.css'
}).then(function (result) {

  console.log(result.css)
  fs.writeFileSync('app.out.css', result.css);

});
```

Here's the output:

```css
.foo {float: left; margin-right: 20px;width: calc(100% - 20px);
}
```

I'm trying to keep whitespace and it seems to work fine if I exclude the `decl.before` call.

I need to replace instances of `.foo { column: 1/2; }` in my CSS with several declarations, and even some new rules like `.foo:nth-child(2n) { margin-right: 0; }`.

Honestly, I have no idea how to do this. Any suggestions?

**Comment by corysimmons** [comment]
I don't want to use the `@mixin` syntax as I want the grid to be pretty seamless.

**Comment by MoOx** [comment]
My suggestion https://github.com/cssrecipes/grid
:)

**Comment by ai** [comment]
@corysimmons welcome aboard :).

Using `decl.before` is not a good idea. This property contains whitespaces before declaration. For example:

```css
a {
  *content: 'IE hack'
}
```

```js
var decl = root.first.first;
decl.before //=> '\n  *'
```

In PostCSS API you need to insert new `Declaration` nodes. For example, like this:

```js
decl.cloneBefore({ prop: 'float', value: 'left' });
decl.cloneBefore({ prop: 'margin-right', value: '20px' });
decl.cloneBefore({ prop: 'width', value: 'calc(100% - 20px)' });
decl.removeSelf();
```

We use `cloneBefore`, because it was copy `decl.source` and CSS with have correct source map.

**Comment by ai** [comment]
BTW, you should look at [postcss-flexgrid](https://github.com/area17/postcss-flexgrid).

**Comment by corysimmons** [comment]
This is great. Thanks guys!
