### ISSUE TITLE
Error are silently ignored

### ISSUE THREAD

**Issue by 1j01** [postcss/postcss#298]
There's no `node` available to do `node.error`, and errors are being silently ignored.
With replaceValues, there should be a way to throw a `CssSyntaxError` (which should be called `CSSSyntaxError` by the way, since CSS is an initialism) tied to the correct node.
```coffee
css.replaceValues /@([a-z_\-]+)/i, fast: "@", (m, var_name)->
	color_vars[var_name] ? throw new Error "Color variable #{var_name} has not been defined"
```
Why are errors caught and silenced anyways? That can't be good.

**Comment by ai** [comment]
`replaceValue` is just a simple shortcut. If you need something more complicated, you should iterate by declaration manually. It will be very simple, just check `replaceValue` source.

I can't add argument with node, because it is important to have same arguments, that in `String#replace`.

**Comment by 1j01** [comment]
Okay, but errors are silently ignored? What's up with that?

**Comment by ai** [comment]
Do you use Promise?

**Comment by 1j01** [comment]
No. Am I supposed to?

**Comment by ai** [comment]
Nope. Hm, I will look about error silenting on this week.

**Comment by 1j01** [comment]
```coffee
postcss = require "postcss"

module.exports = postcss.plugin "testing123", ->
	(css, processor)->
		throw new Error "The world is ending"
```
Okay, cool.

**Comment by 1j01** [comment]
Oh wait, sorry, I am using promises. I just never have before. Nevermind... :flushed:
