### ISSUE TITLE
simple for loop? Examples?

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss#301]
Not sure whether this is better suited in the postcss-mixins repo? Apologies if so.

My question: is there a defined way (or specific plugin to enable) to write a for loop with PostCSS? Some way to delineate a JS function that will be parsed as JS by PostCSS and output as CSS?

For example some way to section something like this in the CSS file:

````
for (var loopPos = 1; loopPos < 9; loopPos++) {
 return '[data-heading="' + loopPos[i] + '"] { width: ' + loopPos[i] + '0%;';
}
````

Expected output:

````
[data-heading="1"] {
    width: 10%;
}
[data-heading="2"] {
    width: 20%;
}
````
etc etc

I'd like to be able to write this kind of thing 'in place' (as opposed to a gulpfile or the like) so partial files can contain rules applicable to them. 

Is this kind of for loop do-able at present. How should I be tackling this?

**Comment by ai** [comment]
I want to write some `postcss-each` with some iterator for simple task to write them inside CSS.

I think about this API:

```css
@each $i 10 {
    [data-heading="$(i)"] {
        width: calc(10% * $i);
    }
}
```

But right now you need to write cstom plugin, sorry. Maybe after Autoprefixer 5.2 I will finish `postcss-each`.

Or maybe somebody want to create it? @yisibl @ben-eb @antyakushev

**Comment by ai** [comment]
Full API from my draft:

```
@each VAR [FROM] TO [by STEP] {
}
```

**Comment by benfrain** [comment]
That sort of thing would be ideal. Although I'm a little torn. Let me explain.

Part of the attraction of PostCSS for me was the ability to try and use JS syntax/approaches when tackling 'logic' problems in authoring CSS. That way I get better at writing JS, which I can use in both PostCSS and actual JS.

This 'nicer' syntax you suggest is an abstraction that is close to Sass. So then I'm thinking, if all these plugins end up looking and acting just like Sass, I may as well just use Sass.

I realise this may seem a bit odd but I wonder if there is scope for a plugin that just parses blocks of JS inside the CSS as JS and exports it out in that position in the processed CSS.

I don't know, maybe it is just me!

**Comment by ben-eb** [comment]
If you just want to write JS functions, you might just like to write a PostCSS processor instead, because it gives you more flexibility. This function will output the expected behaviour at the bottom of the CSS file that is ran through PostCSS:

```js
var postcss = require('postcss');

var dataHeading = postcss.plugin('data-heading', function () {
    return function (css) {
        for (var i = 1; i < 9; i++) {
            var rule = postcss.rule({selector: '[data-heading="' + i + '"]'});
            rule.append(postcss.decl({prop: 'width', value: (i * 10) + '%'}));
            css.append(rule);
        }
    };
});
```

**Comment by lydell** [comment]
And if that's too verbose for you, there's of course nothing that stops you from writing it in, say, CoffeeScript :)

**Comment by benfrain** [comment]
@ben-eb that syntax is fine, and is exactly the kind of thing I'd like to use. :) 

However, I'd just like the ability to stick that in the CSS file itself so that it gets picked up and parsed. That way, I can keep the pieces of logic inside the partial file it is relevant to (I tend to shard each visual component e.g. `_table-of-contents.css`). That way, when I remove that partial I can also remove loops and the like that are only relevant to that component.

So I guess it's some plugin that can identity something in a comment, pick up the enclosed JS and parse it.

I don't know, does that sound like madness?

**Comment by ai** [comment]
I have too some cases, when custom plugin will be bad solution and loop inside CSS will be more readable.

**Comment by ben-eb** [comment]
@benfrain I'm not sure that writing JS in CSS files is going to be beneficial, in comments less so. It would be akin to writing Ruby code in Sass comments, for all of those times where you need some custom functionality.

@ai I'm not sure I like the `each` identifier for this; this should be reserved for iterating over a collection of items, such as `[1, 2, 3].forEach`. It seems like this should be done with `for` instead. Here is the relevant documentation for it in Sass: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_10

**Comment by ai** [comment]
@ben-eb yeap, maybe `@for` is better name.

**Comment by benfrain** [comment]
Boiling it down I suppose I want to write CSS in my style sheets when being declarative and JS when logic is required. 

I don't want a new pseudo syntax that is neither one nor the other (as is the case with Sass logic already - that knowledge/syntax can't be transported and used elsewhere). 

In a system based in JS it just seems odd to not be able to write JS. But I am naive and don't necessarily appreciate the difficulties in planting JS inside CSS.

**Comment by ben-eb** [comment]
Well, if this were to happen, all JS logic **would have** to be written inside comments, so that PostCSS didn't try to parse it as CSS. At a very basic level:

```css
/*
(function () {
    for (var i = 0; i < 9; i++) {
        return '[data-heading="' + i + '"] { width: ' + i + '0%; }';
    }
})();
*/

h1 { color: blue }
```

Such a parser would have to inspect comments for this syntax, `eval` the result and then replace the comment altogether with the result of the function call. But what about syntax errors? Code highlighting? Having comments inside the function? Having comments *outside* the function? If this were to happen you would probably expect something like this to work:

```css
/*
  Generate headings
  --------------------------
(function () {
    for (var i = 0; i < 9; i++) {
        return '[data-heading="' + i + '"] { width: ' + i + '0%; }';
    }
})();
*/

h1 { color: blue }
```

Then, how do you distinguish from what is part of the comment and what is part of the function call? How do you handle this case?

```css
/*
function test () {
    console.log('.test {}');
}
*/

h1 { color: blue }

/* test(); */
```

This function does not inject anything into the CSS, nor does it call the console log. It just outputs:

```css
h1 { color: blue }

/* test(); */
```

Unless you are to keep some kind of state for all comments, to track function identifiers registered somewhere. It all gets too complicated very quickly.

I think you are better to keep your concerns separate; [write mixins in JS syntax](https://github.com/postcss/postcss-mixins#function-mixin), and then include them in your PostCSS runner. :smile:

**Comment by ai** [comment]
@ben-eb JS in CSS? O_o Why we need it?

`postcss-for` plugin will fix @benfrain needs.

**Comment by ben-eb** [comment]
@ai I was trying to illustrate why you *wouldn't* need it. It's definitely not something that I would want to support. :smiley:

**Comment by benfrain** [comment]
Yes, using comments — I now agree: the syntax highlighting issue alone (with comments) is enough to make me think it's a bad idea at this point.

However, perhaps the parser need not choke on at-rules? Could something like `@parsejs {}` get through the parser and get eval'd back in place?

It just occurred to me that generating any kind of string via programmatic means can be handled by Javascript.  Apparently JS is quite popular ;) If PostCSS ends up having its own (non portable) abstractions for for loops, mixins and the like, it'll be problems that have already been solved that same way with Sass (and LESS and Stylus etc) and they will have all the same kinds of restrictions so authors may as well just use one of those languages instead. 

However, something that enabled full on JS logic (when and if needed) within style sheets just seems infinitely more useful to front-end developers. 

?

**Comment by ai** [comment]
@benfrain problem of Sass is not a special language. Main problem is that they put programming language into CSS.

This is why I think `@parsejs` is a bad idea. Styles mst be declarative.

And it is a main difference between `postcss-for` and `@each` in Sass. Sass is a template language. `@each` is a iterator and it accepts Sass types, like Array.

`postcss-for` is not a statement of programming language. It is not a Turing complete. It is just a short way to write many rules. But it doesn’t allow you to write a program like Sass’s `@each` does.

Same with mixins. Sass’s mixin is a programming language function. PostCSS’s mixin is just a template.

Current PostCSS idea is:

* We have simple declarative task. Like `:nth-child(1) { left: 10px; } :nth-child(2) { left: 20px; }`. And we ses some simple templates (like `postcss-mixins` or `postcss-for`) to write them.
* Other task is complicated and requires a code. Like read a JSON and create a nodes. We uses custom plugins for them.

Putting JS inside a CSS is not a part of this PostCSS philosophy. Stylus should be declarative. Full Turing complete power must be in plugin, that transforms a CSS by pipe.

**Comment by ai** [comment]
BTW. Why you ask for JS in CSS for this simple task like `[data-heading="' + i + '"]`. Simple template based solution like `postcss-for` is totally enough and **much** more readable, that inline JS.

I think inline JS is only a phantom pain of missed Sass, when we mixed programming language and styles :).

**Comment by benfrain** [comment]
@ai you're probably right ;)

**Comment by ai** [comment]
I reopen it for `postcss-for`

**Comment by ai** [comment]
Done. @antyakushev made a [postcss-for](https://github.com/antyakushev/postcss-for)
