### ISSUE TITLE
at-rules don't work with Stylus

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss#306]
I'm trying `@lost gutter 60px`.

Works fine with CSS, but breaks Stylus. Any ideas?

https://github.com/corysimmons/lost/blob/master/lost.js#L30

**Comment by ben-eb** [comment]
*This is not valid CSS*, it's a custom rule which you designed to work with PostCSS.

Using an options object instead would mitigate this issue by declaring variables outside your CSS file.

**Comment by ai** [comment]
You should ask Stylus team for support of non-standard at-rule.
