### ISSUE TITLE
Sass + Autoprefixer + Sourcemaps

### ISSUE THREAD

**Issue by MethodGrab** [postcss/postcss#308]
If there are unicode **symbols** anywhere in the Sass (eg: pseudo element `content` property), it will cause the sourcemap to not appear in Chrome when using `gulp-sourcemaps` with `gulp-sass` + `autoprefixer`.

It seems to be just the symbols, if you replace them with hex representations then sourcemaps work.
It also appears to be autoprefixer related as compiling **with** symbols but **without** autoprefixer **does** show the sourcemap correctly.

I made a reduced test case which demonstrates the issue and has more detail here [MethodGrab/gulp-sourcemaps-test-case](https://github.com/MethodGrab/gulp-sourcemaps-test-case).

Originally issue: https://github.com/postcss/autoprefixer-core/issues/45

**Comment by ai** [comment]
OK, I found a problem. Happy for me, but bad for you is that error is in Sass :D.

When your SCSS contains non-ASCII symbol, Sass will add `@charset "UTF-8";` at-rule to top of file (very right solution). But unfortunately `@charset` logic in Sass doesn’t know anything about source map and doesn’t update it. So we Sass will add `@charset`, it will generate broken source map.

This is Sass only (I removed PostCSS) [mapping vizualization](http://sokra.github.io/source-map-visualization/#base64,QGNoYXJzZXQgIlVURi04IjsKLnQxIHsKICBjb2xvcjogIzAwMDsKICB0cmFuc2Zvcm06IHJvdGF0ZSgzNjBkZWcpOyB9CiAgLnQxOmJlZm9yZSB7CiAgICBjb250ZW50OiAndGVzdCc7IH0KCi50MiB7CiAgdHJhbnNmb3JtOiByb3RhdGUoNzIwZGVnKTsgfQogIC50MjpiZWZvcmUgewogICAgY29udGVudDogJ+KAlCc7IH0KCi50MyB7CiAgdHJhbnNmb3JtOiByb3RhdGUoMTA4MGRlZyk7IH0KICAudDM6YmVmb3JlIHsKICAgIGNvbnRlbnQ6ICdcMjAxMyc7IH0KCgovKiMgc291cmNlTWFwcGluZ1VSTD10ZXN0LmNzcy5tYXAgKi8=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3Quc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtFQUNDLEFBQU87RUFDUCxBQUFXO0VBRVosQUFBRztJQUNELEFBQVM7O0FBSVg7RUFDQyxBQUFXO0VBRVosQUFBRztJQUNELEFBQVM7O0FBSVg7RUFDQyxBQUFXO0VBRVosQUFBRztJQUNELEFBQVMiLCJmaWxlIjoidGVzdC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIudDEge1xuXHRjb2xvcjogIzAwMDtcblx0dHJhbnNmb3JtOiByb3RhdGUoMzYwZGVnKTtcblxuXHQmOmJlZm9yZSB7XG5cdFx0Y29udGVudDogJ3Rlc3QnO1xuXHR9XG59XG5cbi50MiB7XG5cdHRyYW5zZm9ybTogcm90YXRlKDcyMGRlZyk7XG5cblx0JjpiZWZvcmUge1xuXHRcdGNvbnRlbnQ6ICfigJQnO1xuXHR9XG59XG5cbi50MyB7XG5cdHRyYW5zZm9ybTogcm90YXRlKDEwODBkZWcpO1xuXG5cdCY6YmVmb3JlIHtcblx0XHRjb250ZW50OiAnXFwyMDEzJztcblx0fVxufVxuIl0sInNvdXJjZVJvb3QiOiIvc291cmNlLyJ9,LnQxIHsKCWNvbG9yOiAjMDAwOwoJdHJhbnNmb3JtOiByb3RhdGUoMzYwZGVnKTsKCgkmOmJlZm9yZSB7CgkJY29udGVudDogJ3Rlc3QnOwoJfQp9CgoudDIgewoJdHJhbnNmb3JtOiByb3RhdGUoNzIwZGVnKTsKCgkmOmJlZm9yZSB7CgkJY29udGVudDogJ+KAlCc7Cgl9Cn0KCi50MyB7Cgl0cmFuc2Zvcm06IHJvdGF0ZSgxMDgwZGVnKTsKCgkmOmJlZm9yZSB7CgkJY29udGVudDogJ1wyMDEzJzsKCX0KfQo=) that shows my point.

**Comment by ai** [comment]
I can help you when Sass issue report. Just create a issue and put link to Sass issue here. I will repeat all technical info there.

**Comment by MethodGrab** [comment]
Thanks for taking a look at this. After looking though the libsass issues it seems they are already aware of the problem with `@charset "UTF-8"` & sourcemaps (https://github.com/sass/libsass/issues/879)!

**Comment by MethodGrab** [comment]
This has been fixed in `gulp-sass@2.0.0` ([`libsass@3.2.0`](https://github.com/sass/libsass/releases/tag/3.2.0)).
