### ISSUE TITLE
Plugin request: Automatically insert a charset when file contains non ASCII characters

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#309]
Had this idea from the CSSO tracker - https://github.com/css/csso/issues/219 - personally not sure how to implement it, perhaps someone with better knowledge of encoding could tackle this?

I would be interested in bundling this as part of [cssnano](https://github.com/ben-eb/cssnano).

**Comment by ai** [comment]
Nice idea. Also plugin can remove encoding at-rule with utf 8 if file doesn't contain non-ascii symbols.

**Comment by ben-eb** [comment]
@ai Yes, that should definitely be part of this module's responsibility. :+1:

**Comment by ai** [comment]
Maybe we should extend [postcss-single-charset](https://www.npmjs.com/package/postcss-single-charset)

/cc @hail2u

**Comment by hail2u** [comment]
I think converting CSS file into UTF-8 with [iconv-lite][1] etc. is a better solution. Detecting charset and adding correct `@charset` directive is not hard, but CSS files may have different non-ASCII charset and this could be a problem on concatenating.

[1]: https://www.npmjs.com/package/iconv-lite

**Comment by ai** [comment]
We still have no plugins for it? @ben-eb it will be very useful for cssnano?

**Comment by ben-eb** [comment]
No rush.

**Comment by ai** [comment]
I want to close unnecessary issues, maybe I can promote this issue. It seems like very easy for me.

@hail2u should I ask developers to send PR to you or create separated plugin?

**Comment by ben-eb** [comment]
Perhaps we should find some alternative forum to discuss plugin ideas?

**Comment by ai** [comment]
@ben-eb not bad idea :). Any suggestion? Maybe with votes?

**Comment by davidtheclark** [comment]
I could try handling this one within the next few days.

**Comment by ben-eb** [comment]
@ai We could just make a new repo exclusively for this. I don't know of anything better at the moment.

**Comment by andyjansson** [comment]
>CSS files may have different non-ASCII charset and this could be a problem on concatenating.

Is this really a problem, though? I mean, the CSS is converted to an AST before being merged together. Care to weigh in on this @ai @MoOx ?

**Comment by ai** [comment]
@andyjansson missed `@charset` can affect on CSS, for example `::before` `content` can be read wrong.

But unnecessary `@charset` is bad for cssnano. I really-really want to have the best CSS minifier in PostCSS :).

**Comment by andyjansson** [comment]
@ai Perhaps we could have PostCSS identify the charset of the CSS? So, for instance, if we try to add nodes from a ISO-8859-1 document to a UTF-8 document, those nodes would be converted to UTF-8 prior to insertion.

**Comment by ai** [comment]
@andyjansson it is not question about PostCSS insternal JS. It is about browsers and output bundled CSS.

**Comment by andyjansson** [comment]
@ai I know. What I am proposing is having postcss detect the encoding and expose that via the AST. Since we have methods such as `moveTo`, `moveBefore`, `moveAfter` to migrate nodes, we could check the encoding of those nodes and compare it to the destination node prior to moving on with the migration. Having that information would also enable the proposed plugin in this issue to insert `@charset` by simply checking the encoding property of the `Root` node.

**Comment by ai** [comment]
@andyjansson not a UNIX way :). Separated plugin is better.

**Comment by andyjansson** [comment]
@ai What do you mean "not a UNIX way"? I'm not proposing adding automatic `@charset` insertion to PostCSS. That should of course be handled by a plugin.

**Comment by ai** [comment]
@andyjansson So, why we should handle insert methods if we works in plugin?

**Comment by andyjansson** [comment]
I'm saying it should normalize the encoding of node data, not insert a `@charset`.

**Comment by ai** [comment]
@andyjansson How you think to normalize? When you will save CSS on disk, browser need some information to understand bytes encoding. Is it 1 char in UTF-8 or two in ASCII.

**Comment by andyjansson** [comment]
@ai You can check the file header to get a good idea of the encoding. However, if there's a `@charset` in the document you could override it.

**Comment by ai** [comment]
@andyjansson this plugin also should remove `@charset` if it is unnecessary

**Comment by andyjansson** [comment]
@ai Yes, but we're discussing two different things here. At one hand we have the PostCSS API and at the other we have the plugin. The PostCSS API, which I am discussing, could facilitate the plugin.

**Comment by ai** [comment]
@andyjansson just put plugin right after all transformation. Why we need to hook insert methods?

**Comment by andyjansson** [comment]
@ai because if you have two files which different encoding and merge those together, half of the resulting file will have the wrong encoding. Also, I'm not talking about hooking into insert methods, but extending their functionality to handle encoding.

**Comment by ai** [comment]
@andyjansson this plugin is only about reducing file size, not about fixing encoding conficts (it is UTF-8 era :D ).

**Comment by andyjansson** [comment]
@ai I'm just saying it's a related concern and also that my proposed solution could be used to facilitate the plugin by providing it with the information of what encoding is used. That's all.

**Comment by TrySound** [comment]
Done https://github.com/TrySound/postcss-normalize-charset

**Comment by ben-eb** [comment]
:+1:
