### ISSUE TITLE
Remove node.js 0.10 support and Promise polyfill

### ISSUE THREAD

**Issue by ai** [postcss/postcss#311]
I think we should remove node.js 0.10 support in 5.0 (anyway it will be only in the end of summer or later).

**Comment by ben-eb** [comment]
:+1:

**Comment by tunnckoCore** [comment]
:+1:

**Comment by ai** [comment]
I think we can ship it in next 5.0.

**Comment by ai** [comment]
Done f619212

**Comment by bjrmatos** [comment]
don't you think is too early to drop support for node.js v0.10? we had v0.10 for a long time.. i have a bunch of apps done in v0.10 and still want to use next versions of PostCSS. :(

**Comment by ai** [comment]
@bjrmatos you can still use PostCSS, just load Promise polyfill manually. Right now all users get this big polyfill.

**Comment by bjrmatos** [comment]
oh, sorry.. read that title scared me a little :smiley: load the polyfill manually will be documented?

**Comment by ai** [comment]
@bjrmatos thanks for notice, I will add docs later.

**Comment by bjrmatos** [comment]
thnks :clap:

**Comment by ai** [comment]
Done

**Comment by ai** [comment]
@bjrmatos done 7f3838d
