### ISSUE TITLE
Context scoping

### ISSUE THREAD

**Issue by olegstepura** [postcss/postcss#316]
Hi, gyus!

When using pligins like `postcss-mixins` and some other together with `postcss-nested` everything defined in any context becomes available at any nesting level. I suppose that's because there is actually no real nesting levels and also because of an issue https://github.com/postcss/postcss-nested/issues/11

Also some plugin authors have no way of differing selectors (e.g. `h1, h2` vs `h1, h2`, see https://github.com/ben-eb/postcss-discard-duplicates).

My suggestion (as from a side observer, I'm not familiar with your API yet) - maybe it's a good idea to introduce some kind of context scoping for those plugin authors. So that any defined variable, media query or so would be visible only to this selector and child selectors but not any other scope or root. In that case plugin authors could use this context for setting/getting their data in such context. Context inheritance comes into mind.

This change would require parsing selector paths and also should make it possible to compare selectors.

This change would require some changes inside `postcss-nested` for sure, because it should affect contexts.

just thinking aloud, please close if not accepted.

**Comment by ben-eb** [comment]
In my case, postcss-discard-duplicates does not diff selectors because it is not its responsibility. The module is not to know about selectors because it might get it wrong if the logic is not complex enough, so it has to assume that the selectors are normalised beforehand. You may use postcss-minify-selectors for this purpose. And in any case, discard-duplicates is best when it operates on a global context.

**Comment by olegstepura** [comment]
@ben-eb isn't `rule.selectors` from  https://github.com/postcss/postcss/blob/master/API.md#rule-node what is needed?

**Comment by ben-eb** [comment]
I'm not sure I follow. My module is designed to operate on a global context. Other authors may choose to limit their module's scope, for example postcss-mixins only operates in `@mixin` and `@define-mixin` at rules: https://github.com/postcss/postcss-mixins/blob/master/index.js#L109-L117

**Comment by ben-eb** [comment]
@olegstepura Does https://github.com/postcss/postcss-plugin-context solve your issue?

**Comment by olegstepura** [comment]
I don't think adding custom syntax i a good idea. Nested css rules already create logical scope. My initial idea was to reuse this scope.
