### ISSUE TITLE
Slow gulp task when used with sourcemaps

### ISSUE THREAD

**Issue by noahgrant** [postcss/postcss#317]
Hi,

Any particular reason why adding the autoprefixer would triple my sass gulp task?  Here's some sample code:

```js
gulp.task('sass', function() {
  return gulp.src('my-master-sass-file.scss')
      .pipe(plumber())
      .pipe(sourcemaps.init())
      .pipe(sass({
        errLogToConsole: true,
        outputStyle: 'compressed'
      }))
      .pipe(.pipe(postcss([autoprefixer({
        browsers: 'last 3 versions',
        cascade: false
      })])))
      .pipe(sourcemaps.write('./', {
        includeContent: false,
        sourceRoot: '../../src/css'
      }))
      .pipe(gulp.dest('./build/'))
```

If I remove the sourcemaps, task compilation time goes back down to normal; if I remove the autoprefixer, it goes back down to normal. If I have them both, it's 3x.  Any idea why that might be happening?

postcss with gulp-postcss v5.1.3
autoprefixer-core v5.1.11
postcss v4.1.7

Thanks!!

**Comment by ai** [comment]
Can you show me a time information from Gulp with and without source maps.

**Comment by ai** [comment]
But anyway source map generation is complicated, so CSS processing with source maps uses more time by definition.

**Comment by noahgrant** [comment]
well, the time for the task without is ~1s, with is ~ 2.8s.  Yes source map generation is complicated, but even with source maps (and no autoprefixer), my sass compilation is 1s.  The thing is, since it only takes 1s, we rebuild all our sass on every `.scss` file save.  so we run the task quite often.  That's why there's a big difference between 1 and 3s.

It's interesting because if I remove the sourcemaps, as I said, and just use sass + autoprefixer, the build time is 1s.  And if I remove the autoprefixer, and use sass + sourcemaps, the build time is 1s. But all three together is consistently 2.8s.

**Comment by ai** [comment]
Can you show me full Gulp output, because it contains time for each task.

**Comment by noahgrant** [comment]
i'm only running this task, so it doesn't show any more useful output.

ie it says:

```
$ gulp sass
$ [21:41:54] Using gulpfile ~/path/to/gulpfile.js
$ [21:41:54] Starting 'sass'...
$ [21:41:55] Finished 'sass' after 922ms
```

and for the case with all three:

```
$ gulp sass
$ [21:43:47] Using gulpfile ~/path/to/gulpfile.js
$ [21:43:47] Starting 'sass'...
$ [21:43:50] Finished 'sass' after 922ms
```

**Comment by ai** [comment]
OK, I will create a internal benchmarks to find a source.

**Comment by noahgrant** [comment]
Thank you!!

**Comment by noahgrant** [comment]
did you figure out the reason for its slowness?

**Comment by ai** [comment]
Because of source maps :D. Source map generation is a slow by nature. When we have several processing steps, we need to merge mapping from steps and it is complicated process.
