### ISSUE TITLE
Benchmark cannot be run with fresh checkout

### ISSUE THREAD

**Issue by xzyfer** [postcss/postcss#318]
I've tried running the benchmark and run in to a few road blocks. Ideally there'd be an npm script (or something) that bootstraps a benchmark environment for repeatable results across machines.

Some of the things that block the benchmark being run atm 

- missing node-sass, less, myth, stylus install
- missing bootstrap.css and bootstrap.scsss
- missing `../build.js` (`require('../build');`)

**Comment by ai** [comment]
Just move dependencies from `benchmarkDependencies` to `devDependencies` and run `npm install`.

Next you can run benchmark by `gulp bench`.

**Comment by ai** [comment]
I uses `benchmarkDependencies` because `node-sass` need too many time to compile. Most of Travis CI runs fails because of the `node-sass`. And many times `node-sass` was broken with some of io.js version. So it is very difficult to install all benchmark dependencies on every `npm install`.

**Comment by ai** [comment]
We can put Benchmark Run Instructions in some place. Where we should puut them?

**Comment by xzyfer** [comment]
The easiest thing would be have an npm script 

```
npm run benchmark
```

that could the the initialisation, and run the benchmark.

**Comment by ai** [comment]
Nice suggestion. I am waiting for PR ^_^.

**Comment by xzyfer** [comment]
I'm still trying to get it all running :)

If I'm reading the code correctly the benchmark is also implicitly bias to node libraries. I think we can improve this as well. I'll PR some stuff when I get it all working.

**Comment by ben-eb** [comment]
What about a separate repository for this?

**Comment by ai** [comment]
@ben-eb I didn’t like this idea, because benchmark is like a tests for me. Should be with code. But if we will not have any other solution, we can think about it.

BTW, I have a dream to make a CI for benchmarks for PostCSS and its plugins. To find perfomance regression.

**Comment by ben-eb** [comment]
@ai I think a performance benchmark for PostCSS inside PostCSS is fine and should be part of test suites. But, comparing against other processors should be a separate module. This means that you can lock CI down to node 0.12 if you are having issues with iojs builds, and this doesn't affect the main PostCSS module. :smile:

**Comment by ai** [comment]
@ben-eb yeap, it is a good reasons. Let me think.

**Comment by ai** [comment]
@ben-eb I love more and more idea of separate repo for benchmark. But main reason of benchmark is PostCSS optmizations. So I need to works is PostCSS sources, compile ES6 and run benchmark. How we can do it with separate repo? GitHub link in bbenchmark’s `package.json` is a bad idea, because I need some feedback before commit.

**Comment by xzyfer** [comment]
@ai you could make the benchmark repo an npm dev dependency

```
  "devDependencies": {
    "postcss-benchmark":"postcss/postcss-benchmark"
  }
```

This syntax pulls the latest master from git at `npm install` time. This also means you can iterate quickly in dev by using `npm link`.

**Comment by xzyfer** [comment]
I separate repos is definitely the way to go. It would be great to be able to open issues and PRs specifically against the benchmarks with increasing the postcss S:N

**Comment by ai** [comment]
@xzyfer `npm link` is awesome, I missed it. OK, I will create a repo on this weekend.

**Comment by ai** [comment]
Done https://github.com/postcss/benchmark
