### ISSUE TITLE
Plugin Guidelines discussion

### ISSUE THREAD

**Issue by ai** [postcss/postcss#319]
Here is a current draft of [PostCSS Plugin Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md). I just finish first version of draft and totally open for any feedback. What we should add, remove, change?

This document is only for mandatory rules. We will have separated document for Best Practices (like “try to use W3C draft instead of own syntax”).

I think my draft contains too any grammar mistakes. Let’s fix them after we will fix document content.

This rules will be mandatory for all plugin developers. Speak now or forever hold your peace.

/cc @MoOx @ben-eb @yisibl @morishitter @davidtheclark @antyakushev @btholt @magsout @corysimmons @jo-asakura @simonsmith @pascalduez @iamvdo @geddski

**Comment by ben-eb** [comment]
I think we need to make https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin *optional* for plugin packs such as cssnano, until there is some built in way in PostCSS to create a wrapper module. Such as when fixing https://github.com/postcss/postcss/issues/280

The rest of the guidelines look good to me.

**Comment by MoOx** [comment]
It looks good @ai, good job !

Some comments:

> If you wrote a polyfill for

We only wrote transpiler, using the term "polyfill" is wrong imo.

> For example don’t use fs.writeFile instead of fs.writeFileSync:

I guess you want to say the opposite: "For example, use `fs.writeFile` instead of `fs.writeFileSync`)"

> Maintain a changelog

We should totally mention semver !

> 4.4. postcssplugin keyword in package.json 

why not "postcss-plugin" ?

**Comment by davidtheclark** [comment]
Looks great to me.

**Comment by simonsmith** [comment]
:+1:  Nice job

**Comment by ai** [comment]
@MoOx 1, 2 and 3 is fixed, thanks.

We decided to use `postcssplugin` because Gulp has same naming.

**Comment by ai** [comment]
@ben-eb `postcss.plugin` add a API and plugin name and PostCSS version. We can allow to add this nodes manually. But maybe we should fix `postcss.plugin` for you case.

I think I fix that issue, that you mentioned. Can you check, have we a problem right now?

**Comment by tunnckoCore** [comment]
> why not "postcss-plugin" ?

:+1: 

> because Gulp has same naming.

and why we should follow gulp?!

**Comment by ai** [comment]
@tunnckoCore @MoOx yes, I think `postcss-plugin` is more readable. But maybe dash has some problem. Here is old discussion about keyword: https://github.com/postcss/postcss/issues/181#issuecomment-74409398

The main reason is that it is a common way: `gruntplugin` also has no dash.

@hail2u does dash has some problems in npm?

**Comment by tunnckoCore** [comment]
> does dash has some problems in npm?

what problems? nope, try https://www.npmjs.com/browse/keyword/gulp-plugin

As of the plugin guidelines lgtm except grammar errors and

```
postcss([ plugin ])       // Bracket-less call
postcss([ plugin(opst) ]) // Brackets call to set options
```
We need CONSISTENCY, dont support it in official guidelines.

**Comment by tunnckoCore** [comment]
there's no such thing like "too many brackets" as you mention somewhere.

**Comment by ai** [comment]
@tunnckoCore OK, I will change keyword.

You can find many issue reports in GitHub and Twitter when users forget to add brackets. What consistence API do you suggest?

**Comment by tunnckoCore** [comment]
> OK, I will change keyword.

first check your eco system and then decide

**Comment by tunnckoCore** [comment]
> What consistence API do you suggest?

im no saying to drop it from the api, just dont show/support it in official guidelines and the community won't do it in future and in one point in future we will be able to deprecate it.

**Comment by tunnckoCore** [comment]
it seems
https://www.npmjs.com/browse/keyword/postcssplugin
https://www.npmjs.com/browse/keyword/postcss-plugin
both aren't used in many many plugins

**Comment by ben-eb** [comment]
Agreed with @tunnckoCore - I am only doing this in my README because it is sort of an expected behaviour for PostCSS processors to support method invocation without parentheses. I would much prefer to write a README like so:

```js
var processor = require('postcss-processor');
var postcss = require('postcss');

console.log(postcss([ processor() ]).process('h1{color:red}').css);
```

Also - I use `postcss-plugins` as keyword because a lot of plugins were already under that namespace.

**Comment by ai** [comment]
@tunnckoCore if I will not promote brackets-less API more users will have this issue. It will promote PostCSS as tool that doesn't work.

Theoretically ideas should be created to have practice result. There is no sense in consistency if it produces user problems.

**Comment by ai** [comment]
We can throw a error if plugin returned a functions (if user forgot brackets). But here we will have conflict with other API best practices: "good API should not let user to make a mistake".

**Comment by ai** [comment]
@ben-eb your example is not honest ;-). In real world users have a big list of plugins. So they will not save them to variables and will call `require('plugin')` right into a plugins array. And `require('plugin')()` doesn't look so nice add in your example ;-).

**Comment by ai** [comment]
Also we need to change runner keyword to `postcss-runner` but we has only 4-5 runners, so it will be easy.

**Comment by ben-eb** [comment]
@ai I am only thinking in terms of consistency with other JS projects, for example a gulp plugin that would use this syntax: https://github.com/ben-eb/gulp-uncss

**Comment by ben-eb** [comment]
@ai Also, we should encourage users to use something like https://github.com/TrySound/postcss-load-plugins - where plugins can be lazily loaded, rather than all required in a huge block at the top of the file.

**Comment by ai** [comment]
@ben-eb Gulp doesn't has big lists of plugins, because it has separated tasks.

**Comment by tunnckoCore** [comment]
> I use postcss-plugins as keyword because a lot of plugins were already under that namespace.

yea, but not good thing. actually finally the package is plugin, so `postcss-plugin` seems better, no matter it is complex of plugins.

> Theoretically ideas should be created to have practice result. There is no sense in consistency if it produces user problems.

i'll repeat again. im not suggesting to break the API, throw errors and etc, only not promoting in official guideline, then there won't have problems and more issues in the issue tracker.

> doesn't look so nice

nice.. inconsistency also is not nice as @ben-eb mentioned somewhere

```js
var postcss = require('postcss');

postcss([
  processor1({foo: 'bar'}),
  processor2,
  processorThree({opts: true}),
  processorFour({bar: 123}),
  processor5,
])
```

**Comment by tunnckoCore** [comment]
> users use single package that you create, no every postcss plugin that you use in your package through your package.

damn, that sucks, lol

I mean, users of `cssnano` use it as is, packaged. they not use `postcss-minify-selectors` through css nano like

```js
cssnano.minifySelectors()
```

**Comment by tunnckoCore** [comment]
> also two keywords would be confusing. actually npm search would find your if it have postcss-plugins keyword, imho.

hmm, nope, not true

**Comment by MoOx** [comment]
what about just "postcss" as a keyword ?!

**Comment by ben-eb** [comment]
^ :100:

**Comment by ai** [comment]
@MoOx we have different tools in PostCSS ecosystem, so we need to specified what kind of tool it is. For example, `postcss-load-plugins` will also have a `postcss` keywords. Even a PostCSS has `postcss` keyword :). So we can’t make a plugins list dynamically.

@tunnckoCore @ben-eb I changed keyword to `postcss-plugin` and `postcss-runner`.

@tunnckoCore I removed a API examples fro `postcss.plugin()` rule.

f00c76a

**Comment by ai** [comment]
So, we are close all current question or I forget someone?

Tomorrow and in Tuesday I will promote discussion in Twitter.

**Comment by tunnckoCore** [comment]
:+1: :100:

**Comment by btholt** [comment]
This all looks good to me. I'll have to make some changes but that's not a bad thing.

My only suggestion to put somewhere for people to tag their npm versions on GitHub so users can easily go back and find the code for the version they're looking for (something else I'll need to do. :smile:)

**Comment by btholt** [comment]
Also, the way of declaring plugins using `postcss.plugin( … )` has the adverse side-effect of making my project depend on PostCSS itself while previously it was only a dev dependency for testing. Shouldn't be a big deal but worth mentioning.

**Comment by pascalduez** [comment]
A  bit late to the party but looks good to me! Thanks @ai for starting those guidelines.

Happy to see a consensus on the `postcss-plugin` keyword, I will update my packages.

Agree that this kind of syntax causes confusion:

```js
postcss([
  processor1({foo: 'bar'}),
  processor2,
  processorThree({opts: true}),
  processorFour({bar: 123}),
  processor5,
])
```

But well...

**Comment by hail2u** [comment]
`postcss-plugin` keyword also looks good.

**Comment by ai** [comment]
@pascalduez really code will be:

```js
postcss([
  require('processor1')({foo: 'bar'}),
  require('processor2'),
  require('processorThree')({opts: true}),
  require('processorFour')({bar: 123}),
  require('processor5'),
])
```

**Comment by ai** [comment]
@btholt what problem we possible may have from PostCSS in dependencies?

`postcss.plugin` will also save a used PostCSS version. So if we break a API in 5.0, we will be able to find plugins for 4.x and give the some kind of proxy with downgraded API.

**Comment by ai** [comment]
@btholt I love git tags too. Does we have any other guidelines, which asks to crate tags?

**Comment by ben-eb** [comment]
@btholt @ai We could recommend users to use the `npm version` command to automatically tag their releases. I run this on every publish to npm:

```
npm version X.X.X && git push --follow-tags && npm publish
```

**Comment by pascalduez** [comment]
> really code will be:
```js
postcss([
  require('processor1')({foo: 'bar'}),
  require('processor2'),
  require('processorThree')({opts: true}),
  require('processorFour')({bar: 123}),
  require('processor5'),
])
```

Uh yeah, damn copy paste and lack of :coffee: 
 That's the way I use plugins anyway. Nevermind.

**Comment by MoOx** [comment]
The problem about the plugin usage confusion isn't new.
Note that es6 will change the game since import must be at the top of the file.
That's why I asked for every plugin to use function so we use brace all the time.
There is plenty of example of this kind of issue since rework exist.

...This old thread https://github.com/postcss/postcss/issues/149#issuecomment-71493152

Still relevant.

_All gulp plugin use braces, am I right ?_

**Comment by MoOx** [comment]
Reminders
- https://github.com/ianstormtaylor/rework-color-function/issues/6
- https://twitter.com/jongleberry/status/496552790416576513
- https://github.com/postcss/postcss-color-function/issues/6
...

**Comment by ben-eb** [comment]
> All gulp plugin use braces, am I right ?

I've written and contributed to a lot of gulp plugins. They *always* use parentheses.

**Comment by ai** [comment]
@MoOx why you didn't get the links when users can't understand why PostCSS plugins doesn't work, because they forgot brackets? ;-)

**Comment by ai** [comment]
@MoOx yeap, ES6 imports are good point. Thanks for notice.

I can agree to promote brackets version in docs, but we need to have bracket-less fallback.

Also `postcss.plugin()` is not just for bracket-less API. It also saves plugin’s PostCSS version to warn users about versions conflict on plugin error. Also `postcss.plugin()` saves plugin name, so if some pluugins has conflict, they can warn users.

**Comment by ai** [comment]
@btholt BTW, ClojureWerkz’s recommendations already mentions tags, so we can miss it from rules.

**Comment by RnbWd** [comment]
I'm writing a plugin - [postcss-component](https://github.com/RnbWd/postcss-component)  - unpublished, unconventional. The goal is transforming css components into javascript objects, and I'm trying to figure out the best way to export the js object. At the moment (for testing purposes) I'm adding it to `result` as an additional method `result.styles` - but that breaks API guidelines.. I assume. Just wondering. 

Eventually I'll map it onto React components and generate js files - this is the first building block of that process.

**Comment by ai** [comment]
@RnbWd yo can save `.styles` file directly in your plugin.

Or you can use `result.messages` array. It is used for plugin communications.

**Comment by RnbWd** [comment]
Okay, I added the style in `result.messages` - but trying to simplify css to js conversion in [postcss-js-styles](https://github.com/RnbWd/postcss-js-styles) - added method `result.toJS()`. Nothing is published yet still experimenting with the concept.

**Comment by ai** [comment]
@RnbWd if you have time to wait, there will be better way to do what you want.

PostCSS 4.2 will have a Custom Syntax. For example, we can build a custom parser to read some syntax sugar like Stylus. Or to process SCSS.

But we will ba able to make a custom stringifier too (for example to move CSSComb on PostCSS). So you will create just a custom stringifier to create a JS object.

**Comment by tunnckoCore** [comment]
@RnbWd not good idea to slice first character if it is dot or hash, lol. It wont be so easy as you expect, believe me. Dont forget that js have overriding.
But yea, this discussion isnt for here.

**Comment by RnbWd** [comment]
@ai I'll wait before publishing anything, custom syntax sounds interesting.

@tunnckoCore I'm well aware of the limitations and I'm not trying to discuss issues with that library here. I'm trying to discuss the semantics of exporting non-css output in a way that'll play nicely with other plugins and follows the guidelines.
