### ISSUE TITLE
Documentation is a little misleading

### ISSUE THREAD

**Issue by matthew-dean** [postcss/postcss#320]
On the readme, it says:

> PostCSS transforms are often more powerful than preprocessor equivalents. For example, Autoprefixer would be impossible with preprocessors.

I wonder what you mean by this? To my knowledge, there aren't any CSS transforms that you can't perform in Less.

Specific to your example:

https://github.com/less/less-plugin-autoprefix

**Comment by ai** [comment]
`less-plugin-autoprefix` just run a PostCSS with Autoprefixer after LESS.

**Comment by ai** [comment]
In preprocessors you can create a mixins with a prefixes. You can’t take a CSS syntax tree and try to find any `box-sizing` properties. Does I understand it right?

**Comment by matthew-dean** [comment]
Well, with Less plugins, I think you can manipulate the AST however you please, including searching for properties and performing actions based on those conditions, but I could be wrong. PostCSS looks like a more straightforward approach (and no doubt it's currently faster), but since Less 2.0, you can add pre-process and post-process plugins, and the post-process can be before or after the CSS is generated, if I recall correctly.

So, in Less, plugins allow you to manipulate the tree after it has been parsed and before the CSS has been generated, or further alter the CSS before it is output.

**Comment by ai** [comment]
@matthew-dean I am more Sass user, so maybe I have a mistakes in Less API.

Can you show me a docs, how I can read and change CSS AST by Less?

**Comment by ai** [comment]
I found the `addPostProcessor` but this post-processor receives a CSS string. So it is still impossible to do Auutoprefixer. Because you can’t make a such complicated thing on regexps. This is why PostCSS has a parser and CSS nodes object API to manipulate with CSS nodes tree.

And this is why Less (as I saw by tests) is not even close to [Rework/PostCSS postprocessing idea](http://tjholowaychuk.tumblr.com/post/44267035203/modular-css-preprocessing-with-rework).

**Comment by matthew-dean** [comment]
> So it is still impossible to do Autoprefixer. 

o_O .... It's not impossible, it will just parse twice.

What if we worked out a format for a CSS AST, similar to how Mozilla did with the SpiderMonkey AST for JavaScript?

**Comment by ben-eb** [comment]
It is impossible to do **inside Less itself**, which means that the statement is not misleading. Such a transformation requires you as a developer to parse the CSS from the Less output, modify it and then stringify it again, using some outside means. PostCSS already provides you with a CSS AST which you can modify using plugins.

**Comment by seven-phases-max** [comment]
@ben-eb

>It is impossible to do *inside Less itself*,

*Before* making such statements I'd suggest you to learn Less sources. You can write a plugin to manipulate every single bit of the parsed CSS AST and manipulate it at every possible CSS entity resolution level (starting from single properties and its values and ending with the final CSS output string (that string is what the `addPostProcessor` thing mentioned by @ai is for.. it's just a hook to chain an *external* processor)).

So not commenting anything else of this issue I'm just remarking Ben's totally wrong declaration (for examples on manipulating the Less AST items see https://github.com/less/less.js/issues/2371 etc.)

**Comment by ai** [comment]
@seven-phases-max where I can read a docs about working with Less AST?

**Comment by seven-phases-max** [comment]
@ai There's no. Simply because Less was made and developed primarily as a language not as a CSS processing core.

**Comment by ai** [comment]
@seven-phases-max undocumented API is not “we has full postprocessing support” ;).

Maybe you can suggest better sentence to tell that idea ore correctly?

**Comment by ben-eb** [comment]
@seven-phases-max You are talking about an undocumented, internal API. If Less is not intended to be used this way, then my statement still stands.

**Comment by seven-phases-max** [comment]
@ben-eb  Now you just sound ridiculous.

**Comment by matthew-dean** [comment]
C'mon guys. The point is that saying "Autoprefixer would be impossible with preprocessors" is a completely false statement. It's fair to say it's difficult or undocumented with certain preprocessors, but there's no "intention" that people do not. Your claim is that there is an inherent design difference that makes this achievable and unachievable by everyone else, when, in fact, both Less and PostCSS parse a "pseudo-CSS" language, and transform that to a browser-consumable CSS document. Both allow plugins to manipulate the language input, and transform the result.

It's possible PostCSS has a better architectural approach, and I think it's fair that the plugin process is better documented, since plugins only recently arrived in Less 2.0 and are, as of now, largely undocumented. PostCSS has a lot of pluses, so I don't understand the desire to lie about what's technically possible. Why not just say, "We believe we have a better pre-processor architecture" instead of making claims that other preprocessors can't do things that they clearly can?

I think Less.js can learn from (and often does) the way other libraries find solutions to the same problems, just like there are likely several advantages that Less might have over other preprocessors, but Less doesn't have any documentation that says that those advantages are completely unachievable by others, as such statements would tread into a territory of arrogant grandstanding. The nature of open source is that we all find better solutions together, faster, and that we do so by forming supportive networks. But it's up to individuals in those communities to make that possible. Each project sometimes has it's own maturing process, so best of luck.

**Comment by ben-eb** [comment]
I think you have a fair point, which is that it is unfair to say that you absolutely cannot do this with another tool. I think the original intent behind this type of wording was to say that PostCSS makes such transformations easily, because its architecture is very much built on this idea of transforming an AST in memory, and is not built in a way that a 'classic' preprocessor is. For example, mixins, variables and the like are not baked into PostCSS, although there are plugins to do so.

I think this sentence has touched a nerve, which was not its original goal. Personally I would be happy to update the language so that it is less arrogant. What do you think, @ai?

**Comment by ai** [comment]
@matthew-dean I am not against text changes. You can saw it above. But I can still understand what Less plugin API gives. Where I can get full methods list. Maybe you have a tests, where I can read about this API? Does they update source maps? Does it has access to full AST?

@ben-eb there is really not way to do Autoprefixer in Stylus and Sass. I migrated from Sass because there is really no way.

**Comment by seven-phases-max** [comment]
* [For plugin authors](http://lesscss.org/usage/#plugins-for-plugin-authors)
* minimal AST visitor plugin [in tests](https://github.com/less/less.js/blob/master/test/plugins/visitor/index.js).
* compiler's own AST visitor [modules](https://github.com/less/less.js/tree/master/lib/less/visitors) using *the same* API (it's not really "internal" or "external")
* real plugin using the same API [less-plugin-inline-urls](https://github.com/less/less-plugin-inline-urls).

**Comment by ai** [comment]
@seven-phases-max OK, I read all your examples. Does I understand right, that plugin can subscribe on parse a function or rule event (like in SAX parsers) and event listener can return new nodes to replace parsed?

But what if I need to look around the parsed node? For example:

```
a {
    tab-size: 4px
    -o-tab-size: 5px;
}
```

should be compiled to:

```
a {
    -moz-tab-size: 4px;
         tab-size: 4px;
    -o-tab-size: 5px
}
```

So, when we get `tab-size` we need to look forward for vendor-spefic hacks.

How I can do it with this SAX-like parser?

**Comment by seven-phases-max** [comment]
A plugin can subscribe to any tree node not just a rule... Hence you can just take all the rules in a ruleset and perform any transformation on those (e.g. add/remove/replce/merge/whatever). Technically every tree entity has its corresponding `visit` function.

**Comment by ai** [comment]
So I can get all nodes by `visitRuleList`? And there is some `node.source` to set origin node?

**Comment by ai** [comment]
What about this changes? https://github.com/postcss/postcss/commit/859b34f3a7282eecae5fbc408de920a0c1b84916

**Comment by seven-phases-max** [comment]
@ai  
>And there is some  node.source  to set origin node?

Sorry, I'm sure I understand what would `origin node` mean there. By defining `visitRuleset` you'll get all rulesets of the tree (so you are on your own to decide which of those to modify). Though this is also set by the plugin itself (`root` [there](https://github.com/less/less.js/blob/master/test/plugins/visitor/index.js#L9) is the complete `tree` node, so technically you can run another visit handler for any subtree/node when/if necessary). There're no specific limitations or requirements or conventions, everything is just plain JS objects and arrays. All modifiable (provided that you won't break anything further in the chain).

**Comment by ai** [comment]
@seven-phases-max I mean how you will generate a source map. For example, you need to know, that `-webkit-transition` source if `transition` property.

**Comment by davidtheclark** [comment]
I wonder if the real problem here -- the sticking point for the Less fans -- lies in the words "more powerful." Those words imply that Sass/Less and PostCSS are trying to do the same thing but PostCSS is doing it better. That kind of argument is bound to become a mess.

Instead, maybe the sentences at issue could be rephrased so they are emphasizing how PostCSS is uniquely open-ended because it is an engine for plugins rather than a superset langauge. (Sure, Less may be working on an interface for open-ended plugins, but its core feature is undoubtedly its language, right? Besides, this sentence does not have to be about comparison: it can promote PostCSS without diminishing Less.)

For example, maybe something like this could replace the "New abilities" point?

> Unlimited possibilities: PostCSS can power an unlimited variety of plugins. They can extend the CSS language (as Sass and Less do), transform cutting-edge CSS into browser-friendly syntax (e.g. Autoprefixer), lint and analyze stylesheets, and more.

**Comment by seven-phases-max** [comment]
@ai Ah, I see. Yes, nodes have their source file/line fields (when applicable) so you just copy these to derived nodes.

**Comment by ai** [comment]
@davidtheclark we already mention “cssnext” features in second section “Future CSS”.

**Comment by davidtheclark** [comment]
I know, and I might organize it differently myself or the suggestion I have could be rephrased; but my main point is making this focus on "Unlimited possibilities" instead of "more powerful".

**Comment by ai** [comment]
@davidtheclark there are limits technically :).

**Comment by ai** [comment]
@davidtheclark I am open to change features structure. What do you suggest?

**Comment by davidtheclark** [comment]
Maybe that's for another discussion :) My attempt to contribute here was just to suggest a way to avoid a pissing match. Any bad-mouthing I've seen about PostCSS so far seems to have been provoked by these kinds of competitive statements, which diminish other tools and make those tools' authors and users defensive and annoyed. Maybe you and @matthew-dean et al. can indeed work out a clear, acceptable statement about the differing "powers" of Less and PostCSS that pleases everybody; but I'd be surprised. I wonder if the more efficient tactic, which might appeal to more Readme readers and better clarify what PostCSS is about, would be to emphasize that PostCSS enables unlimited possibilities.

To finish the thought, though: Personally, I might use the unlimited possibilities point (maybe note cssnext within it), remove the "Future CSS" point (which is just one of the unlimited possibilities), and if you want a third point add something about how the modularity of plugins means they are easy to create and contribute to (they don't live in a large and intimidating repository like the Less/Sass languages). But we've probably gone over this in the past and you have a different vision, which is fine :) I just thought I'd throw in my two-cents.

**Comment by ai** [comment]
@davidtheclark what about:

> **New abilities:** PostCSS plugins can read and change every part of CSS. It makes possible many new classes of tools. Autoprefixer or `postcss-colorblind` are a good examles.

**Comment by davidtheclark** [comment]
That sounds better to me --- the key being "It makes possible many new classes of tools."

**Comment by matthew-dean** [comment]
Well, to me as an outsider, my perception is that PostCSS's unique value proposition is its modularity and well-documented API. So, for a developer tailoring a preprocessor environment for their particular needs, they can structure a "stack" of PostCSS plugins that meet their needs (much like gulp streams, that have standardized input / output), or extend tools if they need to.

The appeal of PostCSS is obvious. It's not that it does something no pre-processor has ever done or supported, but the key advantage is that its designed to be inherently modular and customizable, and as a result, has built up a significant library of PostCSS modules.

Less has a different unique value proposition, but that would be my take.
