### ISSUE TITLE
Smarter rule.selectors setter join

### ISSUE THREAD

**Issue by ai** [postcss/postcss#329]
`rule.selectors` always uses `", "`, maybe we should add some smart logic to use or not space.

**Comment by ai** [comment]
If selector hasn’t `,`, we can use `rule.between` to select `", "` or `","`.

If selector has `,` we should use it, for example ",\n".

**Comment by ai** [comment]
https://github.com/TrySound/css-list

**Comment by lydell** [comment]
Oh, so you've changed your mind since #37? I'd suggest to fix this by doing https://github.com/postcss/postcss/issues/76#issuecomment-52617716.

**Comment by ai** [comment]
@lydell yeap, right now we have time for this :D

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser supports 1:1 parse/stringify of selectors. Related: https://github.com/postcss/postcss/issues/235

**Comment by ai** [comment]
What you think about fixing it ok merging with your awesome parser? :-)

**Comment by ai** [comment]
BTW, can you make a PR with link to your parser in any related sections in API docs?

**Comment by ben-eb** [comment]
Yeah, no problem. Let's get people using the parser and trying out its features before we merge it into PostCSS. I think 6.0 might be a nice release for it, as there are already enough features we have to refactor in 5.0. :smile:

**Comment by ai** [comment]
Done 8fdd17b

In 4.3 I think we can use @ben-eb smarter solution
