### ISSUE TITLE
PostCSS plugins website?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#333]
At the current pace of development, containing every plugin in the README is going to be unsustainable. I think we need a site to collect all of the PostCSS plugins, which should offer a search functionality, and example recipes for different use cases for plugins. For example, quick benefits to using modules like `postcss-plugin-context` with `postcss-simple-vars`, or using `postcss-simple-vars` with `postcss-map`, or "building your own preprocessor" with the relevant plugins.

Some of the nice similar resources are http://perf-tooling.today/tools and http://gulpjs.com/plugins/ - but I feel like something that's not just a localised npm search would be really beneficial.

What features would you like to see in an official PostCSS plugin website?

**Comment by ai** [comment]
My current plans to start building a PostCSS after Autoprefixer 5.2 release.

**Comment by ai** [comment]
Also we need a PostCSS playground with ability to use any set of plugins.

**Comment by MoOx** [comment]
a PostCSS what ?
website ? lang ? :)

**Comment by ben-eb** [comment]
@MoOx :grinning:

**Comment by whdigger** [comment]
Great idea =) and in the futures to do something like automatic travis ;)

**Comment by ai** [comment]
@whdigger what do you mean?

**Comment by simonsmith** [comment]
You could certainly start with something like the gulpjs list, would be better than the current README setup.

> Also we need a PostCSS playground with ability to use any set of plugins.

+1

**Comment by ai** [comment]
@simonsmith BTW, why you think that Gulp list is better, that current categorized list (in current size)?

**Comment by whdigger** [comment]
something like this
The user downloads the src PostCss syntax and the output gets :sparkles: css

**Comment by tunnckoCore** [comment]
@whdigger erm? again? Maybe you mean online demo for converting postcss to css?

**Comment by simonsmith** [comment]
@ai Mainly for the ability to filter but also being able to send someone to a proper plugins page, rather than hunting around in a large README.

**Comment by ai** [comment]
@simonsmith search is very good for some case. But not for cases, when you didn't know what to search (it is a popular case in PostCSS, because it is a new tool class).

I am thinking right now, how to join benefits of categorized list with autogenerated pages like Gulp plugin list.

BTW, do you know, that you can send a anchor link to any section on GitHub's READMEs?

**Comment by ben-eb** [comment]
> But not for cases, when you didn't know what to search (it is a popular case in PostCSS, because it is a new tool class)

That's why I think having input and output examples should be done on the website, as well as recipes for more complex usage. :smile:

**Comment by simonsmith** [comment]
@ai Yep, linking to headers is handy. Perhaps we could encourage a keyword in the package.json (shortcuts, optimisation etc)? Tricky to get consistent though.

One benefit of searching via npm is finding plugins that were not submitted to the list. As an example I found [this plugin](https://github.com/cuth/postcss-pxtorem) that wasn't in the list, but was very useful to me.

Also I'm sure a proper site will help cement PostCSS as a viable option to many existing pre-processor users.

**Comment by ai** [comment]
@simonsmith yeap, autolist is better. But right now I manually watch for new PostCSS plugins. I didn't add that plugin, because we already have pixrem. But seems like postcss-pxtorem now much powerful. Does it better that pixrem?

**Comment by simonsmith** [comment]
I think pixrem is subtly different in that it converts `rem` to `px` but pixtorem converts `px` to `rem` which is useful.

To be honest it could be one plugin, perhaps I will suggest it on the pixrem repo.

**Comment by iamvdo** [comment]
@simonsmith https://github.com/robwierzbowski/node-pixrem/issues/31

**Comment by ai** [comment]
@simonsmith ouh, I misunderstood plugin task. What is a point to converting all sizes to rem?

**Comment by simonsmith** [comment]
Thinking in pixels is easier, but using rems is nice for relative sizing. As mentioned in [this comment](https://github.com/robwierzbowski/node-pixrem/issues/31#issuecomment-87113776).

Looks like it won't happen according to that thread, so I'll stick with the other plugin. I don't want to take this off topic any further heh :)

**Comment by ai** [comment]
Close for 391
