### ISSUE TITLE
Pixrem is not a postcss plugin

### ISSUE THREAD

**Issue by ismay** [postcss/postcss#334]
It's listed in this repo's readme as a plugin, but doesn't work with ember-cli-postcss (whereas other postcss plugins that I'm using with it work just fine). I've checked the pixrem source code, and pixrem doesn't seem to export a postcss plugin like postcss-custom-properties does for example:

https://github.com/postcss/postcss-custom-properties/blob/master/index.js#L119
```javascript
// this works with ember-cli-postcss
module.exports = postcss.plugin("postcss-custom-properties", function(options) {
  // etc.
}
```

Instead it seems to use postcss for *internal* processing, but it doesn't export the functionality as a standard postcss plugin (but more as a general node library):

https://github.com/robwierzbowski/node-pixrem/blob/master/lib/pixrem.js#L119
```javascript
// this doesn't work with ember-cli-postcss
var pixrem = function (rootvalue, options) {
  return new Pixrem(rootvalue, options);
};
pixrem.process = function (css, rootvalue, options, postcssoptions) {
  return new Pixrem(rootvalue, options).process(css, postcssoptions);
};
pixrem.postcss = function (css) {
  return new Pixrem().postcss(css);
};

module.exports = pixrem;
```

Which makes sense, given its name: *node-pixrem*. So am I missing something, or is the inclusion of node-pixrem on the plugin list a mistake?

**Comment by MoOx** [comment]
[postcss is able to consume module that have a .postcss property](https://github.com/postcss/postcss/blob/57a8d4fa771fbca9f4976f586b455545f87f21f4/lib/processor.js#L21) which is the case for this module. So it should works.
Probably an issue from ember-cli-postcss.

**Comment by ismay** [comment]
Ah ok, my mistake. Can see it here as well: https://github.com/postcss/postcss/blob/master/docs/api.md#processoruseplugin . Ok, so then it should be fixed in ember-cli-postcss (or broccoli-postcss). I'll see what I can do there. Thanks!
