### ISSUE TITLE
Plugin#process shortcut

### ISSUE THREAD

**Issue by ai** [postcss/postcss#337]
Mayb we should add `process()` shorcut to all plugins for debug purpose?

```js
var plugin = postcss.plugin('my-plugin', function () { … });

plugin.process(css).then(function (result) {
});
```

/cc @MoOx @simonsmith @ben-eb

**Comment by MoOx** [comment]
Might make sense, especially for tools like cssnext or cssnano for standalone usage.

**Comment by ben-eb** [comment]
Sure. :+1:

**Comment by simonsmith** [comment]
Looks good :+1:

**Comment by MoOx** [comment]
This should be easy to do right ? @ben-eb can you push it from cssnano in the core ?

**Comment by ben-eb** [comment]
@MoOx What do you mean?

**Comment by MoOx** [comment]
I mean add this https://github.com/ben-eb/cssnano/blob/master/index.js#L69-L79 to all plugin registered with postcss.plugin()

**Comment by ben-eb** [comment]
What about handling async processors?

**Comment by TrySound** [comment]
@ben-eb Return a promise?

**Comment by ai** [comment]
Do not worry, I will make it for 4.2

**Comment by ai** [comment]
Done by @ben-eb
