### ISSUE TITLE
decl.value should be forced as string

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#339]
Some plugin might add things like integer as value in the AST.
When setting declaration value, we should force the value to be a String.

Related: this https://github.com/postcss/postcss-calc/pull/10 (where you would find more material about why and who to handle this)

This will prevent bugs in all plugins that do `decl.value.indexOf(...`

**Comment by ben-eb** [comment]
Agreed. Would save plugin developers from having to coerce it themselves (such as here https://github.com/ben-eb/postcss-minify-font-weight/blob/master/index.js#L5-L9)

**Comment by evilebottnawi** [comment]
@ai bump

**Comment by ai** [comment]
Ouh. I didn’t like a virtual properties by getter/setter, but I think we have no other solution.

I will fix it after CSSConf.

@evilebottnawi @MoOx can you help me, please? Can you invastigate the best way to define virtual property, that will looks like common JS property. For example, it should be disableable in `console.log(decl)`.

**Comment by ben-eb** [comment]
@ai Can we not do something like this:

```js
export default class Declaration extends Node {
    // ...
    set value (value) {
        this.raw._value = value;
    }

    get value () {
        return this.raw._value;
    }
}
```

**Comment by ai** [comment]
@ben-eb we can, but `value` will not be displayed in `console.log` and many users don’t read docs and will use some strange things like `decl.raw._value`.

**Comment by ben-eb** [comment]
Does it matter if they set that indirectly? As long as the AST returns a string type?

**Comment by ai** [comment]
They will use raw property and will get same type issue ;-).

Any way, our API should be simple to developers. So it should be inspectable. I think `defineProperty` had options to make it inspectable.

**Comment by ben-eb** [comment]
Ah, the joys of no private properties in JS. :smile:

**Comment by ai** [comment]
Some extra property with long name is OK. Question is only to see `node.value` in inspect.

**Comment by ai** [comment]
We can add `Node#setContext` and set `Result` to `node.context.result` to use it in `node.warn`. But does it is a good way?

Especially in current love on pure function and FP.

Or maybe we can use this API:

```
node.warn(result, 'text');
```

What guys do you think?

**Comment by gucong3000** [comment]
fixed
https://github.com/postcss/postcss/pull/784

**Comment by gucong3000** [comment]
```CSS
#qunit-fixture {
    position: absolute;
    top: -10000px;
    left: -10000px;
    width: 1000px;
    height: 1000px;
}
```

```JS
function cssPipe(stream) {
    var processors = [
        require("stylelint")(stylelintConfig),
        require("cssnext"),
        require("autoprefixer")({
            browsers: ["last 3 version", "ie > 8", "Android >= 3", "Safari >= 5.1", "iOS >= 5"]
        }),
    ];
    stream = stream.pipe(require("gulp-postcss")(processors));
    return stream;
}
```

```
TypeError: value.indexOf is not a function
    at OldValue.check (E:\work\CommonJS\node_modules\autoprefixer\lib\old-value.js:17:17)
    at E:\work\CommonJS\node_modules\autoprefixer\lib\processor.js:198:25
    at E:\work\CommonJS\node_modules\postcss\lib\container.js:94:28
    at E:\work\CommonJS\node_modules\postcss\lib\container.js:81:26
    at Rule.each (E:\work\CommonJS\node_modules\postcss\lib\container.js:68:22)
    at Rule.walk (E:\work\CommonJS\node_modules\postcss\lib\container.js:80:21)
    at E:\work\CommonJS\node_modules\postcss\lib\container.js:83:32
    at Root.each (E:\work\CommonJS\node_modules\postcss\lib\container.js:68:22)
    at Root.walk (E:\work\CommonJS\node_modules\postcss\lib\container.js:80:21)
    at Root.walkDecls (E:\work\CommonJS\node_modules\postcss\lib\container.js:92:25)
```

**Comment by ai** [comment]
We need to override `Node#inspect` to show `value` getter instead of `_value`.

It could be useful in #296 too.
