### ISSUE TITLE
plugin request: graceful degradation flexbox

### ISSUE THREAD

**Issue by iamstarkov** [postcss/postcss#340]
Does anybody interested in plugin to fallback flexbox to something supportable in IE9 (e.g. table-cells)?

From my point of view, this plugin will be very popular.

I have not time right now to create it, so If anyone want to create it — go ahead!
Otherwise, I’ll try to implement it by myself but not sure about timeframes.

**Comment by btholt** [comment]
Seems like a fun idea. I can give it a shot.

**Comment by simonsmith** [comment]
Do you mean prefixed with something like `.no-flexbox` from Modernizr?

**Comment by iamstarkov** [comment]
@btholt good news =)

@simonsmith No, I mean to add `table-smth` as fallback to `flex-smth` for IE9

**Comment by simonsmith** [comment]
@iamstarkov Wouldn't you have the issue of modern browsers applying the flex declarations and the fallbacks? If you were to use [this Flexbox like component](https://github.com/suitcss/components-arrange/blob/master/lib/arrange.css) as an example, there are things like width, min-width that you might only want to apply to the IE stuff

**Comment by iamstarkov** [comment]
yep, you are right fallback styles should be separated in some way

**Comment by simonsmith** [comment]
Yeah, that's why I figured the Modernizr route. Not sure how else you'd do it reliably as a lot more browsers than just IE fail to support Flexbox

**Comment by iamstarkov** [comment]
IE is primarily for example, and because I know for sure that flexbox can be imitated in it

**Comment by btholt** [comment]
I have a bastardized version more or less working. I'll push it up in a bit (even if the code is a mess.) It uses the `@supports(display:flex)` tag to apply flex to new browsers and everything else will use table. The gap here is that IE10 and IE11 can support flex but don't support `@supports`.

Anyway, it's been a fun experiment. It could actually turn out into something useful.

**Comment by iamstarkov** [comment]
can you try to turn it into something useful? as @simonsmith mentioned you can rely on `.no-flexbox` class instead of `@support`

**Comment by iamstarkov** [comment]
:sparkles: it will be awesome! :sparkles:

**Comment by btholt** [comment]
An interesting idea. At that point you do inherently tie the plugin to Modernizr (or something equivalent) but I imagine that's not too bad as most people use Modernizr or could at least at that portion. Anyway, give me a little bit and I'll push up my messy version.

**Comment by btholt** [comment]
Up here: [btholt/postcss-flex](https://github.com/btholt/postcss-flex).

It sorta works. It needs to be more cautious not to fuck up other people's code and the code needs to be reworked to not be dumb. I'm working on that. :smile:

**Comment by ramsaylanier** [comment]
Also ie10 supports flexbox but flex items with margins kinda break
sooooooo.....

😕

**Comment by simonsmith** [comment]
Is there always a consistent set of rules to use for Flexbox fallback? I feel like in  most scenarios you might need to tweak the fallback declarations based on your particular situation. Makes having a plugin like this tricky, as it will rely on outputting the same rules each time.

**Comment by btholt** [comment]
There is a subset of flexbox you can reliably recreate using tables. My plan is to nail that subset with the plugin and then allow for further customizations for other scenarios using something like custom at rules or comments.

**Comment by iamstarkov** [comment]
any news here?

**Comment by btholt** [comment]
Just got back from JSConf China and catching up on work at which point I'll catch up on OS work. :)

Sorry to be dragging my feet.

**Comment by simonsmith** [comment]
Looking for examples of this I've found - http://codepen.io/kevinsmets/pen/AmDzh
Is this the kind of thing you're hoping to recreate?

**Comment by btholt** [comment]
Awesome. This is more or less the approach I've been taking. There are still some cases you can't cover with this approach but I still think it's the best one I've found.

I'll probably be back at it next week. This week I've got worky type things and I'm at OSCON next week.

**Comment by ben-eb** [comment]
@btholt Any updates? :smile:

**Comment by robabby** [comment]
We were just discussing this kind of feature at my office the other day, as we are starting to prototype in Flexbox, but would love to have a graceful degradation to Tables for IE9 and 10.  Some kind of flexbox transpiler that would hook into the `.no-flexbox` modernizr class would be awesome.

**Comment by iamstarkov** [comment]
Is it already plugin out there?

**Comment by ben-eb** [comment]
@iamstarkov An early version is here: https://github.com/btholt/postcss-flex

Perhaps we should move discussion to that repo instead.

**Comment by btholt** [comment]
Sorry, heads down on some Netflix stuff. No idea when I'll surface again to work on it again.

**Comment by ben-eb** [comment]
@btholt No worries. Thanks for the update! :smile:

**Comment by bkinsey808** [comment]
Anybody try this one? https://github.com/7rulnik/postcss-flexibility

**Comment by iObject** [comment]
@bkinsey808 I've tried it, does terrible things in IE10 by using javascript to manipulate your elements.
