### ISSUE TITLE
real world example is 3 times slower than libsass

### ISSUE THREAD

**Issue by soenkekluth** [postcss/postcss#341]
this is a general issue.
you promise to be like 3 times faster than libsass. we experience the complete opposite.
in fact your benchmark is not even close to a real word example.
https://github.com/postcss/benchmark
sadly right now we can not open source our testcase but we could come up with one if anyone can still say that he has  experienced the kind of fast rendertime as promised.

is postcss really faster than libsass?

**Comment by soenkekluth** [comment]
using node v0.12.2 btw

**Comment by MoOx** [comment]
I am very curious about that. It's clearly true that we can't really make fair comparison.
Eager to see some real benchs with comparable codebase.

**Comment by ai** [comment]
@soenkekluth of course, we always willhave cases with a different result. Specially, when we have big architecture difference.

Right now we are sure, that PostCSS parse Bootstrap faster. And PostCSS has same perfomance in appling mixins, nested and variables by plugins, used in benchmark.

But your case is interesting. Let’s try to find a difference between your case and benchmark:

1. What plugins do you use? I think `postcss-custom-properties` should be slower, that `postcss-simple-vars`, because W3C spec is much more complicated.
2. How you CSS generally looks like? In benchark we have a Bootstrap CSS and 100 mixins/vars/nested rules. Maybe you use bigger depth in nesting? Or maybe you have much more mixins?

How we can make benchmark more real?

**Comment by ai** [comment]
@scottkellum 3. Do you use a source maps? What tool you use to tun PostCSS/libsass?

**Comment by scottkellum** [comment]
@ai unsure if I was intended to be tagged here but no I don’t use source maps and our compilation for our project that uses these tools is using node-sass and PostCSS/autoprefixer.

As for my 2¢, I don’t see PostCSS and Sass as competitors. Both are really good at different things and both can be used in the same project to get different types of tasks done more efficiently. I realize this view isn’t shared by all but the Sass vs PostCSS debate is not one that I’m interested in as I find value in both.

**Comment by ai** [comment]
@scottkellum oops :-) sorry I mean a @soenkekluth in last message

**Comment by soenkekluth** [comment]
thanks for the fast reply!
our setup is based completely on node either way. we use gulp and node-sass (gulp-sass)
the same codebase using mixins and @includes takes about 60ms to render with node-sass. postcss takes about 115ms.

we use sourcemaps but of course tried without. does not change a bit.
our goal is to replace scss completely with postcss. thats why we use a bunch of plugins:
(can not show you the whole code right now. but we will)
```
gulp.task('css', function() {
  return gulp.src(css.src)
    .pipe(postcss([
      cssImport(),
      cssComments(),
      cssMixins,
      cssExtend,
      cssNested,
      cssSimpleVars,
      cssCond,
      cssFor,
      cssVars,
      cssNext,
      lost(),
      autoprefixer({
        browsers: browsers,
        cascade: false
      })
    ]))
    .on('error', handleErrors)
    .pipe(gulp.dest(css.dest));
});

```

**Comment by soenkekluth** [comment]
with same codebase i mean the same code refactored for both cases of course

**Comment by ai** [comment]
@soenkekluth I'm, and what do you used for prefixes in node-sass. Autoprefixer has many checks abd look backs, so it can be very slow.

**Comment by MoOx** [comment]
Wow. Why the hell are you using cssnext (+why at the end) ?
cssnext already do import and a lot of other stuffs.

**Comment by soenkekluth** [comment]
@ai well in fact we use postcss for autoprefixer in our sass version too!

i removed sourcemaps in both examples

```
gulp.task('sass', function() {
    return gulp.src(config.src)
        .pipe(sass(config.settings))
        .pipe(postcss([
            lost(),
            autoprefixer({
                browsers: browsers,
                cascade: false
            })
        ]))
        .on('error', handleErrors)
        .pipe(gulp.dest(config.dest));
});

```

**Comment by ai** [comment]
@soenkekluth I think some plugin is a bottleneck here. Can you disable plugin by plugin (except postcss-import of course) to find the slowest one. I think Autoprefixer will be a slowest.

**Comment by soenkekluth** [comment]
@ai nope look my last comment. 60ms there

**Comment by ai** [comment]
@soenkekluth 60 ms is for nodesass+autoprefixer+lost?

**Comment by soenkekluth** [comment]
yes. macbook pro i7

**Comment by soenkekluth** [comment]
its a base setup!

**Comment by soenkekluth** [comment]
and defenitly the same code optimized for postcss with taht config above in 115ms

**Comment by ai** [comment]
@soenkekluth very interesting. So it is not problem of CSS parsing and problem is definitely in some plugin.

Can you disable it one by one, please?

**Comment by soenkekluth** [comment]
@ai yes i will. maybe takes some minutes to fix errors then. will get back to you! thanks!

**Comment by soenkekluth** [comment]
@ai  we are down to 80ms commenting almost everything out.
lost did not do anything (base setup is not using it)
autoprefixer took about 10-15ms
cssVars took about 5-6ms

the only ones left are :
postcss-import
postcss-mixins
postcss-simple-vars

one of these should be the main factor..

```
gulp.task('css', function() {
  return gulp.src(css.src)
    .pipe(postcss([
      cssImport(),
      // cssComments(),
      cssMixins,
      // cssExtend,
      // cssNested,
      cssSimpleVars,
      // cssCond,
      // cssFor,
      // cssVars,
      // cssNext,
      // lost(),
      // autoprefixer({
      //   browsers: browsers,
      //   cascade: false
      // })
    ]))
    .on('error', handleErrors)
    .pipe(gulp.dest(css.dest));
});
```

**Comment by MoOx** [comment]
Just to get an idea, how many file are you importing ? Cause postcss-import use fs.readFileSync, so it might be the source of the issue.

**Comment by ai** [comment]
@MoOx can I ask you to look at postcss-import performance? I can help you only on next week?

**Comment by soenkekluth** [comment]
in the base setup 10 files only. will be hundrets when we finish ;)

**Comment by ben-eb** [comment]
It might be worth making postcss-import an async plugin. :smile:

**Comment by MoOx** [comment]
@ai No I can't write now, same for me I am super busy. But I am pretty sure the main problem is probably the sync read.
@ben-eb Not sure how it's possible but maybe we can refactor it to make it using async reading.

**Comment by MoOx** [comment]
Is it possible for libsass to do some async reading ?

**Comment by MoOx** [comment]
Anyway, making postcss-import a real async plugin seems crazy because it might breaks lot of current process. But internal process might be done using async reading, that can be a start.

**Comment by soenkekluth** [comment]
@MoOx  don't know exactly but they cache the files and merge only the changed parts I guess.

**Comment by MoOx** [comment]
That's can be an enhancement. For now there is totally no cache for postcss-import. Might be worth adding that.

**Comment by ai** [comment]
@MoOx I made separated issue in `postcss-import` to send it for my friends who can helps https://github.com/postcss/postcss-import/issues/41

**Comment by bmds** [comment]
I'm experiencing a massive slowdown for the postCss version of autoprefixer vs the grunt-autoprefixer version.

Libsass runs over the files in ~650ms followed by grunt-autoprefixer at ~270ms.
If i swap grunt-autoprefixer out to postCss it runs in ~11s.

Taking all processors out of the config results in ~1s run time so there is obviously something wrong.

**Comment by ai** [comment]
@bmds can you me your Grunt configs for both cases?

**Comment by ai** [comment]
`postcss-import` was rewritten to use async API

**Comment by MoOx** [comment]
Note:
- async api is not enabled by default (for now), you have an option to enable async usage
- fs read is not async yet (see https://github.com/postcss/postcss-import/issues/41)
