### ISSUE TITLE
Add options for granular positioning to warn and error functions

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#348]
Re: https://github.com/stylelint/stylelint/issues/133

Right now the positions reported by errors or warnings rely on the `node` option; therefore, the position is approximate but not exact, since a node might contain any number of lines, and the warning/error might not relate to the *first* line.

To increase accuracy, a few things could be done:

- Add an `index` option to the functions (alongside `node`), which would allow us to register an exact index for the item *relative to the specified node*. PostCSS would then calculate a line/column position based on the node's raw string value and this reported index.
- Add `line` and `column` options, so that whoever is registering the warning/error can dictate exactly what position gets reported.

Any other ideas?

**Comment by davidtheclark** [comment]
I think it would also be useful to expose an API function like `node.lineOf(index)` that would return the line number of that index in the node.  Plugins might want to use these accurate line numbers for purposes other than errors/warnings.

**Comment by ai** [comment]
Maybe manual `Warning` construction is a better way?

```js
var Warning = require('postcss/lib/warning');
var warn = new Warning('my own text');
result.messages.push(warn);
```

**Comment by davidtheclark** [comment]
Yeah, we could certainly create our own warnings. But I thought other plugins using warnings might want the same precision (I know that any linter could use it, e.g. `postcss-bem-linter`.

**Comment by ai** [comment]
@davidtheclark I afraid right now that current API suggestions is too complicated to use and to describe in docs.

Maybe the better solution is to store origin tokens from tokenizer step and then we will able to set `token` option. But what if some plugin changed value before our linter?

**Comment by davidtheclark** [comment]
I don't know much at all about how the tokenizer could be used, so if you think that's a better way I defer to you :)

**Comment by ai** [comment]
What about this API:

```js
node.error('Unknown variable $one', { word: '$one' })
```

**Comment by davidtheclark** [comment]
I don't understand ... could you explain more?

Would `node.error()` be more appropriate than `node.warn()` for some reason?

Are you suggesting that we specify the word within the original CSS string? That would indeed be nice, but what if we have

```css
background: one, two , three , four, five;
```

And we want to make two complaints, about the spaces before the second and third commas -- how would passing `{ word: ' ,' }` distinguish?

**Comment by ai** [comment]
@davidtheclark `{ word: ' ,' }` will highlight only first word.

**Comment by davidtheclark** [comment]
If you think that would be generic and useful enough to be in postcss core, seems fine to me. But I think based on that discussion in #393 I'll be focusing on an external module provoding `positionAt(index)` to meet the stylelint needs.

**Comment by lydell** [comment]
Hmm … is `node.error('Unknown variable $one', { word: '$one' })` really better than `node.error('Unknown variable $one', str => str.indexOf('$one') })`, which also allows `node.error('Unknown variable $one', str => str.lastIndexOf('$one') })` and `node.error('Unknown variable $one', str => str.search(/\$one\b/) })`?

**Comment by MoOx** [comment]
Why just not the exact position ?

**Comment by davidtheclark** [comment]
I've thought about this more, and @lydell and @MoOx's comments have helped prod me ... and now I'm thinking that I rolled over too easily on this one. I think postcss *should* have built-in functionality for getting exact positions; and it may be that the only way to do that is to use an index --- since "word" is insufficient unless the value is unique, and "word" would probably run into problems with comments and strings, etc.

Many plugins, not just stylelint, would benefit from having accurate positions in their warnings. A variables plugin, for example, might want to say "Variable X has not been declared" for `margin: 0px 10px var(--X) 3px`. Right now, unless I'm mistaken, the line/column reference on that warning (based on the node) would refer to `m` in `margin`, not the `--X` that is the problem. This disconnection would be more prominent if the value had multiple lines, in which case both line *and* column would be inaccurate.

In fact, I'm thinking that `postcss-reporter` should not in fact print `[line]:[column] [message]`, as it currently does, because that format suggests that the line and column number refer *precisely* to whatever the message is complaining about --- while with the current warning API that's not the case. Unless we add `positionAt(index)` or something similar, `postcss-reporter` should probably instead just primarily report the message and secondarily note the line/column of *the node the warning is attached to*. I was thinking that `reporter` could look for a `position` property on the Warning by convention and print that --- but why not build that convention into postcss?

**Comment by davidtheclark** [comment]
Also, I've got to +1 @lydell's note, that "word" does not really give us anything we can't easily get with `indexOf()`, unless there's something more sophisticated behind it.

**Comment by MoOx** [comment]
I have the feeling indeed that this must be built-in.

**Comment by MoOx** [comment]
I have the feeling indeed that this must be built-in.

**Comment by ai** [comment]
Yeap, anyway we need a `index`, even with `word` option, because `word` option will just create a `index`.

But `index` API seems very complicated for me. Specially, that we need to use `decl.before` to calculate this index. I think it will be difficiult for user and we need some better API, which is focused on user cases.

But I understand, that `word` option is not so flexible. Maybe:

```js
node.error('Msg', point: str => str.lastIndexOf('word') )
```

**Comment by ai** [comment]
Or we can do this way:

We will have simple API for simple cases:

```js
node.error('Msg', { point: 'word' });
```

And advanced API for complicated cases:

```js
node.error('Msg', { point: 123 });
```

**Comment by lydell** [comment]
@ai +1. (I'd call it index, though, since that feels more JavaScripty to me.)

**Comment by ai** [comment]
Yeap, let’s choose a name for option :). I afraid if `index` option, because in context of error/warning it is not so clear (we are in right context right now, because talking in this issue, but users will be in different context).

**Comment by lydell** [comment]
If you feel that point is more clear then go ahead. I don't have any strong opinions on it.

**Comment by MoOx** [comment]
Users are developers. Index is very common (and clear), point... I have never seen this except for drawing stuff... `position` can be a solution.

**Comment by ai** [comment]
Yeap, `position` is nice.

**Comment by davidtheclark** [comment]
I think it's clear enough to explain this by saying that `position` is an index relative to `node.toString()`.

I also find it a little confusing to have to include `decl.before` in the index calculation. Bu the reason that I felt I had to do that is because there isn't currently an easy way to get the node as a string *without* its `before`. Right? Or am I overlooking something? With `a {\n  color: pink;\n}` would there be some way to get the full declaration as a string without `before` (i.e. `color:pink;` instead of `\n  color:pink;`)?

**Comment by davidtheclark** [comment]
`position` is good but kind of conflicts with a function named `positionAt()`, since in the case of `positionAt()` "position" refers to a line/column pair, while in this case `position` would refer to an index. That's kind of confusing in my mind. I think one of them should have a different name so the word "position" can be used consistently throughout the API.

**Comment by davidtheclark** [comment]
It's worth noting that throughout the current API documentation "position" refers specifically to line/column pairs.

**Comment by ai** [comment]
@davidtheclark good note about `position`

**Comment by ai** [comment]
Done e8df88b4bcece1a881f299db5b39fdbbe84a2c6d

In docs I promote only `word` option right now.

@davidtheclark but `Warning` has not API to use `word` because `toString()` do not show code example. But `result.warn('text' { node: node, word: ':' })` anyway [will save](https://github.com/postcss/postcss/blob/valac/lib/warning.js#L6) `word` or `index` to warning instance. Do you need some sugar?

**Comment by davidtheclark** [comment]
Sounds good. At some point soonish I'll try to get stylelint using this feature and see how it goes. Thanks!

**Comment by davidtheclark** [comment]
Am I understanding right that node's will have a `positionInside()` function that will return the object with line and column number?

So if in stylelint we want to add properties to the warning designate line and column, we'd do something like:

```js
var positionOfProblem = someDecl.positionInside(indexOfProblem);
result.warn('blah blah blah', { 
  node: someDecl,
  line: positionOfProblem.line,
  column: positionOfProblem.column
});
```

Is that right?

**Comment by ai** [comment]
@davidtheclark 

1. yeap, `positionInside()` has this API
2. nope, `result.warn` has not this API.

Probem is that `Warning` do not print line and column. Maybe we should add them to `valac`. What do you think?

**Comment by davidtheclark** [comment]
For some reason I thought I could add arbitrary properties to the warning, like I could for a regular message --- I didn't think `warn` would understand those, just that it would carry them through to the reporter. I must have been confused.

I do think it would be great it warnings could accept line and column properties. I was thinking that `postcss-reporter` could look and say "*If there are* line and/or column, properties, print those; otherwise, if there's a node property, print that node's start position; otherwise, print no position." What do you think of that?

**Comment by ai** [comment]
Maybe we should use shorter API by accepting `word` option directly in `result.warn` with string or index?

**Comment by davidtheclark** [comment]
Sure, so user doesn’t have to do the `positionAt()` stuff herself. Sounds good.

What do you think of having `index` be an alias in this case, or an undocumented possibility? I only ask because I feel weird passing a number as `word` :) But if you think that sticking with `word` only is better, whether because of better API for more PostCSS users or because of better internal code, I defer to you.

**Comment by davidtheclark** [comment]
Also: if we pass `word` or index to `result.warn` -- what is exposed for the reporter to know position? It would have to be a new property, because currently it gets line/column from the node.

**Comment by ai** [comment]
Right now any `Warning` options is saved into object, so you can use `line` and `column` in that way.

**Comment by davidtheclark** [comment]
Cool. So for `postcss-reporter`, maybe we'd have this method for choosing line/column numbers to print:

- If message has `line` and/or `column` properties, print those.
- If message has `node` and `word` properties, use `positionAt()` to get a line/column for `word` and print that.
- If message has `node` property but no `word`, print the node's starting line/column.
- Otherwise, print no position.

Seem right?

**Comment by ai** [comment]
Yeap, but maybe e should move this logic to `Warning` in 4.2?

**Comment by davidtheclark** [comment]
Sounds smart to me. So `Warning` would expose `line` and `column` properties that are determined based on those steps?

**Comment by davidtheclark** [comment]
Or a `position` object that has `line` and `column` properties, maybe.

**Comment by ai** [comment]
`line` an `column` props is better to have same API as `CssSyntaxError`.

**Comment by ai** [comment]
Done 31f3e86
