### ISSUE TITLE
Postcss and node.js

### ISSUE THREAD

**Issue by admdh** [postcss/postcss#350]
Hi! is there any documentation how to use postcss with node.js server?

**Comment by MoOx** [comment]
I don't think so, but someone made a connext plugin for cssnext, might be a place too look https://github.com/cssnext/cssnext-connect

**Comment by ai** [comment]
@admdh technically PostCSS is node.js project. So it is very easy to [use it from JS code](https://github.com/postcss/postcss#usage).

But I think you ask about some out-of-box solution for some exactly case? What is your user case?

I think on-the-fly CSS processing in production is a very bad way. Gulp in deploy step is better solution for most cases.

**Comment by admdh** [comment]
i'm building a node.js and browser sync server, so both node.js server and browser sync can run at the same time on different ports. currently I'm using harp and sass and wanted to give a try for postcss.

**Comment by ai** [comment]
There is no harp support right now out of box. But it is really very easy to add it.

Caan you add a issue in [harp](https://github.com/sintaxi/harp) repository? Post then link here and we will support you there.

**Comment by admdh** [comment]
Thank you!
https://github.com/sintaxi/harp/issues/451
