### ISSUE TITLE
PostCSS Runner Logic Re-Use for Ember-Component-CSS Addon

### ISSUE THREAD

**Issue by e-karma** [postcss/postcss#353]
If you follow Ember, you know you want Component Based PostCSS w/ CSSNext.  Let's make it happen. 

https://github.com/ebryn/ember-component-css/issues/50

**Comment by ai** [comment]
@e-karma is this issue is just a announce to joins us to that issue? Or you need something from PostCSS codebase?

**Comment by e-karma** [comment]
@ben-eb suggested I post this here as he said some have applied similar solutions and it might be simple.  Nothing needed from PostCSS codebase that i'm aware of

**Comment by ai** [comment]
OK, I will close this issue to make issue list clean.

BTW, @MoOx maybe you will be interested to in that issue with Ember, because they think to build in cssnext.
