### ISSUE TITLE
error : (node) warning: Recursive process.nextTick detected.

### ISSUE THREAD

**Issue by basiclaser** [postcss/postcss#356]
Hi! I'm new to postcss & autoprefixer. I'm trying to run a basic single process. 

Here's my declaration for postcss in grunt : 

         postcss: {
            options: {
                processors: [
                    require('autoprefixer-core')({browsers: 'last 1 version'})
                ]
            },
            dist: {
                src: 'homepage/static/stylesheets/test.css'
            }
        },

i register the single task:
     `grunt.registerTask('postcss', ['postcss']);`

My test CSS looks like 
`a {
    background:yellow;
}`

however when i run the task 'grunt postcss' I see: 

    (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.  
    util.js:35
    var str = String(f).replace(formatRegExp, function(x) {
                      ^
    RangeError: Maximum call stack size exceeded

How can I get around this? thanks!

**Comment by ai** [comment]
Thanks for error. But could you open it in [grunt-postcss](https://github.com/nDmitry/grunt-postcss/issues). It is grunt relevant, but I have no experience in Grunt.
