### ISSUE TITLE
plugins via package.json file?

### ISSUE THREAD

**Issue by duivvv** [postcss/postcss#358]
Any plans on making plugin configuration possible via the package.json?

see browserify
https://github.com/substack/browserify-handbook#browserifytransform-field

**Comment by ai** [comment]
What user cases we have for this place of config? :)

BTW, `packkage.json` can’t be used itself, because many PostCSS plugins accepts functions and other complicated types in options.

**Comment by duivvv** [comment]
User cases? a cleaner gulp file I guess.

But I do understand your point about the functions and complicated types

**Comment by ai** [comment]
We moved PostCSS plugin to `postcss/plugins.js` and include them in gulp by `postcss( require('./postcss/plugins') )`.

**Comment by MoOx** [comment]
I guess lot's of people doesn't use options for plugins. All cssnext users that I know are not using a single option. So you should probably support that, not a big deal to implement.

**Comment by ai** [comment]
@MoOx maybe we should ask `postcss-cli` author. Because PostCSS core has no API for this behaviour.

**Comment by duivvv** [comment]
thanks for considering this, like your work on PostCSS

**Comment by duivvv** [comment]
Isn't this something that PostCSS should implement? `postcss-cli` isn't used in `gulp-postcss` for example. 
Or am I missing something?

**Comment by ai** [comment]
I can't see any benefits of this. Only disadvantaged:

* extra code for FS, which will be unusable in web only solution
* unexpected behaviors, when PostCSS works different in different current dir
* impossibility to config any plugin

**Comment by duivvv** [comment]
ok fair enough.

**Comment by MoOx** [comment]
Since all package.json are already read and cached (eg for main property) i think tere is no extra fs access.

Anyway i guess postcss runners may handle that themselves.
Implementing a such feature as a lib might be a good idea to make this integration easy for all runners.
