### ISSUE TITLE
es6-promise dependency

### ISSUE THREAD

**Issue by karantin2020** [postcss/postcss#361]
Hello. Will you remove es6-promise library from dependencies? Babel supports it well. Babel/ES7 features work well with async/await :)
What is need to have more dependencies where it is not needed?

**Comment by ai** [comment]
@karantin2020 Babel is only development dependency. When I compile PostCSS, there is no Babel and `babel-runtime` with `Promise` polyfill. So PostCSS build depends on `es6-promise`.

**Comment by ai** [comment]
In 5.0, we will stop to support node.js 0.10 and remove `es6-promise` from dependencies.

**Comment by karantin2020** [comment]
babel-loader for webpack is not a decision? Everyone who uses webpack and babel uses babel-loader I think

**Comment by ai** [comment]
@karantin2020 are you understand that PostCSS is used not only with webpack? ;) So `babel-loader` can not be a decision.

**Comment by karantin2020** [comment]
Yes, sorry. That is my mistake :)
