### ISSUE TITLE
Fix or warn on flexbox errors

### ISSUE THREAD

**Issue by ai** [postcss/postcss#365]
There is a good list of all flexbox issues: https://github.com/philipwalton/flexbugs

Maybe somebody want to write a plugin to find all that errors in CSS? Some errors we can fix. On other we can add warning.

**Comment by luisrudge** [comment]
That would be awesome! :)

**Comment by ai** [comment]
@luisrudge 

Plugin Boilerplate: https://github.com/postcss/postcss-plugin-boilerplate
API: https://github.com/postcss/postcss/blob/master/docs/api.md

**Comment by ai** [comment]
@luisrudge you need to create a plugin:

```js
module.exports = postcss.plugin('postcss-flexbugs', function (opts) {
    return function (css, result) {
    };
});
```

iterate through declarations:

```js
css.eachDecl(function (decl) {
});
```

Make some tests on every declaration. If we can’t fix it, add a warning:

```js
result.warn(text, { node: decl });
```

If we can fix it, we should build other nodes by PostCSS API:

```js
var fix = postcss.decl({ prop: 'flex-basis', value: val, source: decl.source });
decl.parent.insertBefore(decl, fix);
decl.removeSelf();
```

**Comment by ai** [comment]
@luisrudge are you in? I already scheduled a tweet on tomorrow to promote this issue :D.

**Comment by ai** [comment]
@luisrudge also we have a 24 hours support in Gitter (thanks to @ben-eb) :D

https://gitter.im/postcss/postcss

**Comment by luisrudge** [comment]
ahahah @ai. I'll join gitter and try to tackle this one :)

**Comment by ai** [comment]
@luisrudge OK I will change a tweet text to promote it as future feature, so you will not have opportunity to loose it :D

**Comment by luisrudge** [comment]
Started here: https://github.com/luisrudge/postcss-flexbugs-fixes

**Comment by ben-eb** [comment]
What a great idea. :+1:

**Comment by dmitrykiselyov** [comment]
:+1:
