### ISSUE TITLE
Normalize.css and Autoprefixer

### ISSUE THREAD

**Issue by fab1an** [postcss/postcss#371]
Hi,
i'm using PostCSS in a brunch-configuration like this:

    postcss:
      processors: [
        require('autoprefixer')(['last 2 versions']),
        require('csswring')
      ]

I also use normalize.css. Is there a way to tell autoprefixer to not strip prefixes from normalize.css?

**Comment by ai** [comment]
Why you want to keep `normalize.css`?

**Comment by fab1an** [comment]
Because it seems to use vendor-prefixes to fix issues in certain browsers only.

**Comment by ai** [comment]
Autoprefixer doesn’t remove outdated prefix if there is no unprefixed version near by.
