### ISSUE TITLE
Plugin to beautify CSS?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#387]
@yisibl raised this in the Gitter chat; a plugin to consistently format CSS. We noted that https://github.com/hail2u/postcss-fmt is too simplistic, and will need to be rewritten after the `clone` method is changed to return an exact copy of a node.

It would be good if the plugin supported a variety of formats to output to, like Sass.

Indeed, a simplistic `compress` option could be used a base for cssnano to normalise whitespace. It is currently handled internally: https://github.com/ben-eb/cssnano/blob/master/lib/core.js

**Comment by ben-eb** [comment]
See also: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

**Comment by yisibl** [comment]
I don't like `nested` format.

```css
#main {
  color: #fff;
  background-color: #000; }
```

**Comment by WolfgangKluge** [comment]
At the moment it's more a container for ideas than a project, but I just started such a project some days ago ;)

The main idea is to allow to format a given piece of css-code and the plugin reads out all the needed information...

**Comment by davidtheclark** [comment]
Such a plugin could probably work hand-in-hand with https://github.com/stylelint/stylelint, so that it automatically adjusts to fix those linting errors that could be automatically fixed.

**Comment by yisibl** [comment]
@ai What do you think?
I think this plugin should be officially completed.

**Comment by ai** [comment]
Nice idea, this plugin will be very useful.

**Comment by ben-eb** [comment]
I've got a bit of time to do this now. @yisibl, @ai - any objections? :smile:

**Comment by yisibl** [comment]
Great! :ghost

**Comment by ben-eb** [comment]
Done! https://github.com/ben-eb/perfectionist

**Comment by diegocr** [comment]
New to PostCSS here, and wanting to re-format/beatify files only. Is `perfectionist` still useable nowadays or deprecated (given the repo is archived) ?

**Comment by ai** [comment]
The best option today is using `stylelint --fix`

**Comment by diegocr** [comment]
Thanks for the suggestion, at my team we have just started using stylelint where the ruleset we're defining is quite permissive, for example not enforcing any _indentation_, so as part of our current bundle process i would like to re-format it to remove all the spurious extra spaces and unneeded comments my team mates may add, so... the `--fix` option won't work here, unless if we define an additional styleling config for this only purpose, but i was hoping PostCSS may have some build-in feature to do this straight away.

**Comment by diegocr** [comment]
if anybody else is interested, this is what i ended up doing: https://github.com/C-Lodder/grunt-postcss/issues/44#issuecomment-726314859
