### ISSUE TITLE
Migration Cheat Sheet

### ISSUE THREAD

**Issue by ai** [postcss/postcss#390]
We can explain many things and PostCSS philosophy by some table “from Sass to PostCSS”.

I think rewrite projects from Sass to PostCSS is a bad idea, but it is a nice way to explain difference.

For example, “clearfix mixin” → “postcss-clearfix”.

**Comment by yisibl** [comment]
>  Other additions, like having a clearfix hidden in a CSS property, blend a little too well with the surrounding real CSS to be spotted by people who might not be so familiar with your way of creating CSS. It might be outright considered … harmful (it isn't, wink wink).

https://medium.com/@ddprrt/postcss-misconceptions-faf5dc5038df

**Comment by ai** [comment]
Close for 391
