### ISSUE TITLE
Anyway to reuse existing sass frameworks with postcss?

### ISSUE THREAD

**Issue by mariopeixoto** [postcss/postcss#392]
I'm have a project that uses compass and susy for the grid system and we're want to migrate to postcss but right now I'm struggling to get that working.

I think this is more like a generic question on how to reuse existing sass frameworks like susy or bootstrap?

**Comment by ai** [comment]
I think there is no sense to remove Sass in your case. PostCSS do not need exclusive rights to yours style :-).

Just add PostCSS right after Sass complication step.

**Comment by mariopeixoto** [comment]
Well, that's my fault for not being clear about my problem. 

Today I'm using a sass preprocessor, even though I'm using webpack, and I really wanted to take advantage of the style-loader in order to include css files on demand, but the sass-loader is a pain.

Anyway, I've just found this awesome plugin called postcss-lost and I think I'll get rid of susy, compass and sass-loader altogether.

But I'm still curious. Is there a way to reuse popular sass frameworks like susy and bootstrap without having to preprocess them?

Thanks anyway.

**Comment by ai** [comment]
Nope, this way couldn't be exists, because you lose all PostCSS benefits by making Sass compatibility.
