### ISSUE TITLE
How to define multiple tasks?

### ISSUE THREAD

**Issue by loominade** [postcss/postcss#399]
I'd like to define two postcss tasks with different files and different configs. I thought it would work like in [grunt docs](http://gruntjs.com/configuring-tasks#task-configuration-and-targets). So I created a ``modern``and an ``ancient``subtask:

```coffeescript
module.exports = (grunt) ->
  grunt.initConfig
    postcss:
      modern:
        options:
          processors: [
            require('autoprefixer-core')(browsers: 'last 2 versions')
            require('cssnano')()
          ]
        dist: src: 'modern.css'
      ancient:
        options:
          processors: [
            require('autoprefixer-core')(browsers: 'ie 6-8')
            require('cssnano')()
          ]
        dist: src: 'ancient.css'
```

But unfortunately they wont be executed like that. What should I do?

**Comment by ai** [comment]
You should ask in [grunt-postcss](https://github.com/nDmitry/grunt-postcss) repo. It is not PostCSS specific, as I understand.

/cc @nDmitry

**Comment by loominade** [comment]
sorry
