### ISSUE TITLE
Nested styles? SASS and LESS?

### ISSUE THREAD

**Issue by zakdances** [postcss/postcss#4]
I'm really liking postcss and I was wondering if you had any plans to include support for SASS and LESS? It'd be incredibly useful to be able to get structured data not just from CSS, but from CSS extension languages as well...

**Comment by yairEO** [comment]
I've been using `Autoprefixer` and other gulp modules for CSS modifying already, and I hardly see a reason to use `postCSS` unless it would replace my dependency on `SCSS` preprocessor completely. why on earth would I need to use postCSS already after my SCSS has been compiled? 

Anyway, @zakdances asked if it will even do what the SASS or LESS does and compile these files. you told him the current state of things, but he asked about future plans, not current.

**Comment by tunnckoCore** [comment]
Im not familiar with sass and less so much, but I think you can completely replace them in 90% of the cases - postcss have tons of plugins.

**Comment by tunnckoCore** [comment]
It is fun how people (the community) invent them, invent these totally new syntaxes, invent compilers/parsers for these harder (than css) syntaxes; before invent this so easy parsing just ol' css.
