### ISSUE TITLE
Rename some plugins to postcss-w3c-*

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#403]
I think to be clear about some postcss plugins, I we should make some renaming.
I got this idea "because" of the plugin `postcss-css-variables` (which use w3c syntax but [doesn't respect the spec](https://github.com/MadLittleMods/postcss-css-variables/issues/4) which make code not future-proof at all, at the contrary of most postcss w3c inspired plugins).

So I am open to make some renaming for some plugins based on specifications naming:

- postcss-custom-properties
  - postcss-w3c-variables (according to the url http://www.w3.org/TR/css-variables/ and because we use same syntax as custom properties, but we are limited to root, so it's more "simple variables" than a custom properties implementation)
- postcss-custom-media
  - postcss-w3c-custom-media (http://dev.w3.org/csswg/mediaqueries/#custom-mq) (should we add an S ? ref https://github.com/cssnext/cssnext/pull/170#discussion_r33567193)
- postcss-custom-selectors
  - postcss-w3c-custom-selectors (http://dev.w3.org/csswg/css-extensions/#custom-selectors)
- postcss-color-function
  - postcss-w3c-color-function (http://dev.w3.org/csswg/css-color/#modifying-colors)
- postcss-color-function
  - postcss-w3c-color-function
- postcss-color-gray
  - postcss-w3c-color-gray
- postcss-color-hex-alpha
  - postcss-w3c-color-hex-alpha
- postcss-color-hwb
  - postcss-w3c-color-hwb
- postcss-font-variant
  - postcss-w3c-font-variant

Btw I think we should update/change/normalize & rename some plugins

- postcss-selector-matches
  - postcss-w3c-selector-[pseudo-class-]matches
- postcss-selector-not
  - postcss-w3c-selector-[pseudo-class-]not
- postcss-pseudo-class-any-link
  - postcss-w3c-selector-[pseudo-class-]any-link

Not sure if we should use selector- or pseudo-class. poke @jonathantneal 

- postcss-color-rebeccapurple
  - postcss-w3c-color-named-color (named color to hexa)
- postcss-color-rgba-fallback
  - postcss-w3c-color-rgba (all plugins are fallback right?)

- postcss-media-minmax
  - postcss-w3c-media-queries-range (http://dev.w3.org/csswg/mediaqueries/#mq-ranges) (poke @yisibl)

Some notes:
- Maybe for all postcss-w3c-color-* we should rename to postcss-w3c-color-*-to-hexa to offer a clear name. I know that some are not fan of long name, but it helps new users a lot (especially when you have a fucking huge list of plugins to choose from)
- should plugin have use a plural form? Is it relevant? (custom-medias or custom-media? custom-selector or custom-selectors? color-function or color-functions?...)

Also we should require in each plugin documentation:

- link to spec
- limitation if any
- level of stability (see https://github.com/cssnext/cssnext/issues/100)

I think new postcss-w3c- plugin will need to be approved by the community to be
in the appropriate section in postcss readme/website.

The idea of this thing is to normalize things and helps new users to choose.
I want postcss to embrace standards the right way, so I think adding a distinction in the name of plugins will be a huge help to avoid unclear things (poke @ddprrt ref https://medium.com/@ddprrt/postcss-misconceptions-faf5dc5038df "Misconception Number Two: Future CSS syntax")

Discussion is open :)

**Comment by ai** [comment]
I very like `postcss-w3c-` prefix, it makes clear.

I think `-pseudo-class-` makes namess too long.

**Comment by ben-eb** [comment]
I am in favour of all of the above. We should definitely make stability level mandatory for future CSS syntax, and I would even go as far to make that a PostCSS plugin rule.

**Comment by MoOx** [comment]
> @MoOx ask W3C first? You’re using their name, as if they’d approved the modules. “Postcss-respectingStandards-*” ? ;)

Source: @remitbri https://twitter.com/remitbri/status/616939304825298944

@tabatkins any thoughts on this ?

**Comment by ai** [comment]
@MoOx this point has sense if you think logically, but looks like very weird in practice.

**Comment by MoOx** [comment]
@ai The question is: is it ok to use postcss-w3c-*. Is this naming approved by the w3c ? :) (I guess that `postcss-respectingStandards-*` is a joke)

**Comment by Xaviju** [comment]
@MoOx 
Should the w3c approve all the names that contain 'w3c'? All the plugins in the world? 
It is not enough to make clear that this is just a plugin respecting w3c standards? 
How to avoid that a plugin uses that naming if they don't respect the standards or becomes unmaintained?

**Comment by MoOx** [comment]
Like every "approved" thing, I guess we will need a "postcss w3c" police :) (hello gulp)
And we could ask for people to submit they postcss plugin as "w3c" one (in the doc) so we can approve them, and then, move them into the org so they don't end up "unmaintained".

**Comment by iamvdo** [comment]
It won't surprised you but for me this is non sense. 

I understand your point though but hey, it's just another level:
- me: I'm not fan of future syntax based modules
- you: you want future syntax based modules but with maximum respect to the spec
- others: they could want future syntax based modules but with their own addition or need, whatever the spec says

As it's impossible to fully implement a CSS spec with PostCSS modules, I don't see a reason to change names.

Maybe clearly note that these specific modules are trying to respect the spec is enough? Mention that these modules are kind of "certified" by PostCSS, not by W3C?

**Comment by MoOx** [comment]
> I'm not fan of future syntax based modules

Ok then, it's not your problem :)

> you want future syntax based modules but with maximum respect to the spec

I write future-proof code, based on specs. It's up to me to choose my level of stability. And this helps to play with the new specifications.

> they could want future syntax based modules but with their own addition or need, whatever the spec says

I see two things here, the first one leads to this topic (future-proof code), the other thing is another topic (language extension) which have nothing to do in this thread. That's the beauty of postcss for some people, but it's not my cup of tea (it's a nice way to try things tho as I think some plugins might inspired w3c for new specs) ;)

> As it's impossible to fully implement a CSS spec with PostCSS modules

I don't agree. Modifying a color for example, is doable. "custom props" module is for now the only exception from what I know.

> Mention that these modules are kind of "certified" by PostCSS, not by W3C?

Most people don't even read docs. That's why I bring this discussion on the table. I would like people to have a quick way to distinguish future-proof, well maintained plugin (that respect the specification) and I think something in the name would really help. If you have some other ideas, please share :)

**Comment by yisibl** [comment]
You can add the `w3c` prefix, but I don't like to long plugin name.

**Comment by lydell** [comment]
Hmm, perhaps people who care very much about only using future-proof spec-compliant CSS also are the ones who actually read docs, and investigate plugins before using them?

One alternative is also to use a keyword in package.json.

**Comment by magsout** [comment]
>Also we should require in each plugin documentation:

    link to spec
    limitation if any
    level of stability (see cssnext/cssnext#100)

:+1: 

>I think new postcss-w3c- plugin will need to be approved by the community to be
in the appropriate section in postcss readme/website.

:+1: 

Rename the plugins or not, no matter, the two ideas above are crucial to avoid lying that actually do the plugins

**Comment by daleeidd** [comment]
If they are renamed, I wouldn't mind claiming `postcss-custom-properties` if possible

**Comment by tabatkins** [comment]
> The question is: is it ok to use postcss-w3c-*. Is this naming approved by the w3c ? :)

You don't have to care about permission, feel free to use it if you want.

**Comment by jonathantneal** [comment]
I’m okay changing **pseudo-class** for **selector**, but it does not solve the problem of properly tagging plugins that respect a real-life web standard, whether it be w3c or whatwg or whoever, should forking ever happen again.

Also, naming conventions will not help us when a developer *falls off the face of the earth*; if they cease to update their plugin with the spec, or with API or boilerplate changes or improvements, or if the fail to take in pulls for minor fixes because their job or life situation no longer permits the time.

Perhaps the only way to whitelist plugins is to curate them yourselves. Perhaps whitelisted plugins should be pulled into a whitelisted fork that accepts contributions from the community, adding the developer as a collaborator. Then, whitelisted plugin lists can be generated automatically from that group.

**Comment by MoOx** [comment]
I agree that those spec compliant plugins must be in a place where more than one people might be able to maintain them. This looks like a requirement. That's why I propose:

- plugins should need to be approved by the community
- renamed with a potential prefix if we found it's accurate (postcss-w3c ? anyone have a better idea?)
- moved to the postcss org.

We might create a specific team in postcss org in order to allow a group of people to interact with all this list of plugins.

(@daleeidd It's not a good idea since custom props can be "polyfilled" without a client side script. Anyway, this won't be possible to give you this name since I will need to deprecate the package on npm so people see they need to use the renamed plugin instead.)

**Comment by hgl** [comment]
I'm not sure what's the real benefit of putting w3c in plugin names. Normal users that want to write future-proof code should simply use cssnext.

If you really want to inform users if a plugin is spec compliant or not, I think it's best to create a list at postcss/w3c, the website, etc, listing the postcss plugins that haven't been **verified** to be spec compliant. You can not prevent `postcss-css-variables` from renaming to `postcss-w3c-css-variables` if they feel like it.

**Comment by MoOx** [comment]
It seems it's not a good idea. I will make a PR to remove postcss-css-variables from "future syntax" section.
