### ISSUE TITLE
Plugin initializer called before use

### ISSUE THREAD

**Issue by rtsao** [postcss/postcss#415]
Currently, plugin initializer functions are called before they are used, see: https://github.com/postcss/postcss/blob/709200a2b4bea3e50f96dde757cffd53012a02a6/lib/postcss.js#L26

This means that simply `require`ing a plugin, e.g. `require('my-postcss-plugin');` will call the initializer with no arguments. This is problematic if we want to require certain options to be supplied and want to throw if they are not.

It seems to me that the initializer should only be called once options have been explicitly supplied (by calling the plugin), or if options are not supplied then postcss should call the initializer when processing the plugins array.

**Comment by ai** [comment]
Initializer is called without option only to fill `init.postcss` field. It will be used if user will use plugin without brackets:

```js
.use( require('my-plugin') )
```

What end-user problem you have with this logic?

**Comment by ben-eb** [comment]
You should move that logic in the function that processes the CSS, like so:

https://github.com/postcss/postcss-use/blob/master/index.js#L11-L15

**Comment by ai** [comment]
We can add lazy load for bracketsless form in `init.postcss` by getter.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss/commit/f92780de76f0c0d098a7bb5ad4fa9afbb7cb168a
