### ISSUE TITLE
A postcss component that moves animation keyframes outside of media queries

### ISSUE THREAD

**Issue by TCotton** [postcss/postcss#423]
I've spent a while looking but can't, as yet, find a component to refactor code like below:

    @media screen {
      .ie9 .aboutme [class*=per] span {
        -ms-transform: scaleX(1);
        -webkit-transform: scaleX(1);
        transform: scaleX(1);
        opacity: 1
      }

      @-webkit-keyframes fadeIn {
        from {
          opacity: 0;
          -webkit-transform: scaleX(0)
        }
         to {
          opacity: 1;
          -webkit-transform: scaleX(1)
       }
      }@keyframes fadeIn {
         from {
           opacity: 0;
           transform: scaleX(0)
         }
         to {
           opacity: 1;
           transform: scaleX(1)
         }
       }

Does one currently exist?

**Comment by ai** [comment]
Nope. You can write it. It is very easy.

**Comment by TCotton** [comment]
As an NPM module? Sounds like a nice little project to get my teeth into. Thanks for responding so quickly

**Comment by ai** [comment]
Yeap. Please checkout "Develop your own plugin" section on PostCSS README. It contains very important Guidelines.

**Comment by TCotton** [comment]
So I have wrote one! https://github.com/TCotton/postcss-animations You are right, it was quite easy. Do you have any time to review the code Andrey?

**Comment by ai** [comment]
@TCotton I already made few issues
