### ISSUE TITLE
A Shout out for postHTML, postJS!

### ISSUE THREAD

**Issue by 7immy** [postcss/postcss#443]
The format for postCSS is brilliant! I'm just wondering if someone has thought of using the same sort of thinking on the other standard web scripts like HTML and javascript?

Just a thought..

**Comment by ai** [comment]
postJS = Babel. It is not only es6→es5 tool, you really can do many different things.

postHTML is XSLT, but it is ugly :D.

**Comment by MoOx** [comment]
For JavaScript, you have Babel http://babeljs.io/

**Comment by Guria** [comment]
https://github.com/posthtml/posthtml from the protein team

**Comment by ai** [comment]
@Guria awesome! i will promote it tomorrow by PostCSS twitter :D.

**Comment by 7immy** [comment]
This is awesome news! :D
