### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#445]
I have 28 tests failing on Windows, I think mostly due to file path issues. Unfortunately, it's rather hard to fix, because it's reading a large JSON file and checking the equality in some tests (e.g., [this line](https://github.com/postcss/postcss/blob/ac8c257ed5ae77ea688f2e5a20e88d743427250a/test/parse.js#L52)).

Mocha gives the following error in that case:
```
          "source": {
              "input": {
                  "css": "a {\n\tcolor: black\n}\n",
                  "safe": false,
     -            "file": "z:\\tab.css",
     -            "from": "z:\\tab.css"
     +            "file": "/tab.css",
     +            "from": "/tab.css"
              }
          },
```

Any suggestions on a strategy to fix this? I'm willing to help.

**Comment by jedmao** [comment]
I should note that if a `path.resolve(source.input.file)` were run on these file paths then it would pass just fine. Unfortunately, I can't do that in a JSON file.

**Comment by jedmao** [comment]
And for the record, my GitHub folder is on my `z:` drive. That's why you see the `z:` paths in there.

**Comment by MoOx** [comment]
Maybe it's time to add Appveyor here ? http://www.appveyor.com/
I am using it for cssnext https://github.com/cssnext/cssnext/blob/master/appveyor.yml

**Comment by jedmao** [comment]
That sounds like a great idea!

**Comment by ben-eb** [comment]
:+1:

**Comment by ai** [comment]
@jedmao I am open for PR, but please make it for `valac` branch.

Sorry, I can’t help you, because I can’t make any investigation without Windows (I am Fedora user). I agree that it is important issue, but I need your help here.

**Comment by jedmao** [comment]
I'll try to help here. BTW – what is the purpose of the `valac` branch?

**Comment by ai** [comment]
It is a branch for 4.2 release. It is almost finish.

**Comment by ai** [comment]
4.2 release will have a `President Valac` code name.

**Comment by jedmao** [comment]
I think I'll have to convert these JSON files into JavaScript files to `path.resolve` each path for this to work on Windows. Is this acceptable for you?

**Comment by ai** [comment]
Yeap, JSON’s seems to be to hacky.

**Comment by ai** [comment]
@jedmao but do not miss `gulp cases` task to update tests.

**Comment by ai** [comment]
@jedmao Can you test `valac` branch on Windows? I think this fixes can help:

https://github.com/postcss/postcss/commit/b3b49811703eea98b5a5caf8a5e374d6436578aa
https://github.com/postcss/postcss/commit/626ae02abfc4c8125dab4f29e044fda2d5f29671

**Comment by ai** [comment]
I tried to test it myself, but running node.js on Windows is so difficult :(. I still have `Unexpected token case` on `mocha` execution.

**Comment by lydell** [comment]
@ai I used to develop for Node.js on Windows (but thankfully I don't anymore). As far as I remember, all you need to install is git, which includes ”git bash” which gives you a nice unix shell and a bunch of unix tools, as well as one of the official Node.js binaries to get Node.js (and of course a sane text editor and web browser helps too). I almost never had problems running Node.js this way (unless a project uses `make`—then you're basically screwed).

**Comment by jedmao** [comment]
@ai the `valac` branch works great on Windows! I even ran `gulp cases` first and there were no changes, so that's good. Everything is fast too. There was an unrelated error, however, with spell check:

```
[ERR] Z:\Documents\GitHub\postcss\docs\syntax.md 725 ms
-----
Typos: 1
1. TODO (count: 10, suggest: TO-DO)
-----
```

I agree with https://github.com/postcss/postcss/issues/445#issuecomment-126993181, but I just install [GitHub for Windows](https://windows.github.com/), which comes with a portable version of msysgit. I then set my PATH environment variable to include `AppData\Local\GitHub\PortableGit_xxxxxxx\bin`, which gives me a bunch of Unix commands, even in the Windows Command Prompt. I rarely use the Windows Command Prompt, however, because I set my default shell in GitHub for Windows as Git Bash:

![github-for-windows](https://cloud.githubusercontent.com/assets/1058243/9027249/93f7da70-3913-11e5-8752-2a02c24736a4.png)


Have you given any thought to AppVeyor yet?

**Comment by ai** [comment]
What is a befits of AppVeyor in comparasion with Travis CI?

**Comment by jedmao** [comment]
It runs the tests on Windows vs. Travis-CI, which is Unix-based.

**Comment by jedmao** [comment]
I'm suggesting you use both.

**Comment by ai** [comment]
Hm. It is interesting. But I will need your help.

**Comment by ben-eb** [comment]
@ai I've been running appveyor and travis for cssnano, it's pretty good so far. :+1:
