### ISSUE TITLE
PostCSS better highlighters

### ISSUE THREAD

**Issue by ai** [postcss/postcss#449]
Right now “SCSS” highlighters works normal for PostCSS’ nested CSS.

But what we want to highligh additionally?

**Comment by andyjansson** [comment]
Ideally, we'd want to highlight any custom syntax that's introduced by the plugins. I believe the only viable option is to have these plugins include their own grammar files in their npm packages.

**Comment by ai** [comment]
@andyjansson I asked what exactly highlight to you mean? Most of plugins provide just custom at-rule with one/two parameters.

**Comment by ai** [comment]
@andyjansson can you show me example on screenshot?

**Comment by andyjansson** [comment]
There is no "exactly". I'm not talking about syntax highlighting for just a few specific things, but generic syntax highlighting for any and all plugins, present and future, which introduces custom syntax. I don't think that the scss syntax highlighter is an adequate solution since PostCSS is modular and there's no guarantee that the plugins that the user has loaded will be compatible with that syntax highlighter. You can look to the language extensions for examples on custom syntax, but keep in mind that even if they happen to work for you with your current highlighter, future plugins might not and that's why we need grammar files.

**Comment by ai** [comment]
Can you show me just a example of pllugin when non-SCSS highlight will be better.

**Comment by joshdrink** [comment]
@ai Not sure if this is relevant to the conversation, but the biggest issue I've run into with **syntax highlighting** is `cmd+/` for commenting out code. Both Sublime and Atom handle the comment styles (`//` vs `/* */`) based on the syntax highlighting. Does anyone have a useful fix for this?

**Comment by andyjansson** [comment]
There's an issue for WebStorm support currently assigned to @zolotov: https://youtrack.jetbrains.com/issue/WEB-16601 
I think we should bring them into the discussion.

**Comment by ai** [comment]
Maybe we can highlight PostCSS’ props and at-rules in different color to split standard and non-standard things?

**Comment by ilyashubin** [comment]
Syntax highlighter for PostCSS would be cool. I think basically custom at-rules + cusom properties as native + nesting.

**Comment by hudochenkov** [comment]
I've made [syntax highlighting for Sublime Text](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS). It's based on SCSS syntax highlighting, but using standard comments `/* */`. It's probably not cover 100% of PostCSS-plugins syntax, but for most users, I think, it will work pretty well.

**Comment by azat-io** [comment]
Syntax highlighting for Atom: https://github.com/azat-io/atom-language-postcss

**Comment by joshdrink** [comment]
@azat-io You sir, are a gem. This is very much appreciated!

**Comment by hudochenkov** [comment]
@azat-io This is great! :) By the way, you build this from scratch (all this regexes) or use other syntax as base?

**Comment by ai** [comment]
On next week I will go to JetBrains office to talk about PostCSS support in WebStrorm.

But note, that it is a big slow company, so PostCSS support could be added only in next-next release (I as know next release is very soon and they can’t add new features).

**Comment by ai** [comment]
https://github.com/postcss/postcss#ide-integration
