### ISSUE TITLE
dont remove sourcemap comments

### ISSUE THREAD

**Issue by benjaminfunk** [postcss/postcss#462]
the problem is that postcss remove all comments include sourcemap comments!

my problem is that my concat generate my sourcemaps and postcss will remove it later. if i activate sourcemaps in postcss too it will create a wrong sourcemap that included the concated file as a source.

see also https://github.com/nDmitry/grunt-postcss/issues/43

**Comment by ai** [comment]
I need extra info. PostCSS do not remove any comments by default (it is a goal of PostCSS, byte-to-byte equal output).

This is a logic for cleaning previous source map comment, if you ask to generate new source map: https://github.com/postcss/postcss/blob/master/lib/map-generator.js#L64

**Comment by benjaminfunk** [comment]
problem is in another module
