### ISSUE TITLE
PostCSS birthday

### ISSUE THREAD

**Issue by ai** [postcss/postcss#465]
7 september is birthday day of PostCSS. Maybe we should selebrate it somehow? It will show that PostCSS has strong community?

What about small drinkups in few cities (we can make them in 6 september, Sunday). So tweets with photos about drinkups in Russia, USA, Europe, Chine, Japan will looks great. Like we are global right now and nothing can stop us :).

@ben-eb @MoOx @MadLittleMods @jonathantneal @davidtheclark @yisibl @morishitter

**Comment by MoOx** [comment]
I am in the country land, so not the better place for a small meetup :)

**Comment by morishitter** [comment]
Cool! I will selebrate it from Japan :D

**Comment by ai** [comment]
@MoOx one person meetup is fine for marketing plan too :).

**Comment by yisibl** [comment]
So cool, Happy birthday :ghost: !

**Comment by jonathantneal** [comment]
I am technically a four person meetup, counting my wife and kids. :)

**Comment by ai** [comment]
Hi, again. Birthday is on next Monday, September 7. So this Saturday/Sunday will be great time to make party photos.

I will make special event in Saint Petersburg (ping to @brainopia @cakeinpanic), but it will be fine just photo of yourself with some selebration stuff. Just to show how big our community is. If your photo will contain some things from your country (city attraction, nation cliche), it will be better. 

Anyway, I think it is a great motive to break working routine :). Maybe if you live in sam city with other contributor or plugin developer, it will be cool motive to meet each other in real world.

How is in? I need photos in Sunday to make a post.

@MohammadYounes @yisibl @ben-eb @jonathantneal @MoOx @morishitter @davidtheclark @jedmao @hail2u @shinnn @borodean @iamvdo @andyjansson @corysimmons

**Comment by corysimmons** [comment]
[My photo](http://i.imgur.com/tVdVYbj.jpg)

I won't be able to properly celebrate but I'll be presenting PostCSS at Sass Summit this year. =)

**Comment by ai** [comment]
BTW, I need a photo of selebration. To show common event.

**Comment by ai** [comment]
@corysimmons awesome! What is a date of your talk? I will promote you by PostCSS twitter account.

**Comment by corysimmons** [comment]
Nov. 18th. There doesn't seem to be a site for Sass Summit 2015 yet.

**Comment by ai** [comment]
@corysimmons :( please ping me, when date will be closer

**Comment by ben-eb** [comment]
Ping me if you're in the UK and want to meet up for drinks.

**Comment by cakeinpanic** [comment]
sunday evening is ok

**Comment by MadLittleMods** [comment]
If anyone is in Minnesota, Twin Cities area, I am willing to meetup :grinning:

**Comment by ai** [comment]
Meetup in Russia, Saint Petersburg https://vk.com/postcss2y

**Comment by ai** [comment]
So, I wait a photos tomorrow. Just a selfie how you spend a day. Maybe dinner with family. Or developing some code. If you company uses PostCSS, your office photo wil be awesome.

All that photos will be used in birthday post at Monday.

**Comment by yisibl** [comment]
@ai I'm going to collect some photos of Chinese users.

**Comment by ai** [comment]
@yisibl awesome :)

@morishitter also wait photos from Japan ^_^

**Comment by morishitter** [comment]
@ai Today, I took a photo when I was drinking with my friends. When should I tweet to celebrate?

**Comment by ai** [comment]
Technically, today is OK, but mention that birthday is tomorrow.

**Comment by ai** [comment]
@morishitter @yisibl @ben-eb @jonathantneal send your photos to andrey@sitnik.ru

**Comment by ai** [comment]
Thanks everyone, who helped :).

Post is ready https://medium.com/evil-martians/postcss-2nd-birthday-2c76c223c78f
