### ISSUE TITLE
Better ES6 compiler for GitHub users

### ISSUE THREAD

**Issue by ai** [postcss/postcss#466]
PostCSS is compiled to ES5 on release. But in GitHub version we have some special hack.

Right now we have `index.js`, which adds Babel hook to `require`.

This method is old and unsafe. Also sometimes it just do not work (for example, when you require some subfile from PostCSS).

Maybe we should move [to other way](http://mammal.io/articles/using-es6-today/). I like a idea to rename `.js` to `.es6` and add `prepublish` hook to compile them back to `.js`. (I didn’t like idea about `scr`→`dist` hook compilation, because users must understand path to submodule by GitHub).

@MoOx I kno you have fresh experience with ES6 hooks in cssnext. What do you think?

**Comment by MoOx** [comment]
Like everybody, I use a prepublish hook that compile src to dist folder. package.json have the `main` section set to `dist/index.js`. That's all.

**Comment by jedmao** [comment]
Thanks @MoOx! You're referring to [these lines](https://github.com/cssnext/cssnext/blob/9aad8a94eaef5c73f3e925cc63ede6945403a520/package.json#L118-L120), for reference.

**Comment by MoOx** [comment]
Don't forget this one https://github.com/cssnext/cssnext/blob/9aad8a94eaef5c73f3e925cc63ede6945403a520/package.json#L28 ;)

**Comment by ai** [comment]
First step 0945046f2b8022f63409ec056f7e237d38ecc59b

**Comment by ai** [comment]
Fuck, all `prepublish` way is wrong. `npm` do not call `prepublish` for packages from GitHub. So there is not sense in this way (building `build/` and maing `cd build; npm publish ./` is easier).

Also I tried `postinstall`, but it do not work too, because `npm` by some very strange reason call `postinstall` before installing all `dependencies`.

So right now there is no way to compile ES6, when user got your packages from GitHub. Only `index.js` on-the-fly hook, like PostCSS was used.

**Comment by MoOx** [comment]
You should not try to handle install using github. Not all people are doing that.
Instead you should cover 99% of usage (from npm release) and provide this instruction for rare people that want to use a branch http://cssnext.io/setup/#install-from-git

**Comment by ai** [comment]
For PostCSS it is more important, because sometimes we may try to unreleased API in plugins. Or maybe I was too happy in Ruby world and really mad, why `npm` team do not handle this case.

Anyway `index` hook works fine (not ideal, but fine). I have `babel-core` in `dependencies` and call `babel-core/register` in `index.js`. `build` task fix `package.json` before release by cleaning `dependencies` and remove `index.js`.

Not ideal solution, but it woks for most cases out-of-box.
