### ISSUE TITLE
Preparing for PostCSS 5.0

### ISSUE THREAD

**Issue by ai** [postcss/postcss#467]
OK. So we will release 5.0 instead of 4.2. So I have 2 questions:

1. Maybe somebody want to some small API changes?
2. We need prepare main plugins and release new compatible version with 5.0.

API problem is that `.before`, etc will be changed to `.raw.before`. I think main plugins are:

* [ ] Autoprefixer (my work)
* [ ] cssnext (as I know postcss-import uses `.before`) @MoOx how we can update cssnext plugins? You chosen next maintainer or will accepts PR?
* [ ] PreCSS. @jonathantneal I will update `postcss-nested`. Does other plugins use `.before`?
* [ ] cssnano @ben-eb 
* [ ] stylelint @davidtheclark

**Comment by davidtheclark** [comment]
stylelint uses `.before`.

**Comment by ai** [comment]
So, guys, are you in? :)

**Comment by davidtheclark** [comment]
"In" as in, am I ok with releasing a new version when 5.0 comes out? Yep, sure. If that `before` change is the only big concern, it should not take me very long at all to make the change.

**Comment by ben-eb** [comment]
It might be an idea to release a patch containing the old properties as aliases to the new ones (maybe just as setters/getters that warn when they are used), so that authors will be aware of this upcoming change.

**Comment by jonathantneal** [comment]
I’m in.

**Comment by ai** [comment]
@ben-eb `valac` branch already has warnings in `before` getters. But I want to use `.before` as insert method like DOM has (wwe will be able to add this methods in 5.1). Also if we left warnings, we will be forced to keep them until 6.0.

But I am open to dicussion.

**Comment by ai** [comment]
OK, I will change ES6 hook on this week, so you will be able to make branch depends on PostCSS branch.

**Comment by ai** [comment]
Also 5.0 will throw a clear error, when somebody will try to access to removed methods. I think it will help with migration.

**Comment by ben-eb** [comment]
@ai If we add deprecation warnings to the 4.x codebase then we can change the 5.x codebase to use the new insert methods. The point is more that people will be aware of the code change because it will be warning them when it is used (and providing them with an upgrade path).

**Comment by ai** [comment]
@ben-eb yeap, it was my origin plan. But we can’t ship Custom Parsers in 4.x releases. So extra release will take more time.

**Comment by MoOx** [comment]
More major versions with less changes seems a good idea.

**Comment by ai** [comment]
We can release a 5.0 with warnings and then 6.0 with insert `before`/`after`.

**Comment by ai** [comment]
I also moved some “old 5.0” refactor tasks to “new 5.0” release, but they should not affect anyone (this is a reson why I ant to remove some hidden or unpopular APIs):

* Stop using fixed version of dependencies #312
* Remove node.js 0.10 support and Promise polyfill #311
* Remove return Root support from plugin #231
* Remove Root#prevMap #194

**Comment by ai** [comment]
Are everyoone OK with often major releases, but without many break changes? So 5.0 will contains warning for `before`, but 6.0 will be after few months.

**Comment by MoOx** [comment]
Lgtm

**Comment by davidtheclark** [comment]
Sure.

**Comment by ben-eb** [comment]
:+1:

**Comment by ai** [comment]
Nice. @MoOx thanks for suggestion.

So without a break changes we can close this issue.
