### ISSUE TITLE
JSDoc

### ISSUE THREAD

**Issue by ai** [postcss/postcss#480]
When we will have PostCSS website, we should autogenerete sources. JSDoc seems like good source for `api.md`.

Also JSDocs will be useful for IDEs.

**Comment by davidtheclark** [comment]
I don't know the current status of ES6 support in JSDoc, but last I checked it was a problem.

There is a project that is trying to remedy some of the flaws of JSDoc (the tool, not the syntax), which you might look into: https://github.com/documentationjs/documentation

**Comment by jedmao** [comment]
If the comments are preserved in transpilation from ES6 to ES5, does it matter what ES6 support it has? Currently, only the ES5 JavaScript is published with the npm package.

**Comment by shuvalov-anton** [comment]
You can try tj/dox instead of jsdoc parser. It's kinda better.

**Comment by ai** [comment]
I think to move all `API.md` to some sort of JSDoc comments on this sunday.

What format and tool is best? @ben-eb @MoOx @jedmao 

@marcustisater what requirements do you have for usging this API on postcss.org?

**Comment by jedmao** [comment]
@ai I already implemented all the API docs as JSDoc comments in my [typescript branch](https://github.com/jedmao/postcss/tree/typescript). See [`node.ts`](https://github.com/jedmao/postcss/blob/typescript/lib-ts/node.ts) as an example. All it requires is a simple `tsc` command to build `.es6` files from the TypeScript source and all the documentation is there.

That said, I've only used Visual Studio and Visual Studio Code to generate JSDocs, but I wouldn't be surprised if there was something better out there. Still, it's nice how you can just type `/***` to start the JSDoc comment and start typing away. Every subsequent ENTER key press keeps you in a comment block. Not sure if other tools have more support than that, but I imagine they would.

**Comment by jedmao** [comment]
@ai I created a jsdoc branch. See the comparison here: https://github.com/postcss/postcss/compare/master...jedmao:jsdoc

**Comment by ai** [comment]
@jedmao when I will create a JSDocs in `.es6`, I can remove it from `.ts` files? Visual Studio will look into `.es6` first?

**Comment by jedmao** [comment]
@ai, I should mention that the branch is just the transpiled result of my [typescript branch](https://github.com/jedmao/postcss/tree/typescript) source code.

**Comment by marcustisater** [comment]
I'm not very familiar with JSDocs but I don't think that shouldn't be any problems, however we would need markdown files.

@ai - I was just about to open an issue about syncing documentation(.md files) between [postcss](https://github.com/postcss/postcss) and [postcss.org](https://github.com/postcss/postcss.org).

**Comment by ai** [comment]
@marcustisater when 5.1 will be released, link to `docs/api.md` will return 404 ;). We need to generate API page for postcss.org by JSDoc. Are we ready for it?

**Comment by marcustisater** [comment]
How far are you from the release of 5.1? We haven't started the development for basic pages yet so if the time runs short maybe we can forward from postcss.org with a link to somewhere?

**Comment by ai** [comment]
I decide to make 5.1 very small release so I can release it on next week.

But if postcss.org will not be ready, we can set a link to old commit on GitHub.

**Comment by ai** [comment]
@marcustisater or we can generate API page without any special style as temporary solution

**Comment by marcustisater** [comment]
Yeah, I was thinking about that as well. The most important thing is that it's accessible for users so a "temporary" page for postcss.org is the best choice here. I will open issue.

**Comment by tunnckoCore** [comment]
Try https://github.com/verbose/verb or directly use `assemble` for the website - they are proved.

**Comment by jedmao** [comment]
Once we have the JSDoc comments, we can generate documentation pages with [YUIDoc](http://yui.github.io/yuidoc/) or something similar.

**Comment by marcustisater** [comment]
Just a quick wrap up from our [discussion](https://github.com/postcss/postcss.org/issues/71) at [postcss.org](https://github.com/postcss/postcss.org) to make sure everyone is on the same page. 

Our website runs on a markdown engine which means that we would need to get a generated markdown file from you guys to render it on our page. Is that possible to do? 

I also have another question; how are we going to "sync" changes for this page to postcss.org in best way possible? Everything gets generated here through some CLI tool, right?

**Comment by ai** [comment]
@jedmao I am finishing a JSDocs. Could TypeScript uses them instead of `.ts` files? Because I add types for most of methods and properties.

**Comment by ai** [comment]
I moved all API docs to JSDoc. So, where we should put generated HTML while we creating special page in postcss.org?

**Comment by ai** [comment]
`postcss.github.io/postcss`?

**Comment by ai** [comment]
Or we could put static HTML to postcss.org?

**Comment by ai** [comment]
@jedmao seems like we can remove `.ts` file https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by ben-eb** [comment]
@ai How about on *postcss.org/api*?

**Comment by ai** [comment]
@ben-eb we will definitely have `postcss.org/api`, but API page is not ready in `postcss.org` repo.

**Comment by marcustisater** [comment]
Yup, that's my fault. I'm working on it. We can do a redirect meanwhile?

**Comment by ai** [comment]
No rush, reflect is fine. We just need to fine best place for temporary JSDoc page

**Comment by andyjansson** [comment]
>So, where we should put generated HTML while we creating special page in postcss.org?
>postcss.github.io/postcss?
>Or we could put static HTML to postcss.org?

Can't we make a subdomain e.g. `api.postcss.org` and link it to Github Pages? Or am I misunderstanding the question?

**Comment by jedmao** [comment]
@ai, the JsDoc support in TypeScript is only one piece of the pie. The definition files also provide types and interfaces, some of which are inferred by the types declared within functions. I didn't look at your JsDocs yet, but I'm pretty sure that even if you were extremely thorough with return types and such, JsDocs by themselves would still fall short of the completeness of the complex type information that TypeScript provides, specifically with interfaces. Let me take a closer look and provide an example to illustrate my point, if you're interested, but this is perhaps why some people don't use TypeScript, because they truly don't understand the power it provides with IntelliSense, which is much more than documentation hints.

**Comment by marcustisater** [comment]
> Can't we make a subdomain e.g. api.postcss.org and link it to Github Pages? Or am I misunderstanding the question?

Yes, we can make that happen. Good point.

**Comment by ai** [comment]
@jedmao no problem, I just need your advice what to do with `.ts` files after JSDoc. I just need to remove JSDoc from TS files?

**Comment by jedmao** [comment]
It might be that simple, yes, but I need some time to investigate.

**Comment by andyjansson** [comment]
>The definition files also provide types and interfaces, some of which are inferred by the types declared within functions. I didn't look at your JsDocs yet, but I'm pretty sure that even if you were extremely thorough with return types and such, JsDocs by themselves would still fall short of the completeness of the complex type information that TypeScript provides, specifically with interfaces. 

@jedmao What do you feel is missing from JSDoc? 

Types can be represented using [`@param {type}`](http://usejsdoc.org/tags-param.html) for parameters and [`@type {type}`](http://usejsdoc.org/tags-type.html) for properties and variables. 

PostCSS doesn't really have interfaces, but rather base types (e.g. Node). The inheritance is expressed using [`@augments/@extends`](http://usejsdoc.org/tags-augments.html). Nevertheless, interfaces can be represented by using [`@interface`](http://usejsdoc.org/tags-interface.html) and creating a stub. Classes that implement said interface then uses [`@implements`](http://usejsdoc.org/tags-implements.html).

**Comment by ai** [comment]
@andyjansson yeap, theoretically JSDoc could replace TS files, but right now TS doesn't support all JSDoc features. For example, it doesn't support `@typedef`.

**Comment by andyjansson** [comment]
@ai I quickly glanced over the JSDocs you've added. From what I saw things are looking good.

**Comment by jedmao** [comment]
@ai you really have been very thorough with your JSDocs. Very impressed!

@andyjansson, you asked what was missing. I just thought of one example; though, I bet there are more. What about [generic types](https://www.typescriptlang.org/docs/handbook/generics.html)? See [this line](https://github.com/jedmao/postcss/blob/typescript/lib-ts/postcss.ts#L41), which allows a plugin like [postcss-triangle](https://github.com/jedmao/postcss-triangle/blob/master/lib/plugin.ts#L7) to provide an [interface/template of plugin options](https://github.com/jedmao/postcss-triangle/blob/master/lib/plugin.ts#L187-L203) via [generic types](https://www.typescriptlang.org/docs/handbook/generics.html).

**Comment by andyjansson** [comment]
> I just thought of one example; though, I bet there are more. What about generic types? See this line, which allows a plugin like postcss-triangle to provide an interface/template of plugin options via generic types. 

At this point we aren't talking about generating documentation for postcss anymore. That's only interesting when it comes to auto-completion and compile-time safety (which has its merits too, but it's kinda off-topic). (side-note: clojure compiler has generic types via `@template`). 

Anyway, let's back up for a moment though. Looking at the postcss repo, it looks like the typescript files aren't even being used and the es6 files are the actual sources. Why are these even there if they're not being used as the source?

**Comment by jedmao** [comment]
@andyjansson the TypeScript definition files are only for people who are writing a PostCSS plugin in TypeScript. In this case, the files **are** being used, as you can see [here](https://github.com/postcss/postcss/blob/master/package.json#L5). This makes it so a TS user can do:

```ts
import postcss from 'postcss';
```

And if their editor supports TypeScript, it will read the files in the [`d.ts`](https://github.com/postcss/postcss/tree/master/d.ts) folder for more information.

**Comment by andyjansson** [comment]
Oh I see, it holds no actual code. It's just a scaffold. Fair enough. 
If that directory were to be absent, would it read from the JS sources instead?

>See this line, which allows a plugin like postcss-triangle to provide an interface/template of plugin options via generic types. 

Couldn't this be accomplished by specifying `@type {type}` on `module.exports`?

If yes, then other editors could use that information as well, not just TypeScript-enabled ones, plus we wouldn't need to keep duplicate records of the documentation.

**Comment by jedmao** [comment]
@andyjansson, yes. I just finished reading [JsDoc support in JavaScript](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript) and it does look like they do support generic types with the following syntax:

```js
/**
 * @template T
 * @param {T} p1 - A generic parameter that flows through to the return type
 * @return {T}
 */
function fn4(p1){}

/** @type {function(string, boolean): number} */
var fn5;
```
Still investigating a bit on the existing JsDocs that @ai has written. I already made a comment about one of perhaps many inconsistent return types, so it looks like there might be yet more work to do on the JsDocs.

**Comment by jedmao** [comment]
You won't get any complaints from me as long as I can do this...

![typescript](https://cloud.githubusercontent.com/assets/1058243/16383973/dbf4c1de-3c4c-11e6-94c4-f542e9298a25.png)

That's the TypeScript definitions in action. As for the JsDocs in this repo, I can't even get them to work in vscode yet, so I'm not sure what I'm doing wrong.

**Comment by jedmao** [comment]
For those interested in trying it out, I put up a repo [`postcss-foo`](https://github.com/jedmao/postcss-foo/blob/master/index.ts) to see some in-editor vscode action. Still can't get the JsDocs to work though, and yes, I copied the js files from latest master, complete with JsDocs.

**Comment by jedmao** [comment]
@ai, I'm guessing you've tested the JsDocs in some editors already? Which ones did you try so far?

**Comment by ai** [comment]
I created JSDoc only for generated API page (you can see it by calling `gulp api`). Sorry, I didn't test it with IDE abd need a help here.

So, could we remove JSDoc from TS files, because we have it in JS files.

**Comment by jedmao** [comment]
I can't confirm that yet, @ai, because I can't get the JsDocs to work in-editor yet. For me, it could be a vscode issue, but I haven't verified that yet. Also, there are still some gaps between what my TS definitions provide vs. your JsDocs (example above with generic types). Lastly, I'm thinking there are a bunch more union types that are being returned that you haven't called out, so I wanted to look at that too, but I can't necessarily commit to investing time in that at this moment either.

Can someone – anyone – get these JsDocs to work in vscode? Or, at the very least, any other IDE that supports JsDoc? Can we start from there before gutting out the TS definitions?

**Comment by jedmao** [comment]
@ai, it might be easier to identify more issues w/ the JsDoc if you compare your JsDoc w/ the corresponding TS definition file. As those files were generated, that means they passed through the TS compiler successfully, resolving any multiple return type issues and such.

Of course, you can always move forward and iterate w/ patch versions, but I think it would be unwise to ditch the TS files until we know the JsDocs are working properly in-editor.

**Comment by ai** [comment]
@jedmao could you test it in WebStorm?

Anyway we could keep TS in old way, not problem

**Comment by jedmao** [comment]
Mmm, not really in the mood to install WebStorm. Let's just move forward w/ the JSDocs and keep the old TS files in there for now. How's that?

**Comment by andyjansson** [comment]
@ai works fine in WebStorm. This is with the `t.ds` directory deleted. 

![webstorm](http://i.imgur.com/eqLu9Rb.png)

**Comment by ai** [comment]
@jedmao maybe we could create a separated repo with typings? It is very rare case. Also it will be better for you to maintain it directly, without PRs.

**Comment by jedmao** [comment]
@ai there are already huge repos like [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) that provide definition files. That is one solution; however, the glory of having the files installed w/ `npm install postcss` is that you don't need to "hunt the typings down". They already come included, and because the `typings` key is provided in the package.json file, editors that support TS know exactly where to find them.

It seems to me that the golden path way to provide TS definitions is to reference them in your package.json file and include them in the `npm install`. That said, I know I can emit the definition files w/o comments, which, if I did, it would probably track down the documentation from the JSDocs. If only I could get the JSDocs to work in the first place under vscode. I'll submit an issue. Please, give me a bit more time to figure this out.

**Comment by jedmao** [comment]
I see now. @andyjansson's screenshot above is a relative module import, which is definitely working for me; however, that completely bypasses the package.json file's typings field. It appears that, at least, vscode does [not yet support IntelliSense for node module imports](https://github.com/Microsoft/vscode/issues/462). It's in their backlog though.

This means that even the JSDoc support won't work in vscode on a module import. The only way to get IntelliSense (for now) is via the `typings` field in the package.json file, which points to the TS definitions. If it's removed from this repo, then people will have to go hunting for them. Clearly, I wouldn't be happy about this, as all my plugins are written in TypeScript, but I guess I'm just one person!

**Comment by ai** [comment]
@jedmao yeap, I understand benefits of IntelliSense, but right now I think only 2-3 people uses Typescript. This is why maybe we should move type definition to addition package.

How complicated it would be for TS users? We can mention about type definition package in docs.

**Comment by jedmao** [comment]
I still don't agree w/ moving the definitions, but if you're set on the idea, there's nothing I can do about it. I don't think it requires any documentation, as TS users know where to look for definitions.

**Comment by ai** [comment]
@jedmao you can always proof the idea by showing more TS users. I am always open for community reasons for TS files.

But if you 2-3 people uses TS, it will be better to install one npm package for them, rather than load 2x more files for other users.

**Comment by jedmao** [comment]
I will never win that argument.

**Comment by jedmao** [comment]
TypeScript 2.0 is [almost out](https://github.com/Microsoft/TypeScript/milestones) and it looks like they will be [improving declaration file acquisition](https://github.com/Microsoft/TypeScript/issues/9184).

> Publishing declaration files with your packages would be the preferred course of action. for packages that do not include their declaration files, @types, would be the correct place for them.
@mhegazy, https://github.com/Microsoft/TypeScript/issues/9184#issuecomment-226299103

In other words, if you don't bundle the declaration files w/ the PostCSS package any more (the golden path), you should at least be able to install them via:

```
npm install --save @types/postcss
```
I would imagine we'll hear some big news about TS 2.0 this week or next.

**Comment by ai** [comment]
@jedmao I think we can’t remove TS files right now, because it will break API :). But I will remove it in 6.0 ;)
