### ISSUE TITLE
ES6 iterators

### ISSUE THREAD

**Issue by ai** [postcss/postcss#485]
PostCSS has callback-style iterators, but ES6 provide a better way.

It is a long-term issue, not in next few releases.

**Comment by jedmao** [comment]
How are you thinking ES6 will do it differently?

**Comment by ai** [comment]
@jedmao 

```
for ( let decl of rule.walkDecl(/^backgdound/) ) {
}
```

**Comment by jedmao** [comment]
Ahh, well that would be [similar to Python's walk](https://docs.python.org/2/library/os.html#os.walk). You could even use destructuring to get the index in there:

```js
for ( let [decl, index] of rule.walkDecls(/^background/) ) {
    // do stuff...
}
```

I suppose ES5 plugin developers would write it thus:

```js
rule.walkDecls(/^background/).forEach(function(decl) {
    // do stuff...
});
```

Unless they wanted to `break`, in which case it would be something like:

```js
for ( var i = 0, decls = rule.walkDecls(/^background/); i < decls.length; i++ ) {
    var decl = decls[i];
    break;
}
```

**Comment by ai** [comment]
Yeap, main benefits of using ES6 iterator is `break` and upper `return`.

For ES5 we can bring old API, I think.

Main problem of this task implementation is that iterators requires a `Symbol` polyfill.

Current browsers support (we can work if at least last version of each browser will support this ES6 feature): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by jedmao** [comment]
[es6-symbol](https://www.npmjs.com/package/es6-symbol) looks hugely popular.

**Comment by ai** [comment]
Any really unnecessary polyfill will be bad for client side usage of PostCSS (for example, for Inline Styles or tools like CodePen).

**Comment by Semigradsky** [comment]
Hi! I don't know which `symbol` support was when this ticket was created but now all major browsers have support (except IE of course). Is current support enough for implementing this?

**Comment by ai** [comment]
@Semigradsky what iterator you want? Can you show an example?

**Comment by ai** [comment]
Custom iterators didn’t become popular in ES6
