### ISSUE TITLE
options: {map: false} delete previous sourcemap comment from css

### ISSUE THREAD

**Issue by delka** [postcss/postcss#486]
If I set 
```
    options: {
      map: false,
```
PostCSS should won't create or update sourcemaps!
But it **delete** previous sourcemap comment from result css: `/*# sourceMappingURL=main.css.map */` so css-file no longer have sourcemap.

My config for PostCSS is default (from https://github.com/nDmitry/grunt-postcss).

Why I set `map: false`? I was try to make workaroud because PostCSS broked my sourcemap if I add Google MDL.css

**Comment by ai** [comment]
I will look when finish current refactoring

**Comment by ai** [comment]
@delka Hm. What is a reason to save old source map if you change CSS. Source map is very content based, if you change one line or letter in CSS, you can broke entire source map.

**Comment by delka** [comment]
@ai the reason is what PostCSS broke source map if I add material.min.css from Google MDL (http://www.getmdl.io/started/index.html). Bug looks like https://github.com/nDmitry/grunt-autoprefixer/issues/88
I read about promblem with `@charset "utf-8"` and delete it almost, but bug still present.

**Comment by ai** [comment]
Source map is a big file with `origin line, column → generated line, column` mappings. So if you disable source map in PostCSS, Autoprefixer will add new lines and it will broke previous mappings. So there is no sense to keep old source map because it became outdated after any sources changes.
