### ISSUE TITLE
Rename recursive `each` methods to `walk` methods.

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#487]
I have no issue with the `each` method, as it's non-recursive, just like [`jQuery.each`](http://api.jquery.com/each/). My issue, instead, is with the similarly-named methods:
- `eachInside`
- `eachDecl`
- `eachAtRule`
- `eachRule`
- `eachComment`

Based on the name alone, I would expect the above methods to also be non-recursive, akin to the `each` method. Unfortunately, this is not the case and I find it to be highly confusing.

Instead, I propose naming these recursive methods to replace `each` with `walk`. This would be similar to [walking folder structures in Python](https://docs.python.org/2/library/os.html#os.walk) or [traversing a tree](https://msdn.microsoft.com/en-us/library/Aa227569(v=VS.60).aspx). I propose the following method names:

| Before | After |
|-------------|--------------|
| `each` | `each` |
| `eachInside` | `walk` |
| `eachDecl` | `walkDecls` |
| `eachAtRule` | `walkAtRules` |
| `eachRule` | `walkRules` |
| `eachComment` | `walkComments` |

This would separate the confusion of the `each` method and bring absolute clarity to the intention behind each `walk` method, knowing that `walk` **_always_** means recursion.

**Comment by ai** [comment]
Hm, awesome idea.

We will not be able to add it on current 5.0. Only in next 6.0.

But I am definatly like this idea.

**Comment by jedmao** [comment]
Sounds great to me!

**Comment by ben-eb** [comment]
:+1:

**Comment by ai** [comment]
@ben-eb @jonathantneal @TrySound @andyjansson what do you think if we accept this changes to 5.0? @jedmao anyway make a PR and idea is great.

We have a time until Sunday features freeze.

**Comment by lydell** [comment]
+1 For adding in 5.0.0—but only if the old names remain as aliases until 6.0.0 and print deprecation warnings.

**Comment by TrySound** [comment]
Deprecation is ok. For 6.0 need a time to rewrite all plugins :))

**Comment by jedmao** [comment]
@lydell the PR does preserve the old names and print deprecation warnings, so we're OK there.
