### ISSUE TITLE
SugarSS syntax

### ISSUE THREAD

**Issue by ai** [postcss/postcss#495]
Many users asked about some compact syntax like Sass or Styles. In PostCSS 5.0 we can make it, it is good time to find the best compact syntax.

My requirements:

* No `;`.
* Short syntax for comments.
* Allows multiline values.
* Consistency (not like Stylus, when you can write in different syntax).

**Comment by ai** [comment]
First suggestion:

```scss
// Comment

@charset "UTF-8"

a {
  color: black
  background: white,
              linear-gradient(black, white)
}
```

Pros:

* Intuitive multi-line values
* Do not use indents

Cons:

* We still have `:`, `{` and `}`

**Comment by ai** [comment]
Second suggestion:

```stylus
// Comment

@charset "UTF-8"

a
  color black
  background white, \
             linear-gradient(black, white)
```

Pros:

* No `:`, `{` and `}`

Cons:

* `\` before `\n` in multilines values.

**Comment by azat-io** [comment]
The first suggestion is better. The second suggestion is not supported in any text editor and looks difficult for reading CSS code.

**Comment by ai** [comment]
@azat-io can you describe objective, why indent-based is hard to read? Because many Sass developers said, that CSS syntax is harder. So I think it is question of time.

**Comment by ai** [comment]
The main problem with first syntax is that it has only one benefit, no `;`. Compact comments and nesting are already possible with SCSS syntax for PostCSS.

@azat-io what do you think?

**Comment by azat-io** [comment]
@ai Hmm.. Don't know. Maybe it's just my habit. But in my personal opinion the first suggestion looks better for my code understanding. The second benefit of the first suggestion is compact comments. :smiley:

**Comment by ai** [comment]
@azat-io SCSS syntax for PostCSS already supports compact comments.

**Comment by 1j01** [comment]
```sass
@charset "UTF-8"

// Braces are for noobs
p
  // Colons make a lot of sense
  color: #555
  font-family:
    "Helvetica" // Newlines imply commas
    sans-serif // within indented lists

// Newlines in selectors imply commas as well
.good button
.okay button
  background: greenish bluey black // TODO: write PostCSS plugin

h1, h2, h3, h4, h5, h6
  commas-are: "always allowed", "of course"
  
```

**Comment by ai** [comment]
@1j01 we have a problem with some plugins with `:` in selector. Like https://github.com/jedmao/postcss-nested-props

**Comment by 1j01** [comment]
@ai Wouldn't that then be parsed as a value? Might need to be changed in the normal parser, to treat what are now selectors with trailing colons as properties. (You don't really want selectors ending in colons, you just want it to parse as something plugins can use.)

**Comment by jedmao** [comment]
For the record, [postcss-nested-props](https://github.com/jedmao/postcss-nested-props) is aligned with [Sass syntax](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties) and I would be happy to update it to whatever new requirements we define.

**Comment by ai** [comment]
@jedmao yeap, other solution, we can deny unbracket `:` in selector. But I think there is a few plugins with `:` in selectors anyway.

**Comment by alwillis** [comment]
@ai I like the second version—pretty much the same as the original [Sass syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html), which I really enjoyed using back in the day.

I like the direction this is going in—no semicolons or curly braces, which adds lots of visual noise.

**Comment by Frank74mgn** [comment]
I like second version. Stylus minimal syntax + multiline write ( / ), must be very cool.

**Comment by urec** [comment]
1j01 предложил хороший вариант ,можно писать мультилайновые значения(на разных строках) 
```javascript
p
  // Colons make a lot of sense
  color: #555
  font-family:
    "Helvetica" // Newlines imply commas
    sans-serif // within indented lists
```

возможность задавать мультилайновые значения только если после свойства стоит " : "(двоеточие)  stylus синтаксис +++

**Comment by ai** [comment]
@urec сейчас есть плагины, которые используют `:` в селекторе. Да и от `:` тоже хотелось бы избавиться

**Comment by gazay** [comment]
Closer to Sass syntax – is for the win as I think. The second variant is cleaner. Also `\` is really necessary? Because we can match all related to property by first property indentation as in Haskell:
```Sass
.square
  background: white,
              linear-gradient(white, black)

// And in this case maybe we can omit brackets in arguments too
// It allows us to write clean code with 80 column rule =)
.square
  background: white,
              linear-gradient to bottom right,
                              white,
                              black
```

**Comment by gazay** [comment]
I understand about multiline selectors, but if here will be no nested styles, there is no problem, right? All selectors strat only from first column

**Comment by ai** [comment]
@gazay nested styles is important

**Comment by gazay** [comment]
But they aren't finish with `:`?

**Comment by kezzbracey** [comment]
My vote is also for the second version. I know a few people who are using Stylus before PostCSS right now purely so they don't have to type curly braces or semicolons.

I can't speak as to the practicality of including colons, but I do know a lot of people who like terse syntax always use colons to make code more readable.

Re. text editor support / highlighting, any Stylus plugin should handle that, e.g. for Sublime Text or Atom.

**Comment by talgautb** [comment]
may be we need 2 plugins ? I need use `:` but i don't like brackets

**Comment by azat-io** [comment]
Best suggestion @talgautb

**Comment by andrejsm** [comment]
There should be (1) distinct parsers for one or another style. Or make all configurable and allow to (2) explicitly set each option. Or to set more general (3) configuration preset.

Example 1
```js
let parser = require('postcss-parser-stylus-alike')
postcss([...]).process(input, { parser }).then(...)
```

Example 2
```js
let options = {
  parser: {
    braces: false,
    colons: false,
    semicolons: false,
  }
}
postcss([...]).process(input, { options }).then(...)
```
or event go for `.postcssrc`
```yaml
parser:
  braces: 0
  colons: 0
  semicolons: 0
```

Example 3
```js
let options = {
  preset: 'noBracesSemicolons',
}
postcss([...]).process(input, { options }).then(...)
```

If omitting braces or colons will be optional, then should go for max!

**Comment by kezzbracey** [comment]
Flexibility is definitely great from the user side, but from the developer side it makes it difficult because it means many more tests have to be done for every possible combination of syntax options.

It's one of the reasons the Stylus devs have talking about removing the options to code with different syntaxes and settling on one approach.

I'm getting ready to release a few plugins, and I can imagine that having to make them work with multiple syntax options could be pretty painful.

**Comment by andrejsm** [comment]
@kezzbracey I fully agree with you. Therefore I prefer my first suggestion - distinct parsers. And seems at v5 PostCSS will have such a option.
To vote for proposed styles I will go with @ai's first suggestion as it is semantically similar to JS I write
```js
let style = {
  color: 'red',
  fontSize: '1.6em',
}
```
```css
div {
  color: red
  font-size: 1.6em
}
```
I just don't want to type semicolons. Braces and colons I want to retain. They are used in JS, but semicolons mainly are redundant. Currently I have minor issues with forgetting to type semicolons in css.

**Comment by kezzbracey** [comment]
@andrejsm Even though I prefer not to use curly braces, you do make a good point that keeping things semantically similar to JS would give consistency.

Using Emmet can make it feel like you're barely writing curly brackets, but semicolons are always a slow down and a pain.

So in short, I think you might have just bought be around to agreeing the first option might be the better one.

**Comment by akella** [comment]
I think the best approach is in Sass, it is also heavily tested by a lot of teams now.
```
.l
	+clr
	.l-col1
		float: left
		width: 20%
	.l-col2
		float: right
		width: 70%
```
Leaving ':' for readability, removing {} like noise, using indentation to parse.

**Comment by ai** [comment]
@andrejsm nope, flexibility had really bad history in Stylus. It has very complicated parser with unexpected behaviour.

@talgautb I am not against 2 parsers, but I will write only one ;). It is not only `:` or not-`:` question. If we remove `:` it will hcange many other aspects of syntax.

**Comment by ai** [comment]
@gazay your Haskell suggestion is awesome. Main question, do it will be understanded by users without reading a docs?

**Comment by ai** [comment]
@akella what about multiline values and multiline selectors?

**Comment by akella** [comment]
@ai in sass they proved to be  useless for setting css values, this is just uncomfortable to type. If you mean arrays or some other things - we can have some magic symbol at start, like  {}. Multiline arrays are possible in Sass syntax too.

**Comment by ai** [comment]
@akella i mean very long values like gradients. It is better to write each gradient on new line to keep it clear.

**Comment by akella** [comment]
@ai understood you point, but i think this case is not that important, mostly all the gradients are hidden inside mixins now.

**Comment by gazay** [comment]
@ai in Haskell it solved by good, very clear explained compilation time error messages

**Comment by kezzbracey** [comment]
@akella There are still many workflows where gradients aren't hidden inside mixins. For example, people use software to grab CSS out of Sketch / Photoshop / Reflow designs and drop it straight into code. Multiline gradients are common in these cases.

Also, plugins where several arguments are passed might be more easily used with multiline values.

**Comment by akella** [comment]
@kezzbracey agree on that, but i think the most important thing, that : and {} are _way more_ common inside our CSSs than those multiple gradients.

**Comment by kezzbracey** [comment]
@akella Fair point.

**Comment by kezzbracey** [comment]
I just wanted to chime in with an example of where multi-line values can be handy for working with plugins.

I'm developing a plugin at the moment to provide a PostCSS method of using @MoOx's [color npm module](https://www.npmjs.com/package/color). One example of how it can be used is where a value is given with three arguments passed between brackets, e.g.

```
.element {
	background-color: is_light(
		$background_main,
		color( $background_main shade(3%) ),
		color( $background_main tint(3%) )
	);
}
```
1. The first argument provides a color to check the luminosity of, i.e. whether the color is light. 
2. The second argument is the color to use if the "is_light" check returns true. 
3. The third argument is the color to use if the "is_light" check returns false.

When working on this I played with a few approaches to handling the "is light?" logic, and found this structure to work the best. But allowing multiple lines in the value is pretty important for readability.

I'm guessing that perhaps other plugin developers might find they want to use a structure like this, and as such it would be great if there were a way to make multi-line values also work with the upcoming terse syntax.

**Comment by 1j01** [comment]
@kezzbracey In my syntax this would be able to be written as
```sass
.element
    background-color: is_light(
        $background_main
        color( $background_main shade(3%) )
        color( $background_main tint(3%) )
    )
```
(The rules for comma insertion could be to insert a comma at each newline in a value preceded by non-whitespace, but not preceded by `/[+\-*/^\\(\[{]\s*/` and not followed by `/\s*[+\-*/^\\)}\]]/`)

**Comment by kezzbracey** [comment]
@1j01 Yeah that looks really good. If it could be made to get along with all plugins it would be great.

**Comment by talgautb** [comment]
@1j01 +1

**Comment by corysimmons** [comment]
Definitely keep the `:`

**Comment by imShara** [comment]
Drop braces, please

**Comment by pvalentim** [comment]
Hey, any progress on this?

**Comment by ai** [comment]
My current plan:

* Autoprefixer 6.0
* PostCSS birthdays events
* “The right way to use PostCSS” keynotes
* 10 days holidays

So I can return to this issue only after October 3.

**Comment by pvalentim** [comment]
Thanks for the update, have a nice holiday!

**Comment by a-x-** [comment]
:+1:

**Comment by a-khannanov-parc** [comment]
I vote for @akella approach

**Comment by j-walker23** [comment]
second @akella approach

**Comment by onemanstartup** [comment]
I say haskell approach is the best, but with so many requests for `:`, it is ok to consider semicolons as optional. I think it won't add too much complexity for parser.

**Comment by campykid** [comment]
i vote for second suggestion

**Comment by ai** [comment]
Let’s collect cases, that I want to support in this syntax:

Multiline values:

```sass
.button
  background: linear-gradient(white, black),
              linear-gradient(white, black)
```

Multiline values on new string:

```sass
.button
  background:
    linear-gradient(white, black),
    linear-gradient(white, black)
```

Colon in selector:

```sass
.text
  font:
    family: Arial
```

Multiline selectors (with `\n` in any place of selector, not only after `,`):

```sass
.one,
.two,
.three
  color: black
```

Right now I see this way to find selector or declaration (“has `:`” mean to have `:` outside brackets):

1. If line has `:` inside and no indent increase on next lines, it is a declaration.
2. If line has `:` inside and next line has indent increase, but no `:`, it is a declaration.
3. If line has no `:` and no indent increase, it is part of selector.
4. If next line has `:` and indent increase, so this line is selector.

Limitations:

1. No `:` in the middle of multiline selector (but anyway we have no this types of plugins).
2. No `:` in the middle of multiline value (but I think it is illegal in CSS spec).
3. No indent changes in multiline selectors.
4. Multiline value must have indent increase.

Do anyone has examples to broke this rules (I really need fresh mind look).

**Comment by ai** [comment]
But parser for this rules will be really complicated, because it should look ahead.

**Comment by ai** [comment]
Other question: should we put 2 space indent as part of syntax?

I really think to raise error on tab symbol in indent, because it is really dangerous to have tabs/spaces mix in indent-based syntaxes.

**Comment by 7rulnik** [comment]
@ai no.
I like how it's work in Jade. Jade throw error only if you mix tabs and spaces.

**Comment by j-walker23** [comment]
@ai Hey, i am brand new to stylus, convert from long time sass user (the "old", but so much better syntax!) and am trying to get up to speed on stylus.

Could you please explain in noob terms what you mean in 
> Right now I see this way to find selector or declaration (“has :” mean to have : outside brackets):

Specifically what is meant by outside brackets please.

Also i have a question about the multiline selectors. Is there anything in the syntax currently that would fail if the commas were not included? Where the parser would treat each selector as if they had commas after them.

```css
.one
.two
.three
  color: black
```

I remember my IDE being confused in sass and would indent the selectors with auto format like below which was annoying. Obviously not an important reason, i was just curious so i thought i would ask.

```css
.one
    .two,
        .three
  color: black
```

**Comment by ai** [comment]
@j-walker23 hi, why you asking about Stylus? Here we discuss next syntax for PostCSS, not Stylus :).

**Comment by j-walker23** [comment]
@ai haha damn, been a long night. I was thinking about stylus i guess. I am trying to implement `poststylus` now in a jspm css loader which brought me here a little while ago because i would love to just use PostCSS, but still have the clean indent syntax i have grown to love in pre processors. 

Thanks for letting me know, updating.

**Comment by kezzbracey** [comment]
I think the examples / plans look quite thorough. I can't think of anything right now that would break them.

I also agree with @7rulnik in that it would be great to have the option to choose between tabs or spaces. I think a lot of devs are set in their ways of using one or the other.

**Comment by dustindowell22** [comment]
I'm not sure whether you're still debating on `:` vs no `:` but i'm definitely for the use of `:`. I would even use curly braces again just to have the colon back. I think it helps readability a lot.

**Comment by ai** [comment]
@dustindowell22 do not worry, we are on `:` syntax

**Comment by jenius** [comment]
Hi guys! Just popping in to check the progress on this. Having a plugin that removes brackets and semis would truly be an amazing productivity boost. If there's any way I can help, let me know. Otherwise will be looking forward to this :grinning:

**Comment by ai** [comment]
There will not be any progress until Riga WebConf, sorry :).

**Comment by DavidOliver** [comment]
I'm glad to see that (a) simpler syntax(es) is/are being planned, though I appreciate it's likely complicated to implement. My personal thoughts/prefernces follow.

I'm used to the indented Sass type of syntax and have been using this with Stylus:

    .selector
        property: value

I find the colon very easy to type and that it helps with readability. I don't like typing semi-colons as I feel, like the Go developers, that they should be replaceable by machines. And I absolutely hate typing curly brackets in CSS. I don't find the argument for consistency between different languages very convincing; CSS and JS seem so different in their capabilities and intended uses.

I'm not anywhere nearly as bothered about multiline values such as gradients as these generally occur relatively infrequently. My preference regarding tabs is hard/real tabs.

How would a simpler syntax affect things like `@custom-selector :--seltest .one, .two` - could that remain as is?

**Comment by ai** [comment]
I found some problem. How we would be able to implement multiline at-rules? For example, long `@media` or `@supports`.

**Comment by dustindowell22** [comment]
Are parentheses required? If so, maybe you could check if there's a parenthesis before you would check to see if there's a colon. If there's a parenthesis, then that line would be part of the multiline rule.

```scss
@media
  (min-width: 100px) // parenthesis before colon -> multi
  and (max-width: 200px) // parenthesis before colon -> multi
  width: calc(100% - 100px) // parenthesis not before colon -> property/value
```

**Comment by ai** [comment]
@dustindowell22 nice suggestion. But it will only simplest cases, but we will still have confused cases.

I try to avoid Stylus catastrophe because of too many rule in parser.

Maybe we just give up and use `\` before new lines in at-rule.

**Comment by dustindowell22** [comment]
What is an example of some code that could be confused? I don't think I like the idea of using an escaping character. Is there any case where a plain word like `handheld` on a single line without a value used in places other than in an at-rule?

**Comment by ai** [comment]
2, 3 and 4 lines of your example looks like selectors. Don't forget that your rules should split divide at-rules and selector too.

**Comment by dustindowell22** [comment]
Oooh. I see. I've only just started messing with parsers. I suppose I was thinking once within an at-rule the parser would sort of switch gears to a short of mini-parser until the end of the at-rule had been reached, then go back to dividing rules and selectors. I'll have to think about this one for a while longer.

**Comment by 1j01** [comment]
So, options...
* Backslashes before newlines
* Require some sort of brackets around the at rule's `afterName` (e.g. `@media (screen and...)`)
* Require curly brackets around the body if there is one, like in plain CSS

But noone's gonna want to have to do any of those, and decent error handling could be difficult, so...
* Empty rules are not allowed
```sass
@single-keyframe
  cool-keyframe // this is part of the at rule's `afterName`
  iframe // this is a rule because it's followed by indented declarations*
    background: black // this is a declaration
  color: red // this is a declaration

// *or any indented lines as long as they aren't part of a parentheical,
// such as may be used with media queries
```
The parser rules might get complicated, but I think it's worth a go. We just need lots of tests, right?

**Comment by ai** [comment]
But selectors can be multiline too ;-)

**Comment by 1j01** [comment]
@ai I thought I was forgetting something! Yeah, that can be completely ambiguous.

**Comment by ryanmclaughlin** [comment]
Any updates on this question?

**Comment by thisconnect** [comment]
> Many users asked about some compact syntax like Sass or Styles. In PostCSS 5.0 we can make it, it is good time to find the best compact syntax.

Are you going to make postcss another sass/stylus/less? I hope this will be a plugin and would not blowup postcss. 

Instead of introducing a new non-standard, wouldn't it be nice if there is fully compatible postcss-less, postcss-stylus, postcss-sass and what you suggest... postcss-iLoveNewLines

**Comment by ai** [comment]
@ryanmclaughlin I am on it right now https://github.com/postcss/sugarss

**Comment by ai** [comment]
@thisconnect yeap, `postcss-less` or `postcss-sass` are important. Do you want to create them?

I specially write a docs about syntaxes to ask other developers to help me: https://github.com/postcss/postcss/blob/master/docs/syntax.md

SugarSS will be a better replacment, rather than Sass syntax, because SugarSS will allow multiline selectors and properties without any strange symbols.

**Comment by thisconnect** [comment]
I don't hate CSS, that is probably why I ended up using postcss. If i did not like CSS I would probably use less/sass/stylus/sugars . Nevertheless I don't mind if a project uses one of the 4 custom syntaxes. But I get more excited about standards becoming reality, for example http://caniuse.com/#feat=css-variables

**Comment by vtrushin** [comment]
May be try to detect, does is last symbol at line is comma. If yes, ignore tab indent as semantic for next line

**Comment by dustindowell22** [comment]
I'm not really sure how I feel about this suggestion or how it would work but... double indents?

```
@media
    handheld
    min-width: 100px
    and max-width: 200px
  width: calc(100% - 100px)
```

**Comment by ai** [comment]
@dustindowell22 double indent can't be found without reading a docs. Also it will be hard to detect indent size of first indent will be double.

**Comment by corysimmons** [comment]
Do people really use multiline stuff that often? I've never needed to break a CSS rule down into multiple lines...

**Comment by jedmao** [comment]
I use multi-line all the time. It makes the diffs less confusing.

**Comment by azat-io** [comment]
What about SugarSS extension?

**Comment by ai** [comment]
I am playing in Witcher 3. No opensource until good ending.

**Comment by azat-io** [comment]
@ai Lol :smile:

**Comment by corysimmons** [comment]
rofl, :+1: :100:

**Comment by DavidOliver** [comment]
@ai, it's been 9 hours. Have you finished yet? ;)

(I started the game a while back and need to get back into it. And Dark Souls. *sigh*)

**Comment by ai** [comment]
@DavidOliver Withcer 3 has more than 100 game play hours :D

**Comment by ai** [comment]
BTW, I already started a repo and made some parts of logic: https://github.com/postcss/sugarss

I think 25% is ready.

**Comment by ai** [comment]
Also SugarSS will accept only two types of indent: 2 spaces and 4 spaces.

**Comment by 1j01** [comment]
@ai That's ridiculous and prejudiced. We should support any indentation, just not mixed.

**Comment by jedmao** [comment]
I'm inclined to agree with @1j01. All about tabs here.

**Comment by corysimmons** [comment]
I hate tabs, but my company uses them. They're pretty much everywhere. Is there some technical limitation or is this just a "screw tabs" kinda thing?

**Comment by jedmao** [comment]
![tabs-vs-spaces](https://cloud.githubusercontent.com/assets/1058243/12585832/61d9a196-c413-11e5-8338-17b8942b2545.gif)

**Comment by ai** [comment]
Mixing tabs and spaces for indent-based languages is very dangerous. This is why it is better to deny tabs abd solve problem at the beginning.

For example, YAML denies tabs too.

**Comment by jedmao** [comment]
I like the Python approach where all indentation is supported, but MIXED indentation is denied.

**Comment by corysimmons** [comment]
PostCSS users aren't idiots. We figured out the whole tab/space thing a long time ago. Just let a few people make mistakes that they'll quickly figure out, and let everyone else pick their preferred syntax.

**Comment by 1j01** [comment]
@ai "Mixing tabs and spaces for indent-based languages is very dangerous. This is why it is better to deny spaces and solve problem at the beginning."

Broken logic.

**Comment by ai** [comment]
OK, I will try to add spaces-tabs mixing logic. But it is uch harder, than just add tab-check in tokenizer.

**Comment by jedmao** [comment]
Too many people are not aware of what "mixing" tabs and spaces actually means. It's perfectly OK to have leading tabs, followed by spaces. What you want to flag is two scenarios:
  1. Leading spaces, followed by tabs.
  1. Leading tabs, followed by spaces, followed by more tabs.

What you do NOT want to flag are the following scenarios:
  1. Leading tabs (indentation), followed by spaces (alignment).
  1. Anything that happens after indentation (you shouldn't be concerned about it).

**Comment by 1j01** [comment]
e.g. Strict indentation checking that @jedmao wouldn't like:
```coffee
used_tabs = false
used_spaces = false
for line, lineno in code.replace(/\r/g, "").split("\n")
  for char, colno in line
    if char is "\t"
      used_tabs = true
      if used_spaces
        throw new Error "Mixed indentation, unexpected tab on line #{lineno + 1}, column #{colno + 1}"
    else if char is " "
      used_spaces = true
      if used_tabs
        throw new Error "Mixed indentation, unexpected space on line #{lineno + 1}, column #{colno + 1}"
    else
      break
```

**Comment by 1j01** [comment]
Minimally strict checking that only looks for ambiguities:
```coffee
previous_indentation = ""
for line, lineno in code.replace(/\r/g, "").split("\n")
  indentation = line.match(/^\s*/)[0]
  for previous_indentation_char, colno in previous_indentation when indentation[colno]
    if indentation[colno] isnt previous_indentation_char
      char_name = switch indentation[colno]
        when "\t" then "tab"
        when " " then "space"
        else JSON.stringify(indentation[colno])
      # throw new Error "Mixed indentation, unexpected #{char_name} on line #{lineno + 1}, column #{colno + 1}"
      throw new Error "Mixed indentation between lines #{lineno} and #{lineno + 1} on column #{colno + 1}"
  previous_indentation = indentation
```
Could add a check for spaces followed by tabs.

**Comment by jedmao** [comment]
@1j01 to be clear, there's nothing wrong with spaces followed by tabs unless they are then followed by more tabs.

**Comment by 1j01** [comment]
@jedmao I suppose so. Not inherently, anyway.

**Comment by jedmao** [comment]
@1j01 spaces followed by tabs are considered alignment is my point, which some people do (not me), but some do.

**Comment by ai** [comment]
@jedmao I remove tab deny code https://github.com/postcss/sugarss/commit/489a87f046379ce2ae949522ba56f06ee8e92849

**Comment by corysimmons** [comment]
@ai So happy to hear you're working on this. :^) :+1: :100:

**Comment by jedmao** [comment]
Thank you @ai!

**Comment by lalomartins** [comment]
Sorry, it's unclear to me — will there be nesting? With what syntax? @akella's [sass-redux](https://github.com/postcss/postcss/issues/495#issuecomment-132960493)?

It could also be an option to just detect them insofar as not breaking the parser, then outputting them again to be handled by something like [postcss/postcss-nested](https://github.com/postcss/postcss-nested) IMO.

**Comment by ai** [comment]
@lalomartins yeap it will support nesting

**Comment by lalomartins** [comment]
:+1:

**Comment by danielbayley** [comment]
How about allowing `# comments`?

This would be nice with CoffeeScript together with this terse sass-like syntax.

I appreciate that `#` is for `#id`s in CSS, but hashes followed by a space could easily be comments instead. Besides, the use of `#id`s seem to be mostly discouraged anyway.

Something like `/#\s+/` to match them?

**Comment by ai** [comment]
@danielbayley Yeap. I was thought about `#` comments too.

But having `#\s` is too tricky. Most of languages with `#`-comments allow to miss a space between `#` and text. Look for example to bang comment `#!/usr/bin/bash`.

This is why I think having `# comments` will not be a good idea

**Comment by dustindowell22** [comment]
I agree that `#` comments would conflict with CSS. Are we still stuck on the multi-line indents problem?

**Comment by ai** [comment]
@dustindowell22 nope, everything fine. Right now `.sss` to `.css` complication is finished. I need just `.sss` to `.sss` conversion (for tools like postcss-sorting).

**Comment by jenius** [comment]
@ai for real? is there a beta release we can try out if we are just going for straight compilation? can't wait to get my hands on this :grin:

**Comment by ai** [comment]
@jenius You can try it from GitHub https://github.com/postcss/sugarss

I think SugarSS will be finished on this or next week.

**Comment by danielbayley** [comment]
> I think SugarSS will be finished on this or next week.

:+1: 

Hopefully I can figure out how to get this into [atom-language-postcss-sugarss](https://github.com/danielbayley/atom-language-postcss-sugarss) asap…

**Comment by ai** [comment]
SugarSS code base was finished: https://github.com/postcss/sugarss

I am writing a docs and converting tool right now.

**Comment by dbox** [comment]
Thanks for the all the work @ai!

**Comment by corysimmons** [comment]
:tada:

**Comment by danielbayley** [comment]
[atom-language-postcss-sugarss](https://atom.io/packages/language-postcss-sugarss) is up now. It's really just scaffolding at this point though as it just extends the existing Sass syntax highlighting. Any help is welcome…

> We are working on syntax highlight support in text editors.

**Comment by ai** [comment]
@danielbayley you are fast :). Awesome work. I added it to SugarSS README.md and installed to local machine for test highlights :).

**Comment by ai** [comment]
SugarSS 0.1 was released. Please try and post your feedbpack: https://github.com/postcss/sugarss

**Comment by aazcast** [comment]
Hi i modify a SASS Syntax Highlight to work with .SSS files.
You can find it in Package Control or https://github.com/aazcast/Syntax-SugarSS-SublimeText

**Comment by ai** [comment]
@aazcast wow! Could you send PR with your highlighter to SugarSS docs?

**Comment by aazcast** [comment]
@ai Hi i just send PR. This is the packagecontrol link: https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20SSS%20SugarSS

is available to install using packagecontrol.
