### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#501]
How would you feel if I (or anyone) added code coverage to this project? This can be achieved with [isparta](https://github.com/douglasduteil/isparta) for ES6/babel.

See the [postcss-triangle package.json](https://github.com/jedmao/postcss-triangle/blob/6b428fd0f89011373858db02813bff6f554293a8/package.json#L9-L11) for how the tasks might look.

We don't need a badge on the README, per se, but we can definitely prevent code from being introduced that doesn't have tests to go along with it.

**Comment by ai** [comment]
I want a code coverage :)

**Comment by andyjansson** [comment]
@jedmao What kind of code coverage is it?

**Comment by jedmao** [comment]
isparta uses [Istanbul](http://gotwarlost.github.io/istanbul/).

**Comment by andyjansson** [comment]
So no condition coverage?

**Comment by jedmao** [comment]
I'm unclear what you're talking about.

**Comment by andyjansson** [comment]
https://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria

**Comment by lydell** [comment]
Is some other code coverage rool that _does_ measure condition coverage?

**Comment by jedmao** [comment]
Istanbul says:
> All-javascript instrumentation library that tracks statement, branch, and function coverage and reverse-engineers line coverage with 100% fidelity.

I guess that means no condition coverage, but it's sure better than no coverage at all and I'm unaware of any tool that measures condition coverage for JavaScript; though, i haven't really looked into it.

What I do know is that Istanbul is very well-known/used and widely supported, so it's bound to implement well into this code base as it has for me on many other projects.

**Comment by ai** [comment]
By some strange reason, `/* istanbul ignore next */` doesn’t work, so I can’t hide depreacted code.

**Comment by jedmao** [comment]
I've used `/* istanbul ignore next */` myself, many times. What is the example that's not working? Maybe you need 2 of them?

**Comment by ai** [comment]
I tried to add this comment att start of depreacted method, but coverage HTML shows red lines next anyway.

**Comment by jedmao** [comment]
Hmm. Yeah, it's not working. Maybe it's configuration related? Because I've definitely had it work for other projects.
