### ISSUE TITLE
Node#toString seems not to include `before` for any nodes

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#522]
The Changelog says that for 5.0

> `Node#toString` does not include `before` for root nodes.

But I'm finding that `Node#toString` is not including `before` for *any* nodes.

Is that intentional, or a bug?

If intentional, maybe it should be documented, both in the Changelog and in the API docs. Also, is there a function that returns what the old `toString()` returned — that is, the node with its `before` and `after` stuff? Or do I need to add those back in myself when they're needed?

**Comment by ai** [comment]
Root, but not `Root` node. Change is that `someNode.toString()` will not contain `someNode.raws.before`.

**Comment by davidtheclark** [comment]
Ok, thanks for clarification. I guess I don't understand why the word "root" is there in the changelog entry?

**Comment by ai** [comment]
@davidtheclark yeap, it is not good word there but I didn’t find better
