### ISSUE TITLE
How do i select CSS folder and Dist Folder?

### ISSUE THREAD

**Issue by resetme** [postcss/postcss#530]
Hi, 

Im trying this plugin but i have some doubts. How can i select my _css folder  so postcss can read all ny css and save it in another folder?

The destination is dist:{ src: path??
but the input is?

Thanks

**Comment by ai** [comment]
Hi. I think you asked not about PostCSS intself (because it is a core library and do not work with file). I asked question about [grunt-postcss](https://github.com/nDmitry/grunt-postcss).

Sorry, I use only Gulp and webpack and can’t help you. You should create issue in grunt-postcss project.
