### ISSUE TITLE
Incompatibility w/ PostCSS 5.0, Autoprefixer (Gulp)

### ISSUE THREAD

**Issue by joshdrink** [postcss/postcss#531]
@ai As requested. If you or any gulp users can shed light on what I'm doing wrong, I'd appreciate it. I don't really care about warnings if you can make this work with 5.0. The gulpfile below works flawlessly with 4.1.x, and upgrading to 5.0 shoots me this error.

*My gulpfile:*
![screen shot 2015-08-28 at 7 51 07 am](https://cloud.githubusercontent.com/assets/6960386/9544900/e605f99a-4d5a-11e5-8e0e-46eaf5b2337c.png)

*The error:*
![screen shot 2015-08-28 at 7 51 37 am](https://cloud.githubusercontent.com/assets/6960386/9544906/eb668bde-4d5a-11e5-869e-5c117d04e804.png)

**Comment by ai** [comment]
I need version of all PostCSS related packages. Especially `gulp-postcss`

**Comment by joshdrink** [comment]
@ai 

![screen shot 2015-08-28 at 8 28 27 am](https://cloud.githubusercontent.com/assets/6960386/9545325/d33472ac-4d5e-11e5-9e34-00136f484f00.png)

**Comment by ai** [comment]
BTW, cssnano is PostCSS plugin too, you can use it directly.

**Comment by joshdrink** [comment]
@ai That I knew, but they haven't updated to 3.0 yet and therefore its not compatible with PostCSS 5.0 :(

**Comment by ai** [comment]
I see postcss-import is dependencies? Do you use it somewhere?

**Comment by joshdrink** [comment]
@ai it's the `includes` variable in the `gulpfile.js`

**Comment by ai** [comment]
Also, can you make clean install. Remove `node_modules` and then run `npm install` again.

**Comment by ai** [comment]
OK, I think, the problem is not from Autoprefixer, but from postcss-import. PostCSS 5.0 has compatibility hooks to work with 4.x plugins, but postcss-import do not use public API, so there is no way to fix it.

Can you update postcss-import to latest version with PostCSS 5.0 support?

**Comment by joshdrink** [comment]
@ai I tried the clean install, same error. I'll try updating `postcss-import` explicitly.

**Comment by joshdrink** [comment]
@ai Perfect! Everything is working. Thanks man, I appreciate the hasty help!

**Comment by ben-eb** [comment]
@joshdrink 3.0 is blocked by autoprefixer update, sorry.

**Comment by joshdrink** [comment]
@ben-eb No worries, using it outside PostCSS for now is perfectly fine with me until the update comes out! :)
