### ISSUE TITLE
Warnings on root node have line/column positions of 0

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#533]
If I create a warning and make the `node` option be a `Root` node, I'm being told that the position is `line: 0, column: 0`.

Seems like a bug.

**Comment by ai** [comment]
Why you think it is a bug?

`Root` node represents all CSS conten and start at 0, 0.

**Comment by davidtheclark** [comment]
I thought it would be line 1, column 1?

**Comment by davidtheclark** [comment]
The use-case is to attach warnings to `root` and still use `index`, `word`, etc., to get accurate positions. If you have a way to do that, that's really all I need.

**Comment by davidtheclark** [comment]
(Sorry, didn't mean to close.)

**Comment by ai** [comment]
Fixed 2860300

**Comment by davidtheclark** [comment]
Thanks!

**Comment by ai** [comment]
Released in 5.0.4
