### ISSUE TITLE
Rule constructor triggers derecation messages

### ISSUE THREAD

**Issue by pascalduez** [postcss/postcss#545]
Hey,

creating a new rule with the rule constructor triggers warnings since v5:

```js
let newRule = postcss.rule({
  selectors: [ ... ],
  nodes: someRule.nodes,
  source: someRule.source,
  semicolon: true,
});
```

```
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#before is deprecated. Use Node#raws.before
```

The Node constructor is attaching every passed properties to the instance, with no distinction between direct or raws ones:
https://github.com/postcss/postcss/blob/master/lib/node.es6#L36

The API docs are not of much help regarding which properties are accepted:
https://github.com/postcss/postcss/blob/master/docs/api.md#postcssruleprops

I wouldn't be against some enlightenment here :)

**Comment by ai** [comment]
```js
let newRule = postcss.rule({
  selectors: [ ... ],
  nodes: someRule.nodes,
  source: someRule.source,
  raws: { semicolon: true },
});
```

**Comment by ai** [comment]
It is same properties as mentioned in docs. You can see, that there is no `Rule#semicolon`, so you can’t pass it to constructor. But there is `Rule#raws` objet with `semicolon` property, which you can pass.

**Comment by pascalduez** [comment]
Hey @ai, thanks for the quick reply.

This fix the "semicolon" warning but not the "before" one, which is coming from the nodes appending: `nodes: someRule.nodes`.

**Comment by ai** [comment]
Can you open PostCSS `Node#befoe`, set `throw` and get stacktrace?

**Comment by pascalduez** [comment]
```
Node#before is deprecated. Use Node#raws.before
/[...]/postcss-quantity-queries/node_modules/postcss/lib/lazy-result.js:204
            throw error;
                  ^
Error: hey
    at Declaration.get (/[...]/postcss-quantity-queries/node_modules/postcss/lib/node.js:280:19)
    at /[...]/postcss-quantity-queries/dist/index.js:85:23
    at /[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:88:34
    at /[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:73:26
    at Rule.each (/[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:59:22)
    at Rule.walk (/[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:72:21)
    at Rule.walkDecls (/[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:86:25)
    at cleanIndent (/[...]/postcss-quantity-queries/dist/index.js:84:15)
    at processAtRule (/[...]/postcss-quantity-queries/dist/index.js:75:3)
    at /[...]/postcss-quantity-queries/node_modules/postcss/lib/container.js:141:34
```

**Comment by ai** [comment]
What is here `postcss-quantity-queries/dist/index.js:85:23`?

**Comment by pascalduez** [comment]
Nevermind, that's my code setting it...
