### ISSUE TITLE
AtRule#params or AtRule#raws.params?

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#560]
Very confused by this.

1. The documentation says [AtRule#params](https://github.com/postcss/postcss/blob/master/docs/api.md#atruleparams).
1. The deprecation warning says to use [AtRule#raw.params](https://github.com/postcss/postcss/blob/137024f2b8985fbb9db34510b71fe57a06401dae/lib/at-rule.js#L42).
1. The `Node` class has a `raws` property (plural, not `raw`).
1. The tests say [AtRule#params](https://github.com/postcss/postcss/blob/master/test/at-rule.es6#L12).
1. `postcss.parse('@a foo {}').first.params` yields `foo`. Everything else is undefined.

What is the desired approach; thus, which parts need to be fixed?

Also, the `Rule` has the same issue with `Rule#selector`. Perhaps there are others?

**Comment by ai** [comment]
Use `AtRule#params`.

Warning tells about `_params`, not `params`. `AtRule#raw.params` store origin parameters with comments and spaces. In other hand, `AtRule#params` was trimmed and cleaned from comments.

**Comment by jedmao** [comment]
@ai are you sure `AtRule#raw` has anything at all? Here's what I'm seeing:

```
> postcss.parse('@a foo /* bar */ {}').first.raw
[Function: raw]
```

If, however, I use `raws` (plural), I get this:

```
> postcss.parse('@a foo /* bar */ {}').first.raws
{ before: '', between: ' /* bar */ ', afterName: ' ', after: '' }
```

**Comment by ben-eb** [comment]
@jedmao The `raws` property was renamed from `raw` before 5.0 was released, so the deprecation warning has probably not been updated. :smile:

**Comment by jedmao** [comment]
That's what needs to be fixed then.

**Comment by jedmao** [comment]
Oops! I was referencing an old commit! My bad.

**Comment by ai** [comment]
@jedmao in `@a foo /* bar */ {}` comment is between params and `{`, so it is stored as `raws.between` :).

Try `@a foo /* comment */ bar {}`

**Comment by ai** [comment]
BTW, it is not really every day API. I think only strigifier and formatters developers should know about `Node#raws`.
