### ISSUE TITLE
error on nested at-rule without semicolon

### ISSUE THREAD

**Issue by mahtd** [postcss/postcss#561]
The following input results in a syntax error:

```
a { @import "b" }
```

Error:

```
     CssSyntaxError: <css input>:1:1: Unclosed block
  a { @import "b" }
  ^
      at Input.error (lib/input.es6:9:5992)
      at Parser.unclosedBlock (lib/parser.es6:1:40)
      at Parser.endFile (lib/parser.es6:1:40)
      at Parser.loop (lib/parser.es6:1:40)
      at Object.parse [as default] (lib/parse.es6:1:30)
```

**Comment by mahtd** [comment]
In [parser.es6:279](https://github.com/postcss/postcss/blob/master/lib/parser.es6#L279), the parser picks up the `}` as a param, so it looks like it needs to break when it sees a `}` instead

**Comment by ai** [comment]
All at-rules must have `;` at the end.

**Comment by OEvgeny** [comment]
@ai It is complicating scss styles compilation.

**Comment by ai** [comment]
@OEvgeny add issue in `postcss-scss` repo ;). It is not relevant with default parser.
