### ISSUE TITLE
stringifying cloned rule doesn't add semicolon to last at-rule

### ISSUE THREAD

**Issue by mahtd** [postcss/postcss#562]
This is related to #561, but for the stringifier. Stringifying a cloned rule with at-rules leaves the semicolon off the last at-rule. This produces CSS that the parser can't parse.

Input

```
var root = postcss.parse('a { @import "b"; @import "c"; }');
var rule = root.first;
var ruleCloned = rule.clone();

console.log('Rule:\n%s\n', rule.toString());
console.log('Cloned rule:\n%s\n', ruleCloned.toString());
```

Output:

```
Rule:
a { @import "b"; @import "c"; }

Cloned rule:
a {
    @import "b";
    @import "c"
}
```

**Comment by ai** [comment]
It is not a issue, but current `clone()` behaviour. It removes code style from cloning node, because I thought that code style is part of root.

We will fix this behaviour in 6.0.
