### ISSUE TITLE
Не удаляются комментарии.

### ISSUE THREAD

**Issue by GitScrum** [postcss/postcss#564]
Использую связку postcss-import и cssnano, ошибок нет но и результата удаления комментариев то же )
``` javascript
.pipe(postcss([
    require('postcss-import')(),
    require('postcss-mixins')(),
    require('postcss-nested')(),
    require('postcss-extend')(),
    require('cssnext')(),
    require('cssnano')({
        convertValues: {
            length: false
        },
        discardComments: {
            removeAll: true
        }
    })
]))
```

**Comment by ai** [comment]
Пиши в cssnano, ядро PostCSS тут не при чём.

Только обязательно укажи входные/выходные CSS и укажи работают ли другие плагины.

**Comment by azat-io** [comment]
@GitScrum Какая версия nano и postcss? Была такая же проблема.

**Comment by GitScrum** [comment]
@azat-io 
"postcss": "^4.1.16",
"cssnano": "^3.0.1",

**Comment by TrySound** [comment]
@GitScrum Обнови postcss. cssnano3.0 работает с postcss5

**Comment by GitScrum** [comment]
@TrySound не прокатило (

**Comment by azat-io** [comment]
@GitScrum У меня вот так всё работает:

"cssnext": "^1.8.4",
"gulp-postcss": "^6.0.0",
"postcss": "^5.0.5"

Вопрос был [тут](https://github.com/ben-eb/cssnano/issues/51).

**Comment by GitScrum** [comment]
@azat-io c postcss-import не работает ( [тыц](https://github.com/ben-eb/cssnano/issues/61)

**Comment by TrySound** [comment]
@GitScrum Вместо cssnext можно postcss-cssnext попробовать.
