### ISSUE TITLE
How to write a plugin

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss#565]
I'm currently trying to rewrite some old plugins using new guidelines.
I have some trouble, for example, what's the difference between:

```
postcss([plugin]).process(css).css;
```

and

```
postcss([plugin()]).process(css).css;
```

I expect no differences, but it's not the case. Is it intended?

**Comment by ben-eb** [comment]
Does this issue help? :smile:

https://github.com/postcss/postcss/issues/415

**Comment by ai** [comment]
`plugin` syntax is for option-less call. `plugin(opts)` for call with option.

The reason of this API because *a lot* of users forgot `()`. In Gulp if you forgot `()`, it will raise a error. But PostCSS hide this issue and “plugin just not works”.

**Comment by iamvdo** [comment]
@ben-eb Not really.

@ai 
>plugin syntax is for option-less call. plugin(opts) for call with option.

So why calling `plugin()` is different from `plugin`? It still seems odd to me. If Gulp raises an error, it's a Gulp problem, not PostCSS one. The PostCSS API for end-user should be simple. If I don't want to have options, I should be able to call without parenthesis. 
Plus, examples in docs never use parenthesis while in README there are parenthesis and this is confusing.

**Comment by ai** [comment]
@iamvdo we can’t raise a error on missed `()`, because in PostCSS initializer and plugin are both functions. Un gulp initializer is a function, but plugin is a `Transform` instance.

**Comment by iamvdo** [comment]
@ai Anyway, so examples in docs are still confusing to me.

**Comment by ai** [comment]
Do I fix a example? https://github.com/postcss/postcss/commit/dbdd456f27055b0dcd950b7e49058fce2f9d6b90

Where di you find `plugin()` ithout options?

**Comment by iamvdo** [comment]
https://github.com/postcss/postcss/blob/master/docs/api.md#postcssplugins
https://github.com/postcss/postcss/blob/master/docs/api.md#processor-class

**Comment by iamvdo** [comment]
In fact, it's the opposite, I find `plugin` without parenthesis. O_o This is why I'm confused because you say that parenthesis are mandatory.

https://github.com/postcss/postcss/blob/master/docs/api.md#postcssplugins
https://github.com/postcss/postcss/blob/master/docs/api.md#processor-class

**Comment by ai** [comment]
@iamvdo everything is fine in this examples. Without options, you use bracket-less version.

**Comment by iamvdo** [comment]
>Without options, you use bracket-less version.

OK, so it's my first question: why is there a difference between `plugin` and `plugin()`. I'm not talking about `plugin(opts)`.
