### ISSUE TITLE
Space handling regression in 5.0.6

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#576]
This build failed on 5.0.6:

https://travis-ci.org/ben-eb/perfectionist/jobs/81659108

However after locking the dependency to 5.0.5, all tests pass:

https://travis-ci.org/ben-eb/perfectionist/builds/81661098

**Comment by morishitter** [comment]
I have the same bug in CSSfmt. https://travis-ci.org/morishitter/cssfmt/jobs/81744843

I found, some decls have `decl.raw.value` but some decls don't have it.

```
{ before: '\n  ',
  between: ': ',
  value: { value: '12px', raw: '12px      ' } }
{ before: '\n  ', between: ': ' }
{ before: '\n  ',
  between: ': ',
  value: { value: 'red', raw: 'red     ' } }
{ before: '\n  ', between: ': ' }
{ before: '\n    ', between: ': ' }
{ before: '\n    ',
  between: ': ',
  value: { value: 'red', raw: 'red     ' } }
{ before: '\n    ', between: ': ' }
{ before: '\n      ',
  between: ': ',
  value: { value: 'red', raw: 'red     ' } }
```

**Comment by TrySound** [comment]
@morishitter decl.raw.value exists only if value ends with spaces (if there isn't importnant) or contains comments.

**Comment by morishitter** [comment]
@TrySound Thanks. Now, I could fix it :) https://github.com/morishitter/cssfmt/commit/be7c516af006910c5821c11dcb713328a4fca170

**Comment by ai** [comment]
@ben-eb @morishitter I need betetr data to fix it. What is input CSS. What is expected and real AST.

**Comment by TrySound** [comment]
@ai Everything is okay. Just my fix was unexpected, but it works.

**Comment by ben-eb** [comment]
Bug is that postcss favours the raw `decl.raws.value.raw` over `decl.value`. So a modified `decl.value` is not used, instead I have to do:

```js
if (rule.raws.value) {
  rule.raws.value.raw = rule.value;
}
```
