### ISSUE TITLE
Is there any flow to create Typescript type definitions ?

### ISSUE THREAD

**Issue by sotayamashita** [postcss/postcss#579]

**Comment by TrySound** [comment]
@sotayamashita Is this what you want?
https://github.com/postcss/postcss/tree/master/d.ts

**Comment by jedmao** [comment]
@sotayamashita I have a [TypeScript branch](https://github.com/jedmao/postcss/tree/typescript) of PostCSS, which is a port of PostCSS into TypeScript. What I do is read the PostCSS commit history, synchronize those changes with my TypeScript branch and do a `gulp build` to generate the definition files after I ensure tests are passing. It's kind of a lot of work, but I can sleep soundly, knowing that the definitions were generated from test-passing code; thus, they must be correct.

**Comment by sotayamashita** [comment]
@jedmao Thank you for your kindness. I will fork your repo.

**Comment by jedmao** [comment]
@sotayamashita I'm just curious, what do you plan on doing other than what's already been done?

**Comment by sotayamashita** [comment]
@jedmao I just want to know its flow and try to use [closure-ts](https://github.com/teppeis/closure-ts) on PostCSS.
