### ISSUE TITLE
Plugin to scan SCSS for features used?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss#592]
Via [Twitter](https://twitter.com/iDGS/status/651024844641955840):

> Is there a *DO*-I-use style utility to scan existing SCSS for employed features, to help with conversions?

It would be really great if someone from the community could take this project and make it their own. I have enough on my plate already and I don't have an in-depth knowledge of the SCSS spec, in order so that I could implement this properly.

**Comment by ai** [comment]
Is it about [doiuse](https://github.com/anandthakker/doiuse)?

**Comment by ben-eb** [comment]
@ai It's about seeing which Sass features are being used in the SCSS source code. For example you could be using `@for` or `@each` and it would lint those.
