### ISSUE TITLE
Run synchronously

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss#595]
Hi!
Can I run `postcss` synchronously?
Something like:
```js
var result = postcss(plugins).processSync(css);
```

**Comment by ai** [comment]
```js
postcss(plugins).process(css).css
```

**Comment by ai** [comment]
`Processor#process` returns `LazyResult` object with `then` method to async and `css`/`map` methods to sync access.

**Comment by Semigradsky** [comment]
Wow! :zap:  Thanks
