### ISSUE TITLE
Process inline CSS in HTML using PostCSS

### ISSUE THREAD

**Issue by pensierinmusica** [postcss/postcss#596]
Shall we mention this library in the `README`?

https://github.com/RebelMail/html-postcss

I needed exactly this feature for a [Polymer](https://www.polymer-project.org/) project I'm working on, since the Polymer team recently [deprecated external stylesheets](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules). Otherwise it'd be impossible to use a CSS preprocessor.

Thoughts? Cheers!

**Comment by ai** [comment]
Yeap, send PR

**Comment by pensierinmusica** [comment]
Done :)
