### ISSUE TITLE
API to parse values

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#599]
Would you consider adding a value parser, I believe this will give plugin authors more power over CSS manipulation. 

For example:

```css
body {
  padding: 1em 5rem;
}
``` 
gives
```js
{ raws:
   { before: '  ',
     between: ': ',
     value: {
         value: '1em 5rem', raw: '1em 5rem', 
         values:[
            {before:'', after:' ', type:'length', value:'1', unit:'em'},
            {before:'', after:'', type:'length', value:'5', unit:'rem'}
         ]
      }
   }
}
```

Thanks!

**Comment by ben-eb** [comment]
https://github.com/TrySound/postcss-value-parser :smile:

**Comment by ai** [comment]
Yeap, on-demand value parser seems like good idea right now in terms of perfomance and API simplicity.

**Comment by MohammadYounes** [comment]
Awesome! Thanks for the link :+1:
