### ISSUE TITLE
Previous sourcemap

### ISSUE THREAD

**Issue by sebakerckhof** [postcss/postcss#605]
Hello,

I'm looking to add autoprefixing to the build system of Meteor, but I fail to get sourcemaps to work correctly.

Our files are kept in memory and do not always have real filepaths.
A typical build is:
1. Compile individual sass/less/stylus/... files with a preprocessor to css files
2. Merge all css files
3. Autoprefix.

At the end of step 2 we have a valid sourcemap. Now I'm looking to add step 3 with postcss.

If I try something like:
```js
 postcss([ autoprefixer ])
    .process(merged_css.code, {
      prev:  merged_css.map,
      map: { inline: false }
    })
    .then(function (result) {
      console.log(result.map);
    });
```
The resulting source map seems to only include the merged_css.code and nothing from the previous source map I specify.

**Comment by TrySound** [comment]
@sebakerckhof 
```js
{
  map: {
    inline: false,
    prev:  merged_css.map
  }
}
```
