### ISSUE TITLE
Version of the source-map dependecy

### ISSUE THREAD

**Issue by gustavohenrique** [postcss/postcss#609]
Hi!
I'm trying to use the gulp-postcss but I'm having an error about the source-map lib that is a dependency of postcss: Error: Cannot find module './lib/source-map-generator'
I think this error is because the postcss is using the source-map v0.5.1 and the latest version is v0.5.2. Is possible to update the source-map version in the package.json? If you prefer, I can send a pull request.
Thanks!

**Comment by ai** [comment]
Module `./lib/source-map-generator` is not in `source-map` but in PostCSS itself. So seems like you have broken `require`.
