### ISSUE TITLE
FixedCSS

### ISSUE THREAD

**Issue by ai** [postcss/postcss#610]
CSSWG posted their [mistakes in CSS specs](https://wiki.csswg.org/ideas/mistakes).

I think it will be fun to make a plugin with props name fixes, etc.

**Comment by jonathantneal** [comment]
I’m free today, so I’ll see about it. postcss-unmistakable?

**Comment by ai** [comment]
Awesome! I am OK with `postcss-unmistakable`, but shorter thing will be better. `postcss-fixedcss`?

**Comment by ai** [comment]
Project was started https://github.com/jonathantneal/postcss-time-machine
