### ISSUE TITLE
postcss silently failing if there is an invalid comment syntax on non last rule

### ISSUE THREAD

**Issue by jithin1987** [postcss/postcss#620]
This fails silently. File is just ignored no error or whatsoever to figure out what is happening. I am running via grunt-postcss

```
.rule  {
  position: relative;
  color: red !important; //FIXME
  top: 10px;
}
```

Working rule 
```
.rule {
  position: relative;
  top: 10px;
  color: red !important; //FIXME
}
```

If postcss has a problem with comment syntax, then it should fail consistently and provide error.

**Comment by ben-eb** [comment]
Single line comments are not valid CSS, which is why they are unrecognised by the default parser. If you want to process them, load https://github.com/postcss/postcss-scss.

https://github.com/nDmitry/grunt-postcss#optionssyntax-optionsparser-optionsstringifier

**Comment by jithin1987** [comment]
@ben-eb It's true that the CSS syntax is invalid, but postcss should have failed consistently in both cases. Also its silently ignoring error, leaving it up to the user of postcss to figure out why not all files are processed. It should have thrown error and failed the task.

**Comment by jithin1987** [comment]
`grunt-postcss 0.7.1` fixes this issue. Thanks everyone.

**Comment by keithjgrant** [comment]
Does this mean PostCSS should throw an error upon finding an invalid comment (`//`)? Because I’m seeing these silently breaking my CSS, and I really wish I could get it to log an error.

**Comment by ai** [comment]
@keithjgrant yeap, PostCSS throws. But maybe your `gulp-postcss` or some other tools in environment hide it.
