### ISSUE TITLE
Add npm shrinkwrap

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss#622]
> This command locks down the versions of a package's dependencies so that you can control exactly which versions of each dependency will be used when your package is installed. The package.json file is still required if you want to use npm install.

https://docs.npmjs.com/cli/shrinkwrap

**Comment by ai** [comment]
Let's wait few weeks until npm@3 become more popular, because shrinkwrap is too big on npm@2.

**Comment by ben-eb** [comment]
:-1:

https://github.com/postcss/postcss/issues/312

**Comment by TrySound** [comment]
:-1: Just complicating
