### ISSUE TITLE
Specify previous source map after parse

### ISSUE THREAD

**Issue by papandreou** [postcss/postcss#623]
I originally asked on the gitter channel on October 30th: https://gitter.im/postcss/postcss/archives/2015/10/30

I tried a couple of things, but I haven't managed to get it to work.

Here's my latest attempt in the form of a failing test (the first one succeeds, the last one fails): https://github.com/papandreou/postcss/commit/11bab9023718f4bd1622044463bae163f5ebd511

Think of this as a support request -- or consider introducing an "officially" supported way to specify the previous map after parsing.

**Comment by papandreou** [comment]
Found a hack that seems to do the job: https://github.com/postcss/postcss/commit/d9eaf41528cdadeb684eafa2b5660e54f758372e

I'm taking the liberty of keeping this issue around as a feature request, though :)

**Comment by ai** [comment]
Sorry, I forget about this issue :)

**Comment by ai** [comment]
Nope, main problem is wrong usage of PreviousMap.

You can miss `PreviousMap#text`, because you should create second class and override `consumer()` logic.

**Comment by papandreou** [comment]
If I wanted to do that, I would need to have `mozilla.SourceMapConsumer` available in my code, wouldn't I?

**Comment by ai** [comment]
Yeap. Do you have any worries about it?

**Comment by papandreou** [comment]
Only in the sense that it adds another dependency to my app and I need to keep it in sync with the version that postcss depends on.

**Comment by ai** [comment]
Just use same wild requirements as in PostCSS

**Comment by ai** [comment]
Seems like this issue become outdated :)
