### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by ivoputzer** [postcss/postcss#634]
It looks like that under certain circumstances Promise is not defined when using this library. Any suggestions on how this could be solved?

**Comment by ben-eb** [comment]
You can either upgrade from node 0.10 or polyfill the Promise API before you run PostCSS.

More information here: https://github.com/postcss/postcss/issues/311

**Comment by ivoputzer** [comment]
Unfortunately I'm not using postcss directly; see the other issue [here](https://github.com/sindresorhus/gulp-autoprefixer/issues/49)

However I'm running `v0.10.40`, Promises are yet not part of the API; They should have been implemented from `v0.12` onwards!

**Comment by ben-eb** [comment]
It's fine, just load the polyfill before you call gulp-autoprefixer. From the usage section:

>If you want to run PostCSS on node.js 0.10, add Promise polyfill:
>
>```js
>require('es6-promise').polyfill();
>var postcss = require('postcss');
>```

https://github.com/postcss/postcss#usage

**Comment by ivoputzer** [comment]
thanks @ben-eb! i already submitted a pr to the guys of `gulp-autoprefix` ;)
