### ISSUE TITLE
How to add custom data in the return value

### ISSUE THREAD

**Issue by markqin** [postcss/postcss#635]
I hope not only to get the css:
```
result.css
```
but also to get the custom values in the result object , just like:
```
result.customData
```
but I do not know how to do, please tell me...
thank you very much!!!!!!

**Comment by ben-eb** [comment]
What do you mean by custom values?

**Comment by ai** [comment]
@markqin if you want to return some special data from you plugin (like for plugin communication) you should use `result.messages`.

```js
result.messages.push({
  type: 'my-plugin#type',
  a: 1,
  b: 2
});
```
