### ISSUE TITLE
Node v4.2.2 but Promise is not defined

### ISSUE THREAD

**Issue by roydukkey** [postcss/postcss#643]
I've seen a lot on this issue. All resolutions point to upgrading node or using a polyfill (which I'm not content on using). So, I've upgraded node, but the issue persist. Here is a screenshot of my setup.

![autoprefixer](https://cloud.githubusercontent.com/assets/1509616/11312643/882273de-8fa5-11e5-83ed-6c152683ff0b.png)

**Comment by TrySound** [comment]
@roydukkey Try to run from cmd, not from visual studio.

**Comment by roydukkey** [comment]
It seems Visual Studio includes its own version of gulp....... Referencing all `$(DevEnvDir)` external tools last allows VS to pick up the correct version of gulp.

![image](https://cloud.githubusercontent.com/assets/1509616/11315443/d0ef868c-8fbf-11e5-99aa-4e071ea0f5b1.png)

**Comment by matijs** [comment]
Unticking `$(DevEnvDir)\Extensions\Microsoft\Web Tools\External` did the trick for me. It also allowed me to only have Gulp installed locally.
