### ISSUE TITLE
Q: Should plugins have PostCSS in dependencies?

### ISSUE THREAD

**Issue by OEvgeny** [postcss/postcss#644]
I got some issues related to this question (see [this](https://github.com/OEvgeny/postcss-atroot/issues/3)). In short, I think plugins should have PostCSS in `peerDependencies` and `devDependencies` if it's needed. Didn't find information about it in docs. Quick check shows me that every plugin does it in its own way :)

What is your poin?..

**Comment by TrySound** [comment]
@OEvgeny Just look at existing plugins. Plugins defines with `postcss.plugin` function. So, postcss should be in usual deps to have ability to use this function. Also `peerDependencies` are deprecated for a long time. So, never use it.

**Comment by OEvgeny** [comment]
Ok. thanks. Didn't know about `peerDependencies` deprecation.
I check plugins and some of them didn't have PostCSS in deps (eg [`postcss-host`](https://github.com/vitkarpov/postcss-host/blob/master/package.json)).

So, I think will be good to add this info into plugin guidlines..

**Comment by TrySound** [comment]
@OEvgeny That's the same mistake. Better check plugins which in postcss org.

**Comment by TrySound** [comment]
@OEvgeny The rule: everything u require in module code (not test and build code) you should place in regular dependencies

**Comment by OEvgeny** [comment]
@TrySound I know. But it also means that with `npm@<3` it will install PostCSS for each plugin in plugins directory. Of course with `npm@^3` it works good.

**Comment by TrySound** [comment]
@OEvgeny You still can install postcss as dep, but not use it. I did such thing before move to npm2
https://github.com/TrySound/case/blob/master/package.json

**Comment by Guria** [comment]
@TrySound You're wrong. `peerDependencies` wasn't deprecated:
https://docs.npmjs.com/files/package.json#peerdependencies
https://github.com/npm/npm/issues/6565#issuecomment-74971689

**Comment by ai** [comment]
Let’s I clear this thing.

Every PostCSS plugin should be created by `postcss.plugin()`. This method is in `postcss`, so every plugin must have `postcss` in `dependencies`.

The reasons:

1. Many major releases do not change plugin API. This is why default `peerDependencies` mechanism is not ideal for us. We use different: every plugin contains `plugin.postcssVersion` with its PostCSS version. If plugin throw a error and its version is different, we show a message, thet problem is in PostCSScore conflict. Also using `plugin.postcssVersion` we can even change AST API for older plugins.
2. Also in real word plugins are quite more compilcated, than just a function. Plugin builder is useful thing.
3. Many plugins anyway use `postcss` for AST transformations methods like `postcss.rule()`.

Of course, every reason can be solved in many different ways. But in general we found that this solution is better for PostCSS purpose.

Maybe in PostCSS 6 we will have some tiny `postcss-plugin` creator. But only if PostCSS was popular in CSS-in-JS world.

**Comment by OEvgeny** [comment]
@ai Thanks for clarification.
