### ISSUE TITLE
postcss-hacks

### ISSUE THREAD

**Issue by ai** [postcss/postcss#645]
We need some hacks collection for PostCSS. For example, many developers use `compass` for `sticky-footer` and other things.

Also this plugin will save us from many tiny plugins with unknown properties. I think adding a special property for some small case is not a best way for PostCSS plugin, because other developer will not understand what is the source of this property.

Suggested API:

```css
.footer {
  @hack sticky-footer 50px;
}
```

Suggested hacks (please suggest your one):

* [Sticky footer](https://github.com/ai/evil-front/blob/master/evil-front/lib/assets/stylesheets/evil-front/sticky-footer.sass)
* padding’s [responsive aspect ratio](http://www.goldenapplewebdesign.com/responsive-aspect-ratios-with-pure-css/)
* clearfix?

@jonathantneal @ben-eb @TrySound @jedmao

**Comment by ben-eb** [comment]
Yeah, this seems like a much better solution than using mixins. :+1:

**Comment by davidtheclark** [comment]
I made one of these in SCSS a little while ago: http://davidtheclark.github.io/scut/ Some of those are just shortcuts, but a bunch would qualify as hacks like this.

**Comment by davidtheclark** [comment]
Hacks in there:
- HiDPI breakpoint
- hide visually
- image replacement
- triangle
- center absolutely
- center block
- center transform
- clearfix
- ratio-box
- sticky-footer, fixed height
- sticky-footer, fluid height
- vertical center, inline-block method
- vertical center, table display method
- vertical center, transform method
- hanging indent
- indented paragraphs
- truncate

**Comment by ai** [comment]
BTW, do need definition for hacks. Because this question may bring a strong holy war to project in future. Maybe different name?

**Comment by TrySound** [comment]
@ai They are not hacks, they are features :)

**Comment by sotayamashita** [comment]
Is it kind of hack ? https://github.com/AllThingsSmitty/css-protips

**Comment by oyeanuj** [comment]
@davidtheclark Did any of the things in your `scut` utility make it as a plugin?

**Comment by davidtheclark** [comment]
I didn't build any. But feel free to checkout the PostCSS plugin list and possibly build your own.

**Comment by yisibl** [comment]
In Houdini CSS we can do this

```js
registerLayout('masonry', class {
    static get inputProperties() {
        return ['width', 'height']
    }
    static get childrenInputProperties() {
        return ['x', 'y', 'position']
    }
    layout(children, constraintSpace, styleMap, breakToken) {
        // Layout logic goes here.
    }
}
```

```css
body {
  display: layout('masonry');
}
```

https://www.smashingmagazine.com/author/philipwalton/

**Comment by marcustisater** [comment]
I'm moving this discussion over to our new [suggestion box](https://github.com/postcss/postcss-plugin-suggestion-box).
