### ISSUE TITLE
Post-css z-index plugin

### ISSUE THREAD

**Issue by ottomen** [postcss/postcss#646]
Hi!

I found that this plugin is only disturb me as developer, forcing creation of unnecessary automatic dependencies. 
Instead of building clean z-index structure what i needed, i'm messing now with this automatic calculations.

How can i remove this plugin?

**Comment by ai** [comment]
Just remove it from PostCSS plugins list.

PostCSS do not have any plugins by default. You add any plugins that you want manually. So if you didn’t want some plugin, just do not add it.
