### ISSUE TITLE
AST Vizualizer

### ISSUE THREAD

**Issue by ai** [postcss/postcss#649]
You input CSS on left and get AST structure on the right.

**Comment by davidtheclark** [comment]
I saw something that does this recently: https://sneakertack.github.io/postcss-playground/

**Comment by ai** [comment]
@seaneking you hide so awesome tool from us?! :D

I just want to show classes info in AST tree, because it is not just AST.

**Comment by TrySound** [comment]
@ai @sneakertack :)
