### ISSUE TITLE
Replace repetitive word in decl

### ISSUE THREAD

**Issue by HoBi** [postcss/postcss#653]
In https://github.com/HoBi/postcss-czech-stylesheets/issues/4 I tried to replace repetetive word `transparent` but it replace only the 1st occurrence.

In JSFiddle it worked (for example http://jsfiddle.net/5xnq16ff), but if I use it with PostCSS it does not.

Any idea how to do it or is it some crazy bug? :smirk_cat:

**Comment by TrySound** [comment]
@HoBi Your code extends String prototype. It's very very bad practice to extend global objects. And you problem is there I think.
Try to use [postcss-value-parser](https://github.com/TrySound/postcss-value-parser) to remove difficult regexp

**Comment by HoBi** [comment]
@TrySound I do not want to use the value parser plugin, it is to masive. *The extend of the String prototype was just for a test, I wanted to use code as is in JSFiddle example.*

I just want to get decl value as a string and replace all occurrences, not only the first one.

`decl.value = decl.value.replace(new RegExp(_what_, "g"), _with_);`

This should work (it works here http://jsfiddle.net/5xnq16ff), isn't it?

**Comment by TrySound** [comment]
@HoBi It's not massive at all. I made it as small as it possible. Also regexps are less efficient. value-parser let you just compare strings and reassign value

**Comment by TrySound** [comment]
@HoBi btw, regexp is much more massive parser :)

**Comment by TrySound** [comment]
@HoBi And it's not plugin, it's a parser.

**Comment by TrySound** [comment]
@HoBi And it's not plugin, it's a parser.

**Comment by ai** [comment]
Have no idea :-)
