### ISSUE TITLE
New docs

### ISSUE THREAD

**Issue by ai** [postcss/postcss#656]
Guys, I made new `README.md`. More clear wiith few highlighted plugins, instead of long unreadable list.

https://github.com/postcss/postcss/blob/master/README.new.md

@davidtheclark @jonathantneal @ben-eb I need your feedback and grammar check, please

**Comment by himynameisdave** [comment]
@ai in the first blurb under "plugins" it reads...
> *Here is out favorites*

...when I believe it should say *here is* ***our*** *favorites*.

**Comment by himynameisdave** [comment]
@ai also, no link to [`postcss-plugins`](https://github.com/himynameisdave/postcss-plugins) in the readme eh? Thats cool I'm just curious what the plan is to show all the plugins. Are you going to make use of that plugin list to generate [this file that does not yet exist](https://github.com/postcss/postcss/blob/master/docs/plugins.md)?

**Comment by ai** [comment]
@himynameisdave I have a link to `postcss.parts`. I really think that we really should use `npmsearch.com` on `postcss.parts`, because  local database:

1. Has no popularity.
2. Miss plugins, because author can misss add plugin to it. Anyway using `postcss-plugin` keyword is a better solution.

**Comment by himynameisdave** [comment]
'aight whatever's clever man. I'm still going to be maintaining `postcss-plugins` though :smile: let me know if I can be of any help!

**Comment by davidtheclark** [comment]
I offered some feedback in https://github.com/postcss/postcss/pull/733
