### ISSUE TITLE
Node#replaceWith BUG

### ISSUE THREAD

**Issue by markqin** [postcss/postcss#668]
```javascript
var newNode = postcss.parse('a{ _background-image: url(a.png);}');
oldNode.replaceWith(newNode);
```
I got this code:
```javascript
a {
	background-image: url(a.png);
}
```
"_" is a IE7 hack, I need it, how to get the original code? 

Thanks!!!

**Comment by ai** [comment]
Sorry, it is not a bug, but API.

You need to care about this cases by hands. Just copy `newNode.raws.before = oldNode.raws.before` after the replacement.

BTW, do not forget also to copy `newNode.source = oldNode.source`  to generate correct source maps.
