### ISSUE TITLE
Cache api

### ISSUE THREAD

**Issue by glebmachine** [postcss/postcss#672]
Hi guys!

I have some idea, for better perfomance in postcss plugins
What about to provide cache api for plugins, to store data between postcss launches.

For example:
```js
module.exports = postcss.plugin('postcss-pluginname', function(opts, pluginapi) {
  
  //  -- set data
  // scalar
  pluginapi.cache.setItem('fileChecksum', '7815696ecbf1c96e6894b779456d330e');
  // array or hash
  pluginapi.cache.setItem('fileChecksums', {
    file1 : '7815696ecbf1c96e6894b779456d330e',
    file2 : '7815696ecbf1c96e6894b779456d330e',
    file3 : '7815696ecbf1c96e6894b779456d330e'
  });
  
  //  -- get update or delete
  // scalar
  pluginapi.cache.removeItem('fileChecksum')
  // array or hash
  delete pluginapi.cache.getItem('fileChecksums').file1;
  pluginapi.cache.getItem('fileChecksums').file2 = '293c747dd5f833b0b0cd002bb0bdf155';
}
```

This `cache` api will keep all cached data in `.postcss-cache` folder as `json` file for each plugin.
This feature can be optional, and turned off by `default`. Also in future, `pluginapi` object can be extended by other features.

In my case (https://github.com/glebmachine/postcss-easysprites), i have to recompile all sprites on nodejs start and won't to make file caching on plugin level.

If you ok, i will code it)

**Comment by TrySound** [comment]
@glebmachine Seems like an idea for some external module, but not part of postcss. Why not just use custom cache? You can define it in postcss.plugin function scope and it will be saved in all launches.

**Comment by ai** [comment]
Yeap, nice idea. But we should do it by separated library to keep core small and focused.
