### ISSUE TITLE
PostCSS Seems to not run on webpack

### ISSUE THREAD

**Issue by DPr00f** [postcss/postcss#678]
Hi guys, I have the following css:
```
:root {
  --blue: #056ef0;
}

body {
  background: var(--blue);
}
```

And my webpack configuration is as such:
```
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var webpack           = require("webpack");
var PROD              = process.env.NODE_ENV === 'production';
var customProperties  = require("postcss-custom-properties");

var plugins = [ new ExtractTextPlugin('app.css') ];
if(PROD) {
  plugins.push(new webpack.optimize.UglifyJsPlugin({minimize: true}));
}

module.exports = {
  entry: './src/js/main.js',
  output: {
    path: './dist',
    filename: 'bundle.js'
  },
  devServer: {
    inline: true,
    port: 3000
  },
  resolve: {
    modulesDirectories: ['node_modules', './src'],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: '/node_modules/',
        loader: 'babel',
        query: {
          presets: ['es2015', 'react']
        }
      },
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader') },
      { test: /\.(png|jpg)$/, loader: 'file-loader?name=images/[name].[ext]' },
      { test: /\.woff$/, loader: 'file-loader?name=fonts/[name].[ext]' }
    ]
  },
  postcss: [ customProperties() ],
  plugins: plugins
};
```

When I build or run the webpack-dev-server the background is white because it never gets compiled.

I've been trying to set this up for a while now and can't seem to find a solution, is almost like it's running a different set of postcss plugins, I can use @import in my code and I didn't set it up. :\
Am I missing something?

**Comment by ai** [comment]
Put `css-loader` before `postcss-loader`.

Anyway it is a question for a chat, not a issue inside a PostCSS core.

**Comment by DPr00f** [comment]
Thanks, I know it wasn't the best way to contact. Sorry for that.

**Comment by saleo3** [comment]
Did you solve it? because I had the same issue and I fixed doing this:
`ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')`

and by the way you can omit the `-loader` like this:
`ExtractTextPlugin.extract('style', 'css!postcss')`
