### ISSUE TITLE
Use ava as a test runner

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss#684]
I'm working on [converting all tests to ava](https://twitter.com/andreysitnik/status/679739628144967680), but I'm running into [this ava issue](https://github.com/sindresorhus/ava/issues/358).

I currently can't run any ava tests because of Babel 6, and while this issue is resolved, I need to wait for the next ava release so the fix gets included in [gulp-ava](https://github.com/sindresorhus/gulp-ava).

Posting here so nobody does duplicate work, if somebody knows a (temporary) workaround please let me know!

**Comment by ben-eb** [comment]
You can install from github to work around this:

```json
"ava": "sindresorhus/ava#945dbea40a6a500a24d54ebcc7e10dcd75647fc7"
```

(closing as not an issue with PostCSS :wink:)

**Comment by ai** [comment]
Issues as TODO is OK. Anyway we have a lot of them :-).
