### ISSUE TITLE
Using Variables for Decl Values

### ISSUE THREAD

**Issue by moshemo** [postcss/postcss#691]
Perhaps this is obvious, but I'm not a very proficient javascript programmer.

To understand what I want to do, please take a look at the following code:

    button {
         button: button;
         button-border: 3px solid #abcde1;
    }

Here is what I would like to do.  

If button-border is NOT set, then I would like there to be a default value of border: none;
However, if button-border is set, then I would like to use the value set in button-border -- border: 3px solid #abcde1; in the example above.

I thought I would do that by setting a variable, but I think I'm having problems with scope.  Here is the code that I have tried:

           css.walkDecls(decl => {                  
                 var buttonBorder = 'none',
          		button = [
                             'cursor: pointer;',
                             'display: inline-block;',
                             'min-height: 1em;',
                             'outline: none;',
                             'border:' + buttonBorder
                        ],
              joinButton = button.join('');
			if (decl.prop === 'button-border') {
                             var buttonBorder = decl.value;
                              decl.remove();
        	       }
          
             if (decl.prop === 'button') {
                             decl.replaceWith(joinButton);
            }  
        });

Any idea of what I am doing wrong and how I can do it right?

Thanks,

Moshe

**Comment by ai** [comment]
You can remove previous `border` on `button-border`:

```js
css.walkDecls('button', decl => {
    decl.replaceWith('cursor: pointer; display: inline-block; min-height: 1em; outline: none; border: none');
});
css.walkDecls('button-border', decl => {
    decl.prop = 'border';
    let prev = decl;
    while ( prev = prev.prev() ) {
        if ( prev.type === 'decl' && prev.prop === 'border'  ) {
            prev.remove();
            break;
        }
    }
});
```

**Comment by ai** [comment]
BTW, adding a custom `border` property is not good API design. Because other developers may think that it is some W3C property. I think mixins from `postcss-mixins` is a better solution.

If you try to make some controls library, custom at-rule will be better:

```css
button {
    @super-library button {
        border: 1px solid blue;
    }
}
```

**Comment by moshemo** [comment]
Thanks, that did it.  Much appreciated.

I will also consider looking at the at-rule option, thanks again.
