### ISSUE TITLE
How to set up postcss with babel

### ISSUE THREAD

**Issue by moshemo** [postcss/postcss#692]
I am wondering how to set up postcss with babel.  I tried gulp-babel, but it didn't seem to work.  

Gulp-babel is expecting a .js file -- and I am feeding a .css file into the pipe.  

In short, any idea or pointers on how to get this to work?

Thanks.

**Comment by ai** [comment]
@moshemo why you need to set up Babel and PostCSS? Because CSS is not JS, so it doesn’t need a Babel.

**Comment by moshemo** [comment]
I thought it would be nice to use es6 in the postcss plugin that I'm writing.

**Comment by TrySound** [comment]
See examples in projects written in es2015.
@moshemo https://github.com/ben-eb/postcss-colormin/blob/master/package.json#L10-L13

**Comment by ai** [comment]
PostCSS plugin files has JS extension, so you can use normal way to run it. For example, you can rename `gulpfile.is` to `full-time.babel.js` and all required files (including your PostCSS plugins) will be processed throw Babel.

**Comment by moshemo** [comment]
Thanks.  I'll see if I can get it working.
