### ISSUE TITLE
Plugin API Examples in AST Explorer

### ISSUE THREAD

**Issue by moshemo** [postcss/postcss#695]
I very much like the AST Explorer as it helps me to understand how the plugin API works.  However, the link provided for in the readme section only provides one example.  It would be really helpful if there was a link available for the AST Explorer that provide a number of examples of different elements of the api (cloneBefore, atrule, etc).

I have also looked for video tutorials on how to make a postcss plugin, but found only one: https://www.youtube.com/watch?v=-_gIKdHYP3E.  A few short video tutorials on the plugin api would also be extremely helpful.

Just a couple of suggestions on how to help people like myself better understand how to use the plugin api.

Thanks and be well,

Moshe

**Comment by ai** [comment]
PR is welcome :)
