### ISSUE TITLE
Adding Pseudo Classes

### ISSUE THREAD

**Issue by moshemo** [postcss/postcss#696]
Hello,

I am trying to figure out how I can add some pseudo classes.  In particular, I want to be able to add pseudo classes to the selector when a particular prop is being used.

For example:  

    selector {
       prop: value;
    }

I would like that to output as follows:

     selector {
         newProp:  newValue;
     }
    
     selector:hover {
         hoverProp: hoverValue;
         }

      selector:before {
          beforeProp: beforeValue;
       }

And so on.

How can I do that?

Thanks,

Moshe

**Comment by TrySound** [comment]
@moshemo First of all read api documentation. If you had some problems with understanding you can ask in our gitter channel. But you should ask more specific questions. Also read plugins code.

**Comment by moshemo** [comment]
@TrySound  I have been reading the api documentation, but am having trouble.  I'll check out the gitter channel.  Thanks.

**Comment by ai** [comment]
```js
css.walkRules(rule => {
    if ( checkSelector(rule.selectors) ) {
        let hover = postcss.rule({
            source: rule.source,
            selectors: rule.selectors.map(i => i + ':hover')
        });
        hover.apppend({ prop: 'hoverProp', value: 'hoverValue' });
        let before = postcss.rule({
            source: rule.source,
            selectors: rule.selectors.map(i => i + ':before')
        });
        before.apppend({ prop: 'beforeProp', value: 'beforeValue' });
        rule.parent.insertAfter(rule, hover);
        rule.parent.insertAfter(rule, before);
    }
})
```
