### ISSUE TITLE
FYI: the babel register require hook is outdated in index.js

### ISSUE THREAD

**Issue by LeonFedotov** [postcss/postcss#697]
Hi so I think this is the right thing to do
https://babeljs.io/docs/usage/require/

**Comment by ai** [comment]
I test other way to work with Babel in SugarSS parser. Maybe I remove hook completly.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss/commit/193e5ae897abb8e7d0c19b5a5312e57d5cbf002e

**Comment by LeonFedotov** [comment]
Cool :+1:
