### ISSUE TITLE
use a stream for postcss.parse(css)

### ISSUE THREAD

**Issue by thisconnect** [postcss/postcss#698]
https://github.com/postcss/postcss/blob/master/docs/api.md#postcssparsecss-opts

> - css (string|#toString): String with input CSS or any object with toString() method, **like file stream**.

Should `postcss.parse` to be able to work with stream, i.e. `fs.ReadStream`, or does "like file stream" mean it accepts a Buffer?

Are there any examples or tests for this?

**Comment by ai** [comment]
Yeap, it is a wrong docs. A buffer should be here.

Do you want to send PR?
