### ISSUE TITLE
ReferenceError: Promise is not defined - at LazyResult.async

### ISSUE THREAD

**Issue by tnga** [postcss/postcss#708]
using gulp-autoprefixer with my gulp task, assuming that it use postcss like module dependency,  i get this error on console:
```sh
node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/tngarsel/my_github/lib.iui/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/tngarsel/my_github/lib.iui/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21) 
...
```
here are some extras information:
*nodejs*: `version 0.10.45`
*npm*: `version 1.3.10` 
*gulp-autoprefixer*: `version 3.1.0` 
*postcss*: `version 5.0.14`

**Comment by ai** [comment]
README contains instructions how to add Promise polyfill. Also you should update node.js. Latest version is even 5.5.

**Comment by tnga** [comment]
For node.js, i use to install it via the software manager on my linux distro; but i am surprise when get current update to `0.10.45` when it's officially `4.2.5` for *LTS* and `5.5.0` for latest stable version on official node.js website.

However thank for your help about Promise polyfill.
