### ISSUE TITLE
Correct way to .append() and maintain code style?

### ISSUE THREAD

**Issue by tivac** [postcss/postcss#715]
I ran into #184 and wasn't able to figure out the right solution. I'm combining multiple results together into a single stylesheet using `.append()`, but it's stripping off any * hacks. Is there a more appropriate way to combine parsed CSS that I then want to further process? I could combine them all as strings but that seems really wasteful since I want to do further processing on it.

Here's a simple repro of what I'm doing:

```js
"use strict";

var postcss   = require("postcss"),
    processor = postcss(),
    root      = postcss.root(),
    result;

result = processor.process(".fooga { color: red; *color: black; }");

root.append(result.root);

console.log(root.toResult().css);
```

which outputs

```
> node ./test.js
.fooga {
    color: red;
    color: black
}
```

This came up in https://github.com/tivac/modular-css/issues/76

**Comment by ai** [comment]
First, you can make this code faster:

```js
result = processor.process(".fooga { color: red; *color: black; }");
root.append(result.root);
```

by replaceing `process` to `parse`:

```js
root2 = postcss.parse(".fooga { color: red; *color: black; }");
root.append(root2);
```

**Comment by ai** [comment]
Yeap, unfortunately `append` and other insert methods clean “raw” properties like indent or `*`.

I know, it is a bug and we will fix it in 6.0. Sorry, it will break plugins API so we need time to wait.

**Comment by ai** [comment]
Here is a temporary solution:

```js
for ( let i of root2.nodes ) {
    i.parent = undefined;
    root.append(i);
}
```

PostCSS will [clone](https://github.com/postcss/postcss/blob/master/lib/container.es6#L307) node only if it has different parent. So if we will remove parent, PostCSS will ignore cloning step. Raw properties are cleaned in `clone()`.

Sorry for this mess, it is hard to make API without any mistake =^_^=.

**Comment by tivac** [comment]
Thanks, I'll give that a shot!

PostCSS is great, no need to apologize :+1:

**Comment by pygy** [comment]
So even _you_ trip on the way you handle the hacks ;-)

I still think that they should be treated as vendor prefixes, and left in the property name...
