### ISSUE TITLE
Client side postcss (browsers)

### ISSUE THREAD

**Issue by acterhd** [postcss/postcss#724]
Hello. Can I use postcss in web browser, directly? 
And how?

**Comment by stephenway** [comment]
You can use it on codepen.io if you go into CSS settings. It's not native to the browser, and I doubt it will be.

A lesser functional option would be if you edited your postcss in the sources panel then compiled using terminal or devtools terminal. That experience isn't as good as a modern editor though.

**Comment by ai** [comment]
@acterhd yes, you can.

But I need more info to answer on second question. There is a two use cases in browser usage.

1. “Complie CSS string to other string to make some tool like CodePen”. Just take `postcss` npm package and back it to bundle by browserify or webpack. Then use [JS API](https://github.com/postcss/postcss#js-api) like it is a node.js app.
2. “Use PostCSS in dynamic CSS in my live component like CSS-in-JS”. Take [postcss-js](https://github.com/postcss/postcss-js).

**Comment by acterhd** [comment]
Can I use Verbal Expressions library?

**Comment by ai** [comment]
@acterhd you can use any JS library inside your PostCSS plugin.

But what exactly do you want to do?

**Comment by acterhd** [comment]
I want declare new color functions.
I look to conic gradient library, very hard regex :)

**Comment by ai** [comment]
@acterhd regexp is not a best way to work with syntax. At least you can't write regexp for any brackets case 😉.

You should look to postcss-value-parser https://github.com/TrySound/postcss-value-parser

**Comment by ai** [comment]
If you want to generate some dynamic CSS (like polyfill with some client side calculations) from static CSS, you should provide to user JS and some PostCSS plugin. Look to cq-prolifill

https://github.com/ausi/cq-prolyfill

Because most of PostCSS users run PostCSS once on deploy.

**Comment by acterhd** [comment]
I have some custom-images.
https://github.com/acterhd/css-canvas-emulator

But... I want use HCG colors in real time.
https://github.com/acterhd/hcg-color

Also I want make workaround of some CSS properties with JavaScript. So, I
have question: can postcss generate JS, and even give some API for JS
algorithms.


2016-02-09 6:53 GMT+08:00 Andrey Sitnik <notifications@github.com>:

**Comment by ai** [comment]
@acterhd yes. Your plugin can accept a callback option and pass JS content to callback, so user can save it. Or just save this extra JS near origin CSS file.

Or you can use one common static JS, but put some data to CSS and then extract it JS file like cq-prolyfill does.

**Comment by acterhd** [comment]
I know CSS3 attr, and CSS3 custom properties. I know that this feature can be acheive by CSS variables I.e. semi-static. But need append JS observer to every new elements. 

Need to think...

**Comment by acterhd** [comment]
I'm sorry, cq-polyfill used parts of postcss?

**Comment by ai** [comment]
@acterhd yeap, it contains big client side JS file and small PostCSS plugin to preprocess CSS files for that client side JS.

**Comment by acterhd** [comment]
I think I know... 
In theory need two files: variable-function map (JSON) and valid stylesheet (CSS). And map elements with these variables. But can I generate JSON with postcss?

**Comment by ai** [comment]
@acterhd yes, your plugin can write some file or pass it to user callback.

**Comment by acterhd** [comment]
How to get selector of declaration?

**Comment by ai** [comment]
@acterhd I do not sure, that I understand you, but:

```js
var rule = declaration.parent;
rule.selector;
```

Also this issue is about client side usage. You can ask this small questions in [our Gitter support chat](https://gitter.im/postcss/postcss). You will get answer faster and it is a better way for questions (not a issues).

**Comment by acterhd** [comment]
I have problems. How to test local plugin?

**Comment by ai** [comment]
See postcss-plugin-boilerplate. It contains a test example on AVA (you should ask this question in gitter chat, not here).
