### ISSUE TITLE
Problem reporting positions when using SCSS parser and // comments

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#725]
I'm not sure if the best resolution to this issue lies in postcss itself or in postcss-scss, so I figured I'd start here.

The function `node.positionInside()` is not producing accurate positions when using the SCSS parser on stylesheets with `//` comments. This is causing stylelint to report inaccurate positions in its warnings: https://github.com/stylelint/stylelint/issues/712

I believe the problem is this: stylelint passes `result.warn()` a `node` and an `index`. Ultimately, `node.positionBy()` calculates the line and column positions based on those two pieces. But within `node.positionBy()`, it stringifies the node *and in that stringification outputs real CSS comments instead of `//` comments*. Therefore, it calculates line and column positions based on a string that is not identical to the original source.

For example, the original code string

```css
// 1\n// 2\n// 3\n// 4\n// 5\n// 6\na::before { content: ''; }
```

becomes this

```css
/* 1*/\n/* 2*/\n/* 3*/\n/* 4*/\n/* 5*/\n/* 6*/\na::before { content: ''; }
```

... so the index that originally referred to, say, the colon after `content` no longer does.

Any ideas on a good solution here? I understand why you'd want the stringifier to output real comments; but how can `node.positionBy()` then calculate positions based on the real original stylesheet?

**Comment by ai** [comment]
In this example, `a::before` will be on separated line, so it will be independent from previous comments size, as I understand.

Can you should some better example?

**Comment by davidtheclark** [comment]
In fact this example does illustrate the problem. But I'll try to explain better. 

Maybe the main thing to point out is that I'm attaching the warning to the `root` node, not to the `rule`. So the `root` node *does* contain the comments.

```
// 1\n// 2\n// 3\n// 4\n// 5\n// 6\na::before { content: ''; }
```

The index of the opening quotation (in the value of `content`) in this source code is 58. So when I report a warning with `{ node: root, index: 58 }`, I should get a position of `{ line: 7, column: 22 }`. However, what I end up with is `{ line: 7, column: 10 }` — a difference of 12 columns. That number 12 corresponds exactly to the number of comments: for every comment (6 total), 2 columns are added to the original source, for the `*/` that is added to close the *real CSS comments*. When `positionBy()` calculates the position, it does so in relation to the modified string, with these extra `*/` columns; and to that string, index 58 refers to the space between `before` and `{`, not the opening quote — so the warning position ends up inaccurate.

Does that better explain?

**Comment by ai** [comment]
Hm. Why you use `{ node: root, index: 58 }`, but do not `{ node: decl, index: 10 }`?

**Comment by davidtheclark** [comment]
Well, I have some reasons in this particular case --- but that shouldn't matter for this issue, right? 

Theoretically the same problem is going to arise anywhere `//` comments are used: even if the `node` is more focused, the `index` will have problems. 

Like if I try to report the position of `10px` in this declaration:

```scss
.foo {
  padding:
    8px
    12px
    // 10px corresponds to something else somewhere
    10px;
}
```

Or if I try to report the position of the `div` selector in this rule:

```scss
.foo,
// All divs in #bar need the styling
#bar div {
  color: pink;
}
```

**Comment by ai** [comment]
These examples is better :D

**Comment by davidtheclark** [comment]
:+1:

**Comment by davidtheclark** [comment]
@ai: I could try to help fix this one but I'm really not sure how you'd like it done. If you give me any direction as to what you would like done, I can try to write some code.

**Comment by ai** [comment]
@davidtheclark I have no idea for direction too :D.

First dirty idea: add `Node#raws.lengthDiff` property.

**Comment by davidtheclark** [comment]
Maybe I'm misunderstanding something about the goal of custom parsers/stringifiers. The postcss-scss Readme states:

> Note that you don't need a special stringifier to handle the output; the default one will automatically convert single line comments into block comments.

That seems weird to me, because it's like PostCSS is doing a little bit of compilation there automatically — not just parsing. Doesn't every parser need to have a complementary stringifier, capable of converting the parsed AST back to its original code? In the case of SCSS it would be capable of stringifying inline comments differently? Otherwise wouldn't `node.toString()` be unreliable, because other unique constructs might throw it off just like `//`-comments do?

I was also wondering: If `node.toString()` is supposed to return a *real CSS* string based on the AST, could a method like `node.toRawString()` return the *original source code no matter what*? Parsers that enable non-CSS stuff like `//`-comments would have to add another bit of information to nodes: the complete raw source string for the node.

I don't know if I'm way off-base, just thought I'd throw out my thoughts — does any of the above make sense?

**Comment by ai** [comment]
@davidtheclark not every parser should have complementary stringifier. For example, `postcss-safe-parser` has no stringifier. In other hand `midas` has no parser.

**Comment by davidtheclark** [comment]
How about this idea? "If node.toString() is supposed to return a real CSS string based on the AST, could a method like node.toRawString() return the original source code no matter what?"

**Comment by ai** [comment]
Or we can use `node.source.input.sourceContent` :)

**Comment by davidtheclark** [comment]
Yeah, that makes sense to me, too.

If we did that, am I right in thinking that would need involve changes to the tokenizer and parser?

**Comment by ai** [comment]
BTW, what is end-user case of this issue (It will be useful for thinking about new API).

**Comment by davidtheclark** [comment]
End-user just wants to see accurate line/column positions of some report. 

Maybe it's stylelint tell you about a linting error. Or maybe it's a CSS syntax error that PostCSS itself tells you about.

**Comment by ai** [comment]
I mean I need task example (abstract thinking is hard to me 😀)

**Comment by davidtheclark** [comment]
How about the examples above? https://github.com/postcss/postcss/issues/725#issuecomment-181900397

**Comment by ai** [comment]
Thanks. And what JS code you will use?

**Comment by davidtheclark** [comment]
I think something like this should show the issue, right?

```css
.foo {
  padding:
    8px
    12px
    // 10px corresponds to something else somewhere
    10px;
}
```

```js
rule.eachDecl(decl => {
  const violationIndex = decl.toString().indexOf('10px');
  if (violationIndex === -1) return
  result.warn('Do not use 10px values', { node: decl, index: violationIndex })
})
```

**Comment by davidtheclark** [comment]
Hmmm ... or maybe it only causes the problem if you use `decl.source.input.css`. Because wouldn't `decl.toString()` balance it out?

Obviously I'm not experimenting actively just throwing out ideas. I can look into it later but probably not today.

**Comment by davidtheclark** [comment]
The actual code this came up for is here: https://github.com/stylelint/stylelint/blob/master/src/rules/string-quotes/index.js. The `styleSearch()` util in there just moves through the whole string looking for what it's told to look for. The `report()` function pretty directly interfaces with `result.warn()`.

**Comment by davidtheclark** [comment]
@ai: I dug a little bit more and found this: The problem is arising for me when I get an index based on `node.source.input.css` (which I guess is undocumented anyway?). But I actually *do not have the problem* if I get an index based on `node.toString()`. So as long as I stick with `node.toString()`, I shouldn't have the problem.

Do you want to close this issue, then?

**Comment by ai** [comment]
Yeap, let’s close it :)
