### ISSUE TITLE
TypeError: Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by timaschew** [postcss/postcss#729]
I'm using webpack and have two css files. One file uses an `@import` of the other.
The imported file cannot be loaded, because I get this error:

```
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
Module build failed: TypeError: Cannot read property 'before' of undefined
    at Stringifier.raw (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/stringifier.js:120:30)
    at Stringifier.body (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/stringifier.js:91:31)
    at Stringifier.root (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/stringifier.js:33:24)
    at _class.stringify (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/stringify.js:14:9)
    at _class.generateString (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/map-generator.js:235:14)
    at _class.generateMap (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/map-generator.js:192:14)
    at _class.generate (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/map-generator.js:275:25)
    at LazyResult.stringify (/Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/lazy-result.js:226:24)
    at /Users/timaschew/dev/redux-boilerplate/node_modules/postcss/lib/lazy-result.js:163:27
 @ ./src/styles/styles.css 4:14-125 13:2-17:4 14:20-131
```

My webpack config looks like this:

```js
var cssnext = require('cssnext')
var precss = require('precss')

module.exports = {
  module: {
    loaders: [
      {
        test: /\.css/,
        exclude: [/node_modules/],
        loader: 'style!css!postcss'
      }
    ]
  },
  postcss: function() {
    return [
      cssnext({
        autoprefixer: ['last 2 version']
      }),
      precss
    ]
  }
```

I logged the object where the error happens:

```js
Rule {
  nodes:
   [ Declaration {
       type: 'decl',
       parent: [Circular],
       source: [Object],
       before: '\n    ',
       prop: 'color',
       between: ': ',
       value: '#ccc' } ],
  type: 'rule',
  parent:
   Root {
     raws: { semicolon: false, after: '\n' },
     type: 'root',
     nodes: [ [Circular], [Object], [Object], [Object] ],
     source: { input: [Object], start: [Object] },
     lastEach: 51,
     indexes: {},
     _autoprefixerDisabled: false,
     variables: { column: '200px' } },
  source:
   { start: { line: 1, column: 1 },
     input:
      Input {
        css: '.foobar {\n    color: #ccc;\n}\n',
        safe: false,
        file: '/Users/timaschew/dev/redux-boilerplate/src/styles/vendor.css',
        from: '/Users/timaschew/dev/redux-boilerplate/src/styles/vendor.css' },
     end: { line: 3, column: 1 } },
  before: '',
  between: ' ',
  selector: '.foobar',
  semicolon: true,
  after: '\n',
  lastEach: 9,
  indexes: {},
  _autoprefixerDisabled: false }
```

**Comment by ai** [comment]
Can you show content of that 2 CSS files?

**Comment by timaschew** [comment]
Assumed that it's not neccessary, becaues they really simple.
Both files located in `src/styles`

__styles.css__
```css
@import "vendor.css"

$blue: #888;
$column: 200px;

.menu {
    width: calc(4 * $column);
    background-color: #ccc;
}

.menu_link {
    background: $blue;
    width: $column;
    a {
      font-weight: bold;
    }
}
```

__vendor.css__

```css
.foobar {
    color: #ccc;
}
```

The file is loaded by a JavaScript file via `require('../styles/styles.css')`.
It's working if I load the vendor file directly or if I put the content of the vendor into the styles file.

**Comment by ben-eb** [comment]
You've missed a semicolon on your `@import` rule, which is invalid.

**Comment by ai** [comment]
Yeap, it looks like `@import "vendor.css" $blue: #888;` at-rule. But we need to print better error message for this cases. Any ideas?

/cc @TrySound

**Comment by TrySound** [comment]
Hm... we have better error message for this. Need to try without loader.

**Comment by ben-eb** [comment]
I thought we had a `throw` especially for a missed semicolon? Or does it not work for atrules because there are two syntaxes? `@foo bar;` & `@foo bar {}`

**Comment by ai** [comment]
@ben-eb we have special coase for missed `;` between declarations. Unfortunatly `@import "vendor.css" $blue: #888;` is a valid syntax — for example for mixins. So we need some check in `postcss-import`.

**Comment by timaschew** [comment]
Oops. I add the semicolon, but still have the same error message.

The object again:

```js
Rule {
  nodes:
   [ Declaration {
       type: 'decl',
       parent: [Circular],
       source: [Object],
       before: '\n    ',
       prop: 'color',
       between: ': ',
       value: '#ccc' } ],
  type: 'rule',
  parent:
   Root {
     raws: { semicolon: false, after: '\n' },
     type: 'root',
     nodes: [ [Circular], [Object], [Object], [Object] ],
     source: { input: [Object], start: [Object] },
     lastEach: 51,
     indexes: {},
     _autoprefixerDisabled: false,
     variables: { blue: '#888', column: '200px' } },
  source:
   { start: { line: 1, column: 1 },
     input:
      Input {
        css: '.foobar {\n    color: #ccc;\n}\n',
        safe: false,
        file: '/Users/timaschew/dev/redux-boilerplate/src/styles/vendor.css',
        from: '/Users/timaschew/dev/redux-boilerplate/src/styles/vendor.css' },
     end: { line: 3, column: 1 } },
  before: '',
  between: ' ',
  selector: '.foobar',
  semicolon: true,
  after: '\n',
  lastEach: 9,
  indexes: {},
  _autoprefixerDisabled: false }
```

**Comment by ai** [comment]
@timaschew post stacktrace again, you may miss some changes.

**Comment by TrySound** [comment]
@timaschew Can you make two runs with disabled cssnext and with disbled precss?

**Comment by timaschew** [comment]
@ai I checked the stacktrace, it didn't change
@TrySound 
turned off precss -> no changes, same stack
turned off cssnext, just pass autoprefixer -> it works!

**Comment by timaschew** [comment]
BTW: If I omit the semicolon without cssnext, it just compile, but it's interpreted as an media query and the output is
```css
@media $blue: #888 {

    .foobar {
        color: #ccc;
    }
}
```

**Comment by jeddy3** [comment]
Doesn't `precss` need to come before `postcss-cssnext` in the pipeline? Otherwise won't `postcss-cssnext` trip up on the `$var` syntax?

**Comment by TrySound** [comment]
@timaschew It was interpreted as media query, because after url can be optional media query :)

**Comment by timaschew** [comment]
@TrySound yes I just wanted to confirm what @ai said :)

@jeddy3 You're right, it's working with cssnext if I use precss before, thank you!

I cathed the order up from these examples
https://github.com/postcss/postcss-loader#usage, of course it's autoprefixer here and not cssnext
https://github.com/lcjnil/react-redux-scaffold/blob/master/webpack.config.js#L127-L135

**Comment by timaschew** [comment]
@ai I would suggest to provide a PR with an note or/and example in the readme about the order in combination with cssnext. Maybe in both 
https://github.com/postcss/postcss#webpack
and
https://github.com/postcss/postcss-loader

And maybe also in combination with the postcss-import, otherwise it isn't really usefull in development mode.

**Comment by ai** [comment]
@timaschew what PostCSS version do you use?

I check 5.0.15 and 5.0.14 build files and there is no any `any.before` or `any['before']` in line 120.

I think problem is in broken AST. I check current `Stringifier#raw` for any cases, when we ask `any.before` and `any['before']` and it can be when `Node#raws` is undefined. But it could not be, because `raws` is created in constructor.

So I think there is two possible sources of issue: cssnext generates broken AST (`postcss-import` has tricky logic with `raws.before`) or you use old PostCSS (maybe < 5).

**Comment by timaschew** [comment]
postcss 5.0.14 but I used __cssnext__ and not __postcss-cssnext__ :/
"Upgrading" to __postcss-cssnext__ fixes the error, BUT there was some other strange thing:

`@import "vendor.css"` results into an error because `_vendor` could not found. Why it's searching with an underscore prefix? I tried to write `@require "vendor.css"` which works

**Comment by TrySound** [comment]
@timaschew cssnext do not have require directive. Seems like you have sass loader.

**Comment by TrySound** [comment]
@timaschew Oh, you have precss. It uses `postcss-partial-import`.

**Comment by ai** [comment]
Problem is that you use `cssnext`. It based on old PostCSS.

You should use `postcss-cssnext`.

Also feel free to create issue in cssnext to clear in docs, that `cssnext` is deprecated.

**Comment by timaschew** [comment]
@TrySound thanks, I created an issue here: https://github.com/jonathantneal/postcss-partial-import/issues/12
