### ISSUE TITLE
compare plugins of packs like cssnext, rucksack and precss

### ISSUE THREAD

**Issue by timaschew** [postcss/postcss#732]
I started (still WIP) to create a table and compare which packs use which postcss plugins.
https://github.com/timaschew/postcss-compare-packs

Do you think it can be linked somewhere here in the postcss repo?

**Comment by ai** [comment]
`postcss-cssnext` doesn’t use Autoprefixer and `cssnext` is depreacted.

**Comment by timaschew** [comment]
You're right it should be `postcss-cssnext` not `cssnext`.
But what you mean with it  _doesn’t use Autoprefixer_ ?
This line showing it is: https://github.com/MoOx/postcss-cssnext/blob/master/src/features.js#L70

**Comment by ai** [comment]
Nice work. But I think it is a wrong way to solve this real pproblem. The best solution do not need a docs.

For example, we need need more task focused plugin packs, rather than all-in-one (like rucksack). this is why postcss-cssnext now focused only on CSS4 features.

Other solution, we should find same plugins with same settings and disable it.

Also one extra plugin is not a problem, because PostCSS is very-very fast.

**Comment by ai** [comment]
I can retweet your tweet about it, but I afraid that link from PostCSS docs will increase a more bad plugin packs.

**Comment by timaschew** [comment]
> Nice work. But I think it is a wrong way to solve this real pproblem.

Which problem? :D

I totally agree with you about __we need need more task focused plugin packs, rather than all-in-one__. 

The table should be just an overview for people which might be interested in using some of the packs and see what they are actual use internally.
Or maybe to prevent from creating new packs which would contain most of plugins which already exist in existing packs.

> Other solution, we should find same plugins with same settings and disable it.

You mean find packs with same plugins?
But right this case can be done with the table.

> but I afraid that link from PostCSS docs will increase a more bad plugin packs.

Don't really understand why? We can agree on list only packs which are only listed on
http://postcss.parts/
and/or
https://github.com/postcss/postcss/blob/master/docs/plugins.md

Or how it can __increase more bad plugin packs__?

**Comment by ai** [comment]
It can increase more bad packs by showing that it is OK to having same plugin in many different packs.

**Comment by timaschew** [comment]
Okay, but this can be prevented by saying explicitly that it's not ok. Anyway.
I completed the table and wrote down some short FAQs, maybe you can check if I missed something or misunderstood something. 

https://github.com/timaschew/postcss-compare-packs/blob/master/README.md#what-does-it-mean-if-a-plugin-exists-in-more-than-one-pack

**Comment by ai** [comment]
Hm, let’s see people feedback. I will promote this link in Twitter and we will see people feedback.

What do you think about it?

**Comment by timaschew** [comment]
Yep sounds great :)
