### ISSUE TITLE
Changelog format

### ISSUE THREAD

**Issue by maximkoretskiy** [postcss/postcss#734]
It would be nice to format changelog like described in this document http://keepachangelog.com/.
It wouldn't take a lot of time and will make changelog more consistent.

**Comment by ai** [comment]
@maximkoretskiy I use pretty same format https://github.com/postcss/postcss/blob/master/CHANGELOG.md

What exactly do you want?

**Comment by maximkoretskiy** [comment]
- release dates
 - `unreleased` secteon
 - document title (optionaly)
 - article about semver (optionaly)

**Comment by ai** [comment]
Unreleased is useful (but we didn’t have unreleased changes right now).

Why release dates is important for you?

**Comment by maximkoretskiy** [comment]
Changelog is a project history. And it`s not too hard to write it now.
For example, dates can be useful when You detect some problems related with dependency version change and You can't remember the date when version changed.

**Comment by ai** [comment]
OK, I agree about date and SemVer mention. But I think title is bad for date. There are only few non-important cases for date, so we should not put it in most important section.

PR is welcome.

**Comment by maximkoretskiy** [comment]
@ai  Do You wanted to say "I agree about ~~date~~**title** and SemVer mention"?

And I missed your idea about the most important section.

Usualy it looks this way

## 5.0.15 - 2016.02.11
* Fix `Node#clone()` on `null` value somewhere in node.

## 5.0.14 - 2016.02.05
* Allow to use PostCSS in webpack bundle without JSON loader.

## 5.0.13  - 2016.02.01
* Fix `index` and `word` options in `Warning#toString` (by Bogdan Chadkin).
* Fix input source content loading in errors.
* Fix map options on using `LazyResult` as input CSS.
* 100% test coverage.
* Use Babel 6.

**Comment by timaschew** [comment]
@maximkoretskiy
Why you don't use the dates from the releases page? https://github.com/postcss/postcss/releases

**Comment by ai** [comment]
@maximkoretskiy nope, I mean that I am OK with release date, but they should not be in title, because it is a minor information.

**Comment by maximkoretskiy** [comment]
@ai what formatting do you prefer for dates?

@timaschew It is not a part of git project. We can't search in 'releases'. 
You can read arguments to use this changelog format here http://keepachangelog.com/ru/

**Comment by ai** [comment]
`YYYY-MM-DD`

**Comment by maximkoretskiy** [comment]
It is format. I asked You about formatting.

Example:

## 5.0.15
**2016-02-11**
* Fix `Node#clone()` on `null` value somewhere in node.

**Comment by timaschew** [comment]
I think it would be easier to write it in one line with the version number, this way it's less typing :)
But it's your decision ;)

**Comment by ai** [comment]
@timaschew in one line minor data looks too small.

I really think that this date is non-important. And if we can’t put them nice, we should not put them to ChangeLog.

There is no case for dates. For some rare case, users can use git tags and GitHub Releases.

**Comment by maximkoretskiy** [comment]
Ok

**Comment by timaschew** [comment]
Seems to be used for some projects: https://github.com/nodejs/node/blob/master/CHANGELOG.md ;)
But it's up to you :)

**Comment by ben-eb** [comment]
I agree with @ai, it's redundant. Especially when you can generate this list from the tags;

```
git for-each-ref --sort=taggerdate --format '%(refname) %(taggerdate)' refs/tags
```

outputs:

```
refs/tags/0.1 Mon Nov 4 22:08:13 2013 +0200
refs/tags/0.2 Wed Dec 18 00:46:13 2013 +0100
refs/tags/0.3 Thu Feb 13 23:28:30 2014 +0400
refs/tags/0.3.1 Tue Feb 18 16:24:30 2014 +0400
refs/tags/0.3.2 Wed Feb 19 15:04:20 2014 +0400
refs/tags/0.3.3 Sun Mar 2 13:14:22 2014 +0400
refs/tags/0.3.4 Tue Mar 4 00:23:16 2014 +0400
refs/tags/0.3.5 Fri May 30 13:56:04 2014 +0800
refs/tags/1.0.0 Mon Jun 23 13:53:29 2014 +0900
refs/tags/2.0.0 Wed Jul 23 10:51:06 2014 +0400
refs/tags/2.1.0 Sun Jul 27 13:14:26 2014 +0400
refs/tags/2.1.1 Thu Aug 7 01:49:54 2014 +0400
refs/tags/2.1.2 Fri Aug 8 23:34:28 2014 +0400
refs/tags/2.2.0 Sun Aug 17 18:51:22 2014 +0400
refs/tags/2.2.1 Fri Aug 22 16:29:19 2014 +0400
refs/tags/2.2.2 Wed Aug 27 19:24:20 2014 +0400
refs/tags/2.2.3 Thu Aug 28 03:15:52 2014 +0400
refs/tags/2.2.4 Mon Sep 1 21:53:18 2014 +0400
refs/tags/2.2.5 Thu Sep 25 00:53:15 2014 +0400
refs/tags/2.2.6 Fri Oct 31 23:53:25 2014 +0300
refs/tags/3.0.0 Wed Nov 12 01:12:36 2014 +0300
refs/tags/3.0.1 Thu Nov 13 21:38:13 2014 +0300
refs/tags/3.0.2 Fri Nov 14 16:58:17 2014 +0300
refs/tags/3.0.3 Fri Nov 21 15:53:20 2014 +0300
refs/tags/3.0.4 Sat Nov 22 11:26:48 2014 +0300
refs/tags/3.0.5 Thu Nov 27 23:36:49 2014 +0300
refs/tags/3.0.6 Sun Dec 7 23:03:38 2014 +0200
refs/tags/3.0.7 Tue Dec 9 12:14:31 2014 +0300
refs/tags/4.0.0 Tue Dec 30 13:37:49 2014 +0100
refs/tags/4.0.1 Sun Jan 11 19:43:17 2015 +0100
refs/tags/4.0.2 Sat Jan 24 20:13:55 2015 +0300
refs/tags/4.0.3 Wed Jan 28 15:40:35 2015 +0300
refs/tags/4.0.4 Sat Feb 14 13:43:45 2015 +0300
refs/tags/4.0.5 Mon Feb 23 16:28:59 2015 +0300
refs/tags/4.0.6 Tue Feb 24 15:42:00 2015 +0300
refs/tags/4.1.0 Wed Apr 1 18:31:53 2015 +0300
refs/tags/4.1.1 Thu Apr 2 10:15:11 2015 +0300
refs/tags/4.1.2 Thu Apr 2 13:56:01 2015 +0300
refs/tags/4.1.3 Sun Apr 5 21:53:10 2015 +0300
refs/tags/4.1.4 Mon Apr 6 02:51:18 2015 +0300
refs/tags/4.1.5 Tue Apr 14 00:45:36 2015 +0300
refs/tags/4.1.6 Sun Apr 26 20:45:04 2015 +0300
refs/tags/4.1.7 Wed Apr 29 01:34:54 2015 +0300
refs/tags/4.1.8 Fri May 1 03:16:18 2015 +0300
refs/tags/4.1.9 Tue May 5 13:31:41 2015 +0300
refs/tags/4.1.10 Mon May 11 20:58:51 2015 +0300
refs/tags/4.1.11 Sat May 16 20:13:19 2015 +0300
refs/tags/4.1.12 Sun Jun 21 22:01:12 2015 -0400
refs/tags/4.1.13 Tue Jun 23 18:55:51 2015 -0400
refs/tags/4.1.14 Sat Jul 4 13:57:46 2015 +0300
refs/tags/4.1.15 Tue Jul 7 18:23:48 2015 +0300
refs/tags/4.1.16 Tue Jul 7 21:53:37 2015 +0300
refs/tags/5.0.0 Wed Aug 19 21:56:36 2015 +0300
refs/tags/5.0.1 Thu Aug 20 23:55:24 2015 +0300
refs/tags/5.0.2 Sat Aug 22 17:11:07 2015 +0300
refs/tags/5.0.3 Sat Aug 29 01:00:52 2015 +0300
refs/tags/5.0.4 Tue Sep 1 21:21:26 2015 +0300
refs/tags/5.0.5 Sat Sep 12 13:30:58 2015 +0300
refs/tags/5.0.6 Mon Sep 21 19:38:07 2015 +0300
refs/tags/5.0.7 Fri Sep 25 11:33:25 2015 +0100
refs/tags/5.0.9 Thu Oct 8 19:30:12 2015 +0100
refs/tags/5.0.10 Thu Oct 15 00:36:36 2015 +0100
refs/tags/5.0.11 Sat Nov 7 16:56:13 2015 +0300
refs/tags/5.0.12 Fri Nov 13 17:20:51 2015 +0200
refs/tags/5.0.13 Wed Dec 16 16:54:11 2015 +0300
refs/tags/5.0.14 Sun Jan 3 22:41:42 2016 +0100
refs/tags/5.0.15 Thu Feb 11 17:15:42 2016 +0300
```
