### ISSUE TITLE
Is documentation wrong for `input.origin()`?

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#737]
[The docs for `input.origin()`](https://github.com/postcss/postcss/blob/master/docs/api.md#inputoriginline-column) say that the function returns an object like this:

```js
{ source: 'a.css', line: 3, column: 1 }
```

But when I tried it out today I was getting the key `file` instead of `source`:

```js
{ file: '/path/to/less-foo.less',  line: 5, column: 0 }
```

Is that a mistake in the docs or am I missing something?

**Comment by ai** [comment]
Oops. `result.file` is right. Technically we have also `result.source` with origin source code of this file.

DO you want to send PR with fix?

**Comment by davidtheclark** [comment]
Will do.
