### ISSUE TITLE
File-specific plugins options

### ISSUE THREAD

**Issue by nezed** [postcss/postcss#753]
In some cases it will be very useful to pass specific options to plugin for current file, from current file.
Also in some cases disable specific plugin.

For example in cases of: ignoring lints and check for current file, disabling polyfilers/fixers/prefixers for current file (when polyfill can break current solution), etc.

I think great syntax for solution will be like [postcss-use syntax](https://github.com/postcss/postcss-use#standard-syntax)

> Создай ишью, на трезвую голову.
> — [Ситник](https://github.com/ai)

**Comment by TrySound** [comment]
@nezed Can't postcss-use do what you need?

**Comment by TrySound** [comment]
Or you want something like
```css
@use autoprefixer;
@ignore stylelint;
```

**Comment by TrySound** [comment]
Btw normalize.css has `font-family: monospace, monospace` which shoudn't be affected with `minify-font-values`. In this case it should be customised via options.

/cc @ben-eb 
We need to integrate the same feature in cssnano4.

**Comment by ai** [comment]
Maybe we should integrate postcss-use in next versions to core and implement default way to disable plugin or some option.

**Comment by ben-eb** [comment]
@ai Keep PostCSS core minimal; I don't want or need `@use` functionality for cssnano or other modules. Unless, we are to extract current core functionality into some other module that solely provides the parser/stringifier/source maps support (and nothing else) as it stands today.

**Comment by nezed** [comment]
@TrySound not sure about postcss-use, its main feature is requiring plugin, which not specified in postcss options

Agree with @ben-eb about keeping additional features as external module, cause theirs syntax can confuse or conflict

**Comment by TrySound** [comment]
I'm for plugins too.

I think we should introduce internal API for plugins filtering which can be used out of the box in options or via `postcss-use` or similar plugins,

**Comment by nezed** [comment]
@TrySound but its not only about internal API and not only about ignoring some plugins.
Its also about custom options for plugin per specific files.
Same as u can [`/* doiuse-disable flexbox */`](https://github.com/anandthakker/doiuse#ignoring-file-specific-rules)

**Comment by ai** [comment]
I will close for now.
