### ISSUE TITLE
Enabling absolute urls in source maps

### ISSUE THREAD

**Issue by markfinger** [postcss/postcss#757]
Hi,

I'm in the process of trying to implement a PR for postcss that would enable absolute urls (including protocols, eg: file, http, or https). In effect, given the following options

```js
from: 'file:///dir/a.css',
to: 'http://example.com/a.css'
map: {
  inline: false, 
  // note: this option is described below
  preservePaths: true
}
```

I'd like for the source map to correctly reference both the source and the target file. Unfortunately, postcss is currently implemented such that `from` and `to` are assumed to be file directories that a relative path can be inferred from. Suffice to say, the resulting output is fairly broken.

I've tried adding the following to the `relative(file) {...}` in `map-generator.es6`:

```js
if (this.mapOpts.preservePaths) {
  return file;
}
```

The intention being to enable the `map.preservePaths` flag to prevent the majority of the behaviour in the `relative(file) {...}` method, but unfortunately this hasn't had the immediate result that I hoped for. 

From logs that I've been outputting, the incoming values to `relative(file) {...}` is called with `file` equal to `/path/to/cwd/file:/dir/a.css`. 

My _assumption_ is that something higher up in the codebase would be manipulating the `from` argument. But - having taken a bit of a dig through the source code - I've been unable to understand why. Is anyone able to shed any light on how I could approach the problem of preventing complete urls from being manipulated during source map generation?

**Comment by ai** [comment]
Done 47d00dd (even without special option)

**Comment by ai** [comment]
Also this commit is relative too fe51a0c
