### ISSUE TITLE
CSSSyntaxError no longer instanceof Error

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss#763]
Change occurs between 5.0.12 and 5.0.13. Can't find why.

Test code:
```js
postcss().process('a{').catch(function (err) {
  // 5.0.12: true, 5.0.13: false
  console.log(err instanceof Error);
});
```

Is it intended ?

**Comment by ai** [comment]
Yeap. But JS is not a class language, it is prototype language. So public API is only `err.name === 'CssSyntaxError'`

**Comment by iamvdo** [comment]
OK, but it used to work, so I don't get why it's no longer the case. No matter.

**Comment by ai** [comment]
@iamvdo problem was in Babel 6. It had some issues with class extending.
