### ISSUE TITLE
Plugins order

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#764]
We have to fix this. I am so tired of being wrong postcss config with autoprefixer as the first plugin, before other transformation.
We have to do something. Very bad UX. We waste our times to explain the same thing all the times. Most postcss/cssnext tutorial are wrong.

**Comment by ai** [comment]
This task is duplicate for Event based API.

I totally agree, that it is one of the biggest problem in PostCSS right now. But I asked for some technical committee leader as we did in postcss.org.

**Comment by MoOx** [comment]
You mean that you want all existing plugin to be updated before doing anything?
You are not likely to ship this changes in a near future, and most plugins will not be updated right after it, so maybe we should do something now until the entire ecosystem has been updated?

**Comment by lkraav** [comment]
Can someone point me to what the underlying problem is? It's the first I've heard of this topic.

**Comment by ai** [comment]
@lkraav https://github.com/postcss/postcss/issues/296

**Comment by ai** [comment]
@MoOx yeap, I want to implement new also knowed as “visitors” API and they we need to rewrite all plugins to it. it will dramatically fix many plugin order conflicts in PreCSS.

Do you have any other ideas? What is a “autoprefixer as the first plugin” problem?

**Comment by MoOx** [comment]
Current problem example:

plugin list: autoprefixer, postcss-import

autoprefixer is executed before other transformation (so inlined import), so inlined import rules won't be prefixed.

This is a really common mistake.

**Comment by ai** [comment]
@MoOx as quick fix you can print a warning. Like have a blacklist of most popular plugins and warn users about having plugin before postcss-import.

**Comment by MoOx** [comment]
A note is wrote in bold in the very first start of the README. But nobody read that. Well I will try to add a warning (not using the postcss api since most people don't have the correct reporter)... But that's kind of gross... Same thing for all plugin packs etc.

**Comment by ai** [comment]
@MoOx yeap, nobody read a docs :(. Sorry, I have no other ideas, only Event Based API.
