### ISSUE TITLE
Plugin request: Remove unused styles from CSS

### ISSUE THREAD

**Issue by azat-io** [postcss/postcss#767]
It'll be very helpful if in PostCSS there will be some plugin to remove unused styles like in [UnCSS](https://github.com/giakki/uncss). Can we do something like this using PostCSS and maybe something like PostHTML?

Because using UnCSS after PostCSS works very slow and Gulpfile.js looks dirty:

```js
var gulp = require('gulp');
var nano = require('gulp-cssnano');
var postcss = require('gulp-postcss');
var uncss = require('gulp-uncss');

gulp.task('postcss', function () {
  var processors = [
    // list of many plugins
  ];
  return gulp.src('src/css/*.css')
    .pipe(postcss(processors))
    .pipe(uncss({
        html: ['dist/index.html']
    }))
    .pipe(nano())
    .pipe(gulp.dest('dist/css/'))
    .pipe(browserSync.stream());
});
```

**Comment by ben-eb** [comment]
UnCSS uses PostCSS now.

https://github.com/giakki/uncss/blob/master/package.json#L44

**Comment by ai** [comment]
@ben-eb Awesome!
