### ISSUE TITLE
Cannot use es2015 destructuring in plugin option

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#768]
```js
const somePlugin = postcss.plugin(
  "postcss-blahblah",
  ({ something }) => {
    return () =>  {}
  }
)
```

This throw an error. It seems in the core (I don't know why but I have an idea), you are "trying" plugin before they are actually used, and you call those with no options. I lost like an hour to trace this issue.
Why are you doing this during registration? What if plugin MUST have options (in my case it must).
I have to add an ugly workaround to hide this undesired plugin call without arguments.

**Comment by ai** [comment]
Yes, it is a limits of current API. We can think how to fix it in 6.0. But it will be possible only if plugin builder (function which accepts options) will be somewho different from plugin itself (maybe with new visitors API).

**Comment by ai** [comment]
Hm. Our Or maybe we can fix it in 5.1. I think a have a idea how to avoid `builder.postcss` creating.

**Comment by TrySound** [comment]
@MoOx Wil this help?
```js
({ something } = {}) => {}
```

**Comment by MoOx** [comment]
Thanks but no. This is not a fix, this is a workaround... :p

**Comment by TrySound** [comment]
@MoOx But it still should be if you want to use destructuring in arguments to error correctly if even object is not passed.

**Comment by MoOx** [comment]
This is a private plugin.

**Comment by ai** [comment]
Done 18513f5
