### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss#771]
Hello team,

If you didn’t know we recently migrated the postcss organization to GitHubs [new update](https://github.com/blog/2020-improved-organization-permissions) about a month ago. I think everyone should have received an e-mail about this.

With this update we have let everyone get full ownership access for the organization but this got us thinking of some security measures. Trust is key and always will be **BUT** I do believe [two-factor authentication ](https://help.github.com/articles/about-two-factor-authentication/) is very important and in fact maybe even mandatory to enable in this case.

Therefor we would you like you to enable [two-factor authentication](https://help.github.com/articles/about-two-factor-authentication/) on you’re GitHub account for security purposes.

I hope we can all be on the same page about this, but if someone has any problems - we are open for thoughts and discussion regarding this matter.

Thank you,

@davidtheclark , @gazay , @magsout , @morishitter , @TrySound , @yisibl , @ai

**Comment by ai** [comment]
I totally agree, that two-factor authentication is very important.

If you will not enable it, we will remove you from organization :).

**Comment by ai** [comment]
@gazay , @magsout , @morishitter , @TrySound , @yisibl I will remove your access if you will not enable Two-factor authentication on GitHub ;).

**Comment by magsout** [comment]
:+1:

**Comment by TrySound** [comment]
Done.

**Comment by marcustisater** [comment]
Closing this issue.

@morishitter @yisibl still missing two-auth.

**Comment by ai** [comment]
I move @morishitter @yisibl to outside collaborator role.

**Comment by morishitter** [comment]
@ai I'm so sorry to be late. I just enabled two-factor authentication.

**Comment by ai** [comment]
@morishitter no problem, I invited you back :)

**Comment by morishitter** [comment]
@ai Thanks :)
