### ISSUE TITLE
Request: first and last enhancement

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss#772]
I'd like to request modification of `first` and `last` properties in the `Container` module. Other parsers will allow passing an argument specifying a type to select. eg. `ast.root.first('selector')`.

This would be immensely helpful, though admittedly not critical. Cheers.

**Comment by ai** [comment]
Sorry, this change will broke API :(

**Comment by shellscape** [comment]
How would it break the API if the argument was optional? We do this all the time in javascript...

**Comment by ai** [comment]
Because right now `first` is a getter, not a method.
