### ISSUE TITLE
CssSyntaxError is not instanceof Error

### ISSUE THREAD

**Issue by LPGhatguy** [postcss/postcss#773]
This was discussed [on Gitter](https://gitter.im/postcss/postcss?at=56ef0a128b806f6b7a18d160).

When PostCSS throws a syntax error, the class (`CssSyntaxError`) doesn't inherit from `Error`, which makes it difficult to do a broad-sweep check for any sort of error.

**Comment by ai** [comment]
Sorry, Babel still have this issue. Somethings happens with prototype and class loose all its methods.

Maybe you can find the source of issue. I am always open for PR to this issue.

**Comment by LPGhatguy** [comment]
Do you have a link to the issue tracked in the Babel repository that corresponds to that problem? It seems like a totally version-breaking bug.

**Comment by ai** [comment]
@LPGhatguy sorry, I know that it is not fare to talk about issue without a link. But I am making a talk and deadline is just after few days.

Can I ask you to investigate? :) Just open `lib/css-syntax-error.es6` and put `extends Error`. Then execute `gulp build` and you will see broken AST (also broken tests).

**Comment by LPGhatguy** [comment]
Sure thing, I'll look into it.
