### ISSUE TITLE
Plugin that only runs after a set of PostCSS processes

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss#774]
I have this conundrum that is plaguing stylelint and postcss-reporter but probably applies to other actual or potential plugins, as well.

The best way to report on stylelint results for a group of files is to generate one report for the whole group, not one report for each file. For example, if I have 100 files, I want to see a total error and warning count for the whole set (34 errors, 20 warnings), not individual totals for each file (e.g. 2 errors, 1 warning ~100 times). There are also certain warnings that I only want to deliver once for the whole group, e.g. deprecation warnings or invalid option warnings, not once per file.

PostCSS is kind of designed to process one file at a time, right? And runners like gulp, Grunt, etc., feed it one file at a time. So that makes it difficult to report on groups of files *without controlling the PostCSS pipeline*. That's what stylelint does with its CLI and Node API: when each file gets processed its PostCSS Result gets added to a list that is then dealt with at the end, once all files are done. But if people are using stylelint within a PostCSS pipeline, with gulp-postcss or grunt-postcss or something similar, the best they can do is tack postcss-reporter onto the end of the PostCSS pipeline and get a whole bunch of one-file-at-a-time reports.

Ideally we would not have to create a specialized stylelint plugin for every runner that people want (gulp-stylelint, grunt-stylelint, etc); and then another set of specialized runner plugins for the next tool that comes along with similar needs. It would be awesome if stylelint and others could just piggyback on the PostCSS runners.

But I don't know of a way to solve the problem of *needing to accumulate Results before reporting*. So I wanted to start this issue.

Has anybody already solved this? Does anybody have ideas? 

See https://github.com/stylelint/stylelint/issues/917#issuecomment-195848903 and https://github.com/olegskl/gulp-stylelint/issues/3#issuecomment-191832200.

**Comment by ai** [comment]
I think you should create special `gulp-stylelint` :(.

The problem is that even Gulp and Webpack is designed to work with files separately :(.

@w0rm
