### ISSUE TITLE
Trailing whitespace inconsistency?

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss#775]
Consider the following input: `.foo {}\n`
That results in a Rule with: `raws: { before: '', between: ' ', after: '' },`
The parent Root has: `raws: { semicolon: false, after: '\n' },`

That's confusing, considering that the newline immediately follows the Rule. It is true that the Root does have the newline afterwards. However:

Consider the following input: `.foo {}\n .bar {}`
That results in two Rule nodes, the last with with: `raws: { before: '\n', between: ' ', after: '' },`
The parent Root has: `raws: { semicolon: false, after: '' },`

Why would the last Rule in the Root's nodes have a `raws.before` containing the newline, but the first Rule doesn't have `raws.after` containing the newline in either scenario? That would seem like a bug.

**Comment by ai** [comment]
`raws.after` has different semantic. It contains spaces inside block. For example, for rule and at-rule it contains space between last child and `}`.

This is why in `.foo {}\n` rule can’t contains trailing `\n`, because it doesn’t have any fields to it.

**Comment by shellscape** [comment]
@ai please give a chance to reply before closing an issue!

if that's the case, then wouldn't it be a bug that the last Rule containing `.bar{}` has a `raws.before: '\n'` since it has no rules as well?

**Comment by ai** [comment]
Don’™ worry, we can always reopen issue :)

**Comment by ai** [comment]
`before` is a spaces before node, not before opening `{`.

We know about problems with `raws`. But we can’t change names or behavior, because it broke API.

Here is description of every `raw` property: https://github.com/postcss/postcss/blob/master/docs/api.md#noderaws

Here is a issue about refactoring `raws` in 6.0: https://github.com/postcss/postcss/issues/199

**Comment by shellscape** [comment]
thanks for the api link, not sure how i missed that one. I'll follow #199 as well!
