### ISSUE TITLE
Failed to decode downloaded font && OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by minooo** [postcss/postcss#779]
hello，I have the problem, I don not know how to do with it;
[this is my problem](https://github.com/minooo/CSS-Modules-----React)
when you run `npm install` and `npm start`,open `localhost:5000`
you can see the problem like this 
![image](https://cloud.githubusercontent.com/assets/9410091/14010823/a260517c-f1d3-11e5-8bb3-6924ff9fd30a.png)
Any ideas? Thanks so much!

**Comment by ai** [comment]
Sorry, it is not relevant to PostCSS. PostCSS has no this type of error.

Maybe this answer is relevant: http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

**Comment by minooo** [comment]
thanks very much!
