### ISSUE TITLE
Proposal for performance improvement

### ISSUE THREAD

**Issue by andywer** [postcss/postcss#786]
Hey there!

I just had a quick thought on how to improve postcss performance, so I am curious for some feedback.

### Right now

Currently when postcss is run it parses the file to an AST and then invokes the plugins sequentially. The postcss plugins iterate over the rules using `Container.walk` and friends. Then the next plugin is invoked, more or less repeating the process applying its own transformations.

```text
+-> @foreach node
|       @transform(plugin1 transforms)
+-- @endforeach

+-> @foreach node
|       @transform(plugin2 transforms)
+-- @endforeach

...
```

### Proposal

Instead of iterating over the parsed AST nodes `no. of plugins` times it should not be too hard to iterate them just ones and invoke the plugins sequentially just for this one node.

```text
+-> @foreach node
|       @transform(plugin1 transforms)
|       @transform(plugin2 transforms)
|       ...
+-- @endforeach
```

That eliminates the redundancy of repeated iterations. The API would need a change and it must be tracked which new nodes a plugin creates while transforming (so it may be passed to the other plugins).

But the API would only need minor changes, maybe even none, since we could still use `css.walk(myFancyTransforms)` (or `css.walkAtRules()`/`css.each()`).

The new `walk` would just not iterate immediately and call the callback on each node, but rather register the callback, initialize the other plugins and eventually perform the iteration and call all those plugin callbacks on each node.

What do you think?

**Comment by ai** [comment]
It is good idea, but we already work on it for 6.0 release #296

**Comment by andywer** [comment]
Ohh, nevermind then!
