### ISSUE TITLE
PostCSS import fails in TypeScript with node resolution

### ISSUE THREAD

**Issue by kourge** [postcss/postcss#787]
I have a TypeScript project with `"moduleResolution": "node"` in its `tsconfig.json` as well as `postcss` in its `package.json` `devDependency`. When I write the following, it fails at runtime with the message `TypeError: Cannot read property 'parse' of undefined`:

```typescript
import * as postcss from 'postcss';
const root = postcss.parse('');
```

This is due to a mismatch between the exported JS from `./node_modules/postcss/lib/postcss.js` and the supplied typings at `./node_modules/postcss/d.ts/postcss.d.ts`. At the end of `postcss.d.ts` the last line says:

```typescript
export default postcss;
```

Which means given `import * as p from 'postcss'`, TypeScript would emit any expression `p.x` as `p_1.default.x`. However, when requiring PostCSS directly in node, it becomes clear that that is not the correct shape of the exported module at runtime:

```
  $ node
> const postcss = require('postcss')
undefined
> postcss
{ [Function: postcss]
  plugin: [Function],
  stringify: [Function: stringify],
  vendor:
   { prefix: [Function: prefix],
     unprefixed: [Function: unprefixed] },
  parse: [Function: parse],
  list:
   { split: [Function: split],
     space: [Function: space],
     comma: [Function: comma] },
  comment: [Function],
  atRule: [Function],
  decl: [Function],
  rule: [Function],
  root: [Function] }
```

This problem seems to be in the same vein of the [Babel default export behavior problem](https://phabricator.babeljs.io/T2212) that hit many people upgrading from Babel 5 to Babel 6, except in TypeScript.

**Comment by ai** [comment]
Sorry, I don‘t a TypeScript user at all. Maybe @jedmao can help?

**Comment by jedmao** [comment]
@kourge, do you know how to solve this? I've seen similar issues, but I'm not sure what the correct trendy is.

**Comment by kourge** [comment]
@jedmao, on a typings level, I believe if you `export = postcss` it does the right thing.

The problem most people have involves older versions of Babel (i.e. 5) treating `module.exports = m` as `module.export = {default: m}` when importing a module. Babel 6 no longer does this, and in a typeless environment this is not difficult to work around; simply `require('...').default` instead of `require('...')`. In TypeScript the declarations manifest as `export = m` versus `export default m`. Technically the `export = m` / `module.exports = m` way of exporting defaults is invalid under the ES6 spec if `m` does not have any enumerable properties, but realistically the ecosystem has continued to support this since single-function CommonJS modules are extremely popular.

**Comment by jedmao** [comment]
@kourge thanks for the in-depth explanation. I'm playing in the [TypeScript Playground](http://www.typescriptlang.org/play/) to see the generated output in both cases and this is what I'm getting:

### input
```ts
function postcss() {}
export = postcss;
```

### output
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    function postcss() { }
    return postcss;
});
```

### input
```ts
function postcss() {}
export default postcss;
```

### output
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    function postcss() { }
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.default = postcss;
});
```

Let me play around with this and see if I can fix my [typescript branch](https://github.com/jedmao/postcss/tree/typescript) to follow suit.

**Comment by jedmao** [comment]
@kourge, the TS compiler doesn't like it, because my compile target is `ES2015`.

![postcss-export-error](https://cloud.githubusercontent.com/assets/1058243/14546409/dbf5ed50-026a-11e6-9c30-ac8880cd08fe.png)

Feel free to submit a PR to my [typescript branch](https://github.com/jedmao/postcss/tree/typescript) that fixes the issue there; however, I haven't been using Node module resolution in my projects and so I haven't run into this issue (e.g., [`postcss-center`](https://github.com/jedmao/postcss-center)).

**Comment by kourge** [comment]
As long as the `postcss` entry point itself directly does `module.exports = f` where `f` is a function, the only way to model this with typings is `export =`. As it is, the purpose of the `"typings"` field in `package.json` is to make Node module resolution work and right now it is broken.

I wonder if this workaround can would work, say, in a theoretical `typings-specific.ts`:

```typescript
import postcss from './postcss';
export = postcss;
```

And have a second `tsconfig.json` file with `{declaration: true, target: "es5", files: ["typings-specific.ts"]}`?

**Comment by jedmao** [comment]
An ES5 target requires a lot of code modification as it stands now, unfortunately.

**Comment by ai** [comment]
Seems like problem is fixed, is’t it?
