### ISSUE TITLE
Solution for plugin node cache

### ISSUE THREAD

**Issue by ai** [postcss/postcss#790]
Right now plugins often add custom `_autoprefixerDisabledCache` properties to node’s objects. Of course, it looks dirty.

Maybe we need to add some unique `Node#id`. Plugins will be able to use this ID in local cache object:

```js
var cache = {};
…
cache[node.id] = myValue;
```

**Comment by delorge** [comment]
Shall this cache be avaiable as postcss.nodeCache or smth?

**Comment by ai** [comment]
@delorge I think that `.id` name is better, because this uniq ID could be used not only in caching. But I am open for use cases :).

**Comment by delorge** [comment]
> var cache = {};
> …
> cache[node.id] = myValue;

@ai as I can see, cache should be avaiable everywhere, am I correct? Or maybe we need to add get/set cache methods for Node class? To be honest I'm not really familiar with such use cases :)

**Comment by ai** [comment]
@delorge no it is private in-plugin cache. For example, Autoprefixer has some caches and this caches should be used only inside Autoprefixer.

**Comment by delorge** [comment]
@ai aye, got it. I have a solution but it breaks 30+ tests :D I guess that's is an issue as well, because tests expect harcoded values, hence I'm not sure how do I test random values (of course I do, but I need an advice how to do that right).

**Comment by ai** [comment]
@delorge what tests you talk about?

If you talk about `postcss-parser-tests`, I regenerate JSONs on PostCSS AST update :)

**Comment by delorge** [comment]
@ai I mean postcss unit tests. For example, one of node tests: 
```
test('toJSON() converts custom properties', t => {
    let root = new Root();
    root._cache = [1];
    root._hack = {
        toJSON() {
            return 'hack';
        }
    };
    t.deepEqual(root.toJSON(), {
        type:   'root',
        id: root.id,
        nodes:  [],
        raws:   { },
        _hack:  'hack',
        _cache: [1]
    });
});

root.id is my addition, because otherwise test fails.
```

**Comment by ai** [comment]
Don’t worry about them :D.

You can fix `parser` and `stringify` tests by adding `id` cleaning here https://github.com/postcss/postcss-parser-tests/blob/master/jsonify.js

**Comment by ai** [comment]
If you have same code. Could you test it in [benchmark](https://github.com/postcss/benchmark). It is important to not have lower performance.

**Comment by delorge** [comment]
@ai alright, I will check parser later, thank you :)

p.s. will try to test in benchmark as well

**Comment by delorge** [comment]
I tested node ids on benchmark with time-based IDs and random (encrypted) ones. I believe that it's impossible to generate unique ids in current  runtime process without performance loss. The question is: do we accept these losses or don't relay on IDs at all. 

here are my results I've got so far:

random IDs (average):


parsers: 
```
Mensch:                30 ms  (1.3 times faster)
CSSOM:                 35 ms  (1.1 times faster)
PostCSS:               40 ms
PostCSS with Node IDs: 79 ms  (2.0 times slower)
Rework:                94 ms  (2.3 times slower)
Stylecow:              108 ms (2.7 times slower)
Gonzales:              148 ms (3.7 times slower)
Gonzales PE:           164 ms (4.1 times slower)
```
prefixers:
```
Autoprefixer:               60 ms
Autoprefixer with Node IDs: 97 ms   (1.6 times slower)
Stylecow:                   322 ms  (5.3 times slower)
nib:                        681 ms  (11.3 times slower)
Compass:                    3099 ms (51.5 times slower)
```
preprocessors:
```
PostCSS:               68 ms
libsass:               69 ms   (1.0 times slower)
PostCSS with Node Ids: 111 ms  (1.6 times slower)
Rework:                123 ms  (1.8 times slower)
Less:                  269 ms  (3.9 times slower)
Stylecow:              408 ms  (6.0 times slower)
Stylus:                501 ms  (7.4 times slower)
Ruby Sass:             1310 ms (19.2 times slower)
```

time-based IDs (average):

parsers:
```
Mensch:                35 ms  (1.2 times faster)
CSSOM:                 41 ms  (1.0 times faster)
PostCSS:               41 ms
PostCSS with Node IDs: 48 ms  (1.2 times slower)
Rework:                73 ms  (1.8 times slower)
Stylecow:              127 ms (3.1 times slower)
Gonzales:              176 ms (4.3 times slower)
Gonzales PE:           202 ms (4.9 times slower)
```
prefixers:
```
Autoprefixer with Node IDs: 93 ms   (1.2 times slower)
Stylecow:                   364 ms  (4.7 times slower)
nib:                        873 ms  (11.3 times slower)
Compass:                    3887 ms (50.3 times slower)
```
preproccessors:
```
libsass:               80 ms   (1.0 times faster)
PostCSS:               81 ms
PostCSS with Node Ids: 93 ms   (1.1 times slower)
Rework:                145 ms  (1.8 times slower)
Stylecow:              447 ms  (5.5 times slower)
Less:                  479 ms  (5.9 times slower)
Stylus:                529 ms  (6.5 times slower)
Ruby Sass:             3740 ms (46.1 times slower)
```

As you can see, PostCSS with encrypted Node IDs is quite slow, but time-based IDs look promising (I've even had zero losses couple of times :D)  @ai what do you think?

**Comment by ai** [comment]
Yeap, time bases is better. But are you sure, that time is always unique?

**Comment by delorge** [comment]
For generating IDs I used [node-uuid](https://github.com/broofa/node-uuid) which guarantees unique ID, because it uses not only timestamp in generating process, so IDs should be fine even if they were produced at the exact same time

**Comment by ai** [comment]
Yeap, UUID is OK

**Comment by delorge** [comment]
alright, will make a PR for this one and for [paser](https://github.com/postcss/postcss-parser-tests) tonight.

**Comment by delorge** [comment]
well seems like some tests are still failing. shall I investigate this?

**Comment by delorge** [comment]
Node.toJson tests are still failing after parser update; I guess this method is being used before parser does its job. Should i change tests and make them expect ids in node objects or change toJson method?

**Comment by ai** [comment]
@delorge did you update `postcss-parser-tests` version in `package.json`?

**Comment by delorge** [comment]
@ai yes I did,  ~30 tests break before `postcss-parser-tests` update; 2 tests break after update

**Comment by delorge** [comment]
seems like `postcss-parser-tests` doesn't apply changes in this scenario

**Comment by ai** [comment]
@delorge I found way how to increase parsing performance, just lazy `id` on demand:

```js
    get id() {
        if ( !this.idCache ) {
            this.idCache = uuid.v1();
        }
        return this.idCache;
    }

    set id(id) {
        this.idCache = id;
    }
```

**Comment by ai** [comment]
But them I rewrite Autoprefixer for new cache and saw dramatic low performance:

```
Autoprefixer:     51 ms
Autoprefixer dev: 75 ms   (1.5 times slower)
Stylecow:         191 ms  (3.7 times slower)
nib:              454 ms  (8.9 times slower)
Compass:          2512 ms (49.2 times slower)
```

The idea was nice, but this trade off is bad. Let’s wait Symbols support :(.

**Comment by ai** [comment]
I will add extra commit to remove `id`, so your name will be in PostCSS history anyway. It was good experiment.

**Comment by delorge** [comment]
@ai well, as I mentioned above, managing unique IDs is expensive. But I didn't really expect such a poor performance of autoprefixer. The idea is good though, maybe symbols will work out. Don't forget to revert parser tests :)
