### ISSUE TITLE
potential mishandling of double colons

### ISSUE THREAD

**Issue by rymohr** [postcss/postcss#800]
I'm using postcss to drive a custom style layer for a project I'm working on. Within it we allow pseudo selectors to be assigned as values, such as:

```
a {
  one: :test;
}
```

I expected the above to parse just fine with `:test` as the value but instead I get a `Double colon` error.

Is there any way to work around this using plugins? Or would you be open to a PR that would correct this? 

https://github.com/postcss/postcss/blob/3ebf7aa321ccace722e51acfbd1f326d08e85833/test/parse.es6#L108

**Comment by ai** [comment]
This syntax is invalid CSS. Why you need this syntax and only any other symbol before `test`?

**Comment by rymohr** [comment]
Thanks, I'm aware of that. We use postcss to drive a custom style engine with a syntax nearly identical to CSS (we use style sheets to drive network visualizations in webgl, not DOM).  The default postcss parser plus a few plugins handles everything else just fine, so it would be a shame to have to fork it for such a minor issue.

For some context, the `:` is required because we have a custom `@settings` block that allows you to supply selectors as values within a declaration (in this case `:orphan` is a pseudo selector that selects all nodes without edges):

```
@settings {
  include: node, edge;
  ignore: :orphan;
}
``` 

To be clear, the only change I'm proposing is to not throw an error for `a { one: :test; }`. The existing test suite would still pass since `a { one:: test; }` would still throw.

**Comment by ai** [comment]
If you want to keep this syntax, you can just fork current parser and fix it for toot case (you can see a example in postcss-safe-parser).

**Comment by rymohr** [comment]
Thanks.  For now we just preprocess the source and replace any `: :` occurrences with a custom token that doesn't trip the error. Works for now but feels like a hack. It just isn't worth the effort to maintain a parallel fork for such a minor change.
