### ISSUE TITLE
walk and case sensitive

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss#803]
```js
root.walkAtRules("media", () => { })
```
not work with `@mEdIa` and `@MEDIA` (etc), but is is valid at-rule(in css all at-rules are case insensitive). In https://github.com/stylelint many of the rules begin in similar designs, but some users are using `UPPER` case and rule don't work. What are you doing guys? 
Also not parsed correctly `!iMpOrT` and `!IMPORT` (but it is also valid).

**Comment by ai** [comment]
You can use RegExp — `root.walkAtRules(/media/i, () => { })`

Maybe it is a issue in API design, but we can solve it only in major release.

**Comment by evilebottnawi** [comment]
@ai thanks for answer!
