### ISSUE TITLE
PostCSS always uses a custom parser after it's set once

### ISSUE THREAD

**Issue by matthew-dean** [postcss/postcss#804]
While integrating a custom parser, I noticed that PostCSS doesn't reset to the default parser even if it's not set as an option. Reduced example:

```
postcss([]).process(css, { parser: customParser });
postcss([]).process(css);  // Will still use customParser
```

**Comment by matthew-dean** [comment]
Until this is fixed, is there a short-term workaround? Is there an explicit "default" setting?

**Comment by ai** [comment]
O_o Hm, very strange. We have tests with differences parsers and they should fail if we have this mistake.

Try to set `syntax: postcss`. I will look at it after tomorrow.

**Comment by matthew-dean** [comment]
@ai In my case, I have two tests that return a Promise, and then am using a `Promise.all` for both tests (using the async processing method of PostCSS, despite my example). Therefore, the second test may start before the first one completes.

Just speaking hypothetically, if the PostCSS processor instance sets anything globally as far as parser (not local to the processor instance), then it would be possible for my test to fail but yours to succeed, if your tests are synchronous.

The only other thing I can think of is a test runner that starts a new JS thread for each test (like a command-line test runner?). That would also hide the issue I think.

**Comment by matthew-dean** [comment]
Or I could have made a mistake. It's possible something else is going on here.

**Comment by matthew-dean** [comment]
I did, in fact, make the mistake. [sad trombone] Sorry, closing.
