### ISSUE TITLE
Sourcemaps corruption (nested blocks?)

### ISSUE THREAD

**Issue by winamp** [postcss/postcss#814]
PostCSS affects mapping of sourcemaps, so it always points to the first line of the file.

Here is a sourcemap without autoprefixer:
![pure](https://cloud.githubusercontent.com/assets/996918/15555281/e416c554-227c-11e6-9cfe-7b8e217b21b6.png)
After autoprefixer was applied:
![autoprefixed](https://cloud.githubusercontent.com/assets/996918/15555280/e4164f20-227c-11e6-99c3-19e7b13f7e4f.png)

I've created a small setup https://github.com/winamp/autoprefixer-sourcemaps based on simplified stack we are currently using in our project. To utilize it, please run `npm install`, `gulp sass`, open files in html folder, inspect red Test.

**Comment by ai** [comment]
I am on this issue. Seems like problem is in merging Sass source map and Autoprefixer source map.

BTW, if you will use [PreCSS](https://github.com/jonathantneal/precss) you will not have any problem, because it uses same parser and AST as Autoprefixer ;).

Anyway I am still investigating

**Comment by ai** [comment]
Hm. Here is result:

1. [Autoprefixer’s origin source map](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvYXV0b3ByZWZpeGVkLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImF1dG9wcmVmaXhlZC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxpQ0FBaUM7RUFDakMsMEJBQTBCLEVBQUU7O0FBRTlCO0VBQ0UsbUJBQW1CO0VBQ25CLGtCQUFrQixFQUFFO0VBQ3BCO0lBQ0UsV0FBVyxFQUFFIiwiZmlsZSI6Ii4uL2F1dG9wcmVmaXhlZC5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyJib2R5IHtcbiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlZmVmZWY7IH1cblxuI2JvYXJkIHtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICB0ZXh0LWFsaWduOiByaWdodDsgfVxuICAjYm9hcmQgYSB7XG4gICAgY29sb3I6IHJlZDsgfVxuIl0sInNvdXJjZVJvb3QiOiIuLiJ9,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9Cg==)
2. [Sass source map](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvbWFpbi5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi4vbWFpbi5jc3MiLCJzb3VyY2VzIjpbIm1haW4uc2NzcyIsIl9iYXNlLnNjc3MiLCJfYm9hcmQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyJAaW1wb3J0ICdiYXNlJztcbkBpbXBvcnQgJ2JvYXJkJzsiLCJib2R5IHtcbiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7XG4gIGJhY2tncm91bmQtY29sb3I6ICNlZmVmZWY7XG59IiwiI2JvYXJkIHtcblx0cG9zaXRpb246IGFic29sdXRlO1xuXHR0ZXh0LWFsaWduOiByaWdodDtcblxuXHRhIHtcblx0XHRjb2xvcjogcmVkO1xuXHR9XG5cbn1cbiJdLCJtYXBwaW5ncyI6IkFDQUEsQUFBQSxJQUFJLENBQUM7RUFDSCxJQUFJLEVBQUUsMEJBQTJCO0VBQ2pDLGdCQUFnQixFQUFFLE9BQVEsR0FDM0I7O0FDSEQsQUFBQSxNQUFNLENBQUM7RUFDTixRQUFRLEVBQUUsUUFBUztFQUNuQixVQUFVLEVBQUUsS0FBTSxHQU1sQjtFQVJELEFBSUMsTUFKSyxDQUlMLENBQUMsQ0FBQztJQUNELEtBQUssRUFBRSxHQUFJLEdBQ1giLCJuYW1lcyI6W10sInNvdXJjZVJvb3QiOiIuLiJ9,QGltcG9ydCAnYmFzZSc7CkBpbXBvcnQgJ2JvYXJkJzs=,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsKfQ==,I2JvYXJkIHsKCXBvc2l0aW9uOiBhYnNvbHV0ZTsKCXRleHQtYWxpZ246IHJpZ2h0OwoKCWEgewoJCWNvbG9yOiByZWQ7Cgl9Cgp9Cg==)
3. [Result after merge](https://sokra.github.io/source-map-visualization/#base64,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsgfQoKI2JvYXJkIHsKICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgdGV4dC1hbGlnbjogcmlnaHQ7IH0KICAjYm9hcmQgYSB7CiAgICBjb2xvcjogcmVkOyB9CgovKiMgc291cmNlTWFwcGluZ1VSTD1tYXAvYXV0b3ByZWZpeGVkLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIl9iYXNlLnNjc3MiLCJfYm9hcmQuc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtFQUNFLGlDQUFpQztFQUNqQywwQkFBMEIsRUFDM0I7O0FDSEQ7RUFDQyxtQkFBbUI7RUFDbkIsa0JBQWtCLEVBTWxCO0VBUkQ7SUFLRSxXQUFXLEVBQ1giLCJmaWxlIjoiLi4vYXV0b3ByZWZpeGVkLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImJvZHkge1xuICBmb250OiAxMDAlIEhlbHZldGljYSwgc2Fucy1zZXJpZjtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjtcbn0iLCIjYm9hcmQge1xuXHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdHRleHQtYWxpZ246IHJpZ2h0O1xuXG5cdGEge1xuXHRcdGNvbG9yOiByZWQ7XG5cdH1cblxufVxuIl0sInNvdXJjZVJvb3QiOiIuLiJ9,Ym9keSB7CiAgZm9udDogMTAwJSBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7CiAgYmFja2dyb3VuZC1jb2xvcjogI2VmZWZlZjsKfQ==,I2JvYXJkIHsKCXBvc2l0aW9uOiBhYnNvbHV0ZTsKCXRleHQtYWxpZ246IHJpZ2h0OwoKCWEgewoJCWNvbG9yOiByZWQ7Cgl9Cgp9Cg==)

**Comment by ai** [comment]
Main problem is that source map merging code is not in PostCSS. I just uses [mozilla source map](https://github.com/mozilla/source-map) tool. So I really have no idea why it doesn‘t merge this maps.

I will create a issue there and provide all technical info that I have. But it is all that I can do on current step.

**Comment by ai** [comment]
I created issue in `source-map` https://github.com/mozilla/source-map/issues/242

I hope they will fix it soon.

If you want quick fix and your project is small you could move to PostCSS-only solution — it will not have any of this problem. One AST is always better than two ;).

**Comment by winamp** [comment]
Thanks a lot Andrey!
