### ISSUE TITLE
Running postcss in the browser

### ISSUE THREAD

**Issue by matsko** [postcss/postcss#830]
Hey guys.

Do you guys have an implementation in place for running postcss in the browser? Is there anything that prevents you guys from making it work in JavaScript on a browser without node? I did some work setting up rollup UMD bundles and it works somewhat, but it would be great if the NPM package included a bundled file that can be used directly in the browser.

**Comment by ai** [comment]
If you want to process CSS in string in browser, just use `browserify` or `webpack` to pack npm modules of `postcss` and PostCSS plugins to bundle.

PostCSS don’t need node.js API to process CSS string (it loads `fs` module, but webpack/browserify have a nice hack for it).

**Comment by ai** [comment]
But you need to make bundle by your own. There are 2 reasons:

1. npm community should really think about npm packages sizes. Having a pack in npm package will increase package size to 3-4 times.
2. Anyway you need bundles not only for PostCSS core itself, but also for plugins. So anyway you will use browserify/webpack to packe PostCSS core with PostCSS plugins.

**Comment by peterbarraud** [comment]
Has anyone tried the [browserify-postcss](https://www.npmjs.com/package/browserify-postcss) tranform?

**Comment by damsorian** [comment]
is there any example for do this?

**Comment by AngeIII** [comment]
node_modules/postcss-functions/dist/index.js
Critical dependency: the request of a dependency is an expression
```
plugin = require('postcss').plugin
export default plugin('postcss-functions', (opts = {}) => {
```

for webpack and to run this in browser it needs to be a plain class/object/function.

**Comment by trusktr** [comment]
This technique could be useful for making polyfills. It'd be neat to show proofs of concept on codepen of features like CSS Nesting, for example. It'd need some glue code in order to automatically transform `<style>` and `<link>` tags, etc.

**Comment by ai** [comment]
@trusktr why you can transform CSS Nested once in the server during the deploy?

**Comment by trusktr** [comment]
@ai Yeah I'd do that for a production app. But I mean, for example, polyfilling for protptypes, or for JSFiddle examples, etc, non-production stuff.

**Comment by ai** [comment]
Since JSFiddle is a rare case they can use bundlers and Babel to make PostCSS runnable in the browser

**Comment by trusktr** [comment]
This would be convenient in small demos, prototypes, etc, anywhere static HTML works:

```html
<script src="cssnext-polyfill.js"></script>

<style>
  @custom-selector :--button button, .btn;
  .foo {
    color: skyblue;
    & :--button {
      padding: 5px;
    }
  }
</style>
```

**Comment by ai** [comment]
I think it is rare case to create a special system for it. Especially nowadays, when React developers always use builders and CSS developers do not like any JS file for CSS.

**Comment by trusktr** [comment]
Yeah, it is rare for applications. But I do find my self in situations where I want to show simple demos, and setting up a build system is often too much work. I may have a go at this sometime.

**Comment by ai** [comment]
There is no internal limits, which block you from using PostCSS in this case

**Comment by bbugh** [comment]
I'm trying to use postcss in the browser as well, but it seems to use `path` and is breaking. 😞

e.g. https://github.com/postcss/postcss/blob/master/lib/input.es6

Has anyone made this work? 

```js
import postcss from 'postcss'
```

**Comment by ifiokjr** [comment]
@bbugh you can use `jspm`.

```ts
import postcss from 'https://jspm.dev/postcss@8.1.10';
import autoprefixer from 'https://jspm.dev/autoprefixer@10.0.2'

const css = `
blockquote {
    border-left: 2px solid #ddd;
    margin-left: 0;
    margin-right: 0;
    padding-left: 10px;
    font-style: italic;
  }
  blockquote p {
    color: #888;
  }
`

postcss([autoprefixer]).process(css).then(value => console.log(value.css))
```

You can see it in this [codepen](https://codepen.io/ifiokjr/pen/qBNeQzO).

**Comment by fatlard1993** [comment]
I wanted something that worked with vite and that didn't rely on CDN imports. It took some finesse, but the jspm tip from @ifiokjr was the hint that I needed. What I ended up with was:

vite.config.js
```
...
import { defineConfig } from 'vite';

export default defineConfig({
	define: {
		'process.env': {},
	},
	resolve: {
		alias: {
			path: 'node_modules/@jspm/core/nodelibs/browser/path.js',
			url: 'node_modules/@jspm/core/nodelibs/browser/url.js',
			fs: 'node_modules/@jspm/core/nodelibs/browser/fs.js',
			'source-map-js': 'node_modules/source-map-js/source-map.js',
		},
	},
...
});
...
```

package.json
```
{
...
  "dependencies": {
...
    "@jspm/core": "github:jspm/core",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.19",
    "postcss-nested": "^6.0.0",
    "source-map-js": "^1.0.2"
...
  },
...
}
```

implementation
```
import postcss from 'postcss';
import plugin_autoprefixer from 'autoprefixer';
import plugin_nested from 'postcss-nested';
...
postcss([plugin_nested, plugin_autoprefixer])
  .process(cssInput, { from: undefined })
  .then(({ css }) => {
...
});
...
```

**Comment by shellscape** [comment]
Was able to make this work in vite by using the following config:

```
    alias: {
      path: 'path-browserify',
      postcss: 'https://jspm.dev/postcss@8.4.31',
      'postcss-css-variables': 'https://jspm.dev/postcss-css-variables@0.19.0'
    }
```

You'll want to alias any additional plugins you're using as well.
