### ISSUE TITLE
api.postcss.org/Container.html 404

### ISSUE THREAD

**Issue by mmmveggies** [postcss/postcss#835]
Several references are made to `Container` throughout the API docs.
These attempt to link to [/Container.html](http://api.postcss.org/Container.html), which does not exist. 

[/container.es6.html](http://api.postcss.org/Container.html/container.es6.html) exists but it is just the source without generated docs.

**Comment by mmmveggies** [comment]
This is also a problem with http://api.postcss.org/Node.html

**Comment by ai** [comment]
Thanks. Yeap, this is JSDoc problem, I don't know how to fix it. We will fix it in custom API page

**Comment by ai** [comment]
I will close it because it is `postcss.org` issue
