### ISSUE TITLE
A whishlist for independent postcss tools?

### ISSUE THREAD

**Issue by dryoma** [postcss/postcss#844]
On the **Writing a PostCSS Plugin** page there is [a list of tools](https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md#tools) that seem to be quite independent on PostCSS and can be used without it. E.g., [postcss-selector-parser](https://github.com/postcss/postcss-selector-parser) and [postcss-value-parser](https://github.com/TrySound/postcss-value-parser) are actively used in [stylelint](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#write-the-rule).

My questions would be does `postcss-` prefix in those tools names bear some special meaning (considering their independent nature)? Are they maybe used in some special manner, or intended to be used, like in incorporating into PostCSS? And is there, then, any kind of requirements/a whishlist for functionality of such tools to be part?

The thing is I am going to release a similar tool for parsing CSS media query lists. And I'm wondering if there is some functionality that I'd better add to the parser beforehand.

Thanks.

**Comment by ai** [comment]
`postcss-` prefix is recommended prefix for all PostCSS plugins and tools. But there is no any special naming for tools.

**Comment by dryoma** [comment]
Let me than ask it this way: what is a PostCSS tool? I.e. what tools are recommended to have this prefix, is there a judgement like "this tool does X and Y, so it can be called a PostCSS tool" or "this tool does X, but to calls itself a PostCSS tool it should also do Y"?

**Comment by ai** [comment]
Tool is a library that you use to work with PostCSS AST. Or, in other words, tools is a library that you use in PostCSS plugin.

**Comment by dryoma** [comment]
Ok, got it, thanks.
