### ISSUE TITLE
Comments within a value list are ignored

### ISSUE THREAD

**Issue by Nirazul** [postcss/postcss#845]
It seems that postcss ignores inline comments within value lists when parsing for example this css:

```
b {
  color: #000, /* comment */ #FFF;
}
```

Here's an ast example provided by m-allanson:
https://astexplorer.net/#/6DZiWrYrxa/1/

This leads to ignored `disable-line` comments in the latest version of `stylelint`. See [this issue](https://github.com/stylelint/stylelint/issues/1628) for more details.

**Comment by ai** [comment]
PostCSS cleans values from comments by design. You can get origin value in `node.raws`.

Maybe it is not best way and we should change it in 6.0.

**Comment by dryoma** [comment]
> Maybe it is not best way and we should change it in 6.0.
Thumbs up for that, will be a big help for linting tools!

**Comment by ogonkov** [comment]
Is there task to return support of comments within selectors @ai?

**Comment by ai** [comment]
@ogonkov what support do you mean?

**Comment by ogonkov** [comment]
I mean ability  to use comments a la`stylelint-disable-line`

**Comment by ai** [comment]
@ogonkov can you show example?

**Comment by ogonkov** [comment]
This one stylelint/stylelint#1628

(sorry, just realized that i post to wrong project)
