### ISSUE TITLE
Mention postcss-less and postcss-scss parsers in parse error

### ISSUE THREAD

**Issue by ai** [postcss/postcss#856]
Many users forget to change parser and complain about parse error.

Maybe we should add mention `postcss-scss` or `postcss-less` if we see that `opts.from` has `.scss` or `.less` extension.

We could release it in 5.1.2.

@davidtheclark @jeddy3 it will be useful for you?

**Comment by davidtheclark** [comment]
Sounds like a good idea to me!

In stylelint we started automatically setting the syntax based on extension, because of all the people who were forgetting. But we already have the syntax installed. Postcss itself can just point you to the syntax you may need.

**Comment by ai** [comment]
@davidtheclark some users use `gulp-postcss` or `postcss-loader` to run Stylus and they have same issue.

**Comment by jeddy3** [comment]
> Sounds like a good idea to me!

Agreed.

Mentioning `postcss-scss`, `postcss-less` or `sugarss`when the extension is `scss`, `less` or `sss` would be helpful for anyone still using stylelint as a PostCSS plugin. As @davidtheclark said, stylelint automatically sets the extensions for using using the CLI or Node API, which also covering anyone using `stylelint` task runner plugins like `gulp-stylelint` and `grunt-stylelint`.

**Comment by ai** [comment]
Done a9f41e7

@davidtheclark @jeddy3 is it OK? Especially my English in error message :D.

**Comment by ai** [comment]
Release in 5.1.2

**Comment by davidtheclark** [comment]
👍

**Comment by jeddy3** [comment]
LGTM
