### ISSUE TITLE
glob pattern string required

### ISSUE THREAD

**Issue by maliyshock** [postcss/postcss#857]
Hey everyone. Have this issue on my windows system. This issue does not apper on nix - based systems.

I`ve installed postcss and postcss-cli, cause i need to run npm scripts from terminal.
So, my package.json looks like this http://joxi.ru/4AkvbE1fMzeaj2
U can see the error on screenshot higher.
When i remove this part "| postcss --use autoprefixer --autoprefixer.browsers 'last 2 versions'" - all is work fine, but without autoprefixier - so this is sad. Can u help me with that?

**Comment by ai** [comment]
Please, open issue in postcss-cli
https://github.com/postcss/postcss-cli
