### ISSUE TITLE
Давайте добавим в вебпак возможность передавать AST из PostCSS по цепочке лоадеров?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [postcss/postcss#864]
I apologize for my Russian...

Прошу прощения что на русском, просто такое через переводчик не перевести =)

Давайте создадим тикет в репозитории вебпака, для того, чтобы лоадеры могли передавать, помимо соурс мепов, какую то другую служебную информацию, которая возможно приигодится следующим лоадерам в цепочке. Как вам такой подход, а?)

Тогда бы например лоадеры, использующие PostCSS могли бы возвращать что-то типа

```javascript
var code = ast.toCss() // я не знаю какой у вас апи просто
callback(code, map, ast) // и дополнительно можно передать служебную инфу
```

а следующий по цепочке лоадер бы получал аргументы:

```javascript
function loader(code, map, ast){}
```

либо же сделать проще, чтобы была возможность просто брать и передавать прям любой обьект а не только строку
```javascript
callback(ast)
```
Но тогда надо придумать какой то механизхм совместимости с уже существующими лоадерами, которые ожидают строку на входе. (и если там прилетит обьект то не факт что они вызовут у него например obj.toString() )

**Comment by ai** [comment]
А что будет, если посредине лоадер изменит код, но не обновит AST?

**Comment by uMaxmaxmaximus** [comment]
> А что будет, если посредине лоадер изменит код, но не обновит AST?
Я слегка обновил пост, я думаю что код вообще передавать не нужно. Нужно передавать либо строку либо обьект имеющий метод `toString()`, и лоадеры должны знать что если им нужна просто строка то у первого аргумента они должны вызвать toString() а если же они могут обработать какой

**Comment by ai** [comment]
Да, можно попробовать поговорить с командой вебпака. Создавай issue.

**Comment by uMaxmaxmaximus** [comment]
Не обязательно с ними разговаривать, я просто напишу сам и скину им реквест)

**Comment by uMaxmaxmaximus** [comment]
@ai слушай, вопрос, компиляция ast в соурсмэп, и в css код это дорогая операция?

**Comment by uMaxmaxmaximus** [comment]
вот гляди, придумал механизм обратной совместимости:

Если лоадер ожидает третий аргумент (определяется как func.length > 2)
Тогда мы просто передаем ему этот аргумент (ast в нашем случае), если же лоадер ожидает всего 2 аргумента, то тогда мы вызываем функцию обработчик, которая генерирует нам массив из мэпа и скомпилированной строки. Выглядит признаться убого, но я пока еще думаю.

```javascript
function PostCSS(code, map) {

	this.callback(ast, function () {
		return [ast.toCss(), ast.createMap()]
	})

}


function PostCSSBro(code, map, ast) {

}


function normalLoader(code, map) {

}
```

**Comment by uMaxmaxmaximus** [comment]
@ai 

во, я придумал, надо просто текущему лоадеру дать доступ к следующему лоадеру, элементарно =)

```javascript
function PostCSS(code, map) {

	if (this.nextLoader.length === 3) {
		this.callback(ast)
	}
	else {
		this.callback(ast.toCss(), ast.toMap())
	}

}
```

**Comment by ai** [comment]
Да, но обсуди с ребятами из вебпака ;). Там очень много хитростей внутри — может это не будет работать, например, с кешами.

**Comment by uMaxmaxmaximus** [comment]
А, ну да. точно.

**Comment by uMaxmaxmaximus** [comment]
> Да, но обсуди с ребятами из вебпака
Может ты обсудишь? А то у меня траблы с английским а сложные предложения приходится упрощать и получается бред. Или у тебя время нет на такое? (

Как раз бы вам пригодилась такая фишка с передачей ast, раз вебпак так популярен.

**Comment by ai** [comment]
Я сейчас брату показываю Россию — не смогу :(.

Но ты начни, там нейтивов мало. Просто чаще используй примеры кода, чтобы показать.
