### ISSUE TITLE
[Help needed] Requiring a module to be executed with webpack loaders within plugin

### ISSUE THREAD

**Issue by yachaka** [postcss/postcss#867]
Hi,

I'm currently writing a plugin that imports all vars from a JS file and insert them as LESS variables on top of the CSS file.

The goal is to do `@import './vars.js';` in my CSS file and to have all the variables from the JS file included as `$var: value;`.

I'm having trouble actually requiring the JS with it being parsed by webpack ; like with ES6 support, etc.

Here is my current code :
`MyPlugin.js`
```js
const postcss = require('postcss');

module.exports = postcss.plugin('postcss-js-to-less-vars', (options = {
  require: () => {}
}) => {
    return css => {

        css.walkAtRules(rule => {
            if (rule.name === 'vars') {
                options.require(rule.params.substr(1, rule.params.length - 2), (module) => {
                  module = module.default || module

                  for (var k in module) {
                    css.prepend(`@${k}: ${module[k]}`)
                  }
                  rule.removeSelf()
                  
                })
            }
        })

    }
})
```

`webpack.config.js`
```js
  postcss: (webpack) => [
    postcssJsToLessVars({
      require: (req, cb) => {
        let path = webpack.resolve(webpack.context, req, (err, result) => {
          cb(require(result))
        })
      }
    }),
  ]
```
The above code does require the module but doesn't execute it through webpack configured loaders - which is what I want to achieve, ultimately.

Any help would be really appreciated ! 😄

**Comment by yachaka** [comment]
For anyone wondering, I've settled on using es5 for theses modules.  ¯\_(ツ)_/¯

**Comment by ai** [comment]
Sorry, this question is for webpack ;).

I think webpack is too complicated and it is good example of problems from complicated API ;)

**Comment by ai** [comment]
I use Gulp and have no good experience with webpack

**Comment by yachaka** [comment]
Webpack has a really complicated API, that's for sure.
I'm pretty sure nobody really gets it.
Thanks anyways !

**Comment by michael-ciniawsky** [comment]
@yachaka does it work that way? Maybe there is something coming up in regard of using es6 template literals and node's vm to use js templating for similiar proposes, but more generic, the problem is that examples with webpack (or any specific build tool) + postcss complicates to grasp the bits needed from the sole postcss side of affairs.

**Comment by yachaka** [comment]
@michael-ciniawsky As @ai correctly mentioned, this is more of a Webpack issue. You're right though, Webpack code does obliterate the understanding at first sight.
