### ISSUE TITLE
Processor instance doesn't include parser

### ISSUE THREAD

**Issue by GarthDB** [postcss/postcss#871]
If I wanted to reuse a processor it has the plugins, but it doesn't include the parser.

I could recreate the same processor by passing the same options through, but it seems like the parser is just as integral a part of the processor instance as the plugins, maybe more so.

Chatting with @ben-eb in the gitter - he brought up remarks' [api](https://github.com/wooorm/remark/tree/master/packages/remark#usage). It is well documented in [unified](https://github.com/wooorm/unified#table-of-contents).

**Comment by ai** [comment]
Hm, strange. The only way to set parser is options.

**Comment by GarthDB** [comment]
@ai - it might work to implement [Unified](https://github.com/wooorm/unified) to handle the parser and plugin loading.

**Comment by ai** [comment]
What do you mean?

**Comment by ai** [comment]
What do you use to run PostCSS? gulp-postcss/postcss-cli/postcss-loader?

**Comment by GarthDB** [comment]
With what I'm building I'm using the JavaScript API.

**Comment by tunnckoCore** [comment]
I also starting to think that `unified` would be the best way to go for these 4 projects - @postjson, @poscss, @posthtml and @reshape. Another one can be @postcore when finish it (it's 90% ready and it's working).

**Comment by ai** [comment]
Idea of global standard for AST-tools is nice, but Unified’s AST basis is not the best. @ben-eb told that in event based API we need something more Babel-like. Idea of separated `node` and `position` is nice.

But I love the idea of some global API standard across Babel, PostCSS and other tools. Maybe we could discuss this standard?

**Comment by wooorm** [comment]
> **Disclaimer: I’m biased.**

I’m all for unified. 😉 👍 I’ve thought a lot about creating processors with retext/remark/* and unified works well. I don’t know too much about PostCSS and the likes though.

> but Unified’s AST basis is not the best

That’s not entirely true.

a) [unified](https://github.com/wooorm/unified) is separate from [Unist](https://github.com/wooorm/unist): you can use any syntax tree you like (at least it should work, but is untested).

b) Unist defines that nodes must have a `type`. All other stuff is optional.
I *really* suggest using `value: string` for text nodes, `children: Array.<Node>` for parents, and `position: {start: {line, column, offset}, end: {line, column, offset}}` though. You don’t have to, but it works in my experience.

Finally, by using these properties, you get [these](https://github.com/wooorm/unist#list-of-utilities) helpers with it for free! 🎈

**Comment by ai** [comment]
@wooorm hi, awesome projects!

1. What is Unified without Unist?
2. I one hand I love pain JS objects. In other hand DOM-like API is very good for new developers. For example, Stylelint rules show be written by developer with any qualification. What you thoughts about it?
3. What do you think about Babel visitor API? It is good to combine all plugins to work in one loop instead of looping separated in every plugin.

**Comment by wooorm** [comment]
@ai <3

> 1. What is Unified without Unist?

unified is everything non-node: the plugin management (`.use`), processing stages (`.process`, `.parse`, `.run`, `.stringify`), constructing new processors, etc. Aside: there’s also helpers to create [“engines”](https://github.com/wooorm/unified-engine#projects) around processors, so you can create gulp-, grunt-, or atom- plugins, or CLIs, without much code.

> 2. I one hand I love pain JS objects. In other hand DOM-like API is very good for new developers. For example, Stylelint rules show be written by developer with any qualification. What you thoughts about it?

I initially started with an object model in retext: TextOM (old version can be seen [here](https://github.com/wooorm/textom/tree/b9adc8a347fb35d974a9dfb08988cf1989b41558)). I used to think similarity to the DOM would make it easier too, but I now think the inverse: everyone knows JSON objects, beginners know how to `.push` to a list of nodes, iterate over them, `.splice` from them, etc. The DOM is easy, but JSON is easier!

The difference is that, in PostCSS the helpers are on nodes: `node.append(child)`, in Unist the utilities are published on npm (or wherever): `append(node, child)`.

P.S. Unist doesn’t require nodes to be plain vanilla objects: they can be instances just as well.

P.P.S. Some examples, quite similar to Stylelint: [this one from `awesome-lint`](https://github.com/sindresorhus/awesome-lint/blob/master/rules/badge.js), which isn’t the easiest to do, but still quite readable I think. Another example is [this one from the `remark-lint` docs](https://github.com/wooorm/remark-lint/blob/master/doc/external.md#creating-external-rules).

> 3. What do you think about Babel visitor API? It is good to combine all plugins to work in one loop instead of looping separated in every plugin.

Really cool! I haven’t run into performance yet, remark/retext/* aren’t as big as PostCSS / Babel.
But, there should definitely be a plugin to do that. I think it could be entirely opt-in and based on external projects.

**Comment by ai** [comment]
@wooorm I like the idea about engines. Where I can read about them and about your plugin API?

What do you think about `parent` node in AST?

Other question, how to make a validations? For example, to prevent user from setting integer to string value?

**Comment by wooorm** [comment]
> I like the idea about engines. Where I can read about them and about your plugin API?

The plug-in API is described in [“processor.use”](https://github.com/wooorm/unified#processoruseplugin-options) (read the section on attachers and transformers too). “transformers” are run by [trough](https://github.com/wooorm/trough), so they can return values, return promises, accept a `next` callback, etc.

More on the engine is in its [readme](https://github.com/wooorm/unified-engine). The engine passes another value to plugins, a [`fileSet`](https://github.com/wooorm/unified-engine/blob/master/doc/plug-ins.md). I haven’t needed it much though, so if there’s something PostCSS needs / anyone needs we should discuss that 👌 

> What do you think about parent node in AST?

In TextOM we had those too. In my opinion they aren’t useful very often (in remark/retext at least), and if you need them you can use [`visit-parents`](https://github.com/wooorm/unist-util-visit-parents#visitparentsnode-type-visitor) which passes a list of all parents to the visitor. Also: they’re hard to keep up to date!

> Other question, how to make a validations? For example, to prevent user from setting integer to string value?

Currently, I don’t really do that. In my opinion, in a loose language like JavaScript, you should just go with the flow and try to accept as many “wrong” values as possible and coerce them to things you do understand.
Also: it’s a development thing right, something that may need to be there in tests, but not really when published to npm. I’ve created some [assertion](https://github.com/wooorm/unist-util-assert) libraries which test the tree, so those could be used

**Comment by ai** [comment]
The origin `processor` issue was resolved
