### ISSUE TITLE
Attributes selectors with unquoted semicolon throw error

### ISSUE THREAD

**Issue by eramdam** [postcss/postcss#876]
Selectors such as `[attr=;]` return the following error when PostCSS parses the CSS input.

`<css input>:7:1: Unknown word`

Even though this selector is valid and correctly parsed by `postcss-selector-parser` itself.

**Comment by ai** [comment]
I will try to look at it on this weekend. Feel free to ping me on next Friday again if I will forget.

**Comment by ai** [comment]
Fixed dacd392

**Comment by ai** [comment]
Sorry, it will be released only in 5.2, because it introduces new token.

You can use `postcss-safe-parser` until release.

**Comment by eramdam** [comment]
@ai when is 5.2 planned? If there's a planning. I can wait a little 😊  

(Thanks for the quickfix though! 👍  )

**Comment by ai** [comment]
I try to release it on this weekend, but maybe it could take a week.

**Comment by eramdam** [comment]
I can definitely wait :)

**Comment by ai** [comment]
Released in 5.2.
