### ISSUE TITLE
Syntax error in API documentation for 'walkRules'

### ISSUE THREAD

**Issue by alexlibby** [postcss/postcss#878]
Hi - I've spotted what I think may be a syntax error in the API docs example for walkRules:

Take a look at http://api.postcss.org/AtRule.html#walkRules - there is a back tick in the console.log statement, where it should otherwise be a single quote:
```
root.walkRules(rule => {
  selectors.push(rule.selector);
});
console.log(`Your CSS uses ${selectors.length} selectors');
```
On a related point - when the back tick is changed, I get this:
![image](https://cloud.githubusercontent.com/assets/16504949/18230488/a623d1a2-7294-11e6-9650-69ec985b9bdf.png)
Whilst I appreciate it is only meant to be a simple example, it might be better if it could actually show something like this:
```
Your CSS uses 3 selectors
```
..or similar, so those new to parsing CSS through an AST can understand how it works? The above example came from the AST Explorer session set up for PostCSS at http://astexplorer.net/#/np0DfVT78g/1 - either the code needs to be changed, or the docs amended to indicate how it should if we use a placeholder in our code?

**Comment by ai** [comment]
1. Oops, second symbol must be back tick too. Fixed 652883d. Thanks for notice.
2. Back tick string could not work in Console, because it is ES6 feature https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
