### ISSUE TITLE
Incorrect position on minified css with sourcemaps

### ISSUE THREAD

**Issue by roose** [postcss/postcss#882]
In Firefox devtools on inspect `body` I see `base.css:3` not `header.css:3`.
If styles not minified all ok, in Chrome devtools all ok in both case.
If I add custom selector e.g. `.nothing {color:#000}` in the top of `header.css` Firefox shown: `header.css:1`, but really selector on position 2.

Windows 10
nodejs v6.2.2
gulp v3.9.1

Gulp task:

``` js
gulp.task('css', () => {
  const processors = [
    precss(),
    autoprefixer({browsers: ['last 2 versions']}),
    csswring
  ];
  return gulp.src('src/css/main.css')
    .pipe($.sourcemaps.init())
    .pipe($.postcss(processors))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('dist/css'))
});
```

main:css:

``` css
$blue: #056ef0;
@import "base.css";
@import "parts/header.css";
```

base.css:

``` css
a {
  color: $blue;
}
```

header.css:

``` css
body {
  background: $blue;
}
```

**Comment by ai** [comment]
Could you create some test project?

**Comment by roose** [comment]
@ai done, https://github.com/roose/postcss-test

**Comment by bcole808** [comment]
+1, I am having a similar problem. 

I use grunt-sass to first compile our SCSS into CSS files, then I use grunt-postcss to do autoprefixer and cssnano and I have noticed that:

- Sourcemaps output from just grunt-sass have correct line numbers
- Sourcemaps output from grunt-postcss often have incorrect line numbers, like 1

This is basically my configuration in grunt:

```
sass: {
    options: {
        sourceMap: true,
        outputStyle: 'compact',
        includePaths: ['assets/styles']
    },
    dist: {
        files: {
            'assets/main.min.css' : 'assets/styles/main.scss',
        }
    }
},

 postcss: {
    options: {
        map: true,
        processors: [
            require('autoprefixer')({
                browsers: ['last 4 versions']
            }),
            require('cssnano')()
        ]
    },
    dist: {
        src: ['assets/*.css']
    }
},
```

**Comment by ai** [comment]
Sorry, I will take a look on it only in the end of January. Feel free to look into PostCSS code if you need fix faster.

**Comment by jonathantneal** [comment]
@roose, thanks for sharing [an isolated example](https://github.com/roose/postcss-test) of your issue. I was able to replicate this in Firefox. Very curious.

I narrowed it down to the `precss` plugin you are using. When I swap that out for `postcss-import`, the source maps are correct in Firefox. I then double confirmed this by identifying a difference in the `mappings` field of the sourcemap. Good news; your issue is unrelated to PostCSS, itself.

@bcole808, if you are able to produce a similar example, I will gladly look into it. Are you using any PostCSS plugins besides `autoprefixer` and `cssnano`?

**Comment by bcole808** [comment]
Thanks for helping look into this, @jonathantneal!

I re-created the issue for you to see here: 
https://github.com/bcole808/postcss-examples/commit/db5516b488d4130101480218c5a38c55d5f2b73f

And here is a quick video illustrating the problem: 
http://www.bencole.net/s/2017-01-03_13-11-25.mp4 

You can see in the video that I inspect the color of the link to see where the `color:red` property is being set. When I run just `grunt sass`, the sourcemap points to line 5 of box.scss (correct line), but when I run `grunt postcss` suddenly it points to line 1 of box.scss (wrong line).

**Comment by ai** [comment]
Yeap. Issue is unrelated to PostCSS. [Source maps](https://sokra.github.io/source-map-visualization/#base64,cHtjb2xvcjojZmZmfWJvZHl7YmFja2dyb3VuZC1jb2xvcjojMDAwfQovKiMgc291cmNlTWFwcGluZ1VSTD1tYWluLmNzcy5tYXAgKi8K,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImJhc2UuY3NzIiwiaGVhZGVyLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxFQUNFLFVBQVksQ0FDYixBQ0ZELEtBQ0UscUJBQXVCLENBQ3hCIiwiZmlsZSI6Im1haW4uY3NzIiwic291cmNlc0NvbnRlbnQiOlsicCB7XG4gIGNvbG9yOiAjZmZmO1xufVxuIiwiYm9keSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICMwMDA7XG59XG4iXX0=,cCB7CiAgY29sb3I6ICNmZmY7Cn0K,Ym9keSB7CiAgYmFja2dyb3VuZC1jb2xvcjogIzAwMDsKfQo=) looks good.
