### ISSUE TITLE
Postcss parser issue

### ISSUE THREAD

**Issue by maliyshock** [postcss/postcss#902]
In package json i have this modules and dependencies
```
"autoprefixer": "^6.3.6",
"clean-css": "^3.4.12",
"node-sass": "^3.7.0",
"nodemon": "^1.10.0",
"postcss": "^5.0.21",
"postcss-cli": "^2.5.2"
```

The full version looks like this
````
{
  "name": "",
  "description": "",
  "devDependencies": {
    "autoprefixer": "^6.5.0",
    "clean-css": "^3.4.12",
    "easy-svg-store": "^1.0.7",
    "node-sass": "^3.7.0",
    "nodemon": "^1.10.2",
    "postcss": "^5.2.3",
    "postcss-cli": "^2.5.2",
    "requirejs": "^2.2.0",
    "uglifyjs": "^2.4.10"
  },
  "scripts": {
    "r": "r.js -o public/build.js",
    "min": "uglifyjs -c drop_console=true,warnings=false -m -- public/js/buildjs/main.js > public/js/buildjs/main.build.js",
    "build": "npm run r && npm run min",
    "sass": "npm run sass:table && npm run sass:cabinet && npm run sass:mob npm run sass:min",
    "sass:min": "./markup/bin/general/min",
    "sass:table": "./markup/bin/layouts/table-layout/compile",
    "sass:cabinet": "./markup/bin/layouts/cabinet-layout/compile",
    "sass:mob": "./markup/bin/layouts/mobile-layout/compile && npm run sass:min",
    "watch:mob": "./markup/bin/layouts/mobile-layout/watch",
    "esvgs": "esvgs --sprite-name svgstore --input markup/svg --output public/svg --html"
  }
}
```

So, when i run "npm run sass" postcss drops with error, that says "bracket unclosed" or "unknown word". My code is valid. I check them several times with different validators and services. 
If i remove postcss module from build chain - all work fine, but without postcss i lost autoprefixier that i needed.

After few days i found out a solution: 
- remove all modules from npm module
- remove "^" signs from packaje.json 
- make npm install - all works fine.

I think the problem exist in postss module higher then 5.0.21 version, or may be it is just unhappy combo vombo of versions and modules that happend with me.

**Comment by ai** [comment]
Could you please show real stacktrace with input CSS example?

“Something was wrong” and then I fixed it somehow is not a good issue report ;).

**Comment by maliyshock** [comment]
http://joxi.ru/DmBnpRduNX4xOm
Output css is clear cause errors.

I know that is not good. But i don`t have any ideas whats wrong. And it is better then nothing.
I reproduce that situation on other machines with that package json

And i cant give you more examples, cause it is exist product.

Try it on your own code, with big scss files, and im sure u can reproduse that.

Input scss - the code is fine
`.table{
  color: #000;
  width: 100%;
  text-align: left;
  font-size: 13px;
  min-width: 710px;

  & th{
    font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
    font-size: 12px;
    color: $th;
    background-color: $cabinet;
    font-weight: 600;
    padding: 18px 10px;
    vertical-align: middle;
    position: relative;

    &:first-child{
      padding-left: $table-paddings;

      & .table__sort-link{
        margin-left: 41px;
      }
    }

    &:last-child{
      padding-right: $table-paddings;
    }
  }

  & td{
    font-weight: 300;
    font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
    padding: 18px 10px;
    position: relative;

    &:first-child{
      padding-left: $table-paddings;
    }

    &:last-child{
      padding-right: $table-paddings;
    }
  }

  a{
    color: $link;
    text-decoration: none;
  }

  & .table__title {
    color: #000;
  }
}

.table--monochrome{
  & tr:nth-child(n) td{
    background-color: transparent;
  }
}


.table--vam{
  & td{
    vertical-align: middle;
  }
}

.table__title{
  text-align: left;
  padding-top: 10px;
  padding-bottom: 10px;
  display: inline-block;
}

.table--new-skin{
  font-size: 13px;

  & th {
    background-color: $user-plank;
  }

  & .table__title{
    color: #fff;
    padding-top: 0;
  }

  & .icon--round-check{
    color: $cold-green;
    font-size: 22px;
  }

  & .icon--cross{
    color: $cross;
    font-size: 15px;
  }

  & .icon--spinner{
    color: $table-icon;
    font-size: 23px;
    //animation: spin 1s linear infinite;
  }

  & .icon--clock{
    font-size: 22px;
    color: $table-icon;
  }

  & .table__time{
    color: $grey;
    margin-top: 5px;
  }

  & tr{
    td.current{
      background-color: $table-current;
    }

    &:hover {
      & td{
        background-color: $drop-block;
        &.current{
          background-color: $table-current;
        }

        &.danger{
          background-color: $table-danger;
        }
      }
    }
  }

  & .icon--round-cross{
    font-size: 22px;
    color: $table-triangle;
    text-align: center;
    position: relative;
    display: inline-block;
  }

  & .icon--cross-man{
    color: $cross;
    font-size: 27px;
  }
}

td.danger{
  background-color: $table-danger;

  &:hover{
    background-color: $table-danger;
  }
}


.table__decline-bonus{
  text-align: center;
  color: #fff;
  position: relative;
}

.table__float-triangle{
  &:after{
    @include pseudo-elem;
    @include tri-t($table-danger, 12, 12);
    top: 100%;
    left: 50%;
    margin-left: -12px;
    margin-top: 13px;
  }
}

.table__button-container{
  float: right;
  @include inlined;
  width: 30%;
  text-align: right;
}

.table__decline-bonus--tall{
  .table & {
    padding-top: 5px;
    padding-bottom: 5px;
  }

  & .b_btn{
    font-size: 16px;
    min-height: 30px;
    padding: 0px 16px;
    min-width: 0;
  }

  & .table__text{
    width: 70%;
    @include inlined;
    padding-left: 20%;
  }
}


.table__date, .table__time{
  display: block;
}

//.table__date{
//  font-weight: bold;
//}

.table__sort-link{
  position: absolute;
  left: 0%;
  margin-left: 10px;
  width: 0;
  height: 0;
}

.table__sort-link--up{
  @include tri-t($table-triangle, 5, 6);
  bottom: 15px;
  left:20px;
}


.table__sort-link--down{
  @include tri-b($table-triangle, 5, 6);
  bottom: 15px;
}


.table__tr--shadow{
  td {
    box-shadow: inset 0px 1px 0 0px $cabinet;
  }
}


.current{
  &.table__title{
    color: $cold-green;
  }

  &.table__sort-link--up{
    border-bottom-color:$cold-green;
  }

  &.table__sort-link--down{
    border-top-color:$cold-green;
  }
}

.table{
  .icon--arrow{
    display: inline-block;
    width: 24px;
    height: 24px;

    &:after{
      display: none;
    }
  }

  .icon--arrow-bottom{
    & .svg-wrapper{
      transform: rotate(0deg);
      @include transition;
    }

    & .svg-icon--arrow{
      fill: $table-triangle;
    }

    &:before{
      display: none;
    }
  }

  .icon--arrow-top{
    & .svg-wrapper{
      transform: rotate(180deg);
      @include transition;
    }

    & .svg-icon--arrow{
      fill:$cold-green;
    }
  }

  tr.current td{
    background-color: $drop-block;
  }

  tr.current th{
    background-color: $drop-block;
  }

  tr.current .current{
    background-color: $drop-block;
  }
}

.contests-splicer:hover {
  & td {
    background-color: $dark-popup;
  }
}

.deposit__td-icon{
  width: 88px;
}

.table__toggler{
  cursor: pointer;
}

.table__toggler-btn{
  cursor: pointer;
  position: relative;
}
`

**Comment by ai** [comment]
You give me a SCSS source, not CSS :).

You use `postcss-scss` to lint SCSS sources with Stylelint?

**Comment by maliyshock** [comment]
Какого лешего мы на английском переписываемся? XD

По CSS. Он пустой на выходе. Т.е. как я себе это представляю. Postcss парсит css-ку в какой-то момент что-то идёт не так, он валится и выплёвывает пустой css.

Я не использую postcss-scss - это видно в packaje.json.
Я использую node-sass для компиляции scss  в css
Выглядит это так

`node-sass markup/scss/layouts/old-layout/index.scss | postcss --use autoprefixer --autoprefixer.browsers '> 1%, last 2 versions' > public/css/my-styles.css
`

**Comment by ai** [comment]
@maliyshock так зачем ты мне дал SCSS? ;)

Если хочешь исправить ошибку — открой новый issue, с входным CSS и stacktrace ошибки.
