### ISSUE TITLE
PostCSS in the browser

### ISSUE THREAD

**Issue by alexisvincent** [postcss/postcss#913]
What kinds of things make it hard to run PostCSS in the browser. I'm asking because I'm particularly interested in getting the PostCSS ecosystem running smoothly in SystemJS.

**Comment by ai** [comment]
Just use webpack/browserify to build a PostCSS and plugins into a single file.

Is it OK for your case?

**Comment by alexisvincent** [comment]
Thanks for the amazingly quick response. I noticed @guybedford did this in the latest systemjs-css plugin. Whats stopping me from importing postcss and plugins in the application and using it like that?

**Comment by ai** [comment]
I added a `Browser` section to docs b302129

**Comment by ai** [comment]
@al

**Comment by alexisvincent** [comment]
Thanks. To clarify, why this, over importing and using plugins directly in 'application' level code (Which gets compiled by something like browserify or webpack)?

**Comment by ai** [comment]
If your application is built webpack/browserify you could use PostCSS inside app’s webpack :D.

Maybe I didn’t write it clear. Do you want to send a PR for this section?

**Comment by alexisvincent** [comment]
Ok thanks. Do you know to what degree other plugins support running in the browser?

I'll contribute once I'm feeling more confident I know whats going on :) Thanks :)

**Comment by ai** [comment]
Most of non-fs-related plugins are working (of course, postcss-assets or postcss-import could not work, because of lack of FS)

**Comment by alexisvincent** [comment]
This is what I would have expected. However there's no real reason fs related things shouldn't be able to work. If we have a way of mapping browser URL's to files.

**Comment by al** [comment]
Wrong @al. Unsubscribing.

**Comment by alexisvincent** [comment]
@al How did you even get pulled in to this convo?

**Comment by ai** [comment]
@alexisvincent what is “convo”?

**Comment by alexisvincent** [comment]
@ai Sorry, convo <-> conversation

**Comment by alexisvincent** [comment]
@al isn't mentioned anywhere, any yet he was still subscribed to the issue. Sounds like a bug with github to me

**Comment by ai** [comment]
@alexisvincent I make a typo and then edit message.

**Comment by alexisvincent** [comment]
Oh I see 👍
