### ISSUE TITLE
Absolute sourceMap paths

### ISSUE THREAD

**Issue by emilbayes** [postcss/postcss#914]
It seems this was requested in #757, but with the difference being not resolving paths with a protocol given. I really want my sourceMap `sources` to be absolute paths, and have changed [lib/map-generator.es6#L177](https://github.com/postcss/postcss/blob/b302129035c895d2723400e81306226ccdcf0d3f/lib/map-generator.es6#L177) to `path.resolve` in my installation. Could we make this an option, as to preserve existing behaviour but accomodating absolute paths?

Maybe something like:

```js
file = (this.mapOpts.absolute !== true ? path.relative : path.resolve)(from, file);
```

I'd be happy to do a PR with tests if this is something you're open to.

**Comment by ai** [comment]
Why do you need it absolute? What is your use case?

**Comment by emilbayes** [comment]
So my current use case is pretty specific; my test server for prototyping parses all the html it sends off and resolve any css using PostCSS. I've made a live reload plugin that will let me update inline "compiled" css, but the live reload server sends off absolute urls. Since relative urls can be ambiguous, it is not always possible to check whether the relative url in the source map is the same file as the received absolute url.

Another, albeit weaker case, is that browserify gives absolute paths (also because absolute paths are unambiguous). If you're worried about performance, we can cache the function in the constructor

**Comment by ai** [comment]
If it is very specific, maybe you can just write relative-to-absolute tool? And just call it on source maps after PostCSS? 😊

I think it could keep PostCSS API clean, but still since your problem.

Also this till will be useful for many other processors with source map (like Babel or Sass).

**Comment by emilbayes** [comment]
Well, my use case is specific, but the applicability of absolute paths is not. The API is not disrupted by this change, since this would be a semver minor change.

**Comment by ai** [comment]
Hm. OK. I will think about it.

But I am not planning minor release on this week 😞. So release week not be soon.

**Comment by emilbayes** [comment]
Another option might be to allow to set a `sourceRoot` which would also solve the problem, and may be more semantic to the spec

**Comment by ai** [comment]
sourceRoot is much interesting! We have more use cases for it.

**Comment by emilbayes** [comment]
Another application of this is if you write your output to a different place than where your input lives. I guess you solve this by resolving `from` and `to`, but if `to` can't be determined ahead of time, absolute paths are your only option

**Comment by ai** [comment]
So, does `sourceRoot` fixes all problems? I think it is better API. Do you want to make PR?

**Comment by emilbayes** [comment]
@ai I ended up re-resolving the source map `sources` in relation to `to` which worked great. For anyone else coming here, this is what I ended up doing:

```js
'use strict'
const postcss = require('postcss')
const PassThrough = require('stream').PassThrough
const concat = require('concat-stream')
const duplexify = require('duplexify')

const path = require('path')
const mold = require('mold-source-map')

module.exports = function (opts) {
  opts = opts || {}
  const p = postcss([ require('../index')(opts) ])

  const input = new PassThrough()
  const output = mold.transformSources(function (sourceFile) {
    return path.resolve(path.dirname(opts.path), sourceFile)
  })

  input.pipe(concat(function (text) {
    p.process(text, { from: opts.path, to: opts.path, map: true }).then(function (res) {
      output.end(res.css)
    }, function (err) {
      output.emit('error', err)
    })
  }))

  return duplexify(input, output)
}
```
