### ISSUE TITLE
map.sourcesContent doesn't work together with map.from

### ISSUE THREAD

**Issue by sormy** [postcss/postcss#916]
```js
const postcss = require('postcss');
const autoprefixer = require('autoprefixer');

const options = {
  from: 'src/test.css',
  to: 'src/test.css!postcss',
  map: {
    inline: false,
    annotation: false,
    sourcesContent: true,
    from: 'src/test.css'
  }
};

const instance = postcss([ autoprefixer({ browsers: '>0%' }) ]);

const result = instance.process('.test { border-radius: 5px }', options);

console.log(result.map.toJSON());
```

code below will produce `sourcesContent: [ null ]` instead of `sourcesContent: [ '...' ]` but will produce correct source name `src/test.css`.

If i will remove `from` option then `sourcesContent` will have correct value but `sources` will have `test.css` instead of `src/test.css`.

So there is no way to keep correct source name together with source content.

Looks like a two defects:

* `options.from` with full path truncated to basename by default and source map looses original source file path
* workaround with `options.map.from` keeps correct source file path but doesn't work well with `options.map. sourcesContent = true` (breaks source content)

**Comment by ai** [comment]
Very weird. I will try to look in this weekend. Feel free to ping me in Monday if I will forget.

**Comment by ai** [comment]
Will it work if you will set `to: 'src/test.css'`? Will it work if you set absolute path to `from` and `to`?

**Comment by sormy** [comment]
@ai no, it doesn't

**Comment by uncleyo** [comment]
Hi, I think I hit the same issue when running `postcss` on `node-sass` output.
if `map.from` is set, the resulting `.map` file only references the empty _virtual_ file, while all original sass maps are gone.

**Comment by ai** [comment]
I found problem. It was because of wrong content of `opts.map.from`. It should be relative from `to` (in this case it should be `test.css`).

I fixed docs: https://github.com/postcss/postcss/commit/30ac96f1a93484a591ba94a98e6a8aba519b3d37

`opts.map.from` is low-level option for rare edge cases. You should not use it.
