### ISSUE TITLE
Source map line numbers off by two with no plugins

### ISSUE THREAD

**Issue by alexturpin** [postcss/postcss#925]
Hey all,

I've encountered a bit of an issue with sourcemaps. My workflow is that I first compile my SASS code down to CSS, and then use PostCSS on the resulting code / source maps.

My problem is that even with no plugins, after going through PostCSS, source map line numbers are off by 2 (they point to 2 lines before the actual line). Here is a small example that reproduces the problem:

```
var styles = `p{color:red}a{color:green}

/*# sourceMappingURL=styles.css.map */`;

var map = `{
	"version": 3,
	"file": "styles.css",
	"sources": [
		"styles.scss"
	],
	"sourcesContent": [
		"p {\\n\\tcolor: red;\\n}\\n\\na {\\n\\tcolor: green;\\n}\\n"
	],
	"mappings": "AAAA,AAAA,CAAC,AAAC,CACD,KAAK,CAAE,GAAI,CACX,AAED,AAAA,CAAC,AAAC,CACD,KAAK,CAAE,KAAM,CACb",
	"names": []
}`;

var postcss = require('postcss');
var fs = require('fs');
var path = require('path');

postcss([])
	.process(styles, { from: 'styles.css', to: 'styles.css', map: { inline: false, prev: map } })
	.then(function(result) {
		fs.writeFileSync('styles.css', result.css);
		fs.writeFileSync('styles.css.map', result.map);
	}, function(err) {
		console.log(err);
	});
```

I've inlined the files using ES6 template strings to make the example more succinct. The original files' source maps work perfectly. However after going through PostCSS with no plugins, the line numbers are off by two.

Am I doing something wrong?

Thanks

**Comment by ai** [comment]
Check source maps after each steps by [source-map-visualization](https://sokra.github.io/source-map-visualization/).

If you find problem in PostCSS, please create separated issue with input CSS, input map, output CSS and map.

**Comment by alexturpin** [comment]
@ai see #926
