### ISSUE TITLE
Postcss out of memory when it is parsing many files

### ISSUE THREAD

**Issue by MatteoWebDesigner** [postcss/postcss#928]
Basically postcss parse and keep in memory every file passed by grunt blob and it parse until breaking and goes out of memory.

example:

```
grunt.initConfig({
  postcss: {
    options: {
      processors: [
        require('autoprefixer')({browsers: 'last 2 versions'})
      ]
    },
    dist: {
      src: 'css/*.css' // 50 css file with 20.000 line of css
    }
  }
});
```

error message I see in console:
```
<--- Last few GCs --->

   69906 ms: Scavenge 1397.3 (1458.2) -> 1397.3 (1458.2) MB, 0.9 / 0 ms (+ 1.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   70766 ms: Mark-sweep 1397.3 (1458.2) -> 1390.5 (1458.2) MB, 860.2 / 0 ms (+ 1.0 ms in 1 steps since start of marking, biggest step 1.0 ms) [last resort gc].
   71601 ms: Mark-sweep 1390.5 (1458.2) -> 1392.3 (1458.2) MB, 834.5 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000348E1AB4639 <JS Object>
    1: spacesFromStart [C:\projects\matteo-project\node_modules\postcss\lib\parser.js:~401] [pc=000001F0D87ADC63] (this=0000020F9DD924E9 <a ScssParser with map 00000322811F6AF9>,tokens=00000247023BD939 <JS Array[9]>)
    2: decl [C:\projects\matteo-project\node_modules\postcss\lib\parser.js:235] [pc=000001F0D8906DCC] (this=0000020F9DD924E9 <a ScssParser with map 00000322811F6AF9>,tokens=000002470...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by ai** [comment]
This question is for `grunt-postcss`. PostCSS should keep only current file :D.

**Comment by VitaliyR** [comment]
I encountered this one also.

**Comment by ai** [comment]
@VitaliyR how big files (in MB) did you parse?

**Comment by VitaliyR** [comment]
@ai ~43MB of ~126 CSS files. A lot of templates.

**Comment by ai** [comment]
@VitaliyR could you try to call `tokenize()` on them to detect is it a tokenizer issue, or a parser

**Comment by ai** [comment]
@hzlmn now is working on taking `csstree` tokenizer to PostCSS, it will improve tokenizer memory usage https://github.com/postcss/postcss/issues/939

**Comment by ai** [comment]
@VitaliyR does this 43 MB is in one file? Or you have many small files? Do you concat them?

do you use webpack or gulp?

Do you have such so big CSS because of inline images/font or it is a lot of rules?

**Comment by VitaliyR** [comment]
@ai I can try, but at least, what debugger says - it is parser issue. 
```
 1: _parseMappings(aka SourceMapConsumer_parseMappings) [/home/vitaliy/hostroot/clioui/node_modules/grunt-postcss/node_modules/postcss/node_modules/source-map/lib/source-map-consumer.js:~423] [pc=0x1e9d743b1aa6] (this=0x1ad8636f0041 <a BasicSourceMapConsumer with map 0x3d66321b1979>,aStr=0x1ad863604101 <Very long string[539601]>,aSourceRoot=0x3a595704101 <null>)
```

**Comment by VitaliyR** [comment]
@ai as I mentioned above, **126 CSS** files with total size of about **43 MB**. No, they're not concated - they should be separated and they're come from SCSS. I'm using only grunt here.

> Do you have such so big CSS because of inline images/font or it is a lot of rules?
3 inlined fonts and 5 svg icons (it should be many, don't it?)

**Comment by ai** [comment]
@VitaliyR could you try to disable source map support (maybe memory problems came from `source-map` library?) Just disable maps in Sass and set `map: false` in PostCSS.

What size of the biggest CSS file?

**Comment by VitaliyR** [comment]
@ai yes, it works. But we need that source maps :) 

I think, the biggest one - 600kb.

**Comment by ai** [comment]
@VitaliyR could you please create a issue in [source-map](https://github.com/mozilla/source-map) with full stacktrace and your project description. Also maybe you should give them one file with source map to investigation.

If problem came from this library they will know more how to fix it.

**Comment by VitaliyR** [comment]
@ai anyway there are a lot of problems in a current version of postcss because of source maps. Parsing them takes a lot of time, more than half of total build time.

For instance, with sourcemaps this project builds for 2m 47s (where 1m 44s postcss), and without them - 1m 55s(where 52s postcss). Damn, that's bad :(

Problem was fixed by fixing grunt-postcss locally - added possibility to handle CSS files in sequential mode, one by one. So, memory is fine for now and GC correctly cleans everything. Will create a PR for that.

**Comment by ai** [comment]
> a lot of problems in a current version of postcss

Why you so aggressive with me? :cry: 

> Parsing them takes a lot of time, more than half of total build time

Do you know any other good source map library? Or maybe we could speed-up current one?

> For instance, with sourcemaps this project builds for 2m 47s (where 1m 44s postcss), and without them - 1m 55s(where 52s postcss)

Did you try to optimize source map usage? For example, did you use `sourceContent`? It always biggest part of source map. If you need it, you can add it on last step of CSS pipeline.

Did you already create a issue about memory problems on `source-map`? It is very important to report issue to library authors (but try to not use Russian aggressive speaking style ;) ).

**Comment by ai** [comment]
Seems like it is Grunt/source-map issue. I will close this issue.

**Comment by VitaliyR** [comment]
@ai Sorry for posting in closed issue, but I just need to..

> Why you so aggressive with me?

Say sorry :) You're awesome!
Am I really aggressive? 😞 

And yes, I'm creating an issue right now in `source-map` repo.

`sourcesContent` was set to false.

**Comment by ai** [comment]
@VitaliyR OK, let’s wait for `source-map` authors help. I just use their API and don’t know internal structure to help in this case.
