### ISSUE TITLE
Plugin#process change

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss#929]
In the next major version, may we please separate plugin options from process options?

```js
plugin.process(cssString, pluginOptions, processOptions)
```

---

Right now, the `Plugin#process` method mixes both the process options and plugin options. This makes accurate stand-alone testing impossible.

```js
plugin.process(cssString, Object.assign(pluginOptions, processOptions))
```

Because the options are mixed, plugin options cannot use the same names as process options (see [processOptions](http://api.postcss.org/global.html#processOptions)). I ran into this problem when testing plugins (like svg fragments, import) that rely on `source.input.file`; because it required I pass in a plugin option named `from` to test the plugin accurately. I ran into a side-effect problem when testing plugins (like postcss-pseudo-class-any) that passed the processOptions to the plugin (in this case, it prevented me from stand-alone testing a plugin without options).

For now, this is my workaround.

```js
// override plugin#process
module.exports.process = function (cssString, pluginOptions, processOptions) {
	return postcss([
		1 in arguments ? module.exports(pluginOptions) : module.exports()
	]).process(cssString, processOptions);
};
```
---
Thanks @ben-eb for catching that oversight. It has been corrected.

**Comment by ben-eb** [comment]
This method signature is lacking the `css` input, it should be:

```js
plugin.process(cssString, pluginOptions, processOptions);
```

**Comment by ai** [comment]
I changed signature to:

```js
plugin.process(cssString, processOptions, pluginOptions);
```

Because now all plugins need options, but `from` and `to` should be set for most of cases.

**Comment by ai** [comment]
Done bde85b8
