### ISSUE TITLE
JS API example not working

### ISSUE THREAD

**Issue by Diokuz** [postcss/postcss#936]
Hi there. I have a problem... I cant understand how readme example is supposed to work:

```js
var postcss = require('postcss');
postcss([ require('autoprefixer'), require('cssnano') ])
    .process(css, { from: 'src/app.css', to: 'app.css' })
    .then(function (result) {
        fs.writeFileSync('app.css', result.css);
        if ( result.map ) fs.writeFileSync('app.css.map', result.map);
    });
```

What is `css`? In the doc you write [It is a String with input CSS](http://api.postcss.org/Processor.html#process)...
but if I have to read my input file and place it as a string to `css` argument, what is `options.from` then?

Also, why I should write `app.css` file in promise `then`? What is `options.to` then?

**Comment by ai** [comment]
Docs about `from` and `to` options: http://api.postcss.org/global.html#processOptions

This options is a filename of origin file (for instance, `app.css`) and output file after PostCSS (for instance, `app.min.css`). You need to specify this file names to generate correct source map.

**Comment by ai** [comment]
You need a `process(…).then()` because some plugins could be async.

**Comment by RyanZim** [comment]
`css` would be a string containing the contents of src/app.css.

postcss itself doesn't do any filesystem read/write based on `to` and `from`.

**Comment by ai** [comment]
You have a `fs.writeFileSync('app.css', result.css)` inside `process(…).then()`, because only in `then()` callback you will get processed CSS after PostCSS transformations

**Comment by ai** [comment]
I made JS API example in docs more clear: 2820c76

Thanks for your questions

**Comment by Diokuz** [comment]
Thank you, but I still have a question) Why you have to place `'src/app.css'` and `'dest/app.css'` code twice? Why you cannot use only `options.from` and `options.to`, without `css` argument and `then` with fs.write magic? It looks like repeated unnecessary double-logic.

**Comment by ai** [comment]
@Diokuz I thought about file system shortcut. But it is unnecessary in most of cases:

1. `gulp-postcss` gets file content via Gulp API.
2. `postcss-loader` gets file content via webpack API.
3. PostCSS CLI use better reading mechanism to read multiple files faster.
4. PostCSS for client JS has even no access to `fs`.

In result there is no good reason to some `postcss().readAndWrite()` shortcut.

**Comment by Diokuz** [comment]
So, maybe just handle that case:
```
var postcss = require('postcss');
postcss([ require('autoprefixer'), require('cssnano') ])
    .process({ from: 'src/app.css', to: 'app.css' });
// and after all transformations, `/app.css` will appear as an output file.
```
I dont think one more `readAndWrite` method is a good idea either) but I think code-example above is more consistent and simpler for JS API usage.

**Comment by RyanZim** [comment]
@Diokuz Most postcss runners aren't getting the file contents directly from the filesystem: 

> -    gulp-postcss gets file content via Gulp API.
>  - postcss-loader gets file content via webpack API.
 >  - PostCSS CLI use better reading mechanism to read multiple files faster.
>   - PostCSS for client JS has even no access to fs.

So we need to support passing and returning strings.

**Comment by ben-eb** [comment]
I like showing the simplest example based on the lowest common denominator (the console, available both in browser and node). This is most amenable to "copy, paste & run".

https://runkit.com/npm/cssnano

**Comment by RyanZim** [comment]
@ben-eb Not a bad idea to eliminate the `fs` from the example entirely. :+1: @ai?

**Comment by Diokuz** [comment]
> So we need to support passing and returning strings.

Why just make another `if (type of argument[0] === 'string') ... else if (typeof === 'object')` ?)
Docs says `from` and `to` – both are files, and I expect that if I need only input and output files, I can use only these two parameters, and forget about `css`-string and `then`, and `fs`.

**Comment by RyanZim** [comment]
That would be implicit behavior, not a good idea in most cases. Also, you must keep in mind that postcss core can run in the browser as well, so putting `fs` manipulations in core is just adding complexity. Not in favor of this.

**Comment by ai** [comment]
@RyanZim I uses `fs` to show:

* that you need to write `.map` only if it is present in `result.map`.
* what is `from` and `to` options.

**Comment by ai** [comment]
@Diokuz and what is a reason for this `.process({ from: 'src/app.css', to: 'app.css' })` shortcut? It will increase code size and decrease maintainability without any benefits for any popular runner.

**Comment by Diokuz** [comment]
I think I did not get something important here, please, help me)

It seems to me that `.process({ from: 'src/app.css', to: 'app.css' })` more consistence with docs) It just says that `options.from` and `options.to` – are files. And logical question here: why these parameters not work)

> `options.from` the path of the CSS source file. You should always set from, because it is used in source map generation and syntax error messages.
> `options.to` the path where you’ll put the output CSS file. You should always set to to generate correct source maps.

http://api.postcss.org/global.html#processOptions

Also, I did not get, what css will be taken in this example and why:

```
processor.process(css, { from: 'a.css', to: 'a.out.css' })
  .then(result => {
     console.log(result.css);
  });
```
http://api.postcss.org/Processor.html#process

From `css` string or from `a.css` content?

What `options.from` and `options.to` actually do?

**Comment by ai** [comment]
@Diokuz `options.from` and `options.to` are used only for source maps. Source map should contains a paths. PostCSS *doesn’t* load file from `a.css`, it takes CSS content from `css`.

We could add `.process({ from: 'src/app.css', to: 'app.css' })`, but nobody will use it. Every PostCSS runner (`gulp-postcss`, `postcss-loader`, `postcss-cli`, `postcss-js`) uses different methods to read/write files.

**Comment by michael-ciniawsky** [comment]
@Diokuz 

```js

const css = fs.readFileSync('./src/app.css', 'utf-8') // {String}

postcss(plugins)
   .process(css, { from: 'src/app.css', to: 'app.css', map: { inline: false } })
   .then((result) => {
      fs.writeFileSync('./app.css', result.css, 'utf-8') // {String}
     // Doesn't need options.from/to to work
      console.log(result.map) 
     // Needs options.from/to to know the path/location of the origin (css) and
     // destination (result.css) to generate the mappings (changes made by postcss plugins)
     //
     // Generated Souremap
     //
     // {
     //   "version": 3,
     //   "file": "app.css", (options.from)
     //   "sources": ["src/app.css"], (options.to)
     //   "mappings": "AAAA,KAAI" 
     // }
   })
```

**Comment by felixsanz** [comment]
if you don't use sourcemaps there is no point in using 'from' and 'to' and it's confusing. i end up here because i was thinking that from/to reads/writes css files

**Comment by ai** [comment]
`from` is also used in CSS syntax errors
