### ISSUE TITLE
Parser structure

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss#939]
While was reading throught `postcss` sources, found a moment that current parsing architecture looks                          
```
 ___________                        __________
|           |                      |          |
| Tokenizer | -> List of Tokens -> |  Parser  | -> Parser eats them and produces AST
|___________|                      |__________|

```

While it works fine, I am really wondering if there are any reasons for not using `tokens streaming` like `babylon` do for example, where you plug tokenizer in parser, or expose something like `readNextToken`?

In this manner you only scan source once, instead of scanning source and then iterating over tokens, that could provide significant performance boost.

**Comment by ai** [comment]
There is no real reason for it. Personally, I really like this idea, especially after [csstree](https://github.com/csstree/csstree) show it’s great parser with `nextToken` idea (with many other great ideas).

Do you want to update current parser and tokenizer? Or you could take `csstree` parser and try to connect it to PostCSS’ parser.

**Comment by hzlmn** [comment]
I could do both, it's IMO a question to you and core team, what will be better for further plans.

**Comment by ai** [comment]
@hzlmn I think you could start from backporting `csstree` tokenizer. If it possible, it will give a tokens streaming in the fastest way. If it is not possible we could try to add this feature to current tokenizer.

@lahmatiy do you think it is possible to backport `csstree` tokenizer to PostCSS?

**Comment by hzlmn** [comment]
@ai Ok, I gonna read through`csstree` source to figure out what could be done.

**Comment by hzlmn** [comment]
@ai As far as i can see, it is pretty possible to backport tokenizer from `csstree`. I started work on it and will create WIP pull request as soon as i can for ealier feedback.

**Comment by ai** [comment]
Awesome! 😍🎅 Feel free to ask any help.

**Comment by hzlmn** [comment]
@ai Seems like project' folder is getting bigger, what do you think about decoupling `parser`, `tokenizer` structures to external folders? It could close one spot here #503 .

**Comment by ai** [comment]
Could you show some structure example?

But I think separating set and parser is a good thing.

**Comment by tunnckoCore** [comment]
Externalizing tokenizer to separate package is even better thing. :D Such tokenizers works well for JSON parsing too. :)

**Comment by ai** [comment]
@tunnckoCore you could write much better tokenizer for JSON only format :).

**Comment by hzlmn** [comment]
@ai Nevermind, anyway it should be part of another PR.

Quick question, does current `parser` support passing `ignoreErrors` param, because as I can see [here](https://github.com/postcss/postcss/blob/master/lib/parser.es6#L23) , this [option](https://github.com/postcss/postcss/blob/master/lib/tokenize.es6#L29) never passed ?

**Comment by ai** [comment]
I use this option in [Safe Parser](https://github.com/postcss/postcss-safe-parser).

**Comment by ai** [comment]
Done in `orias` branch
