### ISSUE TITLE
npm install postcss@5.2.8 error

### ISSUE THREAD

**Issue by zhangping2014** [postcss/postcss#943]
Error: unknown compression method (postcss@5.2.8) (/Users/drank/.npminstall_tarball/p/o/s/t/postcss/5.2.8-05720c49df23c79bda51fd01daeb1e9222e94390.tgz)
    at Zlib._handle.onerror (zlib.js:363:17)
npminstall version: 2.2.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/drank/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org postcss

**Comment by ai** [comment]
Sorry, it is not relevant to PostCSS. You have some problems with npm at all.

**Comment by zhangping2014** [comment]
how can i fixed it

**Comment by zhangping2014** [comment]
how can i fixed it @ai

**Comment by ai** [comment]
@zhangping2014 sorry, I don’t know :( I am not good in `npm`.
