### ISSUE TITLE
Move TypeScript definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss#947]
TypeScript is gaining more and more traction these days, now publishing type definitions on npm as `@types/package-name`. @ai, if you still want to remove the TS definitions from this project, I can submit a PR to DefinitelyTyped and it will be published at [`https://www.npmjs.com/package/@types/postcss`](https://www.npmjs.com/package/@types/postcss) in the future; however, that is definitely not the golden path and I would urge you to reconsider based on how much traction TypeScript is getting these days.

**Comment by ai** [comment]
I like to move type definitions, but I think it will be better for major release.

**Comment by jedmao** [comment]
I can at least get a head start by publishing on DefinitelyTyped. My only concern is that the type definitions won't be in sync w/ the version of PostCSS that you install. Are you not concerned about that?

**Comment by ai** [comment]
Can we have `@types/postcss6.0`, `@types/postcss6.1`?

**Comment by jedmao** [comment]
Yeah, but there has to be a separate definition file and test for each version created, which is a bit messy.

> In case there are multiple versions supported, the latest one will be without a version number in the file name. Older versions will be in the form of library-1.2.0.d.ts where the postfix should resemble a valid semantic version number (semver).

See http://definitelytyped.org/guides/contributing.html

**Comment by ai** [comment]
How DefinitelyTyped authors suggest to solve this problem?

**Comment by jedmao** [comment]
Microsoft and DefinitelyTyped are working quite close together these days. This comes straight from the [TypeScript Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) doc:

> There are two main ways you can publish your declaration files to npm:
bundling with your npm package, or
>  1. publishing to the @types organization on npm.
>  1. If you control the npm package you are publishing declarations for, then the first approach is favored. That way, your declarations and JavaScript always travel together.

We can't publish a version directly to `@types/postcss`, because those are reserved and [published directly by Microsoft](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#publish-to-typeshttpswwwnpmjscomtypes) automatically from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) using the [`types-publisher-tool`](https://github.com/Microsoft/types-publisher). This is a relatively new feature, BTW.

> To get your declarations published as an @types package, please submit a pull request to https://github.com/DefinitelyTyped/DefinitelyTyped.

## Conclusion
What [we are doing right now](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) is the golden path, because I can just updated the definition file to be in sync w/ the latest version of PostCSS and the next time you publish a specific version, those types are linked to that version.

I know you want to get rid of the definitions in this project, but I've already [gotten rid of most of them](https://github.com/postcss/postcss/pull/949) except for the one [`postcss.d.ts`](https://github.com/postcss/postcss/blob/master/lib/postcss.d.ts) file. I hope you'll agree that this is the best solution, moving forward, to keep what we have right now. If not, we can talk about next steps.

**Comment by ai** [comment]
OK, let’s keep them inside if we have no good solution right now.

BTW, one file difintion is very good change :).

**Comment by jedmao** [comment]
Excellent! For tracking purposes, I want everyone reading this thread to know that my [`jedmao/typescript`](https://github.com/jedmao/postcss/tree/typescript) branch is still how I'm generating `postcss.d.ts`. There is a bit of manual work required after building the project, unfortunately, but it's necessary right now.

**Comment by ai** [comment]
@jedmao Hi, could you update TypeScript definitions in `orias` brach?

**Comment by jedmao** [comment]
@ai, unfortunately, there's a lot of love required before I can get postcss to compile w/ the newest version of TypeScript and, frankly, I don't have the time right now.

**Comment by jedmao** [comment]
Also, I have to read all the commits that have happened to get the definitions up-to-date. It's really a ton of work.

**Comment by ai** [comment]
No, API was changes in few places.

But of course we could update TS after

**Comment by jedmao** [comment]
As is the case with [DefinitelyTyped](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiyvP2gv8_TAhVLl1QKHVYgA_0QFggmMAA&url=https%3A%2F%2Fgithub.com%2FDefinitelyTyped%2FDefinitelyTyped&usg=AFQjCNEJufWRlTta1PHPSO4pAeuItOfZ_w), people tend to update them when they need them. This is the price we pay for not switching this project to TypeScript, because we'll always be playing catch up, but if someone finds something missing in the TS definitions they will probably just submit a PR here.

**Comment by ai** [comment]
@jedmao but in result DefinitelyTyped doesn’t support PostCSS case? We can’t remove TS from npm?

**Comment by jedmao** [comment]
There are no [postcss types on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/postcss); therefore, no [`@types/postcss` package on npm](https://www.npmjs.com/package/@types/postcss), "because" the [`postcss`](https://www.npmjs.com/package/postcss) package supplies them out-of-the-box. This is the golden path so I'm pretty happy about it.

What I'm saying is that if someone noticed something missing from [`postcss#postcss.d.ts`](https://github.com/postcss/postcss/blob/master/lib/postcss.d.ts), all they would need to do is [submit a PR to this repo](https://github.com/postcss/postcss/pulls) to update them. Problem solved.
