### ISSUE TITLE
How to get the final font/image paths?

### ISSUE THREAD

**Issue by IonicaBizau** [postcss/postcss#951]
Seems like `postcss` is pretty smart in fixing the font paths, but I'd like to get a list of the fonts paths and eventually modify them.

Currently I generate the bundle, but the fonts are not accessible in `node_modules`.
I'd like to modify the font paths like this: `node_modules/my-package/font.ext` :arrow_right: `/foo/node_modules/my-package/font.ext`. Also, my server will know that `/foo/node_modules/my-package/font.ext` will have to load the right font file.

So, how to modify these font paths?

Same story should be applied for background images and eventually to other resources which are accessible in CSS via paths (e.g. `cursor: url(...)`).

Thanks!

**Comment by ai** [comment]
1. You can write any plugin with any logic. Just use [PostCSS API](http://api.postcss.org/) in custom plugin.
2. Some `url()` magic could be done more easy by [url option](https://github.com/postcss/postcss-url#url-function) in `postcss-url` plugin.

**Comment by IonicaBizau** [comment]
@ai Wow, that was fast. :grin: Thanks!

I was just wondering that maybe someone else did this before. The `postcss-url` code may help to build my own.

**Comment by michael-ciniawsky** [comment]
@IonicaBizau `postcss-url` should support `result.messages[i].dependency` and add the URL paths there, as `postcss-import` does it with `@imports`

**Comment by IonicaBizau** [comment]
@michael-ciniawsky Thank you! :+1:
