### ISSUE TITLE
No longer able to import module in typescript

### ISSUE THREAD

**Issue by michaelkuroda** [postcss/postcss#954]
As of version 5.2.10, we are not sure how to use postcss with typescript.

We import the module via:
`import * as postcss from 'postcss';`

And we could call like:
`postcss().process(mycss).then((result) => { ... }`

However, as of 5.2.10, when attempting to compile we get error like:
> Cannot invoke an expression whose type lacks a call signature. Type of 'typeof "postcss"' has no compatible call signatures.

Attempting to change the import to:
`import postcss from 'postcss';`

Will compile okay, but causes issues when running:
> TypeError: postcss_1.default is not a function

What are we missing to get v5.2.10 to work with typescript? For the moment, we are using 5.2.9.

**Comment by ai** [comment]
We need one extra PR from @jedmao

**Comment by jedmao** [comment]
@michaelkuroda what version of TS are you using and are you also using Babel?

**Comment by michaelkuroda** [comment]
@jedmao I see the problem with a simple project that only includes postcss and typescript v2.1.5. Does not include Babel or anything else.

**Comment by morlay** [comment]
Has same issue with TypeScript@2.1.x

it cause by
```
exports.default = postcss;
module.exports = exports['default'];
```

if we keep `module.exports = exports['default'];` 
we have to use ` export = postcss;` instead of ` export default postcss;`
