### ISSUE TITLE
How process inline styles?

### ISSUE THREAD

**Issue by bernex** [postcss/postcss#956]
I wanna use postcss to process styles in html(parsed with parse5).

How to do it?

**Comment by ai** [comment]
Try to use https://github.com/postcss/postcss-js
Maybe you need to convert c styles from parse5 to object.

**Comment by bernex** [comment]
I think you do not understand question. PostCSS can't parse inline styles(parse5 output styles string), it does not hahe selector and brackets. How parse only brackets body and process with PostCSS?

**Comment by ai** [comment]
Could you show example of parse5 output styles string?

**Comment by bernex** [comment]
`display:flex;color:red;`

**Comment by ai** [comment]
String `display:flex;color:red;` should be parsed without problems. What problems did you have?
