### ISSUE TITLE
postcss-cli do not copy folder structure from input files when pattern is used

### ISSUE THREAD

**Issue by aesopturtle** [postcss/postcss#958]
I am trying to compile multiple `*.pcss` files and have the `*.css` output sit in the same directory. For example, I have the following structure:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
```
When running:
```
postcss --use precss src/**/*.pcss --dir out/
```
I expect:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
out
-- test1
---- 1.css
-- test2
---- 2.css
-- test3
---- 3.css
```
But what I got is:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
out
-- 1.pcss
-- 2.pcss
-- 3.pcss
```
So there are 2 issues here:
1. The output doesn't have the same folder structure as the input when used with pattern.
2. I don't seem to be able to specify the output file extension when using `--dir`.

Any suggestion please?

By the way, it would be great if such options are also available in a config file as that's where I actually configure the options :)

**Comment by ai** [comment]
For example, Gulp behaviour:

1. Take all input files.
2. Find longest common path (`src/` in this example)
3. Work with files based on this root (`test1/1.pcss` in this example)

**Comment by michael-ciniawsky** [comment]
We currently work on an complete CLI overhaul. Could you try ```npm i postcss/postcss-cli#develop``` for tessting out v3?

```bash
postcss src/**/*.pcss -o dest/
```

```js
module.exports = (ctx) => ({
   plugins: {
     precss: {...options}
   }
})
```

For extname I recommend just using `.css` 😛

**Comment by ai** [comment]
@michael-ciniawsky PreCSS has too non-standard syntax, so `.pcss` is good choice in this way. Without it IDE will not be able to highlight all that custom syntax.

**Comment by michael-ciniawsky** [comment]
@ai I understand, will try to see what options we have for renaming

```postcss src/*.pcss -o dest --ext '.css'```

**Comment by ai** [comment]
@michael-ciniawsky maybe we should auto-rename `.pcss` to `.css` as part of PostCSS convention?

**Comment by aesopturtle** [comment]
Is the version number `2.6.0`?
I tried `postcss src/**/*.pcss -o dest/` but it throws an error saying `Cannot find module 'src/**/*.pcss'`.
I also tried `postcss src/**/*.pcss --dir dest/` but it ends up with the same result.

**Comment by aesopturtle** [comment]
@michael-ciniawsky The main reason I use `pcss` extension is because I would like to have it as a source file and have `css` extension as an output which could be minified, autoprefixed, etc.

**Comment by michael-ciniawsky** [comment]
Nope it's v3@beta (not released yet) package.json is still `2.6.0` there, did you `npm uninstall postcss-cli` && ```npm i postcss/postcss-cli#develop``` it should grap it directly from github

Yep, I understand the reasoning behind `.pcss` etc 😛 , I just need to think of a way to handle that accurately

**Comment by michael-ciniawsky** [comment]
cc/ @RyanZim

**Comment by aesopturtle** [comment]
@michael-ciniawsky I tried repeating the npm install but still got v2.6.0 :(

**Comment by ai** [comment]
Oops, issue is in wrong place. It should be openned in `postcss/postcss-cli`. Should we recreate it?

**Comment by aesopturtle** [comment]
Oh... sorry about that -_-"
Should I recreate it there?

**Comment by michael-ciniawsky** [comment]
@ai mimimi... 😛. @aesopturtle yep please reopen at postcss/postcss-cli and close here

**Comment by aesopturtle** [comment]
Reopened at https://github.com/postcss/postcss-cli/issues/78
