### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss#963]
My example:
https://astexplorer.net/#/gist/0b1b43d95ebbacff50dbc586e4c3cd47/e76ccea9b9e87d184c55c337bb462166d0087cf6

All is well if insert some rule between two `@media`s.
Example: https://astexplorer.net/#/gist/0b1b43d95ebbacff50dbc586e4c3cd47/868a33900063dc5804e9d83278f3f7bfbe5bc9f8

I can insert temporary comment and remove it after transformation. But maybe there is another solution?

**Comment by ai** [comment]
Should be fixed in 6.0 with `raws` system refactoring.

**Comment by ai** [comment]
But honestly right indent is not goal for PostCSS. Most of CSS tools just broke your indent ;).
