### ISSUE TITLE
Flex not pre-fixing -webkit-flex

### ISSUE THREAD

**Issue by MartinDawson** [postcss/postcss#968]
Why does display: flex get the pre-fix -webkit-box instead of -webkit-flex?

My understanding of flex is that -webkit-box is really old, -webkit-flex is newwer and flex is the newest.

Took me forever to figure out why it was looking wrong on iphone 6.

**Comment by ai** [comment]
Are you asking about Autoprefixer? Next time create issue here: https://github.com/postcss/autoprefixer

**Comment by ai** [comment]
If you need to support iPhone 6, you need to create `"browserslist": "defaults, iOS 6"` (not sure about right version, check it) in `package.json`, so Autoprefixer will add prefixes for that Safari.

Default browsers supported by Autoprefixer could be checked here: http://browserl.ist/

**Comment by MartinDawson** [comment]
@ai Yes, that's it, it's applying the correct vendors now. Thanks.
