### ISSUE TITLE
incorrect position warn on non standard syntax

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss#979]
Initial issue https://github.com/stylelint/stylelint/issues/2374.
Seems bug on this line https://github.com/postcss/postcss/blob/master/lib/node.es6#L403
i use 
```scss
&.active {
    top:
    .tab {}
}
```
And use `result.warn('Warn message', warningProperties)`, where `warningProperties`:
```
{ severity: 'error',
      rule: 'no-missing-end-of-source-newline',
      node: 
       Root {
         raws: { semicolon: false, after: '' },
         type: 'root',
         nodes: [ [Object] ],
         source: { input: [Object], start: [Object] },
         lastEach: 2,
         indexes: {} },
      index: 32 }
```
Use `this.toString()` return incorrect css (see above what it was)
```shell
&.active {
    top:
    .tab 
}
```
If we change `this.toString()` to `this..source.input.css` all works fine.

**Comment by ai** [comment]
Is is a valid CSS? `top:` seems like a property, but without value and `;`

**Comment by evilebottnawi** [comment]
@ai not valid css and scss, maybe related to postcss-scss, should throw `CssSyntaxError`?

**Comment by ai** [comment]
@evilebottnawi let’s keep it open, I will think what we should do in this case.

But PostCSS public API never contains checking CSS for errors :D. So it will be in low propriety. OK?

**Comment by evilebottnawi** [comment]
@ai how about change `this.toString()` to `this.source.input.css`, i think it is normal solution without breaking changed

**Comment by ai** [comment]
@evilebottnawi it will work only for Stylelint :D `this.source.input.css` will not show AST changes.

Also even in Stylelint `this.source.input.css` could not be equal to `toString()`, because some PostCSS plugin before Stylelint, could change AST.

**Comment by evilebottnawi** [comment]
@ai I'm at a loss :smile: what kind of solution can help us? :smile:

**Comment by ai** [comment]
Only `toString()`. But it doesn't have any guarantees on broken syntax.

**Comment by evilebottnawi** [comment]
@ai we can't use `toString()` in our rules, because we reported on incorrect index :sob:

**Comment by ai** [comment]
OK, so the only solution here is to throw `CssSyntaxError` from parser

**Comment by evilebottnawi** [comment]
@ai it is related to `postcss-scss` or `postcss`?

**Comment by ai** [comment]
Note sure, can you check both parsers?

**Comment by evilebottnawi** [comment]
@ai late, i am very tired today :sleeping:

**Comment by ai** [comment]
Hm. I really afraid to throw error in this case. Because some plugins uses `:` in selector. We need to check it manually in Stylelint :(.

**Comment by evilebottnawi** [comment]
@ai thanks for answer!
