### ISSUE TITLE
Shouldn't postcss call `.toJSON` on returned source maps ?

### ISSUE THREAD

**Issue by MohammadYounes** [postcss/postcss#98]
Running the following code:

``` javascript
var result = autoprefixer().process(data, {map:true, from: 'sample.css', to: 'prefixed.css'});      
rtlcss().process(result.css, {map:{prev:result.map}, from: 'prefixed.css', to: 'prefixed.rtl.css'});
```

Gives the following error:

```
[Error: Unsupported previous source map format: {"version":3,"sources":["sample.
css"],"names":[],"mappings":"AAAA,wBAAuB;AACvB;IACI,mBAAkB;IAClB,sBAAqB;CACxB,gB
AAe;EACf;AACD,sBAAqB","file":"prefixed.css"}]
```

`result.map` contains the internal map object, to get the external map object, you need to call `result.map.toJSON()`, the following works with no error:

``` javascript
var result = autoprefixer().process(data, {map:true, from: 'sample.css', to: 'prefixed.css'});      
rtlcss().process(result.css, {map:{prev:result.map.toJSON()}, from: 'prefixed.css', to: 'prefixed.rtl.css'});
```

**Comment by MohammadYounes** [comment]
@ai  

This issue seems to be back as of autoprefixer 4.

@am11 

This might be whats causing the error described here https://github.com/madskristensen/WebEssentials2013/issues/1726 
Also as of postcss 3 : 
> `map.inline` and `map.sourcesContent` properties are now enabled by default, since it is now the most popular way to use maps.

Thus, the map property is not returned unless the map option contains `inline:false`.

These are breaking changes that might be causing serious issues in webessentials, since it does not reference a specific version and uses latest packages with each published release.

**Comment by ai** [comment]
@MohammadYounes `result.map` willbe created by PostCSS only if need to create seperated map file. So, if PostCSS uses inline map, there will be no `result.map` only `result.css`. This was a PostCSS API since first releases (but maybe not well documented :) ).

**Comment by ai** [comment]
This is bad:

```js
rtlcss().process(result.css, {map:{prev:result.map.toJSON()})
```

this is good:

```js
rtlcss().process(result)
```

PostCSS [accepts](https://github.com/postcss/postcss/blob/master/lib/postcss.js#L31) `Result` object and will autotically uses `result.map` if  it exists (or load inlined map  from `result.css`)

**Comment by MohammadYounes** [comment]
Earlier version of postcss would return `result.map` [without setting inline to false](https://github.com/MohammadYounes/WebEssentials2013/blob/master/EditorExtensions/Resources/server/services/srv-autoprefixer.js#L29-L32):
```
var result = autoprefixer.process(cssContent, { map: { prev: mapContent } });
//result.css
//result.map
```
This is not the case anymore! The issue is with old code using the new postcss :)

Why is the first one bad ?

**Comment by MohammadYounes** [comment]
Also in webessentials the source map is passed between different compilers/processors, not just postcss based plugins!

**Comment by ai** [comment]
Because PostCSS 4.0 made `inline: true` be default, because inlined maps is more popular and easy to use.

First way is bad because `result.map` may be `undefined` ;).

**Comment by MohammadYounes** [comment]
> First way is bad because result.map may be undefined ;).

That's a different issue :)

**Comment by MohammadYounes** [comment]
So from now on, this is the way to do it ?  (If I don't want to process `result`) 
```javascript
var result = autoprefixer().process(data, {map:true, inline:false, from: 'sample.css', to: 'prefixed.css'});      
rtlcss().process(result.css, {map:{prev:result.map.toJSON()}, from: 'prefixed.css', to: 'prefixed.rtl.css'});
```

**Comment by ai** [comment]
The best was is:

```js
postcss([autoprefixer, rtlcss]).process(data, { map: true, from: 'sample.css', to: 'prefixes.css' });
```

You parse CSS twice. If you will use one `process` for 2 plugins it will be about 1.5 times faster.

**Comment by MohammadYounes** [comment]
True if I'm only using postcss plugins, unfortunately this is not the case with webessentials. Nevertheless I think the exposed map property should not be the internal map object.

**Comment by ai** [comment]
Just put all PostCSS transformation closer to ech other:

1. Sass
2. Autoprefixer
3. RTLCSS
4. other PostCSS
5. non-PostCSS transforms

**Comment by ai** [comment]
But yes, `result.map` is optional.

**Comment by MohammadYounes** [comment]
It's not that simple! The transformations are user selectable and each one exists in its own wrapper. @am11 I believe they should use specific versions in order to keep the wrappers compatibility.
