### ISSUE TITLE
Have you a plan to make plugin for VS Code? 

### ISSUE THREAD

**Issue by GriNAME** [postcss/postcss#982]
Now we have a very useful plugin for Atom **language postcss** by **azat-io** . Any plans about a plugin for VS Code?
Anyway thanks in advance!))

**Comment by ai** [comment]
Hi. All current editor plugins are community made. So there is no sense ti ask in core module ;).

Ask in VS Code community. Or you can try to create own plugin. In Atom they take SCSS plugin and improve it for PostCSS.
