### ISSUE TITLE
how can i make my own pack

### ISSUE THREAD

**Issue by shirleyMHao** [postcss/postcss#983]
Is there a way to make my own plugin pack ?

**Comment by hzlmn** [comment]
Hi, what do you mean by "plugin pack". Do you want to create you own plugin for `postcss`?

**Comment by ai** [comment]
@shirleyMHao Hi. Sure. We don’t have How To article right now. Just make a npm package like this:

```js
module.exports = function (options) {
  return new postcss([
    plugin1(options.a),
    plugin2(options.b)
  ])
}
```
