### ISSUE TITLE
Line endings are not preserved

### ISSUE THREAD

**Issue by jakelauer** [postcss/postcss#992]
[test.zip](https://github.com/postcss/postcss-cli/files/845161/test.zip)

I would like my original line endings style to be preserved by postcss. I have a file using the CR+LF line ending style ("\r\n"):

![input](https://cloud.githubusercontent.com/assets/3980400/23957547/e1fc7210-095c-11e7-964b-76221a3e5c38.png)

but when it is processed by postcss, those line endings are converted to just LF ("\n"). 

![output](https://cloud.githubusercontent.com/assets/3980400/23957554/ec88ffa0-095c-11e7-89fe-ffcc3d4de9f1.png)

The zip file shows an example of input (file.css) and output (file-o.css).

**Comment by ai** [comment]
What plugins do you use?

You have same problem even without any plugins?

**Comment by jakelauer** [comment]
Ahh, looks like it is a plugin, my fault. Stylefmt is causing it.

**Comment by ai** [comment]
No problem 😊
